### ISSUE TITLE
Output header meanings

### ISSUE THREAD

**Issue by iremtll** [jts/nanopolish#1000]
Hello,

I'm a newbie trying to find moifications in RNA. I have a quick question about the eventalign output header explainations. Could you please tell me what do the following headers mean and from which input data they are collected?:

read_index 
start_idx 
end_idx

Thanks a lot!

**Comment by jts** [comment]
Hi,

`read_index` is simply a counter of the number of reads that eventalign processed. Read index `i` means it was the `i`-th record in the bam file. You can use the `--print-read-names` option to get the actual read name instead.

`start_idx`/`end_idx` are the index of the first and last sample (from the raw signal) aligned to this reference k-mer.

I hope that helps!
Jared
