### ISSUE TITLE
eventalign --models-fofn

### ISSUE THREAD

**Issue by hd2326** [jts/nanopolish#1005]
Greetings!

As I am trying to run eventalign with alternative k-mer models provided in the r9-models folder:

**~/nanopolish/nanopolish eventalign --reads test.fa --bam test.sorted.bam --genome test.fa --threads 8 --models-fofn ~/nanopolish/etc/r9-models/r9.4_450bps.cpg.6mer.template.model --scale-events > test.tsv**

I got the following error:

**Error: unknown model:**

It seems that the model cannot be read. Any insights into the issue? Thank you very much!

**Comment by jts** [comment]
Hi,

You do not need to provide the models, nanopolish will choose the model for
you.

Jared

**Comment by hd2326** [comment]
Thank you so much for the quick response Jared! So there is no way to use alternative k-mer models for eventalign, right?

**Comment by jts** [comment]
You can but it is an "advanced feature", which means it is poorly documented :)

The "--model-fofn" option takes in a file-of-filenames (fofn) - try putting the paths to models you want to load into a file called "models.fofn", then pass that in.

**Comment by hd2326** [comment]
It works! Thank you so much Jared!
