### ISSUE TITLE
Can you restart nano polish?

### ISSUE THREAD

**Issue by yamkela-mg** [jts/nanopolish#1008]
Hi there, 

I am running nano polish with this command:

python3 nanopolish_makerange.py draft.fa | parallel --results nanopolish.results -P 20 \
    nanopolish variants --consensus -o polished.{1}.vcf -w {1} -r reads.fa -b reads.sorted.bam -g draft.fa -t 56 --min-candidate-frequency 0.1

1) I am polishing a plant genome (1.2 GB) and it's taking more than a week, is this normal? Is there a way to speed it? 

2) If the polishing job gets killed because it has exceeded the set wall time, is there a way of restarting? If I re-run it in the same directory as the previous run, will it continue or start from the beginning?

**Comment by jts** [comment]
HI @yamkela-mg,

I don't recommend nanopolish for polishing genome assemblies anymore, medaka gives consistently better results. If you with to continue your nanopolish run I would suggest checking which .vcf files are complete (perhaps using the job's exit status), then remove any incomplete .vcf files and wrapping the commands in a shell script that only runs nanopolish if the target .vcf file does not exist.

I hope this helps.
Jared
