### ISSUE TITLE
unable to make on cygwin

### ISSUE THREAD

**Issue by hilasharim** [jts/nanopolish#101]
Hi,

I am trying to install nanopolish on windows via cygwin.
gcc version is 4.9.3.

When trying to make I get the following error:

g++ -o src/nanopolish_call_variants.o -c -g -O3 -std=c++11 -fopenmp -I./include -I./htslib -I./fast5/src -I./src -I./src/hmm -I./src/thirdparty -I./src/common -I./src/alignment -fPIC src/nanopolish_call_variants.cpp
src/nanopolish_call_variants.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 //---------------------------------------------------------
 ^
In file included from ./src/hmm/nanopolish_profile_hmm.h:16:0,
                 from src/nanopolish_call_variants.cpp:30:
./src/hmm/nanopolish_emissions.h: In function ‘float log_invgauss_pdf(float, float, const PoreModelStateParams&)’:
./src/hmm/nanopolish_emissions.h:59:42: error: ‘M_PI’ was not declared in this scope
     static const float log_2pi = log(2 * M_PI);
                                          ^
Makefile:104: recipe for target 'src/nanopolish_call_variants.o' failed
make: *** [src/nanopolish_call_variants.o] Error 1

Do I need to change something so it will work?
Thank you

**Comment by jts** [comment]
Hi,

I'm sorry but Windows/Cygwin is not a supported platform right now. I suggest you install ubuntu on a virtual machine to run nanopolish.

Jared
