### ISSUE TITLE
Nanopolish works on test data, but not my new basecalled data

### ISSUE THREAD

**Issue by ChristopherRichie** [jts/nanopolish#1010]
I am new to nanopolish.
I am using it on NIH Biowulf with the following modules:
  1) singularity/3.8.5-1   2) guppy/6.1.2   3) seqkit/2.1.0   4) gcc/7.4.0   5) nanopolish/0.13.2   6) samtools/1.15   7) minimap2/2.24   8) java/12.0.1   9) igv/2.12.3

I ran though the chr20 test data from the https://nanopolish.readthedocs.io/en/latest/index.html, and I got it to work.

I acquired data with a MinION Mk1C, flongle, and rapid barcoding kit (I have attached a screenshot of my MinION report).
I used guppy with the dna_r9.4.1_450bps_sup.cfg.

when I try to use my data, I am able to run the index operation without any apparent error:
[readdb] indexing ./BC07_fast5/
[readdb] num reads: 158, num reads with path to fast5: 158

but when I try to call-methylation, I get a lot of errors:

[chrisr@cn2374 39883855]$ nanopolish call-methylation -t 8 -r $OUTPUT_FQ -b output.sorted.bam -g $REF -w "CR3055_polished1_ref.fa" > methylation_calls.tsv
[bam process] iterating over region: CR3055_polished1_ref.fa
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 46912521406208:
  #000: H5Dio.c line 173 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: H5Dio.c line 550 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: H5Dchunk.c line 1872 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: H5Dchunk.c line 2902 in H5D__chunk_lock(): data pipeline read failed
    major: Data filters
    minor: Filter operation failed
  #004: H5Z.c line 1357 in H5Z_pipeline(): required filter 'vbz' is not registered
    major: Data filters
    minor: Read failed

[ ... ]
![CR3055_MinION_details](https://user-images.githubusercontent.com/74983235/169144613-2df35e8f-085a-4a12-a1cb-46b256f2e5c9.jpg)

I am guessing that this is some incompatibility with my fast5 files.
Any suggestion for what to try next ?
Is there a work around?

thanks
chris

**Comment by jts** [comment]
Hi,

Sorry for the slow response. This is because the VBZ plugin is not loaded. Please see here for instructions to fix it: https://github.com/jts/nanopolish/issues/725#issuecomment-582932080

Jared

**Comment by ChristopherRichie** [comment]
THANKS, I will give it a try.
I did a search on the nanopolish github, but I guess I should have searched github (globally) or in the google.

thanks!

From: Jared Simpson ***@***.***>
Sent: Friday, May 20, 2022 3:45 PM
To: jts/nanopolish ***@***.***>
Cc: Richie, Christopher (NIH/NIDA) [E] ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [jts/nanopolish] Nanopolish works on test data, but not my new basecalled data (Issue #1010)


Hi,

Sorry for the slow response. This is because the VBZ plugin is not loaded. Please see here for instructions to fix it: #725 (comment)<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjts%2Fnanopolish%2Fissues%2F725%23issuecomment-582932080&data=05%7C01%7Cchrisr%40nida.nih.gov%7Ca3aa35e1e0794949abe708da3a993e49%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637886727095500544%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yDASyoPIK2cVf%2FXhXMYrMHn%2BnSDvEhBGNO8b%2BVymHaI%3D&reserved=0>

Jared

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjts%2Fnanopolish%2Fissues%2F1010%23issuecomment-1133268018&data=05%7C01%7Cchrisr%40nida.nih.gov%7Ca3aa35e1e0794949abe708da3a993e49%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637886727095500544%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PiVT5%2FfQWc61M3QsNaYigMmDxE5tOU%2F91MMRnewzf0Y%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAR4COQ2YEPNJSRTKND7LHL3VK7TT3ANCNFSM5WJSNMQQ&data=05%7C01%7Cchrisr%40nida.nih.gov%7Ca3aa35e1e0794949abe708da3a993e49%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637886727095500544%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jZwF0yKLUwV7YhsP1%2BgPZ7s04u%2FJSUJT15HJeJiLKrg%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.
