### ISSUE TITLE
bash: nanopolish: command not found

### ISSUE THREAD

**Issue by shafijcsmr** [jts/nanopolish#1015]
Hi I have run the command nanopolish index -d fast5_files/ reads.fasta but it shows that

bash: nanopolish: command not found
I am using Manjaro

**Comment by hasindu2008** [comment]
Did you compile nanopolish from source or installed through conda or something?
If you compiled from source, you will have to set the PATH variable to point the nanopolish binary. Or else invoke with the path, e.g., /path/tp/nanopolish
