### ISSUE TITLE
HDF5 problem

### ISSUE THREAD

**Issue by najohink** [jts/nanopolish#1016]
Hello, I am trying to run nanopolish in Google Colab Notebooks and running into a HDF5 issue similar to those previously reported but slightly different. I'm guessing because I'm in Google Colab's virtual environment and others were not? Anyways, when I run: 

```
git clone --recursive https://github.com/jts/nanopolish.git
cd /content/nanopolish
make

```
I get something that looks like this: 
[nanopolish_make_log.txt](https://github.com/jts/nanopolish/files/8835854/nanopolish_make_log.txt)

It starts out seemingly ok, then I get a super long list of errors that looks like this:

> In file included from H5public.h:37:0,
>                  from H5private.h:29,
>                  from H5.c:24:
> /usr/include/features.h:184:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
>  # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
>    ^~~~~~~
> In file included from H5.c:27:0:
> H5Eprivate.h:35:32: warning: anonymous variadic macros were introduced in C99 [-Wvariadic-macros]
>  #define HERROR(maj_id, min_id, ...) H5E_printf_stack(NULL, __FILE__, FUNC, __LINE__, H5E_ERR_CLS_g, maj_id, min_id, __VA_ARGS__)
>                                 ^~~
> In file included from H5.c:27:0:
> H5Eprivate.h:41:33: warning: anonymous variadic macros were introduced in C99 [-Wvariadic-macros]
>  #define HCOMMON_ERROR(maj, min, ...)                    \
>                                  ^~~
> H5Eprivate.h:55:40: warning: anonymous variadic macros were introduced in C99 [-Wvariadic-macros]
>  #define HDONE_ERROR(maj, min, ret_val, ...) {          \
>                                         ^~~
> H5Eprivate.h:67:40: warning: anonymous variadic macros were introduced in C99 [-Wvariadic-macros]
>  #define HGOTO_ERROR(maj, min, ret_val, ...) {          \
>                                         ^~~

Things I tired:
1) I tried it on Ubuntu 20.04.4 LTS, still got errors/warning like those above.
2) I tried to install HDF5 myself and then use HDF5=noinstall during the make command, but that did not work either.
3) I thought maybe the above warnings aren't actually errors, and that I should just go for it and see if nanopolish will do anything to my data... so I went for it and got the same "vbz plugin not found" as others did in the past. Even with trying the different export commands, the only way I was able to get nanopolish to run was if i ran it like this:

`HDF5_PLUGIN_PATH=/content/ont-vbz-hdf-plugin-1.0.1-Linux/usr/local/hdf5/lib/plugin/ /content/nanopolish/nanopolish index -s supoutdir/sequencing_summary.txt -d /fast5dir supoutdir/all_D1.fastq`

In the end, from `nanopolish eventalign` I got:

> [post-run summary] total reads: 138255, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 138255, bad fast5: 0

Questions I have:

1) Any suggestions for installing on Google Colab? Or ubuntu? 
2) I noticed in the nanocompore pipeline, they do the minimap2 and samtools steps before running nanopolish index... whereas the nanopolish manual does the nanopolish index step first, does that matter?
3) I used a 10.4 flowcell, how will that effect my ability to use nanopolish? or how would it affect my data?

Thank you in advance for reading over my issues and questions.

best,
S

**Comment by jts** [comment]
Hi,

The normal HDF5 build produces a large number of warnings that you can ignore. I noticed the end of the make log contains this message:

```
make: *** [lib/libhdf5.a] Interrupt
```

Did you press ctrl+c to interrupt the build?

**Comment by jts** [comment]
No problem, good luck!

**Comment by DelphIONe** [comment]
Hi Jared,

I usually use Nanopolish, it's a great tool, thanks for this!
Today, I obtain some surprising results of type :
[post-run summary] total reads: 8135, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 8135, bad fast5: 1941
[post-run summary] total reads: 7845, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 7845, bad fast5: 2011
...

For the first time, the sequencing has been done on 10.4 flowcell, is it the source of problem ?
Do you have any idea when Nanopolish will be able to work with ? Or maybe, you think it's useless since 10.4 flowcell is supposed to be of good quality ?

Thanks for your reply

**Comment by jts** [comment]
Hi @DelphIONe,

Currently nanopolish does not support R10.4 data, so you will have to use another approach (medaka/clair3/guppy+remora) depending on your application.

Jared

**Comment by DelphIONe** [comment]
ok but... why ? (It's for polishing an assembly)
It's not planified ?

**Comment by DelphIONe** [comment]
ok, it seem's logical :-)
Thanks again !

**Comment by PanZiwei** [comment]
Hi,
Any recommendation about the "good tools available for R10.4"? Are you referring to Megalodon? Thank you!
