### ISSUE TITLE
VCF file with header but no variants, no post-run summary output

### ISSUE THREAD

**Issue by chris-toomajian** [jts/nanopolish#1019]
I've run nanopolish variants --consensus for my assembly.
For 1 small contig (< 90kb) that has 23 reads mapping to it, a vcf file is created with the header, but with no variants present.
And, there is no post-run summary output included here as well.
For all other contigs, there are no problems (VCFs with plenty of variants, clear run logs reporting on the status of the reads).

I noticed in another post Jared asked whether a reportedly empty VCF was a case of a missing file (or an empty file with no header), or a file created but with no variants (like in my case) - but the answer was the former. I couldn't find a discussion of what it means when the vcf file is created and header printed, but without variants.
Am I correct to guess that nanopolish could not accurately predict any required edits?

**Comment by jts** [comment]
Hi Chris,

>And, there is no post-run summary output included here as well.

This means the program did not finish correctly, so it likely means there was an error (or perhaps it hung?)

**Comment by chris-toomajian** [comment]
Thanks for the quick reply. 
I am at a loss, what to try differently to prevent the error or hanging (it is very repeatable). Do you have any suggestions?

I am running this on my university computer cluster, the submitted job completes in seconds. I am running it on 1 thread, 1 cpu, and requesting 50G or 80G, still no difference. I don't think the memory requirement should be an issue, since it is a relatively short sequence and few reads mapping to it.

**Comment by jts** [comment]
I agree it is unlikely to be memory. Does the process terminate (return to the shell prompt), or does it run indefinitely?

**Comment by chris-toomajian** [comment]
Yes, I forgot to mention, the job completes (jobs are submitted with sbatch to a slurm job manager, returns COMPLETED). The last time I tried, it reaches completion in 9 seconds. 
Is there some way I can force nanopolish to provide more information on what has happened, more log information?

**Comment by jts** [comment]
Ah, is it possible the post-run summary message has been sent do a different log file (it is written to stderr, not stdout)?

**Comment by chris-toomajian** [comment]
Running nanopolish directly on the headnode of the system gives the same result (no output to terminal before shell prompt returns, creates vcf file and writes the header, but nothing else). Had been running version 0.13.2, but error persists with version 0.13.3 (I believe latest that is installed on the computer cluster)

**Comment by chris-toomajian** [comment]
Thanks - I did this on the headnode and the following printed to the screen:
input region: GA....[MUCH MORE] ... AGGGT
Round 0
==== Starting variant screening =====

Then the terminal prompt returns. 

Would be nice to figure out the bug, but if not, this portion of my Canu assembly may not be well supported by nanopore reads to begin with - I may just drop it (or proceed without polishing it), and move on to using Pilon, then downstream analyses.

**Comment by jts** [comment]
I just remembered that nanopolish won't print the summary message if there are no usable reads in the region. My guess is the process ran correctly but nothing useful could be done with this region.

**Comment by chris-toomajian** [comment]
Ok, that would explain it then - and resolves my issue satisfactorily.
If you could, please give a short summary of what 'no usable reads in the region' basically translates to? I think that Canu had 1 read supporting the contig (i believe we used a subset of all reads, since we had >80x predicted coverage), but then the minimap bam file had 23 reads that mapped to some extent, as I indicated in my original post.
Thanks!

**Comment by jts** [comment]
Nanopolish performs internal QC on the reads to see whether the signal data is readable and can aligned back to the basecalled read with sufficient accuracy. The reads that fail these checks are deemed not usable. I _think_ there is also a mapping quality threshold (20?)
