### ISSUE TITLE
M1 compile error

### ISSUE THREAD

**Issue by pr0kary0te** [jts/nanopolish#1021]
Hi I can see that M1 Mac compilation issues have been raised before, but the release notes in the README suggests m1 support has been added as of  0.14.0.  However, I get these warnings and errors (multiples for each) on my m1 MacBook Pro (14" 2021 OSX 12.4 Monterey)

clang: error: unsupported option '-fopenmp'
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
make: *** [.depend] Error 1

A fix would be appreciated if it is possible.
Thanks
Gary

**Comment by jts** [comment]
Hi,

The M1 build should work but it requires using gcc instead of clang. Could you try installing gcc (perhaps through homebrew or conda) then issue this make command: `make CC=gcc-11 CXX=g++-11` (assuming you installed gcc-11)

**Comment by pr0kary0te** [comment]
Thanks for the speedy reply, unfortunately I still have problems with he m1 install.
I installed gcc-11 OK with home-brew:

brew install gcc
which gcc-11
/opt/homebrew/bin/gcc-11

Note I previously installed **wget** as well as this is required but not standard:
brew install wget

As suggested, I then used:
make CC=gcc-11 CXX=g++-11


I'm now getting a load of htslib errors of which I've pasted just a few below:


compilation terminated.
src/alignment/nanopolish_eventalign.cpp:23:10: fatal error: htslib/faidx.h: No such file or directory
   23 | #include "htslib/faidx.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/io/nanopolish_fast5_processor.h:15,
                 from src/io/nanopolish_fast5_processor.cpp:10:
./src/nanopolish_read_db.h:14:10: fatal error: htslib/faidx.h: No such file or directory
   14 | #include "htslib/faidx.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/basemods/nanopolish_basemods.cpp:9:
src/basemods/nanopolish_basemods.h:13:10: fatal error: htslib/faidx.h: No such file or directory
   13 | #include "htslib/faidx.h"

**Comment by jts** [comment]
It looks like you forgot the `--recursive` flag during `git clone`, could you re-try the clone command then build?

**Comment by pr0kary0te** [comment]
Thanks, that worked!
Gary

Summary:

brew install gcc
git clone --recursive https://github.com/jts/nanopolish.git
cd nanopolish
make CC=gcc-11 CXX=g++-11

**Comment by jts** [comment]
No problem!
