### ISSUE TITLE
eventalign no skip 

### ISSUE THREAD

**Issue by xieyy46** [jts/nanopolish#1023]
Hi nanopolish team! I wonder if there are any settings to prevent skip as showed below when using nanopolish eventalign? As you know, eventalign assigns events to bases accoding to reference,; every bases should have its event when sequencing.
![image](https://user-images.githubusercontent.com/76148123/181764130-2ccceb3b-c104-4449-8216-a63c2ad2a49d.png)

**Comment by jts** [comment]
Hi,

Unfortunately this isn't possible, the skip state is a necessary part of the HMM.

Jared
