### ISSUE TITLE
Removing print statements in EventAlign

### ISSUE THREAD

**Issue by najohink** [jts/nanopolish#1024]
Hello,

I am working in Google Colab and trying to use nanopolish with r9.4.1-generated data, but I run into the following message when running the `eventalign` command:

```
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
--NotebookApp.iopub_data_rate_limit.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)
```

Based on what I found online about this issue, I have concluded that nanopolish is trying to print a lot more (or faster?) than the Colab notebook allows. Suggestions elsewhere have told OPs to just change their script to no longer print everything. 

So here is my question: 
Is there a way I can change the `eventalign` script to not print everything? Can it just be written to a file, or not displayed so that google colab's data rate limit is not continuously triggered? Thanks in advance for any help/insight you may have!

best,
S

**Comment by najohink** [comment]
I have found that adding `%%capture` at the start of my code will hide the output and resolves that data rate issue, but now am wondering if that will have any effect on the command/further analysis? Is everything that is printed during EventAlign just for the user to see what is happening? Sorry if that is a super basic question about how print works!

**Comment by jts** [comment]
Hi,

The prints to stdout is the primary output of eventalign and expected to be consumed by some downstream tool. What are you trying to do with eventalign?

Jared

**Comment by najohink** [comment]
Thanks for clearing that up. I was just trying to align squiggles to a reference so I can look and see what is happening at certain positions (eventually). I assumed eventalign would save something that I can that use for the next step in my pipeline. I should have known considering there is no --output flag.

I appreciate you taking the time to answer my (dumb) question!

best,
S

**Comment by jts** [comment]
No problem, glad to help.

Jared
