### ISSUE TITLE
Index slow5 files

### ISSUE THREAD

**Issue by Tomcxf** [jts/nanopolish#1025]
I used slow5tools to convert fast5 to slow5, and then convert back.
When I print 
`nanopolish index reads.fq --slow5 signals.blow5`
I found the output xxx.index.readdb, it show that

1 *       /home/chenxf/wheat/mutant1/slow5/mutant1.blow5

I use it to handle direct RNA, so I have to use the converted fast5 to basecall.
But when I use converted fast5 to index, it work.
I don't know what the key is. I have update it to 0.14.0
By the way, I found sometimes there is no information type on the screen when index. I don't know if it is an error.
Thanks!

**Comment by hasindu2008** [comment]
Hi, did you mean that when you index converted fast5 it does NOT work? What's do you mean by 'key'? 

Nanopolish index doesn't print any live status messages when indexing. If it doesn't print it means it is doing indexing usually. Note that indexing fast5 takes a magnitude of time compared to indexing slow5, do you might have to wait and see for a few hours if it completes.

**Comment by hasindu2008** [comment]
And wait, did you say basecall? Nanopolish cannot basecall as far as I am aware. You need something like Guppy basecaller for basecalling. What basecalling doesn't need an index

**Comment by Tomcxf** [comment]
maybe I don't explain clearly.
I first transfer fast5 to slow5 and then convert back. I use guppy to basecall the converted fast5.
When I use nanopolish index using slow5 as guided, the output index. readdb show nothing.
When I use the converted fast5 to index, it works well. So I don't know why slow5 index fail.
By the way, the former version index have the message on screen like ‘indexing    bala bala... document’and maybe the new version delete it

**Comment by hasindu2008** [comment]
Do you mean that when you call the command nanopolish index reads.fq --slow5 signals.blow5 the readdb file is empty? Or does it have a single raw?  Also check if a file called signals.blow5.idx has been created?

**Comment by Tomcxf** [comment]
it has just one raw

1 * /home/chenxf/wheat/mutant1/slow5/mutant1.blow5

Is it normal?
When I use this index to nanopolish polya
the result show all is -1.0
and the last column are all READ_FAILED_LOAD
the idx has been created

**Comment by hasindu2008** [comment]
Yeh. That single raw is normal. This is the polyA program I believe? This
issue of -1 was fixed very recently (after v0.14.0 release). Would you be
able to build Nanopolish from the latest commit in master branch in github?

Hasindu Gamaarachchi

**Comment by Tomcxf** [comment]
Excuse me, when I use 'make' to install  nanopolish from github, I met an error 
`fatal error: htslib/faidx.h: No such file or directory 
make: *** [.depend] Error 1`
I don't know if it is website error or permission deny or something else
Thank you

**Comment by Tomcxf** [comment]
Maybe I think the biggest issue is the website. So could you please upload the binary file can use it directly without make? 
Thank you!

**Comment by hasindu2008** [comment]
A binary built on CentOS 7 is here, not sure if it will work due to your libc version.
[nanopolish.tar.gz](https://github.com/jts/nanopolish/files/9256504/nanopolish.tar.gz)

The instructions for the building are here, looks like you missed the --recursive flag
https://github.com/jts/nanopolish#installing-the-latest-code-from-github-recommended

**Comment by Tomcxf** [comment]
Thank you for your help!
I am really excited you have invented such a high effective tools for ONT. I think it will exactly change the latter analysis method for ONT.
Thanks for you distribution!

**Comment by Tomcxf** [comment]
Oh，by the way, I wanna to ask another question.
As the guidance said, slow5 can accelerate the progress of nanopolish index
I just wonder if slow5 can accelerate other nanopolish command, such as nanopolish eventalign
Thanks!

**Comment by hasindu2008** [comment]
Yes. It will make any tool that access signal data much faster.

**Comment by Tomcxf** [comment]
Thanks！
I saw the nanopolish eventalign needs fastq and bam files. So which part of slow5tools can accelerate this progress? Just because index blow5?  Only using the fast5 converted by  slow5tools (fast5>slow5>fast5)  can I speed up eventalign? Or the fastq basecall from raw fast5 can get the same speed.
By the way, I just wonder if you have test the time cost for eventalign. Because I run this command too much time, I don't know whether it is normal. My raw fast5 file is in 134Gb. It has cost me nearly a week to eventalign. Thank you!

**Comment by hasindu2008** [comment]
If you run nanopolish index with the --slow5 option, the subsequent commands like eventalign will use the corresponding blow5 file you gave as input to the nanopolish index. Depending on the underlying disk system, using blow5 can have a 2 to 5x speedup.  You can see the example commands for using nanopolish with slow5 here:
https://hasindu2008.github.io/slow5tools/workflows.html

If you have many CPU cores (more than 16) or GPUs, you can also try f5c eventalign https://github.com/hasindu2008/f5c/, which gives same results as nanopolish eventalign which also can use slow5 as in the example in https://hasindu2008.github.io/slow5tools/workflows.html

**Comment by Tomcxf** [comment]
Thank you!
By the way, will "f5c eventalign" faster than "nanopolish eventalign" ?
Thanks!

**Comment by hasindu2008** [comment]
If you compare nanopolish event align on slow5 with f5c event align on slow5, f5c will be a couple of times faster on a many core CPU or GPU.

**Comment by Tomcxf** [comment]
Well, I test f5c to index, it really faster than before. It works!
but when I use f5c to eventalign, it print out on screen:
[E::faidx_adjust_position] The sequence "NM_001035539.1" not found
[E::faidx_adjust_position] The sequence "NM_001035539.1" not found
......
[get_rank::WARNING] A None ACGT base found : U
[get_rank::WARNING] A None ACGT base found : U
[get_rank::WARNING] A None ACGT base found : U
......
Now it has run two hours, and there is nothing written in output file
I don't know what's wrong with it. Or it is just normal.
Thank you!

**Comment by hasindu2008** [comment]
Hi could you open this issue under f5c repo?

**Comment by Tomcxf** [comment]
ok
