### ISSUE TITLE
nanopolish error too many argument

### ISSUE THREAD

**Issue by krishnakazama** [jts/nanopolish#1027]
python3 /home/niabguest/krishna/apps/nanopolish/scripts/nanopolish_makerange.py /home/niabguest/krishna/hyl2_basecalling/canu_assembly/trim_assembly/assembly_small/assembly.contigs.fasta | parallel --results /home/niabguest/krishna/apps/nanopolish/scripts/nanopolish.results -P 7 /home/niabguest/krishna/apps/nanopolish/nanopolish variants --consensus -o /home/niabguest/krishna/hyl2_basecalling/polishing/nanopolishing/polish.{1}.vcf -w {1} -r /home/niabguest/krishna/hyl2_basecalling/polishing/nanopolishing/1D_mapping/basecall.fastq.gz -b /home/niabguest/krishna/hyl2_basecalling/polishing/nanopolishing/mapping/samindex_mapping.sorted.bam.bai -g /home/niabguest/krishna/hyl2_basecalling/canu_assembly/trim_assembly/assembly_small/assembly.contigs.fasta t-14

I'm using the above command for polishing 
this is the error I'm getting-###  variants: too many arguments

**Comment by jts** [comment]
Hi,

Were you able to solve this? I don't see an obvious error, but you've provided the .bai file instead of the .bam file for the `-b` argument.

Jared
