### ISSUE TITLE
Nanopolish variant calling --consensus  number of variants in span (11) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes

### ISSUE THREAD

**Issue by krishnakazama** [jts/nanopolish#1028]
This is closely related to #501 but in my case, it is tick transcriptome 
I'm performing de novo assembly as I don't have a reference transcriptome.
I'm confused about whether to consider this message or not(the number of variants in span (11) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes).

the script I have used.
python3 ${nanopolish_makerange} ${assembly.fasta} \
    | parallel --results $nanopolish.results -P 7 ${thr} \
    nanopolish variants \
        --consensus \
        -o polished.{1}.vcf \
        -w {1} \
        -r ${basecalled.fasta} \
        -b ${reads.sorted.bam \
        -g ${assembly.fasta} \
        -t 4 \
        --min-candidate-frequency=0.01

Ready to provide further details also 
Please do suggest some ideas

**Comment by jts** [comment]
It is just a warning that you can ignore. Nanopolish is not designed for transcriptome data so it is unlikely to work well for this case, sorry.

**Comment by jts** [comment]
You can ignore this warning. Also just a note but nanopolish isn’t designed for transcriptome polishing and I doubt it will work well.
