### ISSUE TITLE
empty variants (nanopolish.results) file

### ISSUE THREAD

**Issue by zascavage** [jts/nanopolish#103]
I use:
 python /home/nanopore/nanopolish/scripts/nanopolish_makerange.py rCRS.fasta | parallel --results nanopolish.results -P 8 \ nanopolish variants --consensus polished.{1}.fa -w {1} -r sample.fasta -b sample.sorted.bam -g reference.fasta -e sample.eventalign.sorted.bam -t 4 --min-candidate-frequency 0.1 --models nanopolish_models.fofn 
to call variants and generate a consensus sequence. I am able to get a consensus every time, however, with results from the 1D rapid kits, the file with the list of variants is empty. I don't have this issue with results from the 2D kits. I have updated my version of nanopolish, and it doesn't seem to have helped. I tried changing --consensus to --snps, I tried running only nanopolish variants. I am no good at troubleshooting, as you know, so can you help me with a command that would give me the variant list? Thanks!

**Comment by jts** [comment]
Can you try adding a `-o` (output file) option to the command? I suggest:

```
python /home/nanopore/nanopolish/scripts/nanopolish_makerange.py rCRS.fasta | parallel --results nanopolish.results -P 8 \ nanopolish variants --consensus polished.{1}.fa -o polished.{1}.vcf -w {1} -r sample.fasta -b sample.sorted.bam -g reference.fasta -e sample.eventalign.sorted.bam -t 4 --min-candidate-frequency 0.1 --models nanopolish_models.fofn
```

**Comment by zascavage** [comment]
Unfortunately, that did not do it... it did change the output files though. Traditionally, the polished.gi file that is created has the consensus sequence in it. This time, it had the header of the nanopolish.results stdout, but just as the stdout file, there is nothing but a header.


It just seems odd that it is specific to the type of sequencing reaction. Both have had local basecalling, as well as metrichor basecalling, and that doesn't seem to make a difference. The 1d rapid result files will output all the correct files with data in them, and the 2d barcoded result files will not give me the list of variants, however it still complies a consensus sequence.


________________________________

**Comment by zascavage** [comment]
Hey Jared,
Sorry to keep bugging you about this, but is there something I am missing for compatibility with 1D reads? The more I think about it and try alternatives, I feel like this is what my issue boils down to. When I look in the help, it says --reads is for the 2D file where the ONT reads are located. I am also still working off a protocol that used bwa mem –x ont2d… etc. earlier in the pipeline for data extraction. Maybe this is where my problem is? I am not sure, so any other suggestions would be very helpful! I can also send you a data file and see if you can get it to work??

THANKS!


Roxanne R Zascavage
Post Doctoral Associate | Molecular and Medical Genetics
University of North Texas health Science Center | Office: CBH 356
3500 Camp Bowie Blvd | Fort Worth, TX 76107
817-735-2953
roxanne.zascavage@unthsc.edu<mailto:roxanne.zascavage@unthsc.edu>| www.unthsc.edu<http://www.unthsc.edu/>

**Comment by jts** [comment]
Are you using poretools to extract the reads from the fast5 files? Sometimes if there is a combination of metrichor and local basecalling applied to the fast5, it can cause problems. Could you try running `nanopolish extract` to export the sequences, then try your pipeline again?

**Comment by zascavage** [comment]
I was using poretools. I tried nanopolish extract, but it only gives me an empty file as well (at least for my 1D runs). It appears that is the issue: it is not compatible with 1D reads… Boo. Thanks for your help! I’ll keep an eye out for a 1D compatible update.


Roxanne R Zascavage
Post Doctoral Associate | Molecular and Medical Genetics
University of North Texas health Science Center | Office: CBH 356
3500 Camp Bowie Blvd | Fort Worth, TX 76107
817-735-2953
roxanne.zascavage@unthsc.edu<mailto:roxanne.zascavage@unthsc.edu>| www.unthsc.edu<http://www.unthsc.edu/>

**Comment by jts** [comment]
nanopolish extract should be compatible with 1D reads - what basecaller did
you use?

Jared

**Comment by zascavage** [comment]
The Nanopore local basecaller…


Roxanne R Zascavage
Post Doctoral Associate | Molecular and Medical Genetics
University of North Texas health Science Center | Office: CBH 356
3500 Camp Bowie Blvd | Fort Worth, TX 76107
817-735-2953
roxanne.zascavage@unthsc.edu<mailto:roxanne.zascavage@unthsc.edu>| www.unthsc.edu<http://www.unthsc.edu/>

**Comment by jts** [comment]
Ok, I think that might be the problem. Another user reported problems with
albacore basecalls, I'll look into it soon.

Jared

**Comment by zascavage** [comment]
Thanks! You’re amazing, by the way


Roxanne R Zascavage
Post Doctoral Associate | Molecular and Medical Genetics
University of North Texas health Science Center | Office: CBH 356
3500 Camp Bowie Blvd | Fort Worth, TX 76107
817-735-2953
roxanne.zascavage@unthsc.edu<mailto:roxanne.zascavage@unthsc.edu>| www.unthsc.edu<http://www.unthsc.edu/>

**Comment by jts** [comment]
Hi Roxanne,

The latest version should work with albacore basecalls.

Jared
