### ISSUE TITLE
Error during compilation - Make htscodecs.mk : No such file or directory

### ISSUE THREAD

**Issue by nicolo-tellini** [jts/nanopolish#1031]
Hi @jts, 

I followed the installation instructions but I ended up having a series of errors during the compilation.
I attach the file below. 

I am running on Ubuntu 18.04 x86_64

Thank you fro your time,

Nic

[install_nanopolish.err](https://github.com/jts/nanopolish/files/9394552/install_nanopolish.txt)

**Comment by jts** [comment]
Hi,

Sorry for the slow reply, I was on holidays. Can I see the `install_nanopolish.sh` script?

Jared

**Comment by jts** [comment]
I just tested this with a local build. The `htscodecs.mk: No such file or directory` message is expected (if the file is missing it will be generated by the build script). I don't see any other errors in the build log, can you check whether the `nanopolish` binary is available in the current working directory?

**Comment by nicolo-tellini** [comment]
Hi @jts ,

Yeah binaries are responsive. 

see below

```
rferretti@Thor:~/LRSDAY/build/nanopolish$ ./nanopolish index --help
Usage: nanopolish index [OPTIONS] -d nanopore_raw_file_directory reads.fastq
       nanopolish index [OPTIONS] --slow5 reads.blow5 reads.fastq
Build an index mapping from basecalled reads to the signals measured by the sequencer

      --help                           display this help and exit
      --version                        display version
  -v, --verbose                        display verbose output
      --slow5 FILE                     s/blow5 file (-d, -s, -f options below are only for fast5)
  -d, --directory                      path to the directory containing the raw ONT signal files. This option can be given multiple times.
  -s, --sequencing-summary             the sequencing summary file from albacore, providing this option will make indexing much faster
  -f, --summary-fofn                   file containing the paths to the sequencing summary files (one per line)

Report bugs to https://github.com/jts/nanopolish/issues
```

thank you for the help! 

best,


Nic
