### ISSUE TITLE
nanopolish/0.14.0 showing error while processing fast5 file

### ISSUE THREAD

**Issue by rezarahman12** [jts/nanopolish#1032]
Hi there,
I tried to use nanopolish/0.14.0 on direct RNA-seq data of nanopore with the below code:

module load nanopolish/0.14.0

nanopolish index -d /scratch/project_mnt/S0077/xPore/demo/data/HEK293T-METTL3-KO-rep1/fast5 /scratch/project_mnt/S0077/xPore/demo/data/HEK293T-METTL3-KO-rep1/fastq/basecalled.fastq
nanopolish eventalign --reads /scratch/project_mnt/S0077/xPore/demo/data/HEK293T-METTL3-KO-rep1/fastq/basecalled.fastq \
--bam /scratch/project_mnt/S0077/xPore/demo/data/HEK293T-METTL3-KO-rep1/minimap_out/aligned.sort.bam \
--genome /scratch/project_mnt/S0077/xPore/Homo_sapiens.GRCh38.cdna.all.fa \
--signal-index \
--scale-events \
--summary /scratch/project_mnt/S0077/xPore/demo/data/HEK293T-METTL3-KO-rep1/nanopolish_tutorial_out/summary.txt \
--threads 32 > /scratch/project_mnt/S0077/xPore/demo/data/HEK293T-METTL3-KO-rep1/nanopolish_tutorial_out/eventalign.txt

The basecalling was done using guppy ont-guppy-cpu_6.0.1_linux64.
I hot the below error:
###############################################################################
[readdb] indexing /scratch/project_mnt/S0077/xPore/demo/data/HEK293T-METTL3-KO-rep1/fast5
[readdb] num reads: 302, num reads with path to fast5: 302
[post-run summary] total reads: 308, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 0

Can you please tell me how could I solve the error?
Best regards
Reza

**Comment by jts** [comment]
Hi,

Those are normal output messages from nanopolish, can you specify where the error is?

Jared

**Comment by rezarahman12** [comment]
> Hi,
> 
> Those are normal output messages from nanopolish, can you specify where the error is?
> 
> Jared

Hi Jared
Thank you so much for your kind reply. 
I understand now- it is normal output as I have obtained output files. 
Thank you for your time.
Best regards
Reza

**Comment by jts** [comment]
No problem!
