### ISSUE TITLE
problem about 'event' information used by nanopolish

### ISSUE THREAD

**Issue by Flower9618** [jts/nanopolish#1033]
Hi, thank you very much for sharing this very powerful tool.

As we all know, Nanopolish used HMM model to call methylation. And during this process, Nanopolish used the event information from .fast5, which is produced after sequencing. However, the new version of .fast5 files no loner contains event information. Furthermore, Nanopolish can run successfully despite the absence of event information. . So, I am wondering how Nanopolish do it.

Thank you very much.

**Comment by jts** [comment]
Hi @Flower9618,

I explain how we do this in this blog post: https://simpsonlab.github.io/2017/09/06/nanopolish-v0.8.0/ (in particular the 3rd paragraph)

**Comment by Flower9618** [comment]
> Hi @Flower9618,
> 
> I explain how we do this in this blog post: https://simpsonlab.github.io/2017/09/06/nanopolish-v0.8.0/ (in particular the 3rd paragraph)

Very clear. I learned a lot from it. Thank you very much.

**Comment by jts** [comment]
No problem, glad it was helpful
