### ISSUE TITLE
what is the default -q is not set

### ISSUE THREAD

**Issue by yinshiyi** [jts/nanopolish#1035]
is the default -q cpg? Thank you.
what is the sensitivity or specificity for dam,dcm (bacteria)?
In the paper https://www.nature.com/articles/nmeth.4184
It seems to focus on 5-mC in a CpG context .

-q, --methylation=STRING             the type of methylation (cpg,gpc,dam,dcm)

Thank you!

**Comment by jts** [comment]
It defaults to cpg. We haven't measured the accuracy of dam/dcm calling, it was mostly developed for methylation-aware polishing.
