### ISSUE TITLE
nanopolish output bam file with MM/ML tags

### ISSUE THREAD

**Issue by yinshiyi** [jts/nanopolish#1037]
I came across @jts 's package https://github.com/jts/mbtools
It seems convert the bam file with MM tags into TSV tables.
Currently it seems the nanopolish call-methlyation output the TSV tables.
I am curious if nanopolish call-methlyation can output bam file with MM tags.

I also across these related tickets
 https://github.com/samtools/hts-specs/issues/582
https://github.com/jts/nanopolish/issues/939
Thank you!

**Comment by jts** [comment]
Yes, version 0.14 can output mod bams by using the `--modbam-output-name` option.
