### ISSUE TITLE
Running index step with FAST5 in multiple subdirectories

### ISSUE THREAD

**Issue by rezarahman12** [jts/nanopolish#1038]
Hi Jared,

Hope you are doing well. It is not an issue but a query as I'm a bit novice in Linux systems. 

Previously, I ran the nanopolish on a small demo data where all the fast5 files (.fast5, .fast5) were in a single folder. But I downloaded nanopore dRNA-Seq data from the below website:

https://www.ebi.ac.uk/ena/browser/view/PRJEB40872?show=reads

with below command-
module load axel/2.17.11
axel ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR470/ERR4706156/HEK293T-WT-rep1.tar.gz

When I untar using tar -zxvf HEK293T-WT-rep1.tar.gz, I saw a folder "fast5" which has subfolders/directories named "0", "1", "10", "11",... (almost 164 subdirectories). These subdirectories contain .fast5 files. So, I can I move those .fast5 files/contents from those subdirectories "0","1", "10", "11", ... into directory "fast5" and run nanopolish. My below script should work if all .fast5 files are into the directory "fast5".

module load nanopolish/0.14.0

nanopolish index -d /scratch/project_mnt/S0077/xPore/rawdata/HEK293T-WT-rep1/fast5/ \
/scratch/project_mnt/S0077/xPore/rawdata/HEK293T-WT-rep1/fastq/HEK293T-WT-rep1.fastq.gz
nanopolish eventalign --reads /scratch/project_mnt/S0077/xPore/rawdata/HEK293T-WT-rep1/fastq/HEK293T-WT-rep1.fastq.gz \
--bam /scratch/project_mnt/S0077/xPore/rawdata/HEK293T-WT-rep1/minimap_out/aligned.sort.bam \
--genome /scratch/project_mnt/S0077/xPore/rawdata/Homo_sapiens.GRCh38.cdna.all.fa \
--signal-index \
--scale-events \
--summary /scratch/project_mnt/S0077/xPore/rawdata/HEK293T-WT-rep1/nanopolish_out/summary.txt \
--threads 32 > /scratch/project_mnt/S0077/xPore/rawdata/HEK293T-WT-rep1/nanopolish_out/eventalign.txt

I'm sorry for taking your precious time. I will be very grateful if you kindly advise me to solve this difficulty.

**Comment by jts** [comment]
Hi,

No problem at all. This dataset seems to use the older style of one fast5 per read (rather than the current 4000 reads per fast5). Nanopolish should be able to handle this though as it will recursively search through the subdirectories. Did the `nanopolish index` command work?

**Comment by rezarahman12** [comment]
Hi Jared,
Thank you so much for your prompt reply. I ran and it worked. But I would like to bring your kind attention to .er file after the job is finished. I pasted below a few last lines of the .er file. Is it normal? Thank you for your kind consideration. Best regards
Reza

... 
[readdb] indexing /scratch/project_mnt/S0077/xPore/rawdata/HEK293T-WT-rep1/fast5/20181120_0819_SHO_20112018_EmptyE2-9/fast5//102
[readdb] indexing /scratch/project_mnt/S0077/xPore/rawdata/HEK293T-WT-rep1/fast5/20181120_0819_SHO_20112018_EmptyE2-9/fast5//10
[readdb] num reads: 1040661, num reads with path to fast5: 88980
fast5 files could not be located for 951681 reads
[post-run summary] total reads: 79892, unparseable: 0, qc fail: 2903, could not calibrate: 179, no alignment: 48, bad fast5: 849809
