### ISSUE TITLE
Segmentation fault (core dumped) and Nanopolish took days to process some samples

### ISSUE THREAD

**Issue by kakuk9** [jts/nanopolish#1039]
Hi,

I use the exact same command and parameters to run nanopolish variants (v0.14.0) on samples from the same sequencing batch.
```
nanopolish variants \
	-g ${ref_seq} \
	-b ${bam} \
	-r ${input_fastq_dir}/${prefix}*.fastq.gz \
	-o ${output_vcf_dir}/${prefix_ref}_nanopolish.vcf \
	--ploidy 1 -t 2 --min-flanking-sequence 10 -x 1000000
```

There was a time, 3-5 samples per batch give me this "Segmentation fault      (core dumped)" error, and if I lowered the threads from 4 to 2, it would usually help. In addition, I also had problems with 2 samples, which it took days and >1 week for Nanopolish variants to run, and I had to end the process because it just simply took too long. My samples are viral amplicon reads (genome size: ~ 3kb).

**Comment by jts** [comment]
Given you sequenced viral amplicons it is likely the sequencing depth is excessively high. Try downsampling the .bam file to have 100-500x coverage.
