### ISSUE TITLE
disk quota exceeded in nanopolish

### ISSUE THREAD

**Issue by rezarahman12** [jts/nanopolish#1041]
Dear Jared,

I have downloaded a public dRNA-seq data consisting of fast5 (ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR470/ERR4706254/HEK293T-Mettl3-KO-rep1.tar.gz) and basecalled fastq files (ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR470/ERR4706158/HEK293T-Mettl3-KO-rep1.fastq.gz). Then, I ran a job using nanopolish with the below script. 

The output is also given below for your kind consideration. I will seek your opinion is it a normal output since I see a lot of bad fast5 file.
...
[readdb] indexing /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/fast5_dir/ko-rep1/20181121_1017_21112018_Sho_METTI3_10/fast5/221
[readdb] num reads: 1490210, num reads with path to fast5: 1113644
fast5 files could not be located for 376566 reads
[post-run summary] total reads: 981058, unparseable: 0, qc fail: 40158, could not calibrate: 1979, no alignment: 719, bad fast5: 337754

**The script of the job is given below:**

#!/bin/bash
#PBS -A UQ-QBI
#PBS -l select=1:ncpus=10:mem=50GB
#PBS -e /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/nanopol/ko-rep1
#PBS -o /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/nanopol/ko-rep1
#PBS -l walltime=72:00:00
#PBS -N nanopol_ko-rep1

cd $PBS_O_WORKDIR

module load nanopolish/0.14.0

nanopolish index -d /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/fast5_dir/20181121_1017_21112018_Sho_METTI3_10/fast5 /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/fastq_dir/ko-rep1/HEK293T-Mettl3-KO-rep1.fastq.gz
nanopolish eventalign --reads /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/fastq_dir/ko-rep1/HEK293T-Mettl3-KO-rep1.fastq.gz \
--bam /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/align/ko-rep1/aligned.sort.bam \
--genome /scratch/project_mnt/S0077/xPore/Homo_sapiens.GRCh38.cdna.all.fa \
--signal-index \
--scale-events \
--summary /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/nanopol/ko-rep1/summary.txt \
--threads 32 > /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/nanopol/ko-rep1/eventalign.txt

I do highly appreciate your time, help and cooperation. 
Kind regards
Reza

**Comment by jts** [comment]
Hi @rezarahman12,

Unfortunately I can't help with the quota issue, you'll have to ask your local IT for more storage. Regarding the "bad fast5" issue, you'll have to ask whether this is expected over at the xPore repository since they prepared and uploaded that data set.

Jared

**Comment by rezarahman12** [comment]
Thanks, Jared for the prompt reply.
