### ISSUE TITLE
Segmentation fault on m1 Mac

### ISSUE THREAD

**Issue by itslittman** [jts/nanopolish#1042]
I was previously using nanopolish in Rosetta. I finally got it to compile successfully and run natively on M1 max. But when I try to specify multiple threads when running Eventalign, it says "segmentation fault." It runs fine when the "t" argument is unused but I would like it to use more than 1/10th of my CPU.
Any suggestions/might it have been a compilation issue?

Noah

**Comment by jts** [comment]
Hi @itslittman,

Unfortunately multi-threading is not supposed on MacOS as the compilers don't support the OpenMP library that nanopolish uses. That said, it shouldn't seg fault in this case, so I'll look into why this happens.

Jared

**Comment by itslittman** [comment]
I compiled it with OpenMP enabled, using the gcc-12 in /opt/homebrew/bin. I don't think the issue is with the compilation; the issue is with HDF5. The pre-set link for the HDF5 install seems to be broken (404 not found), so I edited the Makefile to use my own HDF5. 

Since posting, I re-downloaded the repository and tried again, with proper HDF5 Lib and Include paths in the Makefile (the 1st time, I cobbled together .h files from various places I could find in my files (mostly python packages)). 

Nanopolish compiled successfully, and this time, when trying to multithread, I got a more helpful message: 
"You enabled multi-threading but you do not have a threadsafe HDF5
Please recompile nanopolish's built-in libhdf5 or run with -t 1"

Apparently, the default Homebrew HDF5 library is compiled with thread-safety disabled. The official HDF5 repo has instructions for compiling it with those options enabled, but given my lack of expertise, those directions might as well be written in ancient Minoan language. 

Noah

**Comment by itslittman** [comment]
@jts sorry forgot to tag you

**Comment by jts** [comment]
Ah sorry, I mis-remembered about OpenMP support on MacOS. Glad you were able to compile with gcc-12. Could you try the nanopolish Makefile while specifying a version of HDF5 that they haven't removed the source tarball?

```
make HDF5_VERSION=0.13.2 [other flags you've added]`
```

**Comment by itslittman** [comment]
That did it!! Amazing, thank you!
