### ISSUE TITLE
methylation calling in non-CpG context (CHG and CHH)

### ISSUE THREAD

**Issue by yusmiatiliau** [jts/nanopolish#1044]
Hello there,
I wonder if nanopolish methylation calling can call methylation in CHG and CHH context too in plant samples? Apologise if it can, and I just totally miss it. And if not, is there any plan in the near future to include this?

Thanks a lot

**Comment by jts** [comment]
Hi @yusmiatiliau,

Sorry for the slow response. This is currently not supported - there are other tools specifically for plants that you might be interested to try instead.

Jared
