### ISSUE TITLE
Indexing of FLO-MIN114 output fast5 files

### ISSUE THREAD

**Issue by assafgrw** [jts/nanopolish#1045]
Hello
Has anyone tried nanopolish on files generated with the new ONT chemistry V14?

Nanopoish seems to fail with the output files

**Comment by jts** [comment]
Hi @assafgrw,

Nanopolish does not currently support V14 chemistry.

Jared

**Comment by alexcritschristoph** [comment]
What is the suggested timeline on supporting V14?
