### ISSUE TITLE
Colons in split variants files/directory names

### ISSUE THREAD

**Issue by zephyris** [jts/nanopolish#105]
I had a bottle of a battle getting nanopolish running on the Linux subsystem for Windows, then similar issues using an NTFS-formatted data drive, because of the use of colons in the split file/directory names for variant calling.

I was able to get it running by altering the contig/coordinate delimiter (to a semicolon). Would you consider changing the delimiter for wider OS/file system support?

**Comment by jts** [comment]
Hi,

Could you give an example of the text with the delimiter that you'd like changed (just so I'm sure I understand which you're referring to)?

Jared

**Comment by zephyris** [comment]
Sure!

The window string for the section of the chromosome to process is defined as "ctg:start-end", eg: src/nanopolish_call_variants.cpp line 80.

Using nanopolish to generate a consensus sequence as shown in the readme uses
scripts/nanopolish_makerange.py to make window strings with a colon delimiting the contig and the chromosome coordinates, see lines 14 and 16.

On passing to parallelised nanopolish variants as in the readme, this leads to mkdir and file write errors on file systems not supporting colons in file names (i.e. Windows file systems) as the window string is used for file names. If I understand correctly, this can be changed by altering the window string to "ctg;start-end" and file name parsing by src/nanopolish_call_variants.cpp line 1009-1012 to split the contig from the coordinate range by ";".

Finally, scripts/nanopolish_merge.py loads and merges consensus fasta files using the colon delimiter, see line 70.

**Comment by jts** [comment]
Got it, thanks for clarifying. The `contig:start-end` convention is used many places in genomics (samtools, genome browsers, etc) so I'm very reluctant to change the delimiter for the window argument. The name of the output file (`--consensus <file>`) can be anything though, so perhaps you can wrap the call to `nanopolish variants` in a script that sanitizes the file name for the `--consensus` argument but leaves `-w` as is?
