### ISSUE TITLE
Tutorial broken dataset link

### ISSUE THREAD

**Issue by MmasterT** [jts/nanopolish#1050]
Hello,

I tried to follow the steps of the tutorial (https://nanopolish.readthedocs.io/en/latest/quickstart_consensus.html) but the test dataset link seems to be broken and I couldn't follow the steps.

#here is the link
wget http://s3.climb.ac.uk/nanopolish_tutorial/ecoli_2kb_region.tar.gz

#here the error message 
[test]--% wget http://s3.climb.ac.uk/nanopolish_tutorial/ecoli_2kb_region.tar.gz
--2023-01-09 16:46:29--  http://s3.climb.ac.uk/nanopolish_tutorial/ecoli_2kb_region.tar.gz
Resolving s3.climb.ac.uk (s3.climb.ac.uk)... 147.188.173.14
Connecting to s3.climb.ac.uk (s3.climb.ac.uk)|147.188.173.14|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://s3.climb.ac.uk/nanopolish_tutorial/ecoli_2kb_region.tar.gz [following]
--2023-01-09 16:46:29--  https://s3.climb.ac.uk/nanopolish_tutorial/ecoli_2kb_region.tar.gz
Connecting to s3.climb.ac.uk (s3.climb.ac.uk)|147.188.173.14|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-01-09 16:46:30 ERROR 404: Not Found.

is there any chance for you to provide a new toy dataset to verify the correct installation of the software?

Thanks!

**Comment by jts** [comment]
Hi,

The location of the data has moved, can you try

```
wget warwick.s3.climb.ac.uk/nanopolish_tutorial/ecoli_2kb_region.tar.gz
```

I'll update the link in the tutorial too.

jared

**Comment by bayraktar1** [comment]
Hello,

The linkt to the dataset for the methylation tutorial is broken.
https://nanopolish.readthedocs.io/en/latest/quickstart_call_methylation.html#download-example-dataset

`wget s3.climb.ac.uk/nanopolish_tutorial/methylation_example.tar.gz`

should be

`wget warwick.s3.climb.ac.uk/nanopolish_tutorial/methylation_example.tar.gz`

**Comment by DelphIONe** [comment]
Thanks !
