### ISSUE TITLE
No output in vcf

### ISSUE THREAD

**Issue by smf96** [jts/nanopolish#1051]
Hello,

I am trying to call SNVs from my nanopore data with the `variants` command (v0.13.3) and it's been working on my whole cohort apart from 1 sample and I can't figure out why.

After indexing I use the command:
```
nanopolish variants -d 27 -t 16 --ploidy 2 -w chr1:161450000-161750000 --reads $fastq --bam $bam --genome $genome -o ${output}.vcf
```

I think indexing is successful but the .vcf is empty and these were the only messages printed:
```
[readdb] indexing /mainfs/cansci/Sarah_Frampton/GUPPY_v6.0.1_basecalling_SUP/CRA93/CRA93_cas9_design2_run1/fast5_all/
[readdb] indexing /mainfs/cansci/Sarah_Frampton/GUPPY_v6.0.1_basecalling_SUP/CRA93/CRA93_AdaptSamp_run1/fast5_all/
[readdb] indexing /mainfs/cansci/Sarah_Frampton/GUPPY_v6.0.1_basecalling_SUP/CRA93/CRA93_AdaptSamp_run2/fast5_all/
[readdb] indexing /mainfs/cansci/Sarah_Frampton/GUPPY_v6.0.1_basecalling_SUP/CRA93/CRA93_AdaptSamp_run3/fast5_all/
[readdb] indexing /mainfs/cansci/Sarah_Frampton/GUPPY_v6.0.1_basecalling_SUP/CRA93/CRA93_AdaptSamp_run4/fast5_all/
[readdb] indexing /mainfs/cansci/Sarah_Frampton/GUPPY_v6.1.7_SUP_5mc/CRA93/CRA93_AdaptSamp_run5/fast5_all/
[readdb] num reads: 14856339, num reads with path to fast5: 14856339
Number of variants in span (18) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (21) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
slurmstepd-ruby049: error: *** JOB 1970772 ON ruby049 CANCELLED AT 2022-11-07T06:11:41 DUE TO TIME LIMIT ***
```

Since then I have tried:
- Increasing max haplotypes up to 100,000
- Increasing wall time to 40hrs, then 60hrs and then 120hrs
- Adding the --faster flag to minimise compute time	
- Adding the --snps flag to only identify SNPs
- Increasing minimum depth to 32x with -d
- Increasing threads to 32 with -t 
- Adding the --verbose option to try find out what the issue is

And still there is nothing in the .vcf and it appears to max out of time. 

Unfortunately the only messages that are printed in all these attempts is:
```
Number of variants in span (18) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (21) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
slurmstepd-ruby052: error: *** JOB 2342262 ON ruby052 CANCELLED AT 2022-12-24T05:47:15 DUE TO TIME LIMIT ***
```

It's also very strange the .vcf is completely empty, with not even the header being printed.

Any advice you have to help narrow down what's causing this problem or how to resolve it would be much appreciated. Thank you!

**Comment by jts** [comment]
Hi,

How large is the region that you're trying to variant call? What is the
sequencing depth?

Jared

**Comment by smf96** [comment]
Hello Jared,

Thank you for such a rapid response.

The window I specify in the nanopolish command is 300kb but my focus is the 200kb region shown in the IGV screenshot below. I just call variants for the 300kb to include flanking regions so I can try phase all the way across.

![image](https://user-images.githubusercontent.com/52749489/212286946-2730d456-62aa-4f95-a632-4e7264c1038e.png)

Average depth is about 140x. The reads distribution pattern may look a bit strange and that's because this sample has had both WGS and cas9-targeting performed on it and is suspected to harbour a large SV.

All the best,

Sarah

**Comment by jts** [comment]
So, the way nanopolish variant calling works is that it finds candidate variants (according to the thresholds listed in the help message), then groups these variants together by position and tries to enumerate all possible haplotypes for each group (controlled by `-x`). This seems to be quite a variable region, so the number of possible haplotypes is likely extremely high. The parameters to try are increasing `-m` to reduce the number of candidates, or _decreasing_ `-x` so it doesn't try all possible haplotypes. But really you might be better off using a program like clair3 that uses a different method of variant calling.

**Comment by smf96** [comment]
Great thank you,

So I tried changing `-x` to 500 which successfully ran in 6 minutes, producing 1172 SNVs in my `.vcf` and 10 of those `Number of variants in span (X) would exceed max-haplotypes` messages.

I also I tried changing `-m` to 0.25 and 0.3. Both successfully ran in about 30 mins producing 1066 and 876 SNVs respectively, with no max-haplotype messages. 

I'm now trying `-m` as 0.21, 0.22, 0.23 and 0.24 as I'd like this single sample to be as close to the rest of my cohort which worked with the default. Only 0.24 has completed in 33 mins, the rest have been running for >20hrs. I'm assuming they'll be like my original issue where they time out at 120hrs with nothing printed in the `.vcf`. 

I have also been trying to explain this process to my supervisor and was wondering if you are able to help clarify. Am I able to say that a form of polishing happens before the variants are called? Isn't that why the fast5 files are needed as well? Does that make this tool more accurate than simply using the bases in a pileup?

**Comment by smf96** [comment]
Brilliant thank you.

I was also wondering about filtering based on quality scores...

I have seen in a previous issue ([#405](https://github.com/jts/nanopolish/issues/405)) you commenting that scores of 20-50 aren't great. Are you able to elaborate further? Mine typically range from 20-5000 but can sometimes be nearer 20,000. Is that normal?

Thank you!

**Comment by jts** [comment]
The quality score depends on read depth. If you have high depth, and the ALT allele is much better supported than the REF allele, then a QUAL of >5000 isn't unexpected. If you have high depth and QUAL is 20, it means the REF and ALT are very difficult to separate in signal space. In general `QUAL / TotalReads` is a good measure of how easy the variant is to call.
