### ISSUE TITLE
hdf5  version link dead

### ISSUE THREAD

**Issue by dinovski** [jts/nanopolish#1052]
if [ ! -e hdf5-1.13.0.tar.gz ]; then \
		version_major_minor=`echo "1.13.0" | sed -E 's/\.[0-9]+$//'`; \
		wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-${version_major_minor}/hdf5-1.13.0/src/hdf5-1.13.0.tar.gz; \
	fi
--2023-01-16 13:36:57--  https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.13/hdf5-1.13.0/src/hdf5-1.13.0.tar.gz
Resolving support.hdfgroup.org (support.hdfgroup.org)... 50.28.50.143
Connecting to support.hdfgroup.org (support.hdfgroup.org)|50.28.50.143|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-01-16 13:36:58 ERROR 404: Not Found.

**Comment by jts** [comment]
thanks for letting me know, fixed
