### ISSUE TITLE
Trying to call Dam and Dcm methylation, error

### ISSUE THREAD

**Issue by nad302** [jts/nanopolish#1053]
Hi
I am trying to determine the methylation frequence of dam and dcm for some plasmids of mine. using this command:

export HDF5_PLUGIN_PATH=/usr/local/hdf5/lib/plugin 
nanopolish call-methylation -t 8 -r /home/dan/Share/Dan/BC1/BC1output.fastq -b /home/dan/Share/Dan/BC1/output.sorted.bam -g /home/dan/Share/Dan/references/pDEL152.fa > BC1_methylation_calls.tsv

This shows some of the dam/dcm sites but not all of them. Although the manual doesn't mention it I saw in some other issues that -q dam,dcm is supposed to change the model but it doesnt run and just prints: 

Error, unknown alphabet name: dam,dcm

I am also interested in EcoKI methylation but I cant see that mentioned anywhere.
Many thanks
Dan

**Comment by nad302** [comment]
For anyone else with same problem. I solved this by just running the whole command for just -q dam and then again for -q dcm. Also I found the -q command detailed in the  terminal manual rather than the online one so can see that EcoKI is not supported. 
Cheers
Dan

**Comment by jts** [comment]
Sorry for not replying sooner. Yes, for call-methylation you need to
specify a single methylation type.

Jared

**Comment by nad302** [comment]
Not a problem.

I had some strange results though. With Dam frequencies I am seeing an average of 45% methylation (values ranging from 8%-80%) from plasmids preppared from a strain that has the dam gene knocked out (will be verifying dam deletion via pcr based on these results). Similarly from a pcr amplified version of the same plasmid I see 22% average (5%-40% range). Dcm on the same series shows no results above 15% and most very low.

Is this sort of error from Dam calling you would expect to see in your experience? 

There are in the range of 10,000-25,000 reads for each of the called sites, none are lower than that.

Cheers
Dan
