### ISSUE TITLE
R10 support?

### ISSUE THREAD

**Issue by jguhlin** [jts/nanopolish#1055]
It looks like R10 flowcells may not be supported yet, if this is true would it be possible to add this to the README, as they become more common?

Cheers

**Comment by jts** [comment]
Sure, I will do this now.

**Comment by jts** [comment]
Done, thanks for the suggestion

**Comment by alexcritschristoph** [comment]
@jts Briefly, what would be involved in getting eventalign to work for R10 / kit 14? I'm interesting in calling non-standard base modifications and am looking to just understand what changed there on a conceptual basis. Many thanks.

**Comment by jts** [comment]
There's a branch that implements most of the functionality needed, but I am missing a good k-mer model for R10.4. I have heard that some people are working on one, but so far haven't seen one released.
