### ISSUE TITLE
Nanopolish index error: Error in getting group name size

### ISSUE THREAD

**Issue by tjprins** [jts/nanopolish#1057]
Hello,

I have been trying to use nanopolish to index some newer RNA nanopore sequencing data. Nanopolish works great with my older samples, but running `nanopolish index /path/to/fast5 master.fastq` starts indexing before returning `error in getting group name size`. Note that the .fastq file is a concatenated master version of all the .fastq files in the basecalled output directory and that my fast5 files in this new sample were separated into pass/fail reads (the older samples I ran that worked were not filtered by qscore). The error that I have been getting appears to be similar to the issues posted [here](https://github.com/jts/nanopolish/issues/914) and [here](https://github.com/jts/nanopolish/issues/796).

By any chance, could this be related to changes in how fast5 files are structured (see this [thread]() on the nanopore website)? I do know that this has caused issues running newer data through older pipelines, but I'd imagine nanopolish indexing should be fine. A copy of an exchange I had with an Oxford Nanopore rep about fast5 backward compatibility with older versions of Guppy can be found below:

> Late last year, we made some changes to the fast5 files (see link below), likely impacting backward compatibility with older Guppy but not the forward compatibility.. as you observed with your data. [https://community.nanoporetech.com/posts/proposed-changes-to-the-fa](https://urldefense.com/v3/__https://community.nanoporetech.com/posts/proposed-changes-to-the-fa__;!!F9wkZZsI-LA!F2VA-ecCWsTulQTyzfsG44F8mz7tfaWQVxr_yu-v8P9Ucf2yVRGHtwXtQQHNYJN4P_GNqQDc1kXWHbhcXduxTpG0IIw$). I did find an article that list out a number of available tool designed to detect RNA modifications. While some of the tools listed in here might still be based on older versions of Guppy, but it might be worth taking a look and see if there is something that can work for your project. [https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9650216/#s5title](https://urldefense.com/v3/__https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9650216/*s5title__;Iw!!F9wkZZsI-LA!F2VA-ecCWsTulQTyzfsG44F8mz7tfaWQVxr_yu-v8P9Ucf2yVRGHtwXtQQHNYJN4P_GNqQDc1kXWHbhcXdux50flnLY$). Hope this information is helpful. Please let me know if you have any questions.
    
In the meantime, I'm trying a different computer with a fresh install of nanopolish and its dependencies. I'll also try running it on the data in the minknow root folder rather than copied versions just in case the files got corrupted after copying. I'll report back any findings from that here.

Thanks!

**Comment by jts** [comment]
Hi @tjprins,

I've reviewed the thread on the fast5 changes and they shouldn't effect nanopolish. If the problem persists, could you send me an example fast5?

Thanks,
Jared

**Comment by tjprins** [comment]
So I re-copied over the raw data from the `/var/lib/minknow/data` folder where it was initially generated and re-ran `nanopolish index` on _just_ the "pass" files and got the same result:

`[readdb] indexing /media/nanopore/Silver/Research/Nanopore/Raw/FAR91556/fast5_pass
error getting group name size`

Then, I tried deleting all the files except for 10 fast5 files at a time and index them in "subsets". I figured if one of the files was corrupted, I might be able to find out which it was. When I did this, however, each batch indexed fine! I'm not sure what the issue is, but perhaps it is struggling with large .fast5 files? It is odd because another sample I did, which was 317 files ~400 MB each, it ran fine (while this one is 274 files ~350 MB each). 

Would it be possible to index in batches and then just concatenate the output files?

**Comment by jts** [comment]
Is it possible the process ran out of memory? Sometimes this triggers
strange looking error messages

**Comment by tjprins** [comment]
It's possible, but the machine I was using has 128 GB of RAM available and was able to handle the 317 files of similar size prior in one go. Would it be valid for me to just do it in smaller batches if that works around the issue?

**Comment by jts** [comment]
Yes but its a bit of a pain - you'll want to use the full fastq file each
time, then concat all the .readdb files from subsets.

Jared

**Comment by hasindu2008** [comment]
@tjprins you can try converting the fast5 to blow5 and then running nanopolish on the blow5 file. The memory requirement will be low I think.

**Comment by tjprins** [comment]
I was able to run `nanopolish index` in two chunks on my data and then concatenate the `.readdb` files from the subsets and that worked. However, when I now try to run `eventalign`, I just get repeating warnings like so:

`[warning] sequence of read d8ec5675-5f39-4797-a3de-b22e3f0c7d1e is empty
[W::fai_get_val] Reference 9f5da758-3087-4255-85fa-f17b27dad19d not found in FASTA file, returning empty sequence`

@hasindu2008 I also tried generating blow5 files from the original fast5 files, but `nanopolish index` wont read them. Do I have to specify it is not a fast5 file somehow?

**Comment by hasindu2008** [comment]
Nanopolish v0.14.0 onwards supports directly using BLOW5.
see nanopolish pipeline here https://hasindu2008.github.io/slow5tools/workflows.html

**Comment by tjprins** [comment]
Gotcha. I was able to convert the files to BLOW5 using your provided documentation, but it had some issues (it kept giving me an error for some of the files). The output in the shell was as follows:

`[f2s_main] 275 fast5 files found - took 0.041s`
`[f2s_main] Just before forking, peak RAM = 0.000 GB`
`[f2s_iop] 8 proceses will be used.`
`[f2s_iop] Spawning 8 I/O processes to circumvent HDF hell.`
`[read_fast5::ERROR] Bad fast5: Could not iterate over the read groups in the fast5 file /Volumes/Silver/Research/Nanopore/Raw/FAR91556/fast5_pass/FAR91556_pass_a92bf75a_245.fast5.`
`[f2s_child_worker::ERROR] Bad fast5: Could not read contents of the fast5 file /Volumes/Silver/Research/Nanopore/Raw/FAR91556/fast5_pass/FAR91556_pass_a92bf75a_245.fast5.`
`[read_fast5::ERROR] Bad fast5: Could not iterate over the read groups in the fast5 file /Volumes/Silver/Research/Nanopore/Raw/FAR91556/fast5_pass/FAR91556_pass_a92bf75a_210.fast5.`
`[f2s_child_worker::ERROR] Bad fast5: Could not read contents of the fast5 file /Volumes/Silver/Research/Nanopore/Raw/FAR91556/fast5_pass/FAR91556_pass_a92bf75a_210.fast5.`
`[f2s_child_worker::INFO] Summary - total fast5: 35, bad fast5: 0`
`[f2s_child_worker::INFO] Summary - total fast5: 35, bad fast5: 0`
`[f2s_child_worker::INFO] Summary - total fast5: 35, bad fast5: 0`
`[f2s_child_worker::INFO] Summary - total fast5: 35, bad fast5: 0`
`[f2s_child_worker::INFO] Summary - total fast5: 35, bad fast5: 0`
`[f2s_child_worker::INFO] Summary - total fast5: 35, bad fast5: 0`
`[f2s_iop] Child process 29315 exited with status=1.`
 
I'm unsure how to use the BLOW5 files to run eventalign though, which is the next step I need to do. I _did_ however get it to work by running `nanopolish index` on the original files and concatenating all of the output files together and then running `nanopolish eventalign`. I have yet to feed those results into the rest of my pipeline, so I'll post again here if I run into issues. Any reason I would get the above error with the BLOW5 conversion? Are some of these fast5 files corrupt?

**Comment by hasindu2008** [comment]
@tjprins 
Yeh that fast5 seem to be corrupted. Could you open an issue under slow5tools. I can help you to recover the data from such corrupt files.
