### ISSUE TITLE
Creating a vcf files that include BaseCalledReadsWithVariant in the report

### ISSUE THREAD

**Issue by epiBioCore** [jts/nanopolish#1061]
Hi,

Sorry if I am asking a naive question. I am very new in this field and trying to figure out how to run the nanopolish pipeline so that I can receive "BaseCalledReadsWithVariant" in the report.  With the way that I have done so far what I get in my vcf file is as follows:

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
ref|NC_000077.7|:81926214-81928465	64	.	CT	C	35266.3	PASS	TotalReads=68199;AlleleCount=1;SupportFraction=0.228357;SupportFractionByStrand=0.24173,0.21498;StrandSupport=25861,26764,8244,7330;StrandFisherTest=161;SOR=0.787881;RefContext=ACTTACTCAGCG	GT	1

And here is the command that I used to create above vcf file:
$nanopolish_home/nanopolish variants --consensus -o $out_name -p 4 -r $in_fastq -b $in_sorted_bam -g ./CCL2.fa     -t 32

Any instructions that guide me to generate a vcf file with "BaseCalledReadsWithVariant" feature is appreciated.

Thank you

**Comment by epiBioCore** [comment]
Thanks Jared for your reply!
Is there a pipeline/guideline that you can suggest to find variants from the read alignments? I would like to do this analysis from the scratch so that can generate that tag ...

Thanks for your help

**Comment by jts** [comment]
My apologies, I read your issue too quickly and misunderstood the problem. In `--consensus` mode nanopolish tries all single base edits (substitutions, 1bp insertions and deletions), and _these_ variants don't have the `BaseCalledReadsWithVariant` annotation. All you can try is to remove the `--consensus` flag so it runs in variant calling mode which doesn't have this feature.

**Comment by epiBioCore** [comment]
I used the following command (removed  the --consensus):
nanopolish_home/nanopolish variants -o $out_name -p 4 -r $in_fastq -b $in_sorted_bam -g ./CCL2.fa -t 32

and this time I didn't receive any types of report/tags (please see the below)

##fileformat=VCFv4.2
##nanopolish_window=ref|NC_000077.7|:81926214-81928465:0-2251
##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">
##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">
##INFO=<ID=SupportFractionByStrand,Number=2,Type=Float,Description="Fraction of event-space reads that support the variant for each strand">
##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">
##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">
##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">
##INFO=<ID=StrandSupport,Number=4,Type=Integer,Description="Number of reads supporting the REF and ALT allele, by strand">
##INFO=<ID=StrandFisherTest,Number=1,Type=Integer,Description="Strand bias fisher test">
##INFO=<ID=SOR,Number=1,Type=Float,Description="StrandOddsRatio test from GATK">
##INFO=<ID=RefContext,Number=1,Type=String,Description="The reference sequence context surrounding the variant call">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample

For my analysis I need to generate a vcf file that includes "BaseCalledReadsWithVariant" tag. I am wondering if I didn't create the basecalled reads correctly?? Is there a tutorial/guideline that show me the workflow from scratch to generate this tag?

Thank you.

**Comment by epiBioCore** [comment]
I would appreciate if anybody could help me regarding my above question or provide me some advice??

Thank you!

**Comment by jts** [comment]
1. you've set the ploidy to be 4 (`-p 4`). is this correct for your sample?
2. try a smaller region than the entire reference genome, your depth is extremely high so it may take a long time to call variants

**Comment by epiBioCore** [comment]
Thank you so much for your help, Jared!
I set the -p 2 and it worked!!!
