### ISSUE TITLE
running nanopolish on fast5 files generated with latest vbz compresison

### ISSUE THREAD

**Issue by rezarahman12** [jts/nanopolish#1065]
Dear Jared,

I've obtained nanopore direct RNA-sequencing data recently. I'll run Nanopolish on my nanopore data. However, MinKnow has given us the vbz compressed fast5 file. I just wondering whether Nanopolish accepts vbz compressed fast5 files.

Thank you for your kind consideration.

Best regards
Reza

**Comment by hasindu2008** [comment]
See this https://hasindu2008.github.io/f5c/docs/general-troubleshoot#the-fast5-file-is-compressed-with-vbz-but-the-required-plugin-is-not-loaded
This method documented for f5c, works for nanopolish too.

**Comment by rezarahman12** [comment]
Thanks @hasindu2008
