### ISSUE TITLE
MM/ML tag and hard/soft clipping alignments

### ISSUE THREAD

**Issue by PanZiwei** [jts/nanopolish#1066]
Hi,
I am wondering whether you have a following up solution for the https://github.com/samtools/hts-specs/issues/646.  How does Nanopolish do alignment currently? It's soft-clipping or hard-clipping?
Thank you!

**Comment by jts** [comment]
Nanopolish relies on the alignment in the .bam file provided by the user, which is usually from minimap2. I'm going to close this issue so that the discussion about hard clipping is in one place (in the hts-specs issue)
