### ISSUE TITLE
eventalign --scale-events and event_level_mean

### ISSUE THREAD

**Issue by guangzhaocs** [jts/nanopolish#1068]
Hi,

I want to know how to get the `event_level_mean` from the raw signal. You perform a linear scaling of the events and I want to know the details.  In this issue(https://github.com/jts/nanopolish/issues/474) the link for the file(https://media.nature.com/original/nature-assets/nmeth/journal/v14/n4/extref/nmeth.4184-S1.pdf) is unavailable. Could you provide this file?

Thanks.

**Comment by jts** [comment]
Hi,

You can find this file here: https://static-content.springer.com/esm/art%3A10.1038%2Fnmeth.4184/MediaObjects/41592_2017_BFnmeth4184_MOESM258_ESM.pdf

Thanks,
Jared
