### ISSUE TITLE
Call methylation example files not found.

### ISSUE THREAD

**Issue by aobermayer4** [jts/nanopolish#1069]
I am trying to perform the call-methylation methods with the example data provided in the documentation (https://nanopolish.readthedocs.io/en/latest/quickstart_call_methylation.html) but when I try to `wget` the example files it gives me "ERROR 404: Not Found." Does this link need to be updated? 
![image](https://user-images.githubusercontent.com/59879286/223151500-a8c77ef5-80bc-4366-b518-f3934f59c714.png)

**Comment by katiestoker** [comment]
I think this should work...
wget warwick.s3.climb.ac.uk/nanopolish_tutorial/methylation_example.tar.gz

**Comment by aobermayer4** [comment]
@katiestoker Thank you so much, that worked!
