### ISSUE TITLE
squiggle_read.cpp:304: std::vector<EventRangeForBase> 

### ISSUE THREAD

**Issue by damientully** [jts/nanopolish#107]
Hi,

I am trying to use nanopolish on data that was locally basecalled with albacore and I get the following error:

`nanopolish eventalign -t 12 --sam -r BC06.fasta -b BC06_reads.sorted.bam -g BC06.contigs --models nanopolish_models.fofn | samtools view -Sb - | samtools sort -f - BC06.eventalign.sorted.bam `

`nanopolish: src/nanopolish_squiggle_read.cpp:304: std::vector<EventRangeForBase> SquiggleRead::build_event_map_1d(const string&, uint32_t, std::vector<fast5::Event_Entry>&): Assertion f5_events[0].move == 0' failed.`
`
Any assistance would be great.

Thanks,
Damien

**Comment by jts** [comment]
This is probably an incompatibility with albacore. Could you send me a single fast5 so I can debug?

**Comment by johnomics** [comment]
Here's a read that has this problem:

[biolmac472_york_ac_uk_20170119_FNFAB42793_MN17681_mux_scan_20170119_107_79_22807_ch100_read101_strand.fast5.zip](https://github.com/jts/nanopolish/files/744711/biolmac472_york_ac_uk_20170119_FNFAB42793_MN17681_mux_scan_20170119_107_79_22807_ch100_read101_strand.fast5.zip)

FASTQ for all reads was created with:
```
nanopolish extract --type template -q -o nanopolish.reads.fastq MinIONrun/Reads/pass/
```

I just put the FASTQ for this read in its own file and ran:
```
bwa mem -x ont2d reference.fasta firstread.fastq | samtools sort -o firstread.sorted.bam -T . -
samtools index firstread.sorted.bam
nanopolish eventalign --sam -r firstread.fastq -b firstread.sorted.bam -g reference.fasta --models nanopolish_models.fofn
```

Output:
```
nanopolish: src/nanopolish_squiggle_read.cpp:304: std::vector<EventRangeForBase> SquiggleRead::build_event_map_1d(const string&, uint32_t, std::vector<fast5::Event_Entry>&): Assertion `f5_events[0].move == 0' failed.
```

**Comment by jordur** [comment]
More information:
[ugm07_20170126_FNFAF04266_MN19775_sequencing_run_B_atroxPII_f1_55732_ch9_read1267_strand.fast5.zip](https://github.com/jts/nanopolish/files/744737/ugm07_20170126_FNFAF04266_MN19775_sequencing_run_B_atroxPII_f1_55732_ch9_read1267_strand.fast5.zip)
Created fasta using:
`nanopolish extract --type template fast5/pass/ > files_extract.fasta`

Alignment:
`bwa mem -x ont2d -t 4 reference.fasta files_extract.fasta | samtools view -Sb - | samtools sort -f - files_extract.bam`

Eventalign:
`nanopolish eventalign -t 4 --sam -r files_extract.fasta -b files_extract.bam -g reference.fasta --models nanopolish_models.fofn | samtools view -Sb - | samtools sort -f - reads.eventalign.sorted.bam`

Output:
>nanopolish: src/nanopolish_squiggle_read.cpp:304: std::vector<EventRangeForBase> SquiggleRead::build_event_map_1d(const string&, uint32_t, std::vector<fast5::Event_Entry>&): Assertion `f5_events[0].move == 0' failed.

**Comment by jts** [comment]
I'll look into this today. Could you also tell me what reference genome I should use for the read?

**Comment by johnomics** [comment]
Thanks - it's a draft assembly of Galdieria sulphuraria from MinION R9.4 reads only, 1D ligation kit, sequenced last week and assembled with canu 1.4.
[galdieria.contigs.fasta.zip](https://github.com/jts/nanopolish/files/745046/galdieria.contigs.fasta.zip)

**Comment by jts** [comment]
This looks like a bug in the local basecaller, I'll have to discuss it with ONT. If you'd like to use nanopolish on these reads I suggest running them through nanonet or metrichor.

**Comment by jordur** [comment]
Here the reference sequence was an amplicon 11Kb length sequenced with a MinION R9.4 flow cell. The library was done also with 1D ligation kit
[Batrox_PII_F1.fasta.zip](https://github.com/jts/nanopolish/files/745167/Batrox_PII_F1.fasta.zip)

**Comment by jts** [comment]
Hi @johnomics can you describe how your reads where basecalled? Was this using the local basecalling feature in MinKNOW or the standalone version of albacore?

**Comment by johnomics** [comment]
Local basecalling with MinKNOW 1.3.25.

**Comment by jts** [comment]
@jordur did you also use Local basecalling with MinKNOW or standalone albacore?

**Comment by damientully** [comment]
@jts The file that I sent you was standalone albacore.

**Comment by jts** [comment]
Thanks @damientully could you send the reference sequence as well?

**Comment by damientully** [comment]
@jts I just emailed you the ref sequence.

**Comment by jts** [comment]
thanks, got it

**Comment by jordur** [comment]
@jts , I used Local basecalling with MinKNOW  but not sure about the version since I'm away from the computer

**Comment by jts** [comment]
thanks all for the help, we're looking into it.

**Comment by jts** [comment]
I've finally fixed this in b751d0a. This is in the 0.6-dev branch, which I intend to merge into master this week.

**Comment by johnomics** [comment]
Excellent, thank you! I'll try it out when it's merged into master.

**Comment by jordur** [comment]
Great! Thank you very much!

**Comment by jts** [comment]
0.6 is now the master version
