### ISSUE TITLE
Nanopolish variants looks like stuck

### ISSUE THREAD

**Issue by HJArdin** [jts/nanopolish#1070]
Hi,
I'm using nanopolish variants from artic pipeline to call variants.
Usually I dont have any problems but one sample take infinite time to process.
Here is my artic command :
```
artic \
    minion \
    --normalise 500  --minimap2 \
    --threads 25 \
    --read-file sample.fastq.gz \
    --scheme-directory ./primer-schemes \
    --scheme-version 8 \
     \
    --fast5-directory fast5_pass \
    --sequencing-summary ONT_summary.txt \
    schemes_dir \
    sample
```
At this point the pipeline get stuck after alignement with this command :
`nanopolish variants --min-flanking-sequence 10 -x 1000000 --progress -t 25 --reads sample.fastq.gz -o sample.vcf -b sample.trimmed.rg.sorted.bam -g primer-schemes/scheme_dir/scheme.reference.fasta -w NC_006273.2:1-235647 --ploidy 2 -m 0.15 --read-group 1`
I don't know if the task is running efficiently cause only 1 cpu is use and i specified 25.

I'm running out of idea... Do you have any suggestions ?

**Comment by jts** [comment]
You can reduce runtime in variant calling by reducing `-x` to a smaller number (try `-x 100`) or increasing `-m` (`-m 0.25`). This will reduce the number of candidate variants and haplotypes that it considers.

Jared
