### ISSUE TITLE
nanopolish: error while loading shared libraries: libhdf5.so.10

### ISSUE THREAD

**Issue by SophieValk** [jts/nanopolish#1071]
Hi, 
I have tried installing Nanopolish via the following commands: 

_git clone --recursive https://github.com/jts/nanopolish.git
cd nanopolish
make_

And I get the following errors after make: 
_/usr/bin/ld: cannot find -lbz2
collect2: error: ld returned 1 exit status
Makefile:316: recipe for target 'libhts.so' failed
make[1]: *** [libhts.so] Error 1
make[1]: Leaving directory '/home/nanopolish/nanopolish/htslib'
Makefile:138: recipe for target 'htslib/libhts.a' failed
make: *** [htslib/libhts.a] Error 255_

When I tried to run nanopolish it mentions the following error: _nanopolish: error while loading shared libraries: libhdf5.so.10: cannot open shared object file: No such file or directory_

Does anyone know how I can solve this error?

**Comment by jts** [comment]
Hi @SophieValk,

Nanopolish requires htslib, which in turn requires a library called bz2 (this is the `-lbz2` error). You'll need to install this to compile both.

Jared

**Comment by SophieValk** [comment]
Thanks a lot! I will try that.
