### ISSUE TITLE
 Is there a way to calculate methylation frequency of every individual motifs using nanopolish?

### ISSUE THREAD

**Issue by YingziZhang-github** [jts/nanopolish#1073]
Hi,

Thank you very much for developing nanopolish.

I am interested in studying methylation patterns at the single-motif level. It becomes difficult to determine the methylation status of individual motifs within a motif group. Is there a way to calculate methylation frequency of every individual motifs?

Looking forward to hearing from you. Thank you in advance.

Yingzi

**Comment by jts** [comment]
Currently no, there isn't. The basecallers (guppy, dorado) can call methylation at single bases however, so I recommend using them instead.

Jared
