### ISSUE TITLE
POD5 support?

### ISSUE THREAD

**Issue by ellieanderson** [jts/nanopolish#1074]
Hi there,
I'm currently working with dorado and nanopolish to detect methylated bases and I'm trying to index the dorado output. I keep getting an error, which I've provided below. 

`nanopolish index -d $POD5DIR $DORADO_FQ`

> [readdb] indexing /work/eaa50/met_epi/raw_data/met_epi/pod5
> Error: no fast5 files found

I first tried pointing the directory to the reads that were stored in fast5 format - which are in the path specified, and I can basecall on them - but after getting the same error, I changed the path to the POD5 directory because it seems like the reads need to be from the same source as the original reads. In my case, I converted the fast5s to the pod5 format and then used those with dorado as basecaller. 

I'm pretty new at using nanopolish and related tools, so excuse my ignorance if I'm just completely wrong about what I've done in my code, but is there going to be support for POD5 in the future, given that dorado is Nanopore's new recommended basecaller? Or is there something else I'm doing wrong that could fix this problem? 

Thanks in advance!

Ellie

nanopolish version 0.13.3
dorado version 0.2.1+c70423e

**Comment by jts** [comment]
Hi @ellieanderson,

You are correct, nanopolish does not support POD5 yet as I haven't had a chance to implement this. It should have worked when you provided fast5 files though, I can try to help with this if you can provide a bit more information (commands, paths, error messages).

Jared

**Comment by ellieanderson** [comment]
@jts thanks for responding so quickly. Here's what I've done so far.

Original command:
`nanopolish index -d $FAST5DIR $DORADO_FQ`

`$FAST5DIR` = /work/eaa50/met_epi/raw_data/met_epi/fast5
`$DORADO_FQ` = /work/eaa50/met_epi/dorado_results/toy.fq 

toy.fq was derived from this dorado command:
`/opt/bin/dorado basecaller -x cpu -n $SUBSET_SIZE /work/eaa50/met_epi/models/dna_r9.4.1_e8_fast@v3.4 /work/eaa50/met_epi/raw_data/met_data/pod5 --modified-bases 5mCG > $DORADO_SAM`

`$DORADO_SAM` = /work/eaa50/met_epi/dorado_results/toy.sam

Then converted to fastq format using samtools.

I've gone through the suggestions in issue #917 and checked to make sure there are fast5 files there.
`ls $FAST5DIR`

> FAK91328_e8a6856236ed91f985df968fe6159ff4334ca968_91.fast5
> FAK91328_e8a6856236ed91f985df968fe6159ff4334ca968_92.fast5
> FAK91328_e8a6856236ed91f985df968fe6159ff4334ca968_93.fast5
> FAK91328_e8a6856236ed91f985df968fe6159ff4334ca968_94.fast5
> FAK91328_e8a6856236ed91f985df968fe6159ff4334ca968_95.fast5
> FAK91328_e8a6856236ed91f985df968fe6159ff4334ca968_96.fast5
> FAK91328_e8a6856236ed91f985df968fe6159ff4334ca968_97.fast5
> FAK91328_e8a6856236ed91f985df968fe6159ff4334ca968_98.fast5
> FAK91328_e8a6856236ed91f985df968fe6159ff4334ca968_99.fast5
> FAK91328_e8a6856236ed91f985df968fe6159ff4334ca968_9.fast5

`find . -name "*.fast5"`

> ./FAK91328_e8a6856236ed91f985df968fe6159ff4334ca968_300.fast5
> ./FAK91328_e8a6856236ed91f985df968fe6159ff4334ca968_311.fast5
> ./FAK91328_e8a6856236ed91f985df968fe6159ff4334ca968_338.fast5
> ./FAK91328_e8a6856236ed91f985df968fe6159ff4334ca968_23.fast5
> ./FAK91328_e8a6856236ed91f985df968fe6159ff4334ca968_287.fast5
> ./FAK91328_e8a6856236ed91f985df968fe6159ff4334ca968_88.fast5
> ./FAK91328_e8a6856236ed91f985df968fe6159ff4334ca968_257.fast5
> ./FAK91328_e8a6856236ed91f985df968fe6159ff4334ca968_388.fast5

`h5dump` also is not working.
`h5dump $FAST5DIR/FAK91328_e8a6856236ed91f985df968fe6159ff4334ca968_9.fast5`

> h5dump error: unable to open file > "/work/eaa50/met_epi/raw_data/met_epi/fast5/FAK91328_e8a6856236ed91f985df968fe6159ff4334ca968_9.fast5"

Any suggestions?

Thanks for your help!

Ellie

**Comment by hasindu2008** [comment]
Hi 

The FAST5 files are probably corrupted.
A quick suggestion. Could you run dorado basecaller on this FAST5 directory and see if it gives an error? 
Another thing you can try is to use [slow5toools f2s](https://github.com/hasindu2008/slow5tools) to convert the FAST5 to BLOW5 and see if that catches any issue with the FAST5 files. If that works, you can use nanopolish on the BLOW5 files.

**Comment by ellieanderson** [comment]
Okay, I fixed it! Turns out my path was wrong... Silly me! Thanks for all your help.
