### ISSUE TITLE
nanopolish variants --consensus needs fai index for input contigs

### ISSUE THREAD

**Issue by fanavarro** [jts/nanopolish#1075]
I have been trying nanopolish variants --consensus and it has a strange behavior: the first run it failed, but the second run was fine. I was executing it by using the make_range.py and the parallel pipe, as denoted in the documentation:

```
python3 nanopolish_makerange.py draft.fa | parallel --results nanopolish.results -P 8 \
    nanopolish variants --consensus -o polished.{1}.vcf -w {1} -r reads.fa -b reads.sorted.bam -g draft.fa -t 4 --min-candidate-frequency 0.1
```
After some research, I suspect that nanopolish variants needs `draft.fa` to be indexed, so it needs a file `draft.fa.fai` in the same folder than `draft.fa`. I think nanopolish is creating internally this index in case that it is not found; however, when using multiple threads by `parallel`, I think there is some race condition in which one thread starts to create de index while the other ones try to obtain information from that index, which is not already built. This derives in error messages indicating that `faidx could not get contig length` (maybe this is related to  #869) for each thread that tries to access the index while it is been built. Once every thread is finished, the command showed above return an error code because some threads did not finish properly.

For this reason, when I executed the command for the second time, it worked perfectly because the fai index was already created.

To avoid this kind of errors, I would set the fai index as mandatory before the execution (so, delegate the construction of the fai index to the user).

Do you think this would be a good idea?

Thanks in advance.

**Comment by jts** [comment]
Hi,

This is a good point, I have encountered this problem myself. I agree the fai index should be mandatory.

Jared
