### ISSUE TITLE
Nanopolish segmentation fault (code dumped) error

### ISSUE THREAD

**Issue by surbhiseth** [jts/nanopolish#1076]
Hi

I tried running Nanopolish variants but kept getting the segmentation fault error. I have used the following command:

nanopolish variants -p 2 -w chr1:97077743-97995000 -t 16 --snps --reads barcode43.fastq --bam barcode43.bam --genome ../GRCh38.primary_assembly.genome.fa

I get this error message:

##fileformat=VCFv4.2
##nanopolish_window=chr1:97077743-97995000
##FILTER=<ID=StrandBias,Number=1,Type=Integer,Description="Variant failed the fisher strand bias test">
##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">
##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">
##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">
##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">
##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">
##INFO=<ID=StrandSupport,Number=4,Type=Integer,Description="Number of reads supporting the REF and ALT allele, by strand">
##INFO=<ID=StrandFisherTest,Number=1,Type=Integer,Description="Strand bias fisher test">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample
Segmentation fault (core dumped)

Please give me some advice on how to solve this problem. Thank you very much!
Best wishes,
Surbhi

**Comment by jts** [comment]
Hi,

It is hard to say what the problem is. Did it seg fault immediately, or run for awhile before crashing?

Jared
