### ISSUE TITLE
install error: src/nanopolish_call_methylation.cpp:50:10: fatal error: minimap.h: No such file or directory

### ISSUE THREAD

**Issue by jackzhong1995** [jts/nanopolish#1078]
Hi!

When I install nanopolish, I got an error, the log infomation as following:

2023-04-17 11:10:00 (4.05 MB/s) - ‘eigen-3.3.7.tar.bz2’ saved [1663474]

tar -xjf eigen-3.3.7.tar.bz2 || exit 255
mv eigen-3.3.7 eigen || exit 255
rm -f ./.depend
/home/miniconda3/bin/x86_64-conda_cos6-linux-gnu-c++ -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/miniconda3/include -std=c++11 -fopenmp -fsigned-char -D_FILE_OFFSET_BITS=64  -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/miniconda3/include -I./include -I./htslib -I./minimap2 -I./src -I./src/hmm -I./src/thirdparty -I./src/thirdparty/scrappie -I./src/common -I./src/alignment -I./src/pore_model -I./src/io -I./src/basemods -I./eigen/ -I./slow5lib/include/ -MM  src/nanopolish_vcf2fasta.cpp src/nanopolish_polya_estimator.cpp src/nanopolish_haplotype.cpp src/nanopolish_call_methylation.cpp src/nanopolish_squiggle_read.cpp src/nanopolish_detect_polyi.cpp src/nanopolish_variant_db.cpp src/nanopolish_read_db.cpp src/nanopolish_fast5_check.cpp src/nanopolish_raw_loader.cpp src/nanopolish_index.cpp src/nanopolish_scorereads.cpp src/training_core.cpp src/nanopolish_phase_reads.cpp src/nanopolish_call_variants.cpp src/nanopolish_methyltrain.cpp src/nanopolish_train_poremodel_from_basecalls.cpp  src/hmm/nanopolish_transition_parameters.cpp src/hmm/nanopolish_duration_model.cpp src/hmm/nanopolish_profile_hmm_r9.cpp src/hmm/nanopolish_profile_hmm.cpp src/hmm/nanopolish_profile_hmm_r7.cpp      src/common/fs_support.cpp src/common/nanopolish_bam_processor.cpp src/common/nanopolish_klcs.cpp src/common/nanopolish_alphabet.cpp src/common/logsum.cpp src/common/nanopolish_iupac.cpp src/common/nanopolish_common.cpp src/common/nanopolish_variant.cpp src/common/nanopolish_bam_utils.cpp  src/alignment/nanopolish_eventalign.cpp src/alignment/nanopolish_anchor.cpp src/alignment/nanopolish_alignment_db.cpp  src/pore_model/nanopolish_model_names.cpp src/pore_model/nanopolish_pore_model_set.cpp src/pore_model/nanopolish_poremodel.cpp  src/io/nanopolish_fast5_processor.cpp src/io/nanopolish_fast5_loader.cpp src/io/nanopolish_fast5_io.cpp  src/basemods/nanopolish_basemods.cpp      src/thirdparty/fet.c src/thirdparty/stdaln.c  src/thirdparty/scrappie/event_detection.c src/thirdparty/scrappie/scrappie_common.c           > ./.depend;
src/nanopolish_call_methylation.cpp:50:10: fatal error: minimap.h: No such file or directory
 #include "minimap.h"
          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:187: .depend] Error 1

My minimap2 is normal.

**Comment by hasindu2008** [comment]
Did you git clone with --recursive option?

**Comment by jackzhong1995** [comment]
> Did you git clone with --recursive option?

No, I canot clone it with --recursive option. I don't know how to deal it.
git clone --recursive https://github.com/jts/nanopolish.git
Cloning into 'nanopolish'...
error: RPC failed; result=7, HTTP code = 0
fatal: The remote end hung up unexpectedly
