### ISSUE TITLE
Variant calling from Nanopore cDNA-seq?

### ISSUE THREAD

**Issue by CWYuan08** [jts/nanopolish#1079]
Hi,

I am wondering if the current version of Nanopolish supports variant calling from PCR cDNA-seq data?

Many thanks!

Best,
CW

**Comment by jts** [comment]
Yes, but only for R9.4 data.

**Comment by CWYuan08** [comment]
Dear @jts,

many thanks for prompt reply! Yes, we have R9.4 data, are there any tutorial/instructions that I can follow?

Best regards,
CW

**Comment by jts** [comment]
Sorry for missing this - we don't have any instructions for cDNA variant calling since it isn't something we have tried before.
