### ISSUE TITLE
Problem with locally base called read names 

### ISSUE THREAD

**Issue by johnomics** [jts/nanopolish#108]
I'm trying to run nanopolish using a set of reads called with MinKNOW 1.3.25, so local 1D base calling with event data. The read names all look like this:
`@channel_100_2def5700-f333-4aed-a8aa-9ec22b6639e4_template`

Unfortunately, this means `nanopolish extract` gives all the reads the same name, `channel`, because it splits at the first underscore (nanopolish_extract.cpp lines 140-141).

I'm on commit https://github.com/jts/nanopolish/commit/de0a1b23bc50d120697c1e17d02671120e9c4d9a but this appears to still be present in the current master.

**Comment by jts** [comment]
Thanks for the clear report. @mateidavid could you fix this?

**Comment by jts** [comment]
Hi John,

This should be fixed in the latest code, could you try it out?

**Comment by johnomics** [comment]
OK, here's the first FASTQ header:
`@channel_100_2def5700-f333-4aed-a8aa-9ec22b6639e4_template:1D_000:template`

So it seems to be working - thanks for getting to this so quickly!

**Comment by jordur** [comment]
Hi! Not for me. The fasta header now looks like:
`>channel_285_a45dbebb-6949-467d-a46d-34bb5c3c107d_template:1D_000:template ugm07_20170126_FNFAF04266_MN19775_sequencing_run_B_atroxPII_f1_55732_ch285_read61_strand fast5/pass/ugm07_20170126_FNFAF04266_MN19775_sequencing_run_B_atroxPII_f1_55732_ch285_read61_strand.fast5`
Some white spaces still remain in the name.
Actually I don't know the reason of such a weird name since I am not the owner of the Minion device.

**Comment by johnomics** [comment]
Sorry, I wasn't completely clear - I also have extra information like that after the sequence name (before and after the fix), but this is normal - nanopolish adds these extra fields so it can find the event data in the FAST5 file for the read.

**Comment by jordur** [comment]
Just to clarify: I have the following directories structure
├── Batrox_nanopolish_extract.bam
├── Batrox_nanopolish_extract.bam.bai
├── Batrox_nanopolish_extract.fasta
├── Batrox_nanopolish_extract.fasta.fast5.fofn
├── fast5
│   ├── fail
│   ├── pass -> ALL *.fast5 files
│   └── skip
├── nanopolish_models.fofn
├── README
├── reads.eventalign.sorted.bam
├── template_median68pA.5mers.model
└── template_median68pA.model

Moreover, some tags could be easily identified: 
ugm07 -> Laboratory
_20170126_ -> Date
FNFAF04266_MN19775_sequencing_run_
B_atroxPII_f1_ -> Sample label
55732_ch285_read61_strand
But trying the eventalign command I obtained the following:
>registering model t.007-base
registering model t.007-ONT
nanopolish: src/nanopolish_squiggle_read.cpp:304: std::vector<EventRangeForBase> SquiggleRead::build_event_map_1d(const string&, uint32_t, std::vector<fast5::Event_Entry>&): Assertion f5_events[0].move == 0' failed.
nanopolish: src/nanopolish_squiggle_read.cpp:304: std::vector<EventRangeForBase> SquiggleRead::build_event_map_1d(const string&, uint32_t, std::vector<fast5::Event_Entry>&): Assertion f5_events[0].move == 0' failed.
nanopolish: src/nanopolish_squiggle_read.cpp:304: std::vector<EventRangeForBase> SquiggleRead::build_event_map_1d(const string&, uint32_t, std::vector<fast5::Event_Entry>&): Assertion f5_events[0].move == 0' failed.

Do you think that underscores could be the reason of that?

**Comment by johnomics** [comment]
This is a different bug... which I have also just hit! It's https://github.com/jts/nanopolish/issues/107. Trying to figure out if it's linked to the header names but I suspect not - probably a format problem with the locally called FAST5 files. Should discuss on https://github.com/jts/nanopolish/issues/107 instead though.
