### ISSUE TITLE
Can I index trimmed fastqs?

### ISSUE THREAD

**Issue by weishwu** [jts/nanopolish#1080]
A naive question: after I run `nanopolish index` on trimmed fastqs, how does the downstream software (such as `nanopolish call-methylation`) match the basecalls in fastq and the signals in fast5? For example, if I clip off 10nt from the 5' ends of the reads in fastq, will the software match the 11th pulse with the 1st base in the fastq? How does it know?

**Comment by jts** [comment]
Hi,

This should be fine. There is an internal signal-to-read alignment step that is designed to tolerate light trimming of the reads (like barcodes).

Jared

**Comment by weishwu** [comment]
@jts Thanks!
