### ISSUE TITLE
Empty eventalign.txt file after running nanopolish eventalign

### ISSUE THREAD

**Issue by vincentwu1999** [jts/nanopolish#1083]
please help me with this asap. Thx

**Comment by vincentwu1999** [comment]
I was using only 1 fast5 file before decompressing it using multi2single

**Comment by vincentwu1999** [comment]
Yes it's R10.4 data - I just confirmed with my PI

**Comment by jts** [comment]
Ok, right now we don't support R10.4 data - see here: https://github.com/jts/nanopolish#a-note-on-r10-support. f5c does however so you might want to try it instead.

**Comment by vincentwu1999** [comment]
We are not using variant or methylation - just the "nanopolish index" and "nanopolish eventalign" commands. Thx

**Comment by vincentwu1999** [comment]
I can send you a compressed fast5 file to run for testing, if you need

**Comment by hasindu2008** [comment]
@vincentwu1999 
If you want eventalign output, you can try f5c eventalign on R10.4.1 data: https://github.com/hasindu2008/f5c/ with --pore r10 option.
