### ISSUE TITLE
Eventalign.txt file is too large

### ISSUE THREAD

**Issue by SEVEN-XYCHEN** [jts/nanopolish#1086]
Hello,
I encountered a memory issue. My fastq file is 5.9G，bam file is 9.3G, transcript.fa file is 1.8 G, and there are 453G fast5 files under the fast5 folder. I first ran `nanopolish index`, it ran successfully. Then, I would run eventalign, but the generated `eventalign.txt` file is too large. It's already 835G before it's finished running. I estimate that there may be 6~7 T after it is completed, and my server does not have such a large amount of memory to store it. Is this reasonable? Is the `eventalign.txt` file too large? Is there any way to improve it? Can I split the bam file to run `nanopolish eventalign`?
Thank you very much for taking the time to answer my question! Looking forward to your reply.

**Comment by jts** [comment]
It is expected that the file is very large as it annotates the raw signal data with a lot of information. Typically you do not need to generate an eventalign file for all of your data. What are you trying to do with it?

**Comment by jts** [comment]
I suggest asking them for advice on how to split up the input/output for efficient processing.

**Comment by SEVEN-XYCHEN** [comment]
Okay @jts , thank you very much for your help! So have you ever tried to split bam files for `napolish eventalign`? Is this reasonable?

**Comment by jts** [comment]
Yes that is fine.

**Comment by SEVEN-XYCHEN** [comment]
Okay, thank you again! Best, Chen
