### ISSUE TITLE
Why CpGs are clustered

### ISSUE THREAD

**Issue by weishwu** [jts/nanopolish#1087]
I'm new to Nanopore methylation calling and wonder why neighboring CpGs can be merged in one line in the `calculate_methylation_frequency.py` output. I found an explanation saying "Since nanopore signals depend on multiple bases, we need to cluster nearby CpGs together and add a bit of flanking sequence to make the call(s)". I understand that when DNA goes through the pore, the signal is dependent on the nucleotides in and around the pore, so single-nucleotide resolution is not in the root of the Nanopore mechanism. But still could someone give me a thorough explanation or point me to a reference paper or something?

My specific questions are:

1. In my `calculate_methylation_frequency.py` output, ~85% lines have a single CpG and the rest can have up to ~50 CpGs. Which factor(s) determine which neighboring CpGs are clustered for methylation calling?

2. How is the "group_sequence" determined when there are multiple reads mapped? I imagine that the signaling portions are different between the reads.

3. Could I assume that the clustered CpGs have similar methylation status?

4. When I run `calculate_methylation_frequency.py` with the `-s` parameter, it splits the multi-CpG record into one line per CpG. When it does the splitting, does it always equally split the read counts (for both total counts and methylated counts) and keep exactly the same methylation frequency across all the clustered CpGs?

5. Should I assume the CpGs that are clustered in methylation calling have less accurate data than the single CpGs? If so, I will consider using only the single CpGs for my downstream analysis (allele-specific methylation).

Thanks.

**Comment by jts** [comment]
Hi @weishwu,

The technical details of how (and why) we must cluster CpGs together can all be found in our [2017 paper](https://pubmed.ncbi.nlm.nih.gov/28218898/). The reason, as you found, is due to how we model the data and the type of training data we used, which methylates the entire genome. You may wish to use the basecaller's (dorado) methylation caller as it does not have this limitation.

Jared

**Comment by weishwu** [comment]
Thanks!
