### ISSUE TITLE
Can't find the calculate_methylation_frequency.py 

### ISSUE THREAD

**Issue by kjs13** [jts/nanopolish#1091]
Hello, I have tried to use the Nanopolish to find the DNA methylation. 
After the run, it successfully built the methylation_call.tsv. 

But for the next step, I tried to find the py file, but I can't find the calculate_methylation_frequency.py from the example from the call-methylation tutorial. I re-installed the example files twice, but I still don't see the calculate_methylation_frequency.py

Any help on the same will be appreciated.

Thanks,

Samuel

**Comment by jts** [comment]
Hi,

The script is here: https://github.com/jts/nanopolish/blob/master/scripts/calculate_methylation_frequency.py

Jared

**Comment by kjs13** [comment]
Thank you for the quick reply! However, it keeps making weird output instead of example output. 

When I use 
'scripts/calculate_methylation_frequency.py methylation_calls.tsv > methylation_frequency.ts'
 command in the directory that has the data, it saids there is no command. 
 
 Therfore, I used "nanopolish scripts/calculate_methylation_frequency.py methylation_calls.tsv > methylation_frequency.ts", it makes this output

usage: nanopolish [command] [options]
  valid commands: 
    --help
    --version
    call-methylation
    detect-polyi
    eventalign
    fast5-check
    help
    index
    methyltrain
    phase-reads
    polya
    scorereads
    variants
    vcf2fasta
  for help on given command, type nanopolish command --help

May I ask what mistake am I making? 

Thanks,

Samuel
