### ISSUE TITLE
big output file after nanopolish eventalign 

### ISSUE THREAD

**Issue by VikArz02** [jts/nanopolish#1093]
Hello!

I use this code:
nanopolish eventalign --reads reads.fastq --bam reads-ref.sorted.bam --genome transcript.fa --scale-events --signal-index --summary > read.eventalign.txt

And my output file is more than 500gb. Is it okey?

reads-ref.sorted.bam 3.5 gb
reads.fastq 5.7 gb
fasta5 files 169 gb

**Comment by VikArz02** [comment]
I found this to be ok. So, I want to ask, do you have some kind of "formula" for calculating how much memory is needed for the output file?

characteristics of my file:
reads-ref.sorted.bam 3.5 gb
reads.fastq 5.7 gb
fasta5 files 169 gb

**Comment by jts** [comment]
Sorry, I don't. The ratios you have are probably decent estimates.

Jared
