### ISSUE TITLE
I can't find the compare_methylation.py script and I can't download the sample data

### ISSUE THREAD

**Issue by lanyunxin** [jts/nanopolish#1096]
--2023-07-25 20:11:51--  http://s3.climb.ac.uk/nanopolish_tutorial/methylation_example.tar.gz
Resolving s3.climb.ac.uk (s3.climb.ac.uk)... 147.188.173.14
Connecting to s3.climb.ac.uk (s3.climb.ac.uk)|147.188.173.14|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://s3.climb.ac.uk/nanopolish_tutorial/methylation_example.tar.gz [following]
--2023-07-25 20:11:51--  https://s3.climb.ac.uk/nanopolish_tutorial/methylation_example.tar.gz
Connecting to s3.climb.ac.uk (s3.climb.ac.uk)|147.188.173.14|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-07-25 20:11:52 ERROR 404: Not Found.

**Comment by rdeborja** [comment]
The script and example data can be found in the following bundle:
```
warwick.s3.climb.ac.uk/nanopolish_tutorial/methylation_example.tar.gz
```
Issue reference:
https://github.com/jts/nanopolish/issues/1069

**Comment by lanyunxin** [comment]
There is only sample data in this bundle, and there is no script, please check it again, trouble

**Comment by rdeborja** [comment]
Hi @lanyunxin,

I just re-downloaded and unarchived the file and the script is in the directory:
```
$ ls -lah methylation_example/compare_methylation.py
-rwxr-x--x  1 user  staff   2.9K 14 May  2018 methylation_example/compare_methylation.py
$ tree -L 1 methylation_example
methylation_example
├── albacore_output.fastq
├── bisulfite.ENCFF835NTC.example.tsv
├── compare_methylation.py
├── fast5_files
└── reference.fasta
```

**Comment by rdeborja** [comment]
Note that I used both `wget` and `curl` to download the file.  Here are the specific commands I used to download and unarchive:

Using `wget`
```
$ wget warwick.s3.climb.ac.uk/nanopolish_tutorial/methylation_example.tar.gz
$ tar xvfz methylation_example.tar.gz
```

Using `curl`:
```
$ curl -O warwick.s3.climb.ac.uk/nanopolish_tutorial/methylation_example.tar.gz
$ tar xvfz methylation_example.tar.gz
```

**Comment by lanyunxin** [comment]
Can you send me the script directly as I really didn't find the script in the sample data

**Comment by rdeborja** [comment]
While the script should be in the root of the extracted `methylation_example` directory,  
I have submitted a PR to include the `compare_methylation.py` script as part of `nanpolish`: https://github.com/jts/nanopolish/pull/1099
