### ISSUE TITLE
0.6-dev branch build fails

### ISSUE THREAD

**Issue by johnomics** [jts/nanopolish#110]
Trying out [0.6-dev beta](https://github.com/jts/nanopolish/tree/0.6-dev) https://github.com/jts/nanopolish/commit/8be00b94182e60f8b610545a852cd81a35827a4d:
```
$ git clone --recursive https://github.com/jts/nanopolish.git
$ cd nanopolish
$ git checkout 0.6-dev
$ make
...
src/nanopolish_squiggle_read.cpp: In member function 'void SquiggleRead::_load_R9(uint32_t, const string&, const std::vector<EventRangeForBase>&, const std::vector<double>&, uint32_t)':
src/nanopolish_squiggle_read.cpp:242:28: error: 'class fast5::File' has no member named 'get_basecall_config'
         auto config = f_p->get_basecall_config(basecall_group);
                            ^
Makefile:104: recipe for target 'src/nanopolish_squiggle_read.o' failed
make: *** [src/nanopolish_squiggle_read.o] Error 1
```

Can't find any `get_basecall_config` code in the nanopolish or fast5 repositories - where does this come from?

**Comment by jts** [comment]
Hi,

When pulling a branch in git the submodules are not automatically updated. If you run `git submodule update` it should grab the latest version of `fast5` then compile.

Jared

**Comment by johnomics** [comment]
Ah, thanks - compiled and running now. Sorry to bother you with this.

**Comment by jts** [comment]
No problem, let me know if you find any issues with 0.6

**Comment by duspriya** [comment]
Hi

$ git clone --recursive https://github.com/jts/nanopolish.git
$ cd nanopolish
$ git checkout 0.6-dev
$ make
...
src/nanopolish_squiggle_read.cpp: In member function 'void SquiggleRead::_load_R9(uint32_t, const string&, const std::vector<EventRangeForBase>&, const std::vector<double>&, uint32_t)':
src/nanopolish_squiggle_read.cpp:242:28: error: 'class fast5::File' has no member named 'get_basecall_config'
         auto config = f_p->get_basecall_config(basecall_group);
                            ^
Makefile:104: recipe for target 'src/nanopolish_squiggle_read.o' failed
make: *** [src/nanopolish_squiggle_read.o] Error 1

**Comment by duspriya** [comment]
Hi,
git clone --recursive https://github.com/EvdH0/nanopolish.git
cd nanopolish; git checkout 04fd9aecbb4ab266350476b957f4abb8ed994d8d; make 

fatal: reference is not a tree: 04fd9aecbb4ab266350476b957f4abb8ed994d8d
g++ -c -fopenmp -O3 -std=c++11 -g  -fPIC nanopolish_squiggle_read.cpp
In file included from fast5/src/fast5.hpp:11:0,
                 from nanopolish_squiggle_read.cpp:11:
fast5/src/hdf5_tools.hpp:15:18: fatal error: hdf5.h: No such file or directory
compilation terminated.
Makefile:67: recipe for target 'nanopolish_squiggle_read.o' failed
make: *** [nanopolish_squiggle_read.o] Error 1

**Comment by jts** [comment]
Is there a reason you are using that version rather than the latest code? Note that the repository you are cloning is not the main nanopolish repository but a very old fork.

In any case once you fix the repo you have to run `git submodule update` after the `git checkout`.
