### ISSUE TITLE
question about multiple runs

### ISSUE THREAD

**Issue by huawen-poppy** [jts/nanopolish#1105]
Hello Jared,

I recently have three sample runs. I am wondering could I put all the output files into one folder and then run the nanopolish, or should I run the process separately on each sample?

Best,
Huawen

**Comment by jts** [comment]
Hi @huawen-poppy,

I can't answer that without more information - what are you trying to do (run eventalign, polish an assembly, etc)?

Jared

**Comment by huawen-poppy** [comment]
Hi, Jared. 

I am trying to run the eventalign.

**Comment by jts** [comment]
Then it is fine to merge all data into one folder.

**Comment by huawen-poppy** [comment]
I see, thank you for your quick response!
