### ISSUE TITLE
Is it feasible to combine runs basecalled with different models?

### ISSUE THREAD

**Issue by weishwu** [jts/nanopolish#1107]
I have the following runs that were basecalled using different guppy models. Could I simply concatenate their fastqs and fast5s for methylation calling using Nanopolish?

run | sample | base_call_model
-- | -- | --
4211P | A-1 | dna_r10.4.1_e8.2_400bps_hac@v4.2.0
4092P | A-1 | dna_r10.4.1_e8.2_400bps_hac@v3.5.2
4031P | A-1 | 2021-05-05_dna_r9.4.1_promethion_384_dd219f32
4212P | B-2 | dna_r10.4.1_e8.2_400bps_hac@v4.2.0
4093P | B-2 | dna_r10.4.1_e8.2_400bps_hac@v3.5.2

**Comment by jts** [comment]
Hi @weishwu,

Nanopolish does not support R10.4 data. I suggest you use the dorado or guppy methylation calls.

Jared

**Comment by weishwu** [comment]
OK. Thanks!
