### ISSUE TITLE
BWA command in README does not work

### ISSUE THREAD

**Issue by govinda-kamath** [jts/nanopolish#111]
The BWA mem command in the README has `-x` option which does not seem to be a legal option. What command should one run there?

<img width="725" alt="screen shot 2017-02-06 at 10 15 52 am" src="https://cloud.githubusercontent.com/assets/7320464/22660141/4a3432d4-ec55-11e6-9cfd-ccd8f7b64049.png">

**Comment by jts** [comment]
Hi,

This means your version of bwa is too old, please update to the latest.

Jared

**Comment by govinda-kamath** [comment]
Thanks. That worked.
