### ISSUE TITLE
could not find path to FAST5 for read 

### ISSUE THREAD

**Issue by mumdark** [jts/nanopolish#1111]
Hi! Thank you for developing such a great tool！

**I run the code above：**

```
nanopolish index -d $afexptdir/fast5 $afexptdir/aftest_out/*.combined.fastq

nanopolish eventalign --reads $afexptdir/aftest_out/*.combined.fastq --bam $afexptdir/out_fastq_bam/raw_data.sorted.bam --genome $refdir --summary gm2.nanopolish.sum --print-read-names --threads 3 --scale-events > $afexptdir/out_nanopolish/raw_data.gm2.nanopolish_eventAlignOut.txt
```

Then I got the following error report:

- **Error: could not find path to FAST5 for read 0000145b-a8c3-43c0-95c9-fc4a1986a2a2
Please make sure that this path is accessible: start_time=2020-10-06T08:16:56Z**

How to deal with this, thanks！

**Comment by mumdark** [comment]
#### I tested again, still not working:

### error: 

Error: could not find path to FAST5 for read 013a824f-f99f-471f-a7d1-68f46797ee00
Please make sure that this path is accessible: model_version_id=2020-09-07_rna_r9.4.1_minion_256_8f8fc47b


### code

```
guppy_basecaller -i fast5 -s output --flowcell FLO-MIN106  --kit SQK-RNA002  --cpu_threads_per_caller 12 -r
cd output
#rm combined.fastq 
cat pass/*.fastq > combined.fastq
# generate sam
sed -i 's/U/T/g' combined.fastq
minimap2 -ax map-ont -t 3 ../ref.fasta combined.fastq > combined.gm2.sam
samtools view -@ 3 -S combined.gm2.sam -b | samtools sort -o sorted.bam - ; samtools index sorted.bam

# mutil test
cd ..
nanopolish index -d fast5/ output/combined.fastq
nanopolish eventalign --reads output/combined.fastq --bam output/sorted.bam --genome ref.fasta --summary gm2.nanopolish.sum --print-read-names --threads 3 --scale-events > eventAlignOut.txt

# single test
multi_to_single_fast5 -i fast5/ -s single_fast5/ -t 3
nanopolish index -d single_fast5/0/ output/combined.fastq
nanopolish eventalign --reads output/combined.fastq --bam output/sorted.bam --genome ref.fasta --summary gm2.nanopolish.sum --print-read-names --threads 3 --scale-events > eventAlignOut.txt

```
## file dir:

![image](https://github.com/jts/nanopolish/assets/83895347/a71d0687-12f1-4a70-99be-cd58c4e530bc)

---

### this read exist:
![image](https://github.com/jts/nanopolish/assets/83895347/f69c1467-bc79-42e3-ab34-c9898f7b6592)

**Comment by mumdark** [comment]
#### I found the answer here, I'll try it first:

https://github.com/jts/nanopolish/issues/583

**Comment by mumdark** [comment]
The version is  `nanopolish   Version  0.4.0`

**Comment by mumdark** [comment]
#### I run the `nanopolish index` as follow, there are no messages at all.:

```
nanopolish index -d fast5/ output/combined.fastq
```

#### No error is reported here, but no index-related files are generated in the directory:

![image](https://github.com/jts/nanopolish/assets/83895347/cb88d687-7a98-4cdb-834e-dc71b664cd40)

**Comment by hasindu2008** [comment]
@mumdark 

Try indexing using [f5c](https://github.com/hasindu2008/f5c/) to index and see if there is an error.
```
f5c index -d fast5/ output/combined.fastq --iop 3 -t 3
```

Nanopolish and f5c index are intercompatible.

**Comment by mumdark** [comment]
Thanks so much! @hasindu2008 

I used the nanopolish software from a lab colleague, and `nanopolish index` worked. The issues might have arisen from the software I previously installed via conda.
