### ISSUE TITLE
Compare the nanopolish methyaltion output with bismark output to analysis the correlation

### ISSUE THREAD

**Issue by Modernism-01** [jts/nanopolish#1114]
Hi, I followed the instructions for calling methylation with nanopolish (https://nanopolish.readthedocs.io/en/latest/quickstart_call_methylation.html#calling-methylation). when I use script (compare_methylation.py) to compare the bismark output with nanopolish. But I got confused with the data structure of an example, like bisulfite.ENCFF835NTC.example file：

Chromosome Name | Start Position | End Position | ? | ? | Strand | Start Position | End Position | ? | ?| ?
chr20 | 5000104 | 5000105 | . | 13 | + | 5000104 | 5000105 | 55,255,0 | 13 | 15
chr20 | 5000105 | 5000106 | . | 17 | - | 5000105 | 5000106 | 105,255,0 | 17 | 18
chr20 | 5000224 | 5000225 | . | 20 | + | 5000224 | 5000225 | 0,255,0 | 20 | 5
chr20 | 5000225 | 5000226 | . | 14 | - | 5000225 | 5000226 | 0,255,0 | 14 | 0
chr20 | 5000236 | 5000237 | . | 20 | + | 5000236 | 5000237 | 0,255,0 | 20 | 5
chr20 | 5000237 | 5000238 | . | 15 | - | 5000237 | 5000238 | 0,255,0 | 15 | 0

Could you tell me what the meaning of the each columns is? like " 55,255,0 | 13 | 15", and how can I prepare the input for comparing process according to the bismark_methylation_extraction output? 

Thank you very much!

**Comment by jts** [comment]
The description of this file can be found on this page: https://www.encodeproject.org/data-standards/wgbs/
