### ISSUE TITLE
Nanopore reads that have been double basecalled

### ISSUE THREAD

**Issue by AsclepiusDoc** [jts/nanopolish#112]
Hello all,

I am currently trying to use nanopolish on some canu assemblies. However, looking back at the Metrichor basecalled reads I realized that some of my reads were double basecalled, one from MinKNOW and one from Metrichor. Knowing that nanopolish uses the original reads to "polish" the assembly would this double basecall become an issue? Thank you for your time.

Best,

Alex

**Comment by jts** [comment]
Hi Alex,

If you use `nanopolish extract` to convert the `fast5` files to fasta, it should be ok.

Jared

**Comment by AsclepiusDoc** [comment]
Hello Jared,

Thank you for the quick input, we will go ahead and try it. I do have one more question, is nanopolish compatible with the new R9.4 chemistry?

Best,

Alex

**Comment by jts** [comment]
Hi Alex,

The `0.6-dev` branch supports R9.4 reads. If you check that branch out it should work on your reads. Note that the 0.6-dev README is different as I made nanopolish easier to run.

Jared
