### ISSUE TITLE
How does call-methylation work?

### ISSUE THREAD

**Issue by isnmn** [jts/nanopolish#1120]
Hi,
I may missed that in the documentation but I have several questions about how call-methylation pipeline works:

- Does nanopolish use some sort of background noise to calculate methylation frequency?
- How are log_lik_meth or _demeth calculated? What type of data or information is used for this calculation?
- For example if log_lik_ratio is 1 does that mean the methylation in that region is equal to the background noise? Or is it equal to genome-wide methylation frequency? 

Could you please elaborate more? I couldn't find detailed information about these and without knowing it's not scientifically correct or easy to interpret the results.

**Comment by jts** [comment]
Hi,

Please see our paper describing the method, which describes the procedure in detail: https://www.nature.com/articles/nmeth.4184

Jared

**Comment by isnmn** [comment]
so can you correct me if i'm wrong? as far as i understood, the log_lik_ratio > 0 means methylation but does log_lik_ratio < 0 means demethylation or no methylation changes at all?

**Comment by jts** [comment]
< 0 means that the signal looks more like the canonical (C, not methylated) base
