### ISSUE TITLE
Error installing dependencies?

### ISSUE THREAD

**Issue by ZachChua** [jts/nanopolish#1122]
Hi, 

I am trying to set up nanopolish on Windows 10:

I have successfully downloaded the latest version from github as follows:
 git clone --recursive https://github.com/jts/nanopolish.git

But when I enter the following:
cd nanopolish
make

The following errors appear:
process_begin: CreateProcess(NULL, uname -s, ...) failed.
if [ ! -e hdf5-1.8.14.tar.gz ]; then \
                version_major_minor=`echo "1.8.14" | sed -E 's/\.[0-9]+$//'`; \
                wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-${version_major_minor}/hdf5-1.8.14/src/hdf5-1.8.14.tar.gz; \
        fi
! was unexpected at this time.
make: *** [lib/libhdf5.a] Error 255

I am unsure what I'm doing wrong. It'll be great if I could get some help regarding this.
Thank you.

Zachary Chua

**Comment by jts** [comment]
Sorry but nanopolish does not work on Windows.

**Comment by ZachChua** [comment]
Thanks for the clarification!
