### ISSUE TITLE
Running 5 hours with the empty error.txt and empty .vcf output files.

### ISSUE THREAD

**Issue by JWang52md** [jts/nanopolish#1126]
I run nanopolish variants on HPC, it went well and about 5 hours later it finished running. However, the .vcf file was empty and error files was also empty. I even don't know how to troubleshoot. Even more, I run another assembles of the same strains using nanopolish variants, it generated the .vcf files that I want. Could someone have the same experiences? could you please give me a solution?

**Comment by JWang52md** [comment]
I run  Nanopolish variants on 8 assemblies with the same script, only 5 successed, the other 3 failed with empty .vcf and empty error.txt files.

**Comment by jts** [comment]
Nanopolish variants is now largely deprecated, and you will likely get better results from medaka or clair3. This is especially true for R10.4.1 data, which nanopolish variants does not support. If you have a specific reason for using nanopolish let me know and I will try to help look at this issue.
