### ISSUE TITLE
Problem with eventalign

### ISSUE THREAD

**Issue by MarioRinBarr** [jts/nanopolish#1128]
Hi,

I am writing to you because I have a problem with nanopolish. When using eventalign it is not able to align most reads, so in the end all reads fail, for one reason or another:
[post-run summary] total reads: 69721, unparseable: 0, qc fail: 190, could not calibrate: 8740, no alignment: 60749, bad fast5: 281
Do you know why this is happening? 

Thank you,
Mario

**Comment by jts** [comment]
I suspect you are using R10 reads, which nanopolish does not support

**Comment by MarioRinBarr** [comment]
Uffff, you are right, I am using R10 reads... Do you know if there is a method to transform R10 reads into R9? 
Thank you very much!

**Comment by hasindu2008** [comment]
@MarioRinBarr You may try [f5c](https://github.com/hasindu2008/f5c/) which an optimised reimplementation of nanopolish which has an r10 model.
