### ISSUE TITLE
Nanopolish with pod5 files

### ISSUE THREAD

**Issue by DIPLOMICS-SA** [jts/nanopolish#1129]
Hi there,
is nanopolish compatible with pod5 files produced by the promethIon?

**Comment by jts** [comment]
Sorry, nanopolish does not support pod5s. I planned to do this but since there are better options available for most things nanopolish does it wasn't a development priority.

**Comment by Salvobioinfo** [comment]
Hi @jts 
Based on your response, can you recommend a tool that can perform a similar function to nanopolish event align, starting from pod5, and produce a similar output (especially when the option --samples is active)?  
Thanks in advance.

**Comment by jts** [comment]
I believe both f5c and uncalled4 can. Or you can use ONT's conversion tools to generate fast5 from pod5.

**Comment by hasindu2008** [comment]
Yes. [f5c](https://github.com/hasindu2008/f5c/) can as long as the POD5 are converted to BLOW5 using [bluecrab](https://github.com/Psy-Fer/blue-crab).

 Nanopolish also supports BLOW5, so if you convert to BLOW5 using bluecrab, you can either use nanopolish or f5c.
