### ISSUE TITLE
IUPAC::isValid(out[i]) failed error

### ISSUE THREAD

**Issue by govinda-kamath** [jts/nanopolish#113]
On running nanopolish I seem to get following error:

```
govinda@shannon$ nanopolish eventalign -t 8 --sam -r reads.fa -b reads.sorted.bam -g draft.fa --models nanopolish_models.fofn | samtools view -Sb - | samtools sort -o reads.eventalign.sorted.bam
registering model t.007-base
registering model t.007-ONT
nanopolish: src/common/nanopolish_alphabet.h:173: virtual std::string Alphabet::disambiguate(const string&) const: Assertion `IUPAC::isValid(out[i])' failed.
```

I did make sure that both reads.fa and draft.fa have all bases in capitals (from issues #67 and #83). Do you know what I must do to get this working?

**Comment by jts** [comment]
Hi,

Could you send me draft.fa so I can try to reproduce the problem locally?

Jared

**Comment by govinda-kamath** [comment]
I've attached the file
[draft.fa.zip](https://github.com/jts/nanopolish/files/761587/draft.fa.zip)

**Comment by jts** [comment]
could you try to grab a stack trace in gdb for me?

**Comment by lpryszcz** [comment]
I had similar issue with nanopolish. Innitially I had non-ACGT chars in the reference FastA. I removed them, but the nanopolish was still failing. 
It turned out the issue was due to **an old Fasta index `.fai`** - once I removed it everything worked just fine.

**Comment by jts** [comment]
Thanks for the feedback @lpryszcz, that's good to know.
