### ISSUE TITLE
Docker Build Error

### ISSUE THREAD

**Issue by tutkuiince** [jts/nanopolish#1131]
Hi,

Make command after cloning the repository worked without any errors. However, i got these following errors after i used "docker build ." inside the local nanopolish repository.

![image](https://github.com/jts/nanopolish/assets/137634569/c16c827c-a1e2-43f6-a1e5-6780f76e946b)

**Comment by jts** [comment]
Sorry about this. The docker build is quite old and not maintained. It looks like a library needs to be installed (libbz2) to make it build with docker.
