### ISSUE TITLE
Nanopolish Call-methylation error

### ISSUE THREAD

**Issue by bebert30** [jts/nanopolish#1133]
Hello, thank you for creating this useful tool. I am trying to call methylation on aligned .bam files using these options: 

nanopolish call-methylation -t 40 -r ../FASTQs/refs/mm10.fa -b wt/wt_aligned.sorted.bam -q cpg -o wt_meth.methylation.tsv. 

I am encountering an error that requires a --genome in this command. When I include the -g indexed reference file, I get another error that says the reference needs to be indexed with nanopolish index. However, I can't get nanopolish index to work on a non Fast5 file (the refs are in FASTA format). 

Any advice would be greatly helpful! Many thanks!

**Comment by jts** [comment]
The reference genome needs to be indexed by samtools. You can run `samtools faidx <genome.fa>` to generate it.
