### ISSUE TITLE
can nanopolish work without a genome alignment?

### ISSUE THREAD

**Issue by haannguyen** [jts/nanopolish#1134]
Hello,

I am working with a short synthetic RNA and looking at the polyA tail by Nanopore sequencing.  Is there a way to run nanopolish on a sequence that does not align to a reference genome?

Thank you!

Yours,
Ha An

**Comment by jts** [comment]
The bam file is required. You can try to align the reads to the synthetic genome to generate one.

**Comment by haannguyen** [comment]
Thank you!
