### ISSUE TITLE
nanopolish variants vs freebayes

### ISSUE THREAD

**Issue by emilydolivo97** [jts/nanopolish#1135]
Hello , 

**I have 11 FASTQ files. I have already used FreeBayes to detect variants. For this purpose, I utilized the following command for each FASTQ.gz file:**

freebayes -f user/ref_genome/reference_sequence.fa -L SRAXXXX87.fastq.gz --vcf SRAXXX87.vcf --ploidy 2 --min-alternate-fraction 0.05

**Now, I want to know what s the equivalent of this command using Nanopolish. Is it nanopolish variants --consensus or nanopolish variants without consensus? 
If it is, how do I use it please?**

I hope that you could help me !!**

**Comment by jts** [comment]
Nanopolish requires the raw signal data in fast5 format. If you only have fastq you can't use nanopolish.
