### ISSUE TITLE
Nanopolish polyA on RNA004 data

### ISSUE THREAD

**Issue by rugilemat** [jts/nanopolish#1136]
Hi,

I want to estimate the polyA length in my direct RNA samples but they're run with RNA004 kit and new RNA flow cells. I've used `f5c` for indexing and event aligning for my other applications, so I'm just wondering if `nanopolish polyA` would be compatible with this?

**Comment by jts** [comment]
Hi,

Sorry but RNA004 is not supported by the poly-A tail caller since dorado now estimates poly-A tail lengths.

Jared

**Comment by rugilemat** [comment]
I see, thanks for such a quick response!
