### ISSUE TITLE
nanopolish with fastq

### ISSUE THREAD

**Issue by mocherry** [jts/nanopolish#1138]
Dear all,

I have a naive question:
does nanopolish eventalign run with reads as fastq-file?

Thanks and best,
Matthias

**Comment by jts** [comment]
It takes fastq as input, but requires the signal files (fast5) as well. It will not work with only fastq.

**Comment by mocherry** [comment]
Hi JTS,

sorry. I have the fast5-files but was not sure whether in addition fasta or fastq is needed.

Thanks a lot,
Matthias

**Comment by jts** [comment]
fastq is fine
