### ISSUE TITLE
does nanpolish work with RNA004

### ISSUE THREAD

**Issue by mocherry** [jts/nanopolish#1139]
Dear all,

I would like to know if I can use data from direct RNA sequencing with nanopolish from sequencing runs with: 
protocol=sequencing/sequencing_PRO004RA_RNA:FLO-PRO004RA:SQK-RNA004:130
Flow cell type
FLO-PRO004RA
SQK-RNA004

Thanks and best,
Matthias

**Comment by jts** [comment]
No, sorry but it does not.

**Comment by mocherry** [comment]
Too bad, so what can I do?

**Comment by hasindu2008** [comment]
@mocherry 
You may try [f5c](https://github.com/hasindu2008/f5c/) which is an optimised implementation of nanopolish, which currently has an rna004 model .

**Comment by mocherry** [comment]
o.K. but what does it mean then if nanopolish eventalign produces an output file which actually contains information and can be used with m6anet. Are the results the most likely rubbish?

**Comment by jts** [comment]
Yes, the results would be unreliable in that case
