### ISSUE TITLE
Does Nanopolish still not support R10.4.1 for methylation analysis

### ISSUE THREAD

**Issue by Taylorain** [jts/nanopolish#1147]

**Comment by jts** [comment]
It does not. Dorado provides more accurate methylation calls in more contexts. Also, the nanopolish approach is implemented in f5c, which supports r10.4.1 data.

**Comment by Taylorain** [comment]
I get!
Thanks very much!



---Original---
From: "Jared ***@***.***&gt;
Date: Fri, Sep 27, 2024 20:11 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jts/nanopolish] Does Nanopolish still not support R10.4.1 formethylation analysis (Issue #1147)




 
It does not. Dorado provides more accurate methylation calls in more contexts. Also, the nanopolish approach is implemented in f5c, which supports r10.4.1 data.
