### ISSUE TITLE
nanopolish eventalign slow processing speed

### ISSUE THREAD

**Issue by vetmohit89** [jts/nanopolish#1148]
Hello, 

I am using following command to run nanopolish eventalign but it is very slow. 

```
nanopolish eventalign \
--reads ./index/*.fastq \
--bam ./sorted_PF_NCBI_reference.bam \
--genome ./GRCh38_latest_rna.fna \
--signal-index \
--scale-events \
--summary ./PF/sequencing_summary.txt \
--threads=48 > ./PF_CHEUI_NCBI_output_R1.txt

```
Here is the job script with computation allocation:
```
#SBATCH --nodes=1
#SBATCH --mem=128G
#SBATCH --cpus-per-task=48
```

I am wondering if there is anything I can do to speed up the process. 

Thank you
Mohit

**Comment by jts** [comment]
You can partition the BAM into smaller pieces, then merge the results. Also, https://github.com/hasindu2008/f5c may be faster.
