### ISSUE TITLE
nanopolish eventalign taking to much time to finish...

### ISSUE THREAD

**Issue by baibhav-bioinfo** [jts/nanopolish#1149]
in my case i ran the nanopolish eventalign, but it is taking to much time to finish...and 
So, i had to chunk the original fastq into 10 parts (Will merge the eventalign.txt later for subsequent analysis)

then i had to reindex for each part.fastq. 
but then the eventalign is not working, giving warning of skipping several fast5's.

i can see the issue can be with indexing,
the readdb file i can see is still containing as much number of rows (~reads) as in original undivided fastq.

is there anyway i can pull of the eventalign commands with these 10 parts and merge together eventalign.txt for further analysis with xpore?

**Comment by jts** [comment]
You should partition the bam file into smaller chunks, not the fastq. Yes, you can merge the resulting txt files together.
