### ISSUE TITLE
Does nanopolish polya support cDNA sequencing? "noregion" problem

### ISSUE THREAD

**Issue by Xing-2024** [jts/nanopolish#1150]
Hi, 

Recently I tried to use this program to run cDNA sequence data (kit: SQK-PCB111.24), but encounter a problem just like https://github.com/jts/nanopolish/issues/545. the running result show a lot of noregion. 

Any suggestion?

Thank you.

Xing

**Comment by jts** [comment]
Sorry, it does not support cDNA.

**Comment by Xing-2024** [comment]
OK, thanks.Xing On Oct 10, 2024, at 12:47, Jared Simpson ***@***.***> wrote:﻿
Sorry, it does not support cDNA.
