### ISSUE TITLE
Assertion `read_to_path_map.find(seq->name.s) == read_to_path_map.end()' failed

### ISSUE THREAD

**Issue by nidafra92** [jts/nanopolish#117]
Hello:

I'm running an example using the lines in the README and using  Loman et al. 2015 E. coli reads as input.

` nanopolish eventalign -t 2 --sam -r /home/nfranco/Documents/Nanopore/Loman_Data/canudata/polishing/oxford.fasta -b /home/nfranco/Documents/Nanopore/Loman_Data/canudata/polishing/reads.sorted.bam -g /home/nfranco/Documents/Nanopore/Loman_Data/canudata/polishing/ecoli.contigs.fasta --models nanopolish_models.fofn | samtools view -Sb - | samtools sort -o /home/nfranco/Documents/Nanopore/Loman_Data/canudata/polishing/reads.eventalign.sorted.bam - `

And I got this error:

```
registering model t.007-base
registering model t.007-ONT
nanopolish: src/common/nanopolish_fast5_map.cpp:84: void Fast5Map::load_from_fasta(std::string): Assertion `read_to_path_map.find(seq->name.s) == read_to_path_map.end()' failed.
Aborted (core dumped)  
```

I'm using Ubuntu 16.04 and I compiled nanopolish using gcc version 4.8.5 (Ubuntu 4.8.5-4ubuntu2).

I would appreciate any help with this issue.

Thanks.

**Comment by jts** [comment]
Hi,

When nanopolish reads in the `fasta` file, it builds a map from the read name to the path of the `fast5` file (which contains the event information). This assertion means that when it tried to build this map, it found a duplicate read name. This is not allowed - what program did you use to extract the reads from the fast5 files?

Jared

**Comment by nidafra92** [comment]
Hello Jared:

Thanks for your answer.

I'm using nanopolish extract as follows:

```
nanopolish extract -o nanopore_reads.fasta -r /home/nfranco/Documents/Nanopore/Loman_Data/RawData/flowcells/

```
This is the folder structure:
./flowcells
├── flowcell_20
│   └── 1.9
│       └── downloads
│           └── pass [8451 entries exceeds filelimit, not opening dir]
├── flowcell_32
│   └── downloads
│       └── pass [5639 entries exceeds filelimit, not opening dir]
├── flowcell_33
│   └── downloads
│       └── pass [2855 entries exceeds filelimit, not opening dir]
└── flowcell_39_K12_Histag
    └── downloads
        └── pass [5325 entries exceeds filelimit, not opening dir]

I followed this procedure:

```

# Index the draft genome
bwa index ecoli.contigs.fasta
# Align the reads in base space
bwa mem -x ont2d -t 4 ecoli.contigs.fasta nanopore_reads.fasta | samtools view -Sb - | samtools sort -o reads.sorted.bam -
samtools index reads.sorted.bam
# Align the reads in event space
nanopolish eventalign -t 4 --sam -r nanopore_reads.fasta -b reads.sorted.bam -g ecoli.contigs.fasta --models nanopolish_models.fofn | samtools view -Sb - | samtools sort -o reads.eventalign.sorted.bam -

```

After 'eventalign' I'm still getting this:
```
registering model t.007-base
registering model t.007-ONT
nanopolish: src/common/nanopolish_fast5_map.cpp:84: void Fast5Map::load_from_fasta(std::string): Assertion `read_to_path_map.find(seq->name.s) == read_to_path_map.end()' failed.
Aborted (core dumped)
```

I checked my file for any repetitions on read names, but I could not find any.

Headers in FASTA file look like this:

```
>channel_40_read_90:2D_000:2d LomanLabz_PC_K12_0.4SPRI_Histag_2004_1_ch40_file98_strand /home/nfranco/Documents/Nanopore/Loman_Data/RawData/flowcells/flowcell_39_K12_Histag/downloads/pass/LomanLabz_PC_K12_0.4SPRI_Histag_2004_1_ch40_file98_strand.fast5

```
I'm using Samtools  version 1.3.1 and bwa 0.7.12-r1039.

Any clue about this or any suggestion?

Thanks.

**Comment by jts** [comment]
Hi,

That dataset is very old and it was generated before ONT switched to unique read IDs across runs. This is the source of the name collision. I suggest that you switch to a more recent R9 run for your tests, like this one:

http://lab.loman.net/2016/07/30/nanopore-r9-data-release/

Jared
