### ISSUE TITLE
unable to make latest version / can't find variants with 0.5

### ISSUE THREAD

**Issue by proukakis** [jts/nanopolish#118]
hello I have struggled on and off for some time, almost getting there..

1) trying to install latest version on my mac os x el capitan. I get the same error I was getting with 0.5, and I had solved it with  advice which allowed me to use gcc compiler "brew install gcc --without-multilib", then "brew install nanopolish --cc-gcc-6"- but this is the homebrew version, which is not updated yet
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated
clang: error: unsupported option '-fopenmp' (this line repeated many times)
make: *** [.depend] Error 1

maybe there's a way to force it to use a different compiler with make? I have gcc6.2 installed via home-brew, but I cant work it how to get it to be used by make.

2) using v0.5 on a modified hg19 used by our NGS team. We are interested in variant calling, not reference sequence refinement. We did
- poretools -> fasta
- graphmap 
- eventalign
nanopolish eventalign --sam -r BC01kapa2.poretools.fa -b BC01_K2sorted.bam -g human_hg19_mod.fa --models nanopolish_models.fofn | samtools sort > BC01kapa2.eventalign.sorted.bam
samtools index BC01kapa2.eventalign.sorted.bam
- variant call
nanopolish variants --reads BC01kapa2.poretools.fa -o BC01kapa2_mel_spcreg.nanopolish.vcf -b BC01_K2sorted.bam -e BC01kapa2.eventalign.sorted.bam -g human_hg19_mod.fa -vv -w "1:150000000-160000000" --models nanopolish_models.fofnn

the problem is clearly the -w, which I dont understand. This runs 

registering model t.007-base
registering model t.007-ONT
TODO: train model
TODO: filter data

and returns a blank vcf, while there are clear SNPs here, so I dont know if the command is wrong, or something with the reference, or the event aligned bam, or... 

We have tried 
- using the genome name after -w, and it doesnt work
nanopolish variants --reads BC01kapa2.poretools.fa -o BC01kapa2_mel_spcreg.nanopolish.vcf -b BC01_K2sorted.bam -e BC01kapa2.eventalign.sorted.bam -g human_hg19_mod.fa -vv -w "human_hg19_mod.fa:chr1:150000000-160000000" --models nanopolish_models.fofn
registering model t.007-base
registering model t.007-ONT
TODO: train model
TODO: filter data
[fai_fetch_seq] The sequence "human_hg19_mod.fa" not found

- omitting -w , same error

- aligning with BWA mem, same problem

any help welcome!

**Comment by jts** [comment]
Hi,

The syntax of the first command you ran is correct, I think. Nanopolish
requires a minimum depth of around 20X to call SNPs - is your sequencing
data deep enough?

You can force OSX to compile with gcc/g++ by running make like this:

make CC=gcc-{version} CXX=g++-{version}

where {version} is the version number you have installed.

Jared

**Comment by proukakis** [comment]
Thank you again Jared!

1. 0.6-dev. Still can't install, perhaps it is too much to expect. The command works for the 0.5 master as you said. the error now is  ( i can post more if it will help)

/usr/include/unistd.h:701:14: note: suggested alternatives:
In file included from /usr/include/sys/types.h:108:0,
                 from ./include/H5public.h:40,
                 from ./include/hdf5.h:24,
                 from ./fast5/src/hdf5_tools.hpp:28,
                 from ./fast5/src/fast5.hpp:18,
                 from src/nanopolish_extract.h:12,
                 from src/nanopolish_extract.cpp:6:
/usr/include/sys/_types/_gid_t.h:30:24: note:   'hdf5::gid_t'
 typedef __darwin_gid_t gid_t;
                        ^~~~~
/usr/include/sys/_types/_gid_t.h:30:24: note:   'hdf5::gid_t'
make: *** [src/nanopolish_extract.o] Error 1

2. the results are interesting, it finds some indels (probably not real) if I use the --fix homopolymers , but not the homozygous and het SNPs. I have aligned the same ~100x R9 data with BWA and graphmap, and BWA looks better, although a couple of reads less seem to align. 
We have a couple of higher coverage samples so can try them.
The main thing is that we have most of our 12 samples done on 2 or 3 flow cells, but a mix of R7 and R9 chemistry. We have merged the bam files and used them on IGV. What I was hoping is to use v0.6 on the merged bam file with the mixed chemistry fast5 data, to allow easy calls with the higher coverage- but perhaps this won't work!

anyway, i finally have a sense of achievement, but if we can get it to call the SNPs it will be great.

**Comment by jts** [comment]
You'll need to use 0.6-dev for calling hets. The 0.6-dev branch doesn't have the `hid_t` fix that I made - I'll port this change and it should compile for you.

**Comment by jts** [comment]
I've just made the change on `0.6-dev`. Could you grab the latest and try it?

**Comment by proukakis** [comment]
I am very sorry but i am not sure if i have managed to get 0.6-dev. 

I have tried git clone -b 0.6-dev, but I still seem to get 0.5. 
I then downloaded the zip file from the 0.6 page and it didnt work (some folders were empty). 
I then looked at a previous thread and did

git clone --recursive https://github.com/jts/nanopolish.git
cd nanopolish
git checkout 0.6-dev
   M fast5
   Branch 0.6-dev set up to track remote branch 0.6-dev from origin.
   Switched to a new branch '0.6-dev'
 git submodule update --recursive
    Submodule path 'fast5': checked out '0e1bfb1079151e14837373dd2f8df8e2850f7a43'
make CC=gcc-6 CXX=g++-6

then when I do nanopolish --help  i dont get the new commands (no extract- shouldn't that be there?) 
and then
nanopolish variants --version
variants Version 0.5.0
Written by Jared Simpson.

so does this mean I am still compiling 0.5? I dont get how this is happening....

**Comment by jts** [comment]
No, this is my fault, I haven't updated the version number for that branch yet.

**Comment by proukakis** [comment]
ok thanks, so does this mean I do have 0.6-dev now? Shouldnt i be seeing -extract as a command ( I dont need it right now, just checking).
anyway, running the same sample with the reinstalled version still doesnt find the SNPs/ I will try a couple with higher coverage and see

**Comment by jts** [comment]
Yes you should have extract, and phase-reads commands with 0.6.

For SNP calling coverage is the key, I suggest trying to find a region with at least 30X coverage that contains a known SNP and only calling on that region using the `-w` option. If it doesn't work let me know.

Jared

**Comment by proukakis** [comment]
ok will do

**Comment by jts** [comment]
0.6 also does not require the `--models` file, so if `nanopolish variants` asks for it you don't have the right version running.

**Comment by proukakis** [comment]
so, it works!!!! I had the old 0.5 home-brew install I had forgotten about, s fine once I removed it

and it's calling my SNPs! Will try to phase them next, and compare bwa and graphmap alignments

before closing this, can I ask you one thing- this now works for r7 and r9 right? Will this work if they are mixed? I have bam files merged from r7 and r9 alignments- can I event align and use this do you think? I guess I have nothing to lose by trying.

Thank you!!!

**Comment by jts** [comment]
Great! I'm very happy to hear it works now, sorry for the difficulties getting it to run.

It should work with R7 and R9 data mixed. Note you no longer have to run eventalign before `nanopolish variants` (the `-e` parameter is no longer needed)
