### ISSUE TITLE
[alignmentdb] error

### ISSUE THREAD

**Issue by gligong** [jts/nanopolish#119]
I ran nanopolish-dev0.6.0 with a draft assembly constructed by Canu assembler. One of the contigs got following error messages:
[alignmentdb] error: requested coordinates [150161 150241] is outside of region boundary [99960 150240]

Therefore, it did not create consensus segment. This error is repeatable for the same contig.

**Comment by mw55309** [comment]
Hi

Just to note that I also see this, also from Canu.

I have two contigs which fail:

nano.tig00000022.1450000-1500200.sh.e2115371:[alignmentdb] error: requested coordinates [1500154 1500241] is outside of region boundary [1449960 1500240]
nano.tig00011452.900000-950200.sh.e2115428:[alignmentdb] error: requested coordinates [950129 950241] is outside of region boundary [899960 950240]

Neither have produced polished data.  Both have produced some tabular output.

Every other segment across two contigs has successfully finished.

I'm on the latest branch, cloned yesterday

Cheers
Mick

**Comment by jts** [comment]
Ok, thanks for the note. I'll look into it.

**Comment by gligong** [comment]
Hi Mick,

Jared told  me to use –min-candidate-frequency 0.2, and it worked.
Good luck!

George

**Comment by mw55309** [comment]
OK this worked for one of my errors but not the other one.

Should I try  –min-candidate-frequency 0.3 ??

What is this actually doing?

**Comment by jts** [comment]
I'll try to fix this today but I might need some help. I think nanopolish is trying to make a correction too close to the end of a contig. --min-candidate-frequency is just hiding the error but reducing the number of corrections it tries to make, I need to fix it properly.

**Comment by jts** [comment]
Mick could you send me the stderr/stdout logs, preferably with with `-vvvvv` option added if possible?

**Comment by jts** [comment]
I've just pushed a candidate fix in 3b2c032. Could you test it and let me know if the issue is fixed?
