### ISSUE TITLE
nanopolish_makerange.py

### ISSUE THREAD

**Issue by ematlab** [jts/nanopolish#120]
Hi,
everything went ok until we run makerange.py scrypt:

`paola@PC:$` python /home/paola/nanopolish/scripts/nanopolish_makerange.py /home/paola/hg19/CHRLLC.fa | parallel --results nanopolish.results -P 8 /home/paola/nanopolish/nanopolish variants --consensus polished.{1}.fa -o polished.{1}.vcf -w {1} -r LLC01.fa -b LL01.sorted.bam -g /home/paola/hg19/CHRLLC.fa -e LLC01.eventalign.sorted.bam -t 4 --min-candidate-frequency 0.1 --models nanopolish_models.fof`

We got the following error:

`mkdir nanopolish.results/1/CHR2:0-50200: Invalid argument at /usr/bin/parallel line 3745.
Traceback (most recent call last):
  File "/home/paola/nanopolish/scripts/nanopolish_makerange.py", line 16, in <module>
    print "%s:%d-%d" % (name, n, n + SEGMENT_LENGTH + OVERLAP_LENGTH)
IOError: [Errno 32] Broken pipe`

Any suggestion?

Thanks in advance

**Comment by jts** [comment]
Hi,

Could you attach the output of this command:

```
python /home/paola/nanopolish/scripts/nanopolish_makerange.py /home/paola/hg19/CHRLLC.fa
```

Thanks,
Jared

**Comment by georgiab7** [comment]
Hi Jared, 

I also had an issue with the nanopolish_makerange.py. 
When trying to run nanopolish as described in the Readme: 

  python nanopolish_makerange.py ~/D5/SC1_D5_canu_contigs.fasta | parallel --results nanopolish.results -p 8 \ nanopolish variants --consensus polished.{1}.fa -w {1} -r ~/D5/SC1_D5_np_complete.fasta -b reads.sorted.bam -g ~/D5/SC1_D5_canu_contigs.fasta -t 4 --min-candidate-frequency 0.1

I get a syntax error in the nanopolish_makerange.py file: 

  File "nanopolish_makerange.py", line 19
    print "%s:%d-%d" % (name, n, n_segments)
                   ^
SyntaxError: invalid syntax


I installed Nanopolish using Conda and am running this on a linux OS. 
Any help or advice on solving this would be greatly appreciated
Thank you

**Comment by jts** [comment]
Are you using python3?

Jared

**Comment by georgiab7** [comment]
Hi,

Yes I ran this in 3.6, is there something else you would suggest?

Thanks

**Comment by jts** [comment]
The script uses python2 print statements, I'll fix it tomorrow to work with
both versions. If you have python2 installed you should be able to run it
if you explicitly use python2 instead of the system default python.

**Comment by georgiab7** [comment]
Awesome thank you so much, I'll run it in a python 2 environment.

Georgia

**Comment by jts** [comment]
Fixed in 7e7c310

**Comment by ematlab** [comment]
Hi, 
thank you for your support. In our case, the problem was associated with the working path used for the analysis, although we had previously verified it. So, we have successfully solved the issue, sorry for our mail.

Paola

**Comment by jts** [comment]
OK, thanks for letting me know!

**Comment by SMcTaggart** [comment]
Hello;

I am having the same error message as Georgiab7, but am using python2.7. Here is my command and the error message:

python ~/bin/nanopolish/scripts/nanopolish_makerange.py kpc_2d_fresh_best.contigs.fasta
  File "/home/seannamctaggart/bin/nanopolish/scripts/nanopolish_makerange.py", line 14
    print "%s:%d-%d" % (name, n, length - 1)

SyntaxError: invalid syntax

Any suggestions?

Seanna

**Comment by jts** [comment]
Hi Seanna,

It looks like your version of nanopolish_makerange.py is out of date, can you update to the latest code on github?

Jared

**Comment by SMcTaggart** [comment]
Cheers Jared, That has cleared the syntax error message.
Seanna
