### ISSUE TITLE
coredump when running nanopolish eventalign

### ISSUE THREAD

**Issue by peterbjarke** [jts/nanopolish#123]
In the step nanopolish eventalign -t 8 --sam -r reads.fa -b reads.sorted.bam -g draft.fa --models nanopolish_models.fofn 

I get 

registering model t.007-base
registering model t.007-ONT
nanopolish: src/common/nanopolish_fast5_map.cpp:84: void Fast5Map::load_from_fasta(std::string): Assertion `read_to_path_map.find(seq->name.s) == read_to_path_map.end()' failed.
Aborted (core dumped)

**Comment by jts** [comment]
The new version with an informative error message is now live. I'm closing this, reopen it if you still have this problem.
