### ISSUE TITLE
nanopolish make fails

### ISSUE THREAD

**Issue by JackieGOO** [jts/nanopolish#125]
Probably something simple here? 
$git clone --recursive https://github.com/jts/nanopolish.git
$cd nanopolish
$make

I get: 
src/common/nanopolish_fast5_map.cpp:10:18: fatal error: zlib.h: No such file or directory
compilation terminated.
Makefile:104: recipe for target 'src/common/nanopolish_fast5_map.o' failed
make: *** [src/common/nanopolish_fast5_map.o] Error 1

There is a nanopolish_fast5_map.cpp in the src/common/ directory

do not see any zlib.h 

What to do?

**Comment by JackieGOO** [comment]
RESOLVED: (but leaving up here to help anyone else who makes such a silly mistake) 

$sudo apt-get install zlib1g-dev
$make

**Comment by jts** [comment]
Thanks for following up with the solution, glad you were able to fix this.
