### ISSUE TITLE
Error: cannot find model with key r9_250bps.cpg.6mer.complement.pop2

### ISSUE THREAD

**Issue by cytham** [jts/nanopolish#126]
Hi,

After executing 'nanopolish call-methylation' command, I received the following notifications and the run stopped.

[fai_load] build FASTA index.
Error: cannot find model with key r9_250bps.cpg.6mer.complement.pop2

Thanks
cy

**Comment by jts** [comment]
Hi,

Sorry for leaving this so long. Right now the support for calling methylation on the complement strand is not very good since most sequencing runs are 1D. I suggest as a workaround extracting only template reads - I will fix the handling of the complement model when we have 1D^2 data.

Jared

**Comment by jts** [comment]
Fixed in  7cb2211
