### ISSUE TITLE
nanopolish on SLURM grid

### ISSUE THREAD

**Issue by jordur** [jts/nanopolish#127]
Hi Jared/all, 
I tried to use the makerange.py python script included on the scripts folder of nanopolish on a SLURM grid computer. As far as I know I provided useful files to the script with the following command line:
```
python /home/ibv/jdurban/programas/nanopolish/scripts/nanopolish_makerange.py Canu_assembly.unitigs.fasta | /home/ibv/jdurban/programas/bin/parallel --results nanopolish.results -P 4 \ nanopolish variants --consensus=polished.{1}.fa -w {1} -r Batrox_DEF.fasta -b Batrox.unitigs.sorted.bam -g Canu_assembly.unitigs.fasta -t 8
```
However, I got the following error:
```
error: cannot open Packages index using db5 - Permission denied (13)
error: cannot open Packages database in /var/lib/rpm
Traceback (most recent call last):
  File "/home/ibv/jdurban/programas/nanopolish/scripts/nanopolish_makerange.py", line 2, in <module>
    from Bio import SeqIO
ImportError: No module named Bio
```
I understand that Biopython seems not to be installed in the grid. However, what should I ask to my system administrator regarding the two lines referring to some Packages?
Thank you.

**Comment by jts** [comment]
Hi,

You just need to install biopython. If your system admin can't install this, then you can try to use a virtualenv to install it locally.

Jared

**Comment by jordur** [comment]
Ok, thanks. I asked my system admin about Bioython. I didn't know that the errors could be related.

**Comment by jordur** [comment]
Done with virtualenv ! Thank you for your suggestion!!
