### ISSUE TITLE
Protocol error at /usr/local/bin/parallel line 6548.

### ISSUE THREAD

**Issue by miles-gene** [jts/nanopolish#129]
Hello
I'm using the latest release of nanopolish and the command I've been trying is
 
python /home/miles/pac*/nanopolish/scripts/nanopolish_makerange.py 052c5363.fast5_1.fasta | parallel --results nanopolish.results -P 8 \nanopolish variants --consensus polished.{1}.fa -w {1} -r /home/miles/share2/3H6_FFPE/3H6_FFPE_SKIPPASS_METBC/3H6FFPE_ALLPASS_nanopex.fa -b bwa3H6APx052c5363_sort.bam -g 052c5363.fast5_1.fasta -t 4 --min-candidate-frequency 0.1

I get this error:
mkdir nanopolish.results/1/052c5363-8b09-4e27-8500-26f9f069e1ff_Basecall_FFPE_74528_ch280_read5940_strand_\_home\_miles\_share2\_3H6_FFPE\_3H6_FFPE_SKIPPASS_METBC\_pass\_DUMARMST4372_20170309_FNFAF18608_MN22: Protocol error at /usr/local/bin/parallel line 6548.

I thought it might be the version of parallel I'm using (20130922-1). So I installed 20161222-1 which is the release in stretch(testing) on debian. However I get the same error. Parallel seems to be working according to running through the first exersize in the parallel tutorial. I was wondering if you had any thoughts about where I'm going wrong.

Thanks for reading
Miles

**Comment by jts** [comment]
Hi,

What program did you use to make the assembly in `052c5363.fast5_1.fasta`? The contig names look odd to me.

Jared

**Comment by miles-gene** [comment]
Hi Jared
The fasta file is from canu. It's a single sequence of  ~ 83 Kbp long which is the size of the BAC insert I'm trying to nanopolish. I used bwa mem to align the reads (R9.4 1D) to the draft. I can imagine nanopolish complaining about the size of the draft if it's trying to work on 8 50Kb chunks of genome at a time. I'm surprised parallel is producing the error.
Thanks

**Comment by jts** [comment]
Hi,

The names of the sequences from canu should be named like `tig0000000N` but the names that makerange is seeing look like this:

```
052c5363-8b09-4e27-8500-26f9f069e1ff_Basecall_FFPE_74528_ch280_read5940_strand__home_miles_share2_3H6_FFPE_3H6_FFPE_SKIPPASS_METBC_pass_DUMARMST4372_20170309_FNFAF18608_MN22
```

Can you double-check the names in `052c5363.fast5_1.fasta` are correct?

Jared

**Comment by miles-gene** [comment]
Hi
I edited the contig names and ran:

python /home/miles/pac*/nanopolish/scripts/nanopolish_makerange.py 3H6contigs.fasta

9e53b521:0-50200
9e53b521:50000-83452

which seems ok? The full command results in a similar parallel error to before
mkdir nanopolish.results/1/9e53b521:0-50200: Protocol error at /usr/bin/parallel line 3745.

Do the names have to be tig0000000N format? 

Thanks

**Comment by miles-gene** [comment]
I should say the reason the name is not in tig0000000N format is that this is a corrected read generated by canu rather than a finished assembly. Canu gererated 80 such reads all ~81Kbp and the fact they all overlap by >95% seems to be preventing canu from generating a final consensus read. I thought I would try and nanopolish one such corrected read as a test. 
I have reverted back to parallel 2013 due to an annoying message about citations produced by the 2016 release, i think that's why the error message has changed. Can I assume that the problem is unlikely to be parallel related?
Thanks again
Miles

**Comment by jts** [comment]
Ok, the contig name shouldn't be the issue and the output from `nanopolish_makerange.py` looks fine. I don't know what this error from parallel means. I suggest you slowly build the command up from scratch to see if you can figure out where it breaks. Start with something very simple like:

```
python /home/miles/pac*/nanopolish/scripts/nanopolish_makerange.py 3H6contigs.fasta | parallel echo "parallel-test" {1}
```

Jared

ps: I see in your original command what looks like a pasting error `-P 8 \nanopolish` - there shouldn't be a `\n` here, in the instructions it is just a line continuation.

**Comment by miles-gene** [comment]
Thanks for the suggestion. I removed the pasting error and have tried to break the command down (build from scratch) but still get the same error immediately after mkdir nanopolish.results. I was wondering if parallel could be removed from the command and the nanopolish process gone through more laboriously. I guess I would have to specify nanopolish eventAlign in that case?

**Comment by jts** [comment]
If you run the basic command I suggested above (piping into `parallel echo`) does it fail?

**Comment by miles-gene** [comment]
Working with a draft genome with five contigs I get

python /home/miles/pac*/nanopolish/scripts/nanopolish_makerange.py 3H6FFPE_correctedReads.EmEd2_ex.fasta | parallel echo "parallel-test" {1}

parallel-test 9e53b521:0-50200
parallel-test 9e53b521:50000-83452
parallel-test acf6f24e:0-50200
parallel-test acf6f24e:50000-83444
parallel-test 85dfb247:0-50200
parallel-test 85dfb247:50000-83236
parallel-test a656302a:0-50200
parallel-test a656302a:50000-83226
parallel-test 26dc79ec:0-50200
parallel-test 26dc79ec:50000-83396

I'm experimenting with the echo command to see if i can build the command in stages as you suggested.

Thanks









ThanksI

**Comment by miles-gene** [comment]
I've made some progress. I have to run ./nanopolish / ./nanopolish_test or I get parallel error/hdf5 errors (nanopolish is in $PATH)

python /home/mileskb/myapps/nanopolish/scripts/nanopolish_makerange.py /home/mileskb/share/3H*/3H6_FFPE_ALLPASS_METBC/3H6_FFPE_cor1_trim_sembl.contigs.fasta | parallel --results nanopolish.results -P 8 \   ./nanopolish variants --consensus polished.{1}.fa -w {1} -r /home/mileskb/share/3H*/3H6_FFPE_ALLPASS_METBC/3H6FFPE_APMET_NANEX.fa -b /home/mileskb/share/3H*/3H6_FFPE_ALLPASS_METBC/3H6FFPE_APMET_NANEX.sorted.bam -g /home/mileskb/share/3H*/3H6_FFPE_ALLPASS_METBC/3H6_FFPE_cor1_trim_sembl.contigs.fasta -t 2 --min-candidate-frequency 0.1

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
Unknown model type string: , please report on github.
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
Unknown model type string: , please report on github.
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
Unknown model type string: , please report on github.
thanks

**Comment by miles-gene** [comment]
The .bam from
/home/mileskb/my*/bwa/bwa mem -x ont2d -t 8 3H6_FFPE_cor1_trim_sembl.contigs.fasta 3H6FFPE_APMET_NANEX.fa | samtools sort -o 3H6FFPE_APMET_NANEX.sorted.bam -T 3H6FFPE_APMET_NANEX.tmp -
samtools index 3H6FFPE_APMET_NANEX.sorted.bam

**Comment by jts** [comment]
What basecaller (and version) did you use?

**Comment by miles-gene** [comment]
So this is the SQK_RAD002 kit with local basecalling then basecalled again with Metrichor. I'm not what version Metrichor was using at the time as this was 2-3 months ago. I have albacore available if you think that's the problem, I thought the error related to the .bam format.

**Comment by jts** [comment]
I suggest calling the reads with albacore and forcing `nanopolish extract` to use the albacore basecalls with the `-b albacore` option.
