### ISSUE TITLE
installation-mac

### ISSUE THREAD

**Issue by rojinsafavi** [jts/nanopolish#130]
Hello,

I'm getting this error when I install nanopolish on my Mac ($make)

 NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [nanopolish] Error 1

Any idea why this is happening?

Thanks!

**Comment by jts** [comment]
Hi,

Can you post the complete output when you tried to run `make`?

Jared
