### ISSUE TITLE
Error detected in HDF5

### ISSUE THREAD

**Issue by jjscarpa** [jts/nanopolish#132]
Hi, 

I am running nanopolish version 0.6.1 on Ubuntu 14.04 and I get the following message when running `nanopolish extract`. The command seems to run successfully but I wanted to check to see if this is something I should be concerned with. I ran the ` nanopolish_test` and did not get any warnings. I have also seen similar errors with `nanopolish_makerange.py` but I reinstalled `nanopolish` so I do not have the log file for that. 

Thanks!

`nanopolish$ ./nanopolish extract --type template pass/ > p_marinus_pass.fasta
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140306214426624:
  #000: H5F.c line 604 in H5Fopen(): unable to open file  
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1085 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: H5Fsuper.c line 294 in H5F_super_read(): unable to load superblock
    major: Object cache
    minor: Unable to protect metadata
  #003: H5AC.c line 1320 in H5AC_protect(): H5C_protect() failed.
    major: Object cache
    minor: Unable to protect metadata
  #004: H5C.c line 3574 in H5C_protect(): can't load entry
    major: Object cache
    minor: Unable to load metadata into cache
  #005: H5C.c line 7954 in H5C_load_entry(): unable to load entry
    major: Object cache
    minor: Unable to load metadata into cache
  #006: H5Fsuper_cache.c line 476 in H5F_sblock_load(): truncated file: eof = 242178, sblock->base_addr = 0, stored_eoa = 478452
    major: File accessibilty
    minor: File has been truncated
[extract] found 93853 files, extracted 93853 reads
`

**Comment by jts** [comment]
The error message `File has been truncated` suggests there might be an issue with (one of) your HDF5 files. If you re-run the command does it happen again?

**Comment by metacrobe** [comment]
Thanks for the advice. Makes sense. I will try to re-run...
