### ISSUE TITLE
Assertion `f5_events[0].move == 0 || f5_events[0].move == 1' failed

### ISSUE THREAD

**Issue by nidafra92** [jts/nanopolish#133]
Hi

I'm running Nanopolish (v 0.6) on a draft assembly of lambda phage (R9.4 / Rapid Sequencing Kit).

I got this error when running 'nanopolish variants':

```
[fai_load] build FASTA index.
WARNING: [Warning: model type could not be detected from fast5, defaulting to R9.4-450bps]
nanopolish: src/nanopolish_squiggle_read.cpp:384: std::vector<EventRangeForBase> SquiggleRead::build_event_map_1d(const string&, uint32_t, std::vector<fast5::Basecall_Event>&): Assertion `f5_events[0].move == 0 || f5_events[0].move == 1' failed.
[fai_load] build FASTA index.
nanopolish: src/nanopolish_squiggle_read.cpp:384: std::vector<EventRangeForBase> SquiggleRead::build_event_map_1d(const string&, uint32_t, std::vector<fast5::Basecall_Event>&): Assertion `f5_events[0].move == 0 || f5_events[0].move == 1' failed.
```

I executed the command as follows:

```
python2.7 /home/nfranco/nano/apps/nanopolish/scripts/nanopolish_makerange.py lambdaEAFIT_albacore.contigs.fasta | parallel --results nanopolish.results -P 4 nanopolish variants --consensus=polished.{1}.fa -w {1} -r reads_albacore.fa -b reads.sorted.bam -g lambdaEAFIT_albacore.contigs.fasta -t 4 --min-candidate-frequency 0.1
```
I obtained the draft via Canu v1.3. I basecalled my reads using standalone Albacore version 1.0.1., and extracted them in FASTA format using 'nanopolish extract'.

I would appreciate any help with this. Thanks.

**Comment by jts** [comment]
Hi,

This is an issue with the latest albacore (`1.0.1`). I'm actively looking into it and will update this issue when I find a solution.

Jared

**Comment by nidafra92** [comment]
Thanks Jared for your answer. I'll be checking to any updates on this.

**Comment by jts** [comment]
Hi,

The latest version has preliminary support for albacore 1.0.1. It is not well tested yet. I will try to test it on a large data set soon, please let me know how it works in your hands.

Jared

**Comment by nidafra92** [comment]
Hi Jared:

Thanks for your answer. I updated Nanopolish (v 0.6.1) and executed my data again. But I'm still getting errors:

```
[extract] found 23083 files, extracted 23083 reads
[bwa_index] Pack FASTA... 0.00 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.03 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Pack forward-only FASTA... 0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.01 sec
[main] Version: 0.7.12-r1039
[main] CMD: bwa index lambdaEAFIT_albacore.contigs.fasta
[main] Real time: 0.426 sec; CPU: 0.048 sec
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 8446 sequences (40006145 bp)...
[M::process] read 8200 sequences (40004400 bp)...
[M::mem_process_seqs] Processed 8446 reads in 526.168 CPU sec, 131.818 real sec
[M::process] read 6437 sequences (30693183 bp)...
[M::mem_process_seqs] Processed 8200 reads in 527.172 CPU sec, 132.575 real sec
[M::mem_process_seqs] Processed 6437 reads in 410.552 CPU sec, 103.147 real sec
[main] Version: 0.7.12-r1039
[main] CMD: bwa mem -x ont2d -t 4 lambdaEAFIT_albacore.contigs.fasta reads_albacore.fa
[main] Real time: 367.981 sec; CPU: 1464.068 sec
nanopolish: src/nanopolish_squiggle_read.cpp:481: std::vector<EventRangeForBase> SquiggleRead::build_event_map_1d(const string&, uint32_t, std::vector<fast5::Basecall_Event>&): Assertion `read_sequence_1d.compare(curr_k_idx, k, event_kmer, 0, k) == 0' failed.
[fai_load] build FASTA index.
nanopolish: src/nanopolish_squiggle_read.cpp:481: std::vector<EventRangeForBase> SquiggleRead::build_event_map_1d(const string&, uint32_t, std::vector<fast5::Basecall_Event>&): Assertion `read_sequence_1d.compare(curr_k_idx, k, event_kmer, 0, k) == 0' failed.
```
I used the following lines to perform the analysis:

```
nanopolish extract -r /home/nfranco/nano/Projects_BEC/lambda_phageEAFIT/RawData/albacore_output/workspace/ > reads_albacore.fa
bwa index lambdaEAFIT_albacore.contigs.fasta
bwa mem -x ont2d -t 4 lambdaEAFIT_albacore.contigs.fasta reads_albacore.fa | samtools sort -o reads.sorted.bam -T reads.tmp -
samtools index reads.sorted.bam
python2.7 /home/nfranco/nano/apps/nanopolish/scripts/nanopolish_makerange.py lambdaEAFIT_albacore.contigs.fasta | parallel --results nanopolish.results -P 4 nanopolish variants --consensus=polished.{1}.fa -w {1} -r reads_albacore.fa -b reads.sorted.bam -g lambdaEAFIT_albacore.contigs.fasta -t 4 --min-candidate-frequency 0.1
```

Maybe is there anything wrong in the procedure?

**Comment by jts** [comment]
Can you confirm you grabbed the latest commit from git and not the 0.6.1 tagged release (this fix isn't in a tagged release yet)?

**Comment by piroonj** [comment]
I got similar issue as shown below. I used albacore (1.0.1) for base-calling. 
`nanopolish variants --progress -t 5 --reads $sample.fil_bam.fasta -o $sample.vcf -b $sample.ampcon.bam -g $ref -vv -w "'nanopolish_header.py $ref'" --snps --ploidy 1`

> nanopolish: src/nanopolish_squiggle_read.cpp:384: std::vector<EventRangeForBase> SquiggleRead::build_event_map_1d(const string&, uint32_t, std::vector<fast5::Basecall_Event>&): Assertion `f5_events[0].move == 0 || f5_events[0].move == 1' failed.
> zsh: abort      nanopolish variants --progress -t 5 --reads $sample.fil_bam.fasta -o  -b  -g

**Comment by nidafra92** [comment]
Jared. I checked what you mentioned. Just to be sure, I cloned the repo again, and then I got the proper commit (git checkout 9c33f63), but I'm still getting the same error:

```
nanopolish: src/nanopolish_squiggle_read.cpp:481: std::vector<EventRangeForBase> SquiggleRead::build_event_map_1d(const string&, uint32_t, std::vector<fast5::Basecall_Event>&): Assertion `read_sequence_1d.compare(curr_k_idx, k, event_kmer, 0, k) == 0' failed.
[fai_load] build FASTA index.
nanopolish: src/nanopolish_squiggle_read.cpp:481: std::vector<EventRangeForBase> SquiggleRead::build_event_map_1d(const string&, uint32_t, std::vector<fast5::Basecall_Event>&): Assertion `read_sequence_1d.compare(curr_k_idx, k, event_kmer, 0, k) == 0' failed.
```

Any ideas?
Thanks

**Comment by jts** [comment]
Thanks for checking, I'll take a look tomorrow (away from the office today).

**Comment by rrwick** [comment]
I'm hitting the same issue, also with recent Albacore (v1.0.2) reads, also on the latest Nanopolish commit.

I'm using `nanopolish_makerange.py` and `parallel` as described in the README, and it's only happening on a few of the ranges. Most complete without a problem. I can provide more info/data if you need it to debug.

**Comment by jts** [comment]
Hi,

I've just pushed a change to github that will skip these reads. Please give it a try and let me know how it looks.

Jared

**Comment by rrwick** [comment]
I just tried again and it worked without a problem. Thanks so much for the quick fix!
