### ISSUE TITLE
Nanopolish in an event-free future?

### ISSUE THREAD

**Issue by rrwick** [jts/nanopolish#134]
Hi Jared,

I recall Clive Brown, in his tech update last month, talking about no longer using events in basecalling. I think (if I interpreted it correctly), he means that future basecallers will train/run their neural network on the raw signal, no longer having an intermediate event-calling step.

Nanopolish works by aligning reads at the event level, correct? So what would an event-free future mean for Nanopolish? Just curious - thanks!

Ryan

**Comment by jts** [comment]
Hi Ryan,

nanopolish's model framework is pretty flexible and we could switch to using a raw model for inference pretty easily. We've done a bit of work on this but haven't gotten very far yet. I don't think its a pressing issue yet but it is definitely something we are thinking about. Happy to chat about this at LC in a few weeks!

Jared

**Comment by rrwick** [comment]
Okay, that's good to know. I'll close this 'issue' now. Looking forward to London Calling - see you there!
