### ISSUE TITLE
Error: could not find path to FAST5 for read channel_100_0007dcec-e8d1-4b71-9330-30a7e5dc116d_template

### ISSUE THREAD

**Issue by caonetto** [jts/nanopolish#136]
Hi, I am getting this error when trying to run the polishing command. My nanopore 1D reads were extracted in fastq format using poretools, is this ok or I need to use fasta format?

This is the command I am running.
python /home/ubuntu/nanopolish/scripts/nanopolish_makerange.py /mnt/cris/JJ2_49/nanopolishspades/draftgenome/contigs.fasta | parallel --results nanopolish.results -P 8 \
    /home/ubuntu/nanopolish/nanopolish variants --consensus polished.{1}.fa -w {1} -r /mnt/cris/JJ2_49/JJ2_49nanoporeraw.fastq -b mnt/cris/JJ2_49/nanopolishspades/sorted.bam -g /mnt/cris/JJ2_49/nanopolishspades/draftgenome/contigs.fasta -t 4 --min-candidate-frequency 0.1

Thanks!

Cris.

**Comment by jts** [comment]
Hi,

nanopolish requires the path to the original fast5 file to be in the header of each record in the file. I don't remember if poretools writes this information to fastq - try the fasta option or try using `nanopolish extract` instead.

Jared

**Comment by jts** [comment]
Closing issue, feel free to reopen if there is still a problem.

**Comment by caonetto** [comment]
Hi,
I keep on getting the following outcome when trying to run Nanopolish:

Error: could not find path to FAST5 for read 0000914b-f7c3-4bd4-ba21-eba0466bba5b_Basecall_1D_template:1D_000:template
Please make sure that this path is accessible: /mnt/cris/allbasecalled/all/DPB9XH6V_20170504_FNFAE21462_MN18577_sequencing_run_JJ2_49_40517_82302_ch494_read5889_strand.fast5
##fileformat=VCFv4.2
##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">
##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">
##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">
##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">
##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
Error: could not find path to FAST5 for read 0000914b-f7c3-4bd4-ba21-eba0466bba5b_Basecall_1D_template:1D_000:template
Please make sure that this path is accessible: /mnt/cris/allbasecalled/all/DPB9XH6V_20170504_FNFAE21462_MN18577_sequencing_run_JJ2_49_40517_82302_ch494_read5889_strand.fast5

My reads.fasta file has been obtained using Nanopolish. 


Any ideas?

**Comment by jts** [comment]
Hi,

The error message indicates nanopolish cannot read one of your fast5 files. Is the path that nanopolish reports correct? Is that file readable?

Jared
