### ISSUE TITLE
model

### ISSUE THREAD

**Issue by Dangoh** [jts/nanopolish#140]
Hi,

I'm kinda new to this, and checked some tutorials for nanopore eventalign, however I don't understand how to get the model file. As I see it I have the following in my nanopolish/etc/r9-models dir:

r9.4_450bps.cpg.6mer.template.model
r9.4_450bps.nucleotide.5mer.template.model
r9.4_450bps.nucleotide.6mer.template.model
r9_250bps.cpg.6mer.template.model
r9_250bps.nucleotide.5mer.complement.pop1.model
r9_250bps.nucleotide.5mer.complement.pop2.model
r9_250bps.nucleotide.5mer.template.model
r9_250bps.nucleotide.6mer.complement.pop1.model
r9_250bps.nucleotide.6mer.complement.pop2.model
r9_250bps.nucleotide.6mer.template.model

And according to the tutorial I'm following I should cp everything into my working directory and the run:

nanopolish eventalign \
-t8 \
--sam \
-- reads .fasta \
--bam .sorted.bam \
--genome .contigs.fa \
--models nanopolish_models.fofn \

and obviously get "Error: could not read nanopolish_models.fofn"

Appreciate all the help you can give!

**Comment by jts** [comment]
Hi, 

The `--models` parameter is no longer required. If you omit that parameter it should work. What tutorial are you following? I'll have to update it.

Jared

**Comment by Dangoh** [comment]
Hi Jared,

Thank you for the quick reply!

I'm using 0.5.0, will use 0.6.0 and see if it works better!

**Comment by Dangoh** [comment]
Also, the tutorial I was following was one from Porecamp 2016:

https://porecamp.github.io/2016/tutorials/PoreCamp2016-04-Assembly.pdf
