### ISSUE TITLE
nanopolish call-methylation does not use available cores

### ISSUE THREAD

**Issue by scottgigante** [jts/nanopolish#142]
I am running `nanopolish call-methylation` on a VM running on our local HPC cluster. I've requisitioned 16 threads and 16GB of memory, and am running nothing else on the node. There are 14GB of memory free and very low disk I/O, and despite this, nanopolish is running at between 25-45% of a single CPU (or about 2-3% of the resources available to it). 

Any idea why this might be the case?

**Comment by jts** [comment]
We had to put a lock around access to the fast5 files to prevent an HDF5 read error. `call-methylation` is effectively I/O bound because of this. If you want to use all available cores you'll have to split the BAM into chunks for now, sorry.

**Comment by scottgigante** [comment]
Ah, that makes sense. Thanks for the quick response!
