### ISSUE TITLE
nanopolish_merge.py AssertionError

### ISSUE THREAD

**Issue by jordur** [jts/nanopolish#143]
Hi !
I successfully ran the nanopolish_makerange.py script in order to get a complete genomic sequence from a bam alignment file composed by 4 Canu-obtained contigs. Nanopolish_makerange gave rise the following files:
```
polished.tig00000001:0-50200.fa
polished.tig00000001:100000-150200.fa
polished.tig00000001:200000-250200.fa
polished.tig00000001:250000-272051.fa
polished.tig00000001:50000-100200.fa
polished.tig00000003:0-50200.fa
polished.tig00000003:100000-150200.fa
polished.tig00000003:150000-200200.fa
polished.tig00000003:200000-250200.fa
polished.tig00000003:250000-255450.fa
polished.tig00000003:50000-100200.fa
polished.tig00000005:0-50200.fa
polished.tig00000005:100000-150200.fa
polished.tig00000005:150000-154139.fa
polished.tig00000005:50000-100200.fa
polished.tig00000010:0-50200.fa
polished.tig00000010:100000-140156.fa
polished.tig00000010:50000-100200.fa
```
Then, I tried to merge results using the following command line:
```
python /home/ibv/jdurban/programas/nanopolish/scripts/nanopolish_merge.py polished*.fa > sample_polished_genome.fa
```
Resulting:
```
Insert tig00000001 0
Insert tig00000001 99960
Insert tig00000001 199960
Insert tig00000001 249960
Insert tig00000001 49960
Insert tig00000003 0
Insert tig00000003 99960
Insert tig00000003 149960
Insert tig00000003 199960
Insert tig00000003 249960
Insert tig00000003 49960
Insert tig00000005 0
Insert tig00000005 99960
Insert tig00000005 149960
Insert tig00000005 49960
Insert tig00000010 0
Insert tig00000010 99960
Insert tig00000010 49960
Merging tig00000001 0
Merging tig00000001 49960
Merging tig00000001 99960
Merging tig00000001 199960
Traceback (most recent call last):
  File "/home/bec2-jcalvete/Feina_Jordi/programes/nanopolish/scripts/nanopolish_merge.py", line 89, in <module>
    assert(prev_segment is None or prev_segment + SEGMENT_LENGTH + OVERLAP_LENGTH > segment_start)
AssertionError
```
Does it mean that resulting polished fasta sequences do not overlap at all?
I mean, as far as I know, since the sentence below is false I obtained the error. My question then: why I got the error?  indeed, some of them showed a high percentage of identity according to a rapid blast inspection. For instance:
tig00000001:99960-150240    VS    tig00000005:99960-150240 
11963 bits(6478) 	0.0 	7291/7672(95%) 	101/7672(1%) 	Plus/Minus

```
# Ensure the segments overlap
        assert(prev_segment is None or prev_segment + SEGMENT_LENGTH + OVERLAP_LENGTH > segment_start)
```
Thank you so much in advance

**Comment by jts** [comment]
Could you make me a zip of all the `polished.*.fa` files so I can try tor reproduce the problem here?

**Comment by jordur** [comment]
Yes, of course! 
[files.zip](https://github.com/jts/nanopolish/files/1014228/files.zip)

**Comment by jts** [comment]
There is a missing segment from 100,000 to 150,000bp of `tig00000001`. It must have failed polishing for some reason, you'll have to re-run that segment.

**Comment by jordur** [comment]
Ok, thank you! And how should I specify to re-run that segment and not the complete polishing process? It lasted ~40h completing the entire dataset. Sorry for the inconvenience
