### ISSUE TITLE
core dump error during 'call-methylation'

### ISSUE THREAD

**Issue by porpheria** [jts/nanopolish#144]
Hi, 
I was recently using "nonopolish" on NA12878.native.simpson.103015 dataset. But the methylation call module gives core dump error. Will you help me to regarding this issue? 
Below are the steps I have followed for the data analysis;

./nanopolish extract -q --type 2d-or-template ../NA12878.native.simpson.103015.fast5/pass/ > NA12878_native_simpson_103015_passed_reads.fastq

bwa mem -x ont2d -t 8 ../../Work/For_nonoporeSeq/hg38.fa ../NA12878.native.simpson.103015.fast5/NA12878_native_simpson_103015_passed_reads.fastq > > NA12878_native_simpson_103015_passed_reads.sam

samtools view -bT ../../Work/For_nonoporeSeq/hg38.fa NA12878_native_simpson_103015_passed_reads.sam > NA12878_native_simpson_103015_passed_reads.bam

samtools sort NA12878_native_simpson_103015_passed_reads.bam NA12878_native_simpson_103015_passed_reads_sorted

samtools index NA12878_native_simpson_103015_passed_reads_sorted.bam NA12878_native_simpson_103015_passed_reads_sorted.bai

./nanopolish call-methylation -t 8 -r ../NA12878.native.simpson.103015.fast5/NA12878_native_simpson_103015_passed_reads.fastq -g ../../Work/For_nonoporeSeq/hg38.fa -b NA12878_native_simpson_103015_passed_reads_sorted.bam > NA12878_native_simpson_103015_passed_reads_sorted_methylation.tsv

nanopolish: src/common/nanopolish_bam_processor.cpp:31: BamProcessor::BamProcessor(const string&, const string&, int): Assertion `m_bam_idx != NULL' failed.
Aborted (core dumped)

**Comment by jts** [comment]
If you use the default bam index file name (*.bam.bai) then it should work.

Jared

**Comment by jts** [comment]
Note that file is R7 data, which is no longer well supported. I suggest trying the more recent data set here instead: https://github.com/nanopore-wgs-consortium/NA12878

**Comment by porpheria** [comment]
Thanks for your prompt reply.
I am going to try with *.bam.bai file, and if it will give the same error I will use the new data for the link provided by you.
Thanks once again.
