### ISSUE TITLE
Document required 3rd-party code and provide release tarballs without them

### ISSUE THREAD

**Issue by mmokrejs** [jts/nanopolish#147]
Hi Jared,
  would it be possible to release solely nanopolish-containing release tarballs which would automatically build using site-wide installed fast5, htslib, eigen, hdf5?

  Please document in top-level Readme.md their required versions and compile options (like hdf5 with threads support being required).
Thank you

**Comment by smoe** [comment]
From the Debian packaging site we have addressed that by auto-removing these 3rd party tools. But I agree. The system should provide hdf5, fast5, htslib and eigen3, not nanopolish.

**Comment by jts** [comment]
I agree in principle it is better to not package dependencies within nanopolish but this causes difficulty for many users, so by default I want to provide these. Many people will only use bioinformatics tools that are trivial to install. I'll commit to making external dependencies an option for package maintainers though; I'll try to address #213 this week.

**Comment by jts** [comment]
I have improved the dependencies section of the README and #213 was fixed by @0xaf1f so I am closing this issue.
