### ISSUE TITLE
nanopolish_makerange.py creating lots of temporary? files in cwd

### ISSUE THREAD

**Issue by mmokrejs** [jts/nanopolish#150]
Hi Jared,
  the Readme.md instructs users to run:
```
python nanopolish_makerange.py draft.fa | parallel --results nanopolish.results -P 8 \
    nanopolish variants --consensus polished.{1}.fa -w {1} -r reads.fa -b reads.sorted.bam -g draft.fa -t 4 --min-candidate-frequency 0.1
```

It turns out that current working direcotry is flooded by many files like:

```
-rw------- 1 3900 4638       34160 May 23 14:40 'polished.contig_10367,length=34106,cov=14.2,gc=0.367:0-34105.fa'
-rw------- 1 3900 4638       29573 May 23 14:40 'polished.contig_6822,length=29520,cov=12.6,gc=0.379:0-29519.fa'
-rw------- 1 3900 4638       28744 May 23 14:40 'polished.contig_13296,length=28690,cov=12.5,gc=0.383:0-28689.fa'
-rw------- 1 3900 4638       27387 May 23 14:41 'polished.contig_34393,length=27333,cov=12.3,gc=0.371:0-27332.fa'
-rw------- 1 3900 4638       26735 May 23 14:41 'polished.contig_11644,length=26681,cov=13.2,gc=0.380:0-26680.fa'
-rw------- 1 3900 4638       26707 May 23 14:41 'polished.contig_11487,length=26653,cov=13.8,gc=0.374:0-26652.fa'
-rw------- 1 3900 4638       26270 May 23 14:41 'polished.contig_22948,length=26216,cov=13.5,gc=0.393:0-26215.fa'
-rw------- 1 3900 4638       26119 May 23 14:42 'polished.contig_9570,length=26066,cov=12.6,gc=0.392:0-26065.fa'
-rw------- 1 3900 4638       25154 May 23 14:42 'polished.contig_15985,length=25100,cov=12.5,gc=0.394:0-25099.fa'
-rw------- 1 3900 4638       25119 May 23 14:42 'polished.contig_7284,length=25066,cov=12.4,gc=0.388:0-25065.fa'
```

I would prefer to be warned in advance what is going to happen. I have 101358 nanopore reads so shall I expect that many files to appear in this `cwd` directory? Huh?

I presume these are my nanopore reads corrected using my temporary reference assembly although teh filename seems to state the opposite. I do not need to correct my Illumina assembly using nanopore reads.

Provided bwa outputs only `SAMv1.3` I wonder if I could use say BBmap to give me `SAM v1.4`. Would anything break in nanopolish pipeline?

How about `XA` tags in the SAM/BAM format. Are they parsed? Provided the above `polished.contig*.fa` files, are they eventually created per every nanopore read and its every mapped locus? So if multiple matches were stored, how does nanopolish behave? `bwa mem` I think keeps track of mostly up to 6 alternative matching regions. How does the nanopore error correction work if a 30kb nanopore read mapped to say 1000 of contigs? Some matches are overlapping. Will I get one  temp file in my `cwd` or *1000* such files, or even file for all their combinations?

**Comment by jts** [comment]
Hi,

That command will polish the input genome in 50kb segments and there will be one output file per segment. So the number of output files is `genome_length/50`. Are you using nanopolish to call a consensus sequence for a set of reads? This is not the intended use.

Nanopolish should work with SAM v1.4 but I have not tested it with BBMap. Nanopolish will use all mappings that have a mapping quality of 20 or greater.

Jared

**Comment by mmokrejs** [comment]
Sorry, I do not understand. I have a fragmented but high-quality-sequence genome assembly and mapped to it nanopore long reads. You say teh approach splits in the input nanopore reads into 50kb fragments and does not put them back after error correction?

I have 1D reads (or at least, nobody told me they are 2D reads and from poretools I did not get any 2D data out from the original FAST5 files), while I extracted sequences as 1D data. I have very few reads, it is only 0.2x genomic coverage, so I only want to error-correct the few nanopore reads and use that for scaffolding. The reference genome is based on Illumina data, as I said contigs are rather short but overall they are fine.

> Nanopolish should work with SAM v1.4 but I have not tested it with BBMap. Nanopolish will use all mappings that have a mapping quality of 20 or greater.

Please update the Readme.md and docstrings in relevant executables/scripts.

**Comment by jts** [comment]
Nanopolish is designed to calculate a new consensus sequence for a draft genome assembly produced by a program like canu. It does not error correct reads. You should be providing to nanopolish a genome assembly with megabase-sized contigs that has low sequence accuracy and it will try to improve the accuracy of the contigs.

**Comment by mmokrejs** [comment]
Aha, again, please update the README.md, ideally explaining a bit more than what you said in this thread.

**Comment by jts** [comment]
Fixed with updated README.md
