### ISSUE TITLE
Standardising fasta headers

### ISSUE THREAD

**Issue by mw55309** [jts/nanopolish#153]
Hey

So nanopolish does some new funky things with FASTA headers.

Both poretools and poRe output something like:

```
>read_id<space>readname<space>file location
```

However nanopolish adds some stuff:

```
>read_id:1D_000:template<space>readname<space>file location
```

e.g.

```
>f2a113ae-b1af-4c6b-9ce7-01929971380d_Basecall_1D_template:1D_000:template mvm_ri_i174163_20170417_FNFAE24884_MN22254_mux_scan_10572RR0012_61620_ch149_read13_strand albacore_1.1.1/0/mvm_ri_i174163_20170417_FNFAE24884_MN22254_mux_scan_10572RR0012_61620_ch149_read13_strand.fast5
```

What is this "1D_000:template" information?  Does nanopolish use it?  Is it formally described somewhere and should we standardise?

Cheers
Mick

**Comment by nickloman** [comment]
It's important to identify the group if reads have been called multiple times (e.g. local and Albacore). There is a poretools branch ('basecaller-choice') that will output this format, which I would like to merge int HEAD. I think this should be a standard.

**Comment by mw55309** [comment]
Great, so the first part can be 1D_001 ... 1D_00n or 2D_001 ... 2D_00n for backwards compatibility.

Do we know what 1D^2 will be?

And the second part can be: template, complement, and .... ?  Is 2D supported?

**Comment by nickloman** [comment]
Yes 2D is supported

No idea about 1D^2

**Comment by mw55309** [comment]
OK, so what's the dictionary?

template
complement
2D

?

**Comment by nickloman** [comment]
Think it might be '2d'

**Comment by jts** [comment]
Yes, it is '2d' lowercase:

https://github.com/jts/nanopolish/blob/master/src/nanopolish_extract.cpp#L187
