### ISSUE TITLE
Nanopolish for Albacore reads on Mac OSX

### ISSUE THREAD

**Issue by woodford87** [jts/nanopolish#155]
We're having a problem here using Albacore basecalled fast5 files with Nanopolish.
Our system is Mac OS X Sierra with nanopolish 0.6.1 via Docker. nanopolish appears to be installed correctly however when we run nanopolish extract -t 2d on individual (or directories of) .fast5 files reports: [filename]`is neither a fast5 file nor a directory`

h5dump of [filename] appears OK, though no reference to albacore (should there be?)

We've also tried to force basecalling with nanopolish extract -b albacore but this reports that -b is an invalid option or

```
docker run adbailey4/nanopolish extract -b albacore --type 2d [filename]
extract: invalid option -- 'b'
= extract.0 nanopolish_extract.cpp:225 process_path path [albacore] is neither a fast5 file nor a directory
```
Installing nanopolish directly from github fails with clang and eigen issues which we've not managed to fix (due to our incompetence I suspect).

With thanks

**Comment by jts** [comment]
Hi,

The docker version is a bit behind and does not support the new `-b` flag. On the next release I'll try to update the docker. The error message `is neither a fast5 file nor a directory` is odd though. Could you send an example fast5?

Jared

Jared

**Comment by woodford87** [comment]
Hi Jared,

Thanks for your response. Attached is a fast5 file.

Cheers, Luke

--
Luke Woodford
PhD Student
Evans Laboratory
School of Biology
Biomolecular Sciences Building
North Haugh
St Andrews, KY16 9ST

Web: http://evanslab.org.uk/
Tel: 01334 464831

**Comment by woodford87** [comment]
Do you know of a way around the eigen installation issue on Mac if docker is not currently an option?

**Comment by jts** [comment]
What error do you get?

**Comment by woodford87** [comment]
Hi Jared, 

I don't have the error message, but essentially, when installing Nanopolish, Eigen failed to install because of the default compiler on Mac OS X, Clang. This resulted in Nanopolish failing to find files when we tried to run the extract command.

We tried removing Clang and installing a new compiler, then reinstalling Nanopolish, but we recieved the same 'file not found' error. Eigen is not a default library for Mac, which could have something to do with it.

Cheers, Luke

**Comment by woodford87** [comment]
Do you know any way around this, other than trying to run it on lineX?

**Comment by jts** [comment]
Linux is the best option, if that is possible. Eigen is automatically downloaded by nanopolish and only the headers are used so I'm not sure why that is failing to install. Could you start from a fresh clone of the repository and paste the full log when trying to compile?

**Comment by jts** [comment]
Hi,

I just tested this on my macbook and the build was successful using `gcc-4.8` installed from homebrew:

```
make CXX=g++-4.8
```

**Comment by woodford87** [comment]
Thanks Jared, I've given that a try. However, I am still seeing Clang errors like this - 

`clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]`
`clang: error: unsupported option '-fopenmp'`

**Comment by jts** [comment]
Do you have gcc-4.8 installed? The command `make CXX=g++-4.8` should use the GCC C++ compiler instead of clang.

**Comment by woodford87** [comment]
gcc-4.8 is installed and when I run it with the make command I get the following error:
`ld: can't open output file for writing: nanopolish, errno=21 for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [nanopolish] Error 1`

**Comment by woodford87** [comment]
We've fixed the problem, thanks for all your help Jared!
