### ISSUE TITLE
R9.5 models

### ISSUE THREAD

**Issue by jonhultqvist** [jts/nanopolish#156]
Hi,
When trying to use Nanopolish (used latest commit on June 5th on GitHub) on Albacore (v.1.1.2) base called R9.5 flowcell data the program fails with the following message. 

Unknown model type string: r9.5_450bps, please report on github.

I have not seen anyone post about this already. Is there a fix for this problem that I can implement? 

Cheers
Jon

**Comment by jts** [comment]
Hi,

I ran into this over the weekend and just pushed the fix to github now. For now the R9.4 models will be used for R9.5 data (ONT says the signals should be quite similar). I have tested this and it seems to work but I will evaluate whether a proper R9.5 model is needed later.

Jared

**Comment by jonhultqvist** [comment]
Thanks, it appears to be working now!
