### ISSUE TITLE
nanopolish variants --consensus Aborted (core dumped)

### ISSUE THREAD

**Issue by a1204350** [jts/nanopolish#158]
HI, I followed the steps shown on the main page of nanopolish trying to polish my minion-assembly.
I entered the following commands 

bwa index 96200minion_mc10.fasta
bwa mem -t 8 96200minion_mc10.fasta 96200_nanopolish_extract_reads.fasta | samtools sort -o reads.sorted.bam -T reads.tmp
samtools index reads.sorted.bam
nanopolish variants --consensus 96200minion_mc10_polished.fasta -w start-end -r 96200_nanopolish_extract_reads.fasta -b reads.sorted.bam -g 96200minion_mc10.fasta -t 4 --min-candidate-frequency 0.1

and it returned

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
nanopolish: src/alignment/nanopolish_alignment_db.cpp:355: void AlignmentDB::load_region(const string&, int, int): Assertion `m_region_end >= 0' failed.
Aborted (core dumped)

Could you please help me to fix this?

Thanks

**Comment by jts** [comment]
Hi,

`-w start-end` should be the coordinates of the reference region you want to call variants on (example: `chr1:1000-2000`).

Jared

**Comment by a1204350** [comment]
thanks for the quick reply!
However, I just tried changing strat-end into 1-6680302, the error persisted 
My reference fasta is in multi-fasta format , the total length is 6680302 (divided into 50 contigs or so). Is this causing the problem?
Thanks again

**Comment by jts** [comment]
you need to provide the chromosome or contig name. See the example I made above.

**Comment by a1204350** [comment]
Oh I see,
Do I need to concatenate the multi-fasta reference genome first, otherwise each fasta would have a different name, since I can only specify one contig name, like your example above? Am I right?

**Comment by jts** [comment]
You want to run nanopolish multiple times, then merge the results at the end. A suggested workflow is here:

https://github.com/jts/nanopolish#computing-a-new-consensus-sequence-for-a-draft-assembly
