### ISSUE TITLE
Make

### ISSUE THREAD

**Issue by mercycarter** [jts/nanopolish#159]
Hi,

When I go through the steps, 

$ git clone --recursive https://github.com/jts/nanopolish.git
$cd nanopolish
$ make

I get the error: make
Makefile:109: .depend: No such file or directory
if [ ! -e hdf5-1.8.14.tar.gz ]; then wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.14/src/hdf5-1.8.14.tar.gz; fi
/bin/sh: wget: command not found
make: *** [lib/libhdf5.a] Error 127

Not sure what I'm doing wrong?

Thanks in advance!

**Comment by jts** [comment]
Hi,

It looks like you are missing `wget`. What version of linux are you using? If you install wget using your package manager the build should continue.

Jared

**Comment by mercycarter** [comment]
Hi,

I'm actually running this through terminal on a Mac. I installed wget
through homebrew, which seems to have worked. Now I'm trying to sort out
what seems to be a Mac related issue. Instead of using gcc, it's defaulting
to clang and I'm getting: error: unsupported option '-fopenmp'

Currently reading up on that and trying to find a work around, but any
thoughts would be much appreciated. My lab recently acquired the Nanopore
Oxford MinION technology and I was tasked with setting up the data
processing system, with my 0 years of programming experience.

This has been, and continues to be, quite the adventure.

Cheers!

Meghan

On Tue, Jun 13, 2017 at 7:48 PM, Jared Simpson <notifications@github.com>
wrote:

> Hi,
>
> It looks like you are missing wget. What version of linux are you using?
> If you install wget using your package manager the build should continue.
>
> Jared
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jts_nanopolish_issues_159-23issuecomment-2D308280034&d=DwMCaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=-Q8_fRKqRRHfYSuLpJpifg&m=M6j96-dvjUh9NCVShzdf9rDWtbA2rGbPatwMVbiBDMc&s=pbN6VzkJ88xaCQvoS1U3NmCW6E-a3ph_02ewFLVLUFs&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AcDIIWP8a8PHnTr-2DosXECFPxQcJm8yzoks5sDx-5FcgaJpZM4N45sv&d=DwMCaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=-Q8_fRKqRRHfYSuLpJpifg&m=M6j96-dvjUh9NCVShzdf9rDWtbA2rGbPatwMVbiBDMc&s=UeT18UbAOxaz2faFFvoG7O7jEcjmupL84Qqh3m2ud2A&e=>
> .
>



-- 
Meghan Lawler
Graduate Student
Duke University
Chemistry Department- McCafferty Lab

**Comment by jts** [comment]
Hi,

You'll need to to install gcc-4.8 using homebrew, then nanopolish should compile with this command:

`make CXX=g++-4.8`

Jared

**Comment by rckeerthivasan** [comment]
hi, 

I am facing the above problem. 

fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [cache.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [lib/libhdf5.a] Error 2

I run these commands: make CXX=g++-11, make CXX=/usr/local/bin/g++-11. No use. Any idea on this?
