### ISSUE TITLE
Can nanopolish work with an assembly with ambiguous bases?

### ISSUE THREAD

**Issue by caonetto** [jts/nanopolish#160]
Hi, 
I merged multiple nanopore contigs using illumina data but I have some ambiguous bases in the final contigs. I want to polish this final contig with the original nanopore data. Will nanopolish work with this ambiguous bases?

Thanks!

**Comment by jts** [comment]
Sorry for the slow reply. Currently the consensus polishing step does not work with ambiguous bases. You should change the ambiguous bases to a random nucleotide before polishing.
