### ISSUE TITLE
Options for Speed Optimization

### ISSUE THREAD

**Issue by Daniel-Wilkins** [jts/nanopolish#163]
Hi,

Nanopolish is taking multiple hours for subsets of 20,000 5kb reads, running on 32 cores with the multithreading option. We've noticed in the terminal prints that each identified polymorphism positions is rerun 50x. However, we are also seeing that the SupportFraction is converging after only 2-3 of these repetitions. Are these repetitions indicative of actual computational effort / would there be a way of reducing the number of repetitions?

Thank you,
Daniel

**Comment by jts** [comment]
Hi,

I've just pushed a commit (08c552c) that adds a `--max-rounds` option that allows you to control how many improvement rounds are tried. This won't reduce runtime by a lot (most time is spent in the first stage, where it detects candidates corrections) but it should help a bit. I will be trying to make other optimizations for speed soon.

Jared
