### ISSUE TITLE
errors calling nanoplish due to wrong compiler version?

### ISSUE THREAD

**Issue by sharon558** [jts/nanopolish#167]
I downloaded the latest build this morning. I specified gcc-4.9.2 in the makefile to compile the code, and make finished successfully.
CXX = '/gcc-4.9.2/bin/g++'
CC = '/gcc-4.9.2/bin/gcc'

But when I called "nanopolish variants", I got the following errors:

./nanopolish: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by ./nanopolish)
./nanopolish: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.7' not found (required by ./nanopolish)
./nanopolish: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./nanopolish)

Any idea? 
Should the code be compiled by gcc-4.8 only?

Thanks in advance!

**Comment by jts** [comment]
It should compile with gcc-4.9.2. It looks at runtime it is not able to find the path to the gcc-4.9 libraries. Maybe check your LD_LIBRARY_PATH is correct?

**Comment by sharon558** [comment]
You are right! I added the path to gcc-4.9.2/lib64 in $LD_LIBRARY_PATH and it worked now :)
Thank you!! @jts

**Comment by jts** [comment]
Great!
