### ISSUE TITLE
Output format specification/potential bugs

### ISSUE THREAD

**Issue by JEzpeleta** [jts/nanopolish#168]
Is there any documentation that precisely describes the output produced by `nanopolish variants`? A typical output line (without the `--consensus` option) looks like:

`gb_KP164572_Organism_Chikungunya        11036   .       T       C       13417.6 PASS    BaseCalledReadsWithVariant=1736;BaseCalledFrequency=0.864111;TotalReads=2004;AlleleCount=1;SupportFraction=0.89822      GT      1`

What is the exact meaning of BaseCalledReadsWithVariant, BaseCalledFrequency, TotalReads and SupportFraction? My initial guess is that TotalReads is the total number of reads that align to the reference at the position considered, BaseCalledReadsWithVariant is the number of reads which have the current variant (T->C in this case) at that position and BaseCalledFrequency is the ratio of the latter to the former (I am in the dark about SupportFraction). However, we have seen output lines that look like this:

`gb_KP164572_Organism_Chikungunya        11140   .       T       C       90.4    PASS    BaseCalledReadsWithVariant=51;BaseCalledFrequency=0.662338;TotalReads=4;AlleleCount=1;SupportFraction=0.539529  GT      1`

Here, BaseCalledReadsWithVariant is greater than TotalReads. This is either a bug or contradicts my guess about the meaning of output fields.

**Comment by jts** [comment]
Hi,

I'll fix this today by adding a header to the VCF file. In the meantime:

`BaseCalledReadsWithVariant`  - number of reads that have the ALT allele in their basecalled sequence
`BaseCalledFrequency` - fraction of reads that have the ALT allele in their basecalled sequence
`TotalReads` - the number of signal-level reads used by the HMM to call the variant
`SupportFraction` - the fraction of signal-level reads that support the variant (this is the sum of posterior probabilities so it does not have to be an integral value / TotalReads)

`TotalReads` can be lower than `BaseCalledReadsWithVariant` if some reads are not usable in event-space. Most notably if there aren't enough events flanking a variant on either side, a read will not be used. I suspect you using an amplicon tiling scheme and the second variant is near an amplicon boundary.

**Comment by JEzpeleta** [comment]
Thank you very much for the clarification. Indeed, we have only seen `TotalReads` lower than `BaseCalledReadsWithVariant` near amplicon boundaries, so that is likely the cause.

**Comment by jts** [comment]
With commit 330933f nanopolish will output a real VCF header

**Comment by jts** [comment]
Oh, and `BaseCalledFrequency` has been changed to `BaseCalledFraction` for consistency
