### ISSUE TITLE
Intra-host variants/unimplemented option?

### ISSUE THREAD

**Issue by JEzpeleta** [jts/nanopolish#169]
We are trying to call variants of viral amplicons in a sample in an attempt to determine whether there are intra-host variants. We have around 2000X coverage of the amplicon region (~1.3 kb), so we expect that it should be possible to determine this if the less frequent variant is present at a reasonable ratio. Our initial approach was:

* Run `nanopolish variants --consensus --snps` with a reference genome we know to be closely related to the virus our amplicons come from. This produces about 60 SNPs and a polished genome (obviously SNP calling and polishing are only done in the amplicon region; the rest of the genome remains unchanged).

* Use the polished genome as a reference for a second round of nanopolish. Here we expected to see either no SNPs (indicating that there were no intra-host variants and the polished genome now matches the virus present in our sample) or additional SNPs with relatively low SupportFraction/BaseCalledFrequency (indicating the presence of a minority variant). However, we see additional SNPs with very high SupportFraction/BaseCalledFrequency (around 0.95). This is somewhat surprising, since we would have expected any SNPs with such high support to be spotted during the initial round of polishing. Is this normal behaviour (that not all SNPs with good support are spotted)?

A more general question is: do you think this is a reasonable approach to identify intra-host variants or are we missing the point? We also thought of using the `--calculate-all-support` option to identify polymorphic positions, but it doesn't appear to be implemented. Yet another alternative we thought of was to use `--ploidy 2` to force nanopolish to consider two variants, but this seems rather messy, so we didn't pursue it further.

**Comment by jts** [comment]
Sorry for not replying to this issue sooner. 

This is an application that we'd like to support but our current implementation can't do this well. My general suggestion is to use the reference-based variant calling mode (drop the `--consensus` option) and `ploidy 1` to get your list of variants. It is unlikely that intra-host variants with low support fraction will be called though since we use a discrete genotype model (the genome at a given position is either A or B, not a mixture). 

@nickloman you have a bit of experience with this, do you have suggestions?

**Comment by JEzpeleta** [comment]
Thank you very much for your answer. I'll have to look into this in more detail with your suggestion in mind, but it's useful to know that at least I'm not missing the obvious/standard way to do it. Let's see if Nick chips in with some additional insight.

**Comment by nickloman** [comment]
I don't really have anything specific to add here but I feel like the nanopolish phase-reads argument is useful for creating datasets for downstream analysis. I guess I would be inclined to reduce the min-candidate-frequency a bit. The --calculate-all-support option might be useful (does it not work anymore?)

**Comment by jts** [comment]
`-calculate-all-support` doesn't work with the new genotyping model. I could try to bring it back but the time would probably be better spent working on a more general solution to this.

**Comment by JEzpeleta** [comment]
@jts Bringing `--calculate-all-support` back would be great, but I agree working on a more general solution to the problem would probably be even better/more worthwhile. Obviously, whether any of this is a priority for nanopolish would be your call.
@nickloman Could you please elaborate a little bit more as to the use of `phase-reads` here?

**Comment by jts** [comment]
`--calculate-all-support` is back now
