### ISSUE TITLE
Usage instructions clarification

### ISSUE THREAD

**Issue by rmnorris** [jts/nanopolish#17]
I am attempting to use nanopolish on a draft assembly created by PBcR. In the usage instructions, after running 
    python nanopolish_makerange.py draft.fa | parallel --results nanopolish.results -P 8 nanopolish consensus -o nanopolish.{1}.fa -w {1} --r reads.pp.fa -b reads.pp.sorted.bam -g draft.fa -t 4
where draft.fa is the fasta produced by PBcR, I get the error:
    error: could not open reads.pp.fa for read
Where are the reads.pp.fa supposed to be generated - in the make step, or before using nanopolish? I don't appear to have any .pp.fa files. There did not seem to be an error when running the make step to suggest that it didn't work.

**Comment by jts** [comment]
Yes, the reads.pp.fa file should be generated by the make step. Did running ```consensus.make``` print any output?

**Comment by rmnorris** [comment]
Yes:
>bwa index JR_FAA35548_13042015_KpneCAV1016_clean.fasta
>[bwa_index] Pack FASTA... 0.48 sec
>[bwa_index] Construct BWT for the packed sequence...
>[BWTIncCreate] textLength=123927742, availableWord=20719820
>[BWTIncConstructFromPacked] 10 iterations done. 34177806 characters processed.
>[BWTIncConstructFromPacked] 20 iterations done. 63139438 characters processed.
>[BWTIncConstructFromPacked] 30 iterations done. 88876574 characters processed.
>[BWTIncConstructFromPacked] 40 iterations done. 111747806 characters processed.
>[bwa_index] 36.19 seconds elapse.
>[bwa_index] Update BWT... 0.43 sec
>[bwa_index] Pack forward-only FASTA... 0.29 sec
>[bwa_index] Construct SA from BWT and Occ... 15.28 sec
>[bwt_gen] Finished constructing BWT in 46 iterations.
>[main] Version: 0.7.12-r1039
>[main] CMD: bwa index JR_FAA35548_13042015_KpneCAV1016_clean.fasta
>[main] Real time: 53.904 sec; CPU: 52.681 sec

**Comment by jts** [comment]
I think I've found the problem and have fixed it in fa33c7172. Could you give it a try?

**Comment by rmnorris** [comment]
As it is, it doesn't run for me:
>make: *** No rule to make target `../../data/fasta/JR_FAA35548_13042015_KpneCAV1016_clean/all/2d.pp.sorted.bam', needed by `all'.  Stop.
If I replace the 'all:' with 'all=' it runs, but again doesn't create the .pp. files.

**Comment by jts** [comment]
Can you try to run it so that the READS and ASSEMBLY files are in your current working directory?

**Comment by rmnorris** [comment]
The ASSEMBLY file was already there. I copied the READS file over (as 2d.fasta). Still get the error message:
>make: *** No rule to make target `2d.pp.sorted.bam', needed by `all'.  Stop.

(also now a clock difference error, but I'll fix that)

**Comment by jts** [comment]
Ah, please use "2d.fa" not "2d.fasta". I'll fix this a bit later too.

**Comment by rmnorris** [comment]
Aha! It looks like it's working. A .pp.fa file has appeared. Thanks

**Comment by jts** [comment]
Great. I just changed the script so that it will handle .fasta as input as well (6df0d012f5710). I'm closing this, please open a new issue if you have any new problems.
