### ISSUE TITLE
Abort Trap: 6 error

### ISSUE THREAD

**Issue by woodford87** [jts/nanopolish#171]
I'm getting an Abort trap:6 code error when I try to generate a consensus sequence. 

`nanopolish consensus -w 1910bp:1-1910 --reads /Users/lukewoodford/Data/Input/DWVsurvey/500_read_subsets/DWV_BC01_500a.fa --bam BC01_500reads.eventalign.sorted.bam --genome /Users/lukewoodford/Data/Refs/DWV/REF1910.fa --models /usr/local/bin/nanopolish_dir/etc/r9-models/ -o /Users/lukewoodford/Desktop/BC01_DWV_500reads.fa 
Abort trap: 6`

Does anyone know what is causing this and how to fix it?

Thanks, Luke

**Comment by jts** [comment]
`nanopolish consensus` is deprecated, try using `nanopolish variants --consensus` instead (see README for the syntax)

**Comment by woodford87** [comment]
Thanks. I've got the following error now 

`nanopolish variants --consensus polished.{1}.fa -w {1} -r /Users/lukewoodford/Data/Input/DWVsurvey/500_read_subsets/DWV_BC01_500a.fa -b BC01_500reads.eventalign.sorted.bam -g /Users/lukewoodford/Data/Refs/DWV/REF1910.fa -t 1 --min-candidate-frequency 0.1
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
Error: could not find path to FAST5 for read 0052e7d0-fd76-48bf-94e9-6eaef5dc6fd9_Basecall_2D:2D_000:2d
Please make sure that this path is accessible: `/Users/lukewoodford/Data/Albacore_analysis/workspace/barcode01/Lukes_MacBook_Pro_local_20170427_FNFAE22557_MN20133_sequencing_run_270417_DWV_26537_ch272_read12418_strand.fast5``

Not sure why it is saying it can't find a particular read. I've checked and that sequence is definitely in that directory and the path is correct.

**Comment by jts** [comment]
This looks like a difference between OSX and Linux. I'm looking into it.

**Comment by woodford87** [comment]
Hi Jared, just wondering if you've had any joy with this?

**Comment by jts** [comment]
Not yet sorry. Is it possible for you to run nanopolish on a linux system?

**Comment by woodford87** [comment]
We'll need to set a system up for that, we're exploring that option now.

**Comment by woodford87** [comment]
Hi Jared, I've switched to a linux system and I'm trying to process the same files. I'm getting an error now of 
`error: could not parse model string`
when trying to eventalign my indexed sam files. 

What does this error mean and do you know a way around it?

**Comment by jts** [comment]
You need to basecall your files with the standalone version of albacore, not MinKNOW.

**Comment by woodford87** [comment]
Hi Jared, these reads were basecalled using Albacore 1.1.0 (they are 2D reads, so I haven't ungraded!).

**Comment by jts** [comment]
If you use albacore 1.2.4 it should work - it is the most recent version that includes 2D support.

**Comment by woodford87** [comment]
ok, I'll try that out. Thanks

**Comment by woodford87** [comment]
Hi Jared, my second albacore set using version 1.2.4 gave me the same error as before. Following advice you'd posted elsewhere I extracted all files as 1D reads and tried the process again.

I'm now getting the following errors: 
`nanopolish eventalign -t 4 --sam -r '/home/david/bin/Barcode01_1d/312_1d_90_T00001.fa' -b '/home/david/bin/BC01_312_0001reads.sorted.bam' -g '/home/david/bin/Ref/BC01_1d_312_00001ref.fa' --models '/home/david/Downloads/nanopolish/etc/r9-models' | samtools view -S - | samtools sort -O BAM -o '/home/david/bin/BC01_312_0001reads.eventalign.sorted.bam'
Error: duplicate read name 7f6dc0d0-4a7f-437b-b821-74501e7d3501_Basecall_1D_template:1D_001:template found in fasta file`

And when I remove the repeated read...

`david@linus:~$ nanopolish eventalign -t 4 --sam -r '/home/david/bin/Barcode01_1d/312_1d_90_T00001.fa' -b '/home/david/bin/BC01_312_0001reads.sorted.bam' -g '/home/david/bin/Ref/BC01_1d_312_00001ref.fa' --models '/home/david/Downloads/nanopolish/etc/r9-models' | samtools view -S - | samtools sort -O BAM -o '/home/david/bin/BC01_312_0001reads.eventalign.sorted.bam'
[fai_load] build FASTA index.
[E::sam_parse1] missing SAM header
[W::sam_read1] parse error at line 1
[bam_sort_core] truncated file. Aborting.`

Can you offer any advice here?
Thanks.

**Comment by jts** [comment]
Hi,

 The `--sam` and `--models` options are no longer required and you shouldn't need to provide them. What are you trying to do with nanopolish (call SNPs, call a consensus sequence, etc)? If you let me know I might be able to improve your workflow.

Regarding the error, trying running `eventalign` on its own (without piping into `samtools`) and it might print a more informative error message.

Jared

**Comment by woodford87** [comment]
Hi, 

I'm trying to generate consensus sequences. I've tried what you've suggested and I'm able to print the eventalign output in terminal, but I'm not sure how to output this as a file which can then be indexed.

Simple > eventalign.sorted.bam prints all output, but this is obviously not the right format for indexing...

**Comment by jts** [comment]
Ok. You should use this workflow, which does not require running eventalign:

https://github.com/jts/nanopolish#computing-a-new-consensus-sequence-for-a-draft-assembly

**Comment by woodford87** [comment]
OK, I think I'm nearly there...

Getting the following during consensus generation:
`nanopolish variants --verbose --consensus BC01_312_00333con.fa --window 649ed0bf:1-1500 --reads '/home/david/bin/Barcode01_1d/312_1d_90_T00333.fa' --bam '/home/david/bin/BC01_312_00333reads.sorted.bam.bai' --genome '/home/david/bin/Ref/BC01_1d_312_00333ref.fa'
##fileformat=VCFv4.2
##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">
##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">
##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">
##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">
##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
nanopolish: src/alignment/nanopolish_alignment_db.cpp:364: void AlignmentDB::load_region(const string&, int, int): Assertion `m_region_end >= 0' failed.
Aborted`

**Comment by jts** [comment]
You've given the `.bai` file as the `--bam` argument instead of the `.bam`.

**Comment by woodford87** [comment]
Ah yes, woops! I've removed it, however I'm getting the same error. I wondered if it was a fault with the --window argument? Currently I'm using the name of the ref fasta and seq length, is this appropriate?

**Comment by jts** [comment]
Yeah, that should be fine. Are you using the latest version of nanopolish?

**Comment by woodford87** [comment]
It's 0.7.1

**Comment by jts** [comment]
Is `649ed0bf` the complete name of the fasta record?

**Comment by woodford87** [comment]
Yes

**Comment by jts** [comment]
I just pushed a change that might help identify the problem, could you update to the latest code and test it?

**Comment by woodford87** [comment]
Hi, here is the output with the updated Nanopolish:
`/home/david/nanopolish/nanopolish variants --consensus BC01_312_00333con.fa --window 649ed0bf:0-1593 --reads '/home/david/bin/Barcode01_1d/312_1d_90_T00333.fa' --bam '/home/david/bin/BC01_312_00333reads.sorted.bam' --genome '/home/david/bin/Ref/BC01_1d_312_00333ref.fa'
error: faidx could not get contig length for contig 649ed0bf`

**Comment by jts** [comment]
Ok so either `649ed0bf` is not a valid fasta record name, or your `.fai` file is corrupted. Maybe try to delete the .fai file and try again?

**Comment by woodford87** [comment]
Great, deleting the .fai file has worked and the consensus file has been generated. Thank you so much for all your help!

**Comment by jts** [comment]
Great, glad to hear it!
