### ISSUE TITLE
version number mismatch?

### ISSUE THREAD

**Issue by sharon558** [jts/nanopolish#172]
Dear nanopolish developers, 
I did `git clone --recursive https://github.com/jts/nanopolish.git` a minute ago. After building the files, I found the version is still v0.6.2, not v0.7.  Did I miss something?

$ ./nanopolish --version
nanopolish version 0.6.2
Written by Jared Simpson.

Thanks!
Sharon

**Comment by jts** [comment]
Sorry, forgot to push the commit with the new version number. Please try again!

**Comment by sharon558** [comment]
Thanks Jared! It workded!
