### ISSUE TITLE
variants: a --models file must be provided????

### ISSUE THREAD

**Issue by caonetto** [jts/nanopolish#173]
I am running the following command.
python /usr/lib/nanopolish/nanopolish_makerange.py contigs_copy.fasta | parallel --results nanopolish.results -P 8 \
    nanopolish variants --consensus polished.{1}.fa -w {1} -r /mnt/jiao/nanopore/unyciclerrun/allfiles.fastq -b reads.sorted.bam -g contigs_copy.fasta -t 4 --min-candidate-frequency 0.1

I keep on getting the following output...

variants: a --models file must be provided

Any ideas?

**Comment by jts** [comment]
Hi,

Your version of nanopolish is out of date. Please upgrade to 0.7.0.

jared

**Comment by caonetto** [comment]
Thanks, Any ideas on how to update to 0.7 in Debian? I am having some troubles following the standard installation instructions. 

Thanks.

**Comment by jts** [comment]
Please use the latest version, I can't provide support for older versions. To build it in debian, install gcc version 4.8 or 4.9 and run this make command:

`make CXX=g++-4.8` (or whatever version of gcc you installed)

**Comment by caonetto** [comment]
Thanks Jared,
Can it be installed with a newer version of GCC?I have gcc 6.3

Thanks Again!
