### ISSUE TITLE
Running Nanopolish in parallel using Slurm

### ISSUE THREAD

**Issue by rrwick** [jts/nanopolish#174]
Note: this isn't actually an issue - it all works fine! I just thought I'd log what I did so if somebody searches for "slurm" in the Nanopolish issues, they'd find this.

I use a cluster which is managed by [Slurm](https://slurm.schedmd.com/) and wanted to run Nanopolish as fast as possible. So instead of using `parallel` as shown in the Nanopolish README, I launched a separate job for each range:
`for range in $(python nanopolish_makerange.py draft.fa); do sbatch --nodes=1 --job-name=Nanopolish_"$range" --ntasks=1 --cpus-per-task=2 --mem=4096 --time=0-8:0:00 --wrap "nanopolish variants --consensus polished."$range.fa" -w "$range" -r reads.fa -b reads.sorted.bam -g draft.fa -t 2 --min-candidate-frequency 0.1"; done`

Then when they are all done, merge them together, as normal:
`python nanopolish_merge.py polished.*.fa > polished_genome.fa`

This let me run all 113 ranges of my bacterial genome simultaneously on different nodes of the cluster, and it was done in a couple of hours!

**Comment by jts** [comment]
Thanks @rrwick, I'm sure someone will find this useful!
