### ISSUE TITLE
eventalign summary: Assertion `ea.hmm_state == 'E'' failed.

### ISSUE THREAD

**Issue by Deruijter** [jts/nanopolish#175]
When using the new --summary FILE argument in eventalign I get the following error:

nanopolish: src/alignment/nanopolish_eventalign.cpp:471: EventalignSummary summarize_alignment(const SquiggleRead&, uint32_t, const EventAlignmentParameters&, const std::vector<EventAlignment>&): Assertion `ea.hmm_state == 'E'' failed.
Aborted (core dumped)

The command I used was:
~/Applications/nanopolish/nanopolish eventalign -r chr20_part05.fasta -b chr20_part05.sorted.bam -g ../genomes/hg38.fa --summary eventalign_summary.txt > eventalign.tsv

The fast5 data is was published here: https://github.com/nanopore-wgs-consortium/NA12878 (only chr20 part05)

The application runs fine without the --summary FILE argument.

**Comment by jts** [comment]
Fixed, thanks for the report!
