### ISSUE TITLE
too many arguments?

### ISSUE THREAD

**Issue by yusmiatiliau** [jts/nanopolish#176]
Hi, I try to run:
python "/media/WORKSPACE/cen/nanopolish/scripts/nanopolish_makerange.py" 15amplicon_formated.fasta | parallel --results nanopolish.results -P 8  nanopolish variants -- consensus polished.{1}.fa -w {1} -r barcode15_nanopolish.fa" -b barcode15.sorted.bam" -g 15amplicon_formated.fasta -t 4 --min-candidate-frequency 0.1

but got this message:
variants: too many arguments
variants: a --reads file must be provided
variants: a --genome file must be provided
variants: --ploidy parameter must be provided
variants: a --bam file must be provided

Can you tell me what is wrong here?

Thanks

**Comment by jts** [comment]
There is an errant space in `-- consensus`, it should be `--consensus`. The second set of quotes may be problematic as well.
