### ISSUE TITLE
zsh:1: command not found: nanopolish

### ISSUE THREAD

**Issue by JacLach** [jts/nanopolish#177]
Hello, i try to run command:
python nanopolish_makerange.py /media/blul/workspace/draft.fasta | parallel --results /media/blul/workspace/nanopolish.results -P 8 nanopolish variants --consensus /media/blul/workspace/polished.{1}.fa -w {1} -r /media/blul/workspace/reads.fasta -b /media/blul/workspace/reads_gal_min.sorted.bam -g /media/blul/workspace/draft.fasta -t 8 --min-candidate-frequency 0.1

but got these massage:

zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish
zsh:1: command not found: nanopolish

Can you say me what is wrong?

**Comment by jts** [comment]
Hi,

You either need to put nanopolish on your PATH, or give the full path to nanopolish in the parallel command.

Jared
