### ISSUE TITLE
File nanopolish_merge.py", line 89, in <module>     assert(prev_segment is None or prev_segment + SEGMENT_LENGTH + OVERLAP_LENGTH > segment_start) AssertionError

### ISSUE THREAD

**Issue by caonetto** [jts/nanopolish#179]
Hi, I the last merging step I got the following error:
While looking at the files in the nanopolish.results folder almost all of the files (stdout and stderr) are empty files)

Number of variants in span (25) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (12) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (37) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (65) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (19) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (15) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (10) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (12) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (18) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (13) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (20) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (10) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (11) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (11) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
[post-run summary] total reads: 823 unparseable: 24 qc fail: 2 could not calibrate: 22
ubuntu@bio-linux:/mnt/cris/final_nanopolish/final_polished$ python /home/ubuntu/nanopolish/scripts/nanopolish_merge.py polished.*.fa > polished_genome.fa
Insert Node_1 49960
Insert Node_2 1049960
Insert Node_2 799960
Insert Node_2 849960
Merging Node_1 49960
Merging Node_2 799960
Merging Node_2 849960
Merging Node_2 1049960
Traceback (most recent call last):
  File "/home/ubuntu/nanopolish/scripts/nanopolish_merge.py", line 89, in <module>
    assert(prev_segment is None or prev_segment + SEGMENT_LENGTH + OVERLAP_LENGTH > segment_start)
AssertionError

Any ideas?
The output only gave one short contig. Is this because of the max-haplotypes?

Thanks.

**Comment by jts** [comment]
The max-haplotypes message is just a warning and can be ignored. It looks like some of the polishing steps failed though as parts of contig `Node_2` are missing (the contig is at least 1Mb but only 150kb of polished sequence was found). You'll have to take a look to see why those jobs failed (I suspect they ran out of memory).

Jared

**Comment by caonetto** [comment]
Thanks Jared, I trying running the same files in another cloud with more memory, but I keep on getting the following error 
Error: could not find path to FAST5 for read 0000914b-f7c3-4bd4-ba21-eba0466bba5b_Basecall_1D_template:1D_000:template
Please make sure that this path is accessible: /mnt/cris/allbasecalled/all/DPB9XH6V_20170504_FNFAE21462_MN18577_sequencing_run_JJ2_49_40517_82302_ch494_read5889_strand.fast5
##fileformat=VCFv4.2
##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">
##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">
##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">
##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">
##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
Error: could not find path to FAST5 for read 0000914b-f7c3-4bd4-ba21-eba0466bba5b_Basecall_1D_template:1D_000:template
Please make sure that this path is accessible: /mnt/cris/allbasecalled/all/DPB9XH6V_20170504_FNFAE21462_MN18577_sequencing_run_JJ2_49_40517_82302_ch494_read5889_strand.fast5


Any ideaS?

**Comment by zachcp** [comment]
I recently encountered this same issue.  I used  `poretools extract` to create the fasta files. it will add the fast5 locations to the fasta record lines.

**Comment by jts** [comment]
Hi @caonetto,

As @zachcp suggets, this looks like a problem with how the reads are extracted. You'll have to re-extract the reads so that nanopolish can find them. It is important to not move the files around after they are extracted our else the paths will be broken.

Jared
