### ISSUE TITLE
nanopolish variants error Unknown model type string: , 

### ISSUE THREAD

**Issue by tpshea2** [jts/nanopolish#180]
Hello-

Might one have insight into the following error?

I have assembled E. coli Oxford Nanopore data (with a fasta file of reads generated by nanopolish extract version 0.7.1) and now wish to polish the assembly using nanopolish version 0.7.1

Command (showing just one region, the error is the same is I give the entire contig as a single region):

> nanopolish variants --consensus=contigs.nano_polished.fasta -r ecoli.nanopolished_extracted.longest_50x.fasta -b contigs.reads.bam -g 50x_np_extracted.canu.contigs.fasta -t 4 -o nanopolish.out -w tig00000001:2850000-2900200

error is:

> Unknown model type string: , please report on github.

data type is R9 1D

Canu assembled the read data into single contig, but only at ~98.1% identity to reference in the nucmer-aligned regions)  The contig fasta header is:

>tig00000001 len=4584112 reads=11273 covStat=3540.43 gappedBases=no class=contig suggestRepeat=no suggestCircular=no

I wonder if something is wrong/missing with the underlying fast5 files.  When I run nanopolish getmodel on a fast5 file I only get this:

> strand  kmer    model_mean      model_stdv

Here is an example extracted read fasta header:

> >1c11d830-aeee-49a2-a545-9f13e24e0392_Basecall_Alignment_template:1D_001:template GPBE6_F39_20170222_FNFAF04846_MN19835_sequencing_run_FAF04846_QC2_Prerun_02_22_2017_70677_ch495_read650_strand /btl/projects/advancedlibraryprep/oxford/ecoli_1D_02_22_2017/reads/downloads/pass/batch_1487805679317/GPBE6_F39_20170222_FNFAF04846_MN19835_sequencing_run_FAF04846_QC2_Prerun_02_22_2017_70677_ch495_read650_strand.fast5

Can anyone suggest where to troubleshoot?

Thank you.

**Comment by jts** [comment]
Hi,

This error occurs when you basecall the reads with the MinKNOW local basecaller. Please use albacore instead.

Jared

**Comment by jts** [comment]
Commit 4f1983a will print a more useful error message in this case.

**Comment by tpshea2** [comment]
Hello-

(Please let me know if I should open a new ticket.  I realize this one has been closed for some time).

Albacore was used to re-call some of our ONT data.   In running the most recent nanopolish extract (v 0.8.1) I get the following when trying the command on a single fast5 file:

> nanopolish extract -t any -o test.8.1.extract.fasta --log-level debug /btl/projects/advancedlibraryprep/oxford/ecoli_1D_02_22_2017/reads/uploaded/pass/0/GPBE6_F39_20170222_FNFAF04846_MN19835_sequencing_run_FAF04846_QC2_Prerun_02_22_2017_70677_ch512_read188_strand.fast5
> set default log level to: 3
> = extract.2 nanopolish_extract.cpp:365 parse_extract_options paths: /btl/projects/advancedlibraryprep/oxford/ecoli_1D_02_22_2017/reads/uploaded/pass/0/GPBE6_F39_20170222_FNFAF04846_MN19835_sequencing_run_FAF04846_QC2_Prerun_02_22_2017_70677_ch512_read188_strand.fast5
> = extract.2 nanopolish_extract.cpp:366 parse_extract_options recurse: no
> = extract.2 nanopolish_extract.cpp:367 parse_extract_options read_type: any
> = extract.2 nanopolish_extract.cpp:368 parse_extract_options basecaller_name: 
> = extract.2 nanopolish_extract.cpp:369 parse_extract_options basecaller_version: 
> = extract.2 nanopolish_extract.cpp:224 process_path /btl/projects/advancedlibraryprep/oxford/ecoli_1D_02_22_2017/reads/uploaded/pass/0/GPBE6_F39_20170222_FNFAF04846_MN19835_sequencing_run_FAF04846_QC2_Prerun_02_22_2017_70677_ch512_read188_strand.fast5
> = extract.3 nanopolish_extract.cpp:156 process_file /btl/projects/advancedlibraryprep/oxford/ecoli_1D_02_22_2017/reads/uploaded/pass/0/GPBE6_F39_20170222_FNFAF04846_MN19835_sequencing_run_FAF04846_QC2_Prerun_02_22_2017_70677_ch512_read188_strand.fast5
> = extract.3 nanopolish_extract.cpp:143 get_preferred_basecall_groups preferred_groups: 
> = extract.2 nanopolish_extract.cpp:175 process_file file [/btl/projects/advancedlibraryprep/oxford/ecoli_1D_02_22_2017/reads/uploaded/pass/0/GPBE6_F39_20170222_FNFAF04846_MN19835_sequencing_run_FAF04846_QC2_Prerun_02_22_2017_70677_ch512_read188_strand.fast5]: no basecalling data suitable for nanoplish
> Error running faidx_build on test.8.1.extract.fasta.fa.gz
> 

So we still not have all that is needed to use nanopolish to improve our consensus.  Is there something wrong with the command itself above or is there something missing on the filesystem ( e.g. event-level data)?

We hope that something can still be salvaged in order to run nanopolish with the existing data.

Thank you for any assistance you might be able to provide.

**Comment by jts** [comment]
What basecaller version did you use? If you use albacore version 2.0 or later, you should use `nanopolish index` rather than `nanopolish extract`. See here:

https://github.com/jts/nanopolish#data-preprocessing

**Comment by tpshea2** [comment]
Thank you.  I think that I am making progress now.

nanopolish index was run and appears to have worked as it generated the following files (where input was "albacore.fastq":


>  albacore.fastq.fa.gz.gzi
>  albacore.fastq.fa.gz.fai
> albacore.fastq.fa.gz.readdb

While only a small fraction of the reads have path (stderr/out from nanopolish index):

> [readdb] num reads: 168540, num reads with path: 6064

I think this should be fine at least to see if nanopolish variants --consensus may be able to improve accuracy.

My next question is if there is a problem with file name for the  albacore.fastq.fa.gz.fai file.  My command here:


> nanopolish variants --consensus polished.fa -r  albacore.fastq.fa.gz -b 50x_ont_canu.aligned.sorted.bam -g 50x_ont_canu.contigs.fasta -t 4 --min-candidate-frequency 0.1

returns:

> [fai_load] fail to open FASTA file.

and

> nanopolish: src/nanopolish_read_db.cpp:179: std::__cxx11::string ReadDB::get_read_sequence(const string&) const: Assertion `m_fai != __null' failed.
> Abort (core dumped)
> 

I tried this as link to file:

> albacore.fastq.fa.gz.fa.gz.fai -> albacore.fastq.fa.gz.fai

but still get that fail to open FASTA error.  Is there a problem with the name of this .fai file?  (too many "." ?)

Thank you.

**Comment by jts** [comment]
> [readdb] num reads: 168540, num reads with path: 6064

This indicates something went wrong and nanopolish won't work properly - it seems nanopolish index wasn't able to find the signal files for most of the input reads. Do you have any idea why? Do you still have the original fast5s?

**Comment by jts** [comment]
Also, when you run `nanopolish variants` you should pass it the original file produced by albacore: `-r albacore.fastq` not `-r albacore.fastq.fa.gz` (I realize this is confusing though)

**Comment by tpshea2** [comment]
Thank you Jared.  I was just informed that the albacore basecalled run was an earlier version.  I have requested it be re-run with recently installed 2.0.2.  Thank you again for your help.

**Comment by tpshea2** [comment]
Hi Jared.
We now have nanopolish working on newly generated data.  I think this particular can be closed.  Thank you.

**Comment by jts** [comment]
great, thanks for reporting back.
