### ISSUE TITLE
"Segmentation fault" in variant calling and no action in methylation calling 

### ISSUE THREAD

**Issue by scoa-git** [jts/nanopolish#181]
Hi!

I am trying to call methylation and variants in isolated mtDNA genomes, but I am having some issues which I can't figure out. 

starting from the fast5 I aligned to reference using 
`poretools fasta fast5/ > mtdna_reads.fasta`
`bwa index mtdna_rcs.txt`
`bwa mem -x ont2d mtdna_rcs.txt mtdna_reads.fasta > mtdna.sam`
`samtools view -bS mtdna.sam > mtdna.bam`
`samtools sort mtdna.bam sorted_mtdna.bam`
`samtools index sorted_mtdna.bam`

untril here everything seems ok. 

When I then try to call variants  with
`nanopolish variants --reads mtdna_reads.fasta --bam sorted_mtdna.bam --genome mtdna_rcs.txt > mtdna_snps.vcf`

I get 
`qf@qf-ESPRIMO-P420:/media/qf/Volume/data_np/20170627_mtDNA_HEK/fast5$ nanopolish variants --reads mtdna_reads.fasta --bam sorted_mtdna.bam --genome mtdna_rcs.txt > mtdna_snps.vcf`
`TODO: train model`
`TODO: filter data`
`[fai_fetch_seq] The sequence "" not found`
`Segmentation fault (core dumped)`

The reference is a fasta formatted file and the fast5 are located one subdirectory deeper

When I use a plain sequence file as reference I get 
`[fai_load] build FASTA index.`
`Segmentation fault (core dumped)`

Conversely,  when we call methylation

`nanopolish call-methylation -t 1 -r mtdna_reads.fasta -g mtdna_rcs.txt -b sorted_mtdna.bam > methylation.tsv`
 
(threads set to 1 just for troubleshooting)
absolutely nothing happens. The prompt just reappears instantaneously. The methylation file is created but is empty (0 kb).

nanopolish version is 0.4 installed via bioconda. fast5 were called with local basecaller. Can this cause the observed issue? I am not sure whether nanopolish has even accessed the fast5 at the moment of giving the error. 
Thank you for any help!

kr
stefan

**Comment by jts** [comment]
Hi,

0.4 is very old, please upgrade to 0.7.1 at least. You'll need to rbasecall your reads using albacore before using nanopolish (MinKNOW does not write all the information nanopolish needs).

You should provide to both programs the region of the reference genome that you would like to process in the format `-w chr:start-end`.

Jared

**Comment by scoa-git** [comment]
Hi!

thank you for the fast answer! Ok, I wasn't aware that the version is so old! What is the best way to update without any "version mixing" of the dependencies? Sorry for the naive question, I am just quite new in linux.

**Comment by jts** [comment]
I suggest trying to install from the source code here on github: https://github.com/jts/nanopolish#installation-instructions.

**Comment by scoa-git** [comment]
ok. I am not sure whether I managed. I cloned from github, went into the created directory and  run "make". However, when I now try to start  nanopoish from the command line i get 
`nanopolish: command not found`

**Comment by jts** [comment]
You need to give the full path to the program:

`/path/where/you/cloned/nanopolish`

**Comment by scoa-git** [comment]
When running make?

**Comment by jts** [comment]
No, after you have run make, when you are trying to run it. For example I have cloned nanopolish into `/home/jsimpson/code/nanopolish` so when I run it I use `/home/jsimpson/code/nanopolish/nanopolish`

**Comment by scoa-git** [comment]
aaah. Ok works. Sorry for the very basic questions. I am new in this (wet lab biologist). Thank your so much!

stefan

**Comment by jts** [comment]
No problem, glad it works now!
