### ISSUE TITLE
nanopolish variants 

### ISSUE THREAD

**Issue by yusmiatiliau** [jts/nanopolish#182]
Hi, 

I am using MinION to call multiple SNPs and in-dels from a multiplex PCR. in total, I have 15 amplicons. One of my reference samples have 2 SNPs and 1 one-base deletion (Heterozygotes). 

"/media/WORKSPACE/cen/nanopolish/scripts/nanopolish_makerange.py" 15amplicon_formated.fasta | parallel --results barcode022_nanopolish.results -P 8 nanopolish variants --consensus polished.{1}.fa -w {1} -r barcode02_nanopolish.fa -b barcode02_nanopolish.sorted.bam -g 15amplicon_formated.fasta -t 4 --min-candidate-frequency 0.1 

I have several questions:
1. in both of the SNPs called by nanopolish variants, it gave me two lines:
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
ABCB1	102	.	T	C	51976.9	PASS	TotalReads=3821;AlleleCount=1;SupportFraction=0.413547	GT	1
ABCB1	102	.	T	C	51667.2	PASS	TotalReads=3824;AlleleCount=1;SupportFraction=0.969851	GT	1

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample
VKORC1rs7294    115     .       G       A       7746.0  PASS    TotalReads=1595;AlleleCount=1;SupportFraction=0.792303  GT      1
VKORC1rs7294    115     .       G       A       7718.2  PASS    TotalReads=1595;AlleleCount=1;SupportFraction=0.891691  GT      1

what is the difference between those two lines? For ABCB1, the sample should have CC genotype, so I think the second line is correct. But, if I don't know the genotype, how can I tell which one should I use?

2. I try to write the results into vcf file, using this command:

"/media/WORKSPACE/cen/nanopolish/scripts/nanopolish_makerange.py" 15amplicon_formated.fasta | parallel --results barcode022_nanopolish.results -P 8 nanopolish variants --consensus polished.{1}.fa -w {1} -r barcode02_nanopolish.fa -b barcode02_nanopolish.sorted.bam -g 15amplicon_formated.fasta -t 4 --min-candidate-frequency 0.1 --o barcode022_nanopolish.vcf

but the vcf file only contained the ABCB1 variants, and don't the other one, what arguments should I add?

2. the nanopolish variants failed to call the one-base deletion. when I looked at the bam file (IGV), the deletion site has 1213 read depth, and the deletion depth is 664, which is quite good. Do you have any idea, so the deletion would be called by nanopolish variants?

Thanks a bunch!

Cen

**Comment by jts** [comment]
Hi,

If you are calling variants with respect to a reference genome I suggest you do not use the `--consensus` option and use `--ploidy 2` since you are looking for heterozygotes. 

The syntax of running in variant-calling mode is similar:

```
nanopolish variants -r barcode02_nanopolish.fa -b barcode02_nanopolish.sorted.bam -g 15amplicon_formated.fasta -t 4 --min-candidate-frequency 0.1 -w CHR:START-END --ploidy 2 > variants.vcf
```

You'll need to change CHR, START, END to the region of the reference genome that you want to call.

Running in this mode with `--ploidy 2` should help with the issues you had. Let me know how it goes after you re-run it.

Jared

**Comment by yusmiatiliau** [comment]
Hi,

THanks! so if I just want to call variants, I do not need to run the makerange.py command, am I right?

Above syntax that you gave me, run ok, and give me the vcf file. Just wondering, because I have 15 contigs in my reference genome. Can I call the variants in all contigs in one command and create a single vcf file, or do I need to run it one by one and have 15 different vcf file for each sample? 

Thank you so much!

Cen

**Comment by jts** [comment]
That's right, you don't need makerange.py, but you will have to run it on each contig separately.

**Comment by yusmiatiliau** [comment]
Thanks! from my initial random run on several contigs, it seems like I still failed to call some variants in my reference sampel. I have more than 80 samples, I'll have them all run and get back to you to get some more advice on the failed variant calling.

Thanks,
Cen

**Comment by jts** [comment]
Ok

**Comment by yusmiatiliau** [comment]
Hi Jared, 

Thank you for helping so far! I've called the variants from all my samples. It seems like variants were not called for some contigs (CYP2C1927, CYP4F2, CYP2C96 (del)). 

I've attached some fa, bam, and the reference file if you could have a look?

and I also wonder, what is the default min-frequency to call a homozygote? is there any options to set to another number?

[nanopolish.zip](https://github.com/jts/nanopolish/files/1147413/nanopolish.zip)


Thanks,
cen

**Comment by jts** [comment]
Hi,

Did you include the fast5 files? I'll need those to look. What variants are you expecting? I'll try to look when I have a chance.

Jared

**Comment by yusmiatiliau** [comment]
Hi Jared, I put the fast5 files for sample Barcode01, barcode02, and barcode71 on google drive as below:
https://drive.google.com/file/d/0B1_0hZNTRL0hMFk5aGJ2bjUyRFU/view?usp=sharing

barcode01 should have GA genotype on CYP2C1927 at position 37
barcode02 should have heterozygous delA on CYP2C96 at position 140
barcode71 should have GA genotype on CYP4F2 at position 40

Thanks a lot!

**Comment by yusmiatiliau** [comment]
Hi Jared,

I know it's been a while, but wonder if you know why the variant calling failed for some SNPs? the SNPs was quite visible on the BAM file, but I couldn't call it in the vcf file using nanopolish variant.

Thanks

**Comment by jts** [comment]
Hi,

Sorry I haven't looked yet. I will have more time next week and I will try to look then.

jared

**Comment by yusmiatiliau** [comment]
Thanks!

**Comment by jts** [comment]
Hi,

Can you tell me the command you used to basecall these reads? 

Jared

**Comment by jts** [comment]
Hi,

I had a look at the barcode01 test case. The problem is the variant is too close to the end of the amplicon. Nanopolish will skip anything within about 40bp of the end of the contig as the reads and alignments are less reliable here. If you'd like to change this you have to edit this value in the code:

https://github.com/jts/nanopolish/blob/master/src/nanopolish_call_variants.cpp#L127

If you set this to 10bp it will work.

I suspect that barcode71 and barcode02 is the same problem (I couldn't verify this because I don't have the fast5 files).

Is it possible to redesign your amplicons to provide more flanking sequence surrounding the region of interest?

Jared

**Comment by yusmiatiliau** [comment]
Hi,

I see! Yes, the 2 other SNPs are less or equal to 40 bp to the end of the amplicon.
I'll give it a try! Hope it works.

I can redesign the primers, but I don't have the DNA samples anymore.

Thanks a lot

**Comment by yusmiatiliau** [comment]
I have tried changing the value for min_flanking_sequence in the nanopolish_call_variants.cpp from 30 to 10 and them 5, but it didn't seem to work. Am I doing it right? the cpp file is in the scr directory.

**Comment by yusmiatiliau** [comment]
Hi,

Wonder if I did it wrong, but changing the min_flanking_sequence didn't seem to work to call variants in the 40 bp from the end. Really hope you can help, as I found nanopolish works the best compared to other variant calling tools for MinION, but I just couldn't get these three variants to work.

thanks

**Comment by jts** [comment]
Did you recompile the code after making the change (by running `make`)?

**Comment by yusmiatiliau** [comment]
No, I didn't. It works now :). Thanks a lot!
