### ISSUE TITLE
nanopolish extract doesn't extract sequence from files

### ISSUE THREAD

**Issue by JacLach** [jts/nanopolish#184]
Hello, i've got a problem with nanopolish extract. It's work without any error but after work it doesn't give any extracted sequences. We have communicate:
[extract] found 136375 files, extracted 0 reads

Thanks for help

**Comment by jts** [comment]
Hi,

This means that nanopolish couldn't find any sequences in your fast5 files. Did you run the albacore basecaller on them?

Jared

**Comment by JacLach** [comment]
Yes, I run albacore on them and it extract fastq files.

**Comment by jts** [comment]
Hi,

You need to use the `fast5` output option in albacore if you want to use the reads with nanopolish.

Jared

**Comment by JacLach** [comment]
Ok, thanks
