### ISSUE TITLE
ploidy setting for mtDNA & -w parameter syntax

### ISSUE THREAD

**Issue by scoa-git** [jts/nanopolish#187]
Hi!

I was wondering what the correct ploidy setting would be for mtDNA. Can it be freely scaled? So if we expect >2 variant bases at a position, can we set --ploidy it to 3 or 4? 

Moreover, is the -w parameter strictly necessary and what is the correct syntax? The help (-h) says ctg:start-end, while in https://github.com/jts/nanopolish/issues/181 it is chr:start-end.

When I run 

`qf0297@qf0297-ESPRIMO-P420:/media/qf0297/Volume/data_np/20170627_mtDNA_HEK/alba/fast5_alba$ /home/qf0297/nanopolish/nanopolish variants --reads mtdna_reads_alba.fasta --bam sorted_mtdna_alba.bam --genome rCRS_ME.fasta --ploidy 1 -w ctg:1-16569 > mtdna_snps_ploidy1.vcf`

it reports 

```
nanopolish: src/alignment/nanopolish_alignment_db.cpp:364: void AlignmentDB::load_region(const string&, int, int): Assertion `m_region_end >= 0' failed.
Aborted (core dumped)
```

Also using "chr" instead of "ctg" gives the same error. 

No error occurs if i omit -w . The reference is exactly 16569 bases long: so is it correct to say chr:1-16569?

Thank you
Stefan

**Comment by jts** [comment]
Hi,

nanopolish uses a discrete genotype model so it can't be freely scaled. It doesn't work well for continuous allele frequencies, like you would have in a population.

When making the -w option you should replace "chr" with the name of the chromosome (or contig) you want to process. For example if your chromosome name is "chrA" you would write `-w chrA:1000-2000`.

I hope this helps.

Jared

**Comment by jts** [comment]
I have clarified the `-w` usage in 609f6fd
