### ISSUE TITLE
calculate_methylation_frequency crashes (2)

### ISSUE THREAD

**Issue by scoa-git** [jts/nanopolish#188]
Hi!

Sorry for bothering you again. I open a new issue, as I am not sure, whether answering to the closed one  (#186) works. 
I now reinstalled nanopolish,  but the "calculate_methylation script" still gives the same error. 

`qf0297@qf0297-ESPRIMO-P420:/media/qf0297/Volume/data_np/20170627_mtDNA_HEK/alba/fast5_alba$ python ~/nanopolish/scripts/calculate_methylation_frequency.py -c 2.5 -i methylation.tsv > meth_frequencies.tsv
  File "/home/qf0297/nanopolish/scripts/calculate_methylation_frequency.py", line 82
    print "\t".join([str(x) for x in [c, s, e, sites[key].group_size, sites[key].called_sites, sites[key].called_sites_methylated, f, sites[key].sequence]])
             ^
SyntaxError: invalid syntax
qf0297@qf0297-ESPRIMO-P420:/media/qf0297/Volume/data_np/20170627_mtDNA_HEK/alba/fast5_alba$ `

But the script is however indeed the new one.

`cat calculate_methylation_frequency.py`
`[...]`
```
print("\t".join(["chromosome", "start", "end", "num_cpgs_in_group", "called_sites", "called_sites_methylated", "methylated_frequency", "group_sequence"]))

for key in sites:
    if sites[key].called_sites > 0:
        (c, s, e) = key.split(":")
        f = float(sites[key].called_sites_methylated) / sites[key].called_sites
        print "\t".join([str(x) for x in [c, s, e, sites[key].group_size, sites[key].called_sites, sites[key].called_sites_methylated, f, sites[key].sequence]])
```
 
Am I still doing something wrong when running the script? The command is for sure accessing the correct installation, as I see the changes in the -w parameter description from yesterday's issue #187 when running nanopolish variants --help

**Comment by jts** [comment]
Sorry, I missed one of the print statements. Can you try again with the latest code?

**Comment by scoa-git** [comment]
Works like a charm!

**Comment by jts** [comment]
Great, thanks for reporting the issue.

**Comment by hernandezvargash** [comment]
Hi there!
I tested nanopolish call-methylation and it seems to be working, but I get this error with the frequency function:
```
python calculate_methylation_frequency.py -i methylation_calls_BC01.tsv > methylation_frequency_BC01.tsv
Traceback (most recent call last):
  File "calculate_methylation_frequency.py", line 51, in <module>
    num_sites = int(record['num_motifs']) 
KeyError: 'num_motifs'
```
Am I doing sth wrong?
Thanks for the help,
H
