### ISSUE TITLE
Squiggle read "The basecalling model could not be detected..." with Albacore1.2.5/1D^2

### ISSUE THREAD

**Issue by zephyris** [jts/nanopolish#192]
Sorry to bother you again!

Running nanopolish variants on r9.5/1D^2 fast5 files called during data collection, then recalled for 1D^2 with Albacore 1.2.5, is giving the following error:
"Error: The basecalling model could not be detected from the fast5 file. Please re-run basecalling using albacore."

Viewing the contents of an example fast5 file with h5dump shows the model to be "template_r9.5_450bps_5mer_nontransducer.jsn", and the calling software to be "ONT Albacore Sequencing Software". It looks like this should be happily parsed by squiggle read, but is somehow being missed...

You can download an example read here:
https://www.dropbox.com/s/zscpiew9wi1ah03/gull27_20170714_FAH10619_MN18485_sequencing_run_LmxC9T7_95522_read_0_ch_5_strand.fast5?dl=0

*edit* I should say I am not certain this is an issue with all reads, or just an issue which is common enough among reads to hit every window of a nanopolish variants run.

**Comment by jts** [comment]
Hi,

Since MinKNOW live basecalling was run on the data, then albacore afterwards, you need to tell nanopolish to explicitly extract the albacore sequences:

`nanopolish extract -b albacore:1.2.5`

jared

**Comment by jts** [comment]
With commit 9e6e3c25 you no longer need to give the `-b` option as above, but you'll still need to re-extract the reads.

**Comment by zephyris** [comment]
Apologies, I had missed that change. Thanks!
