### ISSUE TITLE
Unknown model type string

### ISSUE THREAD

**Issue by gligong** [jts/nanopolish#194]
I got following errors when I ran nanopolish to compute the consensus sequence.

Unknown model type string: , please report on github.
##fileformat=VCFv4.2
##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">
##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">
##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">
##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">
##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample
Unknown model type string: , please report on github.

**Comment by jts** [comment]
Hi,

Did you run MinKNOW local basecalling?

Jared

**Comment by gligong** [comment]
Hi Jared:

We used ONT Albacore Sequencing Pipeline Software (version 1.2.4).
Thanks!

George

**Comment by jts** [comment]
Can you send me an example fast5 file?

**Comment by gligong** [comment]
Hi Jared:

Attached is one fast5 file.
Thanks!

George

**Comment by jts** [comment]
Hi,

I don't see the attachment, I think you need to use the github webpage rather than email.

Jared

**Comment by gligong** [comment]
Hi Jared:
I probably gave wrong information previously. The basecalling itself was done in MinKNOW. The fast5 files that go into Albacore are already basecalled. MinKnow was 1.7.7. Albacore was used to demutliplex reads. The fast5 file that I sent to you is created by Albacore.
Thanks for your help!

George

**Comment by jts** [comment]
I did not receive the attachment, could you attach it directly on github?

**Comment by gligong** [comment]
[DESKTOP_4U95VIL_20170621_2002041805_MN18606_sequencing_run_Hoyer_5DNA_2nd_85409_read_10012_ch_286_strand.fast5.gz](https://github.com/jts/nanopolish/files/1159860/DESKTOP_4U95VIL_20170621_2002041805_MN18606_sequencing_run_Hoyer_5DNA_2nd_85409_read_10012_ch_286_strand.fast5.gz)

**Comment by jts** [comment]
Thanks, in commit 9e6e3c25 nanopolish will automatically skip MinKNOW basecalls to avoid this error.

**Comment by jts** [comment]
(you'll need to re-`extract` your reads though)

**Comment by cjfields** [comment]
@jts thanks, we'll give it a try!

**Comment by gligong** [comment]
Hi Jared

After updating the new nanopolish, I ran extract fast5Dir > reads.fa to get reads.fasta file. The fast5Dir contains the fast5 files that were created by albacore (ONT Albacore Sequencing Pipeline Software version 1.2.4). The albacoere command that I used is "read_fast5_basecaller.py -i pass -t 14 -s newAlbacoreResults -k SQK-LSK108 -f FLO-MIN107 --barcoding --recursive -o fast5,fastq". The pass directory contains the fast5 files that are from MinKNOW 1.7.7.

When I ran Nanopolish to compute consensus sequences, I got following errors, which are different from previous ones. If I need to rerun albacore, what input files do I need? Thanks for your help!

George



##fileformat=VCFv4.2

##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">

##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">

##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">

##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">

##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">

##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">

#CHROM POS ID REF ALT QUAL FILTER INFO FORMAT sample

Error: The basecalling model could not be detected from the fast5 file. Please re-run basecalling using albacore.

##fileformat=VCFv4.2

##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">

##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">

##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">

##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">

##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">

##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">

#CHROM POS ID REF ALT QUAL FILTER INFO FORMAT sample

Error: The basecalling model could not be detected from the fast5 file. Please re-run basecalling using albacore.

**Comment by jts** [comment]
Can you send me an example fast5 file

**Comment by gligong** [comment]
Here are two fast5 file from albacore.

[DESKTOP_4U95VIL_20170621_2002041805_MN18606_sequencing_run_Hoyer_5DNA_2nd_85409_read_1003_ch_141_strand.fast5.gz](https://github.com/jts/nanopolish/files/1170765/DESKTOP_4U95VIL_20170621_2002041805_MN18606_sequencing_run_Hoyer_5DNA_2nd_85409_read_1003_ch_141_strand.fast5.gz)
[DESKTOP_4U95VIL_20170621_2002041805_MN18606_sequencing_run_Hoyer_5DNA_2nd_85409_read_10012_ch_286_strand.fast5.gz](https://github.com/jts/nanopolish/files/1170764/DESKTOP_4U95VIL_20170621_2002041805_MN18606_sequencing_run_Hoyer_5DNA_2nd_85409_read_10012_ch_286_strand.fast5.gz)

**Comment by gligong** [comment]
Hi Jared:

I just sent two fast5 files from albacore run to you through GutHub.
Thanks for your help!

George

**Comment by jts** [comment]
Hi Glilong,

I just tested this on my local build of nanopolish and it worked correctly. Can you make sure you are using the latest code from github?

Jared

**Comment by gligong** [comment]
Hi Jared:

I loaded module  nanopolish/0.7.1-IGB-gcc-4.9.4-159d92b and I ran nanopolish --version, I got nanopolish version 0.7.1.
I guss 159d92b is the updated version. I will ask our IT people to update it again. Is it better to delete the previous version and install the latest version?
Thanks for your help.

George

**Comment by jts** [comment]
Yes, please delete and upgrade.

Jared
