### ISSUE TITLE
nanopolish extract HDF5 error?

### ISSUE THREAD

**Issue by slguertin** [jts/nanopolish#195]
Running nanopolish 0.7.1

When trying to run nanopolish extract (./nanopolish extract /home/sguertin/170623_A_data/re-calls/pass-only/workspace -o /home/sguertin/170623_A_data/20170623_A_nanopolishextract.fa), I get the following error: 
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140653545621504:
  #000: H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1085 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: H5Fsuper.c line 294 in H5F_super_read(): unable to load superblock
    major: Object cache
    minor: Unable to protect metadata
  #003: H5AC.c line 1320 in H5AC_protect(): H5C_protect() failed.
    major: Object cache
    minor: Unable to protect metadata
  #004: H5C.c line 3574 in H5C_protect(): can't load entry
    major: Object cache
    minor: Unable to load metadata into cache
  #005: H5C.c line 7954 in H5C_load_entry(): unable to load entry
    major: Object cache
    minor: Unable to load metadata into cache
  #006: H5Fsuper_cache.c line 476 in H5F_sblock_load(): truncated file: eof = 62047, sblock->base_addr = 0, stored_eoa = 225373
    major: File accessibilty
    minor: File has been truncated

Is the root cause of this an hdf5 issue, a nanopolish issue, or something else entirely?

**Comment by jts** [comment]
Hi,

Based on the last error `minor: File has been truncated` it seems there is a problem with one of your fast5 files. Maybe you ran out of disk space when basecalling?

Jared

**Comment by slguertin** [comment]
Possible, but irritating if so. I'll check - thanks!
