### ISSUE TITLE
Squiggle Read assertion failed

### ISSUE THREAD

**Issue by sharon558** [jts/nanopolish#196]
I saw a similar thread (https://github.com/jts/nanopolish/issues/137) but it's close so I'm opening a new issue. Nanopolish eventalign (V 0.7.0) throws an error when using Albacore (latest version) called 1D files.

nanopolish: src/nanopolish_squiggle_read.cpp:263: void SquiggleRead::_load_R9(uint32_t, const string&, const std::vector<EventRangeForBase>&, const std::vector<double>&, uint32_t): Assertion `fields.size() == 4' failed.

I checked the fast5 file contents using h5ls and it seems the events data is correct:
/                        Group
/Analyses                Group
/Analyses/Basecall_1D_000 Group
/Analyses/Basecall_1D_000/BaseCalled_template Group
/Analyses/Basecall_1D_000/BaseCalled_template/Events Dataset {5735}
/Analyses/Basecall_1D_000/BaseCalled_template/Fastq Dataset {SCALAR}
/Analyses/Basecall_1D_000/Configuration Group
/Analyses/Basecall_1D_000/Configuration/basecall_1d Group
/Analyses/Basecall_1D_000/Summary Group
/Analyses/Basecall_1D_000/Summary/basecall_1d_template Group
/Analyses/Segmentation_000 Group
/Analyses/Segmentation_000/Configuration Group
/Analyses/Segmentation_000/Configuration/event_detection Group
/Analyses/Segmentation_000/Configuration/stall_removal Group
/Analyses/Segmentation_000/Summary Group
/Analyses/Segmentation_000/Summary/segmentation Group
/Raw                     Group
/Raw/Reads               Group
/Raw/Reads/Read_99       Group
/Raw/Reads/Read_99/Signal Dataset {42420/Inf}
/UniqueGlobalKey         Group
/UniqueGlobalKey/channel_id Group
/UniqueGlobalKey/context_tags Group
/UniqueGlobalKey/tracking_id Group

Example events:
      (5679) {114.222, 4.19762, 197.178, 0.00166003, "GTAAC", 1, 0.999999, 0.675906, "GTAAC", 0.675906,
        (5679)  0.864481, 0.049184, 0.0690395, 0.0172961},
        (5680) {90.3697, 2.53127, 197.18, 0.00166003, "GTAAC", 0, 0.999991, 0.723124, "GTAAC", 0.723124,
        (5680)  0.85561, 0.0339254, 0.0685387, 0.0419265},
  
Is this a known issue? Shall I try the latest nanopolish version?

Thanks!

**Comment by jts** [comment]
Yes, please try the latest version. You'll have to re-run `nanopolish extract`.

**Comment by sharon558** [comment]
Thanks Jared! I installed the latest nanopolish and reran nanopolish extract on 351 testing reads but got the following message:

Realigned 256 reads in 0.0s
Realigned 351 reads in 0.0s
[post-run summary] total reads: 336 **unparseable**: 0 qc fail: 0 could not calibrate: 2
[post-run summary] total reads: 309 **unparseable**: 0 qc fail: 0 could not calibrate: 0


The extracted fastq file looks like this:
@c126afde-03a4-4d2..._Basecall_1D_template:1D_000:template sequencing_run_test_52473_read_48_ch_113_strand Data/0/dhcp_226_195_sequencing_run_test_52473_read_48_ch_113_strand.fast5
TGTTGGCGCTTCGTTCAGTTG...
+
/+((--3'*)0)9;EA*8330556/'&)...

Any insight?

**Comment by jts** [comment]
Hi,

That summary message looks fine to me - it should be read like this `total reads: 336`, `unparseable: 0`.

Jared

**Comment by sharon558** [comment]
Haha I see!! 

One additional question for you regarding to variant calling pipeline. I used eventalign and then nanopolish variants. Is it the right way to do it? Many thanks in advance!

## 1. Get event aligned sam and bam
nanopolish eventalign -t $threads --reads $reads_fq --bam $reads_bam --genome $ref.fa --progress --sam 
samtools view --threads $threads -bs - | samtools sort - -o $event_bam
## 2. Call variants using original reference ($ref.fa)
nanopolish variants -t $threads --reads $reads_fq -o $reads_vcf -b $reads_bam -e $event_bam -g $ref.fa --ploidy 1

**Comment by jts** [comment]
The eventalign step is unnecessary (the tutorial you are probably following is out of date), you can just do:

```
nanopolish variants -t $threads --reads $reads_fq -o $reads_vcf -b $reads_bam -g $ref.fa --ploidy 1
```

**Comment by sharon558** [comment]
Thank you Jared for the input! So event data is no longer used for nanopolish variant calling? 

To be completely sure, the pipeline I have is:
1) Albacore basecalling to get fastq file
2) bwa align fastq to get bam
3) nanopolish variants: input bam, fastq and the original reference genome; output VCF

- Do you suggest an additional step to polish the reference genome?
- And did I understand right that nanopolish need both bam and fastq as input? I thought bam already contains all the information of fastq?

**Comment by jts** [comment]
Yep, that looks good!

Event data is still used but we don't need to align events to the reference genome first (this is handled internally by `nanopolish variants` now) 

The fastq contains additional information that isn't in the BAM (paths to the fast5 file) so both are needed.

**Comment by sharon558** [comment]
Makes perfect sense! And it's much more intuitive now :) Thank you again!!
