### ISSUE TITLE
nanopolish installation instructions don't match release 

### ISSUE THREAD

**Issue by datakid** [jts/nanopolish#198]
Installation calls for a git clone, with the latest commit being 6 days ago.

Last release was 26 days ago.

Installation documentation and releases don't match. This is not ideal.

**Comment by jts** [comment]
The recommendation is to use the latest code on github hence the instructions say to clone the repository. We also periodically provide versioned releases for the people that prefer that. Maybe I'm missing the issue though (I just got off a long flight)?

**Comment by datakid** [comment]
I'm installing it in a multi user environment where I will update the software periodically - but keep old versions around for reproducibility.

So, versions like:

1
2
3
3.3
3.7
4

work, because people can read progress and see which is the latest etc.

Versions like 

0b384cf

mean nothing numeratively

**Comment by datakid** [comment]
(installing using environment modules)

**Comment by jts** [comment]
Ok. I suggest you grab a release tgz from the 'releases' page. You will have to obtain the submodules manually as they are not packaged by github. To compile you can just start after the git clone step. When I'm back in Toronto I'll make this clear in the readme.

**Comment by jts** [comment]
The README now contains instructions for compiling a particular release.
