### ISSUE TITLE
Nanopolish install problem on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by kbanyas** [jts/nanopolish#200]
Greetings,
I am trying to install the latest nanopolish on Ubunt 14.04 as root.
Our shop is locked down fairly tight so I had to manually download and install some of the dependencies such as fast5.
My latest "make" error is below.
Can you advise as to what I am doing wrong?
Thanks.

### root@J2XP0R1:/opt/nanopolish-master# make
g++ -o src/main/nanopolish.o -c -g -O3 -std=c++11 -fopenmp  -I./htslib -I./fast5/src -I./src -I./src/hmm -I./src/thirdparty -I./src/common -I./src/alignment -I./eigen/ -fPIC src/main/nanopolish.cpp
g++ -o src/nanopolish_call_methylation.o -c -g -O3 -std=c++11 -fopenmp  -I./htslib -I./fast5/src -I./src -I./src/hmm -I./src/thirdparty -I./src/common -I./src/alignment -I./eigen/ -fPIC src/nanopolish_call_methylation.cpp
g++ -o src/nanopolish_call_variants.o -c -g -O3 -std=c++11 -fopenmp  -I./htslib -I./fast5/src -I./src -I./src/hmm -I./src/thirdparty -I./src/common -I./src/alignment -I./eigen/ -fPIC src/nanopolish_call_variants.cpp
src/nanopolish_call_variants.cpp: In function ‘std::string get_single_contig_or_fail()’:
src/nanopolish_call_variants.cpp:193:38: error: ‘faidx_nseq’ was not declared in this scope
     size_t n_contigs = faidx_nseq(fai);
                                      ^
src/nanopolish_call_variants.cpp:199:41: error: ‘faidx_iseq’ was not declared in this scope
     const char* name = faidx_iseq(fai, 0);
                                         ^
src/nanopolish_call_variants.cpp: In function ‘int get_contig_length(const string&)’:
src/nanopolish_call_variants.cpp:206:48: error: ‘faidx_seq_len’ was not declared in this scope
     int len = faidx_seq_len(fai, contig.c_str());
                                                ^
make: *** [src/nanopolish_call_variants.o] Error 1
root@J2XP0R1:/opt/nanopolish-master# cd

**Comment by kyu999** [comment]
Same here. I also failed to install.
This is the error msg.

```
g++ -o src/common/nanopolish_fast5_map.o -c -g -O3 -std=c++11 -fopenmp -I./include -I./htslib -I./fast5/src -I./src -I./src/hmm -I./src/thirdparty -I./src/common -I./src/alignment -I./eigen/ -fPIC src/common/nanopolish_fast5_map.cpp
src/common/nanopolish_fast5_map.cpp:10:18: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
                  ^
compilation terminated.
make: *** [src/common/nanopolish_fast5_map.o] Error 1
```

**Comment by jts** [comment]
Hi @kbanyas, it looks like you missed the `--recursive` flag when cloning the repository so you don't have some of the dependencies. Could you try to re-clone the repo following the instructions in the README?

@kyu999 your linux distribution doesn't have the zlib headers installed. This is a standard package - if you are running ubuntu you should install `zlib1g-dev` through apt.

jared

**Comment by zachcp** [comment]
you may also be interested in installing nanopolish via bioconda: https://bioconda.github.io/recipes/nanopolish/README.html

this will provide precompiled binaries for your platform without the need for root control.

**Comment by kyu999** [comment]
@zachcp Thanks, I tried it previously, but it did not install up-to-date version in linux environment.
 The installed version was v0.4. (In Mac OS, successfully installed v0.7)

**Comment by zachcp** [comment]
i'm using 0.7 on linux and  I believe 0.7.1 may also now be available.

**Comment by smoe** [comment]
I just updated nanopolish for Debian to 0.8.1 which soon will also be available on Ubuntu.

**Comment by jts** [comment]
Cheers, I appreciate you taking the time to package this for Debian.
