### ISSUE TITLE
Error: could not find path to FAST5 && [extract] found 1258 files, extracted 0 reads

### ISSUE THREAD

**Issue by liuqianhn** [jts/nanopolish#201]
Hi,  May I have your help for the following two issues to use nanopolish? Thanks.

1. I am trying to use nanopolish to polish the draft genome, and when I run `python nanopolish_makerange.py ./lambda.contigs.fasta | parallel --results nanopolish.results -P 8 nanopolish variants --consensus polished.{1}.fa -w {1} -r lambda.1_perc0.01400_seed7.fa -b draft.nanopolish.sorted.bam -g ./lambda.contigs.fasta -t 4 --min-candidate-frequency 0.1`, I had an error 
```
Error: could not find path to FAST5 for read 001edc67-d515-42ec-b05b-2a525b5f2914
Please make sure that this path is accessible: start_time=2017-06-21T03:39:09Z
```

May I know why fast5 files needed here?  The first line of `lambda.1_perc0.01400_seed7.fa` is `>98e8d97e-a09d-4d29-a750-b1f26b62d576 runid=708968bcbc99d131131d1081c16f8947cb145e4c read=9 ch=96 start_time=2017-06-20T19:53:13Z`.

2. I thus wanted to re-extract fasta data using `nanopolish extract directory/pass/ > reads.fa`, and I had a message `[extract] found 1258 files, extracted 0 reads`.  Using ` h5dump -n`, the output of fast5 was
```
FILE_CONTENTS {
 group      /
 group      /Analyses
 group      /Analyses/Basecall_1D_000
 group      /Analyses/Basecall_1D_000/BaseCalled_template
 dataset    /Analyses/Basecall_1D_000/BaseCalled_template/Events
 dataset    /Analyses/Basecall_1D_000/BaseCalled_template/Fastq
 group      /Analyses/Basecall_1D_000/Summary
 group      /Analyses/Basecall_1D_000/Summary/basecall_1d_template
 group      /Analyses/Segmentation_000
 group      /Analyses/Segmentation_000/Summary
 group      /Analyses/Segmentation_000/Summary/segmentation
 group      /Raw
 group      /Raw/Reads
 group      /Raw/Reads/Read_9
 dataset    /Raw/Reads/Read_9/Signal
 group      /UniqueGlobalKey
 group      /UniqueGlobalKey/channel_id
 group      /UniqueGlobalKey/context_tags
 group      /UniqueGlobalKey/tracking_id
 }
```
Given a fast5 file above, how to use `nanopolish extract` to find `fa` for nanopolish.

Thanks.

**Comment by jts** [comment]
Hi,

It appears that you basecalled the reads with MinKNOW. You need to basecall them with albacore to run nanopolish.

Jared
