### ISSUE TITLE
Switch xrange to range for Python 3 compatibility?

### ISSUE THREAD

**Issue by devindrown** [jts/nanopolish#203]
Perhaps this breaks things if you switch xrange to range in this script? Only way I got it work with Python 3

https://github.com/jts/nanopolish/blob/0b384cfc007b67fc97e103af13aa78c46ba3e894/scripts/nanopolish_makerange.py#L21

**Comment by jts** [comment]
Thanks for the suggestion, I have changed to `range` in commit fca7cba
