### ISSUE TITLE
nanopolish_makerange Assertion failure

### ISSUE THREAD

**Issue by shelbywilliams** [jts/nanopolish#204]
Hi there,

When running nanopolish_makerange.py I get the following error:

> [fai_load] build FASTA index.
nanopolish: src/nanopolish_squiggle_read.cpp:323: void SquiggleRead::_load_R9(uint32_t, const string&, const std::vector<EventRangeForBase>&, const std::vector<double>&, uint32_t): Assertion `fields.size() == 4' failed.

No fasta file is generated, and the above error repeats itself several times.

Here is what I am using to run nanopolish_makerange.py:

>python /scratch2/software/nanopolish/nanopolish-git-jun6-2017/nanopolish/scripts/nanopolish_makerange.py RCL_Uni_clean.fasta | parallel --results nanopolish.RCL.results -P 20 \
    /scratch2/software/nanopolish/nanopolish-git-jun6-2017/nanopolish/nanopolish variants --consensus polished.{1}.fa -w {1} -r MinION_RCL_reads_nanopolish.fa -b alignments.RCL.sorted.bam -g RCL_Uni_clean.fasta --threads 8 --min-candidate-frequency 0.1

**Comment by jts** [comment]
Hi,

What version of nanopolish are you running? This error usually occurs when the basecalled reads are from MinKNOW, not albacore. What basecaller did you use?

Jared

**Comment by shelbywilliams** [comment]
I was running a version of nanopolish acquired on June 6th. I've recently updated nanopolish and I am trying this again. The reads were basecalled using albacore.

**Comment by jts** [comment]
The issue is probably caused by the old version that you tried.
