### ISSUE TITLE
eventalign and HMM vs. RNN basecalling

### ISSUE THREAD

**Issue by ukaraoz** [jts/nanopolish#207]
Hi,
Thanks for the great piece of reusable software.
I have two questions on the eventalign pipeline on R9 1D data when the basecalling was with Albacore (which does NN basecalling, in this case using template_r9.4_450bps_5mer model).

1. Taking a peak at the source code, I assume that the events and their associated stats from Albacore would not give accurate parameters using eventalign in this case. Is that right?
If so, would the solution to this to do re-basecalling R9 data with an HMM based basecaller-despite the lower accuracy.

2.How do I get R9.4 pore model for 5 or 6mers? These do exist for reads using R7 but probably because the basecalling was not through HMM, they aren't part of the .fast5 files anymore. The model file for the Albacore basecaller has the parameters for the trained NN corresponding to R9.4

**Comment by jts** [comment]
Hi @ukaraoz,

1. The RNN basecaller does not output scaling parameters (shift, scale, var) like the HMM basecaller did. To workaround this issue nanopolish uses the labels that the RNN basecaller attaches to each event to infer these parameters. The relevant code is here:

https://github.com/jts/nanopolish/blob/master/src/nanopolish_squiggle_read.cpp#L391

2. The pore models are provided by ONT in this repository:

https://github.com/nanoporetech/kmer_models

Jared
