### ISSUE TITLE
Add --version flag

### ISSUE THREAD

**Issue by tseemann** [jts/nanopolish#211]
I can't seem to figure out how to find the version. 
Unix standard would be:

```
% nanopolish --version
nanopolish 0.6.0
```

or `nanopolish version` if you must.  Maybe `nanopolish cite` would be good too.

**Comment by jts** [comment]
`nanopolish --version` is already supported :)

https://github.com/jts/nanopolish/blob/master/src/main/nanopolish.cpp#L29

**Comment by tseemann** [comment]
Whoops - I assumed i was on latest version but Brew onlyhas 0.6.0  -- sorry!

```
% nanopolish --version
usage: nanopolish [command] [options]
  valid commands:
    --help
    call-methylation
    consensus
    eventalign
    extract
    getmodel
    help
    methyltrain
    phase-reads
    scorereads
    train-poremodel-from-basecalls
    variants
  for help on given command, type nanopolish command --help
```

**Comment by tseemann** [comment]
I've upgraded brew nanopolish to 0.7.2
