### ISSUE TITLE
running nanoplish

### ISSUE THREAD

**Issue by efratca** [jts/nanopolish#212]
Hi,

I am trying to run nanopolish for polishing the contig created by Canu. I ran the following command:
nanopolish  consensus  --reads reads.fasta  --bam sorted_reads.bam  --genome  contig.contigs.fasta  -t 4 -w tig00000001:1-4674646 
But I got the following error: "consensus: a --models file must be provided"
What is the models file?
Another thing, I showed in the readme the following example:
 python nanopolish_makerange.py draft.fa | parallel --results nanopolish.results -P 8 \
    nanopolish variants --consensus polished.{1}.fa -w {1} -r reads.fa -b reads.sorted.bam -g draft.fa -t 4 --min-candidate-frequency 0.1
Is it necessary to run it like this with the parallel command?

Thanks

**Comment by jts** [comment]
`nanopolish consensus` is deprecated, you should follow the instructions here:

https://github.com/jts/nanopolish#computing-a-new-consensus-sequence-for-a-draft-assembly

**Comment by efratca** [comment]
Thanks for the reply.
As it was suggested I ran the command: 
python nanopolish_makerange.py draft.fa | parallel --results nanopolish.results -P 8 \
    nanopolish variants --consensus polished.{1}.fa -w {1} -r reads.fa -b reads.sorted.bam -g draft.fa -t 4 --min-candidate-frequency 0.1
I got the following errors:
 Error: could not find path to FAST5 for read ......
Please make sure that this path is accessible: ......
Is it necessary to run before:  "nanopolish extract"? or is it possible like I did to take the fastq reads after demultiplexing and convert them to fasta
Thanks

**Comment by jts** [comment]
It is required to run nanopolish extract.

**Comment by efratca** [comment]
Thanks
I ran nanopolish extract and then I ran bwa:
bwa mem -x ont2d -t 8 draft.fa reads.fa | samtools sort -o reads.sorted.bam -T reads.tmp -
samtools index reads.sorted.bam
But, I got an error: unknown read type 'ont2d' 
Is is because I have 1D read? If then how I should run bwa for nanopore reads (1D)?
I ran bwa mem without -x ont2d and then I ran: 
python nanopolish_makerange.py draft.fa | parallel --results nanopolish.results -P 8 \
    nanopolish variants --consensus polished.{1}.fa -w {1} -r reads.fa -b reads.sorted.bam -g draft.fa -t 4 --min-candidate-frequency 0.1
But, I got warnings like: Warning: 2934 variants in span, region not called [19798 21072]
Number of variants in span (70) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes! and I didn't get the output polished.*.fa files

Thanks

**Comment by nickloman** [comment]
You need a later version of BWA which supports -x ont2d. Would not recommend using without this flag.

**Comment by efratca** [comment]
Thanks a lot for the answers, I succeeded to run it.

**Comment by jts** [comment]
Great
