### ISSUE TITLE
Option to use system HTSLIB ?

### ISSUE THREAD

**Issue by tseemann** [jts/nanopolish#213]
Bacl in issue #64 you modified your makefile to allow us to override and use system EIGEN libraries rather than `wget` etc. This is used in the brew formula.

We also do this for HDF5.

However, HTSLIB is still embedded.   I tried a few things but I couldn't get it to use system ones. Is it risky to use different versions even if we could?

**Comment by jts** [comment]
It is probably safe to use the system-wide htslib, as long as it is reasonably recent. The Makefile will need a bit of modification though to pick up the `noinstall` option and set the link/include paths:

https://github.com/jts/nanopolish/blob/master/Makefile#L48

I'll look into it.

**Comment by tseemann** [comment]
@jts it's not critical. i was going to make a pull request until i realised how tricky it was going to be!

I did updated the brew recipe from 0.6 to 0.7 series, and use our local hdf5 and eigen:

```
    # Ensure we use brewed 'hdf5' and 'eigen3'
    # Awaiting patch to allow use of brewed 'htslib' https://github.com/jts/nanopolish/issues/213
    system "make", "HDF5=", "EIGEN=", "EIGEN_INCLUDE=-I#{Formula["eigen"].opt_include}/eigen3"
```

**Comment by jts** [comment]
This was implemented by @0xaf1f
