### ISSUE TITLE
nanopolish variant call crashed 

### ISSUE THREAD

**Issue by sharon558** [jts/nanopolish#214]
Hi Nanopolish developers, 

I ran nanopolish variant call using a cluster node with 16 threads and 256GB memory. The bam file is ~10GB and the reference genome has three contigs ( each about ~4MB).

First I ran with the "--window contig1" parameter, and nanopolish was able to generate the vcf file, but only for the first ~10,000 bases on contig1.

Then I specify the full contig1 size by "--window contig1:1-4000000", but got the following error:
nanopolish.sh: line 158: **14978 Killed**   
               
The full variant call command I used is as below:
nanopolish variants --window contig1:1-4000000 -t 16 --reads $reads_fq -o $vcf -b $bam -g $ref.fa --ploidy 1 --progress -v

Is this a memory usage issue? Does the variant caller use a moving window type approach to call the variant to limit the memory usage? Is there a way to estimate the memory usage for a 10GB bam file with a 4MB reference contig?

Thanks in advance!
Sharon

**Comment by jts** [comment]
Hi Sharon,

This is likely a memory issue. When trying to run on the whole genome it will load all fast5s into memory, which is too much data. You'll have to call variants in windows, I suggest 50-100kb at a time.

Jared

**Comment by sharon558** [comment]
Thanks Jared! Makes sense. I'll close the ticket.
