### ISSUE TITLE
Nanopolish variant calling crashed: Assertion `str[i] != 'M'' failed

### ISSUE THREAD

**Issue by sharon558** [jts/nanopolish#215]
Hi Jared,
I ran nanopolish variant calling on a genome with multiple contigs. Nanopolish was able to call variants on most of the contigs, but I saw the following error on one contig and the resulting vcf file only had header lines.

Error:
./src/common/nanopolish_alphabet.h:145: virtual std::string Alphabet::reverse_complement(const string&) const: Assertion `str[i] != 'M'' failed.

Command I used:
nanopolish variants --window contig1:1-100000 --reads $fastq -o  output.vcf -b $bam -g $ref --ploidy 1 -v

I'm guessing there might be some invalid characters in my fast5/fasta files? Is there a way to print out more messages for debugging? I did try another variant caller (freebayes) and it was able to generate results on the same contig.. Any suggestions?

Thanks,
Sharon

**Comment by jts** [comment]
Hi Sharon,

It looks like your reference genome contains IUPAC ambiguity codes. Right now nanopolish can't handle these so you'll need to remove them from the reference.

Jared

**Comment by sharon558** [comment]
Got it. Thanks Jared!
