### ISSUE TITLE
MinKNOW configuration for Nanopolish

### ISSUE THREAD

**Issue by lintnerBTL** [jts/nanopolish#217]
Hi Guys,

We ran several samples with theMinION a couple months ago, and I think we made a number of mistakes in terms of best practices for the basecalling. We are gearing up again, and I'd like to make sure I'm going about the data handling the correct way. Here's what I plan to do:
1. Download latest MinKNOW
2. Run MinION without local basecalling
3. Call bases with Albacore once the run is finished.
4. Run Nanopolish

Is this the right approach?

Are there any things that need to be configured on MinKNOW such that the fast5 files are usable by Nanopolish?

Thanks,
Robert

**Comment by jts** [comment]
Yep, that approach looks good. As long as you basecall with Albacore the reads should work with nanopolish later.

**Comment by lintnerBTL** [comment]
Excellent, thanks Jared, best!

Robert
