### ISSUE TITLE
Running Nanopolish from fastq file

### ISSUE THREAD

**Issue by situssog** [jts/nanopolish#219]
Hello,

What I got from the sequencing platform were fastq files of the reads. 
It seems nanopolish only accepts compressed .gz fasta files. Am I right?

To produce fasta files I did: 

```
seqtk seq -a reads.fastq | bgzip -c > reads.fasta
```

and then I used those reads to run Nanopolish with this command:

```
python /proj/b2014286/private/tools/nanopolish_test/nanopolish/scripts/nanopolish_makerange.py reads.fasta | parallel --results nanopolish.results -P 8 nanopolish variants --consensus polished.{1}.fa -w {1} -r reads -b aligment.bam -g draft_genome.fasta -t 1 --min-candidate-frequency 0.1
```
However, it doesn't seem to work. Although it runs, it produces fasta files with exactly the same sequence as the draft genome and it does no find any SNP.

I'm wondering if the problem is related with how I transform the reads from fastq to fasta file.

Thanks a lot for your help,

/Sergio

**Comment by jts** [comment]
Hi Sergio,

Please see the instructions here:

https://github.com/jts/nanopolish#analysis-workflow-examples

You need to run `nanopolish index` on your fastq file (using the command in the README). Also, the input into `nanopolish_makerange.py` should be the genome file, not the reads file.

Jared

**Comment by situssog** [comment]
Hello Jared,

Thanks a lot for your help.

Yes my fold, I got confused when I read the instructions the first time.

Sorry for the basic questions. However, I'm still having problems. the instructions say:

```
# Only run this if you used Albacore 2.0 or later
nanopolish index -d /path/to/raw_fast5s/ albacore_output.fastq
```

and then 

```
# Only run this if you used Albacore 1.2 or later
nanopolish extract --type template directory/pass/ > reads.fa
```

My data were produced with albacore-1.2.6, in given case I understand I should use nanopolish extract, but it seems I also need signal files that I don't have (I only have the fastq files). 

If I use nanopolish index, it produces the fa.gz as expected, but running nanopolish variants doesn't seem to produce any output.

I'm running:

```
/proj/b2014286/private/tools/nanopolish_test/nanopolish/nanopolish index reads.fastq

draft_genome=$1
reads=$2
bam_file=$3
output_vcf=$4

python /proj/b2014286/private/tools/nanopolish_test/nanopolish/scripts/nanopolish_makerange.py $draft_genome | parallel --results $output_vcf.nanopolish.results -P 8 /proj/b2014286/private/tools/nanopolish_test/nanopolish/nanopolish variants --consensus $output_vcf.polished.{1}.fa -w {1} -r $reads -b $bam_file -g $draft_genome -t 8 -o $output_vcf.vcf --min-candidate-frequency 0.1
```

It produces fasta files with the fragments of genome, but the vcf files is completely empty. The job is still running, and I wonder if there is point on keep waiting. should the output be produced as it progresses? or it is only shown in the VCF file at the end of the run.

Thanks a lot for your help,

/S

**Comment by jts** [comment]
Hi,

The signal files are always required to run nanopolish. You'll need to get these if you want to proceed.

Jared
