### ISSUE TITLE
Barcoding compatibility?

### ISSUE THREAD

**Issue by tantrev** [jts/nanopolish#22]
Just curious if Nanopolish is currently well-suited to the barcodes from ONT in their barcoding kit?

**Comment by jts** [comment]
I haven't tried barcoded reads. How does metrichor handle barcodes? Are they automatically removed from the basecalled read?

**Comment by tantrev** [comment]
Haven't done a barcoded run yet either but I'm mentoring a high schooler that would like to use it and needs high-accuracy reads like those that Nanopolish offers. :)

According to this [page] (https://wiki.nanoporetech.com/display/BP/Barcoding+workflow), they remove the barcode from the returned Fastq but it's not entirely clear what they do with the .fast5 data.  I made a comment inquiry on the Barcoding workflow so they'll hopefully clarify the details soon, but my suspicion is that the .fast5 data is left unaltered.  If it helps at all, this [file] (https://github.com/nanoporetech/barcoding/blob/master/bin/split_barcodes.pl) seems to have the barcode sequences.
