### ISSUE TITLE
Reference fasta file with Deletion "-"

### ISSUE THREAD

**Issue by icymiktreize** [jts/nanopolish#220]
Hi,
I am trying to run naopolish and got this error:

src/common/nanopolish_alphabet.h:173: virtual std::string Alphabet::disambiguate(const string&) const: Assertion `IUPAC::isValid(out[i])' failed.

All bases in my reference file are in uppercase. There is one "-" indicating a Deletion, which I think caused the above problem. Do you know if there are anyways to fix this issue? 

Thanks a lot.

**Comment by jts** [comment]
Hi,

You'll have to remove the '-' character from the reference before mapping
the reads to it and running nanopolish.

Jared
