### ISSUE TITLE
The basecalling model could not be detected from the fast5 file

### ISSUE THREAD

**Issue by dikkeaap** [jts/nanopolish#221]
Hi Jared,

I'm running nanopolish on yet another genome and encountered the following error:

> Error: The basecalling model could not be detected from the fast5 file. Please re-run basecalling using albacore.

I have data of 12 flowcells that were all basecalled with the same version of albacore as the other genomes I'm working on (version 1.2.1). With this dataset however it appears that (some of) the reads were not basecalled succesfully, but I see no indication of that in the albacore logs. I'm guessing that there's only a few files missing the required data, since nanopolish runs fine on the other genomes that were basecalled with the same version. 

Nanopolish currently exits when a fast5 file doesn't contain the required data; is it possible to either (1) report the filename that contains no data before exiting; or (2) include a parameter that allows nanopolish to ignore fast5 files without the required data and continue? Alternatively, is there a straightforward way for me to check the (hundreds of thousands of) fast5 files to find the offending ones? What are the keys in the fast5 file that you require?

**Comment by jts** [comment]
Hi,

Did you use `nanopolish extract` to export the reads to the fast5 files? 

Jared

**Comment by dikkeaap** [comment]
Yes, I used nanopore extract. I did filter the fasta (and the associated
bam) file afterwards to remove some duplicates that were introduced by
apparently basecalling a small subset of the data twice, but I made sure to
leave the sequence headers intact. I do see now that the fasta file
generated by nanopolish extract has each sequence on a single line, whereas
my filter script limits the line width of the non-header lines and spans
the sequence over multiple lines (as allowed by the fasta specification). I
will reformat the filtered fasta file and try again.

**Comment by dikkeaap** [comment]
I do not encounter this issue when the fasta file contains the sequences on one line each (i.e., no linebreaks in the sequence). This is no longer an issue (but it would be nice if nanopolish would support multi-line fasta records, or produce a more meaningful error message :))

**Comment by jts** [comment]
We use Heng Li's `kseq` library to read fasta/fastq, and it supports multi-line fasta - I don't think it is the root of the problem.

`nanopolish extract` will only export reads to the fasta file that have valid basecalling information. I'll improve the output message to help you track this down.

**Comment by jts** [comment]
Ok, in the latest commit the error message will tell you which fast5 file caused the problem.

Jared

**Comment by dikkeaap** [comment]
Hi Jared,

with the latest commit I ran the following (as an example on one of the chunks):

> chunk="tig00000002:0-50200"
> /home/eda/tools/nanopolish-20170914/nanopolish variants --consensus polished.${chunk}.fasta -w ${chunk} -r dedup.fasta -b dedup.sorted.bam -g reference.fasta -t 4 --min-candidate-frequency 0.1

This gives the following error:

> Error: The basecalling model could not be detected from the fast5 file: basecalled/fast5/FAF17398_pass_10/0/PC_792_20170309_FNFAF17398_MN16622_sequencing_run_RUN_FAF17398_090317_62206_ch177_read5213_strand.fast5
> Error: Please re-run basecalling using albacore.

I can confirm that this file was basecalled with ONT Albacore Sequencing Pipeline Software (version 1.2.1) and I only see these messages in the albacore log relating to this file:

> 2017-08-18 01:17:09,356 Submitting file "PC_792_20170309_FNFAF17398_MN16622_sequencing_run_RUN_FAF17398_090317_62206_ch177_read5213_strand.fast5".
> 2017-08-18 01:17:12,473 Finished processing file "PC_792_20170309_FNFAF17398_MN16622_sequencing_run_RUN_FAF17398_090317_62206_ch177_read5213_strand.fast5".

These files have been basecalled on the same day with the same version of albacore as another dataset that works fine with nanopolish...!

I get this error on most, but *not* all of the chunks of this particular genome; but the chunks that do complete without error are all small (up to 4 kb) so they potentially contain no or very few mapped reads. Running nanopolish on various chunks did not consistently point to one particular flowcell, but instead I get this same error on data from all runs, so it's not the case that a single run had problems with basecalling.

Any help on how to continue would be appreciated!

**Comment by jts** [comment]
This problem was identified and fixed offline
