### ISSUE TITLE
Running nanopolish variants against whole genome or region file using -w?

### ISSUE THREAD

**Issue by bc2zb** [jts/nanopolish#224]
I have a bed file of target regions I'm trying to get genotypes for. I've converted the bed file into the format specified by the -w option. Can I pass the region file into the -w option directly or should I try to convert my bed file into a vcf and use the -c option instead? Is there a way to run nanopolish against the entire genome as well?

**Comment by jts** [comment]
Do you know the sites and alleles that you are trying to genotype?

**Comment by bc2zb** [comment]
I have a bed file of the regions I want to genotype, and I converted the bed file into the format below as specified by the -w option. I do not know the genotypes, but could obtain them as all sites are known SNPs.

```
     chr1:4367265-4367394
   chr1:14155373-14155431
 chr1:105717597-105717664
 chr1:160786620-160786721
 chr1:238439222-238439345
 chr1:239881875-239881985

```

**Comment by jts** [comment]
I suggest you get the sites to genotype and put them in a file called `sites.vcf`, then run it like this:

```
cat regions.bed | xargs -i nanopolish variants --ploidy 2 -r reads.fastq -b alignments.bam -g genome.fasta --genotype sites.vcf -w {} -o genotypes.{}.vcf
```

(I just added help text for the `--genotype` option in f36ca66)

**Comment by bc2zb** [comment]
I'll give this a shot. Thanks for the help.

**Comment by bc2zb** [comment]
@jts Your suggestion works, thanks! However, I'm running into a slightly different issue. I 

```
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140087282988960:
  #000: H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 990 in H5F_open(): unable to open file: time = Fri Sep 15 09:27:50 2017
, name = 'workspace/MacBook_Pro_3_local_20170623_FAH02603_MN20915_sequencing_run_062217_PC_MIN_17664_read_93802_ch_205_strand.fast5', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 992 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: H5FDsec2.c line 343 in H5FD_sec2_open(): unable to open file: name = 'workspace/MacBook_Pro_3_local_20170623_FAH02603_MN20915_sequencing_run_062217_PC_MIN_17664_read_93802_ch_205_strand.fast5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
terminate called after throwing an instance of 'hdf5_tools::Exception'
  what():  : workspace/MacBook_Pro_3_local_20170623_FAH02603_MN20915_sequencing_run_062217_PC_MIN_17664_read_93802_ch_205_strand.fast5: error in H5Fopen
Aborted (core dumped)

```

I do have permissions, so I don't think that is the issue

```
-rwxrwxr-x 1 xxxxx xxxxx  75875 Jun 23 15:39 workspace/MacBook_Pro_3_local_20170623_FAH02603_MN20915_sequencing_run_062217_PC_MIN_17664_read_93802_ch_205_strand.fast5
```
These files have been moved from the machine they were originally run on, so I did index them prior to running 

```
~/nanopolish/0.8.1/nanopolish index -v -d ~/minion/reads/20170623_1939_062217_PC_MIN/ ~/fastq/20170623_A_pass-only_output.fastq

[readdb] num reads: 1668963, num reads with path: 1668963

```
I saw the other issues [here](https://github.com/jts/nanopolish/issues/9) and [here](https://github.com/jts/nanopolish/issues/86) but I don't believe that is the cause.

**Comment by jts** [comment]
Hi, 

Can you clarify if the reads were moved before or after you ran `nanopolish index`?

Jared

**Comment by bc2zb** [comment]
The reads were moved, then indexed.

-Brian

**Comment by jts** [comment]
and this path is accessible from the directory that you are running nanopolish?

```
workspace/MacBook_Pro_3_local_20170623_FAH02603_MN20915_sequencing_run_062217_PC_MIN_17664_read_93802_ch_205_strand.fast5
```

**Comment by bc2zb** [comment]
Yes.

**Comment by jts** [comment]
Can you send me the .readdb file by email? jared.simpson@oicr.on.ca

**Comment by bc2zb** [comment]
Sorry, where would I find the .readdb file.? I've checked around a bit with ls -a, but haven't found it in the nanopolish directory, the fast5 directories, or the directory from where I ran nanopolish.

**Comment by jts** [comment]
It should have been produced by `nanopolish index`, it will either be in the directory you ran it in, or in the directory where the input fastq lives.

**Comment by jts** [comment]
Please reopen if this is still an issue.
