### ISSUE TITLE
Feature request: multiple directories as arguments

### ISSUE THREAD

**Issue by conchoecia** [jts/nanopolish#225]
What do you think about allowing `nanopolish extract` and `nanopolish index` accept multiple directories as arguments? Personally I like to keep my basecalled reads in separate directories based on flowcell, so this would be a nice feature to avoid running in a for loop and catting the fa results.

**Comment by jts** [comment]
Sure, I can add this. In the meantime you can do a workaround by making a directory containing symlinks to the different flowcells and passing the top level directory as `-d`.

**Comment by conchoecia** [comment]
Good idea, thank you for the suggestion.

**Comment by jts** [comment]
Implemented in 8e400a7

**Comment by conchoecia** [comment]
🌮 🍻
