### ISSUE TITLE
nanopolish variants not working with marginalign output

### ISSUE THREAD

**Issue by emdyess** [jts/nanopolish#229]
Hi,

I have used nanopolish extract to obtain fastq files and fasta files.  I used the fasta files for aligning to a reference with bwa mem (-x ont2d) or the fastq files with marginAlign/bwa.  Nanopolish variants has no problems with the bwa mem output (SAM -> BAM -> sorted BAM -> indexed -> nanopolish variants), but it gives me a VCF file with only the header when I run on the marginAlign-realigned bwa mapping (SAM -> BAM -> sorted BAM -> indexed -> nanopolish variants).  Do you know if there is a way to get nanopolish to work with marginAlign output?

Any help would be great.  Thanks!

**Comment by jts** [comment]
Hi @mitenjain, do you have any idea why this wouldn't work? Is there anything unusual about marginAlign BAM files?

**Comment by mitenjain** [comment]
Hi @jts, 

That sounds odd. The BAMs should contain the single most unique contiguous alignment per read. I have used marginAlign output with nanopolish several times. 

@emdyess,
For marginAlign, did you use the fastq files for mapping? I need to push a patch that will allow this to work with fasta inputs, but for now marginAlign requires a fastq read file as input. 

Could you send me a test case (miten@soe.ucsc.edu) so I can reproduce and fix the error from our end?

Sorry for the hassle.
-Miten
