### ISSUE TITLE
Nanopolish with Albacore 2.0: reads.fa?

### ISSUE THREAD

**Issue by miwolff** [jts/nanopolish#230]
Hi,

I'm, very new to this... I'm trying to use the current Nanopolish version after Albacore 2.0.2 and I think I am missing something: When following the analysis workflow example, when/how is the reads.fa file supposed to be created?
I can run nanopolish index with 
nanopolish index -d input/ albacore_output/workspace/pass/*.fastq
but I don't get any .fa files...

I'm able to run the current Nanopolish version after Albacore 1.2.6 (here with '-o fast5') following the analysis workflow example with a minor change: nanopolish extract --type template albacore_output/workspace/ -o reads.fa, that is with '-o' instead of '>' as in the description. That works fine.

**Comment by jts** [comment]
Hi,

You should combine all of the output fastq files from albacore into one file, let's say it is called `albacore_reads.fastq`. Then you run nanopolish index and all subsequent steps with `albacore_reads.fastq` as input. In the documentation `reads.fa` is only an example of the filename.

Jared

**Comment by miwolff** [comment]
Thanks a lot for the quick answer. Your solution works.

I'm getting strongly different results for methylation calling compared to with Albacore 1.2.6 though using exactly the same input data. The number of found cpg sites in methylation.py is only 62% of that with Albacore 1.2.6. Is this expected? Sorry if I'm getting of topic of the original question.

**Comment by jts** [comment]
I have not tested methylation detection with 2.0 but I would not expect it to have a large effect. Can you describe your test in more detail? What genome are you using, how much coverage, etc.

**Comment by miwolff** [comment]
Ok, let me double check this and get a bit more familiar with what is happening first. I'll then get back to you.

**Comment by jts** [comment]
Sure, please do. I'm very interested to hear what you find out though.

**Comment by miwolff** [comment]
Hi again,
today I noticed that after basecalling with Albacore 2.0.2 nanopolish call-methylation says that it can not calibrate 1/3 of the reads, which are most likely the ones I'm missing.
```
[post-run summary] total reads: 366 unparseable: 0 qc fail: 0 could not calibrate: 119
```
What does that mean?
Here the result after basecalling the same raw data with Albacore 1.2.6
```
[post-run summary] total reads: 361 unparseable: 0 qc fail: 0 could not calibrate: 0
```
I'm using the same small fraction (100MB) of a 100GB raw dataset for testing the workflow pipeline. Only using reads with mapping score >= 30 didn't solve the problem. There are some differences in the resulting reads after basecalling, but the overall read statistics are similar for Albacore 1.2.6 and 2.0.2.

**Comment by jts** [comment]
Thanks for the update - what sequencing kit and flowcell did you use? Could you provide me with some reads (maybe 100-500) that I could use to look into this?

**Comment by jts** [comment]
Hi @miwolff,

Another user reported a different error when calling methylation with Albacore 2.0 reads. This is now fixed and the latest code is on github. It might help you a bit but the calibration issue is unresolved. If you can send me test reads it would be appreciated.

Jared

**Comment by miwolff** [comment]
Hi Jared,
that would be great, we can do that. I can send my two testing pipelines and the 100MB test raw files to you. How do you want to do it? Dropbox?

I've just updated Nanopolish again, as you said, that didn't solve the calibration problem. But it did fix an error I got when not supplying the methylation calling with the '-t 16' option for the Albacore 2.0 reads.

Best,
Michael

**Comment by jts** [comment]
dropbox would be great, thanks!

**Comment by miwolff** [comment]
I've send an invite to jared.simpson@oicr.on.ca

**Comment by jts** [comment]
Hi @miwolff,

I have prepared a new release of nanopolish which improves the event-to-read alignment step - it should reduce the number of reads you lose when running on albacore 2.0.2 data. Please try it out and let me know how it looks.

Jared

**Comment by miwolff** [comment]
Hey Jared,

thanks for the update, it seems to work much better now on the test dataset. 
```
[post-run summary] total reads: 465 unparseable: 0 qc fail: 5 could not calibrate: 0 no alignment: 33
```
The number of called methylation sites went up from 58328 to 86600 for the albacore 2.0.2 case. The number for albacore 1.2.6 remained unchanged at 93430.

I'll give it a try on the full dataset over the weekend and let you know what I find.

**Comment by jts** [comment]
Great, thanks for the report back.

**Comment by timacwalker** [comment]
Hi, I'm new to this too and was wondering if using the fastq files generated from porechop instead of albacore for the indexing? I'm assembling genomes sequenced using the rapid barcoding kit in canu. Thanks, Tim.

**Comment by jts** [comment]
Hi,

Yes it should be possible to use the reads generated by porechop but I have not tried this myself. I think @rrwick has though? You'll want to run porechop before `nanopolish index`.

Jared

PS: it is probably best to open a new issue for this kind of question as it isn't related to the issue @miwolff reported.

**Comment by rrwick** [comment]
While I too suspect post-Porechop reads will work in Nanopolish, I actually haven't tried it myself. Since I align the reads _locally_ (with BWA MEM or minimap2), I don't think that adapters are an issue - they'll just clip off in the alignment, right?

**Comment by jts** [comment]
Yep, the alignment should clip them.

Jared
