### ISSUE TITLE
nanopolish_makerange.py

### ISSUE THREAD

**Issue by PhDstuff** [jts/nanopolish#234]
I have used 1D minion data, called on albacore v2
Followed the github read.me example, editting for file names
nanopolish index -d /path/to/raw_fast5s/ albacore_output.fastq
bwa index draft.fa
bwa mem -x ont2d -t 8 draft.fa reads.fa > reads.sam
samtools view -bS reads.sam > reads.bam
samtools sort reads.bam reads_sorted.bam
samtools index reads_sorted.bam

Then following this I try the nanopolish steps:

~/nanopolish$ python scripts/nanopolish_makerange.py draft.fa | parallel --results nanopolish.results -P 8  ./nanopolish variants --consensus polished.{1}.fa -w {1} -r albacore_outpout.fa -b reads_sorted.bam -g draft.fa -t 4 --min-candidate-frequency 0.1

and get the following error:

parallel: invalid option -- '-'
parallel [OPTIONS] command -- arguments
	for each argument, run command with argument, in parallel
parallel [OPTIONS] -- commands
	run specified commands in parallel
Traceback (most recent call last):
  File "scripts/nanopolish_makerange.py", line 32, in <module>
    print("%s:%d-%d" % (name, start, end + OVERLAP_LENGTH))
IOError: [Errno 32] Broken pipe

I editted the above to contain 'parallel gnu' incase it was a problem with the naming and another package and receive this:

/nanopolish$ python scripts/nanopolish_makerange.py draft.fa | parallel gnu --results nanopolish.results -P 8  ./nanopolish variants --consensus polished.{1}.fa -w {1} -r albacore_outpout.fa -b reads_sorted.bam -g draft.fa -t 4 --min-candidate-frequency 0.1
Traceback (most recent call last):
  File "./scripts/nanopolish_makerange.py", line 32, in <module>
    print("%s:%d-%d" % (name, start, end + OVERLAP_LENGTH))
IOError: [Errno 32] Broken pipe

Why is there an issue with this step? 
The head of my sam file, converted to bam is such:
~/nanopolish$ head reads.sam
@SQ	SN:tig00000003	LN:468395
@SQ	SN:tig00000004	LN:1050679
@SQ	SN:tig00000006	LN:135090
@SQ	SN:tig00000007	LN:339130
@SQ	SN:tig00000010	LN:832368
@SQ	SN:tig00000011	LN:66627
@SQ	SN:tig00000012	LN:150659
@SQ	SN:tig00000013	LN:808737
@SQ	SN:tig00000016	LN:654433
@SQ	SN:tig00000021	LN:589863

Thanks in advance

**Comment by jts** [comment]
What version of parallel are you using?

**Comment by PhDstuff** [comment]
I appear to have fixed it by reinstalling and moving the parallel command,
sudo apt-get install parallel
sudo mv /usr/bin/parallel /usr/bin/gnu_parallel
sudo apt-get install moreutils

And then using gnu_parallel in my scripts
Following this, I now receive this error message:
nanopolish: src/nanopolish_read_db.cpp:179: std::__cxx11::string ReadDB::get_read_sequence(const string&) const: Assertion `m_fai != NULL' failed.
##fileformat=VCFv4.2
##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">
##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">
##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">
##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">
##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
[fai_load] build FASTA index.
[fai_build] fail to open the FASTA file albacore_output.fa.fa.gz
[fai_load] fail to open FASTA index.
nanopolish: src/nanopolish_read_db.cpp:179: std::__cxx11::string ReadDB::get_read_sequence(const string&) const: Assertion `m_fai != NULL' failed.

So it is unable to open a file that doesn't exist 'albacore_output.fa.fa.gz'. considering I indexed a fastq file as suggested in the first step?

**Comment by jts** [comment]
the `-r` option should be `-r albacore_output.fastq`, not `-r albacore_output.fa`.

**Comment by PhDstuff** [comment]
That seems to have fixed, I will report if the process is completed successfully
