### ISSUE TITLE
Running Nanopolish from fastq.gz file

### ISSUE THREAD

**Issue by tungufoss** [jts/nanopolish#236]
Hi, I'm using Albacore version 2.0.2 and ran the command
```
nanopolish index -d /path/to/raw_fast5s/ albacore_output.fastq.gz
```
which seems to work fine given the number of reads with path. However, then nanopolish call-methylation fails. Do they fastq files need to be unzipped for the indexing to work? Or must they be bgzipped instead of gzipped?

**Comment by jts** [comment]
Hi,

What is the error message from call-methylation?

**Comment by tungufoss** [comment]
It's the same error for bgzip and gzip compression for fastq files. 

![image](https://user-images.githubusercontent.com/3079749/30977382-e34b5884-a466-11e7-976a-263f81f67b66.png)

**Comment by jts** [comment]
Hi,

I think this is a bug that I fixed a week ago - can you update to the very latest code and try again?

**Comment by tungufoss** [comment]
I updated to the latest version 0.8.1 (from 0.8.0). Works like a charm on gzip fastq files. 👍
