### ISSUE TITLE
Direct RNA sequencing 

### ISSUE THREAD

**Issue by awjga** [jts/nanopolish#237]
Hi,
Does nanopolish works with direct RNA sequencing  data?
I had tried to use get models and eventalign.
But they are not working.
I am on the latest version of nanopolish 0.8.2.

Thanks!

**Comment by jts** [comment]
Not yet, but I'm working on it right now.

**Comment by jts** [comment]
the latest version now has preliminary support for direct RNA data

**Comment by jts** [comment]
you'll need to convert Us in your reads to Ts however

**Comment by awjga** [comment]
Thank you so much! 
I will give it a try, and update you if there are any errors.
