### ISSUE TITLE
Error in nanopolish call-methylation

### ISSUE THREAD

**Issue by ckhithesh** [jts/nanopolish#238]
Hi, I'm running Nanopolish call-methylation. But I'm getting error mentioned below.  
Unknown model type string: r9.5_450bps

**Comment by jts** [comment]
What version of nanopolish are you using? The latest code should handle that model type:

https://github.com/jts/nanopolish/blob/master/src/nanopolish_squiggle_read.cpp#L478

**Comment by ckhithesh** [comment]
The version was old (0.6.1) and now we updated with new version(0.8.2), as if it is working good problem resolved
