### ISSUE TITLE
Problems [SOLVED] when compiling nanopolish

### ISSUE THREAD

**Issue by GA-Goig** [jts/nanopolish#239]
Today I managed to install nanopolish but I experienced some issues I had to overcome so I wanted to share with you just in case this could help anybody.

First of all, nanopolish is suposed to download htslib and fast5 and compile them for you. However, after running make, I found both folders but they were completely empty, so I manually downloaded and compiled them into nanopolish folder.

The tricky one is the reference to some libraries in the Makefile. When running make, the compiler was complaining about "undefined references to some lzma and bz2 libraries?). I'm not sure about this as I know little about C programming. In any case I modified the 11th line of the Makefile in order to "include" these libraries like this:

FROM
`LIBS=-lz`

TO
`LIBS=-lz -llzma -lbz2`

Hope this helps!
Galo

**Comment by jts** [comment]
Hi,

The htslib and fast5 folders were empty because you probably did not use the --recursive flag when running `git clone`. Thanks for the other tips though - what operating system are you using?

Jared

**Comment by GA-Goig** [comment]
It is a CentOS 7.3 server

**Comment by jts** [comment]
Just for my curiosity if you start from `git clone --recursive https://github.com/jts/nanopolish.git` do you still need to edit the makefile to add `-llzma -lbz2`?

**Comment by GA-Goig** [comment]
Yes, I still need to edit the makefile.

**Comment by jts** [comment]
Ok, thanks for the feedback!
