### ISSUE TITLE
Error running nanopolish on MAP006 dataset

### ISSUE THREAD

**Issue by kkrizanovic** [jts/nanopolish#24]
Hi,

I've been trying to run the nanopore paper pipeline on several other datasets (besides the one used in the paper). 

Namely, I'd like to run the latest nanopolish on MAP006 dataset.After I managed to get the fasta headers right, I've gotten a long series of following errors:

    Computing consensus for scf7180000000013:3200000-3210200
    nanopolish: nanopolish_squiggle_read.cpp:84: void SquiggleRead::load_from_fast5(const string&):
    Assertion `model.size() == 1024' failed.

To be more specific, these are 2d reads from MAP006_1-downloads/pass folder.

I've successfully manged to run older version of nanopolish on nanopore paper dataset (and a subset of it). Can you tell what I'm doing wrong this time, or maybe point me in the direction where to look further?

**Comment by jts** [comment]
Please use the latest code.

**Comment by kkrizanovic** [comment]
Thank you for a quick reply. I really appreciate it.

I thought I was using the latest version, but it seems I did something wrong while upgrading from an earlier one. After performing a clean install, it worked. Sorry for not doing my homework before posting here.

However, (there always seems to be a "however") during the polishing, I got two "Assertion failed messages". The process finished, bit I couldn't merge the segments, because some of them were missing. Do you have any advice how I could get it to work?

Running the nanopolish:

    python nanopolish/scripts/nanopolish_makerange.py draft_genome.fasta | parallel --results nanopolish.results -P 8 nanopolish/nanopolish consensus -o nanopolish.{1}.fa -w {1} --r raw.reads.pp.fa -b raw.reads.pp.sorted.bam -g draft_genome.fasta -t 4

Assertion failed messages:

    nanopolish: src/nanopolish_consensus.cpp:599: void run_splice_segment(HMMRealignmentInput&, uint32_t): Assertion `!data.empty()' failed.
    nanopolish: src/nanopolish_consensus.cpp:599: void run_splice_segment(HMMRealignmentInput&, uint32_t): Assertion `!data.empty()' failed.

Merging segments:

    python nanopolish/scripts/nanopolish_merge.py draft_genome.fasta nanopolish.*.fa > polished_genome.fasta
    ERROR_MISSING scf7180000000010 0
    ERROR_MISSING scf7180000000010 1
    ERROR_MISSING scf7180000000010 2
    ERROR_MISSING scf7180000000014 1

**Comment by jts** [comment]
Can you check whether the first 10,000 bases of scf7180000000010 has any
reads mapped to it?

Jared

**Comment by kkrizanovic** [comment]
I looked at the bam file generated by nanopolish, and there are reads mapped to scf7180000000010, with position less then 10000.

**Comment by jts** [comment]
This should be fixed in 3bb2c69306, like issue #23. Please reopen if it still occurs
