### ISSUE TITLE
Nanopolish settings for low coverage

### ISSUE THREAD

**Issue by apredeus** [jts/nanopolish#240]
Dear Jared, 

I'm trying to get a better consensus sequence for my draft genome assembly obtained from 3 nanopore runs. Are there any special options for correcting the assemblies obtained from lower coverage (15-20x) of long reads? 

I've also gotten quite a few warnings saying 

> Number of variants in span (13) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!

What reasonable higher value of this parameter one might use? Thank you!

**Comment by jts** [comment]
Not really, sorry. You will probably not get a high quality consensus sequence with only 15-20x, you should sequence more if possible.

You can ignore those warnings.

**Comment by apredeus** [comment]
Thank you for the answer.
