### ISSUE TITLE
Related Nanopolish Papers Required 

### ISSUE THREAD

**Issue by ckhithesh** [jts/nanopolish#242]
Send me the papers published or documents related to the nanopolish, which i can get details about the nanopolish output and also I'm comparing the two different strains, what tool i can use for pictorial representation of tsv output.

**Comment by jts** [comment]
This question is too broad, can you provide details about what you are trying to do?

**Comment by ckhithesh** [comment]
just to visualize the methylated sites with reference genome. What tool i can use, and also please send me the paper about the nanopolish which is published or unpublished.

**Comment by jts** [comment]
http://www.nature.com/nmeth/journal/v14/n4/full/nmeth.4184.html

Sorry but I don't have any tools for visualization. Here is a description of the fields in the tsv file:

chromosome: the chromosome containing the CpG site(s)
start: the start coordinate of the CpG site(s)
end: the end coordinate of the CpG site(s)
read_name: the name of the read making the call
log_lik_ratio: the log-likelihood ratio between the methylated and unmethylated models
log_lik_methylated: the log-likelihood of the methylated sequence (see paper)
log_lik_unmethylated: the log-likelihood of the unmethylated sequence (see paper)  
num_calling_strands: if 2D reads are provided, nanopolish will use observations from both strands to improve the call and this will be set to "2". With 1D reads it will be "1"
num_cpgs: the number of CpG sites that were evaluated in this call
sequence: the sequence containing the CpGs, plus some flanking sequence
