### ISSUE TITLE
Error in eventalign for direct RNA sequecning

### ISSUE THREAD

**Issue by awjga** [jts/nanopolish#243]
Hi,

I had tried it on my data from direct RNA sequencing.
The command for eventalign is working now.

However it is working when I am only using 1 gene in the reference sequence.
When I tried to use 2 or more genes in my reference sequence, this error occurs:
contig position reference_kmer read_index strand  event_index event_level_mean  event_stdv  event_length  model_kmer    model_mean model_stdv   standardized_level
[fai_fetch_seq] The sequence "Tetra" not found
nanopolish: src/alignment/nanopolish_eventalign.cpp:198: std::__cxx11::string get_reference_region_ts(const faidx_t*, const char*, int, int, int*): Assertion `cref_seq != __null' failed.
Aborted (core dumped)

I had tried mapping with graphmap and bwa, both resulted in the same error.

**Comment by jts** [comment]
Hi,

Can you provide the full commands you used to a) map the reads to the reference and b) run eventalign?

Jared

**Comment by awjga** [comment]
Hi,

I had first extracted my reads using nanopolish extract.
Followed by:
sed -i 's/U/T/g' try.fastq
graphmap align -r cp_nanopore.fa -d try.fastq -o try.sam --double-index
samtools view -bT cp_nanopore.fa try.sam > try.bam
samtools sort try.bam try.sort
samtools index try.sort.bam
nanopolish eventalign -r try.fastq -b try.sort.bam -g cp_nanopore.fa --print-read-names --summary=try.try > event
I had used the same commands for the 2 reference sequence, containing 1 gene and 2 or more genes.
Only the reference sequence with 2 or more genes had the error. 

I would also like to check, is the reference_kmer or model_kmer corrected for direct RNA sequencing?
As RNA is sequenced from the 3' to 5', which is different from how DNA is being sequenced.

**Comment by jts** [comment]
Can you provide the fasta headers of the `cp_nanopore.fa` file and one alignment record from the SAM file for the contig `Tetra`?

reference_kmer and model_kmer are both in the reference (5'->3') orientation, even for direct RNA. I _think_ it is simpler to be consistent but I'm not convinced it is the right thing to do.

**Comment by awjga** [comment]
Hi,
These are the information you require:
fasta header:
>Tetra
>Control

fcf48413-5d17-4ff7-9344-9fd1a99403de_Basecall_1D_template:1D_000:template       0       Tetra   300     40      8M1I8M2I5M1I4M1D21M1I28M1D5M1I20M1D5M1I8M3I1M1S *       0       0       CCCCTTTTCAAGATAAACTGACG

In the direct RNA, it is sequenced from the 3' to 5'. 
And in fast5 file, under Events, the sequences are flipped, when compare to basecalled sequence by albacore.
Did nanopore state that the orientation for the model_kmer is  5'->3'? or the order that it is being sequnced?
 I would think that it would be better if we can just filp the model_kmer?
 
Example for the first few bases from the Events:
Kmer: "CGGTC", "GTCCT","TCCTA","CCTAC","TACCA","ACCAT"
Move:       1  ,          2     ,       1     ,     1      ,      2      ,      1         
Form: CGGTCCTACCAT
From the fastq:
UACCAUCCUGGC

If you need, I can upload some fast5 files for the control RNA provided by nanopore.

**Comment by jts** [comment]
Can you delete cp_nanopore.fa.fai and try again? I think your fasta index for the reference is out of date.

The model kmers ONT provides are 3'->5' but I flipped them before loading into nanopolish and reverse the events. This was easier to implement rather than reversing the reference sequences.

**Comment by awjga** [comment]
I had deleted cp_nanopore.fa.fai, and remapped my reads, but I am still having the same error.

That's good to know, flipping of the model kmers and the event seems to be reasonable.   
So I guess the event index is also flipped?

**Comment by jts** [comment]
Can you run `cat cp_nanopore.fa.fai` and paste the results?

**Comment by awjga** [comment]
Here is the results:
>Tetra
GGCTCTCTAAATAGCAATATTTACCTTTGGAGGGAAAAGTTATCAGGCATGCACCTGGTAGCTAGTCTTTAAACCAATAGATTGCATCGGTTTAAAAGGCAAGACCGTCAAATTGCGGGAAAGGGGTCAACAGCCGTTCAGTACCAAGTCTCAGGGGAAACTTTGAGATGGCCTTGCAAAGGGTATGGTAATAAGCTGACGGACATGGTCCTAACCACGCAGCCAAGTCCTAAGTCAACAGATCTTCTGTTGATATGGATGCAGTTCACAGACTAAATGTCGGTCGGGGAAGATGTATTCTTCTCATAAGATATAGTCGGACCTCTCCTTAATGGGAGCTAGCGGATGAAGTGATGCAACACTGGAGCCGCTGGGAACTAATTTGTATGCGAAAGTATATTGATTAGTTTTGGAGTACTCG
>Control
ATGGCTGTCTCTAAAGTTTACGCTAGATCCGTCTACGACTCCCGTGGTAACCCAACCGTCGAAGTCGAATTAACCACCGAAAAGGGTGTTTTCAGATCCATTGTTCCATCTGGTGCCTCCACCGGTGTCCACGAAGCTTTGGAAATGAGAGATGAAGACAAATCCAAGTGGATGGGTAAGGGTGTTATGAACGCTGTCAACAACGTCAACAACGTCATTGCTGCTGCTTTCGTCAAGGCCAACCTAGATGTTAAGGACCAAAAGGCCGTCGATGACTTCTTGTTGTCTTTGGATGGTACCGCCAACAAGTCCAAGTTGGGTGCTAACGCTATCTTGGGTGTCTCCATGGCCGCTGCTAGAGCCGCTGCTGCTGAAAAGAACGTCCCATTGTACCAACATTTGGCTGACTTGTCTAAGTCCAAGACCTCTCCATACGTTTTGCCAGTTCCATTCTTGAACGTTTTGAACGGTGGTTCCCACGCTGGTGGTGCTTTGGCTTTGCAAGAATTCATGATTGCTCCAACTGGTGCTAAGACCTTCGCTGAAGCCATGAGAATTGGTTCCGAAGTTTACCACAACTTGAAGTCTTTGACCAAGAAGAGATACGGTGCTTCTGCCGGTAACGTCGGTGACGAAGGTGGTGTTGCTCCAAACATTCAAACCGCTGAAGAAGCTTTGGACTTGATTGTTGACGCTATCAAGGCTGCTGGTCACGACGGTAAGGTCAAGATCGGTTTGGACTGTGCTTCCTCTGAATTCTTCAAGGACGGTAAGTACGACTTGGACTTCAAGAACCCAGAATCTGACAAATCCAAGTGGTTGACTGGTGTCGAATTAGCTGACATGTACCACTCCTTGATGAAGAGATACCCAATTGTCTCCATCGAAGATCCATTTGCTGAAGATGACTGGGAAGCTTGGTCTCACTTCTTCAAGACCGCTGGTATCCAAATTGTTGCTGATGACTTGACTGTCACCAACCCAGCTAGAATTGCTACCGCCATCGAAAAGAAGGCTGCTGACGCTTTGTTGTTGAAGGTTAACCAAATCGGTACCTTGTCTGAATCCATCAAGGCTGCTCAAGACTCTTTCGCTGCCAACTGGGGTGTTATGGTTTCCCACAGATCTGGTGAAACTGAAGACACTTTCATTGCTGACTTGGTTGTCGGTTTGAGAACTGGTCAAATCAAGACTGGTGCTCCAGCTAGATCCGAAAGATTGGCTAAGTTGAACCAATTGTTGAGAATCGAAGAAGAATTGGGTGACAAGGCTGTCTACGCCGGTGAAAACTTCCACCACGGTGACAAGTTGTAA

**Comment by awjga** [comment]
Hi,

Thanks! you had found the problem!
Not sure why cp_nanopore.fa.fa is empty.
I think that is causing the issues.

**Comment by jts** [comment]
Great
