### ISSUE TITLE
nanopolish command fails

### ISSUE THREAD

**Issue by splaisan** [jts/nanopolish#244]
I still could not succeed running nanopolish, I recap here what I did
my 1D reads are fastq from the fast5 to fastq conversion with albacore and non-compressed.

I first index them using the latest build of nanopolish index, leading to the following files

```
nanopolish index filtered_albacore_reads.fastq
[readdb] num reads: 596702, num reads with path: 0
-r--r--  1 u0002316 domain users 5.5G Oct  6 17:26 filtered_albacore_reads.fastq
-rw-r--r--  1 u0002316 domain users 851M Oct  9 12:00 filtered_albacore_reads.fastq.index
-rw-r--r--  1 u0002316 domain users  36M Oct  9 12:00 filtered_albacore_reads.fastq.index.fai
-rw-r--r--  1 u0002316 domain users 708K Oct  9 12:00 filtered_albacore_reads.fastq.index.gzi
-rw-r--r--  1 u0002316 domain users  22M Oct  9 12:00 filtered_albacore_reads.fastq.index.readdb
```

I also mapped the same fastq reads to the draft assembly using bwa and coordinate sorted the BAM (I guess this is OK right?)

```
bwa mem -x ont2d -t 88 canu_contigs filtered_albacore_reads.fastq
-rw-r--r--  1 u0002316 domain users 3.8G Oct  6 17:48 read_mappings.sorted.bam
-rw-r--r--  1 u0002316 domain users 1.2M Oct  6 17:48 read_mappings.sorted.bam.bai
```

Then I applied the command from the wiki 
(your example command is using fasta => fastq is OK right?)
(the reads with -r use the name of the fastq file right?)

```
python /opt/biotools/bin/nanopolish_makerange.py ../de_novo/canu_contigs.fasta | \
    parallel --results nanopolish.results -P 8 \
        nanopolish variants --consensus polished.{1}.fa -w {1} \
            -r filtered_albacore_reads.fastq \
            -b read_mappings.sorted.bam \
            -g ../de_novo/canu_contigs.fasta \
            -t 4 --min-candidate-frequency 0.1
```

I get for each interval the same kind of error

> ##fileformat=VCFv4.2
> ##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">
> ##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">
> ##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">
> ##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">
> ##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">
> ##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
> #CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
> HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140333172008896:
>   #000: H5F.c line 591 in H5Fopen(): invalid file name
>     major: Invalid arguments to routine
>     minor: Bad value
> terminate called after throwing an instance of 'hdf5_tools::Exception'
>   what():  : : error in H5Fopen

**makerange works**

```
python /opt/biotools/bin/nanopolish_makerange.py ../de_novo/canu_contigs.fasta | head
tig00000001:0-50200
tig00000001:50000-100200
tig00000001:100000-150200
tig00000001:150000-200200
tig00000001:200000-250200
tig00000001:250000-300200
tig00000001:300000-350200
tig00000001:350000-400200
tig00000001:400000-450200
tig00000001:450000-500200
```

Any idea what is going wrong now?
Thanks in advance

**Comment by jts** [comment]
Hi,

When you ran `nanopolish index` it could not find the paths to the fast5 files:

```
nanopolish index filtered_albacore_reads.fastq
[readdb] num reads: 596702, num reads with path: 0
```

This caused the subsequent polishing steps to fail, as it could not find the signal data.

You'll need to provide the option specifying the nanopore run directory (`-d /path/to/run`). A bit more information is here:

https://github.com/jts/nanopolish#data-preprocessing

Jared

**Comment by splaisan** [comment]
Hi Jared,
I see, I did not see this one coming.

The fact is my fastq is only a subset of the original fast5/fastq where I filtered out 10-20% reads corresponding to a spiked-in lambda genome (I aligned all reads to lambda and removed the mapped reads based on the bam results).

Can I point '-d' to the full fast5 raw data folder tree or should I also filter the fast5 data first to fully match the retained fastq data?

Thanks

**Comment by jts** [comment]
You can point it to the full fast5 directory.

**Comment by splaisan** [comment]
It is polishing loud and clear now (and using my 88 threads more efficiently with 11x8 ;-)
THANK you very much for your help
Best

**Comment by splaisan** [comment]
before I close this, I get warnings after each contigs of the kind:

```
Number of variants in span (13) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
[post-run summary] total reads: 948 unparseable: 0 qc fail: 1 could not calibrate: 0 no alignment: 49
```

Should I higher the parameter when using this only for consensus polishing- or only if I would use the produced VCF results?

Thanks

**Comment by jts** [comment]
You can ignore that warning

**Comment by splaisan** [comment]
Thanks a lot Jared, the run finished and I could assemble the corrected data.
This closes this ticket, thanks for your troubleshooting and patience
Best regards

**Comment by jts** [comment]
No problem. Thanks for the feedback - I will use it to make nanopolish
easier to run.

Jared

**Comment by DEsalasL** [comment]
Hi, I'm having a problem with nanopolish index. the core gets dumped after nanopolish cann't open a summary file. However, the permissions and path of the files that is trying to open are ok (they work when call directly on cmd). I have tons of information so, I couldn't afford to skip the summary files. I'd appreciate if you could take a look to the example of the error I get and point me to what I should fix, check or look into.
Many thanks
this is going in a shell script:

#!/bin/bash
Dir1a=/path/run1/fast5s
Dir1b=/path/run2/fast5s
Summary1=/path/run1/sequencing_summary.txt
Summary2=/path/run2/sequencing_summary.txt
FqReads=Chopped.fastq
ls $Summary1 $Summary2 > summary_files.fof
Nanopolish=/software/nanopolish/nanopolish
source activate nanopolish-python3
$Nanopolish index -d $Dir1a -d $Dir1b -f summary_files.fof $FqReads

**Here is the error:**
blah ... (several lines of the reads with paths...)
[readdb] num reads: 2343834, num reads with path: 2209535
Loaded 1 from fofn
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 23086554726400:
  #000: H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1085 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: H5Fsuper.c line 277 in H5F_super_read(): file signature not found
    major: File accessibilty
    minor: Not an HDF5 file
terminate called after throwing an instance of 'hdf5_tools::Exception'
  what():  /Raw/Reads/Read_1895/duration: /path/run1/sequencing_summary.txt: error in H5Fopen
/var/spool/gridengine/job_scripts/34801: line 46: 63778 Aborted  (core dumped) $Nanopolish index -d $Dir1a -d $Dir1b -f summary_files.fof $FqReads

**Comment by jts** [comment]
Hi, 

Can you open a new issue for this?

Jared
