### ISSUE TITLE
nanopolish_merge error

### ISSUE THREAD

**Issue by apredeus** [jts/nanopolish#246]
Hello again, 

I'm having some trouble with merging the polished parts. It seems like one of the segments (utg000239l:100000-150200.fa) is missing; the stderr and stdout parts in the "results" folder are all empty. 

> Traceback (most recent call last):
>   File "nanopolish_merge.py", line 89, in <module>
>     assert(prev_segment is None or prev_segment + SEGMENT_LENGTH + OVERLAP_LENGTH > segment_start)
> AssertionError

Should I just re-run the polishing for this fragment? How do I do that? 

Thank you in advance.

**Comment by jts** [comment]
Hi,

Yes, you'll need to re-run polishing for that segment. You can do polish a single segment like this:

```
 nanopolish variants --consensus polished.utg000239l:100000-150200.fa.fa -w utg000239l:100000-150200.fa -r reads.fa -b reads.sorted.bam -g draft.fa -t 4 --min-candidate-frequency 0.1
```

If you get a recurrent error, let me know and I can help debug.

Jared

**Comment by apredeus** [comment]
Thank you very much. This fixed the problem - somehow those few runs were just lost.

**Comment by caonetto** [comment]
Hi Jared,
So when I was merging apparently two segments are missing. The fasta files of the segments are actually there however they are not merging?? I tried to re-run those segments but I get the following error. 
`error: segment starting at utg9:350000 is missing
error: segment starting at utg9:550000 is missing
error: some segments are missing, could not merge contig utg9
ubuntu@biolinux:$nanopolish variants --consensus polished.utg9:350000-400200.fa -w "polished.utg9:350000-400200.fa" -r trimmedpass.fastq -b sorted.bam -g TD1.fasta -t 12 --min-candidate-frequency 0.1 
error: faidx could not get contig length for contig polished.utg9
ubuntu@biolinux:/mnt/Federico/TD_1/Smartdenovo_assembly$`

Any ideas???

Thanks!

**Comment by jts** [comment]
Are you using the latest code from github? There was a bug in the merging script that would erroneously miss some segments, but it is now fixed.

Jared

**Comment by caonetto** [comment]
Thanks Jared,
Problem fixed.
