### ISSUE TITLE
Merge methylation calling from different runs!

### ISSUE THREAD

**Issue by trandoanduyhai** [jts/nanopolish#248]
Dear Jared,
would it be possible to merge read.fa (nanopolish extract) from different runs? I would like to run nanopolish call-methylation with the merged file. If yes, it would be great if you could recommend me the best way to merge *.fa file!
Thanks in advance!
Hai

**Comment by jts** [comment]
Sorry I missed this issue. You can merge runs by simply `cat`ing the fasta files together.

Jared

**Comment by trandoanduyhai** [comment]
Thanks Jared, I'll try!
Hai
