### ISSUE TITLE
nanopolish variants --consensus argument unrecognised

### ISSUE THREAD

**Issue by cazzlewazzle89** [jts/nanopolish#249]
I am trying to call nanopolish variants to compute a new consensus sequence by following the example in the README.

I am using the following code

`python /shared/software/anaconda3/bin/nanopolish_makerange.py 20171010_1443.contigs.fasta | parallel --results 20171010_1443_nanopolish.results -P 8 nanopolish variants --consensus polished.{1}.fa -w {1} -r 20171010_1443.cat.fasta -b 20171010_1443.sorted.bam -g 20171010_1443.contigs.fasta -t 4 --min-candidate-frequency 0.1`

but I am getting the following error

```
variants: unrecognized option '--consensus'
variants: too many arguments
```

Could you please shed some light on this? I have a feeling I may be using an out-of-date version of nanopolish (variants Version 0.4.0).

**Comment by jts** [comment]
Yes, your version of nanopolish is very old. If you upgrade this error will go away.

Jared

**Comment by cazzlewazzle89** [comment]
Excellent. Thanks Jared
