### ISSUE TITLE
Variant calling issue

### ISSUE THREAD

**Issue by SashaMeow** [jts/nanopolish#251]
I am trying to call variants with nanopolish. I try to do it with assembled contigs that I got from canu and a raw reads. 
As I understand there are 3 steps to do so:
-> align the reads with BWA (or another aligner, such as marginAlign, or LAST)
-> align the events with nanopolish eventalign
-> call a VCF with nanopolish variants

I have aligned reads from BWA.
So far I ran nanopolish eventalign
```
nanopolish eventalign --reads DB146_6_rawData.fasta -b DB146_6.sorted.bam -g DB146_6_porechop.contigs.fasta > DB146_6.varcall.sam
```
so I tried to convert this file to bam
```
samtools view -bt DB146_6_porechop.contigs.fasta.fai DB146_6.varcall.sam > DB146_6.varcall.bam
```
but it aborts the processes with an error:
```
[W::sam_read1] parse error at line 1
[main_samview] truncated file.
```
If I try to remove the 1 line and run the file without it than there is an error: no SAM header.
If I try to call variants right away (without running eventalign) it aborts:
```
genome has multiple contigs, please use -w to specify input region
```

The question is:
-> how to produce correct SAM file (that it could be transformed into BAM) from evenalign
-> must evenalight be ran to call variants?

**Comment by jts** [comment]
Hi,

You don't need to run `eventalign` before variant calling anymore. You can skip that step.

Jared

**Comment by SashaMeow** [comment]
Hi @jts Jared
thank you for a quick respond. 

I follow up with question: is there a way to call variants on the whole file and not by the regions as it suggesting me when I try to just call variants.
```
genome has multiple contigs, please use -w to specify input region
```

**Comment by jts** [comment]
Not currently, you'll have to call chromosome-by-chromosome.

Jared
