### ISSUE TITLE
Why are megabase-sized contigs needed?

### ISSUE THREAD

**Issue by btemperton** [jts/nanopolish#252]
We have a viral metagenome sequenced by 1D ligation and assembled in canu. Canu + PILON gets us within 99% ANI of contigs we see from SPAdes hybrid assemblies. I would like to try CANU + nanopolish + PILON to see if (a) we can get closer (see http://albertsenlab.org/what-is-a-good-genome-assembly/) and (b) if we can detect any methylation signal in the viral genomes. However, even if we manage to sequence complete viral genomes, most of the contigs will be 10-300kb. What effect will this have on nanopolish?

**Comment by nickloman** [comment]
Speaking from my own experience, it should not matter how long the contigs are. Just bear in mind that the very flanking tips of contigs (e.g. first and last 20-30bp) may not get corrected.

**Comment by jts** [comment]
@nickloman is right, polishing small contigs should work fine except for the very ends
