### ISSUE TITLE
Running nanopolish

### ISSUE THREAD

**Issue by isardi** [jts/nanopolish#254]
Hello,

I am having trouble running nanopolish, mainly because I am unclear about the required input.  I am using the guide from the nanopolish GitHub but I am still having questions.

First, I run Albacore 2.0 to process MinKnow output.  I did it like this:

read_fast5_basecaller.py -i ~/MinKnowOutput/ -s AlbacoreTest -f FLO-MIN106 -k SQK-RAD003 -r -t 8 --output fast5,fastq

This generated several types of files in the pass folder: 
1) Multiple folders, each one labeled with a number, with the fast5 files 
2) Inside that same pass folder I have multiple fastq files 

To run nanopolish, given that I used Albacore 2.0 I am running the following code:

 nanopolish index -d ~/MinKnowOutput/AlbacoreTest/workspace/pass/ ~/MinKnowOutput_pGUS1/AlbacoreTest/workspace/pass/*.fastq

I am getting the error:
index: too many arguments

Not sure about the last part where I need to add the <albacore_output.fastq> given that I have multiple fastq.

Thanks in advanced for any help.

Best,
MariaIsabel

**Comment by colindaven** [comment]
You need to combine your fastqs. 

For example
`cat *.fastq > allreads.fastq`

Then just supply allreads.fastq (single arg) as you were doing
Otherwise it looks correct.

**Comment by jts** [comment]
Thanks for answering @colindaven
