### ISSUE TITLE
AssertionError during merge ; how to rerun specific windows with different parameters?

### ISSUE THREAD

**Issue by ishengtsai** [jts/nanopolish#256]
Hi,

Similar to #247 , I also ran into some problem when some windows came out empty. This is interesting as it didn't happen when I ran 3 rounds of racon instead of 5 now.

Traceback (most recent call last):
  File "/home/ijt/bin/nanopolish/scripts/nanopolish_merge.py", line 89, in <module>
    assert(prev_segment is None or prev_segment + SEGMENT_LENGTH + OVERLAP_LENGTH > segment_start)
AssertionError

I was wondering if I can rerun nanopolish on specific windows. And if so, how to I detect them and how do I rerun with just these windows?

**Comment by jts** [comment]
Hi,

Yes, you can re-run nanopolish on the windows that failed. Currently you manually have to identify the missing windows but I'll add more informative output into `nanopolish_merge.py`. Thanks for the report.

Jared

**Comment by jts** [comment]
Hi,

Sorry for the long delay but `nanopolish_merge.py` will now indicate what segments are missing.

Jared

**Comment by jts** [comment]
(btw if you figure out what the 3 vs 5 rounds of racon problem was, I'd like to hear about it)
