### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by rojinsafavi** [jts/nanopolish#258]
Hi Jared,
I'm trying to run eventalign with a 5mer model given in your r9-models folder, but I keep getting this error:
nanopolish eventalign --reads ../chr20/reads.fa --bam ../chr20/reads.sorted.bam --genome ../chr20/chr20.fa --models-fofn ./etc/r9-models/r9.4_450bps.nucleotide.5mer.template

Error: unknown model: 

I would appreciate if I can get some help!
Thanks,
Rojin

**Comment by jts** [comment]
Hi Rojin,

You don't have to give the `--models` parameter to eventalign, it will automatically select the best model to use. The `--models` parameter is for debugging use only and a bit tricky to use. 

Jared

**Comment by jts** [comment]
Hi Rojin,

You don't have to give the `--models` parameter to eventalign, it will automatically select the best model to use. The `--models` parameter is for debugging use only and a bit tricky to use. 

Jared

**Comment by jts** [comment]
Hi Rojin,

You don't have to give the `--models` parameter to eventalign, it will automatically select the best model to use. The `--models` parameter is for debugging use only and a bit tricky to use. 

Jared

**Comment by rojinsafavi** [comment]
I see, is there any way to get 5mer output instead of 6mers?

**Comment by jts** [comment]
Not easily, why do you want to?

**Comment by Stautis** [comment]
Hi Jared, 
I decided to leave a comment on this closed issue as I've encountered a similar situation. I'm trying to enforce a 5-mer output for my dna samples after the eventalign step to experiment with this format input for the subsequent nanocompore step of my analysis, but when specifying the model I wish to use (r9.4_450bps.nucleotide.5mer.template.model), that I have in my working directory, I also get the message: 

"Error: unknown model:"

I was wondering how I could specify the use of this model.

Thanks,
Thomas

**Comment by jts** [comment]
Hi @Stautis,

You have to tell nanopolish to load your new model. To do this, create a new file called something like `models.fofn` (fofn = file-of-filenames) and put a single entry in it:

```
r9.4_450bps.nucleotide.5mer.template.model
```

Then tell `nanopolish eventalign` to load the models specified in this file with `--models-fofn models.fofn`.

Nanopolish will still try to load the built-in 6-mer model though. You can force it to load your 5-mer model by changing this variable (`k = 6` to `k = 5`):

https://github.com/jts/nanopolish/blob/master/src/nanopolish_squiggle_read.cpp#L287

You'll need to recompile, but after that it _should_ work. 

Jared

**Comment by jts** [comment]
(my apologies to @rojinsafavi for the terse message years ago, this wasn't a very difficult workaround after all)

**Comment by Stautis** [comment]
Thanks for the rapid response. This produced the output I was looking for. Much appreciated!
