### ISSUE TITLE
Variant calling issue (duplicate reads in fasta)

### ISSUE THREAD

**Issue by eyesmo** [jts/nanopolish#261]
Trying to use nanopolish on a little 1d R9.5 amplicon data. I ran
>nanopolish variants --consensus=20171101_Untreated/20171101_Untreated_NanopolishConsensus.fasta --bam 20171101_Untreated/alignment/20171101_Untreated_GraphMap_AlignToConsensus.srt.bam --genome 20171101_Untreated/20171101_Filt13_Untreated_canu.bestcontig.fasta --reads 20171101_Untreated/fastq/20171101_NPextract_Untreated.fastq

and I got
>##fileformat=VCFv4.2
>##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads >used to call the variant">
>##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space >reads that support the variant">
>##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of >base-space reads that support the variant">
>##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space >reads that support the variant">
>##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of >the allele">
>##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
>#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
>Error: duplicate read name daef1c10-5cc9-4664-847f-e8bea1010ff4 found in fasta file

This is with FAST5 files that were basecalled on Albacore v2.something, and fastq files that were generated directly from read_fast5_basecaller.py. Attached are the relevant fastq+fasta files.

[fasta+fastq.zip](https://github.com/jts/nanopolish/files/1460029/fasta.fastq.zip)

Any advice? Is there something obvious that I'm missing?
If it helps I'm also willing to share the fast5 files and the original two fastq files I merged.

**Comment by jts** [comment]
Hi,

The read `daef1c10-5cc9-4664-847f-e8bea1010ff4` appears in your fastq file twice. Nanopolish considers each read to be an independent sample from the genome so it requires that no reads are duplicated. I suspect something went wrong with your basecalling run. If you fix this problem then nanopolish should be able to run.

Jared

**Comment by eyesmo** [comment]
I've tried re-basecalling a couple of times and it hasn't worked. Is there a way for me to delete duplicate reads from the fastq file (or to find and delete duplicate fast5 files)?

**Comment by jts** [comment]
You'd have to write a script to do it.

**Comment by eyesmo** [comment]
Okay, managed to filter all the duplicate reads. Now I tried 
>nanopolish variants --consensus=20171101_Untreated/20171101_Untreated_NanopolishConsensus.fasta --bam 20171101_Untreated/alignment/20171101_Alb_Untreated_GraphMap_AlignToConsensus.srt.bam --genome 20171101_Untreated/20171101_Alb_Filt13_Untreated_canu.bestcontig.fasta --reads 20171101_Untreated/fastq/20171101_Unique_Untreated.fastq

And got
>##fileformat=VCFv4.2
>##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads >used to call the variant">
>##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space >reads that support the variant">
>##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of >base-space reads that support the variant">
>##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space >reads that support the variant">
>##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of >the allele">
>##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
>#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
>Error: could not find path to FAST5 for read 02064ddd-58c5-4708-977b-a9b588c35e7b
>Please make sure that this path is accessible: start_time=2017-10-31T23:02:39Z

I thought this might be because I concatenated/merged fastq files from several stopped-and-started runs, and stored the merged fastq file in a different directory than the Albacore-basecalled fast5 files. So I tried removing duplicates from the original fastq file in one of the albacore directories (20171101_0044_Untreated/workspace/pass):
>!gt sequniq -force -o 20171101_0044_Untreated/workspace/pass/fastq_runid_4d81bcdd2c7416e479c7ded87f124d09fe2b16f6_0_Unique.fastq 20171101_0044_Untreated/workspace/pass/fastq_runid_4d81bcdd2c7416e479c7ded87f124d09fe2b16f6_0.fastq
>
>8 out of 153 sequences have been removed (5.229%)
>
>!nanopolish variants --consensus=20171101_Untreated/20171101_Untreated_NanopolishConsensus.fasta --bam 20171101_Untreated/alignment/20171101_Alb_Untreated_GraphMap_AlignToConsensus.srt.bam --genome 20171101_Untreated/20171101_Alb_Filt13_Untreated_canu.bestcontig.fasta --reads 20171101_0044_Untreated/workspace/pass/fastq_runid_4d81bcdd2c7416e479c7ded87f124d09fe2b16f6_0_Unique.fastq

And I still got 
>##fileformat=VCFv4.2
>##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads >used to call the variant">
>##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space >reads that support the variant">
>##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of >base-space reads that support the variant">
>##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space >reads that support the variant">
>##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of >the allele">
>##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
>#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
>Error: could not find path to FAST5 for read 045eeb20-7017-47a7-8a7e-c56f83a4c856
>Please make sure that this path is accessible: start_time=2017-11-01T02:55:40Z

I've read in other issues that this can happen when the fastq file is generated from MinKNOW; but I'm definitely using Albacore. What am I missing?

**Comment by jts** [comment]
Did you run `nanopolish index` after filtering your fastq file? What version of nanopolish are you running?
