### ISSUE TITLE
Question about results from eventalign

### ISSUE THREAD

**Issue by awjga** [jts/nanopolish#264]
Hi,

I would like to clarify the results from eventalign.
I am having rows that contains NNNNN   0.00    0.00    inf. under model_kmer, model_mean, model_stdv and standardized_level.
What does it mean for those results?

If I had understand correctly, the program scale the model to the events, so that it can be basecalled with the raw signal?
Does the result mean that the program is unable to scale the model_mean to some of my events?

Thanks!

**Comment by jts** [comment]
Hi,

Nanopolish's HMM has a "bad data" state for events that don't match any
k-mer very well. When an event aligns to this state, it is output as
"NNNNNN". I suggest ignoring these events in your subsequent analysis.

Jared

**Comment by awjga** [comment]
Thank you so much for the clarification!
