### ISSUE TITLE
Error for nanopolish extract

### ISSUE THREAD

**Issue by pwkooij** [jts/nanopolish#265]
I am trying to run nanopolish extract on my data (extracted with albacore 1.2.5) using the command

`nanopolish extract --type any -b albacore fast5/ -o reads2_mux_pass.fa`

However, I get the following error:

`Error running faidx_build on reads2_mux_pass.fa.index`

Any idea what is happening here? What exact input is expected for the nanopolish extract?

**Comment by pwkooij** [comment]
I am now using the nanopolish index command instead, and this seems to be working. Will let you know when it is finished

**Comment by jts** [comment]
Ok, let me know if you had problems.

**Comment by pwkooij** [comment]
It seems everything worked well, but I'm encountering a problem for one chunk. When running nanopolish_merge.py I received the following error:

`Traceback (most recent call last):
  File "/var/lib/nanopolish/scripts/nanopolish_merge.py", line 89, in <module>
    assert(prev_segment is None or prev_segment + SEGMENT_LENGTH + OVERLAP_LENGTH > segment_start)
AssertionError`

Following instructions from other issues, I narrowed it down to one missing chunk. When I try to run `nanopolish variants` for this particular chunk I received yet another error:

`##fileformat=VCFv4.2
##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">
##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">
##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">
##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">
##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample
nanopolish: src/alignment/nanopolish_alignment_db.cpp:201: std::vector<HMMInputData> AlignmentDB::get_event_subsequences(const string&, int, int) const: Assertion 'e1 >= 0' failed.
Aborted (core dumped)`

Any idea how to resolve this?

**Comment by pwkooij** [comment]
Having the same problem with a different data set. In both cases the problematic chunk is somewhere in the middle of a contig

**Comment by jts** [comment]
Hi,

I'm at a conference right now but will help next week.

Jared

**Comment by pwkooij** [comment]
Hi Jared, 

Thanks, enjoy your conference!
Just to let you know, for the second set I backed up the results and now I'm re-running it with segment size set at 100k.

Cheers
Pepijn

**Comment by pwkooij** [comment]
Quick update, I set segment size on 100k as well as 25k, but both gave the same problems. I pulled out the 2 different contigs from the 2 datasets and did a blast search. It looks like they are mitochondrial genomes. Not sure if this will help you, but thought you should know

**Comment by jts** [comment]
Hi @pwkooij,

Thanks for the update. Could you follow the instructions I've posted [here](https://github.com/jts/nanopolish/issues/199#issuecomment-349335955) to make a small test case to help us debug this issue?

Jared

**Comment by jts** [comment]
Resolved in #199
