### ISSUE TITLE
cram index not recognized

### ISSUE THREAD

**Issue by noncodo** [jts/nanopolish#266]
I'm trying to use cram files to circumvent the htslib  >64k CIGAR operations problem for ultra-long reads.  As commented on commit 6918f6590ec66748b346063e4ff820ddb661866d, nanopolish doesn't handle/recognise the .crai index well. Something missing in the htslib/sam.c::sam_index_load2() arguments?
FYI I'm using samtools v1.6. 
N.B. attempting to run it with a .bai generated from the .crai with cramtools-3.0.jar segfaults. 

`samtools index read.minimap2.cram && nanopolish eventalign -r ./read.fastq -b read.minimap2.cram -g hg38_UCSC.fa -t 2 --progress 
Error: could not load the .bai index file for read.minimap2.cram 
Please run 'samtools index read.minimap2.cram' before nanopolish`

**Comment by jts** [comment]
Hi,

Most nanopolish modules support cram but I missed adding support to `eventalign`. I'll fix this soon.

Jared

**Comment by jts** [comment]
I've implemented cram support in `eventalign`, could you try the latest code and let me know if it works for you?

**Comment by noncodo** [comment]
Thanks Jared! I'm getting this error now:
`[cram_itr_query] tid=-3 not implemented for CRAM files -- Exiting
Aborted`

**Comment by jts** [comment]
That's a new one to me - maybe try giving a defined reference region to compute the eventalign over:

```
nanopolish eventalign [...] chr1:10,000,000-20,000,000
```

**Comment by noncodo** [comment]
Will do. Have a play if you want: 
`http://pwbc.garvan.org.au/~marsmi/ripper/fastq_runid_f84ad9e2bf813f3cf633e35d4a7bf531d021e5f3_0.fastq.bz2`
`http://pwbc.garvan.org.au/~marsmi/ripper/ripper.minimap2noL.cram`

**Comment by jts** [comment]
I've reported this to the htslib developers, hopefully they will implement it: 
https://github.com/samtools/htslib/issues/625

**Comment by noncodo** [comment]
Defining the reference region works, but eventalign fails to produce an alignment for this read (alignment should be respectable given the mean q-score of 12.445 with albacore-2.0.4). 

`[bam process] iterating over region: chr19:55900000-57030000
[post-run summary] total reads: 1 unparseable: 0 qc fail: 0 could not calibrate: 0 no alignment: 1`

**Comment by jts** [comment]
`no alignment: 1` means that nanopolish couldn't infer the event-to-kmer mapping it relies on to realign the events to the reference genome. It could be due to the long read length, I haven't run many very long reads through it yet. If you don't mind experimenting, you could increase the `bandwidth` parameter here   to see if you can make it work:

https://github.com/jts/nanopolish/blob/master/src/nanopolish_raw_loader.cpp#L89

**Comment by noncodo** [comment]
bandwidth = 200 worked! 
What anticipated effect does a higher bandwidth parameter value have on computation?

**Comment by noncodo** [comment]
Well, partially worked... will play around some more.
