### ISSUE TITLE
Nanopolish index faidx error

### ISSUE THREAD

**Issue by barneypotter24** [jts/nanopolish#271]
Hello! 

I've been trying to run `nanopolish index`, and I have run into an error that says `Error running faidx_build on </output/file>.fastq.fa.gz`. The call that I am using is `nanopolish index -d </path/to/raw/reads/> </path/to/fastq>`. The FASTQ was generated using Albacore 2.0.2 and running that output through Porechop 0.2.2. 

I haven't been able to find a solution to this looking through other issues, so any help would be great. Thanks!

**Comment by jts** [comment]
Hi Barney,

In the instructions `</path/to/raw/reads/>` and `</path/to/fastq>` are placeholders that we use as an example. You should replace these with the actual name of your fast5 directory and the albacore output file.

I hope this helps!
Jared

**Comment by barneypotter24** [comment]
Hi Jared,

I did actually use real global paths in my call! Sorry if that was confusing, I'm in the habit of removing the actual paths when I post online to avoid clutter.

~Barney

**Comment by jts** [comment]
Ah, I see. Do you mind sharing the full command you ran and error message? Did nanopolish manage to write a file called `</output/file>.fastq.fa.gz`?

**Comment by barneypotter24** [comment]
Yes, call was `nanopolish index -d /media/amphora/zika-seq/usvi-library8-1d-2017-03-31/raw_reads/ /home/barneypotter/zika-seq/build/VI41.fastq` and it did write a file called `VI41.fastq.fa.gz`.

**Comment by jts** [comment]
Was `VI41.fastq.fa.gz` output to the working directory or `/home/barneypotter/zika-seq/build/`? I'm wondering whether this is a file path issue.

**Comment by barneypotter24** [comment]
It was output to `/home/barneypotter/zika-seq/build/`.

**Comment by jts** [comment]
What happens if you run `samtools faidx /home/barneypotter/zika-seq/build/VI41.fastq.fa.gz`?

**Comment by barneypotter24** [comment]
When I run the above command:
```
samtools faidx /home/barneypotter/zika-seq/build/VI41.fastq.fa.gz
samtools: error while loading shared libraries: libhts.so.2: cannot open shared object file: No such file or directory
```

**Comment by jts** [comment]
It looks like your samtools installation is broken, could you fix it and try again? 

Once the file `VI41.fastq.fa.gz` is succesfully generated all nanopolish is doing is bulding an `faidx` of the file, using the same function call as samtools. I'd like to see whether the standalone version works or gives a more informative error message.

**Comment by barneypotter24** [comment]
I reinstalled Samtools, the new error message says `Could not build fai index /home/barneypotter/zika-seq/build/VI41.fastq.fa.gz.fai` when I run faidx directly.

**Comment by jts** [comment]
Can you run `zcat /home/barneypotter/zika-seq/build/VI41.fastq.fa.gz | head` and paste the output?

**Comment by barneypotter24** [comment]
I ran that command, and the file appears to be empty.

**Comment by jts** [comment]
That's the problem then, now the question is why is it empty. Is there anything in `/home/barneypotter/zika-seq/build/VI41.fastq`? The `.fa.gz` version should just be a copy with the qualities removed and compressed.

**Comment by barneypotter24** [comment]
When I run `cat /home/barneypotter/zika-seq/build/VI41.fastq | wc -l` I see that there are 2,112,680 lines in the file and looking at it through `head` looks normal.

**Comment by jts** [comment]
Do you get the same error every time you run the program, or is it transient? Have other data sets worked for you? Are you using the latest version of nanopolish?

**Comment by barneypotter24** [comment]
I have found the same error every time that I ran the program. Unfortunately at this time I just have one dataset that I can work with, since we have only sequenced one library on 1D chemistry. I am using 0.8.1 because our server uses Anaconda as a package manager and that appears to be the latest version available through the package manager.

**Comment by jts** [comment]
It would be great if you can try the most recent code to see if the error persists. Nanopolish automatically installs all of its dependencies so it should not be very difficult to compile.

**Comment by barneypotter24** [comment]
After reinstalling and re-running, it looks like the same error is coming up. It looks like the output files are slightly different now—in particular there are no longer compressed `.gz` files being produced—but the same error message still comes up.

**Comment by jts** [comment]
Can you send me `VI41.fastq`?

**Comment by barneypotter24** [comment]
Yes, I can do that. Do you know a good way to send it to you? Github only lets me upload files up to 10MB as a reply, and even the manually compressed version is >200MB.

**Comment by jts** [comment]
Can you host it on dropbox for a day or two?

**Comment by barneypotter24** [comment]
Yes, the file is up, both compressed and uncompressed in case `gzip` on my end is what is causing the issue. https://www.dropbox.com/sh/cfai459p8kuvgx4/AACLgfeq7OzW_sF-IsE0lvABa?dl=0

**Comment by jts** [comment]
Hi Barney,

Thanks, that let me track down the problem. It seems something went wrong when you produced the fastq file as some of the reads have a path embedded within the quality string (heres the first read in the file):

```
@d2ef3ff1-de47-4c57-9291-77edbd6f8850 runid=ac92cc8958563afd4483dd036f08e0dedec23ff0 read=37886 ch=466 start_time=2017-04-01T16:07:32Z
GTCTTGATGAGGAACGGGGCATAGGGAAGATATGAGCTGGAATGGTGTTGACTCTTGCAGAACCCAGCACATGTCTAAAGTGACCAGCTAAGAATTGCATGTGTCCTCATTGTTGTGTTCCTATTGCTGGTGGTTGTCATACCTGGAGGCAGAAAAGCAAAAGATCTCCCCAGGACAACCAAATGTGGCAATCCATCATCATAGTGGCAGCAGTAGGTCACTACAGGCTTGATCCTGCCAATGAACTCGGATGATTTGGAGAGAACAAAGGTGACTATATCTAATAAGGAAGGAGAGGGAGGGGCAACCATACCAAGTTCTCAATGGACATTGACCTGCGGCCAGCCTCAGCTTGAGCCATCTATGCTGCCTTGACAACTTTCATTACCCCAACCGTCCAACATGCAGTGACACC
+
&++-**(*(*-+*&'+>D<9::478/466?>,*(''):.>CEE=89,+'*+:;4D4+())$,;)&(672:45,14,-31,.+-.?2-,(.-'-6.D0:;0,.)+<<9;?CF<>D9>@BA;)((,013131-.+<+)-BAD;@?73-*-7049=CA<*28D70+-.-,EB@,3:=:2;4319=+*'(*,*-1/52,-/29982*0.*015)7,-1(2-,+#%,'+(-8556311))')3-7.--:D>@716430*.>734101*:D=>F-,()+-1*-/=:;/:0-*(47259;5+),0,(2/*&(+=3F7900(4,23G9BD6H88AC>;6;314C=>='8B</+4<2621/home/barneypotter/zika-seq/data/usvi-library8-1d-2017-03-31/alba121/workspace(.%*9F@@?:799999=5B/-(1).+7D?>&71/8EF00)5644:380/2=;-/.-.+,','
```

(note the `/home/` part)

This leads to a length mismatch between the sequence and quality string, which makes the FASTQ records invalid and skipped. If you fix the files it should be ok.

Jared
