### ISSUE TITLE
possible nanopolish variants usage typo

### ISSUE THREAD

**Issue by ConradStack** [jts/nanopolish#272]
In the usage information from `nanopolish variants --help`, the example given for `-q` parameter uses `-m`:

> -q  --methylation-aware=STR          turn on methylation aware polishing and test motifs given in STR (example: -m dcm,dam)

Also, the program doesn't fail when `-m dcm,dam` is used.  Presumably, the string is being converted to a double and overrides an earlier declaration of `-m`?

**Comment by jts** [comment]
Yep, that's a typo - the correct parameter is -q. I'll fix this tomorrow.
Thanks for pointing it out.

jared

**Comment by jts** [comment]
Fixed, thanks again.
