### ISSUE TITLE
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 47364134836800

### ISSUE THREAD

**Issue by damientully** [jts/nanopolish#273]
Hi Jared,

I appear to be getting this error when indexing reads. These reads were base called with Albacore v2.1.2 and I'm guessing its an issue with one of the fast5 files as when I go onto polish I also get an error. Any suggestions.

Thanks,
Damien

[readdb] num reads: 187391, num reads with path: 185892
Indexing pass//33
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 47364134836800:
  #000: H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1085 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: H5Fsuper.c line 294 in H5F_super_read(): unable to load superblock
    major: Object cache
    minor: Unable to protect metadata
  #003: H5AC.c line 1320 in H5AC_protect(): H5C_protect() failed.
    major: Object cache
    minor: Unable to protect metadata
  #004: H5C.c line 3574 in H5C_protect(): can't load entry
    major: Object cache
    minor: Unable to load metadata into cache
  #005: H5C.c line 7954 in H5C_load_entry(): unable to load entry
    major: Object cache
    minor: Unable to load metadata into cache
  #006: H5Fsuper_cache.c line 476 in H5F_sblock_load(): truncated file: eof = 299605, sblock->base_addr = 0, stored_eoa = 319480
    major: File accessibilty
    minor: File has been truncated

**Comment by jts** [comment]
Hi Damien,

Could you send me one read that causes the crash so I can reproduce it here?

Jared

**Comment by jts** [comment]
Actually, looking into this a little I don't think it is a problem. The error comes from HDF5 which nanopolish detects and ignores. The indexed data file should be ok. What error did you get when polishing?

**Comment by damientully** [comment]
Hey Jared,

Thanks for your response.

This is what I get when polishing:

##fileformat=VCFv4.2
##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">
##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">
##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">
##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">
##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 47812937611840:
  #000: H5F.c line 591 in H5Fopen(): invalid file name
    major: Invalid arguments to routine
    minor: Bad value
terminate called after throwing an instance of 'hdf5_tools::Exception'
  what():  /Raw/Reads/Read_7547/Signal: : error in H5Fopen

**Comment by jts** [comment]
Thanks - any chance I could get example reads to debug that one?

**Comment by damientully** [comment]
Sure, I just sent you an email with a link to a folder containing reads.

Thanks!

**Comment by jts** [comment]
Thanks but it appears to work for me when I basecall the reads here. Could you send me your basecalled reads as well in case that is the problem?

**Comment by damientully** [comment]
Thanks Jared. Just sent you an email.

**Comment by jts** [comment]
I've just pushed some code which should fix this, can you try it?

**Comment by damientully** [comment]
Hi Jared,

Thanks for the fix. Worked perfectly now.

Damien

**Comment by BrianKTran** [comment]
im having the same issue/ files check out under h5check and h5dump but when ran, it cant read the data in the files:
```
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 0:
  #000: H5Dio.c line 173 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: H5Dio.c line 551 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: H5Dchunk.c line 1875 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: H5Dchunk.c line 2905 in H5D__chunk_lock(): data pipeline read failed
    major: Data filters
    minor: Filter operation failed
  #004: H5Z.c line 1347 in H5Z_pipeline(): required filter 'deflate' is not registered
    major: Data filters
    minor: Read failed
terminate called after throwing an instance of 'H5::DataSetIException'
*** Aborted at 1611347242 (unix time) try "date -d @1611347242" if you are using GNU date ***
PC: @     0x7f764968efb7 gsignal
```
