### ISSUE TITLE
event index in eventalign result

### ISSUE THREAD

**Issue by yongkuk** [jts/nanopolish#276]
Hi, I'm a 2nd-year PhD Student learning to deal with the raw signal level data from MinION.

I have a direct RNA sequencing data from MinION, and trying to match the events to the reference sequence. The purpose of this run was to see if a certain base modification can generate differences in raw signals. The sample was a mixed pool of modified and unmodified RNA, at a single locus. My expectation was that the signals will split into two distinct groups near the modified locus, similar to the BioRxiv paper by Andrew Smith.

But I'm having difficulties matching the event starts and ends with the reference sequence. I tried using mapped bases as anchors and linearly scaling the raw signals in between them to convert the raw signal's time axis into base counts. However, this resulted in numerous unexpected frame-shifts, making it hard to see which is from modification and which is from aligning errors. I guess this frame shifts are due to the fact that a single event represents ~5 nucleotides, not 1.

Looking into the ONT community, I found that the eventalign module in your nanopolish maybe the perfect solution for this. So I gave it a try. The installation and running the code was a breeze, but I couldn't easily interpret the results. 

In particular, how is the 'event_index' column created? My first guess was that it is the index for the 'move' events, but it wasn't. I couldn't make a second guess, so I'm calling for help.

Moreover, if this kind of usage was not intended, what would be your suggestion for this kind of problem??

For your information, my data was produced from flow cell version MIN107 and protocol SQK-RNA001. Fast5 files used for the nanopolish were 'pass' outputs from an Albacore (v2.1.3) base calling.

Here is a sample of my result.

`contig  position        reference_kmer  read_name       strand  event_index     event_level_mean        event_stdv      event_length    model_kmer      model_mean      model_stdv      standardized_level
YHR174W 2       GGCTG   0167ec74-1ec9-4c44-baa6-82a9d5640ae7    t       47      103.44  4.265   0.00498 GGCTG   108.39  4.12    -1.12
YHR174W 3       GCTGT   0167ec74-1ec9-4c44-baa6-82a9d5640ae7    t       48      79.99   3.563   0.00332 GCTGT   82.13   3.30    -0.60
YHR174W 4       CTGTC   0167ec74-1ec9-4c44-baa6-82a9d5640ae7    t       49      94.48   3.723   0.00232 CTGTC   95.91   4.38    -0.30
YHR174W 5       TGTCT   0167ec74-1ec9-4c44-baa6-82a9d5640ae7    t       50      113.62  8.152   0.00664 TGTCT   109.02  7.04    0.61
YHR174W 6       GTCTC   0167ec74-1ec9-4c44-baa6-82a9d5640ae7    t       51      73.29   2.799   0.00730 GTCTC   74.08   2.39    -0.31`

Thanks for reading, and it would be a great pleasure to learn from your answers.

**Comment by jts** [comment]
Hi @yongkuk,

Great question!

There are two different types of signal data: raw samples and segmented events. Nanopolish uses segmented events, and `event_index` is the index into the vector of events. Previous versions of albacore (prior to 2.0) ran a segmentation algorithm on the raw signal to generate this event vector. Since albacore 2.0 and later no longer uses events for basecalling, nanopolish has to segment the signal internally (you can read about this change [here](http://simpsonlab.github.io/2017/09/06/nanopolish-v0.8.0/)). Since nanopolish now segments the data on its own, the `event_index` it uses does not correspond to anything that is in the fast5 file (in fast5 produced by albacore 2.0 the events are fixed-length windows so very different than what nanopolish expects).

My suggestion for this type of analysis is to just use the event-aligned data rather than going back to the signal in the fast5s. If you use the `--scale-events` option to `eventalign` you should be able to look at individual reference positions to see if you see two groups of current.

I hope this helps, let me know if you have any other questions.

Jared

**Comment by yongkuk** [comment]
Thanks a lot for a quick reply.
Now it all makes perfect sense, and your suggestion is a big help.

Can I understand the function of `--scale-events` option is to somehow normalize the detected events for inter-signal comparisons?
 
Moreover, one minor question, how can I see which signal model was used for a nanopolish run? It seems like it auto-detects appropriate model based on the metadata in fast5 files, but I wanted to be sure.

Thanks again,
Yongkuk

**Comment by jts** [comment]
Yes, `--scale-events` is to account for read-to-read variation in the signal. With this option, you can compare events across different reads (as long as they come from the same strand of DNA).

Right now nanopolish assumes that Albacore 2.0 (or later) basecalled reads come from R9.4 (or R9.5) pores sequenced at 450bp/s. For older data it will detect the pore type and sequencing speed from the metadata in the fast5 file as you discovered.

Jared

**Comment by yongkuk** [comment]
Thanks again, Jared.
That's a bit odd. My data are from direct RNA sequencing, and the nanopolish results are not so nonsensical.
Looking into etc/models directory, It seems like nanopolish also supports latest RNA model.
Is there a possibility that my data were processed by nanopolish using DNA model? How can I check?

Yongkuk

**Comment by jts** [comment]
Sorry, I misspoke above. It will automatically detect if the run was RNA or DNA. For RNA it uses this model:

https://github.com/nanoporetech/kmer_models/tree/master/r9.4_180mv_70bps_5mer_RNA

For DNA it is as I said above.

**Comment by jts** [comment]
I am closing this issue for now, if you still have problems or questions please feel free to re-open it or open a new issue.
