### ISSUE TITLE
nanopolish call-methylation error 

### ISSUE THREAD

**Issue by yuxuanlan** [jts/nanopolish#278]
While I was running nanopolish call-methylation I got this error:
error: could not parse model string: template_r9.5_450bps_5mer_raw.jsn

I used Albacore 2.0.2 for basecalling. I think the above model was introduced to Albacore recently (it was not there for Albacore 1.6.2 for example). I tried to point the program to use a normal r9.4_450bps model but observed that squiggle signals generated were much smaller than they should be. Has anyone observe the same error? I wonder if nanopore new has a new model that is different to r9.4_180mv_450bps_6mer.

Thanks,
Yuxuan

**Comment by jts** [comment]
Hi,

Are you using the latest version of nanopolish? Did you use the `nanopolish index` or `nanopolish extract` workflow? It should work with `nanopolish index`.

jared

**Comment by Jack2King** [comment]
I execute 'nanopolish' command, it doesn't work, anything wrong or need to install something ? Thanks.

**Comment by jts** [comment]
Hi @Jack2King,

This comment doesn't appear to be related to the issue @yuxuanlan reported. If this is related to the issue you opened #279 then please add more details there.

Jared

**Comment by yuxuanlan** [comment]
Dear Jared, 
it turned out that I was using the wrong command. So I tried nanopolish index with Albacore 2.0.2 reads. Now I have per read pore model parameter a, b and d (from supplementary note Eq1) for both reads on Albacore 1.6.2 and 2.0.2. I notice ds from 2.0.2 are noticeably larger than those from the lower version counterpart, with a minimum value of 1.0 . As a result, I observed the pdf of normalised squiggle for a particular kmer has its peak shifted to the left by 10-15pA. Would the change of basecaller cause this much difference? Or are there something else I missed?
Thanks
Yuxuan

**Comment by yuxuanlan** [comment]
Hi Jared,
I was trying to reproduce Figure 1 of your Nature method 2017 paper using my own data. So far I managed to transform the event mean to remove per-read shift, scale and drift following supplementary note section 1.2.2. There is still a per-read variance associated with event data (with pdf std being scaled), which I observed as mentioned in my previous comment. Could you tell me how you remove this variations to produce Figure 1? Is there a code somewhere in the toolbox?
Thanks,
Yuxuan

**Comment by jts** [comment]
Hi @yuxuanlan,

Sorry for the late reply, I was away at a meeting.

To answer your question from a few days ago, `d` values between 1.6.2 and 2.0.2 should be very similar. Can you describe how you are calculating these? Are you using nanopolish or doing it on your own?

For your second question the code used to make each panel of figure 1 is here: https://github.com/jts/methylation-analysis/blob/master/methylation_plots.R#L148. The calling code to make the whole figure is here:

https://github.com/jts/methylation-analysis/blob/master/methylation_plots.R#L244

Jared

**Comment by yuxuanlan** [comment]
Hi @jts,
Thank you for your quick reply. To answer your first question, I extract pore model from a SquiggleRead object. To be specific, I made a small piece of cpp code which includes this:

ReadDB read_db;
read_db.load(opt::reads_file);
SquiggleRead sr(opt::read_name, read_db);
printf("readname: %s,scale: %.5lf,shift: %.5lf,drift: %.5lf,var: %.5lf",
                opt::read_name.c_str(),
                sr.pore_model[0].scale,
                sr.pore_model[0].shift,
                sr.pore_model[0].drift,
                sr.pore_model[0].var);

I notice there is a nanopolish getmodel functionality, but it seems to output kmer models instead. 
Thanks,
Yuxuan

**Comment by jts** [comment]
Hi,

That code looks fine.

Jared

**Comment by yuxuanlan** [comment]
Hi @jts,
Thank you. I managed to make pdf plots on some kmers. Some closely follow the ONT model and some others are off by a long way. I wonder if it is to do with the choice of data. Were the data use in Figure 1 training data for HMMs, i.e., subjected to the filtering process in Note 1.2?
Many thanks,
Yuxuan Lan

**Comment by jts** [comment]
Hi @yuxuanlan,

Yes, the filtering in 1.2 was used for the data presented in figure 1. 

What data set are you using? If you would like to send me your plots by email I may be able to help figure out what is wrong.

Jared

**Comment by yuxuanlan** [comment]
Hi @jts,
Thank you very much for your offer. Could I send them to this email: jared.simpson@oicr.on.ca ?
Thanks,
Yuxuan

**Comment by jts** [comment]
yes
