### ISSUE TITLE
clang: error: unsupported option '-fopenmp'

### ISSUE THREAD

**Issue by Jack2King** [jts/nanopolish#279]
when execute the "make" command it comes to this error
clang: error: unsupported option '-fopenmp'
anybody helps ?

**Comment by Jack2King** [comment]
![error](https://user-images.githubusercontent.com/13234049/33240252-4353d408-d2ee-11e7-8b35-b9d4e5827412.png)

**Comment by jts** [comment]
Hi,

Clang is not a supported compiler for nanopolish. You'll have to install GCC using homebrew and run `make CXX=g++-7 CC=gcc-7`.

Jared

**Comment by Jack2King** [comment]
OK ，thanks #jst , I will have a try.

**Comment by Jack2King** [comment]
It successed while I did by your help, but then I executed the nanopolish command , it didn't work.

**Comment by jts** [comment]
How did you execute the nanopolish command? You need to give the full path to where you compiled it.

**Comment by Jack2King** [comment]
![git-branch](https://user-images.githubusercontent.com/13234049/33272348-d18ba9cc-d3c4-11e7-9172-306d813ce8f8.jpeg)
Like this.

**Comment by jts** [comment]
Does this work?

```
./nanopolish extract --type template directory/fast5 > reads.fa
```

**Comment by Jack2King** [comment]
Ok, it comes to this:
![prompt](https://user-images.githubusercontent.com/13234049/33272853-75385c72-d3c6-11e7-9060-39c67aa7abe1.jpg)

**Comment by jts** [comment]
Good, it is compiled and functional. Please follow the documentation in the README and let me know if you have problems.

**Comment by jts** [comment]
That directory is the code for the fast5 library that nanopolish uses, it is not a directory of fast5 files. The path you have to give `extract` is to the directory of files that your MinION produced.
