### ISSUE TITLE
The error of "no raw samples found"

### ISSUE THREAD

**Issue by anqi-wang-1** [jts/nanopolish#284]
Hi,

I'm using nanopolish (version 0.8.3) to call methylation. To warm up, I tried it first on the data `ecoli_er2925.MSssI.timp.100215.fast5` in the Nature Methods paper (Simpson, et al. 2017.)

Currently I cannot download Albacore, so I used poretools (version 0.6.0) to extract the reads instead.
`poretools fastq --type 2D ./ecoli_er2925.MSssI.timp.100215.fast5/pass/*fast5 > reads.fastq`

Then I indexed the reads using nanopolish
`nanopolish index -d ./ecoli_er2925.MSssI.timp.100215.fast5/pass reads.fastq`

Align the reads to the reference genome
```
bwa mem -x ont2d -t 8 EC_MG1655/EC_MG1655.fa reads.fastq | samtools sort -o reads.sorted.bam
 | samtools index reads.sorted.bam
```
EC_MG1655 is the directory that stores all indexed files given by bwa. All indexed files have the prefix "EC_MG1655" in their names.

At last, I executed the command
`nanopolish call-methylation -r reads.fastq -g EC_MG1655.fa -b reads.sorted.bam
`

However, I got the error message `Error, no raw samples found`.

Could you please help me fix the problem? Is it a must to use Albacore for basecalling?

Thank you very much.

Anqi

**Comment by jts** [comment]
Hi Anqi,

The problem is that data set is very old now so the fast5 format is out of date. I suggest you try calling methylation on this data set (maybe only chr20) as a start:

https://github.com/nanopore-wgs-consortium/NA12878#fast5-signal-level-files

Jared

**Comment by anqi-wang-1** [comment]
Hi Jared,

Thank you for your answers. I'm now working on the human data.

Currently I cannot download Albacore. I used poretools to extract the reads and found "nanopolish call-methylation" still gave the output. Is it proper to replace Albacore by poretools? Will there be any serious problem on the result?

Thanks.


Anqi

**Comment by jts** [comment]
Hi,

What does the output look like?

Jared

**Comment by anqi-wang-1** [comment]
Hi Jared,

Below are the lines at the beginning of `methylation.csv`.
```
chromosome    start    end    read_name    log_lik_ratio    log_lik_methylated    log_lik_unmethylated    num_calling_strands    num_cpgs
chr1    878390    878390    ab5b4280-ad96-4e97-a962-05f36634f496_Basecall_Alignment_template    -0.13    -103.77    -103.64    1    1    CTGCTCGGCTG
chr1    878455    878455    ab5b4280-ad96-4e97-a962-05f36634f496_Basecall_Alignment_template    -0.16    -120.09    -119.93    1    1    AGAAACGGCAT
chr1    878575    878582    ab5b4280-ad96-4e97-a962-05f36634f496_Basecall_Alignment_template    0.06    -142.31    -142.37    1    2    GAAAGCGGAGCTCGCCTG
```

Although I downloaded the data of chr20, some reads could be mis-aligned to chr1. Does the file look normal?

However, when I ran
`python calculate_methylation_frequency.py -c 2.5 -I methylation.tsv`

I got the message
```
Traceback (most recent call last):
  File "/Shared/Au/awang4/Tools/nanopolish/scripts/calculate_methylation_frequency.py", line 47, in <module>
    num_sites = int(record['num_cpgs'])
TypeError: int() argument must be a string or a number, not 'NoneType'
```

I doubt if the reason was that I performed basecalling using poretools instead of Albacore.

I can send you the entire `methylation.tsv` file through e-mail if necessary. It is only 2.2M.

Thank you very much.


Anqi

**Comment by jts** [comment]
Hi Anqi,

Is it possible the `methylation.tsv` file is truncated?

Jared

**Comment by jts** [comment]
Also, we just posted a complete tutorial for calling methylation today: http://nanopolish.readthedocs.io/en/latest/quickstart_call_methylation.html. You might want to follow the tutorial (it will take 1-2hours) to make sure everything is running correctly.
