### ISSUE TITLE
Nanopolish index error

### ISSUE THREAD

**Issue by jonhultqvist** [jts/nanopolish#287]
Hi,

I have been attempting to use nanopolish index on a 1D nanopore dataset (FLOMIN-107) basecalled using Albacore 2.1.3. The run crashed with a core dump and the error message displayed below. I have not seen anyone report this specific error previously. Any suggestions on what may be causing it?

My command was the following 

`nanopolish index -d /scratch2/jon/MINION_DATA_STORAGE/170829_PCE/reads/ \
/scratch2/jon/MinION/PCE/albacore_basecall_2.0/FASTQ/PCE_MinION_albacore_2.1.3_ALL.fq`

and I got the following error message with a core dump

`
[readdb] num reads: 717143, num reads with path: 714123
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 47086235801600:
  #000: H5O.c line 246 in H5Oopen(): unable to open object
    major: Symbol table
    minor: Can't open object
  #001: H5O.c line 1357 in H5O_open_name(): object not found
    major: Symbol table
    minor: Object not found
  #002: H5Gloc.c line 430 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: H5Gtraverse.c line 755 in H5G_traverse_real(): component not found
    major: Symbol table
    minor: Object not found
terminate called after throwing an instance of 'hdf5_tools::Exception'
  what():  /Raw/Reads//Signal_Pack/params/read_id: error in H5Oopen
/var/spool/gridengine/execd/perun14/job_scripts/3626018: line 9: 35177 Aborted                 (core dumped) nanopolish index.........`

```

**Comment by jts** [comment]
Are you using the latest version of nanopolish? A few weeks ago I changed it to catch and ignore these HDF5 issues.

**Comment by jonhultqvist** [comment]
Thanks for replying so swiftly. I'm on v0.8.4. I will update to the latest committed code and see if that helps.

**Comment by jonhultqvist** [comment]
Okey, I can confirm that it is working now. Seems there was an invalid fast5-file (platform QC-derived) in the directory.

Thanks for the speedy fix.
