### ISSUE TITLE
Issue with event align results

### ISSUE THREAD

**Issue by awjga** [jts/nanopolish#288]
Hi,

Thank you so much for always answering my questions.
I have noticed an issue with the results from eventalign for direct RNA sequencing.
This is the command that I had used with nanopolish 0.8.4:

nanopolish eventalign  --reads all.fastq --bam all.s.bam  --genome reference.fa --t 8 --scale-events > scale.event

I am able to run the command fine, with no error.
However, I had noticed for some of the reads, the reference_kmer and model_kmer are not the same.
The event index seems to be flipped too, it is running in the opposite direction.
I am unsure if the the scaling of the event level mean to the model mean are affected.
For most of the strands there is no issue, it only occurs for a small number of strands.

I have attached the one of the reads that have issue.
[issue.txt](https://github.com/jts/nanopolish/files/1538235/issue.txt)

Thank you so much.

**Comment by jts** [comment]
Hi,

In this case the read matches the reverse complement strand of the reference genome. The `model_kmer` will be the reverse complement of the `ref_kmer` and from the perspective of the reference genome the events are in reverse.

Jared

**Comment by awjga** [comment]
Thank you so much for the clarification!
