### ISSUE TITLE
Nanopolish phase-reads not labelling secondary reads

### ISSUE THREAD

**Issue by scottgigante** [jts/nanopolish#292]
Hi Jared,

I'm not sure if this is by design, but `phase-reads` isn't labelling any reads tagged as secondary. I've run the same data through the following software pipelines:

```
albacore 1.2.2       | albacore 2.1.1
bwa mem 0.7.15-r1140 | minimap2 2.4-r555
nanopolish 0.6.1     | nanopolish 0.8.1
```

 and ended up with about a million reads fewer the second time around. Both versions of albacore have given exactly the same number of reads, but `minimap2` uses secondary instead of supplementary (unmapped reads excluded from the `bwa` run):

```
 % samtools flagstat albacore_1.2.2.bwa_mem.sorted.bam
5263767 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
1487630 + 0 supplementary
5263767 + 0 mapped (100.00%:-nan%)
 % samtools flagstat albacore_2.1.1.minimap2.sorted.bam
5144212 + 0 in total (QC-passed reads + QC-failed reads)
2044605 + 0 secondary
392206 + 0 supplementary
4731203 + 0 mapped (91.97%:-nan%)
```

Running both of these bam files through `nanopolish phase-reads`, I end up with the following:

```
 % samtools flagstat nanopolish_data/albacore_1.2.2.bwa_mem.phased.sorted.bam
3973058 + 0 in total (QC-passed reads + QC-failed reads)
1471684 + 0 supplementary
3973058 + 0 mapped (100.00%:-nan%)
 % samtools flagstat nanopolish_data/albacore_2.1.1.minimap2.phased.sorted.bam
3332775 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
214009 + 0 supplementary
3332775 + 0 mapped (100.00%:-nan%)
```

I've checked (n=1) and alignments labelled as secondary *do* exist in the `minimap2` phasing results - they're just labelled as primary.

**Comment by jts** [comment]
Hi Scott,

I had a brief look at the code and noticed that I'm setting the supplementary bit on all output records:

```
out_record->core.flag = record->core.flag & BAM_FSUPPLEMENTARY;
```

I don't remember why I decided to do this but I'm happy to remove this so the original flag is passed through directly to the output. Is that what you would prefer? 

I've been meaning to overhaul `phase-reads` to smooth out some of the rough bits, if you have other suggestions let me know.

Jared

**Comment by scottgigante** [comment]
Hi Jared,

In my opinion, the best thing to do would be to leave the original bam flags. I don't think I have any other suggestions for `phase-reads`, but thank you for your continued work on the module!

Scott

**Comment by jts** [comment]
I've implemented this change, let me know if the bam flags are still an issue.
