### ISSUE TITLE
error: faidx could not get contig length for contig

### ISSUE THREAD

**Issue by webbchen** [jts/nanopolish#293]
Hi Jared

We're running nanopolish version 0.8.4

 nanopolish variants --ploidy 1 -w "ENA|CM001196|CM001196.1":1-6088797 -t 4 -o /my/path/fungus1.vcf --reads /my/path/other_fungus_albacore_trimmed.fastq --bam /my/path/to/alignments/other_fungus_albacore_to_reference_fungus_sorted.bam --genome /my/path/to/reference/reference_chromosomes/entry1.fasta
(paths and file names anonymised)

I'm trying to call variants with nanopolish and when indexing the reference I'm getting this error:
[fai_load] build FASTA index.
error: faidx could not get contig length for contig ENA|CM001196|CM001196.1

I've deleted the indexing file I had and let nanopolish build a new one and it still fails.
Is there anything I can do?

Kind regards,

A. Webb

**Comment by webbchen** [comment]
Update:
Wondering if the problem is caused by the fasta file being laid out like that:
"
ENA|CM001196|CM001196.1 Mycosphaerella graminicola IPO323 chromosome 1, whole genome shotgun sequence. 
CCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAA
CCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAA
CCCTCACCCTCACCCTCGGTCGTACGGCGTGACAATGTCTCCAGAATCGATTTGGTCTTG
ACGAAAGCAGCGCACATAGCACTTCCGGATGATTTTGTCGCATGCTTTGTCAAACACGAC
GTCCGTAAGTACTAGCTCGTTCGGCCTAGCTTTCGCGCCCGTCTGCTGCTCGCTCTTCCG
CAAGAATTGACGCAGAACGACGCGCCGCTTCTGGGTATCGAACTCGATAATTTGGGCTGG
CTGGAGCCGGTCCTCGTCAAGGTCGTCATTCCATTCGCGGACGAGGACGGTGTCACCAAT
TGCATATTTGCTCCGGCACTCGTCGAATATAGGAACGTCATGCTTGCACTGGCACCTAAA
GTCGCTTGCTTGAATTGCAACGAAGTCGTATGTGTCTTGCTCGTAAACTGTGCGGAACTT
CTGGCGCACAAAGTGTCCTCCCTGCTAATATGGATCCTTGGCATACTAACATACGTCTGC
CTTAAAGCGCGCCTTCGGATACGCGAGAAGTCCAACACGAGGACTCGAGAGAGATACTTC
CGCAAAAACGACAGAGAACACAGATACAACTACTCTGTTATCGACTCCGACAATACAAGC
ATTTCGTAGAACACGAGAGGGCTAACTACGCAAAAGACGATCTCTTTAGCGTCTGGAAAA
CCCGATACGAAATAGCAAGACAACGGGAGATCAATAAGGTACCTAGGAATACAAATAGCT
..."
The indexing seems to stop at the first line break, regardless whether it's a \n only or \n\r

**Comment by jts** [comment]
Hi @webbchen,

Is `ENA|CM001196|CM001196.1` the name of a record in the `--genome` file?

Jared

**Comment by webbchen** [comment]
Hi Jared
It is the chromosome's name in the reference. I seemed to have found what's been tripping up the indexing: It didn't like carriage returns in the reference fasta file. 
Once I replaced them with just line breaks it went ahead just fine.
Many thanks for the quick reply, though!

A. Webb

**Comment by jts** [comment]
Great, thanks for letting me know.

jared
