### ISSUE TITLE
General question about methylation detection

### ISSUE THREAD

**Issue by ickou** [jts/nanopolish#296]
Hi,

I don't understand if it is necessary to sequence the two control samples (PCR-amplified and M.SssI treated) to use nanopolish for methylation detection?
Does nanopolish detect the flowcell version to adapt model?
How many model model contains nanopolish for methylation detection?
I need to have an idea about experimental design: 2 MinION flowcells by sample for mouse? steps of learning with two control samples or not?
Thank you for your help
ickou

**Comment by jts** [comment]
Hi @ickou,

> I don't understand if it is necessary to sequence the two control samples (PCR-amplified and M.SssI treated) to use nanopolish for methylation detection?

`nanopolish call-methylation` will call 5-mC in a CpG context from a single genomic DNA sample. See the tutorial here for a walk-through of how this works:

http://nanopolish.readthedocs.io/en/latest/quickstart_call_methylation.html

> Does nanopolish detect the flowcell version to adapt model?

Yes, it will detect flowcell and pore type and select the appropriate model (the characteristics of R9.4 and R9.5 are very similar so we use the same model for both right now).

> How many model model contains nanopolish for methylation detection?

Right now it supports R7.3, R9, R9.4 and R9.5. As noted above the R9.4 and R9.5 models are the same. The other models are only to support older data and won't be used for recent data.

> I need to have an idea about experimental design: 2 MinION flowcells by sample for mouse? steps of learning with two control samples or not?

If you only want to detect 5-mC at CpG sites, you just need to sequence your samples. You don't need to run controls unless you want to confirm the program is working correctly. 

Jared

**Comment by ickou** [comment]
Hi Jared,

Thank you for your answer.
Could you advise me for the mean depth of sequencing for methylation detection?

Best regards,

Ickou

**Comment by jts** [comment]
I don't have a strong recommendation but perhaps at least 20x?

Jared
