### ISSUE TITLE
nanopolish_makerange.py   parallel: command not found

### ISSUE THREAD

**Issue by chenshixuan** [jts/nanopolish#297]
HELLO:
      when I used nanopolish_makerange.py computing a new consensus sequence for a draft assembly ,the command line is python nanopolish_makerange.py draft.fa | parallel --results nanopolish.results -P 8 \ ,  parallel: command not found ,Could you help me to solve the eorror? thank you very much.

**Comment by jts** [comment]
Hi,

You need to install GNU parallel: https://www.gnu.org/software/parallel/

Jared

**Comment by moutusee** [comment]
Hi
I have the same problem. I tried to install the GNU parallel as jts suggested. I can't install it. I am using Ubuntu in virtual box. can you help me?

**Comment by jts** [comment]
What problem do you have installing it?

Jared

**Comment by moutusee** [comment]
I am giving this command to install it: sudo apt-get install  http://ftp.gnu.org/gnu/parallel/ 
But getting the following error:
Reading package lists... Error!
E: flAbsPath on /var/lib/dpkg/status failed - realpath (2: No such file or directory)
E: Could not open file  - open (2: No such file or directory)
E: Problem opening 
E: The package lists or status file could not be parsed or opened.

**Comment by jts** [comment]
Please see my response in the new issue you just opened. Lets try to keep the discussion in one place.
