### ISSUE TITLE
Nanopolish merge missing segments

### ISSUE THREAD

**Issue by jonhultqvist** [jts/nanopolish#300]
Hi,

I have had two independent issues with nanopolish_merge.py flagging missing segments for a certain sequence. All the requisite files for merging seems to be present, but the script fails to identify some segments and also looks for ones which are out of range of the sequence. Oddly enough the failure to identify the missing segments both involve the DNA segment called Seq_99 in respective genome assembly. I show both examples below. Any idea what could be causing this problem and how I could adress it?

Cheers
Jon

Genome 1: Contig size is 213690 bp

```
/scratch3/jon/MinION/NANOPOLISH@perun4> python /scratch2/software/nanopolish-git-dec7-2017/scripts/nanopolish_merge.py polished.*.fa > Abruijn_total_3000_polished_1.NanoP1x.EUK.fasta
error: segment starting at Seq_99:100000 is missing
error: segment starting at Seq_99:250000 is missing
error: some segments are missing, could not merge contig Seq_99

/scratch3/jon/MinION/NANOPOLISH@perun4> ls -lthr *.Seq_99*
-rw-r--r-- 1 jon 14K Dec 14 20:55 polished.Seq_99:200000-213690.fa
-rw-r--r-- 1 jon 50K Dec 14 22:09 polished.Seq_99:50000-100200.fa
-rw-r--r-- 1 jon 49K Dec 14 22:13 polished.Seq_99:0-50200.fa
-rw-r--r-- 1 jon 49K Dec 14 23:05 polished.Seq_99:100000-150200.fa
-rw-r--r-- 1 jon 49K Dec 15 00:32 polished.Seq_99:150000-200200.fa
```
Genome 2: Contig size is 163956 bp.

```
/scratch3/jon/MinION/RCL/NANOPOLISH@perun13> python /scratch2/software/nanopolish-git-dec7-2017/scripts/nanopolish_merge.py polished.*.fa > RCL_only_AB_assembly_P2.corr2.NanoP1x.fa
error: segment starting at Seq_99:200000 is missing
error: some segments are missing, could not merge contig Seq_99
/scratch3/jon/MinION/RCL/NANOPOLISH@perun13> ls -lthr *.Seq_99*
-rw-r--r-- 1 jon roger 14K Dec 14 07:17 polished.Seq_99:150000-163956.fa
-rw-r--r-- 1 jon roger 50K Dec 14 08:38 polished.Seq_99:0-50200.fa
-rw-r--r-- 1 jon roger 50K Dec 14 09:35 polished.Seq_99:50000-100200.fa
-rw-r--r-- 1 jon roger 50K Dec 14 09:44 polished.Seq_99:100000-150200.fa
```

**Comment by jts** [comment]
Thanks, I think this is a bug in the merging script. I will try to fix it today.

Jared

**Comment by jonhultqvist** [comment]
Great, thank you! If it helps you narrow down the bug I can successfully join the pieces of the above mentioned sequence by:

` python /scratch2/software/nanopolish-git-dec7-2017/scripts/nanopolish_merge.py polished.Seq_99*.fa > RCL_only_AB_assembly_P2.corr2.NanoP1x.fa`

It just appears to fail when trying to do it with all queries in sequence. If I remove the Seq_99 pieces, it fails on Seq_98 instead with a similar issue. Again, all the pieces are accounted for.

```
/scratch3/jon/MinION/RCL/NANOPOLISH/POLISHED_SEGMENTS@perun13> python /scratch2/software/nanopolish-git-dec7-2017/scripts/nanopolish_merge.py polished.*.fa > RCL_only_AB_assembly_P2.corr2.NanoP1x.fa
error: segment starting at Seq_98:200000 is missing
error: some segments are missing, could not merge contig Seq_98
/scratch3/jon/MinION/RCL/NANOPOLISH/POLISHED_SEGMENTS@perun13> ls -lthr *Seq_98*
-rw-r--r-- 1 jon roger  50K Dec 15 14:03 polished.Seq_98:0-50200.fa
-rw-r--r-- 1 jon roger 2.8K Dec 15 14:03 polished.Seq_98:100000-102753.fa
-rw-r--r-- 1 jon roger  50K Dec 15 14:03 polished.Seq_98:50000-100200.fa
```

**Comment by jts** [comment]
If you can send the polished segments (via dropbox or google drive?) it would help me look into it.

jared

**Comment by jonhultqvist** [comment]
No problem, I have sent you an e-mail with a Dropbox-link.

**Comment by jts** [comment]
The bug was in the output message, it would print the wrong contig name. It now gives the correct error message:

```
error: segment starting at Seq_1:200000 is missing
error: some segments are missing, could not merge contig Seq_1
```

Thanks for the test data, I was able to find the problem quickly.

**Comment by jonhultqvist** [comment]
Thank you very much Jared!

While where on the topic, what is your recommendation to getting those missing segments polished and incorporated into the assembly?

- Rerunning nanopolish on only those segments or contigs?
- Joining the polished and non-polished segments and leave polishing of those segments to illumina reads?

**Comment by jts** [comment]
My preference is to re-run that segment and if it crashes again then follow [these instructions](http://nanopolish.readthedocs.io/en/latest/debug.html) to send me data for the segment so I can fix it :)

**Comment by jonhultqvist** [comment]
Okey, thank you I will try that.

**Comment by caonetto** [comment]
Hi Jared,
How do we specifically repolish just one segment?

Thanks.

Cris.

**Comment by jts** [comment]
Here's an example of how to repolish a segment: 

https://github.com/jts/nanopolish/issues/246#issuecomment-336529098

You'll have to change the coordinates (`utg000239l:100000-150200`) to the coordinates that you want to re-polish.

Jared
