### ISSUE TITLE
nanopolish_makerange.py error a genome file is expected

### ISSUE THREAD

**Issue by Sofie8** [jts/nanopolish#305]
Hi, 

I am using Nanopolish to improve the draft genome assembly of Rhizobium. I made the draft assembly using CANU on MinIon reads, and I am following this explanation: http://nanopolish.readthedocs.io/en/latest/quickstart_consensus.html

I ran into error in the step of making 50 kb fragments to polish, stating 'error a genome file is expected'. Parallel is not working either, error in line 4990?, so I turned it off.

python nanopolish_makerange.py /media/sf_shared_folder/Fran/draft.fasta --results /media/sf_shared_folder/Fran/nanopolish.results \
nanopolish variants --consensus /media/sf_shared_folder/Fran/polished.{1}.fa \
-w {1} \
-r /media/sf_shared_folder/Fran/reads.fastq \
-b /media/sf_shared_folder/Fran/reads.sorted.bam \
-g /media/sf_shared_folder/Fran/draft.fasta \
-t 4 --min-candidate-frequency 0.1

My draft.fasta file has 10 contigs of variable length. Is this perhaps causing the error? I attached the file draft.fasta file.
[draft.zip](https://github.com/jts/nanopolish/files/1592459/draft.zip)

**Comment by jts** [comment]
Hi,

You can't remove `parallel` from the command, it is essential. The "line 4990" error probably means your original command was incorrect in some way. Please carefully try the command with `parallel` again and if it does not work feel free to send me the full command for help.

Jared

**Comment by Sofie8** [comment]
Hi Jared,

Ok, I solved it! I fixed parallel and then the problem with error a genome file is expected disappeared. The error in parallel seemed to be related to permissions in writing to the output folder. It doesn't work writing to a shared_folder, see below. But when I output to my home directory it runs perfect!
This can maybe also be the answer for this issue:
#https://github.com/jts/nanopolish/issues/129

python nanopolish_makerange.py /media/sf_shared_folder/Fran/draft.fasta | parallel --results /media/sf_shared_folder/Fran/nanopolish.results -P 8 \
> nanopolish variants --consensus /media/sf_shared_folder/Fran/polished.{1}.fa \
> -w {1} \
> -r /media/sf_shared_folder/Fran/reads.fastq \
> -b /media/sf_shared_folder/Fran/reads.sorted.bam \
> -g /media/sf_shared_folder/Fran/draft.fasta \
> -t 4 --min-candidate-frequency 0.1
mkdir /media/sf_shared_folder/Fran/nanopolish.results/1/tig00000001:0-50200: Protocol error at /usr/bin/parallel line 4990.

Thanks,
Sofie

**Comment by jts** [comment]
Hi Sofie,

Is `nanopolish` on your `PATH`? If not you might need to give the full path to the executable (`/path/to/nanopolish variants`) in the command.

Jared

**Comment by Sofie8** [comment]
Hi Jared,

Yes, true I added the path to nanopolish variants, but still this error in line 4990 persists.
I only managed to solve this error by not outputting to my shared_folder but to home, perhaps parallel and mkdir in a shared_folder doesn't have all the permissions to do so.

Sofie

**Comment by jts** [comment]
Can you send me the full command line that fails with the error?

**Comment by jts** [comment]
Please reopen if this is still an issue.

**Comment by Sofie8** [comment]
Thanks Jared, it is solved in the meantime.
Sofie

2018-02-05 21:13 GMT+01:00 Jared Simpson <notifications@github.com>:
