### ISSUE TITLE
nanopolish index, cannot open .fastq for read

### ISSUE THREAD

**Issue by YaoLi3** [jts/nanopolish#306]
This is the command:
 nanopolish index -d basecall_pass/sdfag_20161028_FNFAB42704_MN16454_sequencing_run_Chip103_Genomic_R9_4_450bps_tune_66010_ch391_read1283_strand.fast5 outread.fastq

This is the error:
error: could not open outread.fastq for read

This error keeps showing up, and I don't know why nor how to deal with it.
If I use nanopolish extract for the same file, it works. But my ALbacore version is later than 2.0, so I assume I need to use index command? What's the difference between the results of these two commands?

Thanks in advance!

**Comment by jts** [comment]
Hi,

`nanopolish index` and `nanopolish extract` have different usage. With `nanopolish index` you need to give it a fastq file (from albacore) and the path to the fast5 files. An example is here:

http://nanopolish.readthedocs.io/en/latest/quickstart_call_methylation.html#data-preprocessing

Jared
