### ISSUE TITLE
Problems to get polished.fa

### ISSUE THREAD

**Issue by Lau16** [jts/nanopolish#307]
Hi Jared, I am trying for the first time to use Nanopolish to obtain a new consensus sequence from a draft assembly. I followed all the step posted  at the tutorial of 2Kb E. coli fragment.
When I tried to run the consensus algorithm  I didn't get the output file "polished.fa"
I run the following script:
laura@ubuntu-srv:/bio/work/tmp/ecoli_2kb_region$ nanopolish variants -consensus=polished.fa -w "tig00000001:200000-202000" -r reads.fasta -b reads.sorted.bam -g draft.fa
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
TODO: train model
TODO: filter data
error: no path associated with read fa9ad683-35c5-4dad-a3af-de7a86b1ffa8
Please could you check if the script is OK?
What does mean :"variants: too many arguments"
Waiting for your answers
Thanks
Laura

**Comment by jts** [comment]
Hi Laura,

I think your version of nanopolish is out of date. Can you run `nanopolish --version` and send the output?

thanks,
Jared

**Comment by Lau16** [comment]
Hi Jared,

Here you have the information:
man nanopolish  ->  0.4.0  January 2016    NANOPOLISH(1)

but the command "nanopolish --version"  does not get output.....
Waiting for your answer,
Many thanks
Laura

**Comment by jts** [comment]
Hi Laura,

Version 0.4 is very old, could you update to the latest version (0.8.5)?

Thanks,
Jared

**Comment by Lau16** [comment]
[nanopolish_commands.txt 1.txt](https://github.com/jts/nanopolish/files/1714057/nanopolish_commands.txt.1.txt)
Hi Jared, thank you for your email, we've installed the updated version.
I'm still trying to do a new consensus sequence for a draft  assembly of a bacteria (Acc) .
I encountered with some problems while running the algorithms:

# Align the basecalled reads to the draft sequence
bwa mem -x ont2d -t 8 draft.fa reads.fa | samtools sort -o reads.sorted.bam -T reads.tmp -
samtools index reads.sorted.bam
It only works  when I run each command separately.
I had the same problem to run in parallel the genome in 50 kb blocks for polishing. 
I run: python /bio/nanopolish/scripts/nanopolish_makerange.py acc6.contigs.fasta > makerange_out
The obtained files are in the attached notepad.
What does mean: parallel --results nanopolish.results -P 8  ?
I attached a notepad with the source from where I took the data for the different steps
Thank for your help.
[nanopolish_commands.txt 1.txt](https://github.com/jts/nanopolish/files/1714056/nanopolish_commands.txt.1.txt)
