### ISSUE TITLE
Second round of nanopolishing

### ISSUE THREAD

**Issue by rmnorris** [jts/nanopolish#31]
I would like to do 'two rounds' of polishing, but seem to get errors when I try. The most recent code I tried was:

>cp $DIR/2d.fa $DIR/nanopolish2/reads2.fa
>cp $DIR/polished.fa $DIR/nanopolish2/polished.fa
>make -f ~/apps/nanopolish/scripts/consensus.make READS=$DIR/nanopolish2/reads2.fa ASSEMBLY=$DIR/nanopolish2/polished.fa
>python ~/apps/nanopolish/scripts/nanopolish_makerange.py $DIR/nanopolish2/polished.fa | parallel --plain --results $DIR/nanopolish2/nanopolish_results -P 4 ~/apps/nanopolish/nanopolish consensus -o $DIR/nanopolish2/nanopolish_results/nanopolish.{1}.fa -w {1} --r $DIR/nanopolish2/reads2.pp.fa -b $DIR/nanopolish2/reads2.pp.sorted.bam -g $DIR/nanopolish2/polished.fa -t 4
>python ~/apps/nanopolish/scripts/nanopolish_merge.py $DIR/nanopolish2/polished.fa $DIR/nanopolish2/nanopolish_results/nanopolish.*.fa > $DIR/polished2.fa

This runs until the samtools index step, at which point I get:
>samtools index blah/nanopolish2/reads2.pp.sorted.bam
>[fai_load] build FASTA index.
>[fai_build_core] different line length in sequence 'scf7180000000030'.

(and this error repeats for the intervals). What intermediate step have I missed to cause this error?

**Comment by jts** [comment]
It seems there is a problem with the formatting of polished.fa. Can you check if there are any blank lines or lines that are otherwise formatted strangely?

**Comment by rmnorris** [comment]
That's exactly it! Thanks. It looks like the polished.fa (output by nanopolish_merge.py) has a blank like between each fasta entry. It works now that I have removed them.

**Comment by jts** [comment]
Glad to hear that is the problem but nanopolish_merge.py shouldn't be putting blank lines in between records. Have you seen this behaviour before?

**Comment by rmnorris** [comment]
Actually yes, it seems to have done it to all the samples I've polished so far (just checked all 3).

**Comment by jts** [comment]
This should be fixed now (c1df79155) - can you try it out?

**Comment by rmnorris** [comment]
Great! No blank lines now!
