### ISSUE TITLE
Problems of the download example dataset

### ISSUE THREAD

**Issue by BurinkiWU** [jts/nanopolish#310]
When I tar the dataset - methylation_example.tar.gz , the terminal showed that  
tar: skipping to next header 
tar: exiting with failure status due to previous errors
Does anyone meet this problem?
How could I fix it? 
And also, are there albacore_output.fastq : the subset of the basecalled reads, reference.fasta : the chromsome 20 reference sequence and fast5_files/ : a directory containing signal-level FAST5 files in the tar.gz files? 
Thanks a lot!

**Comment by jts** [comment]
Hi,

I just confirmed the following two commands from the documentation works for me:

```
wget http://s3.climb.ac.uk/nanopolish_tutorial/methylation_example.tar.gz
tar -xvf methylation_example.tar.gz
```

Can you try again?

Jared

**Comment by BurinkiWU** [comment]
Thanks, bro! 
It is all right now.

**Comment by jts** [comment]
Great!
