### ISSUE TITLE
problems accessing fast5 files

### ISSUE THREAD

**Issue by stuartastbury** [jts/nanopolish#311]
Hello Jared,
We're just getting going with adding nanopolish to our workflow - the ultimate aim being to use the phase-reads tool to give us an idea of variation in viral sequence data.

So far I've sequenced virus from 12 patients using the sqk-lwb001 kit for barcoding. Basecalling was done through minKNOW (v1.10.23). After that I extracted fastq with poretools and used porechop to get the demultiplexed fastqs - nanopolish (0.8.5) seems to happily index these when I point the binned fastqs at the original fast5 directory but that's about as far as I get. I get a "[warning] fast5 file is unreadable and will be skipped" error for every fast5.

So my questions are - am I doing something stupid in the above that might upset nanopolish in some way? Am I incorrect in using the fast5s straight from minKNOW and will need to (as seems to often be the case) re-basecall with albacore? I'm pretty new to this so unsure if minKNOW is keeping all the raw signal data required, but delving into the fast5s with hdfview suggests there is something there...

Many thanks for any help you can provide!!
Stuart

**Comment by jts** [comment]
Hi,

Nanopolish requires the use of albacore but I don't think this explains why your fast5s are unreadable. Can you paste the final few output lines from `nanopolish index`?

Jared

**Comment by stuartastbury** [comment]
I just get the one output:

[readdb] num reads: 26014, num reads with path: 26014

**Comment by jts** [comment]
Hmm, that implies that it was able to read your fast5 files (at least, it was able to read many of them). Do the subsequent steps work?

Jared

**Comment by stuartastbury** [comment]
Hi Jared,
Now I've tried it with some Albacore reads everything is working happily, so this issue was simply my own bumbling around. Thanks for your help (and indeed all your help in other threads too, it's really useful!!)
Stuart

**Comment by jts** [comment]
Ok, glad to hear it is working now.

Jared
