### ISSUE TITLE
Lower case letters in reference

### ISSUE THREAD

**Issue by proukakis** [jts/nanopolish#312]
We have had a strange problem when using hg19 from UCSC to align a long amplicon for SNP calling by v0.6-dev. A lot of t>T or other small>capital letter mutations were called- presumably the repeat-masked regions which are in lower case? We can ignore these, but nanopolish missed some very clear SNPs. When we realigned to an all-capital sequence, the problem disappeared, and the SNPs were called.

So i guess you should avoid using a sequence with lower case letters, I think this was mentioned before in relation to eventalign. perhaps this can be fixed in the future

thanks
christos

**Comment by jts** [comment]
Thanks, you're right this should be fixed.

**Comment by jts** [comment]
This is now fixed, thanks for the report.
