### ISSUE TITLE
new assertion error

### ISSUE THREAD

**Issue by pwkooij** [jts/nanopolish#313]
After the recent updates I have been successfully polishing assemblies, but for one data set I now get a new "assertion failed" error:

`nanopolish: src/hmm/nanopolish_profile_hmm_r9.inl:271: float profile_hmm_fill_generic_r9(const HMMInputSequence&, const HMMInputData&, uint32_t, uint32_t, ProfileHMMOutput&) [with ProfileHMMOutput = ProfileHMMForwardOutputR9; uint32_t = unsigned int]: Assertion '(data.rc && data.event_stride == -1) || (!data.rc && data.event_stride == 1)' failed.`

I extracted the specific region that leads to the problem (15GB) which you can find [here](http://pwkooij.com/reads_subset.tar.gz). It will take a bit to upload because of the size.

Please let me know when you downloaded it, so I can remove it.

**Comment by jts** [comment]
Hi,

I downloaded the data set but got an error when untarring it. Can you confirm the .tar.gz is OK? 

Jared

**Comment by pwkooij** [comment]
Hi Jared,

Apoligies for that, I had issues uploading it at work, so currently uploading it from home (which will take a while...). It currently says 4 hrs to go, but possibly longer. It's almost midnight here, but will send a message tomorrow morning if it is all transfered. The file is 15gb...

Cheers
Pepijn

**Comment by pwkooij** [comment]
It's fully uploaded now. Please let me know when you've got it so I can remove it

**Comment by jts** [comment]
Thanks, I have the file now.

Jared

**Comment by jts** [comment]
Fixed in daf9d28. The problem was caused by a read with a very poor alignment to your assembly:

```
bf23b34d-261d-4452-afbd-77b7e4f7525e    2048    scaffold00008   500241  27      2H43M3665H      *       0       0       AGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```

Only 43bp out of ~3700bp aligned to the contig. I don't think reads with such poor alignments should be used, but the assertion is now fixed. Out of curiosity what aligner did you use?

Thanks for the test data.

**Comment by pwkooij** [comment]
Thanks, Jared. Will ask the admin to deploy the fix and rerun.

Regarding the aligner/assembler, I've been juggling/trying some things. This is from a combination of Canu>Nanopolish>Redundans. However I realised that Redundans uses the raw reads again, so wanted to run the results through Nanopolish to improve it again. 
For one of my other datasets, this worked perfect, but this particular dataset ran into problems.

**Comment by jts** [comment]
What aligner did you run between canu and nanopolish?

**Comment by pwkooij** [comment]
I used bwa as suggested in the readme. The version we have is 0.7.15-r1140. Our samtools version is 1.4.1 (using htslib 1.5)

**Comment by jts** [comment]
Ok, interesting. Perhaps I should ignore supplemental alignments (flag `2048`) during polishing.

**Comment by pwkooij** [comment]
It worked, thanks for the fix!
