### ISSUE TITLE
Problem of basecalled the reads

### ISSUE THREAD

**Issue by BurinkiWU** [jts/nanopolish#314]
We can get a pass/ file which contain *.fast5 files inside after doing nanopore test. 
When I want to use this command: 
read_fast5_basecaller.py -c r94_450bps_linear.cfg -t 8 -i pass -s basecalled/ -o fastq 
I get nothing from the output file -- basecalled/workspace/pass/*.fastq and no fastq files in bascalled/workspace/pass/*.fastq inside. How could I fix it ？

**Comment by jts** [comment]
Hi @BurinkiWU,

`read_fast5_basecaller.py` is part of albacore, which is developed by Oxford Nanopore, not me. You'll have to ask them for help with this question.

Jared

**Comment by BurinkiWU** [comment]
Thx!

**Comment by zifeng8824** [comment]
> 
> 
> Thx!

can  you solve the problem?
