### ISSUE TITLE
Segments missing sometimes

### ISSUE THREAD

**Issue by stweebs** [jts/nanopolish#317]
Hi,

I pulled the most recent version of nanopolish (on Jan. 8) and have noticed that on some polishing runs I get the following error:

error: segment starting at tig00000001:100000 is missing
error: some segments are missing, could not merge contig tig00000001

Checking the output files, these segments are actually missing and the final merged fasta file is empty, however, if I rerun the exact same command without changing anything, nanopolish will output all the files and merge everything correctly without error. Other times it will finish without error on the first run. 

As far as I can tell, the error is happening during the nanopolish_makerange command (following the example on the main page for computing a new consensus sequence for a draft assembly) since I have to start from that command when rerunning the failed jobs. Any idea what might be causing this?

Cheers,
Stephen

**Comment by jts** [comment]
Hi,

Sorry for the slow response to this issue. It is unusual for a segment to fail to polish and then work when re-run. This suggests to me that there might have been a memory issue. If you are able to isolate a situation where a polishing step fails I'd be happy to take a closer look.

jared
