### ISSUE TITLE
The problem of nanopolish call-methylation

### ISSUE THREAD

**Issue by BurinkiWU** [jts/nanopolish#319]
I follow the steps of Quickstart - calling methylation with nanopolish and I have done well job from Data preprocessing to Aligning reads to the reference genome, but when it comes to Calling methylation, I met the following problems. Could you fix it for me? 

Thx.
Ziqi

wzq@profxia-SUSTC-309:~/Nanopore_db/coliform_1_downloads$ /home/wzq/nanopolish/nanopolish call-methylation -t 8 -r 2D.fq -b 2D_CP_output.sorted.bam -g CP000034_reference.fasta > 2D_CP_methylation.tsv
[fai_load] build FASTA index.
[fai_build_core] different line length in sequence 'reference'.
[warning] fast5 file is unreadable and will be skipped: coliform-1_downloads/pass/GQY2VBX_20160530_FNFAD00024_MN16589_sequencing_run_Coliform_1_76319_ch205_read403_strand.fast5
[warning] fast5 file is unreadable and will be skipped: coliform-1_downloads/pass/GQY2VBX_20160530_FNFAD00024_MN16589_sequencing_run_Coliform_1_76319_ch192_read446_strand.fast5
[warning] fast5 file is unreadable and will be skipped: coliform-1_downloads/pass/GQY2VBX_20160530_FNFAD00024_MN16589_sequencing_run_Coliform_1_76319_ch156_read941_strand.fast5
[warning] fast5 file is unreadable and will be skipped: coliform-1_downloads/pass/GQY2VBX_20160530_FNFAD00024_MN16589_sequencing_run_Coliform_1_76319_ch38_read469_strand.fast5
[warning] fast5 file is unreadable and will be skipped: coliform-1_downloads/pass/GQY2VBX_20160530_FNFAD00024_MN16589_sequencing_run_Coliform_1_76319_ch184_read964_strand.fast5
[warning] fast5 file is unreadable and will be skipped: coliform-1_downloads/pass/GQY2VBX_20160530_FNFAD00024_MN16589_sequencing_run_Coliform_1_76319_ch156_read941_strand.fast5
[warning] fast5 file is unreadable and will be skipped: coliform-1_downloads/pass/GQY2VBX_20160530_FNFAD00024_MN16589_sequencing_run_Coliform_1_76319_ch38_read469_strand.fast5
[warning] fast5 file is unreadable and will be skipped: coliform-1_downloads/pass/GQY2VBX_20160530_FNFAD00024_MN16589_sequencing_run_Coliform_1_76319_ch363_read172_strand.fast5
[warning] fast5 file is unreadable and will be skipped: coliform-1_downloads/pass/GQY2VBX_20160530_FNFAD00024_MN16589_sequencing_run_Coliform_1_76319_ch245_read401_strand.fast5
[warning] fast5 file is unreadable and will be skipped: coliform-1_downloads/pass/GQY2VBX_20160530_FNFAD00024_MN16589_sequencing_run_Coliform_1_76319_ch346_read87_strand.fast5
[warning] fast5 file is unreadable and will be skipped: coliform-1_downloads/pass/GQY2VBX_20160530_FNFAD00024_MN16589_sequencing_run_Coliform_1_76319_ch156_read717_strand.fast5
[warning] fast5 file is unreadable and will be skipped: coliform-1_downloads/pass/GQY2VBX_20160530_FNFAD00024_MN16589_sequencing_run_Coliform_1_76319_ch322_read486_strand.fast5
[warning] fast5 file is unreadable and will be skipped: coliform-1_downloads/pass/GQY2VBX_20160530_FNFAD00024_MN16589_sequencing_run_Coliform_1_76319_ch512_read725_strand.fast5
[warning] fast5 file is unreadable and will be skipped: coliform-1_downloads/pass/GQY2VBX_20160530_FNFAD00024_MN16589_sequencing_run_Coliform_1_76319_ch327_read1071_strand.fast5
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140113877186304:
  #000: H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 990 in H5F_open(): unable to open file: time = Fri Jan 26 12:48:30 2018
, name = 'coliform-1_downloads/pass/GQY2VBX_20160530_FNFAD00024_MN16589_sequencing_run_Coliform_1_76319_ch324_read786_strand.fast5', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 992 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: H5FDsec2.c line 343 in H5FD_sec2_open(): unable to open file: name = 'coliform-1_downloads/pass/GQY2VBX_20160530_FNFAD00024_MN16589_sequencing_run_Coliform_1_76319_ch324_read786_strand.fast5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
[warning] fast5 file is unreadable and will be skipped: coliform-1_downloads/pass/GQY2VBX_20160530_FNFAD00024_MN16589_sequencing_run_Coliform_1_76319_ch324_read786_strand.fast5
[warning] fast5 file is unreadable and will be skipped: coliform-1_downloads/pass/GQY2VBX_20160530_FNFAD00024_MN16589_sequencing_run_Coliform_1_76319_ch2_read1095_strand.fast5
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140113877186304:

**Comment by jts** [comment]
Hi,

The warnings suggest that your fast5 files are not readable from the current working directory. You'll have to check the paths and permissions are set correctly.

Jared
