### ISSUE TITLE
nanopolish on direct RNA kit data fails at alphabet assertion

### ISSUE THREAD

**Issue by RaverJay** [jts/nanopolish#321]
Hey,
trying to polish a draft genome with direct RNA data.

using:
`nanopolish variants --consensus polished_longest.fa --fix-homopolymers -t 8 --max-rounds=5 --reads /path/to/reads.dna.fq --bam reads.bam --genome draft.fa > polished.vcf`

fails with:
`nanopolish: src/hmm/nanopolish_profile_hmm.cpp:36: float profile_hmm_score_set(const std::vector<HMMInputSequence>&, const HMMInputData&, uint32_t): Assertion 'std::string(data.pore_model->pmalphabet->get_name()) == "nucleotide"' failed.
Aborted`

Basecalled reads and draft reference are DNA right now, but I also tried keeping everything with Us instead of Ts, but that didn't help either.
Any idea?

**Comment by jts** [comment]
Hi,

Nanopolish currently doesn't support variant calling from direct RNA data. I plan to add this as a feature eventually but it won't be ready for awhile.

Jared

**Comment by phiweger** [comment]
Can you polish direct RNA seq data, as hinted at in issue #237? I.e. no variant calling but consensus correction?

Thank you,
Adrian

**Comment by jts** [comment]
`nanopolish eventalign` (which aligns events to a reference genome) works with RNA but the other modules (consensus/variant calling) don't yet.

**Comment by RaverJay** [comment]
Alright thanks!
