### ISSUE TITLE
Eventalign on direct RNA reads fails when using `--samples` flag

### ISSUE THREAD

**Issue by paultsw** [jts/nanopolish#322]
When running nanopolish eventalign on direct RNA data, including the `--samples` flag raises an error:
```
$ nanopolish eventalign --reads=reads.fastq --bam=reads.sorted.bam \
     --genome=ref.fa --print-read-names --samples
nanopolish: src/nanopolish_squiggle_read.cpp:1115: std::vector<float> \
    SquiggleRead::get_scaled_samples_for_event(size_t, size_t) const: \
    Assertion `curr_sample_time >= (this->sample_start_time / this->sample_rate)' failed.
Aborted
```

**Comment by pabloacera** [comment]
I just had this same issue
` nanopolish eventalign --reads ../fastq/sythetic.fastq --genome ../ligated_oligo.fa --bam ../alignment/minimap_filtered.bam --samples  > eventalign.txt
terminate called without an active exception
Aborted (core dumped)`
