### ISSUE TITLE
question on which reads to index -- before or after postprocessing

### ISSUE THREAD

**Issue by phiweger** [jts/nanopolish#324]
When postprocessing reads e.g. using Filtlong or Porechop, does one need to `nanopolish index` the reads before postprocessing (i.e. the Albacore output) or after?

Thank you.

**Comment by jts** [comment]
You should run it with the reads after post-processing. The read sequences you give to `index` need to be exactly the same as whatever is in the bam file and fasta/fastq you use in the subsequent steps (like `variants`).

**Comment by phiweger** [comment]
Thank you for clarifying this.
