### ISSUE TITLE
confusion regarding nanopolish eventalign models

### ISSUE THREAD

**Issue by phiweger** [jts/nanopolish#325]
I came accross [this](http://porecamp.github.io/2016/tutorials/mappingtute.html) Porecamp tutorial or [this](https://github.com/zibraproject/zika-pipeline/blob/master/scripts/go_single_sample_r94.sh) part of the Zibra pipeline, the code goes straight into the eventalign step, w/o a prior `nanopolish index`. However, it specifies a model with `--models-fofn`.

I think I lack an understanding of how to generally go about this. The documentation says 

1. nanopolish index
2. nanopolish variants

What is eventalign used for, practically speaking? And what is the role of the models one can specify and where can they be found?

Sorry if this is in the documentation, I really looked but did not find an answer.

**Comment by jts** [comment]
Hi @phiweger,

That porecamp tutorial is now quite out of date. The `eventalign` step can be skipped and you don't need to provide the `-e Ebola2D.eventalign.bam` file. 

Jared

**Comment by phiweger** [comment]
Thank you!
