### ISSUE TITLE
installation issue on Mac - gcc related

### ISSUE THREAD

**Issue by dbobr** [jts/nanopolish#326]
Hello,

I am having a bit of an issue installing nanopolish on my Mac and I believe it's because of gcc4.8 issues on newer macOS

Installing with gcc4.8 (4.8.5) results in error messages:

`error: ambiguous instructions require an explicit suffix (could be 'fisttps', or 'fisttpl')`

I have tried installing nanopolish with newer gcc versions with no luck

Installing with gcc7 (7.3.0) results in error messages:

```
H5Eprivate.h:42:4: note: in expansion of macro 'HERROR'
    HERROR(maj, min, __VA_ARGS__);           \
    ^~~~~~
```
and a whole lot of various other h5, Eigen, etc issues during make

Installation concludes with nothing useful:
```
g++-7 -o src/test/nanopolish_test.o -c -g -O3 -std=c++11 -fopenmp -fsigned-char -I./include -I./htslib -I./fast5/include -I./src -I./src/hmm -I./src/thirdparty -I./src/thirdparty/scrappie -I./src/common -I./src/alignment -I./src/pore_model -I./eigen/ -fPIC src/test/nanopolish_test.cpp
g++-7 -o nanopolish_test -g -O3 -std=c++11 -fopenmp -fsigned-char -I./include -I./htslib -I./fast5/include -I./src -I./src/hmm -I./src/thirdparty -I./src/thirdparty/scrappie -I./src/common -I./src/alignment -I./src/pore_model -I./eigen/ -fPIC src/test/nanopolish_test.o src/nanopolish_call_methylation.o src/nanopolish_call_variants.o src/nanopolish_extract.o src/nanopolish_getmodel.o src/nanopolish_haplotype.o src/nanopolish_index.o src/nanopolish_methyltrain.o src/nanopolish_phase_reads.o src/nanopolish_raw_loader.o src/nanopolish_read_db.o src/nanopolish_scorereads.o src/nanopolish_squiggle_read.o src/nanopolish_train_poremodel_from_basecalls.o src/nanopolish_variant_db.o src/training_core.o src/hmm/nanopolish_duration_model.o src/hmm/nanopolish_profile_hmm.o src/hmm/nanopolish_profile_hmm_r7.o src/hmm/nanopolish_profile_hmm_r9.o src/hmm/nanopolish_transition_parameters.o src/common/fs_support.o src/common/logsum.o src/common/nanopolish_alphabet.o src/common/nanopolish_bam_processor.o src/common/nanopolish_bam_utils.o src/common/nanopolish_common.o src/common/nanopolish_iupac.o src/common/nanopolish_klcs.o src/common/nanopolish_variant.o src/alignment/nanopolish_alignment_db.o src/alignment/nanopolish_anchor.o src/alignment/nanopolish_eventalign.o src/pore_model/nanopolish_model_names.o src/pore_model/nanopolish_pore_model_set.o src/pore_model/nanopolish_poremodel.o src/thirdparty/stdaln.o src/thirdparty/scrappie/event_detection.o src/thirdparty/scrappie/scrappie_common.o src/thirdparty/scrappie/util.o ./htslib/libhts.a ./lib/libhdf5.a -lz -ldl
```

My gcc installations are done via homebrew. 4.8 is installed with an older commit of homebrew as 4.8 was recently removed from homebrew altogether 

Any idea on what I can try?

I would just go ahead and avoid all of this by installing on my Linux machine but that is currently having unrelated issues

**Comment by jts** [comment]
It looks to me the `g++-7` compilation works, do you not have working executables?

**Comment by dbobr** [comment]
Yes, no nanopolish executable

**Comment by jts** [comment]
The last line in the output is linking `nanopolish_test`, and it didn't report an error. Do you at least see `nanopolish_test`? Could you send me the entire build log when compiling with g++ 7?

**Comment by dbobr** [comment]
No symlink to nanopolish_test. But! I see now that the directory does have two executables (nanopolish_test and nanopolish). Running nanopolish_test from the directory passes all tests. I guess there was no symlink but everything still built

**Comment by jts** [comment]
The build script doesn't make a symlink or copy the executable anywhere, it just writes it to the main directory. Looks like all is ok!

**Comment by dbobr** [comment]
Oh shucks. Glad to see it built. Thank you!
