### ISSUE TITLE
conda install fail

### ISSUE THREAD

**Issue by phiweger** [jts/nanopolish#328]
I tried installing nanopolish using conda:

```
apt-get install -y libhdf5-dev
conda install -y nanopolish
```

When starting nanopolish index, it errs out w/:

```
nanopolish: error while loading shared libraries: libhdf5.so.10: cannot open shared object file: No such file or directory
```

What might I be doing wrong?

Thank you.

**Comment by jts** [comment]
Sorry but I don't maintain the conda package, you'll have to ask the conda devs for help.

**Comment by phiweger** [comment]
I see thank you.
