### ISSUE TITLE
Required coverage

### ISSUE THREAD

**Issue by phiweger** [jts/nanopolish#329]
Hi,

What is the minimum coverage required to effectively polish a genome, given "the usual" 1D data? 

Furthermore, is there a maximum coverage, after which you would not expect nanopolish to improve the consensus? E.g. does a coverage of 100 or 1000 make a great difference?

Thank you very much.

**Comment by jts** [comment]
I recommend at least 50x as a minimum. I think 100-200x is optimal, beyond that more coverage probably doesn't help much.

Jared

**Comment by smf96** [comment]
Hello,

Do you still recommend a minimum of 50x or has this changed considering the improvements to basecalling accuracy since 2018?

All the best,

Sarah

**Comment by jts** [comment]
Yes, the coverage recommendation has not changed.
