### ISSUE TITLE
Subsample fast5

### ISSUE THREAD

**Issue by phiweger** [jts/nanopolish#330]
I notice that one of my major bottlenecks is nanopolish index, because for every subset of reads I need to index the entire read set.

Will nanopolish index work if I subset the fast5 files to match the read subset? I.e. if I create a directory where for each read there is the associated fast5 file, and then I point nanopolish index to this directory?

Thank you.

**Comment by jts** [comment]
Hi,

In the next release (hopefully tomorrow) the indexing step will be much faster and solve your problem.

Jared

**Comment by jts** [comment]
version 0.9.0 supports indexing from the `sequencing_summary.txt` files, which should solve this issue for you.
