### ISSUE TITLE
correction "too perfect"

### ISSUE THREAD

**Issue by phiweger** [jts/nanopolish#331]
Hi,

The result of nanopolish variants is empty (ie no called variants). Maybe I am doing this the wrong way:

- I align reads against a reference genome (not a draft assembly but closely related)
- in the IGV genome browser there is clear support for > 10 SNPs
- I launch nanopolish, providing the alignment and the reference genome, but the consensus it returns is identical to the reference, which is not plausible (max 10 rounds of correction, uniform coverage of 100x in alignment)

What could be the reason for this "overcorrection"?

Thank you very much for your patience,
Adrian

**Comment by jts** [comment]
Can you send the output messages that nanopolish printed during the run? To make it easier to debug you might want to just run on a small window (`-w <contig>:<start>-<end>`) that encompasses one of the SNPs you expect.

**Comment by phiweger** [comment]
It prints 

```bash
##fileformat=VCFv4.2
##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">
##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">
##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">
##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">
##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
[post-run summary] total reads: 199, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 199
```

i.e. something seems to be going wrong during the indexing step? I porechop the reads and size select before indexing them w/ nanopolish. However, nanopolish index and variants receive the same reads as input.

**Comment by jts** [comment]
Since the number of bad reads matches the number of total reads, nanopolish wasn't able to find any useful data. There must be something wrong with the .fast5 files or the indexing step.

Jared

**Comment by phiweger** [comment]
You were right, somehow the fast5 were corrupted. Using a different run, nanopolish worked as expected -- thank you!
