### ISSUE TITLE
Need help with nanopolish

### ISSUE THREAD

**Issue by Lau16** [jts/nanopolish#332]
Hi Jared, thank you for your email, we've installed the updated version.
I'm still trying to do a new consensus sequence for a draft  assembly of a bacteria (Acc) .
I encountered with some problems while running the algorithms:

# Align the basecalled reads to the draft sequence
bwa mem -x ont2d -t 8 draft.fa reads.fa | samtools sort -o reads.sorted.bam -T reads.tmp -
samtools index reads.sorted.bam
It only works  when I run each command separately.
I had the same problem to run in parallel the genome in 50 kb blocks for polishing. 
I run: python /bio/nanopolish/scripts/nanopolish_makerange.py acc6.contigs.fasta > makerange_out
The obtained files are in the attached notepad.
What does mean: parallel --results nanopolish.results -P 8  ?
I attached a notepad with the source from where I took the data for the different steps
Thank for your help.
[nanopolish_commands.txt 1.txt](https://github.com/jts/nanopolish/files/1722923/nanopolish_commands.txt.1.txt)

**Comment by jts** [comment]
Hi,

`parallel` is a program that is used to run multiple commands at the same time. I am not sure I understand your other questions. To make sure all programs are installed correctly, can you check whether you are able to successfully complete the nanopolish tutorial?

http://nanopolish.readthedocs.io/en/latest/quickstart_consensus.html

Jared

**Comment by Lau16** [comment]
Hi Jared,
Thank you for your help. After checking all the programs, Nanopolish  is
working well.

Laura

**Comment by jts** [comment]
Great!

**Comment by Lau16** [comment]
Hi Jared,
I see that in the email I send you with attachment file.
Try from here please.
Thanks Laura

---------- Forwarded message ---------
From: Andrey Beerman <andrey.beer@gmail.com>
Date: Sun, Mar 11, 2018, 8:50 AM
Subject: Re:
To: Laura Chalupowicz <laurachalu@gmail.com>


Nanopolish output  file

2018-01-16 11:42 GMT+02:00 Laura Chalupowicz <laurachalu@gmail.com>:

>
>


-- 
Andrey.

**Comment by jts** [comment]
Hi Laura,

This appears to be a different issue and I still don't see the file. Could you email it to jared.simpson@oicr.on.ca?

Jared

**Comment by Lau16** [comment]
Ok Jared!
Hope you can help me.
Laura

**Comment by Lau16** [comment]
Hi Jared,
Did you have the opportunity to see  the output file?
I'm waiting for your response
Laura
