### ISSUE TITLE
Homopolymer Assessment

### ISSUE THREAD

**Issue by esteinig** [jts/nanopolish#334]
Hi Jared,

just wondering if you had any recommendation on how to assess homopolymer differences between the (polished) draft genome and a reference? Nanopolish is working great, thanks for the excellent program!

**Comment by jts** [comment]
Hi @esteinig,

thanks! what kind of assessment are you trying to do?

Jared

**Comment by esteinig** [comment]
At the moment, I am just interested in a simple difference between the draft and reference genome, i.e. which homopolymers are in the reference that have not been captured in the nanopore assembly. Perhaps there are more sophisticated assessments you may know of, my apologies!

**Comment by jts** [comment]
[Here's a python script](https://github.com/jts/nanopolish/files/1729970/bam_to_homopolymer.py.zip) I wrote to look at this. I haven't tested it in awhile but maybe it is useful to you as a starting point.

**Comment by esteinig** [comment]
Wonderful, that will help me get started, many thanks Jared!

**Comment by jts** [comment]
Great, I hope it goes well!
