### ISSUE TITLE
Methylation calling with mix of R9.4 and R9.5 reads!

### ISSUE THREAD

**Issue by trandoanduyhai** [jts/nanopolish#336]
Dear Jared,
I'm trying to call methylation using a mix of R9.4 and R9.5 data (I started mix data from albacore step), however I got following error:
error: could not parse model string: template_r9.4_450bps_5mer_raw.jsn
Are there other ways to merge these data?
Thanks in advance!
Hai

**Comment by jts** [comment]
What version are you using? (try running `nanopolish --version`)

Jared

**Comment by trandoanduyhai** [comment]
version 0.8.1
Hai

**Comment by jts** [comment]
Can you update to the latest version and try again?

**Comment by trandoanduyhai** [comment]
I'll try it, thanks Jared
Hai

**Comment by jts** [comment]
Which options did you use for Albacore? Did you use `nanopolish index` or `nanopolish extract`?

**Comment by trandoanduyhai** [comment]
Dear Jared,
sorry for the late response! I use nanopolish extract. My reads were basecalled with albacore 1.2.6

**Comment by jts** [comment]
I suggest re-basecalling everything with albacore 2.0 or later and use nanopolish index.

**Comment by trandoanduyhai** [comment]
I'll try it, thanks Jared!
Hai

**Comment by jts** [comment]
Please reopen if this is still an issue after re-basecalling.

**Comment by trandoanduyhai** [comment]
Sure! I'll do it. Thanks Jared!
Hai
