### ISSUE TITLE
nanopolish methyltrain

### ISSUE THREAD

**Issue by wyzhangMPI** [jts/nanopolish#338]
Hello,
     As I can understand, for methylation calling of nanopolish, it would use a pre-trained model behind. I would like to know how this model is trained, and would it only be usable for species like human. For other genomes, should I need to do the methyltrain on my own? If it is, what kind of data (should be golden standard dataset I guess) should I use for this type of model training?

**Comment by dbobr** [comment]
This information is in the original methylation paper and in the supplementary information from that paper: https://www.nature.com/articles/nmeth.4184

There is a repository for the analysis from that paper here: https://github.com/jts/methylation-analysis

Long answer short: the training is done on fully methylated and fully unmethylated PCR samples with a CpG methyltransferase. There are no mixed methyl states in the training set so any methyls within 10 bp of each other are grouped. If you're looking for CpG methylation specifically and the 10 bp grouping doesn't impede you, you shouldn't have to retrain the model

**Comment by jts** [comment]
Thanks @dbobr for answering for me!

I'd like to add that our model is not specific to human, it can be used for any species with CpG methylation. We will be extending it to other methylation types this year.

**Comment by russianconcussion** [comment]
Hi, any updates on the extension to new methylation types? Keen to give it a go on bacterial genomic data!

**Comment by jts** [comment]
Which methylation types are you interested in? We have support for Dam and Dcm now.

Jared

**Comment by russianconcussion** [comment]
Ah that's great! I was under the impression that 5mC was the only profile available in nanopolish. Good to hear that Dam is also available. Thanks very much for the update. I think that signalAlign is about to be updated, too:
https://github.com/mitenjain/signalAlign/issues/3#issuecomment-445628032
