### ISSUE TITLE
call-methylation problem

### ISSUE THREAD

**Issue by wyzhangMPI** [jts/nanopolish#339]
Hi,
   I am trying to repeat the call-methylation with the example data, and had a problem for the call-methylation step. Error info is:

-bash-4.2$ nanopolish call-methylation -t 5 -r albacore_output.fastq -b albacore_output.sorted.bam -g reference.fasta -w "chr20:5,000,000-10,000,000" >methylation_calls.tsv
[bam process] iterating over region: chr20:5,000,000-10,000,000
_nanopolish: src/hmm/nanopolish_profile_hmm_r9.inl:301: float profile_hmm_fill_generic_r9(const HMMInputSequence&, const HMMInputData&, uint32_t, uint32_t, ProfileHMMOutput&) [with ProfileHMMOutput = ProfileHMMForwardOutputR9; uint32_t = unsigned int]: Assertion `data.read->pore_model[data.strand].states.size() == sequence.get_num_kmer_ranks(k)' failed._

Could you please help to take a look at what is wrong there?

**Comment by jts** [comment]
what version of nanopolish are you using?

**Comment by wyzhangMPI** [comment]
version 0.8.1

------ Original Message ------

**Comment by jts** [comment]
Can you update to the latest and try again?

**Comment by wyzhangMPI** [comment]
Yes, you are right. The current version 0.8.5 works. Thanks!

------ Original Message ------

**Comment by jts** [comment]
Good to know. The most recent version is 0.9.0 though and methylation calling is much faster with that version.
