### ISSUE TITLE
logsumset problem

### ISSUE THREAD

**Issue by anamarijaselak** [jts/nanopolish#342]
Hi, 

I am using logsumset.hpp for Forward-Backward algorithm. I have seen usage of the same in Nanocall ( https://github.com/mateidavid/nanocall/blob/master/src/nanocall/Forward_Backward.hpp ). I am not able to find clear() method in logsumset.hpp or logsum.cpp or logsum::logsumset. Am I missing something?

If I don't have clear() method I can not reuse same logsumset object multiple times and creating bunch of them causes a segmentation error. Is there any other way to reset the value of logsumset object?

Thank you.

**Comment by jts** [comment]
The version in nanopolish is old. You should use the logsumset code from the official repository, which has `clear`:

https://github.com/mateidavid/hpptools/blob/master/include/logsumset.hpp

**Comment by anamarijaselak** [comment]
Thank you. Works now :)
