### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by rohn-niaid** [jts/nanopolish#343]
We are building an RPM package for nanopolish v9.0 for our local environment.  It is not clear from the README or the Makefile, which files will need to be installed into our user's PATH.  There is no "install" target for the Make.   I see the nanpopolish binary clearly in the root of the build, but I also see the /bin directory.   So, would I be correct in assuming that nanopolish calls files in bin (or lib) via relative pathing, or....?   If that is the case, we would just move the nanopath directory to a suitable location and set the PATH variable to point to the /path/to/nanopath   

Could someone comment?

Thanks!

Rohn

**Comment by jts** [comment]
Hi,

nanopolish does not call out to anything in bin or lib. The libraries included (htslib and hdf5) are statically linked. It is safe to move the nanopolish binary (and only the binary) to wherever you'd like.

Jared

**Comment by rohn-niaid** [comment]
Thanks!
