### ISSUE TITLE
Nanopolish index not valid command?

### ISSUE THREAD

**Issue by hjb60** [jts/nanopolish#344]
Hello,

I am following the instructions to polish a draft genome assembly. First step I am doing as shown in the read the docs v0.8.4:
nanopolish index -d ../../data/ICP181/181_fast5/all/ 181_reads.fa

just gives me the usage options where it doesn't show index as a valid command?

usage: nanopolish [command] [options]
  valid commands: 
    --help
    --version
    call-methylation
    consensus
    eventalign
    extract
    getmodel
    help
    methyltrain
    phase-reads
    scorereads
    train-poremodel-from-basecalls
    variants
  for help on given command, type nanopolish command --help

Am I being really dim here?
I have just checked nanopolish --version and I have v0.7.2 however I did do git checkout for what I assume is the latest version?

**Comment by jts** [comment]
The problem is definitely that your version is out of date. Please follow these instructions to get the latest version: 

https://github.com/jts/nanopolish/#installing-the-latest-code-from-github-recommended

**Comment by hjb60** [comment]
Hi,
I have followed the instructions as advised and nanopolish --version is still showing 0.7.2
 git clone --recursive https://github.com/jts/nanopolish.git
and
git clone --recursive https://github.com/jts/nanopolish.git
git checkout v0.9.0

are giving the same 0.7.2 version.

**Comment by wdecoster** [comment]
check `which nanopolish`

**Comment by hjb60** [comment]
Ok - think I've figured out the problem. many thanks

**Comment by jts** [comment]
Ok, glad to hear it.
