### ISSUE TITLE
optimisation of variant calling

### ISSUE THREAD

**Issue by webbchen** [jts/nanopolish#345]
Dear Jared

I've got Nanopore reads from 10 individuals I try to call SNPs with nanopolish variants for but have got a maximum of 16 threads available to me for that. Calling SNPs is extremely slow and I'm trying to make as much progress as possible. I've divided the ref into 50kb chunks as recommended and run several batches in parallel. Is it better to run fewer batches with more threads each or more batches with fewer threads? I could run one batch with 16 threads or 16 batches with 1 thread each and am wondering which dataset would be likely to be first to complete?
I have got nanopolish 0.9.0 installed but haven't noticed a huge amount of speed increase for that particular task.

Kind regards,

Anne

**Comment by jts** [comment]
Hi Anne,

How big is the genome, how much coverage do you have for each sample and what SNP rate do you expect?

Jared

**Comment by webbchen** [comment]
Hi Jared
genome: ~39Mb, coverage between 50x and 250x on average.
Anne

**Comment by jts** [comment]
How long does it take to call on a 50kb segment for a single sample?

Jared

**Comment by webbchen** [comment]
I've seen everything between 30 min and 1 day pass between samples of 50kb.

Anne

**Comment by jts** [comment]
That indeed seems much too long. Can you paste the command and send me an output VCF file by email? It will help me figure out the problem.

**Comment by webbchen** [comment]
We haven't got the parallel library installed so I'm creating a file full of batch coordinates  with nanopolish_makerange.py, divide it into however many parts I want to run in parallel and loop over them, which should in theory do the same thing:

lines=`cat /data/anne_webb/fungi/fungus/variants/contig_bits_reference1.txt`
for line in $lines; do
nanopolish variants --ploidy 1 -x 100000 -w $line -o ./fungus_72.$line.vcf -r /data/anne_webb/fungi/fungus/fungus_isolates_basecalled/fungus_72_albacore_trimmed.fastq -b /data/anne_webb/fungi/fungus/alignments/fungus_72_albacore_to_ref_bwa-mem_sorted.bam -g /data/anne_webb/fungi/fungus/reference_chromosomes/ref.fasta -t 4
done

(real file names anonymised)

Anne

**Comment by webbchen** [comment]
Hi Jared

I’ll send you three. The first took 6 hrs to emerge, the second 5 and the third only 2hours.
Many thanks for looking into this!

Kind regards,

Anne

**Comment by jts** [comment]
Hi Anne,

With that script I believe all tasks will be run at the same time - so in effect you'll use 4*N threads, where N is the number of 50kb regions. This might explain why it is so slow.

Jared

**Comment by webbchen** [comment]
I don't believe it does, it produces 1 empty vcf file at a time which sits there until the process has run its course, then it gets filled with data and the next empty one appears, which suggests to me that it's iterating over the lines in succession.
Anne

**Comment by jts** [comment]
Oh yeah you're right sorry. I'll take a look at the VCF files and get back to you.

**Comment by jts** [comment]
Is it still slow without the `-x 100000` option? This may slow it down considerably.

**Comment by webbchen** [comment]
It used to be fairly slow, but it's been a while since I've run it without that option as I was getting lots of warnings about missed variant calls.

**Comment by webbchen** [comment]
It looks like removing the -x 100000 option increases speed considerably!

**Comment by jts** [comment]
Great, I'm glad to hear that.
