### ISSUE TITLE
polyA support for 1D reads?

### ISSUE THREAD

**Issue by NatPRoach** [jts/nanopolish#346]
This is more of a question than an issue, but in the polyA_merged branch the header for the polya function reads

>   -r, --reads=FILE                     the 2D ONT reads are in fasta FILE

I'm assuming that means estimation for 1D sequenced RNA reads is not currently supported? If so, are there plans to include 1D reads in future?

**Comment by jts** [comment]
Sorry, the help message is wrong. It supports 1D direct RNA reads only. @paultsw can you fix?

**Comment by paultsw** [comment]
I've made a pull request fixing the usage message mistake.

**Comment by jts** [comment]
Great, thanks.
