### ISSUE TITLE
error: could not parse model string: template_r9.4_450bps_5mer_raw.jsn

### ISSUE THREAD

**Issue by Omer-K** [jts/nanopolish#348]
Hi,
Using Nanopolish 0.8.3, I think I've been experiencing the same error as #216.
I've basecalled my 1D raw reads offline (aka post sequencing) with Albacore 2.1.10.
Then I've run nanopolish extract, producing my mutli-fasta file with all reads, `reads.fasta`.
I aligned with bwa mem and canu-ed to get a few contigs.
I ran 
`nanopolish index -d fast5_files/ reads.fasta` to generate necessary index files, then `bwa index draft.fa` followed by `bwa mem -x ont2d -t 8 draft.fa reads.fasta | samtools sort -o reads.sorted.bam -T reads.tmp' and 'samtools index reads.sorted.bam`

The problem arises when I implement 
'nanopolish variants --consensus polished.fa \
-w "contig001" \
-r reads.fasta \
-b reads.sorted.bam \
-g draft.fa'

This yields 'error: could not parse model string: template_r9.4_450bps_5mer_raw.jsn'.

How do I solve this?

**Comment by jts** [comment]
Hi,

You should not use nanopolish extract, use the fastq files output by albacore.

Jared

**Comment by Omer-K** [comment]
Hi Jared, thanks for promptly replying!
After posting, I did exactly that. This time, no error such as the one before appeared.

This was the output:

 ##fileformat=VCFv4.2
##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">
##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">
##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">
##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">
##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample
Warning: 2407 variants in span, region not called [9 1139]
Number of variants in span (47) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Warning: 14182 variants in span, region not called [1131 7598]
tig00000002     1141    .       TA      T       420.7   PASS    TotalReads=144;AlleleCount=1;SupportFraction=0.132108   GT      1
tig00000002     1141    .       TA      T       441.3   PASS    TotalReads=144;AlleleCount=1;SupportFraction=0.483243   GT      1
[post-run summary] total reads: 4086 unparseable: 0 qc fail: 0 could not calibrate: 0 no alignment: 107

I'm not sure if everything run smoothly as it was suppose to, I got two warning messages..
The polished contig seems to be 100 bp shorter than the original, which was 7.6kb.
Nonetheless I aligned the old contig with the new polished one, and I got one base, which was previously deleted to appear as an 'A', other than that (and the lost 100bp), all were identical.

**Comment by jts** [comment]
Hi,

These two warnings are troubling:

```
Warning: 2407 variants in span, region not called [9 1139]
Warning: 14182 variants in span, region not called [1131 7598]
```

It means nanopolish found too many candidate variants in these regions so they were skipped (nearly the entire amplicon). If you look at the alignments in IGV does it look ok or does it look like many reads were misaligned? What nanopolish parameters did you use?

Jared

**Comment by Omer-K** [comment]
Aligning the basecalled reads it seems that there are a lot of error and indels, as usual. I'm not sure how to call for misaligned reads, but I think it looks nothing out of the norm. Perhaps I'm lenient so here

**Comment by jts** [comment]
Did you run nanopolish with the `--consensus` option, or without?

**Comment by Omer-K** [comment]
With `--consensus`

**Comment by jts** [comment]
As an experiment can you try without it?

**Comment by Omer-K** [comment]
Sure.
P.s. I run the same workflow on an older batch of raw and the corresponding bascalled data and it ran rather smoothly, with a mild improvement over the canu original contig..

**Comment by Omer-K** [comment]
Ok, so I ran another job just I previously did (With` --consensus`), this time no warnings, and I did see positive polishing.. Haven't been able to explain why no error this time..
Then I ran without `--consensus`, but added and added to following parameters: `-t 12 --ploidy 2 -o variants.vcf`.

Here are the following output:
Number of variants in span (10) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (33) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Warning: 54 variants in span, region not called [2317 2523]
[post-run summary] total reads: 25573 unparseable: 0 qc fail: 5 could not calibrate: 25 no alignment: 656

And I'm attaching the vcf file.
[variants.zip](https://github.com/jts/nanopolish/files/1771760/variants.zip)

What do you think of the run Jared?

**Comment by jts** [comment]
Ok, that output looks better. How many variants did you get when you re-ran with the `--consensus` option? It would be good to understand why it worked this time.

**Comment by jts** [comment]
Closing this for now, please re-open if there is still a problem.
