### ISSUE TITLE
Indexing rather slow

### ISSUE THREAD

**Issue by wdecoster** [jts/nanopolish#349]
Hi,

I'm playing around with calling methylation on some PromethION human genomes. It all seems to work fine, but I noticed that the indexing part takes rather long (hours). I'm _currently_ not calling methylation genome-wide (restricted to a region of interest of 1Mb). I could, in theory, make a preselection I guess of reads (fastq based on minimap2 alignment to the locus) but those are extra steps and intermediate files I would like to avoid.

Of course, being PromethION, this is a ton of data. The fast5 files are on another disk (which is mounted and to which I have access), which can make this procedure slower. I don't speak C++, but do you think some parallelization could be applied to the indexing procedure?

Timewise this seems to be the main bottleneck, the other commands are fairly quick (on the 1Mb locus).

An unrelated request: nanopolish expects a single fastq(.gz) file for the reads, would it be possible to have a fofn for this? With albacore basecalling we get hundreds of fastq.gz files, which is convenient for parallelization but requires that I cat them together for nanopolish.

Cheers,  
Wouter

**Comment by jts** [comment]
Are you using 0.9 with the option to use the sequencing_summary file during indexing?

jared

**Comment by wdecoster** [comment]
Yes, I use a fofn of sequencing summary files with the `-f` option.

It's perfectly possible that the reading the fast5s over the network is a big contributor.

**Comment by jts** [comment]
Yeah, it is effectively I/O bound (specifically listing all the files in a directory). I don't think I can make it much faster easily but I'll take a look.

I probably won't change nanopolish to take in multiple fastq files - it would be quite messy to keep track of all the index files and which read came from each.

Jared

**Comment by wdecoster** [comment]
Alright, thanks for your effort (and the quick reactions). It's not unreasonably slow if I just don't mind running it overnight. It's not that I need to do the indexing repeatedly, fortunately.

Cheers,
Wouter

**Comment by jts** [comment]
No problem - hopefully I can improve it some more (I am waiting for `index` to finish right now too)
