### ISSUE TITLE
Not improvement of  the draft genome assembly after running Nanopolish

### ISSUE THREAD

**Issue by Lau16** [jts/nanopolish#353]
Hi Jared,
I complete all the steps for Nanopolish (first with the E. coli example and then with  my Nanopore reads). When I evaluated the assembly, I got the same number of contigs as the draft assembly and also the draft dnadiff and polished dnadiff report  [Alignments ] 1-to-1 both gave the same values.
I supposed that after polishing, I got an improvement in position and direction of the contigs.
Waiting for your answer.
Thanks
Laura

**Comment by jts** [comment]
Hi,

I need more information to help you. Can you send me the output that was printed to the screen when you ran nanopolish?

Jared

**Comment by Lau16** [comment]
Hi Jared,
I attached here the output file, hope it will help.

Thanks
Laura

**Comment by jts** [comment]
Hi,

Sorry but I don't see the attachment.

Jared

**Comment by Lau16** [comment]
Hi Jared, Here I uploaded again the output file.
Thanks
Laura
[nanopolish_log (1).log](https://github.com/jts/nanopolish/files/1950275/nanopolish_log.1.log)

**Comment by jts** [comment]
A few observations from that output file:

-The number of reads that nanopolish is using is very lower (typically only 12-14). This is too low of depth to have good polishing results. 50-100 is recommended.
-It appears that only 5kb of the draft assembly was polished (positions 95,000-99,900). Is this the complete output file?

Jared
