### ISSUE TITLE
Too many arguments

### ISSUE THREAD

**Issue by hjb60** [jts/nanopolish#354]
Hello,
I am following the github guide but finding I am getting the an error witht he following command: 
python ../../../bin/nanopolish/scripts/nanopolish_makerange.py ICP181_Canu_draft_assembly.fasta | parallel --results nanopolish.results -P 8 ../../../bin/nanopolish/nanopolish variants --consensus polished.{1}.fa -w {1} -r all_ICP_fast5_reads.fa -b 181_reads.sorted.bam -g ICP181_Canu_draft_assembly.fasta -t 4 -min-candidate-frequency 0.1

Gives the error
variants: too many arguments

I have seen this may be a problem for others but I don't understand how to fix it. Please could someone advise?
Everything had been extracted/indexed etc

**Comment by jts** [comment]
What does `../../../bin/nanopolish/nanopolish --version` show?

**Comment by hjb60** [comment]
../../../bin/nanopolish/nanopolish --version
nanopolish version 0.9.0

**Comment by jts** [comment]
`-min-candidate-frequency 0.1` should be `--min-candidate-frequency 0.1`
