### ISSUE TITLE
phase-reads - explanation?

### ISSUE THREAD

**Issue by colindaven** [jts/nanopolish#355]
Hi Jared,

I have successfully used `phase-reads` with nanopolish 0.9.0 - the new index seems to work well, thanks.

I haven't so far found documentation of the phase. I can find the following in the output file:
```
??`?   -  does this mean unphased?
???P?  - phased VCF SNP?
??W?  - unknown

```

Sometimes P occurs before ` and sometimes its the other way around.

I've looked in the code but didn't get far. Are there docs for this -apologies if I've missed them ?

It might be also useful to point out you need to run `nanopolish variants` to call SNVs which are then input into the phase-reads pipeline.  Perhaps I can mock up a bit of initial documentation when I get through this ?

cheers,
Colin

**Comment by jts** [comment]
Hi Colin,

Sorry for the lack of documentation for phase-reads, it is an experimental module that I haven't refined yet.

Could you paste an entire SAM record for me to look at?

I'd appreciate it if you made a documentation mock up - I agree it should be mentioned that `nanopolish variants` can be run to make the input VCF but this VCF could also come from orthogonal sequencing data like Illumina.

Jared

**Comment by colindaven** [comment]
```
fd16f0cc-eb81-4087-bce4-c94652489d98    0       chr18   21118411        60      1301M   *       0       0       TTCCCATGCAACTGTCTTAGCCCAGTCCTCTCCTAGTTTTCTACTGCAAATTAAAGTTGCAGTGGATGCTTATCTGCAATGGCAGCAGCACTTACCCTTTGCCACACTTGGGGTTAGGGTTATCCGAAAGGAACATGGGCAGGAATCTCATGAAGTCTCCCCCCTGAGGCCTCTGTTTGCCTTCCGGAGTCAGAGGCCTGCAGCGAACGCAGGCAGGGTCAACCACTGGCGGAGACATGCAGGGAGGACTGTTAGAAGAATAGGTCTCCAGATTTTTTGTAAAACATTTTAAAATACTGACAGTGAGGGGCATTACTTTCTTCTCTATCGATTACTTTCCTTACTAGTGAGGGATAATCTTTCCCCTTATCTAAAAGCTTCAGCCACATGTCACTTTCACAGTTTAATGAATCTGAAATACCATTTTCATCTTAGGCATACTATGCATCATTTTCTGCCCTGAAGTAGATCTCCTCCTTCAAGTATGGCCTTGACTGGTCAGAGCCCGGGGCTTCTATGTTTTTATTAAGAAAATTCCAGGGCAACCTCGACGCTCCTACAAAACCACAGGGTAAAGTGATAAAGAAAAGCCCTCCTCTGAGAAGCTAAGGCCAGATACCAATCCTGAGAGGCAATCGCTGGAGTTAGAACAGGATGAGAAACCTTATGTGGAAACCACACTCCGAACATGTGGACCTTGTTCAGCTTGCAGCCCCGAGGGTGGCTGTCTGAGCCAGGAACAACATGACAATTTCAGAATGAATGACTGAGGAAAGGAATGATGACACAGGGAGACCCAGCTTTGATATACAAATAGGTATAAACTGAGGCACGATGCAAATGATTTTTAAATGATAATTTGAAAATTTTTCAGCAAAACAGGAAAGATTTGGTAAAGGAGAAGGTACCTGAAGCATTGCAGAACTGGTCAGTGATATTGTCCACTCGACAGCAAGACGACTGTGGCTTCACCCAGTCGAAATAATCGTCGATCCAGGACGAGGGGGCGAAGCCTATTCGGGTACTAGAGAGGACAGACAGGGTTACTGACCTGCTCCACAGGGAGGAAGTCTTTAGTTTCAGTACTTTTTCTTAAAACCTAACTTCCTTTTCTACGTTTTATACTGCTAACAGTCAAAAGAAAAACTACATGAGCACTTAATGAAAAAAGCCTTCAAAGTATTAGGTGGTAAATTAGTCCTTTCAAAGGTTTTTTAAGGTAAAGCCAGATTTAACATACATTTTGCATAAAAACAACTTTTCCAAGAAAGTCTATTTTCAGTGAGACATTTCAGGCCTGA   ???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????P?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
```

**Comment by jts** [comment]
In the read sequence string the bases will be changed to match the phased variants. In the quality string unphased positions will have qual '?' and phased positions will have a quality value depending on nanopolish's estimate of the probability the chosen phase is incorrect.

**Comment by jts** [comment]
NB the output read sequence is taken from the reference genome, not the basecalled read

**Comment by colindaven** [comment]
Ok, thanks,

To be clear, if looking at the last figure/table on this page: https://en.wikipedia.org/wiki/FASTQ_format
```
` means a decent quality - > higher phred score
P means a lower quality - > lower phred score
W is a medium quality -> medium phred score
```
So ideally I want a tick ` in both the positions of the first and last if both heterozygous SNVs are concordant - phased ?

Correct ?

**Comment by jts** [comment]
The exact quality score you see in each position will depend on how well the underlying signal data matches the allele - but yes in general you want to see high quality scores at both het positions.

**Comment by johnomics** [comment]
Hi Jared - I'm only seeing phred scores from E (36) to ` (63) in phase-reads output. Is this expected? Thanks

**Comment by jts** [comment]
Yes I think that is expected.
