### ISSUE TITLE
Error: duplicate read name?

### ISSUE THREAD

**Issue by timacwalker** [jts/nanopolish#357]
Hi there,

I've encountered a problem when indexing that I haven't seen before.

Does anyone know how to fix this? Thanks.

nanopolish index -d ~/fast5/fast5_24_2_18/ -s ~/fast5/basecall_run_24_2_18/sequencing_summary.txt ~/fast5/basecall_run_24_2_18/workspace/pass/barcode04/fastq_runid_715ed30a8910ca6c30b43301495f8ca423d709ed.fastq
Error: duplicate read name 71116bcf-96f0-4758-8eba-cf3db803153d found in fasta file

**Comment by jts** [comment]
Hi,

If you grep for that name (`71116bcf-96f0-4758-8eba-cf3db803153d`) in the fastq file, does it appear multiple times?

Jared

**Comment by timacwalker** [comment]
Yeah it does. I don't know why there's a duplicate read, I haven't seen this before. I'm trying to figure out a way to remove one of the reads without screwing up my file. Any advice would be greatly appreciated.

Thanks,

Tim.
--------


awk -v seq="71116bcf-96f0-4758-8eba-cf3db803153d" -v RS='@' '$1 == seq {print RS $0}' ~/fast5/basecall_run_24_2_18/workspace/pass/barcode04/fastq_runid_715ed30a8910ca6c30b43301495f8ca423d709ed.fastq
@71116bcf-96f0-4758-8eba-cf3db803153d runid=715ed30a8910ca6c30b43301495f8ca423d709ed read=107934 ch=96 start_time=2018-02-25T00:16:33Z barcode=barcode04
TTGTTGTACTTCGTTCCAGTTACGTATTGCTTTCCGGATTCTATCGTGTTTCCCTAGTTTTTTCGCATTTATCATTGAAACGCTTTCGCGTTTTCGTGCGCCGCTTCACTCATGACGTCGGGCGCTGAGCCGCTCCCAATAGCCAGCCGGCGGAAGTCCAGGGCCGCGGGAGATAGGCGTCAGCATACACCAGTCCAGCGTCCGGTGGCGGTCCAGGGCGTCCAGCCGCAACCAGCCGATGGGCCGTCCTCGCCGAGGACGCAGCGTGCGACGGCGTGGCATCGAGCCGATGCCCACACCGGCCCCGACGAGTTCAGGGGTGGCCGCCGCCTCGTCGCTTCGCAGACCACGCGCGGTGCCAGCCTTCACGGGCGAAGAGCCATCTCCAGCAGGGGCCCGTTGCCAGTGGCCCGGGGCGGGTGCTGACCAGAGATCCTCGTCGGCCAGCTCGGCCACCGCGACCCGCTCCCGGCCGGCCGGTCGTGCCCGACCGGTGCGGCCAGGCAGTACCTCCTCGCGGGCCAGTTCGGCAGAGCACACCTCGGGGTTGGTCGGCGGCTGGGAGAGCGGGGCGAGGTCACCTCGCCGAACGCAGATGCCGCCGCATCGAATCCACCGGGGCCTGGAAGGCGCACCCCACTCCCGGCCGGGCTCGCGGAACGCAGACAGCACCCGGCCAGCTGGAGCGCTGGGGTCTCGGCGGCGACCGCGACCCGGCCGGGACCGCCGCGACCGGCGTCGGCCACCTCTCGCCGGGCGTCCTCCAGGCTCCGCCAGCGCCCGCTCTGACCCGGACCAGGAAGGCGTGCTCGTTGAGACGTATGCAGCGGCCCCTGCGGTCCGAAGAGCGGGTGCCGAGTTCCGACTCCAGCCGGATGATGGTCAGCTCACCGACGCTGGGCCACCCTGTGGTTCCTCCGCGGCCCGGCTGATGTGCTGGTGACGTGCGACGGACTGGAAGTAGCGAAGAGACAGCAGATCCCATATCGGTAGTCTCGTCCGGAACGGTACCAGCGGGCGGGCGGAGGCACCGCCACCGCGTCCGGGTAATCCGGCCTCGACGGCGCGCCCCTGCGCTCACTTCGCGTCGCGTAGCACTCCACCACCGCCGTCGTGAACGGGAACCGCACCGGGGTCGCACCGAACGTCAGCCGCCCGCCAGCTCCGCCGCGTCCCGGATCGCCGCGACGGTGGCGGCCTCCTCCACCGGGACAGTGCACGATCACCTCTCGTCGTGCTGGAAGAGACCAGCTCGGCCGCCATGTCCGCGCAGGTCTGCCGCAGGGCCGCGAGCAGGAGCAGGGCCAGTCGGCTGGCGCTGCCCTGGACGACGGTTACGGGCGAAGCGGCCCGCGCAGGCGTTGAAGGGGGAG
+
-'+)(&'&*,7504300,,/0-.16-5-+)-6(4)*,.43+,+/-7:91;2.7)*(1/6:56.7.0./26,13/21*16+,-.28754710854*+-+-158+.370000/(),-1-/1/:73('')(..3.130)&+,))%.3.23-,%'()&&'**'(0225926)41,,-+*+01--*$(*''&()-/)-)+++-/1043031'..,5/:*'9;486.7)))-3*.+&.-*,5***&&/+67-./0(*+/,-.1/8425*4865431//&**&)+/,-32))%*3///..2($'%,+*(-*.)2274'(*0/(/75.-.8/4.6:).3*+++*%',&(&'')-.+$+)42739899833330400457;.-6-)(+-0%'*+,,*+,*/-,%-*-++4.0-,,))()%(-4753.62257;2*+%&($)%+-../160.02-+--.9,412'-+')+-7:3*+,186',/2*/28*842+)--50.+47(40+5'661)((,&&((,/585,1-/&-.70-0514*633..0-*-'+104(46++&2-/5&4-./009:7**&+1.88+1,(*.),).2-0(*+&&,/*0035642--3.02323%%,.13,,(,9:169687-*,*(&(&456)(,,/8./2231.+-,0-50:29413$.%)',-)98+(51-)(((9+(*+)++/14/.1167965954*7:233'18+/,5289-'&%'.2*-+(.4151016.819'0.')13/13320-/195/0-%(34236.1412102;7245,&&&)4++/.46'17'')(%)/04010/50//33'+%(+,&0320652...3&*),)'))((++'+**-..*'-).3.+*4-8)((203:7:,,,,400&+,,-,...+.()++.24402:.-.1%113.+*.0)(*+-4-,0--+,-.,../.32..0/038481*4+,.*-'#$'(0.*))(')*-*&**)10/;5/1970+0,*-.+'+-,1,5*/())'%&-+$-)/273015/1-$*))57:+7.+10+02,8++,')(*+./&(+7/4,-2664451524,.-3)*-2,-,,*)+006.01,))/+.00,%(,)8:/739:8775526'1/0/8301-.0)560/1)*&21&%'*-122/47+./1-3;423241(,/.5563:-1.::;8<<552/.-,*,.*+)5/+18.21&),/4858+64-,+--012.68)-*,.16689;;<:6.++&+333143,,),.12<87443(*,,-/-6133/18-/*002576-++,,'91,+.161-63)-2*,*(&3*--251294,-5+),&**+2,'1)/68*)3*+,+5.)%&')(1:13'-,%%)(&%("%

@71116bcf-96f0-4758-8eba-cf3db803153d runid=715ed30a8910ca6c30b43301495f8ca423d709ed read=107934 ch=96 start_time=2018-02-25T00:16:33Z barcode=barcode04
TTGTTGTACTTCGTTCCAGTTACGTATTGCTTTCCGGATTCTATCGTGTTTCCCTAGTTTTTTCGCATTTATCATTGAAACGCTTTCGCGTTTTCGTGCGCCGCTTCACTCATGACGTCGGGCGCTGAGCCGCTCCCAATAGCCAGCCGGCGGAAGTCCAGGGCCGCGGGAGATAGGCGTCAGCATACACCAGTCCAGCGTCCGGTGGCGGTCCAGGGCGTCCAGCCGCAACCAGCCGATGGGCCGTCCTCGCCGAGGACGCAGCGTGCGACGGCGTGGCATCGAGCCGATGCCCACACCGGCCCCGACGAGTTCAGGGGTGGCCGCCGCCTCGTCGCTTCGCAGACCACGCGCGGTGCCAGCCTTCACGGGCGAAGAGCCATCTCCAGCAGGGGCCCGTTGCCAGTGGCCCGGGGCGGGTGCTGACCAGAGATCCTCGTCGGCCAGCTCGGCCACCGCGACCCGCTCCCGGCCGGCCGGTCGTGCCCGACCGGTGCGGCCAGGCAGTACCTCCTCGCGGGCCAGTTCGGCAGAGCACACCTCGGGGTTGGTCGGCGGCTGGGAGAGCGGGGCGAGGTCACCTCGCCGAACGCAGATGCCGCCGCATCGAATCCACCGGGGCCTGGAAGGCGCACCCCACTCCCGGCCGGGCTCGCGGAACGCAGACAGCACCCGGCCAGCTGGAGCGCTGGGGTCTCGGCGGCGACCGCGACCCGGCCGGGACCGCCGCGACCGGCGTCGGCCACCTCTCGCCGGGCGTCCTCCAGGCTCCGCCAGCGCCCGCTCTGACCCGGACCAGGAAGGCGTGCTCGTTGAGACGTATGCAGCGGCCCCTGCGGTCCGAAGAGCGGGTGCCGAGTTCCGACTCCAGCCGGATGATGGTCAGCTCACCGACGCTGGGCCACCCTGTGGTTCCTCCGCGGCCCGGCTGATGTGCTGGTGACGTGCGACGGACTGGAAGTAGCGAAGAGACAGCAGATCCCATATCGGTAGTCTCGTCCGGAACGGTACCAGCGGGCGGGCGGAGGCACCGCCACCGCGTCCGGGTAATCCGGCCTCGACGGCGCGCCCCTGCGCTCACTTCGCGTCGCGTAGCACTCCACCACCGCCGTCGTGAACGGGAACCGCACCGGGGTCGCACCGAACGTCAGCCGCCCGCCAGCTCCGCCGCGTCCCGGATCGCCGCGACGGTGGCGGCCTCCTCCACCGGGACAGTGCACGATCACCTCTCGTCGTGCTGGAAGAGACCAGCTCGGCCGCCATGTCCGCGCAGGTCTGCCGCAGGGCCGCGAGCAGGAGCAGGGCCAGTCGGCTGGCGCTGCCCTGGACGACGGTTACGGGCGAAGCGGCCCGCGCAGGCGTTGAAGGGGGAG
+
-'+)(&'&*,7504300,,/0-.16-5-+)-6(4)*,.43+,+/-7:91;2.7)*(1/6:56.7.0./26,13/21*16+,-.28754710854*+-+-158+.370000/(),-1-/1/:73('')(..3.130)&+,))%.3.23-,%'()&&'**'(0225926)41,,-+*+01--*$(*''&()-/)-)+++-/1043031'..,5/:*'9;486.7)))-3*.+&.-*,5***&&/+67-./0(*+/,-.1/8425*4865431//&**&)+/,-32))%*3///..2($'%,+*(-*.)2274'(*0/(/75.-.8/4.6:).3*+++*%',&(&'')-.+$+)42739899833330400457;.-6-)(+-0%'*+,,*+,*/-,%-*-++4.0-,,))()%(-4753.62257;2*+%&($)%+-../160.02-+--.9,412'-+')+-7:3*+,186',/2*/28*842+)--50.+47(40+5'661)((,&&((,/585,1-/&-.70-0514*633..0-*-'+104(46++&2-/5&4-./009:7**&+1.88+1,(*.),).2-0(*+&&,/*0035642--3.02323%%,.13,,(,9:169687-*,*(&(&456)(,,/8./2231.+-,0-50:29413$.%)',-)98+(51-)(((9+(*+)++/14/.1167965954*7:233'18+/,5289-'&%'.2*-+(.4151016.819'0.')13/13320-/195/0-%(34236.1412102;7245,&&&)4++/.46'17'')(%)/04010/50//33'+%(+,&0320652...3&*),)'))((++'+**-..*'-).3.+*4-8)((203:7:,,,,400&+,,-,...+.()++.24402:.-.1%113.+*.0)(*+-4-,0--+,-.,../.32..0/038481*4+,.*-'#$'(0.*))(')*-*&**)10/;5/1970+0,*-.+'+-,1,5*/())'%&-+$-)/273015/1-$*))57:+7.+10+02,8++,')(*+./&(+7/4,-2664451524,.-3)*-2,-,,*)+006.01,))/+.00,%(,)8:/739:8775526'1/0/8301-.0)560/1)*&21&%'*-122/47+./1-3;423241(,/.5563:-1.::;8<<552/.-,*,.*+)5/+18.21&),/4858+64-,+--012.68)-*,.16689;;<:6.++&+333143,,),.12<87443(*,,-/-6133/18-/*002576-++,,'91,+.161-63)-2*,*(&3*--251294,-5+),&**+2,'1)/68*)3*+,+5.)%&')(1:13'-,%%)(&%("%

**Comment by jts** [comment]
There may be other duplicated reads, I think nanopolish will exit after seeing the first one. You may want to investigate why there are duplicates in your fastq file. Maybe you basecalled the same folder(s) twice by accident?

**Comment by timacwalker** [comment]
I found the culprit. Some of fast5 directories somehow got copied into each other. I'll have another go once I've re-basecalled. Cheers.

**Comment by AsclepiusDoc** [comment]
Hello Nanopolish,

I've encountered similar issues where my basecalled .fastq file has duplicate reads and I get the same error during indexing:

` Error: duplicate read name a8631512-1431-4439-8598-11d13b2ddf49 found in fasta file`

Due to a large amount of basecalled .fastq files for my project is it possible to ignore these duplicates when running nanopolish index or will I have to go to each of my .fastq files and manually search and remove for duplicates?

Kind Regards,

Alex

**Comment by jts** [comment]
Hi,

In commit 90ec79d I changed this to a warning, from an error. If you use the very latest version from github it should work for you.

Jared
