### ISSUE TITLE
Call Methylation - Empty output

### ISSUE THREAD

**Issue by axgraf** [jts/nanopolish#358]
Hi Jared,
I'm using a basecalled (Albacore 2.10.2) Fastq file to call methylation following the quickstart tutorial. The sample was generated for a small artificial sequence (~2KB) in which all C's were methylated. After indexing the raw albacore reads and mapping with minimap2 (2.9-r720) I always end up with an empty file without any error.

```
nanopolish call-methylation -t 8 -r  sample1.fastq -b sample1.minimap2.sorted.bam -g ref_seq.fasta
chromosome	start	end	read_name	log_lik_ratio	log_lik_methylated	log_lik_unmethylated	num_calling_strands	num_cpgs	sequence
[post-run summary] total reads: 7209, unparseable: 0, qc fail: 0, could not calibrate: 4, no alignment: 210, bad fast5: 0
``` 

Is there anything I'm doing wrong? As far as I understood, nanopolish will give a likelihood for each read, so I should at least get some results, right?

**Comment by jts** [comment]
Hi @axgraf,

`call-methylation` only finds methylation at CpG sites right now. It should have produced output though for any CG dinucleotides in your reference sequence.

Did the tutorial produce output for you?

Jared

**Comment by axgraf** [comment]
Hi Jared,
thank you for the fast response. 
I just ran the example in the tutorial and it is working as expected. I only get slightly different results:
```
chromosome	start	end	read_name	log_lik_ratio	log_lik_methylated	log_lik_unmethylated	num_calling_strands	num_cpgs	sequence
chr20	4986398	4986398	d763e7f0-c28f-413d-aa80-345eeb054f62	2.70	-96.60	-99.30	1	1	ACCTCCGCCTC
chr20	4986473	4986473	d763e7f0-c28f-413d-aa80-345eeb054f62	0.45	-101.30	-101.75	1	1	ATGTCCGACTA
chr20	4986602	4986604	d763e7f0-c28f-413d-aa80-345eeb054f62	-9.46	-118.33	-108.87	1	2	GTCACCGCGCCTG
chr20	4986762	4986762	d763e7f0-c28f-413d-aa80-345eeb054f62	1.71	-92.61	-94.33	1	1	TTGACCGTATT
chr20	4987028	4987028	d763e7f0-c28f-413d-aa80-345eeb054f62	2.14	-94.77	-96.91	1	1	AGCTCCGCAGG
```
So the pipeline is working. The only difference I spotted was that my reference sequence was not multi-lined, but also changing to a multi-line Fasta didn't change anything. 

I also checked the mapping of my sample with `samtools flagstat` which gives me:
```
52521 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 duplicates
16776 + 0 mapped (31.94%:-nan%)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (-nan%:-nan%)
0 + 0 with itself and mate mapped
0 + 0 singletons (-nan%:-nan%)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```
With that I end up with a mean coverage of ~600 for each position. The reference sequence contains multiple CpG sites.
Currently I don't know where the problem could come from. Do you have any hint where I could look for or what I could check? Would it help to provide a small set of reads?
Thank you for your help
Alex

**Comment by jts** [comment]
If you run another command, like say `eventalign`, do you get some output?

**Comment by axgraf** [comment]
Yes, that is working!

```
contig  position  reference_kmer  read_index  strand  event_index event_level_mean  event_stdv  event_length  model_kmer  model_mean  model_stdv  standardized_level
NP_standard 1 TTACAC  0 t 215 99.72 1.524 0.00075 TTACAC  96.56 2.10  1.19
NP_standard 1 TTACAC  0 t 216 96.63 1.380 0.00075 TTACAC  96.56 2.10  0.03
NP_standard 2 TACACT  0 t 217 105.85  2.355 0.00150 TACACT  101.65  2.78  1.20
NP_standard 3 ACACTC  0 t 218 85.53 1.999 0.00250 ACACTC  91.94 2.49  -2.04
NP_standard 4 CACTCT  0 t 219 98.15 1.245 0.00075 CACTCT  96.07 2.97  0.55
NP_standard 4 CACTCT  0 t 220 97.17 1.588 0.00275 CACTCT  96.07 2.97  0.29
NP_standard 5 ACTCTT  0 t 221 114.90  0.966 0.00225 ACTCTT  117.13  4.34  -0.41
NP_standard 5 ACTCTT  0 t 222 111.17  3.253 0.00175 ACTCTT  117.13  4.34  -1.09
NP_standard 6 CTCTTT  0 t 223 89.93 1.352 0.00100 CTCTTT  91.31 3.78  -0.29
NP_standard 7 TCTTTC  0 t 224 95.42 2.346 0.00225 TCTTTC  96.32 3.02  -0.24
NP_standard 8 CTTTCC  0 t 225 100.24  1.562 0.00125 CTTTCC  96.86 2.50  1.07
NP_standard 8 CTTTCC  0 t 226 97.96 0.907 0.00075 CTTTCC  96.86 2.50  0.35
NP_standard 8 CTTTCC  0 t 227 99.84 0.680 0.00075 CTTTCC  96.86 2.50  0.94
NP_standard 8 CTTTCC  0 t 228 97.72 0.599 0.00075 CTTTCC  96.86 2.50  0.27
NP_standard 8 CTTTCC  0 t 229 99.57 0.329 0.00100 CTTTCC  96.86 2.50  0.86
NP_standard 8 CTTTCC  0 t 230 97.30 0.147 0.00075 CTTTCC  96.86 2.50  0.14
NP_standard 9 TTTCCC  0 t 231 110.03  1.082 0.00150 TTTCCC  109.95  3.46  0.02
NP_standard 10  TTCCCT  0 t 232 99.48 0.927 0.00075 TTCCCT  101.61  2.56  -0.66
NP_standard 11  TCCCTA  0 t 233 98.43 0.697 0.00100 TCCCTA  100.75  2.31  -0.79
NP_standard 11  TCCCTA  0 t 234 99.59 0.582 0.00125 TCCCTA  100.75  2.31  -0.40
NP_standard 12  CCCTAC  0 t 235 96.39 2.371 0.00125 CCCTAC  100.59  2.83  -1.18
NP_standard 12  CCCTAC  0 t 236 91.60 1.620 0.00300 NNNNNN  0.00  0.00  inf
....
```

**Comment by jts** [comment]
Ok good - next lets try `call-methylation` with a small region of the reference. Can you try this:

```
nanopolish call-methylation <options> "NP_standard:100-500"
```

**Comment by axgraf** [comment]
Great, thank you! So the next step seems to have a problem. 
I tried it with:
```
> nanopolish call-methylation --read sample1.fastq  --bam sample1.minimap2.sorted.bam --genome ref_seq.fasta "NP_standard:100-200"

chromosome	start	end	read_name	log_lik_ratio	log_lik_methylated	log_lik_unmethylated	num_calling_strands	num_cpgs	sequence
[bam process] iterating over region: NP_standard:100-200
[post-run summary] total reads: 11122, unparseable: 0, qc fail: 1, could not calibrate: 2, no alignment: 323, bad fast5: 0
```
That is the whole output I get. I also tried different regions with the same result.

**Comment by jts** [comment]
Can you send me ~50 fast5 files and the reference sequence so I can
reproduce the problem here?

Jared

**Comment by axgraf** [comment]
Hi Jared,
I put the files together. The zip contains 50 Fast5 files and the reference sequence.
[nanopolish_test_data.zip](https://github.com/jts/nanopolish/files/1840835/nanopolish_test_data.zip)
Thank you for your help.

Alex

**Comment by jts** [comment]
Thanks for the data, this was an interesting issue.

As a preprocessing step before methylation calling we group nearby CpGs together. We do this because the signals for nearby CGs may overlap so they need to be considered jointly by the model. By default we merge CGs that are within 10bp of each other. For your data, many of the CGs are within that distance of each other so they are considered as one big group, which is too large to call. 

I've temporarily made a work around by adding a command line parameter `--min-separation`. If you use `--min-separation 5` it will output calls. You should treat this will caution as I'm not sure if the results will be less accurate with lower separation.

**Comment by jts** [comment]
If you test this, please use version b8d0a3a

**Comment by axgraf** [comment]
Hi Jared,
it is working! Thank you very much for your time and effort!

**Comment by weihongqi** [comment]
Dear Jared,

I checked out nanopolish on July 23rd 2018. My local installation was tested by running "nanopolish_test" and analysing the tutorial data set, both of which were successful. But I ran into the same issue posted here with my own dataset. "eventalign" worked, but "call-methylation" returned a file with only the header. I tried with --min-separation 5 but the output file still contained only the header. 

The same dataset was analyzed using tombo, but all minimap2 aligned reads were filtered out due to "Poor raw to expected signal matching", even with least stringent criteria.  

When you have time, could you please help me out? Here you can download the reference sequence and fast5 files:
https://fgcz-gstore.uzh.ch/public/methylation_test/test.tgz

Many thanks in advance,

**Comment by weihongqi** [comment]
Dear Jared,

Here is the output from "call-methylation":
nanopolish call-methylation -t 8 -r test.fastq -b test.sorted.bam -g ref.fasta  > nanopolish_5mC.tsv
[post-run summary] total reads: 3590, unparseable: 0, qc fail: 55, could not calibrate: 0, no alignment: 2, bad fast5: 0

The original fast5 hd 46 k reads, 10% can ba aligned using minimap2. I hope in the sub dataset send to you there are a few mappable reads. Please let me know if you need more fast5 files.

**Comment by jts** [comment]
Can you please open a new issue with this information?

**Comment by lch14forever** [comment]
Hi Jared,

I recently encountered the same issue and found this thread very useful. However, there is still a strange thing -- I got empty output without the '-w' parameter:
```
[post-run summary] total reads: 62437, unparseable: 0, qc fail: 7018, could not calibrate: 647, no alignment: 18958, bad fast5: 0
```
 but managed to get output with the '-w' parameter on a smaller range:
```
| ~> nanopolish call-methylation -t 15 -r N104_BC12.fastq -b N104_BC12.sorted.bam -g ref.fa  -w tig00000055:1-47371 | head
[bam process] iterating over region: tig00000055:1-47371
chromosome	strand	start	end	read_name	log_lik_ratio	log_lik_methylated	log_lik_unmethylated	num_calling_strands	num_motifs	sequence
tig00000055	-	51	59	82f131a9-f852-4bf5-8c74-4f0885241f3b	-2.77	-188.58	-185.81	1	2	TGTCACGTTATTCCGCATC
tig00000055	-	82	82	82f131a9-f852-4bf5-8c74-4f0885241f3b	-7.89	-200.96	-193.07	1	1	TGTTCCGAATA
tig00000055	-	114	128	82f131a9-f852-4bf5-8c74-4f0885241f3b	-8.66	-309.17	-300.52	1	3	CCAGCCGCACCTTCCGATACGGCTA
tig00000055	-	142	142	82f131a9-f852-4bf5-8c74-4f0885241f3b	0.52	-234.01	-234.53	1	1	TGTTACGACTC
tig00000055	-	171	174	82f131a9-f852-4bf5-8c74-4f0885241f3b	2.36	-215.65	-218.02	1	2	ACCTTCGACGGCTA
tig00000055	-	199	205	82f131a9-f852-4bf5-8c74-4f0885241f3b	-6.42	-220.18	-213.76	1	2	TCCACCGGCTTCGGGTG
tig00000055	-	222	236	82f131a9-f852-4bf5-8c74-4f0885241f3b	-16.72	-334.13	-317.42	1	3	ACTCTCGTGGTGTGACGGGCGGTGT
tig00000055	-	252	267	82f131a9-f852-4bf5-8c74-4f0885241f3b	-4.27	-297.38	-293.11	1	3	AGACCCGGGAACGTATTCACCGTAGC
tig00000055	-	284	294	82f131a9-f852-4bf5-8c74-4f0885241f3b	1.28	-298.55	-299.83	1	2	ATCTACGATTACTAGCGATTC
```
Do you have any ideas why?

Regards,
Chenhao

**Comment by Shians** [comment]
Hi Jared,

Is it possible for this issue to be detected in code and a warning or exception raised? I spent a while debugging before finding my way to this issue which resolved the problem, it would have been very helpful if there was output indicating this may have been an issue.

Kind regards,
Shian
