### ISSUE TITLE
nanopolish extract error 

### ISSUE THREAD

**Issue by ma-diroma** [jts/nanopolish#359]
Hi,

I am trying to use nanopolish 0.9.0. My fast5 has no event data

```
FILE_CONTENTS {
 group      /
 group      /Analyses
 group      /Analyses/Basecall_1D_000
 group      /Analyses/Basecall_1D_000/BaseCalled_template
 dataset    /Analyses/Basecall_1D_000/BaseCalled_template/Fastq
 group      /Analyses/Basecall_1D_000/Summary
 group      /Analyses/Basecall_1D_000/Summary/basecall_1d_template
 group      /Analyses/Segmentation_000
 group      /Analyses/Segmentation_000/Summary
 group      /Analyses/Segmentation_000/Summary/segmentation
 group      /PreviousReadInfo
 group      /Raw
 group      /Raw/Reads
 group      /Raw/Reads/Read_101
 dataset    /Raw/Reads/Read_101/Signal
 group      /UniqueGlobalKey
 group      /UniqueGlobalKey/channel_id
 group      /UniqueGlobalKey/context_tags
 group      /UniqueGlobalKey/tracking_id
 }
}
```

Basecalling was performed using MinKNOW 1.11.5.
I have read that since v.0.8, Nanopolish can be run without event-data-containing fast5 files, which lets it work with any basecaller (https://github.com/rrwick/Basecalling-comparison#method), however `nanopolish extract` ends with this error

`no basecalling data suitable for nanoplish`

Could you please help me?
Thanks,
Maria Angela

**Comment by jts** [comment]
Hi,

`nanopolish extract` is for old ONT data, with recent data you should use `nanopolish index`:

https://github.com/jts/nanopolish/#data-preprocessing

Note it is recommended to basecall your reads with albacore, not MinKNOW.

Jared

**Comment by ma-diroma** [comment]
Thank you for your quick reply. So I could get reads.fa file required in the subsequent steps with poretools or other tools?

**Comment by jts** [comment]
The basecaller will output fastq. You should use this fastq with nanopolish.

Jared

**Comment by LidiaBeka** [comment]
Hi Jared, I'm trying nanopolish index on a small set of fast5's (~2500 total) which I believe were base called with MinKNOW but were output from the Epi2me agent in an output folder called "pass-batch" The indexing files that get made:

nanopolish index -d epi2me_pass_batch_1508684229561/ fastq_runid_1df1d4879bfbbbec0317f63437fa25f6456725a2_0.fastq

$ ls -l
50384587 Jun 29 04:13 fastq_runid_1df1d4879bfbbbec0317f63437fa25f6456725a2_0.fastq
7455406 Jun 29 04:27 fastq_runid_1df1d4879bfbbbec0317f63437fa25f6456725a2_0.fastq.index
165870 Jun 29 04:27 fastq_runid_1df1d4879bfbbbec0317f63437fa25f6456725a2_0.fastq.index.fai
6152 Jun 29 04:27 fastq_runid_1df1d4879bfbbbec0317f63437fa25f6456725a2_0.fastq.index.gzi

It runs for a few min and then spits out an error saying:
could not open fast5 file: 

for each fast5 file
If these were basecalled with something other than Albacore should they work with the indexing step as you said? Could something else be wrong here, thanks!
