### ISSUE TITLE
Suggested Pipeline Help

### ISSUE THREAD

**Issue by metacrobe** [jts/nanopolish#36]
Greetings. I was hoping someone could help me understand the canu + nanopolishing pipeline for MinION data and address some errors I get.

Here is a rough idea of what I am doing:
1) Start with passed Metrichor reads
2) Using <poretools fasta> extract fasta reads-->results in single file with PATH in header
3) correction, trimming, unitig construction in canu to build contigs-->results in single *.contigs.fasta file. This fasta file does not have any of the original header data--looks like canu generated details
4) use nanopolish on canu contig output.

I guess this is where I am a bit confused. First I run the following:

make -f scripts/consensus.make READS=data.fasta ASSEMBLY=data.contigs.fasta
where <lambda_HC.fasta> is the output from poretools and
<lambda.contigs.fasta> is the output from canu. 

I get the following message:

[bwa_index] Pack FASTA... 0.00 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.02 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Pack forward-only FASTA... 0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.01 sec
[main] Version: 0.7.5a-r405
[main] CMD: bwa index lambda.contigs.fasta
[main] Real time: 0.362 sec; CPU: 0.027 sec
bwa mem -x ont2d -t 8 lambda.contigs.fasta lambda_HC.pp.fa | samtools view -Sb - > lambda_HC.pp.bam
mem: invalid option -- 'x'
[samopen] no @SQ lines in the header.
[sam_read1] missing header? Abort!
make: *** [lambda_HC.pp.bam] Error 1

I would really appreciate any insight. Best, 
Jarrod

**Comment by jts** [comment]
Hi Jarrod,

Your version of bwa is too old and doesn't support ONT reads (`mem: invalid option -- 'x'`). If you update bwa it should work.

Jared

**Comment by metacrobe** [comment]
Hi Jared, 

Haha! Always something simple. Looks like the program ran without errors.

**Comment by jts** [comment]
Great, I'm going to close this issue but let me know if you have other problems.
