### ISSUE TITLE
Issue with positions while using eventalign

### ISSUE THREAD

**Issue by awjga** [jts/nanopolish#361]
Hi!

I have run into a problem while using eventalign for direct RNA sequencing data.
It seems that some of the positions are shifted for some strands for the same genes.
And I have doubled checked that they are not the reverse strand of sequences.
For example from the results of eventalign:

position | reference_kmer | read_name
-- | -- | --
21 | GGCTC | 62f8da7d-a17a-4285-bc7b-55ba25cb5910
21 | GCTCA | f9d3f66e-3ced-45e8-9661-ea9954fb864f
21 | GGCTC | 5629137f-3789-47d9-892b-c0283ef1e996
21 | GGCTC | 53535cb3-a229-490b-a186-e0c95412dc23
21 | GCTCA | a0f9c131-c580-46db-91df-b29a8218f93d
21 | GCTCA | b60ad0fd-b466-4a12-ac16-a7ec5eca4864
21 | GGCTC | 42d19b2d-5e8c-40d9-9360-a544bd7c487e

There is a shift of one in the example.
Is there any way I can correct this?

Thanks!

**Comment by jts** [comment]
Hmm, that shouldn't happen! I assume they are all from the same reference chromosome/contig?

**Comment by awjga** [comment]
Finally found the issue!
It was due to having spacing in my reference fasta.
After removing all the spacing, and remapping my sequences the issue was solved.
Sorry for the scare and thank you for your reply!
