### ISSUE TITLE
Error: spliced alignments detected when using minimap2

### ISSUE THREAD

**Issue by hasindu2008** [jts/nanopolish#364]
I have been running nanopolish call-methylation on few nanopore data sets. On a certain dataset that contains some ultra long reads (some reads are close to 1 Mbases) I get the following error.

```
Error: spliced alignments detected when loading read e4f54091-8303-4643-8e5d-e07bfa1ef173
Please align the reads to the genome using a non-spliced aligner
Command exited with non-zero status 1
```

Alignment was performed with minimap2 with following options
`minimap2 -x map-ont -a -L -t 32 hg38noAlt.idx fastq.fastq`
Nanopolish was run with the following options.
`nanopolish call-methylation -t 32 -r fastq.fastq -g hg38noAlt.fa -b bam.bam`

The read that causes the error is a very long read (close to 1 Mbases). Is this issue due to the problem with the CIGAR strings longer than 64K? I have tried minimap2 with and without -L option but still get the same error.

**Comment by hasindu2008** [comment]
Yes exactly. The CIGAR string is as follows
1014562S1034756N
The rest of the CIGAR string is in the CG tag

**Comment by jts** [comment]
If you upgrade the htslib submodule to the latest version, does it work?

**Comment by hasindu2008** [comment]
Yes. That worked. Thank you very much.

**Comment by jts** [comment]
Great, I'll update the submodule soon.
