### ISSUE TITLE
Methylation-frequency tsv

### ISSUE THREAD

**Issue by AnjuniPeiris** [jts/nanopolish#365]
Hi,
Thanks for the great piece of software. I just have a few questions about the methylation-frequency tsv file.
I've run the methylation-calling, and I was just wondering what the "called_sites" and "called_sites_methylated" columns refer to, and what's the difference between these two columns, because the number of called sites is higher than the number of CpG sites in a sequence.

I also noticed the "num_cpgs_in_group" was higher than the actual number of CpG sites in the sequence, and I was wondering how this was column was calculated.

What is the "group" referred to in this column? The methylation tutorial tsv file also had "split-group" in the "group_sequence" column as well, and I wanted to confirm what "split-group" meant.

Thanks

**Comment by jts** [comment]
Can you paste an example of an output line to illustrate the issue?

Jared

**Comment by AnjuniPeiris** [comment]
Yep, the top example here has 6 CpG's, but after checking the start and end positions in a genome viewer, I found it has only 5 CpG's. The group_sequence extends outside the given start and end positions, and finds CpG sites outside the start and end positions. Is there a reason for this?

The bottom example has sites where the number of called sites is higher than the number of CpG's. 

![git](https://user-images.githubusercontent.com/36428247/38225001-2307b528-3736-11e8-8bde-230d229318e8.png)

**Comment by jts** [comment]
Since nanopore signals depend on multiple bases, we need to cluster nearby CpGs together and add a bit of flanking sequence to make the call(s). This is what makes up the `group_sequence`. The `num_cpgs_in_group` field is the number of CpGs in the group. For the first case highlighted there are 6 CpGs in the group. Note the `start` and `end` coordinates are the positions of the first and last CpG in the group, they do not include the flanking sequence.

This is the output of the `calculate_methylation_frequency.py` script, which calculates the methylation frequency at the sites using all observed reads. `called_sites` and `called_sites_methylated` are higher here because you had multiple reads that cover these sites.

When you provide the `-s` option to the script it will split the group into individual sites (so if the group has 2 CpGs it will split it into two separate records). In this case it writes `split-group` into the last column. This makes it a little easier for some downstream applications.

I hope this makes sense!

Jared

**Comment by AnjuniPeiris** [comment]
Thanks, that makes sense.
I had one more question about called_sites. I have some methylated sites where the number of called sites is lower than the number of reads that covered that site.
I had a methylated position with one called_site in the tsv, but had 27 reads for that position in the BAM file.
The tsv output is highlighted below, and the reads for the same position in the genome viewer is below that.

![git](https://user-images.githubusercontent.com/36428247/38231206-e186a2a2-3754-11e8-97f3-aae83c882fb6.png)

pcontig_019:1,418,626
Total count: 27
A : 0
C : 2 (7%, 2+, 0- )
G : 0
T : 25 (93%, 25+, 0- )
N : 0
---------------

Can you clarify why the number of called_sites is lower than the number of reads, because it seems like some reads are being ignored?

Also, what are called_sites and called_methylated_sites referring to? I couldn't find a description for them in the documentation.

Thanks

**Comment by jts** [comment]
There is a QC step that may discard reads. In your case it probably discarded most of the reads for this position. I note that most reads are for the `+` strand, which should not happen for normal WGS data. I suspect there was a mapping issue so nanopolish discarded the reads.

`called_sites` is the total number of calls made (= the number of reads that passed all QC checks) and `called_sites_methylated` is the number that were determined to be methylated.

Jared

**Comment by AnjuniPeiris** [comment]
Thanks for that! Yes, it was a mapping issue.

**Comment by jts** [comment]
Great, I'm going to close this but feel free to reopen if you have other questions.

**Comment by qiuyixmm** [comment]
hello! According to your explanation of methylation-frequency tsv file, i compared results between methylation_calls.tsv file and methylation_frequency.tsv file generated by test data included in nanopolish. And i found there were some differences:
    Firstly, i sort methylation_calls.tsv by coordinate using command sort -k 3 -n methylation_calls.tsv. There is a part of sorted methylation_calls.tsv:
![1](https://user-images.githubusercontent.com/30545631/56874435-7432a880-6a6c-11e9-8f37-f60105235e08.png)

     At chr20:4989922 site, 9 long reads can detected CpG and 2 long reads supported ( called? ) methylation with positive log_lik_ratio value.
     And then, i checked the results in methylation_frequency.tsv at the same site:
![2](https://user-images.githubusercontent.com/30545631/56874613-9c6ed700-6a6d-11e9-93b1-d41b2f3df7d4.png)
     The number of called_sites is 4 (not 9) , while the number of called_sites_methylated is 0 (not 2).
     There may exist some misunderstanding of these two results. Could you settle my doubts?
     Additionally, form the results of  methylation_frequency.tsv file, which threshold of methylated_frequency can be set for more reliable methylated site?

**Comment by jts** [comment]
Hi,

Only sites that meet the log-likelihood threshold (by default 2.5) will be counted in methylation_frequency.tsv. I recommend you keep this threshold at its default value.

Jared

**Comment by qiuyixmm** [comment]
@jts  Hello, 
     Thanks for your reply .I cheked the results and found that only the long sequences would be counted for called_sites in methylation_frequency.tsv file when the corresponding absolute values of log-likelihood are bigger than 2.5 .  Is that right?
    And i have an other question : which site in methylation_frequency.tsv file can be considered as more reliable methylated site? Can i use the methylated_frequency values in methylation_frequency.tsv file as evaluation criterion ? If so,  could you recommend a threshold of methylated_frequency to me? 
    Thanks!

**Comment by jts** [comment]
> Thanks for your reply .I cheked the results and found that only the long sequences would be counted for called_sites in methylation_frequency.tsv file when the corresponding absolute values of log-likelihood are bigger than 2.5 . Is that right?

No, that doesn't sound right. Any sequence that meets the log-likelihood criteria should be included.

> And i have an other question : which site in methylation_frequency.tsv file can be considered as more reliable methylated site? Can i use the methylated_frequency values in methylation_frequency.tsv file as evaluation criterion ? If so, could you recommend a threshold of methylated_frequency to me?

The point of using the log-likelihood ratio to filter out ambiguous sites is to avoid needing to filter the frequency calls. I suggest using the frequencies as they appear in the file, but only include sites that have read coverage of at least 10.

Jared
