### ISSUE TITLE
Nanopolish set a breakpoint in malloc_error_break to debug

### ISSUE THREAD

**Issue by slamatic** [jts/nanopolish#366]
When I use the variants call command as followed, I got the error.

nanopolish variants --threads 8 --reads test03.correctedReads.fasta --bam testing03.sorted.bam --genome ../hg38/hg38.fa -w chr13:10000000-30000000  --outfile testing02.eventalign.vcf --ploidy 2 --min-candidate-frequency 0.1 --calculate-all-support

Error Code:
nanopolish(749,0x70000e49b000) malloc: *** error for object 0x7fd6f5f00b00: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
nanopolish(749,0x70000e69e000) malloc: *** error for object 0x7fd6f0d1c530: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Segmentation fault: 11

Could anyone tell me what the error came from? Thank you very much.

**Comment by jts** [comment]
20Mbp is quite a lot to process at once, is it possible it ran out of
memory? Do you get an error if you try smaller windows?

**Comment by slamatic** [comment]
When I tried to use smaller windows, the error still occurred:

nanopolish variants --threads 8 --reads test03.correctedReads.fasta --bam testing03.sorted.bam --genome ../hg38/hg38.fa -w chr13:25000000-30000000  --outfile testing02.eventalign.vcf --ploidy 2 --calculate-all-support
nanopolish(783,0x70000a81c000) malloc: *** error for object 0x7fa9e7c279d0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
nanopolish(783,0x70000a416000) malloc: *** error for object 0x7fa9e9600a20: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
nanopolish(783,0x7fffa68033c0) malloc: *** error for object 0x7fa9e8803050: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
nanopolish(783,0x70000a619000) malloc: *** error for object 0x7fa9e9600a70: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
nanopolish(783,0x70000a213000) malloc: *** error for object 0x7fa9e9600a70: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
nanopolish(783,0x70000ac22000) malloc: *** error for object 0x7fa9e9b0dc50: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Segmentation fault: 11

Could you tell me any possible causes to give this message? Thank you.

**Comment by jts** [comment]
Can you try without the `--calculate-all-support` option?
