### ISSUE TITLE
CentOS compilation error

### ISSUE THREAD

**Issue by gwaldbieser** [jts/nanopolish#367]
I am trying to install on CentOS7
$ gcc --version
gcc (GCC) 7.3.0

nanopolish appeared to install and provide the executable

$./nanopolish
./nanopolish: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./nanopolish)
./nanopolish: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./nanopolish)

Adding the library flags as per issue #239 does not resolve this error. 
Apparently these libraries are not available for CentOS. 
$ strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH

Is there a workaround?

**Comment by jts** [comment]
Hi,

It appears nanopolish compiled correctly (the executable was built) but there is a run-time error because a core C++ library cannot be found. This is not a problem with nanopolish but with your compiler. Did you install gcc-7.3 through a package manager like conda?

Jared

**Comment by gwaldbieser** [comment]
I installed it using yum.

**Comment by jts** [comment]
Hi,

Sorry for the slow response. Is this still an issue?

Jared

**Comment by gwaldbieser** [comment]
Yes, I have not found how to bring in GLIBCXX_3.4.20 or .21.

**Comment by jts** [comment]
You shouldn't have to bring those libraries in, the compiler needs to select the right version during the build.

Can you run the following commands and send me the complete output:

```
make clean
make
ldd nanopolish
```

Thanks,
Jared

**Comment by gwaldbieser** [comment]
I began the make clean but forgot to port the output to a file, stopped the process and restarted, then just decided to delete the directory and start fresh. 

$ git clone --recursive https://github.com/jts/nanopolish.git
Cloning into 'nanopolish'...
remote: Counting objects: 6167, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 6167 (delta 6), reused 13 (delta 4), pack-reused 6147
Receiving objects: 100% (6167/6167), 8.19 MiB | 1.89 MiB/s, done.
Resolving deltas: 100% (4508/4508), done.
Submodule 'fast5' (https://github.com/mateidavid/fast5) registered for path 'fast5'
Submodule 'htslib' (https://github.com/samtools/htslib) registered for path 'htslib'
Cloning into 'fast5'...
remote: Counting objects: 1313, done.
remote: Total 1313 (delta 0), reused 0 (delta 0), pack-reused 1313
Receiving objects: 100% (1313/1313), 473.04 KiB | 675.00 KiB/s, done.
Resolving deltas: 100% (833/833), done.
Submodule path 'fast5': checked out '18d6e346cadb9990ff8287e54447f90e76dd79bc'
Cloning into 'htslib'...
remote: Counting objects: 9855, done.
remote: Total 9855 (delta 0), reused 0 (delta 0), pack-reused 9855
Receiving objects: 100% (9855/9855), 7.21 MiB | 1.97 MiB/s, done.
Resolving deltas: 100% (6877/6877), done.
Submodule path 'htslib': checked out '3dc96c5699a26c5a46e3ccca4092b3801e1874f4'

$ make 1>make.log 2>make.err &
(Files attached)

$ ldd nanopolish
./nanopolish: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./nanopolish)
./nanopolish: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./nanopolish)
        linux-vdso.so.1 =>  (0x00007fff3cdc1000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fe76da09000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fe76d801000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fe76d5f9000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fe76d2f1000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fe76cfe9000)
        libgomp.so.1 => /lib64/libgomp.so.1 (0x00007fe76cdc1000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fe76cba9000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe76c989000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fe76c5c1000)
        /lib64/ld-linux-x86-64.so.2 (0x00005575902bb000)

[make.log](https://github.com/jts/nanopolish/files/2006719/make.log)

**Comment by gwaldbieser** [comment]
Had to split make.err and rename for GitHub.
[makeErr1.txt](https://github.com/jts/nanopolish/files/2006743/makeErr1.txt)
[makeErr2.txt](https://github.com/jts/nanopolish/files/2006744/makeErr2.txt)
[makeErr3.txt](https://github.com/jts/nanopolish/files/2006745/makeErr3.txt)

**Comment by jts** [comment]
Could you try the solution in the first answer here?

https://stackoverflow.com/questions/44205687/glibcxx-3-4-21-not-found-on-centos-7

**Comment by gwaldbieser** [comment]
$ export LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/usr/local/lib64:/usr/lib64
$ make
$ ./nanopolish --help
usage: nanopolish [command] [options]
  valid commands:
    --help
    --version
    call-methylation
    eventalign
    extract
    getmodel
    help
    index
    methyltrain
    phase-reads
    scorereads
    variants
  for help on given command, type nanopolish command --help

$ ldd nanopolish
        linux-vdso.so.1 =>  (0x00007ffe07d91000)
        libz.so.1 => /usr/lib64/libz.so.1 (0x00007f6453a29000)
        librt.so.1 => /usr/lib64/librt.so.1 (0x00007f6453821000)
        libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007f6453619000)
        libstdc++.so.6 => /usr/local/lib64/libstdc++.so.6 (0x00007f6453291000)
        libm.so.6 => /usr/lib64/libm.so.6 (0x00007f6452f89000)
        libgomp.so.1 => /usr/local/lib64/libgomp.so.1 (0x00007f6452d59000)
        libgcc_s.so.1 => /usr/local/lib64/libgcc_s.so.1 (0x00007f6452b41000)
        libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007f6452921000)
        libc.so.6 => /usr/lib64/libc.so.6 (0x00007f6452559000)
        /lib64/ld-linux-x86-64.so.2 (0x00005636602be000)

I placed the export command in my .bashrc and we're good to go. Thanks for all your help. I'm sure other CentOS users will be happy to know this.

**Comment by jts** [comment]
Glad that's fixed! Let me know if you run into any other problems.
