### ISSUE TITLE
nanopolish variants methylation-aware for eukaryotes

### ISSUE THREAD

**Issue by tpshea2** [jts/nanopolish#368]
Hello-

Is it recommended (or necessary) to nanopolish a fungal ONT Canu assembly running nanopolish variants with the methylation-aware option?  Would this be done via "--methylation-aware=cpg" ? 

Or it is not necessary and instead the --methylation-aware option intended only for bacterial assemblies?

Thank you.

**Comment by jts** [comment]
Yes, `--methylation-aware=cpg` should work (assuming that the fungus you sequenced has CpG methylation of course). It is not as well tested as bacterial dam/dcm methylation though.

Jared
