### ISSUE TITLE
Nanopolish on MAC: error: faidx could not get contig length for contig

### ISSUE THREAD

**Issue by AndreDm39** [jts/nanopolish#369]
Hi,

I've installed successfully Nanopolish on my **macOS 10.13.4** following the instruction provided at https://github.com/jts/nanopolish . 
All the tests resulted positive, the index command works as expected but the nanopolish command to compute the consensus sequence doesn't work. To be sure that the problem were not my files, I tried with the example dataset at https://github.com/jts/nanopolish

I first created the indices by using nanopolish index, then:
**python nanopolish_makerange.py reads.fasta | parallel --results nanopolish.results -P 8 ./nanopolish variants --consensus polished.{1}.fa -w {1} --reads draft.fa  -b aligned_sorted.bam -g ref.fa -t 8 --min-candidate-frequency 0.1**

and obtained an error for each contig:
**error: faidx could not get contig length for contig 4b09492e**

To further investigate, I tried to run the nanopolish variant command alone:

**./nanopolish variants --consensus polished.{1}.fa -w {1} --reads draft.fa  -b aligned_sorted.bam -g ref.fa -t 8 --min-candidate-frequency 0.1**

**error: faidx could not get contig length for contig {1}**

Any idea of what is wrong?

**Comment by jts** [comment]
I suspect you have the wrong version of `parallel`. Can you paste the output of running `parallel --version`?

Jared

**Comment by jts** [comment]
Oh sorry I see the problem now:

```
python nanopolish_makerange.py reads.fasta
```

the argument to this command should be `draft.fa`:

Jared
