### ISSUE TITLE
Multiple Rounds of polishing

### ISSUE THREAD

**Issue by metacrobe** [jts/nanopolish#37]
This is not so much an  issue but I wasn't sure where to ask this question. 

**rmnorris** posted a question about a "Second round of nanopolishing". My interpretation of the code that **rmnorris** posted is that this is a single instance of polishing (see below). Indeed, this pipeline looks very similar to that under the nanopolish usage instructions. 

Could you please suggest how to perform additional rounds of polishing or point me to a resource that describes the process? Many thanks!

Code from **rmnorris**
--cp $DIR/2d.fa $DIR/nanopolish2/reads2.fa
--cp $DIR/polished.fa $DIR/nanopolish2/polished.fa
--make -f ~/apps/nanopolish/scripts/consensus.make READS=$DIR/nanopolish2/reads2.fa ASSEMBLY=$DIR/nanopolish2/polished.fa
--python ~/apps/nanopolish/scripts/nanopolish_makerange.py $DIR/nanopolish2/polished.fa | parallel --plain --results $DIR/nanopolish2/nanopolish_results -P 4 ~/apps/nanopolish/nanopolish consensus -o $DIR/nanopolish2/nanopolish_results/nanopolish.{1}.fa -w {1} --r $DIR/nanopolish2/reads2.pp.fa -b $DIR/nanopolish2/reads2.pp.sorted.bam -g $DIR/nanopolish2/polished.fa -t 4
--python ~/apps/nanopolish/scripts/nanopolish_merge.py $DIR/nanopolish2/polished.fa $DIR/nanopolish2/nanopolish_results/nanopolish.*.fa > $DIR/polished2.fa

**Comment by jts** [comment]
Hi,

To do a second round of polishing all you have to do is run the same pipeline, with the output from the first round used as the input genome. In pseudocode it would be like this:

```
./polish.sh draft_assembly.fa > polished_assembly.round1.fa
./polish.sh polished_assembly.round1.fa > polished_assembly.round2.fa
```

**Comment by metacrobe** [comment]
Got it thanks. If there is a more appropriate place to ask questions please let me know.

**Comment by jts** [comment]
I should start a mailing list but until I do that its fine to open issues.

**Comment by metacrobe** [comment]
understood. Thanks again

**Comment by scdcarpenter** [comment]
Hi! So, do the reads need to be re-aligned to the 1x polished assembly before running the consensus algorithm again, or can we use the same .bam file as for the first iteration?

**Comment by jts** [comment]
You need to realign.

Jared
