### ISSUE TITLE
polyA not sequenced in direct RNA sequencing

### ISSUE THREAD

**Issue by Huanle** [jts/nanopolish#370]
Hi,

Can you tellme why i can not find polyA and adapters in the fast5 files of direct RNA sequencing?
Thanks very much.

Huanlee

**Comment by Huanle** [comment]
Hi Jared,

Thanks a lot for your answer.

if the basecaller, e.g., albacore calls sequence for all but the skip adapter+polyA part.  it should have found the delimit in the raw signals that separate it from the mRNA part. I wonder if you know how it manage to do this? i'd love to have a look at its codes (hope i can understand it) and see if it possible to make it generate this information.
it would be nice if you can show me some hints.

anyway, i am interested in your work on this and look forward to seeing your solutions soon.

Thanks a lot.
Huanle

**Comment by jts** [comment]
I don't think it skips the poly-A+adapter, it just calls them poorly. We have an HMM to segment and size the poly-A signal here:

https://github.com/jts/nanopolish/blob/polya-merged/src/nanopolish_polya_estimator.cpp#L163

(cc: @paultsw)

Jared

**Comment by Huanle** [comment]
thanks Jared.
can you tell me how to call polya_estimator in nanopolish?
Kind Regards,
Huanle

**Comment by Huanle** [comment]
Hi Jared,

I have tried nanopolish polya. 
It would be nice if you can let me know more about the output.
Basically, I'd love to know what the headers represent.
'readname        contig  pos     polya_start     polya_end       read_rate       polya_length    num_cliffs      qc_tag' 

thanks a lot.
Huanle

**Comment by jts** [comment]
@paultsw can you describe the output of the poly-a caller?

@Huanle please note this program is still in early development so use the results with caution

**Comment by paultsw** [comment]
Hi @Huanle , the output of the headers representing the following:
* `readname` is the unique ID of the read from the FASTA/FASTQ file;
* `contig` is the contig/sequence in the reference that the read aligns to;
* `pos` is the position on the reference `contig` at which the read-alignment starts;
* `polya_start` is the index of the raw (pico-amp) sample at which our segmentation algorithm declares the poly(A) region of the RNA starts;
* `polya_end` is the index of the sample at which it ends;
* `read_rate` is our estimate of the read rate, i.e. the number of nucleotides moving through the pore per second;
* `polya_length` is our estimate of the number of nucleotides within the poly(A) region of this read;
* `num_cliffs` is a value primarily used for debugging, but essentially this represents the number of (safe to ignore) "spikes" that appear within the raw pico-amp signal corresponding to poly(A) region;
* `qc_tag` is a string that indicates the quality of the estimates in this row; a QC tag of anything except `PASS` means that you should throw away the estimate.

**Comment by Huanle** [comment]
Hi @paultsw ,
thanks heaps for your explanation.
By 'the raw (pico-amp) sample', do you mean the raw signals/squiggles from the fast5 file (e.g., Raw/Reads/Read_#/Signal)?  
So, can i extract the raw signals standing for polyAs by truncating raw signals from fast5 file using the polya_start, polya_end intervals.

I just learned that the numbers in the column 1 represent time points rather than actual positions in the raw signals. So, i wonder how did you get the right 'index'? By using sampling rate (? HZ).

![image](https://user-images.githubusercontent.com/909201/40028494-6c945b44-5822-11e8-9ac4-57a58f9d0827.png)

**Comment by Huanle** [comment]
Hi Paul,

Thanks a lot for your explanation.
But I am still confused. 
![image](https://user-images.githubusercontent.com/909201/40158852-f66f00f8-59e9-11e8-8053-f05e2bb2a38a.png)

Let's take this result generated by `nanopolish polya` as an example and let's assume that this is from the fast5 you showed.

Are '`polya_start`' and `polya_end `  from the numbers in the parentheses (aka, those before signal lines) and thus directly usable as indices to extract signals correspondent to polya region (`Signal[polya_start,polya_end]`)? 

Basicaly, how do `polya_start` produced by your program differ from the numbers/indices shown in the parentheses? 

Thanks again.

**Comment by paultsw** [comment]
Yes, they should be directly usable in the way you stated. They are the same values as the indices in the parentheses.

**Comment by Huanle** [comment]
@paultsw 
thanks.
Btw, why isn't the estimated polyA length not an integer?

**Comment by paultsw** [comment]
The estimator is currently based on an approximation of the read rate (the number of nucleotides moving through the pore per second), which is a floating point value due to the fact that it's an approximation.

We're currently exploring different techniques for estimating the poly-A length, some of which will return an integer estimate.

**Comment by Huanle** [comment]
@paultsw 

thanks a lot.
So may i ask what are the current translocation speed that has been used for this estimation. 
Is this speed different between RNA and DNA sequencing?
I am looking forward to your progress in this interesting topic.

**Comment by paultsw** [comment]
The read rate is variable on a per-fast5 basis, so you will have to look at the `read_rate` column of the output TSV file to find it. We estimate it on a per-read level based on alignment data --- essentially, after throwing away unaligned ends, you can approximate the average read rate by dividing the number of aligned nucleotides by the elapsed time (in seconds) it took for those nucleotides to translocate through the pore. We're currently looking at some methods to improve the variance on this estimate.

And yes, the observed mode of the read rates of DNA and RNA sequencing protocols on a nanopore sequencer are different --- (as of right now) RNA is sequenced at a slower rate (roughly 70bp/s) than DNA (roughly 450bp/s).
