### ISSUE TITLE
The problem about  input file of the old version fast5  for Calling Methylation

### ISSUE THREAD

**Issue by xingjianfeng100** [jts/nanopolish#372]
Hi @jts 
I have downloaded the escherichia coli fast5 file "PRJEB13021" which  you uesd in your study   from ENA, but albacore can't perform to  basecall in R7.3 FAST5 file because of the wrong-match of  CONFIG in "read_fast5_basecaller.py" probably, would you please share the detail that  you use these data to   Calling Methylation ?

**Comment by jts** [comment]
Hi,

Sorry for my slow response to this issue. The data you downloaded is very old and not supported by the latest basecaller (albacore). We have posted some example data that works with the latest basecaller here:

http://nanopolish.readthedocs.io/en/latest/quickstart_call_methylation.html

Jared

**Comment by xingjianfeng100** [comment]
@jts
Thanks for you answer, in fact , I have gotten the output using  other R9 fast5 files.  At present, I have another problem about the output files-- after calculate how often each reference position was methylated using 'calculate_methylation_frequency.py', I get 'methylation_frequency.tsv', but I don't understand why the value in 'called_sites'  column  is '40','150' or more  larger ,when the 'num_cpgs_in_group'  is only "1"or "2" in the file, and  what  does "called_sites" mean ?

**Comment by xingjianfeng100** [comment]
Thank you very much , it helps me a lot.
