### ISSUE TITLE
Nanopolish Variants problem 

### ISSUE THREAD

**Issue by duspriya** [jts/nanopolish#373]
- bwa index draft.fa
- bwa mem -x ont2d -t 8 draft.fa reads.fasta | samtools sort -o reads.sorted.bam -T reads.tmp samtools 
  index reads.sorted.bam
- samtools view reads.sorted.bam | head
- nanopolish variants --consensus polished.fa \-w "tig00000001:200000-202000" \-r reads.fasta \-b reads.sorted.bam \-g draft.fa

I used these command but do not result create so please find the error down.
command 'parallel' from package 'parallel' (universe)
command 'parallel' from package 'moreutils' (universe)
parallel: command not found
problem in nanopolish eventalign do not create a .txt file

**Comment by jts** [comment]
You need to install the missing package (`parallel`).

**Comment by duspriya** [comment]
I install parallel but same problem to nanopolish

**Comment by jts** [comment]
Please post the full command you ran and the error message.

**Comment by duspriya** [comment]
I attachment find please.

**Comment by jts** [comment]
I don't see an attachment.

**Comment by jts** [comment]
You have to use the github website to attach the file to the issue, you can't email it.

**Comment by duspriya** [comment]
I attach png image please check image these my terminal image.

**Comment by duspriya** [comment]
I currently install and try to work in give to github example.

**Comment by jts** [comment]
It appears `parallel` is still not installed.
