### ISSUE TITLE
"Nanopolish" is not recognized as an internal or external command, operable program or bath file.

### ISSUE THREAD

**Issue by Adelaam** [jts/nanopolish#375]
Hello,

I am trying to download nanopolish in my Windows pc, but something I am doing wrong because I get that this error 👍 (base) C:\Users\hmw180>git clone --recursive https://github.com/jts/nanopolish.git
'git' is not recognized as an internal or external command,
operable program or batch file.

(base) C:\Users\hmw180>cd nanopolish

(base) C:\Users\hmw180\nanopolish>git checkout v0.7.1
'git' is not recognized as an internal or external command,
operable program or batch file.

(base) C:\Users\hmw180\nanopolish>make
'make' is not recognized as an internal or external command,
operable program or batch file.

Could you help me with this please?

Thank you

**Comment by jts** [comment]
Sorry but Windows is not a supported platform. You'll have to use Linux.

Jared

**Comment by Adelaam** [comment]
Ok, thank you. I did not know it.

Adela
