### ISSUE TITLE
direct RNA base modification detection with nanopolish

### ISSUE THREAD

**Issue by Huanle** [jts/nanopolish#377]
Hi Jared,

Does nanopolish support RNA base modification detection ?
What are the commands to be used for this purpose ? (nanopolish extract -> minimap2 alignment -> nanopolish eventalign -> nanopolish call-methylation) ?

Thanks.

Huanle

**Comment by jts** [comment]
It doesn't support RNA mods yet.

Jared

**Comment by Huanle** [comment]
thanks Jared.

What makes ONT direct RNAseq difficult and different from DNAseq?

**Comment by jts** [comment]
It is difficult to get good training data for constructing models.

Jared
