### ISSUE TITLE
Missed polish segments

### ISSUE THREAD

**Issue by lye2** [jts/nanopolish#379]
nanopolish version 0.9.0 with parameters:  -t 8 --fix-homopolymers --faster --min-candidate-frequency 0.1

I am polishing the draft assembly for a large grass genome. Only four contigs have similar errors as below. If run the whole contigs without segments, I got the same error. Could you recommend how to fix it? 

nanopolish: src/nanopolish_haplotype.cpp:113: Haplotype Haplotype::substr_by_reference(size_t, size_t) const: Assertion `derived_base_end != m_coordinate_map.size()' failed.
.lsbatch/1525787652.4215321.shell: line 1: 124615 Aborted

**Comment by jts** [comment]
Hi,

I'll need a bit of data to reproduce and fix this problem. Can you follow the instructions here to make a minimal example (eg the smallest possible window) that reproduces the problem?

http://nanopolish.readthedocs.io/en/latest/debug.html

Thanks,
Jared

**Comment by lye2** [comment]
Jared,
Do you have a place that I can upload the data? We are in a company and it is limited on hosting for download.
ThanksLiang 

Sent from Yahoo Mail on Android 
 
  On Tue, May 8, 2018 at 11:56 AM, Jared Simpson<notifications@github.com> wrote:   
Hi,

I'll need a bit of data to reproduce and fix this problem. Can you follow the instructions here to make a minimal example (eg the smallest possible window) that reproduces the problem?

http://nanopolish.readthedocs.io/en/latest/debug.html

Thanks,
Jared

**Comment by jts** [comment]
The best thing would be to host on google drive or dropbox and send me the link by email.

Jared

**Comment by jts** [comment]
Can you paste the command you ran? 

cc @jopineda

**Comment by lye2** [comment]
python /home/an3423/Tools/nanopolish/scripts/extract_reads_aligned_to_region.py -b /ngsassembly/lye/Sorghum/Nanopore/Nanopolish/Map/nanopore.bam -r /ngsassembly/lye/Sorghum/Nanopore/Nanopolish/nanopore.1200.fastq -g  ../utg17808.pilon.pilon.fa -w utg17808.pilon.pilon:100000-106064 -o debug1


    On Tuesday, May 8, 2018, 2:27:58 PM EDT, Jared Simpson <notifications@github.com> wrote:  
 
 
Can you paste the command you ran?

cc @jopineda

**Comment by lye2** [comment]
FYI. The four segments that had the error are all from the ends of four contigs.
    On Tuesday, May 8, 2018, 2:42:26 PM EDT, Liang Ye <yeliang_2004@yahoo.com> wrote:  
 
   python /home/an3423/Tools/nanopolish/scripts/extract_reads_aligned_to_region.py -b /ngsassembly/lye/Sorghum/Nanopore/Nanopolish/Map/nanopore.bam -r /ngsassembly/lye/Sorghum/Nanopore/Nanopolish/nanopore.1200.fastq -g  ../utg17808.pilon.pilon.fa -w utg17808.pilon.pilon:100000-106064 -o debug1


    On Tuesday, May 8, 2018, 2:27:58 PM EDT, Jared Simpson <notifications@github.com> wrote:  
 
 
Can you paste the command you ran?

cc @jopineda

**Comment by jopineda** [comment]
Hi,

To add the fast5 file for a given read, `extract_reads_aligned_to_region.py` uses the path indicated in the readdb file for your `--reads`. I think this error happens when it can't find the fast5 file using this path.
I’ve added a few lines to indicate cases like this in the script. It should tell you at which read id it fails and which path to the fast5 file it is trying to use. Do you mind updating, trying again, and seeing if the path for the fast5 file is right?

Thanks,
Joanna
