### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by druvus** [jts/nanopolish#38]
Hi, 
do you have any plan to make a new minor release soon? It would be preferable to have a referable release that includes the new ONT models.

**Comment by nickloman** [comment]
Current master should have new ONT models?

**Comment by druvus** [comment]
Sorry for being a little bit unclear. The current master have them but I wanted simplify the version tracking as I am planning to update the bioconda recipe to a post 0.4.0 release. Meanwhile I will solve it by referring to a certain commit (i.e. current latest commit) in the conda recipe.

**Comment by afif-elghraoui** [comment]
Are there no plans for a production release after 0.4.0?

**Comment by jts** [comment]
I'm working on supporting R9 data (and other improvements). I'll make a new release after that work is complete.
