### ISSUE TITLE
Polishing no improvement: scrappie related? 

### ISSUE THREAD

**Issue by damientully** [jts/nanopolish#380]
Hi Jared,

I am trying to polish an assembly that was generated from reads base called using Scrappie. I manually made the .readdb file for indexing the reads and I am highly suscipious of the results given that the polished assembly is no better than the original input. Everything ran fine but I know when I get basecall the reads with Albacore and polish my assembly I do get better accuracy as expected. So although Nanopolish did not complain I think a problem must exist somewhere. Any advice or assistance would be greatly appreciated. 

Here is what I did:

`$ bwa index Run12_scrappie.contigs.fasta `

`$ bwa mem -x ont2d -t 10 Run12_scrappie.contigs.fasta Run12_scrappie_reads.fasta | samtools view -Sb - | samtools sort -f - Run12_scrappie.sorted.bam`
`$ samtools index Run12_scrappie.sorted.bam `

`$ nanopolish variants --consensus Run12_scrappie_polished.fa -w "tig00000001:1-9036" -r Run12_scrappie_reads.fasta -b Run12_scrappie.sorted.bam  -g Run12_scrappie.contigs.fasta --fix-homopolymers --min-candidate-frequency 0.1 --ploidy 1
`

`##fileformat=VCFv4.2
##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">
##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">
##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">
##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">
##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
[post-run summary] total reads: 28442, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 1
`

**Comment by jts** [comment]
I suspect it doesn't like something about the index files. There are additional indices in addition to the readdb, did you manually generate these as well?

Did it take a long time to run or did it return almost instantly?

jared

**Comment by damientully** [comment]
It ran in about 10mins. 

Ah I may be missing the .gzi and .index file. How do I generate these manually?

Thanks Jared!

**Comment by jts** [comment]
The easiest (but hacky) way to do it is to backup your .readdb file somewhere, run `nanopolish index yourdata.fastq` (which will create all files, including an empty .readdb) then restore your .readdb file.

**Comment by damientully** [comment]
Yes I can do that but I'm guessing Nanopolish index only takes .fastq not fast as only outputted by scrappie? 

`nanopolish index -d fast5/ Run12_scrappie_reads.fasta
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551611) > this->size() (which is 1)
Aborted
`

**Comment by jts** [comment]
it should work with fasta. can you remove the `-d` option? How are the scrappie reads named?

**Comment by jts** [comment]
I just checked the code and its not compatible with scrappie fasta headers. You'll have to preprocess the reads to clean up the header a bit. If you remove everything after the read name (">readname") it might work.

**Comment by damientully** [comment]
Great! Did that and at least the index worked and nanopolish seems to be working at least it is running for longer than before! 

Thanks again!
