### ISSUE TITLE
Plotting methylation

### ISSUE THREAD

**Issue by pwkooij** [jts/nanopolish#381]
Hi Jared

A question rather than an issue. Do you know if there is a way (or a package) to plot the output of the methylation variant calling onto the original assembly and/or a gene prediction output (I used AUGUSTUS)?

Any help would be appreciated.

Cheers
Pepijn

**Comment by pwkooij** [comment]
Sorry for not replying earlier. I guess what I'm looking for is something where I can project the gene predictions and the methylation calls on top of my genome. I would like to know what genes exactly are affected by the methylation patterns, and prefer to have that visually.

Hope that clarifies it a bit

**Comment by jts** [comment]
Hmm, I don't know of anything off-the-shelf that will do that. If you find something, please let me know!
