### ISSUE TITLE
where is compare_methylation

### ISSUE THREAD

**Issue by HuJane** [jts/nanopolish#382]
Hi there, I cannot find compare_methylation.py in the scripts. May I know where it is ?

**Comment by HuJane** [comment]
Hi there, I downloaded the example and it is there. But when I ran it, an error message appeared (But I checked it with vim, there is no print writing like this):

File "/home/hujie/software/nanopolish/scripts/compare_methylation.py", line 84
    print "key\tdepth_1\tfrequency_1\tdepth_2\tfrequency_2"
                                                          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("key\tdepth_1\tfrequency_1\tdepth_2\tfrequency_2")?

**Comment by HuJane** [comment]
![image](https://user-images.githubusercontent.com/17492179/39973679-47177176-5755-11e8-8302-30c2d70c3699.png)

Hi I found the error mentioned in the original compare_methylation.py and revised it, together with another print error

**Comment by HuJane** [comment]
![image](https://user-images.githubusercontent.com/17492179/39973918-89ad9842-5757-11e8-8cd0-8c8e1ce13974.png)

**Comment by jts** [comment]
Yes, that script was written for python2. I'll update it to be compatible
with python3.

Jared

**Comment by jts** [comment]
I have updated the script in the tutorial to be compatible with python3.
