### ISSUE TITLE
Problem of align draft.fa and reads.fasta

### ISSUE THREAD

**Issue by Hanjiewu** [jts/nanopolish#383]
Hi, I had problem running the quick start tutorial, and here is the problem:

Commend:
bwa mem -x ont2d -t 8 draft.fa reads.fasta | samtools sort -o reads.sorted.bam -T reads.tmp

Messages:
s.sorted.bam -T reads.tmp
sort: invalid option -- 'T'
open: No such file or directory
[bam_sort_core] fail to open file reads.sorted.bam
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 112 sequences (617552 bp)...
[M::mem_process_seqs] Processed 112 reads in 3.999 CPU sec, 4.300 real sec

Please help, thanks

**Comment by jts** [comment]
The version of samtools you are using is too old, please upgrade.

Jared

**Comment by Hanjiewu** [comment]
Thanks, the problem solved.
