### ISSUE TITLE
variant calling doesn't work

### ISSUE THREAD

**Issue by wbranicki** [jts/nanopolish#384]
Hi all,
I have a message after trying to start variant calling. Can you help? thank you in advance. 

src/common/nanopolish_fast5_map.cpp:84: void Fast5Map::load_from_fasta(std::__cxx11::string): Assertion `read_to_path_map.find(seq->name.s) == read_to_path_map.end()' failed.
Aborted (core dumped)

**Comment by jts** [comment]
What command did you run? This indicates a problem with the index file.

Jared

**Comment by wbranicki** [comment]
Dear Jared,


thanks for the prompt feedback. I did basecalling + demultiplexing with albacore, this produced one fastq file for each barcode. This fastq was changed to fasta (MC1R_barcode3.fasta). I used the same fastq for minimap2 to generate sorted bam (genome  HG_GRCh38.fa).


Command for nanopolish was as follows:


nanopolish variants --reads MC1R_barcode03.fasta --bam MC1R_barcode03_sorted.bam --genome HG_GRCh38.fa


Thanks,


Wojciech


________________________________
Od: Jared Simpson <notifications@github.com>
Wysłane: 16 maja 2018 13:27
Do: jts/nanopolish
DW: Wojciech Branicki; State change
Temat: Re: [jts/nanopolish] variant calling doesn't work (#384)


What command did you run? This indicates a problem with the index file.

Jared

-

**Comment by jts** [comment]
Did you run `nanopolish index`?

Jared

**Comment by wbranicki** [comment]
When I am trying to run nanopolish index command then nothing is happening. Its ended after a second and no output files are generated.
I read somewhere that the version of nanopolish might be wrong but then I installed this again and nothing has changed.  Looks like there is no command index. How to check the version of nanopolish?
Thanks.

Wiadomość napisana przez Jared Simpson <notifications@github.com<mailto:notifications@github.com>> w dniu 16.05.2018, o godz. 19:32:


Did you run nanopolish index?

Jared

**Comment by wbranicki** [comment]
I already tried this but its not working. Similarly after using nanopolish index, after a second its finished but nothing has happened. It seems that some commands do not work.

Wojciech

Wiadomość napisana przez Jared Simpson <notifications@github.com<mailto:notifications@github.com>> w dniu 18.05.2018, o godz. 15:21:


Try nanopolish --version.

Jared

**Comment by jts** [comment]
Can you just run `nanopolish` and paste the output?

**Comment by wbranicki** [comment]
ewela@ewela-HP-Z820-Workstation:~/Desktop/nanopolish$ nanopolish
error: no command provided
usage: nanopolish [command] [options]



Wiadomość napisana przez Jared Simpson <notifications@github.com<mailto:notifications@github.com>> w dniu 18.05.2018, o godz. 15:33:


Can you just run nanopolish and paste the output?

**Comment by jts** [comment]
I think the version you have is very old. How did you install it?

**Comment by wbranicki** [comment]
With the commands given in this instruction:

https://github.com/jts/nanopolish/blob/master/README.md#installing-the-latest-code-from-github-recommended




Wiadomość napisana przez Jared Simpson <notifications@github.com<mailto:notifications@github.com>> w dniu 18.05.2018, o godz. 15:51:


I think the version you have is very old. How did you install it?

**Comment by jts** [comment]
Is it possible that you have two versions installed (perhaps one through a package manager like conda) and run you run `nanopolish` the wrong version is used? If you run it like `/path/to/github/version/nanopolish` do you see different output?

**Comment by wbranicki** [comment]
Thank you very much! Yes, indeed. It looks like the wrong version was used. Thanks!

So we have run indexing but got an error: 
./nanopolish index -d barcode03/ barcode03.fasta
Error: duplicate read name 68baaf25-053c-42f6-8f9d-5bc779ae105a found in fasta file

Do you know what is the easiest way to get rid of duplicate names in fasta file? We have generated fastq file using albacore with demultiplexing option. 

Thank you in advance.

**Comment by jts** [comment]
Albacore should not put duplicate reads in a barcoded fastq. I think the right thing to do is to figure out why duplicated reads ended up in barcode03.fasta - perhaps a `cat` command included a file twice?

Jared

**Comment by wbranicki** [comment]
Dear Jared, 

Thank you very much for your help. 
We have figured out what was the problem with duplicated reads. Now we are trying to run nanopolish variants and we've got this error:

./nanopolish variants --reads barcode07.fa --bam barcode07_sorted.bam --genome HG_GRCh38.fa --ploidy=2 
Error: genome has multiple contigs, please use -w to specify input region

We are trying to specify -w now but we are not exactly sure what we should provide here. Will be very grateful for help.
