### ISSUE TITLE
nanopolish extract not recognizing fast5 files

### ISSUE THREAD

**Issue by CourseraSentMe** [jts/nanopolish#386]
nanopolish-0.8.3 running on CentOS7

The nanopolish extract function appears to ask for FAST5 files as an input but then the -b, --basecaller option says it will "consider only data produced by basecaller NAME, optionally with given exact VERSION"

This does not make any sense to me because basecallers take FAST5 as inputs, and produce FASTQ files.

Also, the nanopolish index function calls for "-d nanopore_raw_file_directory reads.fastq"

The reads.fastq and the raw ont signal files (FAST5) are not the same, but they seem to be referred to interchangeably in the help files.

Please send an example of both commands being used with the appropriate file input.
Thank you.

**Comment by CourseraSentMe** [comment]
[yrw4@biolinux nanopolish-0.8.3]$ ./nanopolish extract --help
Usage: nanopolish extract [OPTIONS] <fast5|dir>...
Extract reads in fasta format

      --help                           display this help and exit
      --version                        display version
  -v, --verbose                        display verbose output
  -r, --recurse                        recurse into subdirectories
  -q, --fastq                          extract fastq (default: fasta)
  -t, --type=TYPE                      read type: template, complement, 2d, 2d-or-template, any
                                         (default: 2d-or-template)
  -b, --basecaller=NAME[:VERSION]      consider only data produced by basecaller NAME,
                                         optionally with given exact VERSION
  -o, --output=FILE                    write output to FILE

Report bugs to https://github.com/jts/nanopolish/issues

[yrw4@biolinux nanopolish-0.8.3]$ ./nanopolish index --help
Usage: nanopolish index [OPTIONS] -d nanopore_raw_file_directory reads.fastq
Build an index mapping from basecalled reads to the signals measured by the sequencer

      --help                           display this help and exit
      --version                        display version
  -v, --verbose                        display verbose output
  -d, --directory                      path to the directory containing the raw ONT signal files. This option can be given multiple times.
  -f, --fast5-fofn                     file containing the paths to each fast5 file for the run

Report bugs to https://github.com/jts/nanopolish/issues

**Comment by jts** [comment]
`nanopolish extract` is an old subprogram that was used for data basecalled using albacore <= 2.0, which produced fast5 as output. You can ignore it unless you are working on old data.

Please follow this tutorial for an example of how to run `nanopolish index`:

http://nanopolish.readthedocs.io/en/latest/quickstart_consensus.html
