### ISSUE TITLE
No albacore_output.fastq file after unzipping methylation_example.tar.gz

### ISSUE THREAD

**Issue by francoiskroll** [jts/nanopolish#388]
I am trying to follow the "Quickstart - calling methylation with nanopolish", but I do not have the _albacore_output.fastq_ after unzipping _methylation_example.tar.gz_.

All my commands so far:
```
wget http://s3.climb.ac.uk/nanopolish_tutorial/methylation_example.tar.gz
tar -xvf methylation_example.tar.gz
cd methylation_example
```

`ls` returns:
```
bisulfite.ENCFF835NTC.example.tsv	fast5_files
compare_methylation.py			reference.fasta
```

No _albacore_output.fastq_... Can you help?

**Comment by jts** [comment]
Ah, sorry I made a mistake when updating that .tgz. I'll fix it now, thanks for letting me know.

Jared

**Comment by francoiskroll** [comment]
Cool! Thanks a lot. Can you tell me when it's done so I can download the file again?

**Comment by jts** [comment]
Yep - it should only be a few minutes, I'll post a reply when it is fixed.

**Comment by francoiskroll** [comment]
Yep, looks like it is there now. Thank you very much, much appreciated!

**Comment by jts** [comment]
No problem, sorry for the error.
