### ISSUE TITLE
Question -Nanopore RNAseq data

### ISSUE THREAD

**Issue by isardi** [jts/nanopolish#389]
Hello,
This is a question instead of an issue with the software.  Can I use nanopolish to polish RNAseq reads generated by nanopore sequencing? If it is possible, should I use nanopolish variants --consensus?

Thanks for you help,

ISardi

**Comment by jts** [comment]
Sorry but we don't support polishing with direct RNA data yet but it should be coming soon!

Jared

**Comment by jts** [comment]
(also nanopolish only polishes genome assemblies, it doesn't error-correct reads. If you want to error-correct reads you want to try racon)

**Comment by isardi** [comment]
Thanks for the information! I will try Racon.
