### ISSUE TITLE
seg fault/no-output with consensus

### ISSUE THREAD

**Issue by kpalin** [jts/nanopolish#39]
Trying to polish some slightly assembled reads but nanpolish consensus gives segfault.  It might be the contig names(?)

```
$tail consensus.fasta.fai

1904f9ab-fe41-493c-a6ee-d797ae458a1d_Basecall_2D_2d.0.clustal_CONSENSUS 2567    132119  2567    2568
62cf9ca1-f639-41d8-9533-c262ed303880_Basecall_2D_2d.0.clustal_CONSENSUS 2655    134760  2655    2656
f9c44f7e-1713-4e91-9d22-22da4b91edce_Basecall_2D_2d.0.clustal_CONSENSUS 637     137489  637     638
$ wc -l consensus.fasta.fai 
72 consensus.fasta.fai
$ rm consensus.fasta.fai 

$ nanopolish consensus --verbose --reads basecalls.pp.fa --bam basecalls.pp.sorted.bam --genome consensus.fasta  
[fai_load] build FASTA index.
[fai_fetch_seq] The sequence "" not found
Segmentation fault (core dumped)

```

**Comment by jts** [comment]
This is a bit of poor input handling on my part. The `-w` argument, which specifies what part of the genome to polish, is required. I'll fix this but if you add `-w contig:0-10` to the command it should work.

**Comment by mcretu-umcu** [comment]
Hi,

I have a very similar error I think. I am trying to use "nanopolish variants" though.
I have nanopore data for 1 gene and I use aligned reads (i.e.: not aligned events). 

If I call nanopolish variants without a --window parameter I get:

TODO: train model
TODO: filter data
[fai_fetch_seq] The sequence "" not found
Segmentation fault

..if I call nanopolish WITH a --window parameter (regardless if the interval is 6:10000-20000 or if it is 6:1-2) I get:

TODO: train model
TODO: filter data
[E::hts_open] fail to open file ''
nanopolish: src/alignment/nanopolish_alignment_db.cpp:281: BamHandles _initialize_bam_itr(const string&, const string&, int, int): Assertion `handles.bam_fh != __null' failed.
Aborted

Any idea what could go wrong?

Some additional, general, questions:
- I ran nanopolish consensus before on the same data (had a similar error but fixed it), but the output was ONE haplotype! 
Did I do something wrong? Given that we are diploid, I would need 2 haplotypes (or more, "corrected" possible reads, based on which to perform variant calling)

- Does nanopolish variants output phased or unphased variants? This paper http://www.nature.com/nature/journal/v530/n7589/pdf/nature16996.pdf describes the algorithm a little, but I did not see if the output is phased or not


Best,
Mircea

**Comment by jts** [comment]
It would appear that there is a problem with the .bam or .bai file. Can you delete them and regenerate and see if the error still occurs?

For your second question, nanopolish currently does not support diploid genomes. This will be added in the future.
