### ISSUE TITLE
No "compare_methylation.py" script?

### ISSUE THREAD

**Issue by francoiskroll** [jts/nanopolish#390]
I was looking for the _compare_methylation.py_ script mentioned in the Quickstart about methylation, but could not find it. A shame, sounded handy!

Can I find it anywhere?

**Comment by jts** [comment]
Is it not in the .tar.gz that I uploaded? I hope I didn't make another
mistake!

Jared

**Comment by francoiskroll** [comment]
Ah, this is what I thought when I read that it was "included". But no, I cannot see a _/scripts_ folder in the _.tar.gz_...

**Comment by jts** [comment]
There isn't a scripts directory, it should be in the `methylation_example` folder. I just checked my local version and found it, can you check again?

**Comment by francoiskroll** [comment]
Ah, you are right. As the first one was not there, I was looking for _compare_methylation.py_ on the Github too. Apologies! Thanks a lot.

**Comment by jts** [comment]
No problem!
