### ISSUE TITLE
Could you help to explain -w in variants calling mudole?

### ISSUE THREAD

**Issue by ykjyhmj** [jts/nanopolish#392]
In the manual, it just said
` -w, --window=STR                     find variants in window STR (format: <chromsome_name>:<start>-<end>)`
I can't understand what's STR.

By the way, my purpose is trying to use nanopore raw sequence to polish my assembly. So the assembly has multiple contigs. I don't know how to define this -w parameters in this situation.

**Comment by jts** [comment]
The `-w` parameter tells nanopolish which region of the genome to polish. For example `-w contig1:50,000-100,000` will polish from the 50,000th to 100,000th base on contig1. We provide a helper script to polish the whole genome, see here:

https://github.com/jts/nanopolish#computing-a-new-consensus-sequence-for-a-draft-assembly

**Comment by ykjyhmj** [comment]
Hi, jts,
Thanks for the reply. I am wondering if polish the genome with 50kb window, will it make the genome more fragmented? And if some nanopore reads cover two contigs, if these two contigs can be merged during the polish step?

**Comment by jts** [comment]
After you polish each 50kb window it will merge the results together into polished contigs. It will not merge two contigs that are spanned by reads though.
