### ISSUE TITLE
compilation error | fail

### ISSUE THREAD

**Issue by nbx0** [jts/nanopolish#394]
OS: Ubuntu 16.04

I'm having trouble compiling with 'make'. The errors and warnings appear to be related to hdf5 sources but I can not really tell. The make log is attached and any advice is greatly appreciated!

Thanks and Cheers,
Ben

[make.log](https://github.com/jts/nanopolish/files/2050144/make.log)

**Comment by jts** [comment]
Hi,

It looks like it compiled to me, does the program not run?

**Comment by nbx0** [comment]
Thanks for the rapid reply! I'm just getting the generic:

~/nanopolish$ nanopolish
The program 'nanopolish' is currently not installed. You can install it by typing:
sudo apt install nanopolish


-Ben

**Comment by jts** [comment]
Can you try running as `./nanopolish`

**Comment by nbx0** [comment]
Success, thank you! I added to my $PATH and now we're cookin'.

**Comment by jts** [comment]
Great!
