### ISSUE TITLE
Variant calling issues

### ISSUE THREAD

**Issue by wbranicki** [jts/nanopolish#395]
Dear Jared,

Thank you very much for your help.
We have figured out what was the problem with duplicated reads. Now we are trying to run nanopolish variants and we've got this error:

./nanopolish variants --reads barcode07.fa --bam barcode07_sorted.bam --genome HG_GRCh38.fa --ploidy=2
Error: genome has multiple contigs, please use -w to specify input region

We are trying to specify -w now but we are not exactly sure what we should provide here. Will be very grateful for help.
wbranicki

**Comment by jts** [comment]
Please see the discussion here: 

https://github.com/jts/nanopolish/issues/392

**Comment by wbranicki** [comment]
Thanks a lot Jared!

Variant caller worked but we wanted to take a step back now and wonder if in our case we should do the polishing of the genome part. 
In our case we have produced amplicons and for the purpose of the mapping we are using human genome reference. Therefore I wonder if computing a new consensus sequence makes sense here? Is it possible to polish when we have amplicons and we don't compute draft genome assembly but just using human reference? 

We are very grateful for help!
Best regards, 
wbranicki

**Comment by jts** [comment]
You should only align to the reference genome when calling variants. Polishing a consensus sequence is not needed.
