### ISSUE TITLE
Installation issue make: *** No rule to make target `

### ISSUE THREAD

**Issue by ebioman** [jts/nanopolish#397]
Hi
I am trying to provide nanopolish for our cluster generating a CentOS7 rpm.
Since we build in a sandbox we have to install all dependencies independently and then provide them for nanopolish building.

I am running into issues towards pretty much the end of building:

    make: *** No rule to make target `-I/software/UHTS/Analysis/HTSlib/1.4/lib', needed by `nanopolish'.  

With the following make command provided:

    make %{?_smp_mflags} HDF5=noinstall EIGEN=nofetch HTS=noinstall  \
      HTS_LIB="-L$HTSLIB_PATH/lib" \
      HTS_INCLUDE="-I$HTSLIB_PATH/include"  \
      H5_INCLUDE="-I/software/include"\
      EIGEN_INCLUDE="-I$EIGEN_INCLUDEDIR"

It looks as if the make command does not take it as a proper include variable but a build target.
But then your syntax is rather unusual and from the Makefile it is less clear whether one has to provide directories or a particular file instead (the latter fails quickly in my case).

**Comment by jts** [comment]
Currently the Makefile supports two modes of operation:

1) build all required dependences automatically (for most users, who do not have sudo privileges)
2) do not build any dependencies and use system-wide installs of hdf5/htslib/etc (in /usr/local or wherever)

It looks like you're trying a third mode where you want to use pre-built dependencies outside of the usual library search paths. If you remove the `HTS_LIB` assignment from the `make` command, but put the path to htslib on your `LD_LIBRARY_PATH` (or some other library directory that gcc will search), does it work?

**Comment by jts** [comment]
I'm not sure why the linker failed to resolve that dependency but I'm glad you were able to work around it.

If you compile the default, non-threadsafe, HDF5 then threading will be turned off for some parts of nanopolish. This may make the program unusably slow. The incompatibility of the threading options in HDF5 is another reason why that dependency is built automatically.

jared

**Comment by ebioman** [comment]
thx, I guess I will have to build a local work-around for hdf

**Comment by jts** [comment]
No problem, sorry for the difficulties. I'm starting to think about transitioning to a more flexible build system.

Jared
