### ISSUE TITLE
HDF5 dependency infinite loop 

### ISSUE THREAD

**Issue by lukea-bioinf** [jts/nanopolish#398]
Server OS: Linux andromeda 4.4.126

I'm trying to install nanopolish on our server (to a virtual environment) using the default options.
When executing 'make' the compilation is getting stuck in an infinite loop when installing the HDF5 dependency. I'm not experienced in dealing with these sorts of problems and so I'm unsure of how to resolve the issue. Any help would be very much appreciated.
The log can be found below.

Many thanks in advance.
Luke

[make.log](https://github.com/jts/nanopolish/files/2067642/make.log)

**Comment by jts** [comment]
That is very strange. What version of `make` and `gcc` are you using?

**Comment by jts** [comment]
I think I see a problem. Can you try to change this line: 
https://github.com/jts/nanopolish/blob/master/Makefile#L31

to:

```
H5_LIB=./lib64/libhdf5.a
```

**Comment by weir12** [comment]
I have changed line 32: `H5_LIB=./lib/libhdf5.a` to `H5_LIB=./lib64/libhdf5.a` of Makefile
It's seem doesn't work.Same error was reported.

**Comment by jts** [comment]
Ok, thanks for trying.

**Comment by jts** [comment]
One more try. Can you start from a completely fresh clone (with `--recursive`), copy [this](https://gist.github.com/jts/4fd5a12b55c91986d59b6c35105247a9) into the directory and run `make`? I'd like to see if this fixes the infinite loop issue.

**Comment by weir12** [comment]
fine.I have copied modified Makefile into a new nanopolish folder(download by git clone master-branch of nanopolish,fast5 ,htslib) .And run `make`.
such error was reported:
`Makefile:120: .depend: No such file or directory
make: *** No rule to make target `lib64/libhdf5.a', needed by `.depend'.  Stop.
`
TA for your help

**Comment by jts** [comment]
Hi,

Sorry I meant the Makefile in this gist, not the one I asked you to modify: 

https://gist.github.com/jts/4fd5a12b55c91986d59b6c35105247a9

Jared

**Comment by weir12** [comment]
Thanks!.I have resolve installaton problem by conda envirement

Liang Ou
Bioinformatics Platform
Institut Pasteur of Shanghai
Chinese Academy of Sciences (CAS)
Shanghai, China


发件人: Jared Simpson
发送时间: 2018年6月27日 20:25
收件人: jts/nanopolish
抄送: weir12; Comment
主题: Re: [jts/nanopolish] HDF5 dependency infinite loop (#398)

Hi,
Sorry I meant the Makefile in this gist, not the one I asked you to modify:
https://gist.github.com/jts/4fd5a12b55c91986d59b6c35105247a9
Jared

**Comment by jts** [comment]
@lukea-bioinf can you test the Makefile I posted above to see if it fixes the infinite loop?
