### ISSUE TITLE
Errors while running nanopolish. Polished result of 0 bytes!

### ISSUE THREAD

**Issue by athulmenon** [jts/nanopolish#40]
Hi,

I run the nanopolish to Ecoli assembly I did with miniasm. This is the first time I am using nanopolish. I came to see these errors while running the commands.

`make -f /home/gba4/Documents/programs/nanopolish/scripts/consensus.make READS=NormalTwoDirectionReads.fasta ASSEMBLY=Normalminiasm.fa`

`python /home/gba4/Documents/programs/nanopolish/scripts/nanopolish_makerange.py Normalminiasm.fa | parallel --results nanopolish.results -P 4 /home/gba4/Documents/programs/nanopolish/nanopolish consensus -o nanopolish.{1}.fa -w {1} --r NormalTwoDirectionReads.pp.fa -b NormalTwoDirectionReads.pp.bam -g Normalminiasm.fa -t 4`

I got a list of errors like.

`nanopolish: src/alignment/nanopolish_anchor.cpp:36: HMMRealignmentInput build_input_for_region(const string&, const string&, const Fast5Map&, const string&, int, int, int): Assertion `bam_idx != __null' failed.
`
after that I ran ...

`python /home/gba4/Documents/programs/nanopolish/scripts/nanopolish_merge.py Normalminiasm.fa nanopolish.*.fa > Normalminiasmpolished.fa`

A long list of  errors came like...

`ERROR_MISSING utg000001l 0
ERROR_MISSING utg000001l 1`

And file is created with 0 bytes.
Can you please tell me the issue? Thanks in advance.
Athul

**Comment by JohnUrban** [comment]
While waiting for better advice, perhaps this could help. I could be wrong, but it looks like the error might be complaining that a BAM file is not indexed. Is your BAM indexed? If not, try indexing it (samtools index file.bam). Then try start over (from the step the BAM is used).

**Comment by jts** [comment]
I agree with @JohnUrban

**Comment by athulmenon** [comment]
Hi John and jts,
Thank you.
It was the problem with the bwa version. I updated it and it worked like a charm!
But presently my error is different after running..

`python /home/gba4/Documents/programs/nanopolish/scripts/nanopolish_makerange.py Normalminiasm.fa | parallel --results nanopolish.results -P 4 /home/gba4/Documents/programs/nanopolish/nanopolish consensus -o nanopolish.{1}.fa -w {1} --r NormalTwoDirectionReads.pp.fa -b NormalTwoDirectionReads.pp.bam -g Normalminiasm.fa -t 4`

Error pops out like..


`error: no path associated with read 0.channel_9_read_93_twodirections_/dev/shm/downloads/LomanLabz_E.coli_MG1655_3311_1_ch9_file98_strand.fast5
`
Any idea?

Regards,
Athul

**Comment by jts** [comment]
poretools puts the path to the FAST5 file In the FASTA header (in `NormalTwoDirectionReads.fa`). This path must be accessible from your current working directory. Did you move this file (or the FAST5s) before running nanopolish?

**Comment by athulmenon** [comment]
True it is not in the path. Thanks alot!

Athul

**Comment by bweestyle** [comment]
Hi I am getting the same error as above:

error: no path associated with read

I extracted my data with my own script and do not have the NormalTwoDirectionReads.fa

Is there a workaround for this? or do I just have to go install poretools?

Thanks
Brendan
