### ISSUE TITLE
Feeding methyltrain with a model-file

### ISSUE THREAD

**Issue by fneuh** [jts/nanopolish#400]
Hi Jared,

I wanted to train a model on some methylation data, and therefore built the model-file below as a initial model.

#ont_model_name r9.4_180mv_450bps_6mer
#kit    r9.4_450bps
#strand template
#kmer   6
#Alphabet       nucleotide
#original_file  r9.4_450bps.cpg.6mer.template.model
"k_mer" "mean_level"    "level_stdv"
"AAAAAA"        86.9596 1
"AAAAAC"        83.4465 1
"AAAAAG"        84.2015 1
"AAAAAM"        84.0604 1
"AAAAAT"        86.5058 1
"AAAACA"        77.3163 1
....

I made a pointer-file (model.txt) giving the location of the model and gave that into methyltrain:

nanopolish methyltrain -m /home/../model.txt --rounds 10 -r $FASTQ -b $BAM -g $REF_SEQ

It throws this error:

nanopolish: src/pore_model/nanopolish_poremodel.cpp:114: PoreModel::PoreModel(std::string, const Alphabet*): Assertion `pmalphabet != nullptr' failed.
/var/spool/slurmd/job34279/slurm_script: line 11: 89040 Aborted                 nanopolish methyltrain -m /home/../model.txt --rounds 10 -r $FASTQ -b $BAM -g $REF_SEQ

Will be very grateful for help,
Florian

**Comment by jts** [comment]
Hi @fneuh,

I think `#Alphabet` should be `#alphabet`

jared

**Comment by fneuh** [comment]
Hi Jared,

thanks for your advice, I implemented your recommendations, my model-file now looks like this:

#ont_model_name r9.4_180mv_450bps_6mer
#kit    r9.4_450bps
#strand template
#k      6
#alphabet       cpg
#original_file  r9.4_450bps.cpg.6mer.template.model
k_mer   mean_level      level_stdv
AAAAAA  86.9596 1
AAAAAC  83.4465 1
AAAAAG  84.2015 1
AAAAAM  84.0604 1
AAAAAT  86.5058 1
...

Now I get this error:

nanopolish: src/pore_model/nanopolish_poremodel.cpp:121: PoreModel::PoreModel(std::string, const Alphabet*): Assertion `ninserted == states.size()' failed.
/var/spool/slurmd/job34283/slurm_script: line 11: 37480 Aborted                 nanopolish methyltrain -m /home/../model.txt --rounds 10 -r $FASTQ -b $BAM -g $REF_SEQ

I did change the alphabet from nucleotide to cpg, running methyltrain with _#alphabet nucleotide_ gave me the same error.. 

Could you help me with that?

**Comment by jts** [comment]
The header column names are incorrect, they must exactly match what nanopolish expects. See here for an example:

https://github.com/jts/nanopolish/blob/master/etc/r9-models/r9.4_450bps.nucleotide.6mer.template.model#L6

**Comment by fneuh** [comment]
Thanks, it works now !

On a related topic: My goal was to train a model that contains the k-mers of 6 bases: A,C,G,T,M and a sixth base called X. I got all k-mers and some starting values for the level_mean and level_stdv. 

#ont_model_name r9.4_180mv_450bps_6mer
#kit    r9.4_450bps
#strand template
#k      6
#alphabet cpg
#original_file  r9.4_450bps.cpg.6mer.template.model
kmer    level_mean      level_stdv
AAAAAA  86.35714        1
AAAAAC  83.90841        1
AAAAAG  85.87108        1
AAAAAX  84.38237        1
AAAAAM  84.40784        1
AAAAAT  84.84753        1
...

Taking your corrections into account, it still throws an error:

nanopolish: src/pore_model/nanopolish_poremodel.cpp:121: PoreModel::PoreModel(std::string, const Alphabet*): Assertion `ninserted == states.size()' failed.
/var/spool/slurmd/job34291/slurm_script: line 11: 73826 Aborted                 nanopolish methyltrain -m /home/../model.modified.txt --rounds 10 -r $FASTQ -b $BAM -g $REF_SEQ

I then removed  the line _#alphabet cpg_ from the model, and got this:

nanopolish: src/pore_model/nanopolish_poremodel.cpp:114: PoreModel::PoreModel(std::string, const Alphabet*): Assertion `pmalphabet != nullptr' failed.
/var/spool/slurmd/job34292/slurm_script: line 11: 74625 Aborted                 nanopolish methyltrain -m /home/../model.modified.txt --rounds 10 -r $FASTQ -b $BAM -g $REF_SEQ

I suspect this is because nanopolish doesn't recognize the used alphabet, as the used bases don't match the alphabets defined in 
https://github.com/jts/nanopolish/blob/master/src/common/nanopolish_alphabet.cpp

Is there a way of doing this without having to change the source-code for nanopolish?
Suggestions on that would be much appreciated! 

Florian

**Comment by jts** [comment]
This requires changing the source code to nanopolish. You need to implement a new type of alphabet that understands the "X" character. Hopefully the existing code can act as a guide to how to do this, if not feel free to ask questions.

Jared

**Comment by fneuh** [comment]
Hi Jared,

I went by #157 and thought that I will have to make changes to nanopolish_alphabet.h and nanopolish_alphabet.cpp

In nanopolish_alphabet.cpp I don't understand what you are doing with:

const uint8_t MethylCpGAlphabet::_rank[256] = {0,0,....}
https://github.com/jts/nanopolish/blob/master/src/common/nanopolish_alphabet.cpp#L67

Could you help me with that? 

Thanks,
Flo

**Comment by jts** [comment]
The `_rank` table maps an ASCII character code to an index into the alphabet. For the simple DNA alphabet ("ACGT") the map is { 'A' -> 0, 'C' -> 1, 'G' -> 2, 'T' -> 3 }. This allows nanopolish to efficiently calculate the lexicographic rank for any k-mer in the alphabet. For other alphabets (like those with an "M" symbol added) the rank table is similar.

**Comment by fneuh** [comment]
Ok thanks for the quick response, the training now works!

In order to test the accuracy of the newly trained model I wanted to call some data with it. The process of _call-methylation_ doesn't throw an error but it produces empty output-files.

In _nanopolish_alphabet.cpp_ I defined various recognition sites for the new alphabet (A,C,G,M,T,X) and I am suspicious of them leading to empty output.

The corresponding code looks something like this:

const uint32_t NewAlphabet::_num_recognition_sites = 2;
const uint32_t NewAlphabet::_recognition_length = 2;
const char* NewAlphabet::_recognition_sites[] = { "CA", "CA" };
const char* NewAlphabet::_recognition_sites_methylated[] = { "MA", "XA" };
const char* NewAlphabet::_recognition_sites_methylated_complement[] = { "AM", "AX" };

Here the methylated "counterpart" of the genomic motif CA, could be either MA or XA.
Could you give me your opinion on this? Is it even possible to propose more than one modification for the same recognition sequence in nanopolish?

Help on this would be much appreciated,
Florian

**Comment by jts** [comment]
Right now call-methylation will only use the cpg alphabet. I need to merge the recent pull request from @mike-molnar before you can specify the alphabet to use during calling. I'll try to do this soon.

Jared

**Comment by fneuh** [comment]
I see you have merged mike-molnar's pull request. I'll be taking a look in the changes, thanks again for your help!

Florian

**Comment by jts** [comment]
No problem, let us know if you need help.

Jared
