### ISSUE TITLE
nanopolish index fails without error

### ISSUE THREAD

**Issue by lskatz** [jts/nanopolish#401]
When I ran nanopolish incorrectly, it did not give me an indication of error until I got to the `nanopolish variant` step.  Ideally, it should give an error if I did it incorrectly.  In my case, I did not understand it well enough and instead supplied an empty directory with `-d`.  This resulted in the creation of all expected files and no stdout and no stderr.

**Comment by jts** [comment]
Hi @lskatz,

What version are you using? When I run `index` on an empty directory I get an error message:

```
nanopolish index -d empty_dir/ test.fastq 
[readdb] indexing empty_dir/
Error: no fast5 files found
```

Jared

**Comment by lskatz** [comment]
v0.8.3

**Comment by jts** [comment]
Ok, this error message appeared in 0.9.0.

**Comment by lskatz** [comment]
I'd say that this is a closed issue then!  Thank you!
