### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by weir12** [jts/nanopolish#407]
Hi~
     When I trying to install nanopolish with command:
     `make - HDF5=noinstall`    （because HDF5  is installed already ）
      I  saw the following error:

`src/nanopolish_call_methylation.cpp:36:23:(url)fatal error: H5pubconf.h: No such file or directory
 #include "H5pubconf.h"
                       ^
compilation terminated.
src/nanopolish_methyltrain.cpp:39:23: fatal error: H5pubconf.h: No such file or directory
 #include "H5pubconf.h"
                       ^
compilation terminated.
src/nanopolish_phase_reads.cpp:38:23: fatal error: H5pubconf.h: No such file or directory
 #include "H5pubconf.h"
                       ^
compilation terminated.
src/nanopolish_scorereads.cpp:37:23: fatal error: H5pubconf.h: No such file or directory
 #include "H5pubconf.h"
                       ^
compilation terminated.
src/alignment/nanopolish_eventalign.cpp:35:23: fatal error: H5pubconf.h: No such file or directory
 #include "H5pubconf.h"
                       ^
compilation terminated.
make: *** [.depend] Error [1]`

Should I edit Makefile to fit my system environment ?

**Comment by jts** [comment]
I recommend you allow nanopolish to compile HDF5 as the system-wide HDF5 is probably not threadsafe. If you really want to use the system-wide version then yes you'll have to change `H5_LIB` and `H5_INCLUDE`.

Jared

**Comment by jts** [comment]
I made a reply in the other thread with a problem I spotted, could you try it and see if it works?
