### ISSUE TITLE
Running nanopolish --variants in the whole genome

### ISSUE THREAD

**Issue by isardi** [jts/nanopolish#408]
Hi,

I have a genome containing 27 chromosomes.  I tried to run nanopolish to generate a consensus file with all variants found in my nanopore reads.  To do so, I run the following code:

python nanopolish_makerange.py Mygenome.fasta | parallel --results nanopolish.results -P 8 \
nanopolish variants --consensus polished.{}.fasta -w {} -r Mygenome.fastq -b Mygenome_sorted.bam -g Mygenome.fasta -t 16 --min-candidate-frequency 0.1

The programs runs for the first chromosome and then stops.  Is there a way to fix this issue so that it runs for all the 27 chromosomes?

Thanks for your help.

-Isa

**Comment by jts** [comment]
Hi,

That command should work across all chromosomes. What does the output of `python nanopolish_makerange.py Mygenome.fasta` show?

Jared

**Comment by jts** [comment]
I think there is something wrong with your `parallel` command. The `{}` tokens should be `{1}`
