### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by snunzi** [jts/nanopolish#409]
Hi all, 
I am having trouble getting nanopolish to compile. I followed instructions from readme and did the recursive clone of the git repository I get the following error even though when I run "whereis zlib" it returns "zlib: /usr/include/zlib.h /usr/share/man/man3/zlib.3.gz"

Any tips would be much appreciated!

g++ -o src/nanopolish_read_db.o -c -g -O3 -std=c++11 -fopenmp -fsigned-char -I./include -I./htslib -I./fast5/include -I./src -I./src/hmm -I./src/thirdparty -I./src/thirdparty/scrappie -I./src/common -I./src/alignment -I./src/pore_model -I./eigen/ -fPIC src/nanopolish_read_db.cpp
src/nanopolish_read_db.cpp:9:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
          ^~~~~~~~
compilation terminated.
make: *** [src/nanopolish_read_db.o] Error 1

**Comment by jts** [comment]
What operating system are you running?

**Comment by jts** [comment]
You might have to install the zlib development package:

```
yum install zlib-devel
```

**Comment by snunzi** [comment]
The zlib-devel package seems to be installed and found on my computer (see
below). I will continue to play with getting it to compile, but I can't
find where it trying to locate zlib. Is there a line somewhere I can edit
so it can find the correct location?

>rpm -qa | grep zlib
zlib-devel-1.2.7-17.el7.x86_64


zlib-1.2.7-17.el7.x86_64

**Comment by snunzi** [comment]
Problem solved, I installed as root and everything compiled fine. Thank you for your help.
