### ISSUE TITLE
spliced alignments detected when using minimap2

### ISSUE THREAD

**Issue by weir12** [jts/nanopolish#411]
Hi:
I have get into similar trouble like #364 
When I use `nanopolish variants --snp -r "/home/weir/tair/20180404-RDS03-YF3/GA30000/G30000.fastq"  -b "/home/weir/output/sixrun/Col0YF.sorted.bam" -g "/home/weir/output/Araport11_genes.201606.cdna.fasta"  -p 2 -t 6 -w AT1G01300.1:530-550
`
`Error: spliced alignments detected when loading read 6eb6a1ac-fe74-4bed-9ea4-210191388dbd
Please align the reads to the genome using a non-spliced aligner
`
However,my nanopolish was just installed.I think htslib is the latest version.
By the way,Alignment was performed with minimap2 with following options:
`minimap2 -ax splice -uf -k14 ref.fa direct-rna.fq > aln.sam `
Thanks

**Comment by jts** [comment]
Hi,

Currently nanopolish does not support calling variants from spliced alignments.

Jared

**Comment by weir12** [comment]
So,I should use non-spliced aligner(like "BWA-MEM") to mapping reads to genome sequence?

**Comment by jts** [comment]
Right now we don't recommend calling variants from direct RNA/cDNA reads. If you really want to try, you can align in non-spliced mode (with minimap2) to a transcript database.

Jared
