### ISSUE TITLE
raw signal extraction from fast5

### ISSUE THREAD

**Issue by wxuzhang** [jts/nanopolish#413]
Hi, I am trying to extract raw current signal from fast5 dataset. What I could see in the fast5 dataset, the raw signal is encoded by Huffman code. I am wondering how I could retrieve the real current signal from this file. 
I get some info from https://github.com/jts/nanopolish/issues/89
But, I am not clear how to do it correctly. Could you please explain it to me? Thank you very much!

**Comment by jts** [comment]
Hi,

Nanopolish doesn't have a function to export the raw signal. You can use the `h5dump` program that comes with `hdf5` to do this. The signal is in the `Raw/Reads/Read_nnnn/Signal` group where `Read_nnnn` is the ID of the read in the hdf5 file.

Jared

**Comment by wxuzhang** [comment]
Thanks for your reply! I could use h5dump to extract the raw signal. However, that number does not make sense for me since it does not seem to match the current signal from experiment. Could you please explain the relation between raw signal in the file and real current signal in the experiment? Thanks!

**Comment by jts** [comment]
The values stored in the file are raw measurements from the device. To convert them to picoamps you need to use the `range`, `digitisation` and `offset` constants. Here is the function in nanopolish that converts from DAC values to pA:

https://github.com/jts/nanopolish/blob/master/src/common/nanopolish_fast5_io.cpp#L129

**Comment by wxuzhang** [comment]
Thanks! I got it!
