### ISSUE TITLE
Is "nanopolish variants --consensus" stuck on something?

### ISSUE THREAD

**Issue by csm1209** [jts/nanopolish#416]
Hello jts,

This is my initial command:

> nanopolish variants --consensus c_cha_polished_assembly.fasta \
> -w "tig00000001:1-2911167" \
> -r input_reads_nanopolish.fastq.gz \
> -b c_chang_reads.sorted.bam \
> -g /mnt/home/nbrnvofj/Canu/c_chang_assembly/c_chang.contigs.fasta

I ran it and left it overnight (~12 hrs), and it's still stuck on this display:

> ##fileformat=VCFv4.2
> ##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">
> ##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">
> ##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">
> ##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">
> ##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">
> ##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
> #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample

I tried tacking on "--verbose" and even "-t 20" to see if it would give me some indication that it's working but it stays on the same message again and doesn't seem to be doing anything or creating any output.

Is this normal, am I just being impatient or am I doing something wrong? I should also mention that I did not use "nanopolish_makerange.py" to segment my genome. If I need to use this can you show me specifically how I would structure the command? There aren't specific instructions on makerange in the Nanopolish Documentation.

Thank you!!

Carl

**Comment by jts** [comment]
Depending on the amount of coverage you have, it could take quite awhile to load the reads for the entire genome. Also, you might want to check the process is not out of memory and swapping. 

There are instructions on using makerange here:

https://github.com/jts/nanopolish#computing-a-new-consensus-sequence-for-a-draft-assembly

I recommend using makerange, each window should only take a few minutes to compute so you'll have a better indication of progress.

Jared

**Comment by csm1209** [comment]
Thanks for getting back so quick, Jared! I followed the link (not sure why I didn't notice before) and everything seemed to work fine.

My only concern is, when running with --verbose, I get a bunch of these at the end of each run:

"Number of variants in span (x) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes."

Should I be concerned about this? My main goal is to just get a polished assembly.

My only other concern aside from this issue is that I'm doing de novo assembly on a new bacterial species with no previous reference genome. How do I then go about comparing the initial and polished assemblies with MUMmer, if at all? 

Thanks,

Carl

**Comment by jts** [comment]
Sorry for the slow response, I was travelling. You can ignore those messages, they are only warnings. 

What information are you trying to get from the comparison?
