### ISSUE TITLE
How to run nanopolish on several runs (i.e. several fast5 directories)? 

### ISSUE THREAD

**Issue by mullinyu** [jts/nanopolish#417]
Hi,

I want to know how to execute nanopolish on several runs of Nanopore sequencing.

From the documentation, here's the command for one run:
nanopolish index -d fast5_files/ reads.fasta

For my case, I have three different directories of fast5 as per my three runs:
C:\data\reads\20180530_1011_A120162A\fast5
C:\data\reads\20180530_1011_A120162B\fast5
C:\data\reads\20180530_1011_A120162C\fast5

In this case, how should I proceed?

Here're the commands listed in documentation:
=>canu -p ecoli -d outdir genomeSize=4.6m -nanopore-raw albacore-2.0.1-merged.fastq
=>minimap2 -d draft.mmi draft.fa
=>minimap2 -ax map-ont -t 8 draft.fa reads.fasta | samtools sort -o reads.sorted.bam -T˓reads.tmp
=>samtools index reads.sorted.bam
=>nanopolish variants --consensus polished.fa -w "tig00000001:200000-202000" -r reads.fasta -b reads.sorted.bam -g draft.fa

Thanks!

Regards,
Mullin

**Comment by jts** [comment]
Hi,

I suggest you make a folder containing all runs for the sample:

```
sample_abc/
   20180530_1011_A120162A\fast5
   20180530_1011_A120162B\fast5
   20180530_1011_A120162C\fast5
```

then run nanopolish index on the top-level folder:

```
nanopolish index -d sample_abc -s merged_sequencing_summary.txt albacore-2.0.1-merged.fastq
```

Note nanopolish doesn't run on windows though.

jared

**Comment by chilltrout** [comment]
What is merged sequening summary? how does it come out of thin air?
