### ISSUE TITLE
Nanopolish on subsample dataset

### ISSUE THREAD

**Issue by Nifaste** [jts/nanopolish#420]
Hi !
I have high coverage dataset that I downsample using filtlong with length priority (some reads in subsample dataset have 'low quality' but I wanted to keep longer reads). The subsample dataset is about 145x. 
I was wondering if, for nanopolish it is better to use high quality reads ? Should I create subsample dataset based on quality ? What is the best practice for nanopolish ? High quality reads + longer reads ? 
Can I use a different subsample dataset for nanopolish that the one I used for assembly with canu ? 
Thanks in advance for your help,

**Comment by jts** [comment]
How are you defining low/high quality reads? In general nanopolish benefits from a lot of coverage so I don't think you need to aggressive filter your dataset.

**Comment by Nifaste** [comment]
By low quality I mean Q<7 and by high quality Q>9.
I tried with many subsample dataset, and for the data i’m analyzing, I’m able to circularized the genome when I’m downsample with length priority (keep longer reads even if Q~5). When downsample based on quality, cannot circularized bacterial genome.

**Comment by jts** [comment]
Nanopolish can't help with circularizing the genome, it only will improve the accuracy of an existing assembly. I suggest using the Q>7 reads.

**Comment by jts** [comment]
Yes, you can use a different read set for nanopolish. I have not tried selecting reads for quality, except for the pass/fail distinctions made by the basecaller.

**Comment by Nifaste** [comment]
Thanks for your reply.
For nanopolish you took all the pass reads from albacore ? I subset because nanopolish is long to run even using parallel (for example, using a subset of high quality reads (Q>9;68322 reads) nanopolish is running since 50h on a unix server with 72CPU and 144 Go of RAM). Does nanopolish needs more RAM ?

**Comment by jts** [comment]
Please follow the instructions here to run the program in parallel:

https://github.com/jts/nanopolish#computing-a-new-consensus-sequence-for-a-draft-assembly

With 72 cores available I suggesting you run 8 nanopolish jobs at once (`-P 16` parameter to `parallel`) where each job uses 4 threads (`-t 4` parameter to `nanopolish`).

Jared
