### ISSUE TITLE
Nanopolish extract doesn't extract reads

### ISSUE THREAD

**Issue by sarah872** [jts/nanopolish#421]
I am using Nanopolish extract to extract the fastq from fast5 files:

      nanopolish extract -q -o nanopolish-extract.fastq -r fast5

but I am getting the following error:

      [extract] found 63166 files, extracted 0 reads

**Comment by jts** [comment]
HI @sarah872,

`nanopolish extract` is a legacy program for dealing with very old fast5 files. You shouldn't need to use it for recent data. It has been replaced by `nanopolish index`. See here for details on how to preprocess your reads:

https://github.com/jts/nanopolish#data-preprocessing

Jared

**Comment by sarah872** [comment]
thanks for the quick answer. In the command `nanopolish index -d /path/to/raw_fast5s/ -s sequencing_summary.txt albacore_output.fastq`, is the `albacore_output.fastq` referring to reading or for the output?

**Comment by jts** [comment]
It is for reading, it is the output from the basecaller that you ran on your sequencing run (usually albacore)

**Comment by sarah872** [comment]
I do not have this file. Can I use the fastq file generated by `poretools` for example?

**Comment by jts** [comment]
Is this data you generated on your own or that you downloaded from somewhere?

**Comment by sarah872** [comment]
On my own, but I do not have access to the Nanopore community/albacore.

**Comment by jts** [comment]
You have to run a basecaller (albacore) on the data before you can do anything else with it.

**Comment by sarah872** [comment]
well, it was basecalled during sequencing
