### ISSUE TITLE
Length confusion

### ISSUE THREAD

**Issue by OldrichBartos** [jts/nanopolish#422]
I have submitted "window" of recommended length 100 kb (tig1:1-100 000) to Nanopolish, however the "polished.fa" reports to me length of 100 040 bp (tig1:1-100 040), whereas the actual length of the reported sequence is close to 1O1 000 bp...
I am quite confused...as the genome had to be divided...how to put it into one piece once again?
Thank you very much, Olda

**Comment by jts** [comment]
Hi,

Nanopolish needs some flanking sequence around the window to accurately call it. It will add 40bp to the window to ensure it can call the full region that you requested. You don't have you worry about putting it back together into one piece, if you use the recommended workflow nanopolish will do it for you.

Jared

**Comment by OldrichBartos** [comment]
Thanks for your fast reply,

however, as I do not use your scripts for dividing the tasks, as I use only 4 core machine...

I probably can not use yours nanopolish_makerange.py which probably assumes multi-core server-like machine...

Instead of parallel runs, I have to (probably) run those 100 kb pieces in series...

How do you then suggest to "assemble" them?

Once again, thank you very much!

**Comment by jts** [comment]
You can use our scripts, just set `-P 1` in the `parallel` command and it will run 1 task at a time.

**Comment by OldrichBartos** [comment]
Well, thank you once again!
