### ISSUE TITLE
de novo variant calling

### ISSUE THREAD

**Issue by sleyn** [jts/nanopolish#426]
Hello!

I'm trying de novo variant calling with nanopolish 0.9.0. We have two organisms Acinetobacter baumannii and Escherichia coli. When calling variants from A. baumannii samples everything works fine and simple thresholds by SupportFraction 0.7 for SNP and 0.85 for InDels gives us variants very consistent with Illumina data.
However when we call variants from E. coli (various experiments) something strange happens. We got around 5-10 thousands of variants and most of them are A->G or T->C substitutions (~95% of all variants).

The code that I'm using for calling in both variants:
`nanopolish variants --ploidy 1 --reads barcode"$bc"_trimmed.fq --bam barcode"$bc".sorted.bam --genome ~/Tasks/01_GEAR/Genomes/$genome --outfile variants_"$bc"_all_n1.vcf --threads 16 --min-candidate-frequency 0.3 --min-candidate-depth 10`

In A. baumannii I'm using -w parameter because my strain has three plasmids. But adding -w with specification of the chromosome to E.coli calling does not change situation.
Could you suggest why I'm observing this behaviour and how can I improve variant calling for E. coli samples?

Thanks, Semion

**Comment by jts** [comment]
Hi Semion,

The first thing that comes to mind is methylation - were the samples PCR amplified or did you make the library directly from genomic DNA without amplification? Can you check whether the variants are in dam (GATC) or dcm (CCAGG, CCTGG) motifs? You can also try adding the `--methylation-aware=dcm,dam` flag to see if it helps.

Jared

**Comment by sleyn** [comment]
Thanks for so fast response! We are doing libraries directly from the genomic DNA of the clones.
I'll try your suggestion.

**Comment by sleyn** [comment]
I've checked several of these suspicious mutations and they are indeed in the dam and dcm motifs.

**Comment by jts** [comment]
Great - add that flag and it should get rid of a lot of them. Let me know how it goes.

Jared

**Comment by jts** [comment]
Very glad to hear, thanks for reporting back.
