### ISSUE TITLE
[fai_fetch_seq] The sequence "tig00000000" not found : Error while polishing

### ISSUE THREAD

**Issue by athulmenon** [jts/nanopolish#43]
Hi all,
I am trying to do a nanopolish of E.coli assembly by CANU.

I am still thinking which all files from the Assembly we need, to do nanopolish? I took only the assembly contig file and ran these commands.

`make -f /home/gba4/Documents/programs/nanopolish/scripts/consensus.make READS=HQ_2D.fasta ASSEMBLY=ecoli.contigs.fasta`

`/opt/athul/Nanopore/Data_Backup/ecoli/Nanopore_Rawreads$ python /opt/programs/nanopolish/scripts/nanopolish_makerange.py ecoli.contigs.fasta | parallel --results nanopolish.results -P 8 /opt/programs/nanopolish/nanopolish consensus -o nanopolish.{1}.fa -w {1} --r HQ_2D.pp.fa -b HQ_2D.pp.sorted.bam -g ecoli.contigs.fasta -t 4`

While running the second command the error pops up!
`[fai_fetch_seq] The sequence "tig00000000" not found`

Do you have any idea for this?
Thanks in advance.
Athul

**Comment by jts** [comment]
This should now be fixed in cd744a631. Can you try again from the `consensus.make` step?

**Comment by athulmenon** [comment]
Hi jts,

Sorry for late reply.
I have done the consensus.make, after that ran 
`/opt/athul/Nanopore/Data_Backup/ecoli/Nanopore_Rawreads$ python /opt/programs/nanopolish/scripts/nanopolish_makerange.py ecoli.contigs.fasta | parallel --results nanopolish.results -P 8 /opt/programs/nanopolish/nanopolish consensus -o nanopolish.{1}.fa -w {1} --r HQ_2D.pp.fa -b HQ_2D.pp.sorted.bam -g ecoli.contigs.fasta -t 4`

but now the error is showing as : 
`
Error: unknown model: _opt_metrichor_model_r7_template_median49pA.model
Error: unknown model: r7.3_template_median60pA.model
Error: unknown model: _opt_metrichor_model_r7_template_median43pA.model
Error: unknown model: r7.3_template_median60pA.model`

Thank you for your response.
Athul

**Comment by jts** [comment]
Is this new data? It would appear that the model names within Metichor have
changed again, breaking nanopolish.

**Comment by athulmenon** [comment]
NO it is not. Its old one itself.

**Comment by jts** [comment]
This version of metrichor output isn't supported by nanopolish. As ONT have now moved to R9 data I don't think we will change this. If you still want to run the assembly write back and I will show you how to modify nanopolish to support these models.
