### ISSUE TITLE
running nanopolish: command "parallel" not found.

### ISSUE THREAD

**Issue by moutusee** [jts/nanopolish#432]
Hi
this is the command I am giving :  nanopolish/scripts$ python nanopolish_makerange.py /home/moutusee/Desktop/nanopolish-out/barcode01_assembled.contigs.fasta | parallel --results nanopolish.results -P 8 \ nanopolish variants --consensus -o polished.{1}.vcf -w {1} -r /home/moutusee/Desktop/nanopolish-out/barcode01_pass.fastq -b /home/moutusee/Desktop/nanopolish-out/reads.sorted.bam -g /home/moutusee/Desktop/nanopolish-out/barcode01_assembled.contigs.fasta -t 4 --min-candidate-frequency 0.1
I am getting the following error: Command 'parallel' not found, but can be installed with:
sudo apt install moreutils
sudo apt install parallel 
When I try to install parallel with these commands; i get further error messages: Reading package lists... Error!
E: flAbsPath on /var/lib/dpkg/status failed - realpath (2: No such file or directory)
E: Could not open file  - open (2: No such file or directory)
E: Problem opening 
E: The package lists or status file could not be parsed or opened.

can you help?

**Comment by jts** [comment]
This looks like a problem with your ubuntu install. If you google for "E: flAbsPath on /var/lib/dpkg/status failed - realpath (2: No such file or directory)" there are other people with a similar problem.

**Comment by moutusee** [comment]
I did what they suggested. still getting the same problem. Error message. Is there any other way to install parallel? Or it is supposed to be included in the nanopolish directory?

**Comment by jts** [comment]
It is not included in nanopolish. You'll have to fix your ubuntu issue, install it from conda or compiling it on your own: https://www.gnu.org/software/parallel/
