### ISSUE TITLE
Some questions running nanopolish on human genome

### ISSUE THREAD

**Issue by tzuyaochen** [jts/nanopolish#435]
Hi 
I followed the steps in http://nanopolish.readthedocs.io/en/latest/quickstart_consensus.html but the result was different from the page.

1. I ran the command down below

nanopolish index -d /home/tzuyaochen/Desktop/nanopore/project/20180705_RD_WGA/reads_output/workspace/pass/barcode09/fast5 /home/tzuyaochen/Desktop/nanopore/project/20180705_RD_WGA/reads_output/workspace/pass/barcode09/outfile.fasta

but there were nothing generated by the code. I didn't know whether I give the wrong parameter or something else.

2. Is the draft.fa the same as the reference.fa such as human reference genome Grch38p2.fa? I was trying to run the nanopolish variants with Grch38p2.fa as the draft.fa file using the command below

nanopolish variants -o polished.{1}.vcf -w {1} -r /home/tzuyaochen/Desktop/nanopore/project/20180705_RD_WGA/reads_output/workspace/pass/barcode09/outfile.fasta -b /home/tzuyaochen/nanopolish/reads.sorted.bam -g /home/tzuyaochen/Grch38p2.fa -t 4 --min-candidate-frequency 0.1

then I got an error message:
Error: could not find path to FAST5 for read @0001e08d-4788-4851-912d-c60af24a9940
Please make sure that this path is accessible: barcode=barcode09

Thanks for your help!

**Comment by jts** [comment]
Did the `nanopolish index` step print any messages to the terminal? It should write out how many reads it found in the fasta file and how many fast5 paths it was able to resolve. If you didn't see any output then the indexing step must have failed.

**Comment by tzuyaochen** [comment]
Hi, thanks for your reply!
I found my problem with the indexing step and it works!
but there are still some errors when I run the "nanopolish_makerange.py". The command is 
python nanopolish_makerange.py /home/tzuyaochen/Grch38p2.fa | parallel --results nanopolish.results -P 4 
and I got error message
python: can't open file 'nanopolish_makerange.py': [Errno 2] No such file or directory

also some errors in the variants step when I run 
nanopolish variants -o polished.{1}.vcf -w {1} -r /home/tzuyaochen/Desktop/nanopore/project/20180705_RD_WGA/reads_output/workspace/pass/barcode09/outfile.fasta -b /home/tzuyaochen/nanopolish/reads.sorted.bam -g /home/tzuyaochen/Grch38p2.fa -t 4 --min-candidate-frequency 0.1
with the error message
TODO: train model
TODO: filter data
Error: could not find path to FAST5 for read @0001e08d-4788-4851-912d-c60af24a9940
Please make sure that this path is accessible: barcode=barcode09
It would be wonderful if you could help me find my problem in my command or somewhere else.
Thanks for your help!

**Comment by jts** [comment]
You appear to be running a very old version of nanopolish. Please try with a more recent version.

(sorry for the slow reply, I was on vacation)

Jared

**Comment by tzuyaochen** [comment]
Thanks for your reply! 
I had fixed the problem and it works perfect now.

Sincerly,
Tzu-yao chen

**Comment by jts** [comment]
Great, thanks for letting me know
