### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by vagnerfonseca** [jts/nanopolish#436]
i'm running nanopolish v0.85 and it's showing this message... is this normal?

```
nanopolish variants -x 1000000 --progress -t 1 --reads FAH81531/BC07_FAH81531.fasta -o FAH81531/BC07_FAH81531.vcf -b FAH81531/BC07_FAH81531.trimmed.sorted.bam -g REF/DENV4_Brazil.reference.fasta -w "JN559741.2:1-10243"  --snps --ploidy 1
Number of variants in span (32) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
```

**Comment by jts** [comment]
That is just a warning and can be ignored. You version is quite out of date though so I suggest updating to the latest (0.10.1).

**Comment by vagnerfonseca** [comment]
Thanks for your response, I solved my problem by running my pipeline (zibra) with Nanopolish v. 0.85. Running it with the latest version (v.0.10.1) initially was the problem.

**Comment by jts** [comment]
Ah I see
