### ISSUE TITLE
methylation filtering standard

### ISSUE THREAD

**Issue by miaoyu01** [jts/nanopolish#437]
Hello, first of all, thank you very much for publishing this software. I encountered two problems when calling nano 5mC when using nanopolish:
(1) For each call out of CpG, there are methylated count and unmethylated count. Do you know how to define them as methylation sites? In bisulfite genomic sequencing, some people performs a binomial distribution test for every CpG site.`Dolzhenko E, Smith A D. Using beta-binomial regression for high-precision differential methylation analysis in multifactor whole-genome bisulfite sequencing experiments.[J]. BMC Bioinformatics, 2014, 15(1):215.` but is there a filtering standard here?

(2) The final result is not as positive or negative as bismark. How can I know whether it is a positive or negative chain? Because the gene is divided into positive and negative chains, I want to calculate the degree of methylation of each genetic element.

**Comment by miaoyu01** [comment]
I will appreciate it if you can help me.

**Comment by tengfeixiaozhu** [comment]
@jts @miaoyu01 
For nanopore sequence data, could you give me some advice for the standard to define them as methylation sites?

**Comment by jts** [comment]
The call-methylation output now reports the strand.
