### ISSUE TITLE
samtools -f option is removed

### ISSUE THREAD

**Issue by hjjansen** [jts/nanopolish#44]
When running the consensus.make script in nanopolish 0.4 with samtools 1.3 the script stops at the samtools sort stage complaining about the -f option: "sort: invalid option -- 'f'"
From the samtools manual I can see that the -f option has been removed:

"Historically samtools sort also accepted a less flexible way of specifying the final and temporary output filenames: 

samtools sort [-f] [-o] in.bam out.prefix 

This has now been removed. The previous out.prefix argument (and -f option, if any) should be changed to an appropriate combination of -T PREFIX and -o FILE. The previous -o option should be removed, as output defaults to standard output."

I hope I've made a correct analysis of this error and if not please let me know because I like to learn from my mistakes.

Hans Jansen

**Comment by BertVanm** [comment]
I was trying to install nanopolish earlier today and I also encountered this error. I can't seem to get around it, so any help is greatly appreciated.

Bert V

**Comment by hjjansen** [comment]
What I did in the end is to run the commands individually. In my case it completed the samtools view command.
Then I did:
`samtools sort -o alignment.pp.sorted.bam alignment.pp.bam
`
Then build an index:
`samtools index alignment.pp.sorted.bam`
And an index for the assembly
`samtools faidx assembly.contigs.fa`
With the output of these steps I can continue with nanopolish consensus. This will finish but only correct some of the contig fragments. It will print often this error message:
`nanopolish: src/nanopolish_consensus.cpp:560: std::string join_sequences_at_kmer(const string&, const string&, uint32_t): Assertion "a_last_kmer == b_last_kmer" failed.
`
The merge script then fails because of empty sequence files. The reason could be that I'm using different datasets. See also issue #45.

Hope this helped.

Hans Jansen

**Comment by jts** [comment]
I believe that error is due to using different k-mer sizes as discussed in #45. Thanks for updating this issue and I believe your analysis of the situation is correct. I will leave this issue open until I can update nanopolish consensus.make to work with samtools-1.3.

**Comment by BertVanm** [comment]
any updates on this?

**Comment by hjjansen** [comment]
I've adapted the script. In ./nanopolish/scripts/consensus.make I've changed this:
`        samtools sort -f $^ $@`
in this:
`        samtools sort -o $@ $^`
This script now finishes without complaining.
I hope this helps

**Comment by BertVanm** [comment]
worked like a charm, thank you
