### ISSUE TITLE
empty vcf/stderr/stdout

### ISSUE THREAD

**Issue by njaupan** [jts/nanopolish#440]
Hi, I got all files empty after 48h running for 130* draft genome, version is 0.10.1. Here is all  the commands:
$nanopolish index -d fast5_files/1 -d fast5_file/2 -s summary1.txt  -s summary2.txt filtered_albacore_reads.fastq
num reads: 1407668, num reads with path to fast5: 1407668, output 4 files

$minimap2 -ax map-ont -t 8 draft.fa filtered_albacore_reads.fastq | samtools sort -o reads.sorted.bam
samtools index reads.sorted.bam

$python ~/nanopolish/scripts/nanopolish_makerange.py draft.fa | parallel --results nanopolish.results -P 8 \ ~/nanopolish/nanopolish variants --consensus -o polished.{1}.vcf -w {1} 
-r filtered_albacore_reads.fastq -b reads.sorted.bam -g draft.fa -t 8 --min-candidate-frequency 0.1 --methylation-aware=cpg  --max-haplotypes 1000000

all vcf/stderr/stdout are empty so far, and it only has warning even tough set 1m max-haplotypes
28 variants in span [9 87]
Number of variants in span (28) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!

Do you have any suggestion?

Best,
panpan

**Comment by jts** [comment]
I don't suggest running with `--max-haplotypes 1000000`, it will make calling extremely slow. You can just ignore those warnings.

Jared

**Comment by njaupan** [comment]
Hi Jared, thank you for your suggestion. I also reduced P that to polish 2 segments at once,  finally got something in one vcf. But do you suggest any command to speed up CPU time?

**Comment by njaupan** [comment]
Dear Jared, it have taken 12 days so far and just outputed vcf files for 3.5 contigs in the cluster of 1 node, 12 threads. I am afraid to I need to terminate it because we have 60 contigs in this genome and other 12 candidate genomes to polish. i guess --faster option will still consume long time, shall i give up nanopolish or do you have better suggestion?

**Comment by jts** [comment]
What command did you run? What sequencing depth do you have?

**Comment by jts** [comment]
For reference on my system it takes ~5minutes to polish each 50kb segment, so there is something unusual going on with your dataset. What program generated the draft assembly?

**Comment by jts** [comment]
How large is the genome expected to be?

**Comment by njaupan** [comment]
130M,  it took ~2h for a 50k segment in this dataset.

**Comment by njaupan** [comment]
130x coverage for a estimated 130Mbp genome

**Comment by jts** [comment]
That is quite a large genome, I don't think it is practical to polish it using a single 12-core server. Greater than 12 days of runtime is not unexpected.

**Comment by jts** [comment]
It is possible that smrtdenovo does not work well for nanopore reads, so the initial consensus accuracy is low and nanopolish needs to do a lot of extra work. Are you able to estimate the accuracy of the draft assembly? Have you tried running canu instead?

**Comment by njaupan** [comment]
Thank you, I will try it in serval nodes, and check the 50k polish time for canu-assembled genome.

**Comment by jts** [comment]
OK, let me know how it goes.

**Comment by njaupan** [comment]
Hi, the average identity for this genome is 93% calculated by mummer dnadiff, so I think it is not that bad, but the N50 of canu assembled genome is 40% less than it.

**Comment by jts** [comment]
93% is too low for nanopolish, it expects the input to be >98%. This is why it is running slowly. Maybe you can try running racon on the assembly before nanopolish.
