### ISSUE TITLE
Using nanopolish after barcoded samples demultiplexing

### ISSUE THREAD

**Issue by herrroaa** [jts/nanopolish#443]
Hi,
I have six barcoded samples multiplexed in a sequence run on Minion.
I used porechop to demultiplex my six samples and now I have six .fastq files (one file per sample).

I want to index my reads before calling SNPs using nanopolish. Is it ok if I use fastq file for one (sample_01) while feeding the path to all of my fast5 files. These fast5 files are all fast5 files generated during the run (i.e. fast5 for the six samples are located in one directory)

`nanopolish index -d /path/to/fast5/  sample_01.fa`

In another word, I have six fastq files for six samples, and one directory containing all fast5 files generated. How can I use these files to index my reads

Thanks

**Comment by herrroaa** [comment]
Hi Jared,

Thanks for the reply. 
Do I have to build the index for the six samples?
and if so how can I save the outputs ?
My samples id are BC01 to BC06

`for file in BC0*.fastq; do nanopolish index -d /path/to/fast5/ $file; done
`

**Comment by herrroaa** [comment]
I indexed my reads as above, then I used variants to call snps. The process was completed but there was an error message. The fastq file has 103328 reads but variant calling algorithm processed only 57246.

```
`$ nanopolish variants -p 2 -w chr9:84273123-84368634  --reads BC01.fastq -b BC01_sorted.bam  --genome NCBI.GRCh38.fa -o BC01.polish.vcf`
[post-run summary] total reads: 57246, unparseable: 0, qc fail: 6, could not calibrate: 19, no alignment: 1500, bad fast5: 0
```

Thanks
Tarek

**Comment by herrroaa** [comment]
Any thougths @jts

**Comment by jts** [comment]
It will only use reads that are aligned to the region of interest (`chr9:84273123-84368634`), so that likely accounts for the remaining reads.

**Comment by jts** [comment]
Hi,

Some reads might have multiple alignments so you might be overcounting. Also nanopolish might be filtering out some reads.

The --snps option was recently reenabled. Try updating to the latest code.

Jared

**Comment by herrroaa** [comment]
Hi,

I am using `nanopolish version 0.10.1` which I installed through `conda install -c bioconda nanopolish`
Is this the most updated version ?
I tried to download it using but I had a problem.

g```
it clone --recursive https://github.com/jts/nanopolish.git
cd nanopolish
make
```

Tarek

**Comment by herrroaa** [comment]
Hi,

These values are extracted from the bam file at chr9:84,307,083. It is clear that this should be called as a heterozygous SNP GA as The A-allele is present in 2881 reads. However `nanopolish variants` did not call this SNP.

`nanopolish variants -p 2 -w chr9:84273123-84368634  --reads BC01.fastq -b BC01_bwa_sorted.bam  --genome NCBI.GRCh38.fa -o BC01.bwa.polish.vcf`

Type| Base|Count of reads|% of Total | MeanQuality 
(match) | G | 3982 | 56.0 | 14.3
(mismatch) | A | 2881 | 40.5 | 10.6
(mismatch) | C | 20 | 0.3 | 6.5
(mismatch) | T | 79 | 1.1 | 5.7
(deletion) |   | 145 | 2.0 | ?
Total |   | 7107 | 100 | 12.7

**Comment by jts** [comment]
Hi,

Sorry but I'm on vacation right now, I'll try to help you more when I'm back. In the meantime you can try the methylation-aware option in case this is a CpG site: -q cpg 

Jared

**Comment by herrroaa** [comment]
Hi,

Thanks for your reply, and sorry for bothering you.

Tarek
