### ISSUE TITLE
nanopolish  index: not enough arguments

### ISSUE THREAD

**Issue by Adelaam** [jts/nanopolish#445]
Hello,

I am starting to use nanopolish and I have this error:
~$ nanopolish index -d '/home/mwiks/Dropbox/data/reads/20180622_1354_mabsc/fast5/pass/0'/'/home/mwiks/Dropbox/data/reads/20180622_1354_mabsc/fast5/pass/m.absc.fasta' 
index: not enough arguments

Thank you!

**Comment by jts** [comment]
Are you missing a space between the directory and filename?

**Comment by Adelaam** [comment]
Yes!
Thank you!

**Comment by jts** [comment]
No problem
