### ISSUE TITLE
HDF5-DIAG: Error detected in HDF5 (1.8.14) when polishing genome

### ISSUE THREAD

**Issue by Omer-K** [jts/nanopolish#449]
I'm trying to polish a rather small sequence (around 7kb), which I've already produced by canu.
I've indexed the draft with `bwa index`
aligned the reads to this draft by using bwa mem
`bwa mem -t 12 -x ont2d draft.fa gene.reads.fasta | samtools view -bS - | samtools sort -o gene.sorted.bam -`
and indexed the bam file with SAMtools
`samtools index gene.sorted.bam`

I've successfully run `nanopolish index -d fast5_files/ gene.reads.fasta`.
Upon executing `nanopolish variants -t 12 --reads gene.reads.fa --bam gene.sorted.bam --genome draft.fa`
I get an error
```
##fileformat=VCFv4.2
##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">
##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">
##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">
##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">
##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140416510068832:
  #000: H5F.c line 591 in H5Fopen(): invalid file name
    major: Invalid arguments to routine
    minor: Bad value
terminate called after throwing an instance of 'hdf5_tools::Exception'
  what():  : : error in H5Fopen
Aborted (core dumped)
```
nanopolish version is 0.8.3.
What may be the issue and how could I solve it?

**Comment by jts** [comment]
The error indicates an invalid path to a fast5 file was found. Did you move the reads after indexing? Also the input files to `index` and `variants` are not the same (`gene.reads.fasta`, `gene.reads.fa`). Maybe this is a problem.

You should update your version as well, `0.8.3` is very old.

Jared

**Comment by Omer-K** [comment]
Hi Jared,
I did not move the fast5 after indexing.
I just wrote the code here for example, mistakenly wrote different suffix for the input file..
But in my command line the they are matching files.
We will update to the latest version (unfortunately I am dependent of the IT lady).
Any other suggestions in the meantime?

**Comment by jts** [comment]
You don't need IT's help to install the latest version, just follow the instructions here:

https://github.com/jts/nanopolish#installing-the-latest-code-from-github-recommended

It does not require admin privileges.  Please try with the latest version.

(sorry for the slow reply, I was on vacation)

**Comment by Omer-K** [comment]
Wow, I was in the dark - through I was dependent on Admin privileges..
Anyway, I tried, all was well until I run `make`. Many code lines were running, some with errors.
Then I run `make` again, and this is the error I got:
`g++ -o src/main/nanopolish.o -c -g -O3 -std=c++11 -fopenmp -fsigned-char -I./include -I./htslib -I./fast5/include -I./src -I./src/hmm -I./src/thirdparty -I./src/thirdparty/scrappie -I./src/common -I./src/alignment -I./src/pore_model -I./eigen/ -fPIC src/main/nanopolish.cpp
cc1plus: error: unrecognized command line option "-std=c++11"
make: *** [src/main/nanopolish.o] Error 1`

Can I fix this?

**Comment by jts** [comment]
What OS and what version of g++ are you using?

Jared

**Comment by Omer-K** [comment]
OS: Red Hat Enterprise Linux Server release 6.9 (Santiago) (I used `lsb_release -a` for this)
g++: gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (I used `g++ -v` for this)

**Comment by jts** [comment]
Ah. That version of gcc is very old so you will need your admins help after all. Nanopolish is also available on conda if that works for you.

**Comment by jts** [comment]
Yes it is likely due to the old version
