### ISSUE TITLE
Can SQK-MAP005 and SQK-MAP006 data be used at the same time?

### ISSUE THREAD

**Issue by hjjansen** [jts/nanopolish#45]
I've generated nanopore sequence data to assemble a yeast strain. This was done in two batches. The first batch was made with the SQK-MAP005 kit, the second with SQK-MAP006. The assembly was done with Canu. To further improve the sequence I want to use nanopolish but I'm not sure if I can use both datasets at the same time as they depend on different kmer models.

**Comment by jts** [comment]
I'm sorry but I don't think this will work with the current code. In many places of the consensus algorithm the k-mer size used in the pore model is a parameter to the algorithm and this will have unexpected results when mixing 5-mers from MAP005 and 6-mers from MAP006.

**Comment by hjjansen** [comment]
OK, lesson learned :-)
Thanks,
Hans Jansen
