### ISSUE TITLE
Nanopolish test failed 

### ISSUE THREAD

**Issue by Adelaam** [jts/nanopolish#450]
I have got his error running nanopolish test:

HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140055475949568:
  #000: H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 990 in H5F_open(): unable to open file: time = Fri Aug 31 11:41:24 2018
, name = 'test/data/LomanLabz_PC_Ecoli_K12_R7.3_2549_1_ch8_file30_strand.fast5', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 992 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: H5FDsec2.c line 343 in H5FD_sec2_open(): unable to open file: name = 'test/data/LomanLabz_PC_Ecoli_K12_R7.3_2549_1_ch8_file30_strand.fast5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
[warning] fast5 file is unreadable and will be skipped: test/data/LomanLabz_PC_Ecoli_K12_R7.3_2549_1_ch8_file30_strand.fast5
nanopolish_test: ./src/nanopolish_squiggle_read.h:177: size_t SquiggleRead::get_model_k(uint32_t) const: Assertion `this->base_model[strand] != NULL' failed.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
nanopolish_test is a Catch v1.1 b3 host application.
Run with -? for options

-------------------------------------------------------------------------------
hmm
-------------------------------------------------------------------------------
src/test/nanopolish_test.cpp:389
...............................................................................

src/test/nanopolish_test.cpp:389: FAILED:
due to a fatal error condition:
  SIGABRT - Abort (abnormal termination) signal

===============================================================================
test cases:   6 |   5 passed | 1 failed
assertions: 634 | 633 passed | 1 failed

**Comment by jts** [comment]
You have to run nanopolish_test from the directory that the executable
resides or else it won't be able to find the test data.
