### ISSUE TITLE
Empty eventalign output

### ISSUE THREAD

**Issue by Adelaam** [jts/nanopolish#452]
Hello,

I am getting an empty eventaling.txt ouput with last version. And I am getting this error for nanopolish extract: [extract] found 22547 files, extracted 0 reads

**Comment by jts** [comment]
You should be using `nanopolish index`, not `nanopolish extract`:

https://github.com/jts/nanopolish#data-preprocessing

**Comment by Adelaam** [comment]
I have got data already indexed with nanopolish and when I tried eventaligment I have got an empty output.

With new data I have tried to extract fast5 files to FASTA and I am getting the error above.


Thank you.

**Comment by jts** [comment]
Can you post the complete set of commands you ran, and the output messages,
when trying to use nanopolish index?

Jared

**Comment by Adelaam** [comment]
I have not problem with nanopolish index, the problem is with eventalign:
./nanopolish eventalign -r '/home/mwiks/Desktop/M. abscessus 1356 analysis/mergedfiles.fasta' -b '/home/mwiks/nanopolish/mab1356.sorted.bam' -g '/home/mwiks/Desktop/Mabscessus ref.fna' --scale-events > mb1356.eventalign.txt
error: could not load the index files for input file /home/mwiks/Desktop/M.
Please run nanopolish index on your reads (see documentation)
But I have already run these data with nanopolish index

**Comment by Adelaam** [comment]
This is the full process:
/nanopolish index -d '/home/mwiks/Desktop/M. abscessus 1356 analysis/M. abscessus 1356/fast5' '/home/mwiks/Desktop/M. abscessus 1356 analysis/mergedfiles.fasta' 
[readdb] indexing /home/mwiks/Desktop/M. abscessus 1356 analysis/M. abscessus 1356/fast5
[readdb] indexing /home/mwiks/Desktop/M. abscessus 1356 analysis/M. abscessus 1356/fast5/skip
[readdb] indexing /home/mwiks/Desktop/M. abscessus 1356 analysis/M. abscessus 1356/fast5/skip/4
[readdb] indexing /home/mwiks/Desktop/M. abscessus 1356 analysis/M. abscessus 1356/fast5/skip/1
[readdb] indexing /home/mwiks/Desktop/M. abscessus 1356 analysis/M. abscessus 1356/fast5/skip/0
[readdb] indexing /home/mwiks/Desktop/M. abscessus 1356 analysis/M. abscessus 1356/fast5/skip/2
[readdb] indexing /home/mwiks/Desktop/M. abscessus 1356 analysis/M. abscessus 1356/fast5/skip/3
[readdb] indexing /home/mwiks/Desktop/M. abscessus 1356 analysis/M. abscessus 1356/fast5/fail
[readdb] indexing /home/mwiks/Desktop/M. abscessus 1356 analysis/M. abscessus 1356/fast5/fail/0
[readdb] indexing /home/mwiks/Desktop/M. abscessus 1356 analysis/M. abscessus 1356/fast5/pass
[readdb] indexing /home/mwiks/Desktop/M. abscessus 1356 analysis/M. abscessus 1356/fast5/pass/6
[readdb] indexing /home/mwiks/Desktop/M. abscessus 1356 analysis/M. abscessus 1356/fast5/pass/4
[readdb] indexing /home/mwiks/Desktop/M. abscessus 1356 analysis/M. abscessus 1356/fast5/pass/1
[readdb] indexing /home/mwiks/Desktop/M. abscessus 1356 analysis/M. abscessus 1356/fast5/pass/0
[readdb] indexing /home/mwiks/Desktop/M. abscessus 1356 analysis/M. abscessus 1356/fast5/pass/2
[readdb] indexing /home/mwiks/Desktop/M. abscessus 1356 analysis/M. abscessus 1356/fast5/pass/3
[readdb] indexing /home/mwiks/Desktop/M. abscessus 1356 analysis/M. abscessus 1356/fast5/pass/5
[readdb] indexing /home/mwiks/Desktop/M. abscessus 1356 analysis/M. abscessus 1356/fast5/pass/7
[readdb] num reads: 31326, num reads with path to fast5: 31326
mwiks@administrator-HP-Compaq-Elite-8300-SFF:~/nanopolish$ '/home/mwiks/minimap2-2.12_x64-linux/minimap2' -ax map-ont -t 4 '/home/mwiks/Desktop/Mabscessus ref.fna' '/home/mwiks/Desktop/M. abscessus 1356 analysis/mergedfiles.fasta'  | samtools sort -o mab1356.sorted.bam -T reads.tmp 
[M::mm_idx_gen::0.163*1.01] collected minimizers
[M::mm_idx_gen::0.189*1.40] sorted minimizers
[M::main::0.189*1.40] loaded/built the index for 2 target sequence(s)
[M::mm_mapopt_update::0.204*1.37] mid_occ = 5
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 2
[M::mm_idx_stat::0.216*1.35] distinct minimizers: 921878 (97.28% are singletons); average occurrences: 1.030; average spacing: 5.361
[M::worker_pipeline::1.072*3.07] mapped 2375 sequences
[M::main] Version: 2.12-r827
[M::main] CMD: /home/mwiks/minimap2-2.12_x64-linux/minimap2 -ax map-ont -t 4 /home/mwiks/Desktop/Mabscessus ref.fna /home/mwiks/Desktop/M. abscessus 1356 analysis/mergedfiles.fasta
[M::main] Real time: 1.081 sec; CPU: 3.300 sec
mwiks@administrator-HP-Compaq-Elite-8300-SFF:~/nanopolish$ samtools index '/home/mwiks/nanopolish/mab1356.sorted.bam' 
mwiks@administrator-HP-Compaq-Elite-8300-SFF:~/nanopolish$ samtools quickcheck '/home/mwiks/nanopolish/mab1356.sorted.bam' 
mwiks@administrator-HP-Compaq-Elite-8300-SFF:~/nanopolish$ ./nanopolish eventalign -r '/home/mwiks/Desktop/M. abscessus 1356 analysis/mergedfiles.fasta' -b '/home/mwiks/nanopolish/mab1356.sorted.bam' -g '/home/mwiks/Desktop/Mabscessus ref.fna' --scale-events > mb1356.eventalign.txt
error: could not load the index files for input file /home/mwiks/Desktop/M.
Please run nanopolish index on your reads (see documentation)
mwiks@administrator-HP-Compaq-Elite-8300-SFF:~/nanopolish$

**Comment by jts** [comment]
It looks like it doesn't like the spaces in your path name. Try running the command from the directory that the fasta resides in.

**Comment by Adelaam** [comment]
It is working now.

Thank you!

**Comment by jts** [comment]
Great!

**Comment by Adelaam** [comment]
Hello,

I am getting a empty eventalign.txt document when running:

'/home/mwiks/nanopolish/nanopolish' eventalign  -r '/home/mwiks/polished03.fa' -b '/home/mwiks/polished03abscessus.bam' -g '/home/mwiks/Desktop/MabscessusATCC19977.fa'  --scale-events > barcode03-absc.eventalign.txt
[post-run summary] total reads: 72, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 72

The document has the head but nothing else:
contig	position	reference_kmer	read_index	strand	event_index	event_level_mean	event_stdv	event_length	model_kmer	model_mean	model_stdv	standardized_level

Thank you!

**Comment by jts** [comment]
```
[post-run summary] total reads: 72, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 72
```

There is something wrong with your fast5 files. Try re-running `nanopolish index`.

Jared
