### ISSUE TITLE
Error when trying to load txt summary file.

### ISSUE THREAD

**Issue by DEsalasL** [jts/nanopolish#453]
Hi, I'm having a problem with nanopolish index. the core gets dumped after nanopolish cann't open a summary file. However, the permissions and path of the files that is trying to open are ok (they work when call directly on cmd). I don't understand why it is calling the file as H5F. I have tons of information so, I couldn't afford to skip the summary files. I'd appreciate if you could take a look to the example of the error I get and point me to what I should fix, check or look into.
Many thanks
this is going in a shell script:

#!/bin/bash
Dir1a=/path/run1/fast5s
Dir1b=/path/run2/fast5s
Summary1=/path/run1/sequencing_summary.txt
Summary2=/path/run2/sequencing_summary.txt
FqReads=Chopped.fastq
ls $Summary1 $Summary2 > summary_files.fof
Nanopolish=/software/nanopolish/nanopolish
source activate nanopolish-python3
$Nanopolish index -d $Dir1a -d $Dir1b -f summary_files.fof $FqReads

Here is the error:
blah ... (several lines of the reads with paths...)
[readdb] num reads: 2343834, num reads with path: 2209535
Loaded 1 from fofn
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 23086554726400:
#000: H5F.c line 604 in H5Fopen(): unable to open file
major: File accessibilty
minor: Unable to open file
#1: H5Fint.c line 1085 in H5F_open(): unable to read superblock
major: File accessibilty
minor: Read failed
#2: H5Fsuper.c line 277 in H5F_super_read(): file signature not found
major: File accessibilty
minor: Not an HDF5 file
terminate called after throwing an instance of 'hdf5_tools::Exception'
what(): /Raw/Reads/Read_1895/duration: /path/run1/sequencing_summary.txt: error in H5Fopen
/var/spool/gridengine/job_scripts/34801: line 46: 63778 Aborted (core dumped) $Nanopolish index -d $Dir1a -d $Dir1b -f summary_files.fof $FqReads

**Comment by jts** [comment]
Can you paste the contents of the summary fofn? `cat summary_files.fof`. Also can you confirm you're using the latest version (0.10.1)?

**Comment by DEsalasL** [comment]
Hi, Just a follow up. The issue above is fixed in the version 0.10.1. 
Many thanks !
D

**Comment by DEsalasL** [comment]
Hi, Just a follow up. The issue above is fixed in the version 0.10.1.
Many thanks !
D
