### ISSUE TITLE
nanopolish variants stuck in a loop

### ISSUE THREAD

**Issue by samstu** [jts/nanopolish#455]
Hi jts,

I've been running nanopolish variants with no problem up until now but for some reason the current run keeps getting stuck in a loop when it reaches the end of the sequence and begins again:

![screenshot 2018-09-05 16 39 29](https://user-images.githubusercontent.com/43008178/45104638-708f9180-b12a-11e8-98f9-e1f16ca218b9.png).

Here's the command I'm running:

nanopolish variants --consensus BC04_trimmed_polished_consensus.fa -r //Volumes/raid/nanopolish/BC04/BC04.fastq -b //Volumes/raid/nanopolish/nanopolish_bams/BC04_sorted.bam -g //Volumes/raid/nanopolish/reference_consensus/DENV4_2k_Illumina_consensus_0.2.fa -t 14 --min-candidate-frequency 0.3

Any idea what's happening?

Cheers,

Sam

**Comment by jts** [comment]
This is normal, it runs multiple iterations of polishing to refine the set
of variants added to the genome. Your coverage is very high (>4000x) so it
will be slow. I suggest downsampling.

Jared

**Comment by jts** [comment]
Hi,

I hope downsampling the data helped, I'm going to close this for now but feel free to reopen if it is still a problem.

Jared
