### ISSUE TITLE
Samtools faidx polished genome

### ISSUE THREAD

**Issue by Adelaam** [jts/nanopolish#457]
Hello,

I have polished a tig on my sequences and everything went ok until: 

"We only polished a 2kb region, so let's pull that out:

It stops because it cannot find the tig000003.

What does it mean?

Thank you!

**Comment by jts** [comment]
Hi,

Sorry but I’m not sure what you’re asking. Can you describe in detail what you’re doing and what went wrong?

Jared

**Comment by Adelaam** [comment]
I have attached the step I am trying to do. Everything is fine until I have tried the last step, I get an error saying it cannot find the tig000003 and it stops.

![screen shot 2018-09-08 at 16 42 39](https://user-images.githubusercontent.com/38724626/45255953-2d7e2a00-b387-11e8-88e8-34429e096098.png)

**Comment by jts** [comment]
Hi,

Those commands are specific to the tutorial dataset we provide. On your data the filenames will be slightly different. The specific part you highlighted is for checking the accuracy of the polished genome. 

Jared
