### ISSUE TITLE
Create full VCF header with "nanopolish variants" module?

### ISSUE THREAD

**Issue by tomsasani** [jts/nanopolish#46]
I may be overlooking something, but is there an option for "nanopolish variants" to generate a full header in VCF output? In the VCF files I've produced, a single header line (with CHROM, REF, ALT, etc.) is produced, but it seems that a full header is necessary to parse with programs like bcftools.

**Comment by jts** [comment]
Yes, I will do this when I get back to Toronto.

**Comment by proukakis** [comment]
Hi, should this be working now? I can't get bcftools to recognise my files which also have the single header line. Perhaps I can actually create the full header with bcftools, or something else?

**Comment by jts** [comment]
Finally fixed in  330933f
