### ISSUE TITLE
(my) stupid but (possibly?) recoverable problem?

### ISSUE THREAD

**Issue by devonorourke** [jts/nanopolish#463]
Hi Jared,

I think I made a mistake when running `nanopolish` and was hoping for your input. 

I started by creating a `nanopolish` directory where I would put all the various Nanopolish outputs. Rather than moving my Nanopore `reads.fq.gz` file into that space, I symlinked the file to that new `nanopolish` directory. For example, the original fasta file might live here:
```
$HOME/nanopore/fastq/reads.fastq.gz
```

But my Nanopolish work was going to all live here:
```
$HOME/nanopolish
```

Thus my first file in that new Nanopolish directory was the symlinked file:
```
[me] $ cd $HOME/nanopolish
[me] $ ls
lrwxrwxrwx 1 me mylab   82 Sep  5 15:52 reads.fastq.gz -> $HOME/nanopore/fastq/reads.fastq.gz
```

I then proceed to run `nanopolish index` and the resulting information all lived within that Nanopolish directory. The job completed without issue so far as I can tell:
```
-rw-r--r-- 1 me mylab 613M Sep  6 08:44 reads.fq.gz.index.readdb
-rw-r--r-- 1 me mylab 358M Sep  5 21:11 reads.fq.gz.index.fai
-rw-r--r-- 1 me mylab 6.9M Sep  5 21:11 reads.fq.gz.index.gzi
-rw-r--r-- 1 me mylab 8.1G Sep  5 21:06 reads.fq.gz.index
-rw-r--r-- 1 me mylab  15M Sep  5 18:22 reads.sorted.bam.bai
-rw-r--r-- 1 me mylab  32G Sep  5 18:15 reads.sorted.bam
-rw-r--r-- 1 me mylab 4.2K Sep  5 17:09 npolish-mapping.log
lrwxrwxrwx 1 me mylab   82 Sep  5 15:52 reads.fastq.gz -> $HOME/nanopore/fastq/reads.fastq.gz
```

As a sanity check, if I look into the `.fai` file I can see all the normal read IDs and corresponding information. Things look normal to me. 

I then ran `nanopolish variants`, but because I'm dealing with a big genome I had to use your suggested `parallel` command (which, thanks for correcting [the typo](https://github.com/jts/nanopolish/issues/429)). This resulted in about 30,000 `.vcf` files. 

The command was something along these lines (it was a bigger shell script to work with our Slurm program, but I've abbreviated that here):
```
READSFILE=$HOME/nanopore/reads/reads.fastq.gz
BAMFILE=$HOME/nanopolish/reads.sorted.bam
DRAFTFILE=$HOME/someassembler/scaffolds.fasta
NPOLISHPYPATH=path/to/nanopolish/scripts/nanopolish_makerange.py
NANOPOLISH=path/to/bin/nanopolish/nanopolish

python3 $NPOLISHPYPATH $DRAFTFILE | parallel --results nanopolish.results -P 6 \
    $NANOPOLISH variants --consensus -o polished.{1}.vcf -w {1} -r $READSFILE -b $BAMFILE -g $DRAFTFILE -t 4 --min-candidate-frequency 0.1
```

A few (20!) days later, the job finished up, producing about 30,000 `polished.xxxxx.vcf` files, all which contained lots of information. There was also a `nanopolish.results/1` directory created within  my `$HOME/nanopolish` parent directory, consisting of 30,000 subdirectories named for the `.vcf` chunks that `nanopolish variants` produced. And inside _those_ subdirectories were always just 3 files: `seq`, `stderr`, and `stdout`. If I was to imagine what `tree` would have produced on that parent `$HOME/nanopolish` directory, I think the abbreviated version would look something like this:

```
$HOME/nanopolish
| --- polished.contig_1:0-50000.vcf
| --- polished.contig_2:0-50000.vcf
| --- polished.contig_3:0-50000.vcf
| --- nanopolish.results
       | --- contig_1:0-50000
                | --- seq
                | --- stderr
                | --- stdout
       | --- contig_2:0-50000
                | --- seq
                | --- stderr
                | --- stdout
       | --- contig_3:0-50000
                | --- seq
                | --- stderr
                | --- stdout
```

I carried on with the last part of the process by trying to combine the `.vcf` files present in the `$HOME/nanopolish` directory, but I get a long list of the same kind of error:
```
error: could not detect polishing window from input file polished.contig_10000:0-50000.vcf_polished.fa_polished.fa
error: could not detect polishing window from input file polished.contig_1000:0-50200.vcf_polished.fa_polished.fa
error: could not detect polishing window from input file polished.contig_1000:100000-150200.vcf_polished.fa_polished.fa
```

I'm wondering if the error is due to my directory structure. Maybe the `.vcf` files are in the wrong place and the `vcf2fasta` file can't find them?

I wonder if it's possible to use `bcftools consensus` to create a fasta file instead? I know there is plenty of information in these `.vcf` files - is there something unique about the `vcf2fasta` script that I should be aware of which may have an equivalent parameter in the `bcftools consensus` program?

Thanks for your advice!

**Comment by yiyi11zhong** [comment]
Hello, Jared 
I got the same problem here.
After running nanopolish variants in parallel as you suggested, I got the result:
> [post-run summary] total reads: 1722, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 0

And my vcf2fasta command is as following:
`nanopolish vcf2fasta -g draft.fasta polished.*.vcf > polished_genome.fasta`
I got one line of error
> error: could not detect polishing window from input file polished.tig00000002:2000000-2050200.vcf

What to do? 

Yiyi

**Comment by jts** [comment]
Yes, the consensus sequence would only be partially polished. I suggest you
re-run the part that failed.

Jared

**Comment by yiyi11zhong** [comment]
Thank you for your advice, it did work. And I also re-did the nanopolish index step to make sure everything went right. Though the no. of contigs remains the same as that before nanopolish, the SNPs and indels were corrected in some extent. 
Thanks again.

Yiyi

**Comment by jts** [comment]
Great
