### ISSUE TITLE
compilation problem again

### ISSUE THREAD

**Issue by gwaldbieser** [jts/nanopolish#465]
I have the same problem as #398 while installing on openSUSE Leap v15.0. 
The following was done as root.
`git clone --recursive https://github.com/jts/nanopolish.git`
Invoked make and the install got stuck in the hdf5 loop. 
Removed all, re-cloned from github, copied the new Makefile from gist and moved it to nanopolish dir
`https://gist.github.com/4fd5a12b55c91986d59b6c35105247a9.git` 
`mv Makefile Makefile.old` 
`cp 4fd5a12b55c91986d59b6c35105247a9.git/Makefile .`
 #Began install and logged to make.log 
`make 1>make.log 2>&1 & `

end of log file:  
>mv eigen-eigen-bdd17ee3b1b3 eigen || exit 255
rm -f ./.depend
g++ -g -O3 -std=c++11 -fopenmp -fsigned-char -I./include -I./htslib -I./fast5/include -I./src -I./src/hmm -I./src/thirdparty -I./src/thirdparty/scrappie -I./src/common -I./src/alignment -I./src/pore_model -I./eigen/ -MM  src/training_core.cpp src/nanopolish_vcf2fasta.cpp src/nanopolish_variant_db.cpp src/nanopolish_train_poremodel_from_basecalls.cpp src/nanopolish_squiggle_read.cpp src/nanopolish_scorereads.cpp src/nanopolish_read_db.cpp src/nanopolish_raw_loader.cpp src/nanopolish_polya_estimator.cpp src/nanopolish_phase_reads.cpp src/nanopolish_methyltrain.cpp src/nanopolish_index.cpp src/nanopolish_haplotype.cpp src/nanopolish_getmodel.cpp src/nanopolish_extract.cpp src/nanopolish_call_variants.cpp src/nanopolish_call_methylation.cpp  src/hmm/nanopolish_transition_parameters.cpp src/hmm/nanopolish_profile_hmm_r9.cpp src/hmm/nanopolish_profile_hmm_r7.cpp src/hmm/nanopolish_profile_hmm.cpp src/hmm/nanopolish_duration_model.cpp      src/common/nanopolish_variant.cpp src/common/nanopolish_klcs.cpp src/common/nanopolish_iupac.cpp src/common/nanopolish_fast5_io.cpp src/common/nanopolish_common.cpp src/common/nanopolish_bam_utils.cpp src/common/nanopolish_bam_processor.cpp src/common/nanopolish_alphabet.cpp src/common/logsum.cpp src/common/fs_support.cpp  src/alignment/nanopolish_eventalign.cpp src/alignment/nanopolish_anchor.cpp src/alignment/nanopolish_alignment_db.cpp  src/pore_model/nanopolish_pore_model_set.cpp src/pore_model/nanopolish_poremodel.cpp src/pore_model/nanopolish_model_names.cpp      src/thirdparty/stdaln.c  src/thirdparty/scrappie/util.c src/thirdparty/scrappie/scrappie_common.c src/thirdparty/scrappie/event_detection.c       > ./.depend;
src/nanopolish_scorereads.cpp:37:10: fatal error: H5pubconf.h: No such file or directory
 #include "H5pubconf.h"
          ^~~~~~~~~~~~~
compilation terminated.
src/nanopolish_polya_estimator.cpp:40:10: fatal error: H5pubconf.h: No such file or directory
 #include "H5pubconf.h"
          ^~~~~~~~~~~~~
compilation terminated.
src/nanopolish_phase_reads.cpp:38:10: fatal error: H5pubconf.h: No such file or directory
 #include "H5pubconf.h"
          ^~~~~~~~~~~~~
compilation terminated.
src/nanopolish_methyltrain.cpp:39:10: fatal error: H5pubconf.h: No such file or directory
 #include "H5pubconf.h"
          ^~~~~~~~~~~~~
compilation terminated.
src/nanopolish_call_methylation.cpp:36:10: fatal error: H5pubconf.h: No such file or directory
 #include "H5pubconf.h"
          ^~~~~~~~~~~~~
compilation terminated.
src/alignment/nanopolish_eventalign.cpp:35:10: fatal error: H5pubconf.h: No such file or directory
 #include "H5pubconf.h"
          ^~~~~~~~~~~~~
compilation terminated.
Makefile:120: .depend: No such file or directory
make: *** [Makefile:118: .depend] Error 1

**Comment by jts** [comment]
Can you attach (or email) the full log file?

**Comment by gwaldbieser** [comment]
[make.log](https://github.com/jts/nanopolish/files/2416688/make.log)

**Comment by jts** [comment]
I noticed a mistake in the Makefile from the gist. Could you try (from a fresh clone) this version: https://gist.github.com/jts/4fd5a12b55c91986d59b6c35105247a9#file-makefile

Thanks and sorry for the hassle.

**Comment by gwaldbieser** [comment]
That worked. Thanks!

**Comment by mbhall88** [comment]
@jts just wondering if you have an idea of when a new release with this fix will be available? The current release (v0.10.2) throws this error.

**Comment by jts** [comment]
Hi @mbhall88,

I've just pushed the change to github, can you try it and report back?

Thanks,
Jared

**Comment by mbhall88** [comment]
Yep, the latest commit, https://github.com/jts/nanopolish/commit/d7c09ab248ed70ca6c02a6d778d85e57bc92be3a, is all good.

**Comment by jts** [comment]
Great, thanks
