### ISSUE TITLE
vcf2fasta fails

### ISSUE THREAD

**Issue by MaestSi** [jts/nanopolish#469]
Dear Nanopolish developers,
I am using nanopolish variants --consensus to polish a draft assembly.
I know that after updating Nanopolish to version to 0.10.2, script 'vcf2fasta' has to be called to polish the draft sequence based on the supplied vcf file.
However, when running command:
`nanopolish vcf2fasta -g draft_genome.fasta nanopolish_output.vcf`
I get this error:

> nanopolish: src/nanopolish_vcf2fasta.cpp:139: int vcf2fasta_main(int, char**): Assertion `fields.size() == 2' failed.

(nanopolish_output.vcf has been correctly generated by nanopolish variants --consensus command).
Any suggestions?
Thanks in advance

**Comment by jts** [comment]
Can you paste the first 20 lines of `nanopolish_output.vcf`?

Jared

**Comment by MaestSi** [comment]
Here is the full output.

> ##fileformat=VCFv4.2
> ##nanopolish_window=consensus=00908699-6889-4fd6-824c-843c7e86a296;seqs=50:0-649
> ##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">
> ##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">
> ##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">
> ##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">
> ##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">
> ##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
> #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample
> consensus=00908699-6889-4fd6-824c-843c7e86a296;seqs=50  51      .       A       AG      153.6   PASS    TotalReads=11;AlleleCount=1;SupportFraction=0.887719    GT      1
> consensus=00908699-6889-4fd6-824c-843c7e86a296;seqs=50  466     .       A       AC      149.4   PASS    TotalReads=11;AlleleCount=1;SupportFraction=0.80214     GT      1
> consensus=00908699-6889-4fd6-824c-843c7e86a296;seqs=50  46      .       A       AA      13.2    PASS    TotalReads=11;AlleleCount=1     GT      .
> consensus=00908699-6889-4fd6-824c-843c7e86a296;seqs=50  498     .       A       AA      11.9    PASS    TotalReads=11;AlleleCount=1     GT      .
>

**Comment by jts** [comment]
Ah, it doesn't like the name of the input contig `consensus=00908699-6889-4fd6-824c-843c7e86a296;seqs=50`. What assembler did you use?

Jared

**Comment by MaestSi** [comment]
I used vSearch. Should I rename the consensus by myself, or will this little bug be fixed to let vcf2fasta work properly also with "unconventional" names?

**Comment by jts** [comment]
I'll try to fix it a little later today

**Comment by jts** [comment]
this is fixed now in the version I just pushed to github
