### ISSUE TITLE
make: *** No rule to make target `libhdf5.install'.  Stop.

### ISSUE THREAD

**Issue by proukakis** [jts/nanopolish#47]
On OS X El Capitan, with the latest Xcode and command line tools, I get this when trying to install via docker. 

I am sure I am doing something wrong bit I am getting desperate, any suggestions welcome.

thanks

**Comment by ljdursi** [comment]
I don't think you're doing anything wrong, it looks like the Makefile got updated and the Dockerfile got out of sync.

The old `libhdf5.install` target is no longer necessary and in fact no longer exists.  Can you remove that from the Dockerfile and re-build?  e.g., changing the make line from

```
RUN make libhdf5.install nanopolish
```

to

```
RUN make nanopolish
```

should work.  We'll fix this on our end as well.

**Comment by proukakis** [comment]
Many thanks, will try Monday

Sent from my iPhone

On 16 Apr 2016, at 6:32 pm, Jonathan Dursi <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't think you're doing anything wrong, it looks like the Makefile got updated and the Dockerfile got out of sync.

The old libhdf5.install target is no longer necessary and in fact no longer exists. Can you remove that from the Dockerfile and re-build? e.g., changing the make line from

RUN make libhdf5.install nanopolish


to

RUN make nanopolish


should work. We'll fix this on our end as well.

-

**Comment by jts** [comment]
Any luck?

**Comment by proukakis** [comment]
Hi, sort of, thanks!

I edited the docker file as you said and it does the trick

I am now stuck however because of my very limited IT skills

I am not sure how to implement the next step

docker run -v /path/to/local/data/data/:/data/ -it :image_id  ./nanopolish eventalign -r /data/reads.fa -b /data/alignments.sorted.bam -g /data/ref.fa

I don’t think I got a UUID, or I obviously misunderstood it- I guess I could try to build it again

I jus managed to get poretools working, but I can;t get it to give me a fasta file- it just prints the output to the terminal window, so I am obviously doing something wrong there too


Best

christos


--
Dr Christos Proukakis PhD FRCP
UCL Institute of Neurology
Clinical Neuroscience, Royal Free Campus
c.proukakis@ucl.ac.uk

From: Jared Simpson
Reply-To: jts/nanopolish
Date: Monday, 18 April 2016 at 17:14
To: jts/nanopolish
Cc: Christos Proukakis
Subject: Re: [jts/nanopolish] make: *** No rule to make target `libhdf5.install'. Stop. (#47)


Any luck?

**Comment by proukakis** [comment]
I wonder if you have experience with Anaconda? The installations seems to go smoothly.

**Comment by ljdursi** [comment]
You can find the id of the image by running `docker images`; the top line will be the most recently built image, and you can use the image id, eg

```
docker run e3adf22ff77b ./nanopolish help
```

will run `nanopolish help`.

Alternately, when building, you can provide a name, eg

```
docker build -t nanopolish:0.4.0 .
```

And then run with 
```
docker run nanopolish:0.4.0 ./nanopolish help
```

The -v option lets you point to the relevant data directories.

**Comment by proukakis** [comment]
Ok I think I got it, thanks again!

--
Dr Christos Proukakis PhD FRCP
UCL Institute of Neurology
Clinical Neuroscience, Royal Free Campus
c.proukakis@ucl.ac.uk

From: Jonathan Dursi
Reply-To: jts/nanopolish
Date: Monday, 18 April 2016 at 19:18
To: jts/nanopolish
Cc: Christos Proukakis
Subject: Re: [jts/nanopolish] make: *** No rule to make target `libhdf5.install'. Stop. (#47)


You can find the id of the image by running docker images; the top line will be the most recently built image, and you can use the image id, eg

docker run e3adf22ff77b ./nanopolish help


will run nanopolish help.

Alternately, when building, you can provide a name, eg

docker build -t nanopolish:0.4.0 .


And then run with

docker run nanopolish:0.4.0 ./nanopolish help


The -v option lets you point to the relevant data directories.

**Comment by proukakis** [comment]
Hello again

I have docker nanopolish image

I am doing poretools to get the fasta /Users/christos/Desktop/BC01/data >reads.fa

I then do

docker run -v /Users/christos/Desktop/BC01/data/data/:/data/ -it 6a99205dccc7 ./nanopolish eventalign -r /data/reads.fa -b /data/alignments.sorted.bam -g /data/ref.fa

This gives me

Error: could not find path to FAST5 for read b2460d4b-500c-4859-829e-c95339f456fa_Basecall_Barcoding_2d

Please make sure that this path is accessible: /Users/christos/Desktop/BC01/data/User_PC_default_sample_id_1812_1_ch14_read149_strand.fast5

Although I haven’t moved any files around.

I have also tried it with a single .fast5 (not the whole set), and still the same.

The .fa file has this header
>b2460d4b-500c-4859-829e-c95339f456fa_Basecall_Barcoding_2d User_PC_default_sample_id_1812_1_ch14_read149_strand /Users/christos/Desktop/BC01/data/User_PC_default_sample_id_1812_1_ch14_read149_strand.fast5

I hope I am using this correctly- I have a bam that was actually done using graphmap (not bwa-mem), but this doesn’t seem to be the problem.

I am using Poretools via Anaconda as I couldn’t get the docker image to work, could this be the problem?

I will have another think tomorrow, any hints very welcome.

Many thanks

christos
--
Dr Christos Proukakis PhD FRCP
UCL Institute of Neurology
Clinical Neuroscience, Royal Free Campus
c.proukakis@ucl.ac.uk

From: Jonathan Dursi
Reply-To: jts/nanopolish
Date: Monday, 18 April 2016 at 19:18
To: jts/nanopolish
Cc: Christos Proukakis
Subject: Re: [jts/nanopolish] make: *** No rule to make target `libhdf5.install'. Stop. (#47)


You can find the id of the image by running docker images; the top line will be the most recently built image, and you can use the image id, eg

docker run e3adf22ff77b ./nanopolish help


will run nanopolish help.

Alternately, when building, you can provide a name, eg

docker build -t nanopolish:0.4.0 .


And then run with

docker run nanopolish:0.4.0 ./nanopolish help


The -v option lets you point to the relevant data directories.

**Comment by ljdursi** [comment]
This is something we're going to have to work on; for now you could work around it by, if you don't already have a `reads.fa.fofn`, running

```
awk '$1 ~ /^>/ {split ($3,var,/\//); printf "%s /data/%s\n",$1,var[7] }' reads.fa | tr -d '>' > reads.fa.fofn
```
Otherwise, editing the .fofn file to get rid of the path `/Users/christos/Desktop/BC01`. 

An alternative to running through the dockers, if you already have homebrew installed on your macbook, would be to install (a slightly older version of) nanopolish that way:

```
brew install homebrew/science/nanopolish
```

and then you can run nanopolish natively rather than through docker (and then the paths should all be correct)

**Comment by proukakis** [comment]
thanks again, I 'll try the home brew

Christos

Sent from my iPad

On 20 Apr 2016, at 9:47 pm, Jonathan Dursi <notifications@github.com<mailto:notifications@github.com>> wrote:


This is something we're going to have to work on; for now you could work around it by, if you don't already have a reads.fa.fofn, running

awk '$1 ~ /^>/ {split ($3,var,/\//); printf "%s /data/%s\n",$1,var[7] }' reads.fa | tr -d '>' > reads.fa.fofn


Otherwise, editing the .fofn file to get rid of the path /Users/christos/Desktop/BC01.

An alternative to running through the dockers, if you already have homebrew installed on your macbook, would be to install (a slightly older version of) nanopolish that way:

brew install homebrew/science/nanopolish


and then you can run nanopolish natively rather than through docker (and then the paths should all be correct)

-

**Comment by proukakis** [comment]
So...

I tried home-brew, the message I got was that it has been compiled with a different compiler and may not work correctly (I am on the mac Xcode GCC4.2, sorry I didn't keep the message, but it seems ok, and then the path can't be found again

Christoss-MacBook-Pro:data christos$ poretools fasta User_PC_GBA_171CER_0850_1_ch90_read64_strand.fast5 > User_PC_GBA_171CER_0850_1_ch90_read64_strand.fa
Christoss-MacBook-Pro:data christos$ nanopolish eventalign -r User_PC_GBA_171CER_0850_1_ch90_read64_strand.fa -b GBA_sorted.bam -g humanhg19mod.fa
contig	position	reference_kmer	read_index	strand	event_index	event_level_mean	event_stdv	event_length	model_kmer	model_mean	model_stdv	ƈ)
error: could not find fast5 path for bfda13c1-c866-4cfa-b85b-8b53e621bb4d_Basecall_2D_2d

this is the reads.fa.fast5.fofn
aa681e1f-e850-493f-b13e-7abc247bef2b_Basecall_2D_2d	User_PC_GBA_171CER_0850_1_ch90_read64_strand.fast5
aa681e1f-e850-493f-b13e-7abc247bef2b_Basecall_2D_complement	User_PC_GBA_171CER_0850_1_ch90_read64_strand.fast5
aa681e1f-e850-493f-b13e-7abc247bef2b_Basecall_2D_template	User_PC_GBA_171CER_0850_1_ch90_read64_strand.fast5

not sure if this was what was suggested, but I deleted the User_PC_GBA_171CER_0850_1_ch90_read64_strand.fast5 lines, and get the same result

I also got the same after trying the docker and awk command above

I also used R script by Mick Watson, still the same!
> setwd("~/Desktop/data")
> library(poRe)
> f5files <- dir(getwd(), pattern="\\.fast5$", full.names = TRUE)
> for (f5 in f5files) {
+ fa <- get_fasta(f5, which="2D")
+ if (typeof(fa) == "list" && exists("2D", where=fa)) {
+ cat(fa[["2D"]], file = "output.2D.fasta", sep = "\n", fill = FALSE)
+     }
+ }

is there something wrong with my fast5 files? I note the error refers to a path for bfda... which isn't anything like my fast5 - shouldn't they correspond?

sorry to be a pain, but I keep thinking I am going to crack it, and then nothing... might try fast files from other run or from other hard drive

**Comment by proukakis** [comment]
also...

Fasta from a pore tools demo fast5 gives me…

error: could not find fast5 path for bfda13c1-c866-4cfa-b85b-8b53e621bb4d_Basecall_2D_2d

This is the same file it is looking for in my own files- so basically nano polish keeps looking for the same fast5 every time!

Bizarre… I must be doing something wrong

**Comment by proukakis** [comment]
So, I am about to give up...

I installed again in the standard way, after deleting from home-brew, then
Make
Make check
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated
clang: error: unsupported option '-fopenmp'

Then i installed again from home-brew as above
and i get the same warning
Warning: homebrew/science/nanopolish dependency hdf5 was built with a different C++ standard
library (libc++ from clang). This may cause problems at runtime.

when running, it is still looking for the path to a totally different file, and can't find it

Reinstalled docker from scratch
 poretools fasta *.fast5>reads.fa
(there are three fast5 in there)

docker run -v /Users/christos/Desktop/data/:/data -it 7da41df5c3a8 ./nanopolish eventalign -r /data/reads.fa -b /data/GBA_sorted.bam -g /data/humanhg19mod.fa

there is no fofn file, but using the awk suggested gets me one 
bb7c4c5d-458e-4ecf-ab78-ccad5efe4454_Basecall_2D_2d /data/
bb7c4c5d-458e-4ecf-ab78-ccad5efe4454_Basecall_2D_complement /data/
bb7c4c5d-458e-4ecf-ab78-ccad5efe4454_Basecall_2D_template /data/
c75bc431-47fa-4ec6-82fc-405e3277897e_Basecall_2D_2d /data/
c75bc431-47fa-4ec6-82fc-405e3277897e_Basecall_2D_complement /data/
c75bc431-47fa-4ec6-82fc-405e3277897e_Basecall_2D_template /data/
aa681e1f-e850-493f-b13e-7abc247bef2b_Basecall_2D_2d /data/
aa681e1f-e850-493f-b13e-7abc247bef2b_Basecall_2D_complement /data/
aa681e1f-e850-493f-b13e-7abc247bef2b_Basecall_2D_template /data/
2e506d1c-41a9-4f38-bf13-7b7531c74aef_Basecall_2D_2d /data/
2e506d1c-41a9-4f38-bf13-7b7531c74aef_Basecall_2D_complement /data/
2e506d1c-41a9-4f38-bf13-7b7531c74aef_Basecall_2D_template /data/

I am not sure how to edit this correctly.
even so, would i have to edit it every time?

Unless anyone has a brilliant idea, I'll have to wait for another version, or an IT specialist locally to help.

thanks.

**Comment by jts** [comment]
I was away from Toronto so only looked at this now. Have you been regenerating the bam file every time you regenerate the fasta? There is no reason nanopolish should always look for the same read unless the bam or fofn are out of date.

Jared

**Comment by proukakis** [comment]
Thanks, I am baffled too, I have had the same bam on the last few tries at least

I think what I need to do is try to install the current version without using docker, there’s obviously a problem with my compiler when doing this, and that’s beyond me to solve at present, but someone can hopefully do it for me in a couple of weeks

I am grateful for your time, and sorry to keep hassling you. It will be really great when I do get it to work, we have some nice graphmap-aligned data on an interesting  9kb human amplicon.

Best christos
--
Dr Christos Proukakis PhD FRCP
UCL Institute of Neurology
Clinical Neuroscience, Royal Free Campus
c.proukakis@ucl.ac.uk

From: Jared Simpson
Reply-To: jts/nanopolish
Date: Saturday, 23 April 2016 at 19:24
To: jts/nanopolish
Cc: Christos Proukakis, Author
Subject: Re: [jts/nanopolish] make: *** No rule to make target `libhdf5.install'. Stop. (#47)

I was away from Toronto so only looked at this now. Have you been regenerating the bam file every time you regenerate the fasta? There is no reason nanopolish should always look for the same read unless the bam or fofn are out of date.

Jared

**Comment by jts** [comment]
Ok let us know if you need more help. To compile from scratch you'll need to use gcc >= 4.8. If you get it installed and it is still looking for the wrong reads send us all the files and we can debug on our local version.

Jared

**Comment by proukakis** [comment]
Dear Jared / all
I have tried to do everything from scratch. I have got over the apparent error in finding the correct fast5 file, but now I seem to have problems with hdf5.
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 0:
  #000: H5A.c line 1692 in H5Aexists_by_name(): unable to determine if attribute exists
    major: Attribute
    minor: Can't get value
  #001: H5Aint.c line 1200 in H5A_exists_by_name(): object not found
    major: Attribute
    minor: Object not found
  #002: H5Gloc.c line 430 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: H5Gtraverse.c line 641 in H5G_traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #005: H5Gloc.c line 385 in H5G_loc_find_cb(): object 'BaseCalled_template' doesn't exist
    major: Symbol table
    minor: Object not found
terminate called after throwing an instance of 'hdf5_tools::Exception'
  what():  /Analyses/Basecall_2D_000/BaseCalled_template/Model: error in H5Aexists_by_name
Abort trap: 6

I am basically getting the same problem, however i try to run nano polish.

I have tried two different data sets, one with barcodes.
I have tried to run via anaconda (which I have now deleted), docker, and now after making a clean installation and "make"- I had deleted hdf5 in the meantime.

So, I guess my hdf5 is a problem, I wonder whether it is because I have been messing around with several things including anaconda, but if you know of a way too solve this I'll be delighted.

One crucial point - I am going straight to nano polish eventalign -r ...., using a bam file created by Graphmap. Am I supposed to do this, or could this be the problem?

thanks again

**Comment by proukakis** [comment]
I have tried to think about this again, and my only explanation is that hdf5-1.8.14 which is included in nano polish is not compatible with mac os el capitan. The way to check would be to use an older mac, but I don't have access to one at present. I could also try to run via docker on windows, but my PC is now win10 and it is proving so far impossible to run docker on it at all. Any hints or ideas welcome.

**Comment by jts** [comment]
From the May 17th message, it appears that your version of HDF5 was working, but your FAST5 files are not in the format expected by nanopolish. Could you send an example file to me?

**Comment by proukakis** [comment]
Of course, thanks

christos
--
Dr Christos Proukakis PhD FRCP
UCL Institute of Neurology
Clinical Neuroscience, Royal Free Campus
c.proukakis@ucl.ac.uk

From: Jared Simpson
Reply-To: jts/nanopolish
Date: Thursday, 16 June 2016 at 16:11
To: jts/nanopolish
Cc: Christos Proukakis, Author
Subject: Re: [jts/nanopolish] make: *** No rule to make target `libhdf5.install'. Stop. (#47)


From the May 17th message, it appears that your version of HDF5 was working, but your FAST5 files are not in the format expected by nanopolish. Could you send an example file to me?

**Comment by proukakis** [comment]
i eventually solved this by reinstalling and using pore tools, so the problem was my fasta. I now have different issues, will open another thread if i cant solve them soon
