### ISSUE TITLE
Could not read error

### ISSUE THREAD

**Issue by igwill** [jts/nanopolish#471]
Hi,

I'm trying to get Nanopolish (0.10.2) up and running and am having trouble simply indexing my reads.

I've tried the walk-through using:
`./nanopolish index -d ecoli_2kb_region/ reads.fasta`
The file is there and I can navigate to it just fine with that path.

Similarly, I've tried this with my own albacore (2.2.5) *.fastq file.

In both cases I get `error: could not open reads.fasta for read` (or the same, but *.fastq for the other file).

What am I missing here?

Thanks

**Comment by jts** [comment]
Hi,

That error indicates `reads.fasta` could not be opened. Maybe you forgot to `cd ecoli_2kb_region` before running he tutorial commands?

Jared

**Comment by igwill** [comment]
Hi Jared,

The way things have been installed on my work machine, the only way I can run nanopolish is when inside the nanopolish directory and running `./nanopolish`. I always need the `./` and can't run nanopolish from ecoli_2kb_region (or anywhere else). 
So, I tried setting the `-d` path relative to /nanopolish to go into ecoli_2kb_region when running `./nanopolish index`.

This is for sure a case of error on my end of things, but I'm not sure what I can do to make nanopolish (and minimap2, samtools, etc.) globally accessible without sitting in their directories. Seems to be more of a general Linux question than something specific to Nanopolish now.

Thank you

**Comment by jts** [comment]
You can just give the full path to nanopolish to run it from elsewhere:

```
/path/to/nanopolish index [...]
```

**Comment by igwill** [comment]
Oh, geez. That did the trick, thank you!

**Comment by jts** [comment]
No problem, glad to help.

Jared
