### ISSUE TITLE
Could not open fast5 file

### ISSUE THREAD

**Issue by malonge** [jts/nanopolish#472]
Hi,

I am trying to build my index with `nanopolish index`. Here is the command I use:

`~/software/nanopolish/nanopolish index -d /seq/sara/ONT/tomato/RW_0195_Tomato_102617/ -d /seq/sara/ONT/tomato/120817/ -d /seq/sara/ONT/tomato/113017/ -d /seq/sara/ONT/tomato/RW_tomato_M82_122917/ -d /seq/sara/ONT/tomato/113017/ -d /seq/sara/ONT/tomato/113017/ -d /seq/sara/ONT/tomato/113017/ -d /seq/sara/ONT/tomato/012518_M82_30kb_15_50/ -d /seq/sara/ONT/tomato/RW_tomato_122917_M82_snacks/ -d /seq/sara/ONT/tomato/SHG_010318_tomato_kevin/ -d /seq/sara/ONT/tomato/SHG_010318_tomato_snacks/ -d /seq/sara/ONT/tomato/113017/ -d /seq/sara/ONT/tomato/113017/ reads.fasta `

However, I get the following errors for a few files (here's an example of one):

`could not open fast5 file: /seq/sara/ONT/tomato/120817//GBX0018_20171208_GA10000_sequencing_run_RW_0218_Tomato_M82A_posD_120817_79182_ch168_read2415.fast5` 

However, I have permission to this file and am able to open it. Could there be some other thing, aside from permissions, which might cause this error?

I should note that at the end of the log file, it states `num reads: 6946615, num reads with path to fast5: 3714352`

Thanks

**Comment by jts** [comment]
If you re-run the command do you get the same error?

**Comment by malonge** [comment]
Yes, this has happened twice now.

**Comment by jts** [comment]
Hmm, it is difficult to say what the problem could be. If you are able to view the contents of the file from the same user that runs nanopolish then nanopolish should be able to read it as well. Since some reads (3714352) were successfully read it suggests its not a global problem.

If you run with just the problematic directory (`nanopolish -d /seq/sara/ONT/tomato/120817/ reads.fasta`) does it still give an error on that read?

Jared

**Comment by malonge** [comment]
Thanks, I will give that a shot. And yeah it is super confusing since I am able to open the file.

**Comment by malonge** [comment]
Alright after trying it with just the directory in question I still get the same errors. It seems like a problem on my end.

**Comment by jts** [comment]
Any luck fixing this? I'm going to close this issue for now but feel free to reopen if there is still a problem I can help with.

**Comment by malonge** [comment]
We suspect these are corrupted fast5 files as other tools can't open them either (e.g. poretools). We are still debugging and will reopen if there is anything of interest.

Thanks for the help.

**Comment by jts** [comment]
Ok, thanks.

**Comment by qiuyixmm** [comment]
Hello, i got the same problem:
could not open fast5 file: ~/fast5_files/GXB01143_20180313_FAH59244_GA10000_sequencing_run_20180313_NPL0039_E1_81227_read_4239_ch_336_strand.fast5
could not open fast5 file: ~/fast5_files/GXB01143_20180313_FAH59244_GA10000_sequencing_run_20180313_NPL0039_E1_81227_read_4596_ch_394_strand.fast5
could not open fast5 file: ~/fast5_files/GXB01143_20180313_FAH59244_GA10000_sequencing_run_20180313_NPL0039_E1_81227_read_3329_ch_364_strand.fast5
could not open fast5 file: ~/fast5_files/GXB01143_20180313_FAH59244_GA10000_sequencing_run_20180313_NPL0039_E1_81227_read_2554_ch_70_strand.fast5
could not open fast5 file: ~/fast5_files/GXB01143_20180313_FAH59244_GA10000_sequencing_run_20180313_NPL0039_E1_81227_read_2304_ch_287_strand.fast5
could not open fast5 file: ~/fast5_files/GXB01143_20180313_FAH59244_GA10000_sequencing_run_20180313_NPL0039_E1_81227_read_9714_ch_405_strand.fast5
could not open fast5 file: ~/fast5_files/GXB01143_20180313_FAH59244_GA10000_sequencing_run_20180313_NPL0039_E1_81227_read_3195_ch_466_strand.fast5
could not open fast5 file: ~/fast5_files/GXB01143_20180313_FAH59244_GA10000_sequencing_run_20180313_NPL0039_E1_81227_read_4938_ch_457_strand.fast5
[readdb] num reads: 3174598, num reads with path to fast5: 3174589

Are there any solutions to this problem?  Thanks!

**Comment by malonge** [comment]
I am having a hard time remembering exactly what we did since it has been a little while. I definitely remember that the overall problem was an inconsistency between the fast5 directory structure and our sequencing_summary.txt files (specified with the -f parameter). I would check that these are all consistent.

**Comment by qiuyixmm** [comment]
@malonge  Hello, I did not provided sequencing_summary.txt files when building  index.  The commandline I used was like this  :
   nanopolish index -d fast5_files  nanopore_sequence.fastq
   So, the inconsistency between fast5 directory structure and sequencing_summary.txt files may not be main problem.

**Comment by malonge** [comment]
The next thing I would try is to see if those files are corrupt. Can you open them with another tool that works on fast5 files? We tried opening corrupt files with poretools.

**Comment by zifeng8824** [comment]
> 
> 
> @malonge Hello, I did not provided sequencing_summary.txt files when building index. The commandline I used was like this :
> nanopolish index -d fast5_files nanopore_sequence.fastq
> So, the inconsistency between fast5 directory structure and sequencing_summary.txt files may not be main problem.

hi, can you resolve this problem?

**Comment by jts** [comment]
Can you open a new issue and attach a few of the problematic files?

**Comment by zifeng8824** [comment]
> 
> 
> Can you open a new issue and attach a few of the problematic files?

I have open a new issue,the title is "Could not open fast5 file(methylation_example)",thanks!
