### ISSUE TITLE
Adding ARM test on CI

### ISSUE THREAD

**Issue by junaruga** [jts/nanopolish#473]
I want to use `nanoplish` on embedded use (Raspberry Pi).

And seeing below pull-request, maybe the person also wants to use `nanopolish` on ARM.

Removing unnecessary parts in scrappie to get nanopolish working on ARM
https://github.com/jts/nanopolish/pull/402

I think adding ARM test case is good to manage the use case.
For example after applying #402 's patch, how to keep the validation?

I share 3 or 4 CIs supporting ARM, I researched.

## Shippable

This is the most possible way.
The CI is managed by a configuration file `shippable.yml` like Travis CI.
It's free and unlimited build for public open source project.
This is good for basic use of ARM.

http://www.shippable.com
http://docs.shippable.com/ci/yml-structure
http://blog.shippable.com/shippable-arm-packet-deliver-native-ci-cd-for-arm-architecture
http://docs.shippable.com/platform/tutorial/workflow/run-ci-builds-on-arm/

## Work on ARM

This service looks for open source project to use ARM instance.
This is to set up whole environment for ARM. It's good to do more complicated things, such as using a compiler LLVM. I have heard it from a friend.

Work on ARM:
https://www.worksonarm.com/cluster/
Some people are requesting to use this service from below issues page.
https://github.com/worksonarm/cluster/issues
The blog is good to check information about CI for ARM
https://www.worksonarm.com/blog

## Drone.io

This CI also supports ARM.
But the steps to start to use is a little harder than Shippable.
I am negative to use this CI right now.

https://drone.io/
https://blog.drone.io/drone-announces-official-support-for-arm/
http://docs.drone.io/installation/

## Travis CI

It seems that Travis CI does not have a plan to support ARM, seeing below issues page.
https://github.com/travis-ci/travis-ci/issues

There might be a way to test on ARM for Travis CI.
But it seems the steps to start is quite hard. I do not like this way.
https://www.tomaz.me/2013/12/02/running-travis-ci-tests-on-arm.html

How do you think?
If you like it, I can work for that.

**Comment by jts** [comment]
Thanks for this. I will look into this but I have been rather busy lately so I'm not sure if I will have time to set up an ARM CI soon.

Jared

**Comment by junaruga** [comment]
Hi @jts , thanks for the answer.
I talked with a friend who are familiar with ARM.
He recommended Shippable as a basic use, and workforarm as a advanced use such as to use LLVM on ARM. I requested to use the ARM machine to Shippable, and then I got the environment.
When I have a time, I would look into this. :)

**Comment by junaruga** [comment]
Let's close this. Now `nanopolish` has the ARM test cases on CI.
