### ISSUE TITLE
eventalign --scale-events: What does it mean? 

### ISSUE THREAD

**Issue by BisonKok** [jts/nanopolish#474]
Hi. When I read that the `--scale-events` parameter for `eventalign` is to scale events to the model, rather than vice-versa. I don't understand what it means. What would be the difference in term of output if this parameter is not included? Thanks in advance.

**Comment by jts** [comment]
Hi,

The sequencing conditions differ read-to-read so the raw signals are not directly comparable. We account for this by performing a linear scaling of the events for a read by factors we call `shift`, `scale`, `drift` and `var`. You can read a more detailed description of these factors [here](https://media.nature.com/original/nature-assets/nmeth/journal/v14/n4/extref/nmeth.4184-S1.pdf). The `--scale-events` option will attempt to remove these factors so the signals for different reads can be compared to each other. 

Jared

**Comment by guangzhaocs** [comment]
Hi, I want to visit this link(https://media.nature.com/original/nature-assets/nmeth/journal/v14/n4/extref/nmeth.4184-S1.pdf) but now it is unavailable. Could you provide this file? Because I want to have a deeper look at the `event_level_mean`.

Thanks.
