### ISSUE TITLE
nanopolish index relative path and portability 

### ISSUE THREAD

**Issue by mmiladi** [jts/nanopolish#475]
Hi Jared,

Running  `nanopolish index` with a relative path, produces relative entries for `index.readdb`. This is ideal for portability, in the sense that `nanopolish variant` step can be done on another system by copying the bundle of fast5 files and index files to the new system. Is this holds for the binary index files as well (fai, gzi, .index)? Are there any notes that should be taken?

Thanks,
Milad

**Comment by jts** [comment]
The other files are standard `samtools faidx`-like indices that don't contain paths, so it should be ok to move them.

Jared

**Comment by mmiladi** [comment]
Thanks for the clarification.
