### ISSUE TITLE
variants --consensus too many arguments 

### ISSUE THREAD

**Issue by Adelaam** [jts/nanopolish#477]
Hello again,

I am trying to polish a bacterial genome and I am getting this error:
'/home/mwiks/nanopolish/nanopolish' variants --consensus barcode03polished.fa -w 'tig00000069:0-1817' -r '/home/mwiks/mergedbarcode03.fasta' -b '/home/mwiks/mergedbarcode03.bam' -g '/home/mwiks/mergedbarcode03/barcode03.contigs.fasta' 
variants: too many arguments
I have tried with different genomes and tig but always I get the same error. 
Thank you!

**Comment by Adelaam** [comment]
I have tried this:
/home/mwiks/nanopolish/nanopolish' variants --consensus barcode03polished.vcf -w 'tig00000069:0-1817' -r '/home/mwiks/mergedbarcode03.fasta' -b '/home/mwiks/mergedbarcode03.bam' -g '/home/mwiks/mergedbarcode03/barcode03.contigs.fasta'
variants: too many arguments

and this:
'/home/mwiks/nanopolish/nanopolish' _makerange.py '/home/mwiks/mergedbarcode01/barcode01.contigs.fasta' | parallel --results barcode01polished -P 4 \ '/home/mwiks/nanopolish/nanopolish' variants --consensus -o polished01.{1}.vcf -w {1} -r '/home/mwiks/merged01barcode.fasta' -b '/home/mwiks/mergedbarcode01.bam' -g '/home/mwiks/mergedbarcode01/barcode01.contigs.fasta' -t 4 --min-candidate-frequency 0.1
error: faidx could not get contig length for contig usage
error: faidx could not get contig length for contig valid
error: faidx could not get contig length for contig help
error: faidx could not get contig length for contig version
error: faidx could not get contig length for contig call
error: faidx could not get contig length for contig eventalign
error: faidx could not get contig length for contig extract
error: faidx could not get contig length for contig getmodel
error: faidx could not get contig length for contig help
error: faidx could not get contig length for contig index
error: faidx could not get contig length for contig methyltrain
error: faidx could not get contig length for contig phase
error: faidx could not get contig length for contig scorereads
error: faidx could not get contig length for contig variants
error: faidx could not get contig length for contig vcf2fasta
error: faidx could not get contig length for contig for

Thank you!

**Comment by jts** [comment]
You are missing `-o`. Try:

```
/home/mwiks/nanopolish/nanopolish' variants --consensus -o barcode03polished.vcf -w 'tig00000069:0-1817' -r '/home/mwiks/mergedbarcode03.fasta' -b '/home/mwik/mergedbarcode03.bam' -g '/home/mwiks/mergedbarcode03/barcode03.contigs.fasta'
```

**Comment by Adelaam** [comment]
Warning: 6611 variants in span, region not called [10 2811]
Number of variants in span (11) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (17) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (11) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (13) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (16) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (15) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (10) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (35) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (37) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (24) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (59) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (19) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (36) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (40) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (15) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (12) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (32) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (14) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (14) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (10) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (24) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (30) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (32) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (22) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (10) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (13) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (14) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (43) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (50) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (78) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (37) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (48) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (14) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (39) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (12) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (45) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (16) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (66) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (25) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (25) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (16) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (11) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (16) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (37) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (13) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (21) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (24) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (19) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (11) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (11) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (19) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (12) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (54) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (60) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (49) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (19) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (59) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (93) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (36) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (23) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (50) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (15) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (58) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (10) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (20) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (22) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (38) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (32) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (22) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (11) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (30) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (19) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (46) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (19) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (25) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (13) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (27) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (26) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (21) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Warning: 112 variants in span, region not called [9760 9970]
Number of variants in span (12) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (34) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (10) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (84) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (57) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
[post-run summary] total reads: 1, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 0
I have got this and the vcf: 
#fileformat=VCFv4.2
##nanopolish_window=tig00000363:0-10312
##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">
##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">
##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">
##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">
##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample

**Comment by jts** [comment]
```
[post-run summary] total reads: 1, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 0
```

there is only one read aligned to the genome?

**Comment by Adelaam** [comment]
Yes, it was the wrong one, it is working now.

Thank you very much!!

**Comment by jts** [comment]
Great, no problem

**Comment by Adelaam** [comment]
Hello,

Just one more question about it when I tried makerange.py yesterday I got this error:
/home/mwiks/nanopolish/nanopolish' _makerange.py '/home/mwiks/mergedbarcode01/barcode01.contigs.fasta' | parallel --results barcode01polished -P 4 \ '/home/mwiks/nanopolish/nanopolish' variants --consensus -o polished01.{1}.vcf -w {1} -r '/home/mwiks/merged01barcode.fasta' -b '/home/mwiks/mergedbarcode01.bam' -g '/home/mwiks/mergedbarcode01/barcode01.contigs.fasta' -t 4 --min-candidate-frequency 0.1
error: faidx could not get contig length for contig usage
error: faidx could not get contig length for contig valid
error: faidx could not get contig length for contig help
error: faidx could not get contig length for contig version
error: faidx could not get contig length for contig call
error: faidx could not get contig length for contig eventalign
error: faidx could not get contig length for contig extract
error: faidx could not get contig length for contig getmodel
error: faidx could not get contig length for contig help
error: faidx could not get contig length for contig index
error: faidx could not get contig length for contig methyltrain
error: faidx could not get contig length for contig phase
error: faidx could not get contig length for contig scorereads
error: faidx could not get contig length for contig variants
error: faidx could not get contig length for contig vcf2fasta
error: faidx could not get contig length for contig for

Do you know why is that error?

Thank you!

**Comment by jts** [comment]
This:

/home/mwiks/nanopolish/nanopolish' _makerange.py

should be:

/home/mwiks/nanopolish/nanopolish'_makerange.py

(no space before the underscore)

**Comment by Adelaam** [comment]
Ah, ok.
But should I install nanopolish with python to get makerange.py working properly or with the latest code from github I can run it.
Because I am getting: bash: /home/mwiks/nanopolish/nanopolish_makerange.py: No such file or directory
Thank you

**Comment by jts** [comment]
it is in the scripts directory:

```
 /home/mwiks/nanopolish/scripts/nanopolish_makerange.py
```

**Comment by Adelaam** [comment]
Works now!

Thank you

**Comment by Adelaam** [comment]
Trying again today:
! /usr/bin/python '/home/mwiks/nanopolish/scripts/nanopolish_merge.py' '/home/mwiks/mergedbarcode02/bracode02.contigs.fasta' | parallel --results polished02.resuslts -P 4 \ '/home/mwiks/nanopolish/nanopolish' variants --consensus -o polished.{1}.vcf -w {1} -r '/home/mwiks/mergedbarcode02.fasta' -b '/home/mwiks/mergedbarcode02.fasta.index' -g '/home/mwiks/mergedbarcode02/bracode02.contigs.fasta' -t 4 --min-candidate-frequency 0.1
Traceback (most recent call last):
  File "/home/mwiks/nanopolish/scripts/nanopolish_merge.py", line 74, in <module>
    (contig, segment_range) = title.split(None, 1)[0].split(":")
ValueError: need more than 1 value to unpack

**Comment by jts** [comment]
You meant `nanopolish_makerange.py`, not `nanopolish_merge.py` at the beginning of the command.

**Comment by Adelaam** [comment]
Yes, it is working now. Sorry!
