### ISSUE TITLE
nanopolish vcf2fasta - Argument list too long

### ISSUE THREAD

**Issue by rfinkers** [jts/nanopolish#478]
with 40K scaffolds (larger genome) / 100960 VCF files produce, I run into an argument list to long error. Running the commands on a partial list runs into the error that not all of the original scaffolds have a result attached (which suggests that I should subset the fasta as well to hack things to an operational situation).

Any suggestions on how to push this forward?

**Comment by jts** [comment]
I'll need to add an option to pass in a file which contains a list of VCF file names. I'll try to do this soon.

**Comment by jts** [comment]
Using the commit 01e1438 that I pushed you can now pass in a file-of-filenames using the `-f` option.

**Comment by rfinkers** [comment]
Thanks Jared, that seems to do the trick. Will perform check on the resulting fasta to be sure.
