### ISSUE TITLE
MacOS installation issue... clang: error: unsupported option '-fopenmp'

### ISSUE THREAD

**Issue by davidfarr** [jts/nanopolish#480]
Hello there it looks like Nanopolish was definitely built with Linux in mind. I had absolutely zero luck in a Windows environment as it didn't have the majority of the dependencies and compatibility with the commands in the make file (and I don't have the expertise to change the file appropriately).

Now I'm in the MacOS environment trying to get it to work and through the use of a few brew installs I've got what I believe to be close to finishing the install. Right now, if I run the make command in terminal, this is what I get...

```
Davids-MBP:nanopolish david$ make
c++ -o src/main/nanopolish.o -c -g -O3 -std=c++11 -fopenmp -fsigned-char -I./include -I./htslib -I./fast5/include -I./src -I./src/hmm -I./src/thirdparty -I./src/thirdparty/scrappie -I./src/common -I./src/alignment -I./src/pore_model -I./eigen/ -fPIC src/main/nanopolish.cpp
clang: error: unsupported option '-fopenmp'
make: *** [src/main/nanopolish.o] Error 1
```

I am hoping someone else will be able to guide me through getting this part fixed. I have already tried:

- installing Xcode (App Store)
- installing Eigen (brew)
- typing the paths of g++ and gcc in to the makefile explicitly (and installing g++ and gcc --without-multilib through brew)
- installing llvm -with-clang
- editing make file "basic flags" to include version number ex. CXX ?= g++-8

And in between attempts I simply run "make" again. Do I need to "unmake" everything and try again, or is there something else I can change that will get me through?

**Comment by jts** [comment]
HI David,

As you've found nanopolish definitely won't work on Windows, however it should work in MacOS. I think there is a homebrew package, although I'm not sure if it is up to date.

To "unmake" you just need to run `make clean`. This will remove any of the build files.

Can you try this (after removing any changes you make to the Makefile):

```
make CC=gcc-8 CXX=g++-8
```

If it does not work, could you post the resulting messages?

thanks,
Jared

**Comment by davidfarr** [comment]
@jts That appears to have fixed it! Besides an occasional warning make completed with no errors.  I'll mark the issue closed.
