### ISSUE TITLE
error when running nanopolish variant

### ISSUE THREAD

**Issue by mariuswalter** [jts/nanopolish#481]
Hi, 
When running nanopolish variant to call SNP, I get the following error message:
```
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
Segmentation fault
```
Do you know what the problem could be?
Thanks for your help!
marius

**Comment by jts** [comment]
Hi,

I think something is wrong with the `.fai` file. Can you try deleting and re-generating them?

Jared

**Comment by mariuswalter** [comment]
Thanks! I started everything from scratch again and then it worked
