### ISSUE TITLE
option -o in nanopolish variants

### ISSUE THREAD

**Issue by mariuswalter** [jts/nanopolish#483]
Hi, i'm not sure to understand what the vcf file provided with the -o option is doing.
From what I understand, it tells nanopolish-variant to specifically looks for snp or indel at a list of already defined location, am I correct?
So it would miss any 'novel' variant?

Thanks for your help!

**Comment by mariuswalter** [comment]
Sorry, I meant -c ..

**Comment by jts** [comment]
In that case it depends on whether the `--consensus` option is used or not. In `--consensus` mode it will use the variants from the file you pass in from `-c` plus all single-base changes to the draft genome (substitutions, insertions and deletions). Without the `--consensus` flag it will only test the variants you pass in with `-c`.

Jared

**Comment by mariuswalter** [comment]
Thanks!
