### ISSUE TITLE
error: cannot run C compiled programs.

### ISSUE THREAD

**Issue by dirkdrost** [jts/nanopolish#485]
Hello,

I've been trying to install nanopolish on my mac for a while, but I keep getting all kinds of error's. This one I can't seem to resolve myself. Im running MacOS Mojave

This is the error I keep getting:

checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/Users/administrator/nanopolish/hdf5-1.8.14':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
make: *** [Makefile:91: lib/libhdf5.a] Error 1
MacBook-Pro-2:nanopolish administrator$ 

I also saw on other issues that you might need a config file, so i just added it. It might be a noob problem, but that's because I am one :)

Thanks a million! 

[config.log](https://github.com/jts/nanopolish/files/2475255/config.log)

**Comment by dirkdrost** [comment]
Hi Jared,

Thanks for your reply and my apologies for responding so late. I tried your suggestion in october and it didn't work. Today I tried it again and the makefile was working like a charm. It did get to install nanopolish. 

Now when I run 'nanopolish', I get the error:

>dyld: Library not loaded: @rpath/libgomp.1.dylib
  Referenced from: /Users/administrator/nanopolish/./nanopolish
  Reason: image not found
Abort trap: 6

Do you have any ideas?

Thanks again!
Dirk

**Comment by vchunch** [comment]
> Hi,
> 
> You need to compile nanopolish using gcc, not clang. Can you try to install gcc (from conda or homebrew maybe) then run:
> 
> ```
> make CC=gcc-<version> CXX=g++-<version>
> ```
> 
> where is the version number you installed.
> 
> Let me know how it goes,
> Jared

# gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)

Please suggest exact command syntx
