### ISSUE TITLE
Can I use nanopolish to generate a output file in fast5 format?

### ISSUE THREAD

**Issue by LinXialab** [jts/nanopolish#487]
Hi,
I wonder if we can use nanopolish to generate a output file in fast5 format, which contain the fastq extracted from raw signal.

 I hope to hear from you as soon as possible.

**Comment by jts** [comment]
No, I'm sorry but nanopolish can't do this.

**Comment by LinXialab** [comment]
OK，I got it.
Thank you so mach!
