### ISSUE TITLE
Nanopolish variants don't use all the reads in bam files

### ISSUE THREAD

**Issue by mariuswalter** [jts/nanopolish#489]
Hi,
I am using nanopolish variants to call snps. I aligned reads with minimap2 and my bam file contains 40000 mapped reads
However, when I run nanopolish variants, the post-run summary indicate a "total reads" around 500-1000. And when I inspect the vcf file on igv, it seems that nanopolish missed most snps, including very obvious ones.
I'm comparing viral sequences, so there is a huge number of potential snp between my sample and the reference, so maybe that affect the calling?
Any idea? Thanks for your help!

**Comment by jts** [comment]
Can you post the output line with the "total reads" number?

Can you also check whether the reads you expect to be use have high mapping quality?

jared

**Comment by mariuswalter** [comment]
Thanks for the fast answer!

`post-run summary] total reads: 437, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 42, bad fast5: 0`

So indeed, it seems that the majority of my read have a mapq of 0 (when I map with minimap2) or 1 (when I map with graphmap). I believe these reads are correctly mapped, but are flagged as mapping to multiple location. 
Which make sense because my reference genome is made of 4 contigs that are all very similar. (The viral genome comes in 4 different flavor that differ uniquely by the orientation of two segments). 

So I guess that nanopolish filter low quality reads?

**Comment by jts** [comment]
Yeah, nanopolish can't handle mapping quality 0 reads (I think the threshold is 20).

**Comment by mariuswalter** [comment]
Ok thanks! 
Is there a specific reason for that? Like the algorithm can't run properly, or is it simply a quality filtering step performed before any variant calling?

**Comment by jts** [comment]
Its quality filtering, the variant calls aren't reliable if the reads are ambiguously mapped.

**Comment by mariuswalter** [comment]
Thanks, It makes sense!
If I ever want to modify that in the source code, do you know where that would be?

**Comment by jts** [comment]
This line should do it:

https://github.com/jts/nanopolish/blob/master/src/alignment/nanopolish_alignment_db.cpp#L484

**Comment by mariuswalter** [comment]
Thanks!
