### ISSUE TITLE
Unitig split into multiple contigs after nanopolish

### ISSUE THREAD

**Issue by ml12220** [jts/nanopolish#49]
Hi,
I've sequenced the Lambda phage genome and I assembled the reads into a single contig of length 48,516 bases using canu. When I use nanopolish I end up with 5 contigs ranging in length from 8054 to 10309 bases (at a length of 49,225 bases). Does anyone know why this happens? Is it an issue with the assembly produced from canu or how nanopolish works?

Many thanks,
Mike

**Comment by jts** [comment]
Hi Mike,

nanopolish splits the genome into segments so that it can run the consensus algorithm in parallel. It provides a script to stitch the genome back together - take a look at the `nanopolish_merge.py` line in the README.

jared

**Comment by ml12220** [comment]
Thanks! Not sure how I missed this.

Mike

**Comment by jts** [comment]
No problem, closing this now feel free to reopen if you have other issues.
