### ISSUE TITLE
Support for older kits

### ISSUE THREAD

**Issue by mschatz** [jts/nanopolish#493]
Hi Jared,

We have been working on reproducing the results from the nanopolish methylation paper -- thanks for posting the detailed notes in the methylation-analysis repo. This repo is very helpful, but it uses a rather old version of nanopolish so have also been trying to reproduce the results with the current version. We can process some of the files just fine, but some of the data sets cause an error like these:

```
nanopolish/nanopolish methyltrain -t 4  --train-kmers all --out-fofn ecoli_er2925.pcr_MSssI.r9.timp.061716.alphabet_nucleotide.fofn --out-suffix .ecoli_er2925.pcr_MSssI.r9.timp.061716.alphabet_nucleotide.model -m ont.alphabet_nucleotide.R9.fofn -b ecoli_er2925.pcr_MSssI.r9.timp.061716.sorted.bam -r ecoli_er2925.pcr_MSssI.r9.timp.061716.fasta -g ecoli_k12.fasta.alphabet_nucleotide --filter-policy R9 "Chromosome:50000-3250000"

Error, unrecognized model kit SQK-LSK108
make: *** [ecoli_er2925.pcr_MSssI.r9.timp.061716.alphabet_nucleotide.fofn] Error 1
```

and

```
nanopolish/nanopolish methyltrain -t 4  --train-kmers all --out-fofn ecoli_er2925.pcr_MSssI.r9.timp.061716.alphabet_nucleotide.fofn --out-suffix .ecoli_er2925.pcr_MSssI.r9.timp.061716.alphabet_nucleotide.model -m ont.alphabet_nucleotide.R9.fofn -b ecoli_er2925.pcr_MSssI.r9.timp.061716.sorted.bam -r ecoli_er2925.pcr_MSssI.r9.timp.061716.fasta -g ecoli_k12.fasta.alphabet_nucleotide --filter-policy R9 "Chromosome:50000-3250000"

Error, unrecognized model kit SQK007
make: *** [ecoli_er2925.pcr_MSssI.r9.timp.061716.alphabet_nucleotide.fofn] Error 1
```

Browsing the source, it looks like the supported kits are:
```
static std::string kit_name_by_idx[] = { "SQK005", "SQK006", "r9_250bps", "r9.4_450bps", "r9.4_70bps" };
```

Is there an easy way to add support for the `SQK007` and `SQL-LSK108` kits, or is these just too old? Any tips would be appreciated.

Thanks in advance!

Mike

**Comment by jts** [comment]
Hi Mike,

Do you want to strictly reproduce the results from our paper, or just get roughly equivalent results to learn how to train models? If the former then I suggest you just use the old version of nanopolish that we describe in the pipeline script. If you want to learn how to train models maybe we (@timp0) can provide more recent data. I'm reluctant to put back in support for old datasets as it makes maintenance a pain since the HDF5 file structure is different. Happy to discuss.

Jared

**Comment by mschatz** [comment]
Hi Jared,

The main need is we want to practice running the current version of nanopolish on a dataset with a known result. Sounds like it is not easy to practice on the old data, so yes, would be great if there was a current dataset with known results. 

We have successfully run through the tutorials here: https://nanopolish.readthedocs.io/en/latest/quickstart_call_methylation.html and https://nanopolish.readthedocs.io/en/latest/quickstart_eventalign.html

So maybe you could extend these a bit more? Im interested in training as well as more basic steps like showing histograms of current with and without methylation (Figure 1 of https://www.nature.com/articles/nmeth.4184). We can make somewhat similar plots with new datasets, but they are different enough to make me second guess that we need to do additional normalization and/or filtering. 

But thanks so much for the existing tutorials! Extremely helpful for us to get started.

Thanks!

Mike

**Comment by mschatz** [comment]
Thanks so much!

Mike
