### ISSUE TITLE
calculate_methylation_frequency.py column num_motifs

### ISSUE THREAD

**Issue by suyanan** [jts/nanopolish#495]
hi,
run the command calculate_methylation_frequency.py, there was a error below:
File "$path/nanopolish/scripts/calculate_methylation_frequency.py", line 51, in <module>
      num_sites = int(record['num_motifs']) 
  KeyError: 'num_motifs‘

the input file's head was "chromosome	start	end	read_name	log_lik_ratio	log_lik_methylated	log_lik_unmethylated	num_calling_strands	num_cpgs	sequence", 
so maybe you should change the int(record['num_motifs'])  to  int(record['num_cpgs'])

**Comment by suyanan** [comment]
sorry, the version problem , now get it.

**Comment by tianrenmao** [comment]
I got an additional line "[fai_load] build FASTA index." in the methylation_calls.tsv and after I removed it the error disappeared.

**Comment by jts** [comment]
That message is printed to stderr, not stdout, and shouldn't have been captured in the output.
