### ISSUE TITLE
relation between SupportFraction and --min-candidate-frequency

### ISSUE THREAD

**Issue by jazberna1** [jts/nanopolish#496]
Hello,

I am using nanopolish version 0.10.2 to polish a mitochondrial draft sequence.
I have 2000X average coverage and my settings to call variants are:

nanopolish variants --verbose \
--calculate-all-support \
--min-candidate-frequency 0.8 \
--consensus --ploidy 1 -o polished.0.8.allsuport.vcf  \
-r reads.fasta \
-b alignments.bam \
-g sequence_to_polish.fasta \
-t 1 

I got one question from the resulting vcf:

Am I right saying that the variant candidates that made it to the vcf were those where the frequency on a particular position of the pileup differed to the reference on at least 80% of the reads?
I am asking this as I see records like this one below with SupportFraction=0.519295 that is less than 0.8 , should I dismiss them?
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
Contig_2	99	.	TN	T	1600.6	PASS	TotalReads=356;AlleleCount=1;SupportFraction=0.519295;SupportFractionByBase=0.013,0.037,0.021,0.929	GT	1

Many thanks for your help
Jorge

**Comment by jts** [comment]
Hi @jazberna1,

`--min-candidate-frequency` controls which variants nanopolish will consider as "candidate" SNPs. It uses the frequency of mismatches at a particular reference position in the basecalled reads. The SupportFraction tag indicates how many reads supported the variant allele based on nanopolish's signal-based model. 

With the parameter you set (0.8), 80% of the basecalled reads will need to mismatch the reference genome to use them as a candidate. This is likely too high, I suggest using the default (0.2).

I hope that helps.

Jared

**Comment by jazberna1** [comment]
Hello Jared,

Thanks so much for clarifying. I'll also set --min-candidate-frequency to 0.2 as you say.

Regards
Jorge
