### ISSUE TITLE
vcf2fasta crash

### ISSUE THREAD

**Issue by rfinkers** [jts/nanopolish#498]
on: ~/bin/nanopolish/nanopolish vcf2fasta -g old_genome.fa -f vcf_filenames.txt > new_genome.fa

I'm running in the following error:
nanopolish: ./src/common/nanopolish_variant.h:74: void Variant::read_vcf(const string&): Assertion `!ref_name.empty()' failed.
Aborted

Any pointers to move this forward?

**Comment by rfinkers** [comment]
4Gb genome, with still quite some contigs! would you be able to catch/patch this one and print the misbehaving vcf filename?

**Comment by jts** [comment]
It would be best if you can identify the problematic vcf file (by bisecting the entries inf `vcf_filesnames`) and send it to me so I can have a look.

**Comment by rfinkers** [comment]
Not sure that I fully understood your question. FYI, we talking about 101.467 VCF file's. So, just understanding which one is troublesome already... Will see what I can figure out.

**Comment by rfinkers** [comment]
The total job is 1 month compute / 100 CPU's. Need to see what is possible.

**Comment by jts** [comment]
I don't mean re-running `nanopolish variants`, I meant changing the input to `vcf2fasta`. 

Can you send me a tar.gz with all the vcfs and the draft genome? I can do the bisection here

**Comment by rfinkers** [comment]
thanks for clarifying, will give it an initial try.
