### ISSUE TITLE
phase-read issue

### ISSUE THREAD

**Issue by wjidea** [jts/nanopolish#499]
Hi Jared,

I attempted to use the phase-read function with Nanopolish.

I have both Nanopore and Illumina reads so I was using Illumina called SNV to phase my nanopore reads.

The nanopolish phase-read output is a SAM file. I am wondering how can I extract reads for each haplotype?

Thanks,

Jie

**Comment by jts** [comment]
Hi,

Sorry for the slow response.

`nanopolish phase-reads` will simply indicate which allele(s) each read supports. You might try running whatshap to phase the alleles onto haplotypes, which works well for nanopore data.

Jared
