### ISSUE TITLE
no @SQ lines in the header. Missing header? 

### ISSUE THREAD

**Issue by abayega** [jts/nanopolish#50]
Hi, I am trying to polish my draft assembly with nanopolish but after ssending the first command 'make -f scripts/consensus.make READS=reads.fa ASSEMBLY=draft.fa' I get the following error;
[samopen] no @SQ lines in the header
[sam_read1] missing header? Abort!

Any advice? Thanks

**Comment by jts** [comment]
Did you receive any other error messages? It would appear that either bwa or samtools failed for some reason (possibly the versions are too old?)

**Comment by abayega** [comment]
make: *** [/home/abayega/Documents/C002_05_4/alignment/2Dpass.pp.bam] Error 1
Many thanks jts. The only other error is that one above.

**Comment by jts** [comment]
Can you paste your bwa and samtools versions?

**Comment by abayega** [comment]
samtools 0.1.19-1
bwa         0.7.5a-2

**Comment by jts** [comment]
I think those are too old, can you upgrade and try again?

**Comment by abayega** [comment]
Okay, many thanks.

**Comment by abayega** [comment]
Thanks again, the old bwa didn't have the -x option which specifies data from pacbio or nanopore. After installation of the latest version, all seems good so far

**Comment by jts** [comment]
Great, I'm going to close this issue, feel free to open a new issue if any other problems come up.
