### ISSUE TITLE
Call Nanopolish

### ISSUE THREAD

**Issue by Lau16** [jts/nanopolish#500]
Hi Jared,
I am having difficult when I call Nanopolish (after indexing and mapping). After 10 min run I got the message “Killed”.
Looking at the syslog, it might be possible that I have problem with SWAP.
My question is what are the Nanopolish requirements  in relation with size of RAM (I have 32G size RAM) and   size of SWAP file. 
Waiting for your answer,
Regards
Laura

**Comment by jts** [comment]
Hi @Lau16,

Memory usage depends on genome coverage, the number of parallel tasks that you run simultaneously and the polishing window size. What command did you run?

Jared

**Comment by jts** [comment]
This command will polish the entire genome in one step, and use a huge amount of memory. Our recommendation is to polish the genome in 50kbp segments, as described here:

https://github.com/jts/nanopolish#computing-a-new-consensus-sequence-for-a-draft-assembly
