### ISSUE TITLE
Number of variants in span (XX) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!

### ISSUE THREAD

**Issue by splaisan** [jts/nanopolish#501]
This is closely related to https://github.com/jts/nanopolish/issues/235 but not identical, I therefore create a new ticket.

quite some background info:
* my genome is a bacterium, so it is haploid.
* I cannot validate my results as this is a 'novel' bacterium and cannot be strictly compared to an existing refseq although it is close to many from blasts I did already
* I have a lot of minion data (420x coverage) so I took only the largest molecules >10k and avgqual>12.5 for canu (still >170x genome size) and got one chr of about 5mb predicted circular which is great!
* I also find one plasmid of ~100k predicted circular and another one of about the same size but not predicted circular. How comes? Do they share a part and canu put this all in one?
* besides these 3 large contigs, all other canu contigs are in the 10 20kb with very little coverage, I think they are noise but will annotate them for sure
* For polishing, I took all molecules >1kb and avgqual > 12.5 (>380x genome size) and used bwa for mapping the reads

>  bwa mem -x ont2d ...

* first polishing was done using racon as recommended elsewhere 
* a second and final nanopolish run was done in several attempts always leading to the title warnings (many) but successful in producing VCF data at the end (and a nice consensus fasta with the next command)
* I tried to improve my command as well as get rid of these many message, leading to the following:

```
python ${nanopolish_makerange} ${iter1bwa} \
    | parallel --results ${iter1bwa}_nanopolish.results -P ${thr} \
    nanopolish variants \
        --consensus \
        -o polished.{1}.vcf \
        -w {1} \
        -r ${correads} \
        -b ${prefix}_bwa_${iter1bwa%_consensus.fasta}.sorted.bam \
        -g ${iter1bwa} \
        -t 4 \
        --min-candidate-frequency=0.4 \
        --min-candidate-depth=100 \
        --max-haplotypes=100000 \
        --methylation-aware='dcm,dam' \
        --ploidy=1 \
        --fix-homopolymers
```

even the 

> --max-haplotypes=100000

 triggers the warning! how can this be? do I reazlly have more than 10000 and is this because my windows are too large? anything to do here to improve sensitivity and results?

Any comments on the additional parameters are very welcome; they were recommended for Ecoli on different places and I am guilty of putting them together.
Should I use larger molecules (smaller quantity) for correction than my large >1kq12.5 set, provided I have so much data? - which minimal size?
Did I make right assumptions or am I wrong?

Thanks in advance

**Comment by jts** [comment]
Hi @splaisan,

Sorry for the slow response, I am preparing a new release. 

These "max-haplotypes" warnings can be ignored. Nanopolish runs in two steps: it finds candidate variants that may improve the consensus, then tries to find the optimal consensus by combining the candidates onto "haplotypes". If there are too many possible combinations nanopolish will emit that warning and skip some combinations to reduce compute time. If the consensus accuracy of your assembly looks ok you can safely ignore these warnings. I'm going to change the wording of these warnings to be less alarming in an upcoming release.

I hope this helps,
Jared

**Comment by splaisan** [comment]
Thanks Jared,

I cannot evaluate the quality of the polished as this is a novel bacterium but was happy it finished without crash and with size close to input.

Do you have any comment on the combination of filters I applied (any inconsistent?)

Thanks for the great package

**Comment by jts** [comment]
I think your pipeline is OK - the only comments I have is that Q12.5 is a pretty high quality filter, I would maybe suggest Q9 or Q10. Also 380x is excessive, maybe downsample to 200x? You could filter out some of the shorter reads to hit 200x and maybe get a better result.

jared

**Comment by splaisan** [comment]
Thanks Jared for you time,
One last comment in case you have any opinion about it
I assembled from the >10k reads only (170x cvg and Q>12.5 which removes quite few data in fact in this run) and from all reads (450x cvg).
When I compare the 2 assemblies, I have a lot of extra small contigs (10-50kb) in the full asm which I loose in the large-read asm and I am concerned about missing small biological entities only represented in shorter reads.
Gene annotation of the small contigs finds 'genes' and I do not know what these fragments are. Maybe leftover of canu excessive clipping...

**Comment by jts** [comment]
My guess is the leftover small contigs are artifacts, but it is hard to say without closely looking at the data.
