### ISSUE TITLE
Problem with VCF2FASTA --skip-checks

### ISSUE THREAD

**Issue by Jaoquien** [jts/nanopolish#503]
Hi everyone,

I want to learn to use Nanopolish to improve my CANU assemblies. I began following the example in the Quickstart (https://nanopolish.readthedocs.io/en/latest/quickstart_consensus.html) to fully understand what is going on. It seems that one of the modules does not work well, here I attach the command:

```
[jvinyes@wright ecoli_2kb_region]$ nanopolish variants --consensus -o polished.vcf \
>     -w "tig00000001:200000-202000" \
>     -r reads.fasta \
>     -b reads.sorted.bam \
>     -g draft.fa
[post-run summary] total reads: 101, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 0
[jvinyes@wright ecoli_2kb_region]$ nanopolish vcf2fasta --skip-checks -g draft.fa polished.vcf > polished_genome.fa
vcf2fasta: unrecognized option '--skip-checks'
```

I have tried to remove "--skip-cheks" option and it stills doesn't work:

```
[jvinyes@wright ecoli_2kb_region]$ nanopolish vcf2fasta -g draft.fa polished.vcf > polished_genome.fa
error: first 200000 bases are not covered by a polished window for contig tig00000001.
error: last 4174233 bases are not covered by a polished window for contig tig00000001.
error: one or more polishing windows are missing. Please check that all nanopolish variants --consensus jobs ran to completion
```

Do you know whcich could be the problem? I have the VCF file with the variants.

Thank you,

Quim

**Comment by jts** [comment]
Hi 

The version of nanopolish you’re using is too old.

Jared

**Comment by Jaoquien** [comment]
@jts I'm using Nanopolish.0.10.1, should I install 0.10.2? 

Thanks,

Quim

**Comment by jts** [comment]
yes

**Comment by Jaoquien** [comment]
@jts thank you so much

Quim
