### ISSUE TITLE
Resuming a crashed nanopolish variants run

### ISSUE THREAD

**Issue by igwill** [jts/nanopolish#504]
Hi,
I am getting close to finally polishing my canu draft assembly, but ran into a memory issue with my cluster and my job got cancelled.

Is there a way to resume the run and pick up from where I left off? My basic understanding is that `-w` can set a window, but I'd need the `makerange `script to also start at `tig000000022` and do everything remaining.

Can you suggest an edit to my previously submitted script?
```
#!/bin/bash
#SBATCH --cpus-per-task=8

python nanopolish_makerange.py "big.contigs.fasta" | parallel --results nanopolish.results -P 8 \
    nanopolish variants --consensus -o polished.{1}.vcf -w {1} -r "Pippin-albacore-2.2.5-FLO-PRO001-SQK-LSK109.porechop.fastq" -b minimap.draft.bam -g "big.contigs.fasta" -t 8 --min-candidate-frequency 0.
```

I'll also include a `--mem=120000000` or so to try to feed the thing more mem (the cluster shut me down at 65GB). 
If you see a possible bottleneck in my script, I can also try to ratchet up either `--cpus-per-task`, `-P`, or `-t` if can help me cruise through my polishing faster (40x coverage of a 42Mbp draft genome over 214 contigs, with 180x raw read coverage).

**Comment by jts** [comment]
Note with -P 8 and -t 8 you will consume 64 cores total, make sure the node you run it on can handle that. If you reduce the -P option (maybe to 4?) it will use less memory and cores.

**Comment by igwill** [comment]
I'll slow myself down a bit to -P 4, each node in our cluster indeed only has 32 cores.

Any thoughts on how to submit the script to resume from where I was cut off (around tig0...22)?

Thanks!

**Comment by igwill** [comment]
Ok I see, thanks for the suggestion.
