### ISSUE TITLE
not corrected snps

### ISSUE THREAD

**Issue by lfaino** [jts/nanopolish#505]
Dear Dev,
i was checking the quality of the correction step. i found something strange to me.

the VCF file generated by nanopolish contain about 10000 variants that were not included in the new consensus call. Can you explain why some variations are not used in generating a new consensus sequence?

Cheers
Luigi

**Comment by jts** [comment]
Hi @lfaino,

Can you paste the messages printed to the terminal by `nanopolish vcf2fasta` when you ran it?

Thanks
Jared
