### ISSUE TITLE
Albacore, Porechop and Indexing

### ISSUE THREAD

**Issue by Jaoquien** [jts/nanopolish#506]
Hi everybody,

I would like to ask about the processing of the reads and Nanopolish. Our workflow includes basecall FAST5 files using Albacore and then process Albacore's output with Porechop to trim barcodes and other sequences.

For example, if I have a run with 12 barcodes, after Albacore basecalling and Porechop filter, I get 12 FASTQ final files. Could I CAT those Porechop FASTQ files into 1 file (let's name it `Porechop_CAT.fastq`) and use it in the Index command?

`nanopolish index -d /path/to/raw_fast5s/ -s sequencing_summary.txt Porechop_CAT.fastq`

And then, if the previous is feasible, could I use the Porechop output for each barcode as the reads needed to align? An imaginary example, with `BC01_Porechop.fa` reads I assemble a genome (`BC01_Porechop_genome.fa`) with Canu. 

```
bwa mem -x ont2d -t 8 BC01_Porechop_genome.fa BC01_Porechop.fa | samtools sort -o BC01_Porechop.sorted.bam -T BC01_Porechop.tmp -
samtools index BC01_Porechop.sorted.bam
```

Thank you so much for your help,

Quim

**Comment by jts** [comment]
Hi @Jaoquien,

You can run nanopolish index on each barcoded file individually, passing in the complete directory of fast5s each time:

```
nanopolish index -d /path/to/raw_fast5s/ -s sequencing_summary.txt BC01_Porechop.fa
```

This should do the right thing, and let you polish the individual barcoded assemblies.

Jared

**Comment by Jaoquien** [comment]
@jts Thanks!

But If I perform for example the CAT of all Albacore's FASTQs and then I make the Index, then I only need to do the index once and not with every Barcode, don't I? So my question was that if I index ALL the Albacore's FASTQs in one file, then I could work with each barcode separately without the need of indexing each time the FASTQ reads. Am I wrong?

**Comment by jts** [comment]
nanopolish finds the index file based on the name of the input .fastq. So when you try to run on BC01_porechop.fa it won't be able to find the master index file you constructed. Its possible to hack around this by changing filenames but its probably not worth it - indexing the files individually is better.

**Comment by Jaoquien** [comment]
@jts Perfect, thank you so much for your help!
