### ISSUE TITLE
No haplotypes printing

### ISSUE THREAD

**Issue by pengelgau** [jts/nanopolish#507]
Hi Jared,

First off, I really appreciate your dedication and the attention you devote to nanopolish. Some background on what I'm trying to accomplish with nanopolish: I study apple diversity of a specific gene. I used PCR to amplify genomic DNA of the gene and it's upstream region. I added barcodes to my samples during the PCR. I then submitted them to the genomics core at my school and they added the adapters, performed the sequencing, and sent the data back to me. I've since parsed out the data by barcode via Porechop and have managed to figure my out through the earlier steps of nanopolish and am now at variants. My goal is to receive the two to three haplotypes (some apples are triploid) of this region for each of the apple varieties I'm investigating. Apples are very heterozygous and so I'm expecting there to be several differences between haplotypes. For the genome file I'm using the region of chromosome around my gene of interest from the current apple genome. However when I run variants I am receiving this error from this command: 
`nanopolish variants -p 3 -r GDE.fasta -b GDE.sorted.bam -e GDE.eventalign.bam -g ../golden_del.fasta
Assertion failed: (k <= N), function Combinations, file src/nanopolish_variant_db.cpp, line 32.
Abort trap: 6`
I've experimented with -snps and -x 1000000 and these still result in the error and no output. When I give --consensus I am actually given a readout with 16 variants. Two of these I can confirm from Sanger data (which I have to verify all my varieties) and past experiments. I suspect the remaining 14 to be true but just have no other verification. However this readout doesn't actually give me haplotypes with the SNPs that are associated together.

Am I inputting incorrect options for what I would like/ can nanopolish perform what I'd like which is to receive the full 2-3 haplotype sequences of my region?

**Comment by pengelgau** [comment]
-p 2 is giving me an output with more results than the -p 3 --consensus command. I do, however, think I need some guidance with interpreting the results. As I said earlier my ultimate goal is to have the 2-3 full length haplotypes/alleles which have their respective SNPs paired with each other. I'm not sure if I can deduce this from the output. Here's an example of my output and my interpretations of it for a diploid organism:
`#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
golden_del_gddh13_28519917:28527048	542	.	G	T	8943.2	PASS	BaseCalledReadsWithVariant=702;BaseCalledFraction=0.308165;TotalReads=2131;AlleleCount=1;SupportFraction=0.404824	GT	0/1
golden_del_gddh13_28519917:28527048	559	.	C	G	27629.7	PASS	BaseCalledReadsWithVariant=1937;BaseCalledFraction=0.848445;TotalReads=2123;AlleleCount=2;SupportFraction=0.946401	GT	1/1
golden_del_gddh13_28519917:28527048	572	.	TA	T	27629.7	PASS	BaseCalledReadsWithVariant=629;BaseCalledFraction=0.274913;TotalReads=2123;AlleleCount=1;SupportFraction=0.338027	GT	0/1
golden_del_gddh13_28519917:28527048	591	.	C	CG	15749.6	PASS	BaseCalledReadsWithVariant=1533;BaseCalledFraction=0.672368;TotalReads=2126;AlleleCount=2;SupportFraction=0.866337	GT	1/1
golden_del_gddh13_28519917:28527048	615	.	AC	A	4736.0	PASS	BaseCalledReadsWithVariant=656;BaseCalledFraction=0.289625;TotalReads=2124;AlleleCount=1;SupportFraction=0.318109	GT	0/1
golden_del_gddh13_28519917:28527048	624	.	A	G	4736.0	PASS	BaseCalledReadsWithVariant=1079;BaseCalledFraction=0.47638;TotalReads=2124;AlleleCount=1;SupportFraction=0.495504	GT	0/1
`
1) Does allele count indicate the number of alleles with that deviation from the reference? Thus if AlleleCount=2 does that mean both alleles disagree with the reference and that both have that variant? In continuation of this, does that mean AlleleCount=1 indicates just one allele to have that variant and that the others should match the reference at said location?
2) Additionally how should I interpret the sample column? Is this a way to relate which SNPs go with each other?

Also, while writing this I tried to look at another apple set which I know has a substantial indel difference between the alleles (~150bp) but it seems like the eventalign step is taking a while (over an hour). I'm trying it on the the full data set for the sample (30163 sequences). Is this normal or is this too much for nanopolish?

Thanks greatly

**Comment by jts** [comment]
`-p` and `--consensus` are mutually exclusive, you should only give one or the other.

AlleleCount is indeed the number of non-ref alleles. There isn't a way to figure out what SNPs go together. You might want to try the `whatshap` phasing program, which works fairly well for nanopore data.

You shouldn't have to run eventalign before consensus or variant calling.

**Comment by pengelgau** [comment]
Thanks for the suggestion for whatshap. It is doing what I need done. I wonder if anyone is working on a nanopore signal-level phasing program. Nonetheless, thanks for all the help.

**Comment by jts** [comment]
I started to work on one called "nanopolish phase-reads" that will show
which alleles from a VCF each read supports. It is not complete though but
you might want to try it.

Jared
