### ISSUE TITLE
Does the Basecalled fastq by Guppy could work for nanopolish?

### ISSUE THREAD

**Issue by tengfeixiaozhu** [jts/nanopolish#508]
# Index the output of the albacore basecaller
Does the output of Guppy basecaller in the PromethION sequencer satisfy the index procedure？
Looking forward for your reply! Thank you very much.

**Comment by jts** [comment]
Yes, guppy works too.

**Comment by tungufoss** [comment]
What about multi-read fast5s? When I used nanopolish 0.10.1 on guppy fastq where the underlying data is 8000 reads per fast5, I only indexed one read per file. So the version I was using just looks at the first read, and moves on.  
Is this maybe solved in 0.10.2? or upcoming release?

**Comment by tungufoss** [comment]
It will be out with the next MINKNOW release, which we were told would be out at the end of November (although probably more like before end-of-year). So I've just been prepping our pipeline with reads using the single_to_multi_fast5 python converting script ONT provided in the community.

**Comment by jts** [comment]
Ok, thanks for letting me know. I'll keep this issue open until I have added support for multi-fast5.

**Comment by jts** [comment]
Hi @tungufoss,

I've just pushed some changes that add support for multi-fast5 files. I'm going to test it for a day or so then I'll make a new release (0.11) if it all looks good. If you want to give it a try before then, you can grab the latest code now.

Jared

**Comment by tungufoss** [comment]
Excellent. I'll check it now 👍

**Comment by tungufoss** [comment]
I tried the latest version (commit e2745af324c1d59962c54a0e900c72586de32a71) , and I'm still only indexing the first read of multireads (using ONT's python script `single_to_multi_fast5`), leaving the rest unindexed.
```
nanopolish index -d fast5/ guppy.fastq.gz -s guppy.sequencing_summaries.txt --verbose 
[readdb] indexing fast5/
[readdb] num reads: 4339, num reads with path to fast5: 1
```
Note the input was a single fast5 multiread with version:
```
HDF5 "fast5/batch_0.fast5" {
ATTRIBUTE "file_version" {
   DATATYPE  H5T_STRING {
      STRSIZE H5T_VARIABLE;
      STRPAD H5T_STR_NULLTERM;
      CSET H5T_CSET_UTF8;
      CTYPE H5T_C_S1;
   }
   DATASPACE  SCALAR
   DATA {
   (0): "2.0"
   }
}
}
```
However, works fine with the single reads (albeit, all 8000 reads were indexed, not subset present in the input -- I guess the sequencing summary is responsible for the filtering).
````
HDF5 "flowcell/reads/0/xxx_strand.fast5" {
ATTRIBUTE "file_version" {
   DATATYPE  H5T_IEEE_F64LE
   DATASPACE  SCALAR
   DATA {
   (0): 0.6
   }
}
}

**Comment by tungufoss** [comment]
Ah. That works like a charm. All reads are properly index, and it was surprisingly fast. So there is no real need to use the sequencing summary anymore. 👍

**Comment by tungufoss** [comment]
Will go on ahead with methylation calling, and compare results and let you know

**Comment by tungufoss** [comment]
What is the second column "strand" in the methylation file for? It's always zero for my data. 
Can I turn that column off? Or at least push it back behind start/end columns? Because then I can compress the result file to gorz format easily. 
Otherwise, if I omit that new column, then there is no difference between the versions, and runs like a charm 🥇

**Comment by jts** [comment]
Hmm. We added a new column to the tsv output with the strand that the read maps to after a user requested it:

https://github.com/jts/nanopolish/commit/84f18654a6781c51f9ea932aec0e0ae75011ffac#diff-0205cc5220914181436bf251011d9101

It shouldn't be 0, it should be "+" or "-". Can you try a fresh re-build (`make clean && make`) to see if the problem persists? @mike-molnar can see if this feature still works locally?

Jared
