### ISSUE TITLE
Could I get methylation call for each summary file?

### ISSUE THREAD

**Issue by tengfeixiaozhu** [jts/nanopolish#509]
Hi Jared,
     As one sample could produce multiple flowcells and each flowcell could also have multiple sub-directory like 0,1,2, could I do index, mapping and methylation call for each fastq file basecalled from the sub-directory. If so, I could calculate methylation frequence by merging multiple methylation calls' result.
    I want to know, does this behavior affect the results?
    Looking forward for your reply.

**Comment by jts** [comment]
That should be fine.

Jared
