### ISSUE TITLE
/bin/bash: nanopolish: command not found

### ISSUE THREAD

**Issue by abayega** [jts/nanopolish#51]
Hi,

when trying to run the nanopolish consensus I get the following message that is printed on the next 34 lines. I need some assistance to resolve this.

/bin/bash: nanopolish: command not found

**Comment by jts** [comment]
Can you paste the command you tried to run?

**Comment by abayega** [comment]
abayega@ubuntu:~/nanopolish$ python nanopolish_makerange.py /home/abayega/Documents/C002_05_4/alignment/assembly/ecoli_denovo.contigs.fasta | parallel --results nanopolish.results -P 2 nanopolish consensus -o nanopolish.{1}.fa -w {1} --r /home/abayega/Documents/C002_05_4/alignment/2Dpass.pp.fa -b /home/abayega/Documents/C002_05_4/alignment/2Dpass.pp.sorted.bam -g /home/abayega/Documents/C002_05_4/alignment/assembly/ecoli_denovo.contigs.fasta -t 2

**Comment by abayega** [comment]
If i run the command from scripts directory or run python scripts/nanopolish_makerange.py ------- that's when I get the /bin/bash: nanopolish: command not found error messages

**Comment by jts** [comment]
You need to change nanopolish in the parallel command to include its full path. For example change:

`python nanopolish_makerange.py [...] | parallel [...] nanopolish [...]`
to:
``python nanopolish_makerange.py [...] | parallel [...] /path/to/nanopolish [...]`

**Comment by abayega** [comment]
Many thanks, I will try later and let you know.

**Comment by abayega** [comment]
Hi, this worked very well. I am completely through and this issue can be closed as well. Many thanks

**Comment by jts** [comment]
Ok, thanks for letting me know.

**Comment by shafijcsmr** [comment]
hi I have run the code 
nanopolish index -d fast5_files/ reads.fasta

but it showed that bash: nanopolish: command not found
