### ISSUE TITLE
Index won't work on fastq that was downsampled for quality and read length

### ISSUE THREAD

**Issue by gwaldbieser** [jts/nanopolish#511]
Following on #228 and #420, I would like to downsample the fastq for quality and read length instead of bulk coverage. Nanopolish (v0.10.2) index runs to completion when I include all fast5 files (in 559 sub-directories), the file of summary file names, and a concatenated file of all fastq reads. 

#!/bin/bash
/home/software/nanopolish/nanopolish index      \
        -d /home/Microbial/kidney/reads/0   \
        -d /home/Microbial/kidney/reads/1   \
        -d /home/Microbial/kidney/reads/10   \
        -d /home/Microbial/kidney/reads/100  \
         ...
         ...
        -d /home/Microbial/kidney/reads/98  \
        -d /home/Microbial/kidney/reads/99  \
        -f /home/Microbial/kidney.SeqFileList_1  Kidney1.all.fastq 1>polish.log 2>&1

However, when I change the script to a fastq file that contains only reads at q10 and 5000bp minimum length, Nanopolish goes through all 559 fast5 sub-directories but reports that no fast5 files were found.

$cat polish.log
[readdb] indexing /home/geoff/Microbial/Sleepy/Sleepy1kidney/reads/0
[readdb] indexing /home/geoff/Microbial/Sleepy/Sleepy1kidney/reads/1
[readdb] indexing /home/geoff/Microbial/Sleepy/Sleepy1kidney/reads/10
[readdb] indexing /home/geoff/Microbial/Sleepy/Sleepy1kidney/reads/100
...
...
[readdb] indexing /home/geoff/Microbial/Sleepy/Sleepy1kidney/reads/98
[readdb] indexing /home/geoff/Microbial/Sleepy/Sleepy1kidney/reads/99
Error: no fast5 files found

Is there a way to do this? Thanks.

**Comment by jts** [comment]
This should work. In the first command (which works) the path is `/home/Microbial/kidney/reads/0` instead of `/home/geoff/Microbial/Sleepy/Sleepy1kidney/reads/0`. Is this a mistake?

**Comment by jts** [comment]
Did the filtering process change the read names as all?

**Comment by gwaldbieser** [comment]
Filtering didn't change the headers, but there were two runs and the fastq headers in the filtered file were from the wrong run. Once corrected, everything worked as it should. PEBKAC error. Sorry for the trouble. Thanks for your help.

**Comment by jts** [comment]
No problem, glad its fixed.
