### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by ranitori** [jts/nanopolish#515]
Hi, I'm a nanopolish newbie. I'm using OSX 10.10.5 on a MacBook Pro. I installed the latest code from github, but when I try to make I get the output below. Any help greatly appreciated. Thanks.

MacTop-IT11905:nanopolish ranitori$ make
if [ ! -e hdf5-1.8.14.tar.gz ]; then \
		version_major_minior=`echo "1.8.14" | sed -E 's/\.[0-9]+$//'`; \
		wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-${version_major_minior}/hdf5-1.8.14/src/hdf5-1.8.14.tar.gz; \
	fi
--2018-12-04 22:25:05--  https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.14/src/hdf5-1.8.14.tar.gz
Resolving support.hdfgroup.org (support.hdfgroup.org)... 50.28.50.143
Connecting to support.hdfgroup.org (support.hdfgroup.org)|50.28.50.143|:443... connected.
ERROR: cannot verify support.hdfgroup.org's certificate, issued by ‘CN=cPanel\\, Inc. Certification Authority,O=cPanel\\, Inc.,L=Houston,ST=TX,C=US’:
  Unable to locally verify the issuer's authority.
To connect to support.hdfgroup.org insecurely, use `--no-check-certificate'.
make: *** [lib/libhdf5.a] Error 5

**Comment by jts** [comment]
That is strange, I don't get that error when I run on linux. To work around it you can run:

```
wget --no-check-certificate https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.14/src/hdf5-1.8.14.tar.gz
```

then continue by running `make`. Alternatively nanopolish is available through conda.

Jared

**Comment by jts** [comment]
Try:

```
wget --no-check-certificate https://bitbucket.org/eigen/eigen/get/3.2.5.tar.bz2
```

then re-run `make` like before.

**Comment by ranitori** [comment]
Hi,
I'm re-trying to install nanopolish again. This time I'm using OSX 10.14.6 Mojave on a MacBook Pro. I installed the latest code from github, but when I try to make it's not working. Please see the attached Terminal log file. Any help is greatly appreciated. Thanks.
[make.log](https://github.com/jts/nanopolish/files/3979862/make.log)
