### ISSUE TITLE
Flappie Basecaller

### ISSUE THREAD

**Issue by giesselmann** [jts/nanopolish#518]
Hey guys,

I get an error when running nanopolish index on sequences basecalled with the new Flappie.
Error:
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551611) > this->size() (which is 1)

The header of the fasta/fastq looks sth. like this:
>d91421cf-6c42-469a-b075-920f0943c5ab  { "filename" : "minION_20170725_FAH14126_MN22308_sequencing_run_U64_88718_read_15443_ch_103_strand.fast5", "uuid" : "d91421cf-6c42-469a-b075-920f0943c5ab", "normalised_score" : 0.650391,  "nblock" : 118995,  "sequence_length" : 18314,  "blocks_per_base" : 6.497488, "nsample" : 238342, "trim" : [ 300, 238290 ] }

It works with albacore basecalling on the same data set, could be an issue with the fastq/fasta parsing.

Great software otherwise!
[0.fa.gz](https://github.com/jts/nanopolish/files/2675644/0.fa.gz)

**Comment by jts** [comment]
Fixed - thanks for providing the test case.
