### ISSUE TITLE
no polishing windows found 

### ISSUE THREAD

**Issue by llz5** [jts/nanopolish#519]
Hi,

I'm having trouble getting nanopolish 0.10.2's vcf2fasta.  It seems that the nanopolish variants step works, producing a .vcf with a reasonable number of variants, but vcf2fasta produces an empty file and throws "error: no polishing windows found for 3001302222_-_PV2_-_Final_Consensus."

It would be reasonable for there not to be any polishing windows because I'm working with a small viral genome, only ~7400 bp, and I didn't set a -w option.  But I've used nanopolish with this very same set of reads before, with very similar commands, and was able to get a phased .sam out of it.

There are two main differences between this attempt and my previous successes:
-I indexed the reads once and then ran nanopolish variants with and without the --fix-homopolymers option simultaneously
-Since nearly all of my reads cover the entire genome, I didn't feel like I'd need to use racon to make a draft genome.  For my successful attempts, I made a draft consensus from the reads assembled to a somewhat-similar virus from GenBank.  For this attempt, I used a consensus sequence for this same viral mixture, created from MiSeq reads.

I've also tried the --skip-checks option for vcf2fasta, with the same results.  I can't see a reason why these changes should make nanopolish expect a polishing window that I haven't defined.  Any thoughts?

For reference, here's the script I ran:
#!/bin/bash -l
#
#$ -pe smp 25
#$ -o BC04pipeline.out
#$ -b n
#$ -e BC04pipeline.err
#$ -N BC04pipeline
#$ -cwd
#$ -q all.q

echo Starting porechop at `date`
	module load porechop/0.2.3
		porechop -i ./fqPass -b porechop --discard_middle
echo Porechop complete at `date`.  Filtering reads by length.
	module unload porechop/0.2.3
	module load prinseq
		prinseq-lite -fastq ./porechop/BC04.fastq -out_format 3 -out_good BC04_long -out_bad null -min_len 7000
echo Reads filtered at `date`.  Start mapping to reference.
	module unload prinseq
	module load minimap2/2.7
		minimap2 -a -x map-ont --no-long-join -t 24 3001302222_MiSeq.fasta BC04_long.fastq > BC04toMiSeq.sam & PIDMINIMAP=$!
echo Starting nanopolish index at `date`.
	module load nanopolish/0.10.2
		nanopolish index -d ./fast5Pass BC04_long.fastq & PIDNANOINDEX=$!
wait $PIDMINIMAP
	module unload minimap2/2.7
echo Indexing started and first mapping complete at `date`.  Converting SAM to BAM.
	module load samtools
	module load tabix
	module load bcftools
		samtools view -S -b BC04toMiSeq.sam > BC04toMiSeq.bam
echo BAM produced at `date`.  Sorting.
		samtools sort -o BC04toMiSeq.sort.bam BC04toMiSeq.bam
echo BAM sorted at `date`.  Indexing.
		samtools index BC04toMiSeq.sort.bam
echo BAM indexed at `date`.  Producing draft consensus.
		samtools mpileup -uf 3001302222_MiSeq.fasta BC04toMiSeq.sort.bam | bcftools call -mv -Oz -o BC04vars.vcf.gz
		tabix BC04vars.vcf.gz
		cat 3001302222_MiSeq.fasta | bcftools consensus BC04vars.vcf.gz > BC04draft.fasta
echo Draft complete at `date`.  Re-aligning reads to draft.
	module unload samtools
	module unload tabix
	module unload bcftools
	module load minimap2/2.7
		minimap2 -a -x map-ont --no-long-join -t 24 BC04draft.fasta BC04_long.fastq > BC04toDraft.sam
echo Aligned to draft at `date`.  Converting to BAM.
	module unload minimap2/2.7
	module load samtools
		samtools view -S -b BC04toDraft.sam > BC04toDraft.bam
echo BAM to draft produced at `date`.  Sorting.
		samtools sort -o BC04toDraft.sort.bam BC04toDraft.bam
echo BAM to draft sorted at `date`.  Indexing.
		samtools index BC04toDraft.sort.bam
echo BAM to draft indexed at `date`.  Waiting for nanopolish index.
	module unload samtools
wait $PIDNANOINDEX
echo Nanopolish index finished by `date`.  Time to polish!
		nanopolish variants --consensus --fix-homopolymers --ploidy 1 -t 13 -o BC04polished_FHP.vcf -r BC04_long.fastq -b BC04toDraft.sort.bam -g BC04draft.fasta & PIDFHP=$!
		nanopolish variants --consensus --ploidy 1 -t 12 -o BC04polished_NoFHP.vcf -r BC04_long.fastq -b BC04toDraft.sort.bam -g BC04draft.fasta & PIDNOFHP=$!
wait $PIDNOFHP
echo NoFHP polishing complete at `date`.  Generating polished consensus.
		nanopolish vcf2fasta -g BC04draft.fasta BC04polished_NoFHP.vcf > BC04polished_NoFHP.fasta
echo NoFHP polished consensus generated at `date`.  Phasing reads.
		nanopolish phase-reads --reads BC04_long.fastq --bam BC04toDraft.sort.bam --genome BC04polished_NoFHP.fasta BC04polished_NoFHP.vcf > BC04phased_NoFHP.sam
echo NoFHP pipeline complete at `date`.  Waiting for FHP polishing.
wait $PIDFHP
echo FHP polishing complete at `date`.  Generating polished consensus.
		nanopolish vcf2fasta -g BC04draft.fasta BC04polished_FHP.vcf > BC04polished_FHP.fasta
echo FHP polished consensus generated at `date`.  Phasing reads.
		nanopolish phase-reads --reads BC04_long.fastq --bam BC04toDraft.sort.bam --genome BC04polished_FHP.fasta BC04polished_FHP.vcf > BC04phased_FHP.sam
echo FHP pipeline complete at `date`.
	module unload nanopolish/0.10.2

**Comment by jts** [comment]
Hi,

vcf2fasta requires nanopolish to run with the `-w` parameter. Since the genome is small in this case, you can just use the entire reference genome as the `-w` parameter (`-w chromosome:1-7400`).

Jared

**Comment by llz5** [comment]
I'm able to get it to work now, but perhaps not as intended?

I added -w <sequenceName>:1-8000 to the nanopolish command, since I wasn't sure of the exact draft length and wanted to see what would happen if I overshot it.  Polishing yielded a reasonable-looking .vcf with "##nanopolish_window=<sequenceName>:1-7429" in the header, but attempting to use vcf2fasta threw:
"error: first 1 bases are not covered by a polished window for contig <sequenceName>.
error: one or more polishing windows are missing. Please check that all nanopolish variants --consensus jobs ran to completion"

I checked the actual length of the draft fasta (7430 bp) and manually changed the line in the .vcf to "##nanopolish_window=<sequenceName>:0-7430."  Vcf2fasta worked with this file.

Do you think a different -w range would avoid this issue?  I'll try 0-8000 overnight tonight and see if that works.

Also, for reference, I looked back at a .vcf produced by polishing without -w, and it did contain a nanopolish_window header, ranging 0-[length-1].  This one worked with vcf2fasta.  Maybe differences in fasta formatting can mess with automatic window setting?

**Comment by llz5** [comment]
Ugh, sorry, I tried to designate a generic sequence name in between > and < signs, and the site must have thought it was a markup tag and ignored it.  So just pretend there's a generic sequence name wherever it makes sense ^^;

I'd go back and edit it, but the editing function doesn't work on IE, which is the only browser on this government box, until my software request goes through.

**Comment by llz5** [comment]
Setting the lower range of the window to 0 worked, so I'll close this.  Thanks for the support, and for an excellent set of tools!
