### ISSUE TITLE
question/request: add #!/usr/bin/env python to /scripts/*py ?

### ISSUE THREAD

**Issue by thsyd** [jts/nanopolish#522]
Hi,
I'm a novice user of linux and bash scripting so I'm sorry if this question has an obvious answer.
I have access to a HPC with nanopolish 0.10.2 installed (the HPC use http://modules.sourceforge.net/).
but even though /nanopolish/scripts/ is added the PATH, running eg
`$ python nanopolish_makerange.py ....`
results in 
`python: can't open file 'nanopolish_makerange.py': [Errno 2] No such file or directory`

I asked the HPC support for help as to why the python scripts arent recocnized by the linux system as the path is added to the environment. The HPC support commented that "!#" was not included in the python scripts.

Is there a reason for not includning
`#!/usr/bin/env python`
at the top of the python scripts in /scripts/ ?
I would have thought this would eliminate the need for invoking "python" before the scipts themselves.

**Comment by jts** [comment]
Hi,

Sure, I can make that change. In the meantime it will work if you provide the full path to the script:

```
python /path/to/nanopolish/scripts/nanopolish
```

Jared
