### ISSUE TITLE
Polya result give fewer reads than expected

### ISSUE THREAD

**Issue by haotianteng** [jts/nanopolish#523]
Hi, I have a question about the new polyA segmentation tool.
The final tsv file has fewer reads than it was given. Here is an example:
`
wc -l merge.fasta
271464 merge.fasta
wc -l merge.fasta.index.readdb
135732 merge.fasta.index.readdb
wc -l polya_results.tsv
65917 polya_results.tsv
`
So which means some of the reads failed in processing, is there a log file indicating the reasons for the failure?

**Comment by paultsw** [comment]
Hi @haotianteng ,

Could you also please report the lines written to stderr after running `nanopolish polya`?

Also, is the `polya_results.tsv` file filtered (e.g. via a `grep 'PASS' polya_results.unfiltered.tsv > polya_results.tsv`)?

Thanks!

**Comment by paultsw** [comment]
Hello @haotianteng,

Did you figure out your issue? I would be happy to look into your problem if you have further details about your dataset as indicated above.

Thanks,

Paul

**Comment by haotianteng** [comment]
Hi Paul,
No worry, the problem is due to a duplication of the readID(somehow strange that they are coming from different fast5 files), we have solved it.
I will close the issue. And the polya segment result is quite good, well done!
Thanks
Teng
