### ISSUE TITLE
Call variants from mitochondrial exome sequencing in minion

### ISSUE THREAD

**Issue by pradyumnasagar** [jts/nanopolish#524]
We are trying to call variants from mitochondrial exome sequencing. 
We are stuck in giving ploidy information for mitochondrial genome. 
Should we give ploidy as 1?

**Comment by jts** [comment]
Hi @pradyumnasagar,

Yes in this case you should give ploidy 1. Right now nanopolish doesn't support calling population variation so you will have to call a discrete genotype and may miss heterogeneity.

Jared
