### ISSUE TITLE
nanopore index too many arguments

### ISSUE THREAD

**Issue by jaworskicoline** [jts/nanopolish#532]
Hello,
I got a zipped file from colleagues containing fast5 nanopore reads. When I unzipped it, it produced many directories, themselves containing several directories, each of them containing a very high number of fast5 files, but apparently no sequencing_summary.txt file.

Following your tuto, if I want to run nanopolish on my genome assembly, I need to pre-process the raw reads, using:
nanopolish index -d nanopore_raw_file_directory reads.fastq

Because of those many directories, I used:
nanopolish index -d ./*/fast5/*/* SRR7167955_1.fastq

However while doing that I get the error:
"index: too many arguments"

Would that be because I call several directories after -d ?
Looking at the help (I'm using /nanopolish index --version 0.10.2), I was wondering if the -f option would help solve my problem, but the help seems to mean to use when referring to the sequencing summary files that I do not have anyway. Would you mind clarifying how to -f and whether this might be an option here ?
Also, the tuto said that trying to pre-process the data without the sequencing summary files would be extremely low, I was wondering how low is extremely low ? 

Thank you very much for your help !

**Comment by jts** [comment]
Hi,

You need to use `-d` before every directory:

```
nanopolish index -d dir1/ -d dir2/ reads.fastq
````

It might be easier if you put all the subdirectories on one directory - nanopolish will search the subdirectories recursively.

The indexing speed depends on your disk storage type. If you don't have the summary just run it over night and it should be finished in the morning.

Jared

**Comment by jaworskicoline** [comment]
Hello,
Thanks for your very fast answer.
Do you mean that if all my subdirectories of subdirectories containing the fast5 are rooted in the same main directory, I should be good by just calling this main directory with -d ?
That is great, I will try that and let you know if it's working.
Also, thank you for information about time constraint, that should not be a problem then.
Thank you very much !

**Comment by jts** [comment]
Yeah, that's right.

Jared
