### ISSUE TITLE
calling SNPs

### ISSUE THREAD

**Issue by lfaino** [jts/nanopolish#534]
Dear Developper,
can you explain to me why the SNP in the left is not called by Nanopolish while the SNP on the right  it is called?
on the top you can see the VCF, the middle is the bam file and the bottom the consensus

Cheers

![image](https://user-images.githubusercontent.com/3789588/51349445-afa0fc80-1aa5-11e9-944c-ce2c807ee373.png)

**Comment by jts** [comment]
Hi Luigi,

Nanopolish uses the signal data to call SNPs, which can sometimes make different calls than what you'd expect by looking at alignments. This appears to be a particularly bad example and I would agree a SNP should have been called at that position. If you can provide me with the reads for this region (we have a guide [here](https://nanopolish.readthedocs.io/en/latest/debug.html) for sending us data) I'd be happy to take a look to see if anything unexpected is happening.

Jared
