### ISSUE TITLE
nanopolish variant --consensus results

### ISSUE THREAD

**Issue by jaworskicoline** [jts/nanopolish#536]
Hello,
I have tried to have nanopolish variant --consensus working on my assembly to polish it; now I'm able to run it without crashing, however i'm not sure the output is as expected, I find it a bit weird:
I am using nanopolish --version  0.10.2n and parallel/2017....

I have run the following command:
python ~/Programs/nanopolish/scripts/nanopolish_makerange.py ../Canu45/CATn_PB_Only.contigs.fasta | parallel --results ./nanopolish.results -P 7 \
  ~/Programs/nanopolish/nanopolish variants --consensus -o polished.{1}.vcf -w {1} -r /path-to-raw-reads/Nano-reads.fastq -b ./Aligned_reads/reads.sorted.bam -g ../Canu45/CATn_PB_Only.contigs.fasta -t 4 --min-candidate-frequency 0.2

with the reads.sorted.bam obtained by running bwa as described in the tutorial.

The output is:
- a bunch of folders in ./nanopolish-results/1/
- a bunch of .vcf files in the working directory
- the stdout says:
[fai_load] build FASTA index.
[post-run summary] total reads: 405, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 404
[fai_load] build FASTA index.
[post-run summary] total reads: 459, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 455
[fai_load] build FASTA index.
[post-run summary] total reads: 477, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 472
[fai_load] build FASTA index.
[post-run summary] total reads: 472, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 471
[fai_load] build FASTA index.
[post-run summary] total reads: 455, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 453
..............continued

The .vcf files say:  $ more polished.tig00000004\:0-50200.vcf 
##fileformat=VCFv4.2
##nanopolish_window=tig00000004:0-50200
##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">
##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">
##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">
##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">
##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample

Therefore, it looks to me that the .vcf files are empty, and I do not understand what the stdout would mean with "bad fast5", as if it would not be able to read bad fast5 ? should the raw reads passed to -r in nanopolish variant be the fast5 files ? If so, would you mind show me how to write the path since they are in multiple directories ?

The draft assembly has been obtained by passing the raw nanopolish in fastq format to Canu.
Thank you very much for your help !

**Comment by jts** [comment]
Is this very recent data, with multiple reads per fast5 file? Or is it
one-read-per-fast5?

Jared

**Comment by jaworskicoline** [comment]
I do not know how to check if multiple reads in fast5 files. Apparently sequenced in 2017 and there is ~3million reads in the fastq.
Are we supposed to call the reads in fast5 format after the nanopolish index step ?

**Comment by jts** [comment]
It appears nanopolish is rejecting your fast5 files for some reason. Do you know what version of the sequencing kit was used?

Sorry for the long delay in responding.

**Comment by jaworskicoline** [comment]
Hello,
I got it to work after a while, the reason was that the fastq was not exactly the same as the reads in the fast5 for some reasons. Therefore, I had to re-basecall with albacore, then index with nanoindex, and finally had nanopolish work after alignment with BWA.

**Comment by jts** [comment]
Great, thanks for letting me know.

Jared
