### ISSUE TITLE
[fai_fetch_seq] The sequence "" not found

### ISSUE THREAD

**Issue by kehey** [jts/nanopolish#54]
When running the consensus step, after running the consensus.make, I get an error not finding the sequence, but the sequence ID is not filled out.

The fofn file points to the correct file paths etc., so I'm wondering whether this could be an error in nanopolish itself. 

I cloned master two hours so using this commit version:

commit 194cc3faafd90d0626318d26ee5be0aaa48926dd
Author: Jared Simpson <jared.simpson@gmail.com>
Date:   Sat Mar 26 12:49:28 2016 -0400

    add read index to site output

**Comment by jts** [comment]
Can you send the full command you ran?

**Comment by kehey** [comment]
Thanks. Commands were:

```
make -f consensus.make \
       READS=Download_Pass.fa \
       ASSEMBLY=canu_PacBio_assemble.contigs.fasta
```
This gave me the BAM file, the pp.fa, and the index on the assembly fasta, which all look fine. Next step was

```
nanopolish consensus \
                    --verbose \
                    -o canu_PacBio_assemble.contigs.polish.fa \
                    -r Download_Pass.pp.fa \
                    -b Download_Pass.pp.sorted.bam \
                    -g canu_PacBio_assemble.contigs.fasta
```

**Comment by jts** [comment]
The consensus step takes quite a long time so it is designed to be run in parallel over segments of the genome. The `-w` parameter is mandatory - I'll update the code to gracefully exit if its not provided. Have a look at the README in the top level directory for instructions to run it.

**Comment by kehey** [comment]
Okay, my mistake. I read the instructions, but since this a BAC sequence of only 127kb, and the example runs it on 100kbp windows, I figured I did not need to run it in parallell.

Any recommendations on what to set w on in this case?

**Comment by jts** [comment]
it is best if you just use the driving script shown in the README. I'm planning some improvements to make this much easier and faster but these won't come until after nanopolish fully supports R9 data.

**Comment by jts** [comment]
commit dfb404975a7 provides a better error message in this case

**Comment by kehey** [comment]
Running smoothly now. Thanks for the very quick help!

**Comment by jts** [comment]
great, let me know if there are other issues
