### ISSUE TITLE
High proportion of "could not calibrate" reads?

### ISSUE THREAD

**Issue by kautto** [jts/nanopolish#540]
Hi @jts,

I'm trying to figure out what's giving me a high proportion of "could not calibrate" reads when trying to call methylation. 

For example, using Guppy-generated reads trimmed with Porechop (to get rid of adapters) and discarding the ones containing middle adapters (--discard_middle), I get something like:

```
[post-run summary] total reads: 637, unparseable: 0, qc fail: 0, could not calibrate: 401, no alignment: 4, bad fast5: 0
```

Using the same reads straight from Guppy (i.e. no Porechop) gives somewhat different results:
```
[post-run summary] total reads: 660, unparseable: 0, qc fail: 0, could not calibrate: 199, no alignment: 4, bad fast5: 0
```

Either way the are a lot of reads that did not calibrate, but it seems to be twice as bad of an issue with the Porechopped reads for whatever reason. What causes the calibration issue? I guess I don't know what "calibration" it's actually referring to.

**Comment by jts** [comment]
Hi @kautto,

Each read that goes through the pore varies a little in its current profile. The calibration step corrects for these subtle variances. If we can't find calibration values that give a good fit to the expected signal, we discard the read.

Can you describe the data you've generated? Is it MinION or PromethION? genomic dna? what sequencing kit? Any info you have might be helpful.

Thanks
Jared

**Comment by kautto** [comment]
Hi Jared,

it's on a MinION, using FLO-MIN106D and SQK-LSK109. The sample is native DNA (not amplified), but the DNA of the sample is pretty chewed up and degraded. The bulk of the reads are short (only a few hundred bp). 

Looking at some of the other samples I ran recently, using the non-trimmed (i.e. didn't go through Porechop) reads always results in less reads failing calibration. Although with the higher-quality samples, I lose way less reads to that. 

Given the limitations of some of our samples, I can't improve the library to get longer reads, although my intuition tells me that the shortness is probably contributing to the problem. I'm guessing keeping the adapter sequences on gives the calibration step more to work with, which could explain why I lose less of the untrimmed than trimmed reads?

Thanks,
Esko

**Comment by jts** [comment]
Hi Esko,

Thanks for providing details about the experiment. I strongly suspect the root cause is the short read length. The calibration step relies on having many "events" in the signal data to be able to accurately estimate the scaling factors. With short reads, this may not work well. As you suspected, this is probably why keeping the adapters worked slightly better.

Jared
