### ISSUE TITLE
variants --consensus is too slow

### ISSUE THREAD

**Issue by valery-shap** [jts/nanopolish#541]
Hello,

I have about 100.000 reads from Nanopore and 4.6 Mbp genome. Also i have 24 threads.
After Canu assambly, minimap2 alignment with -L flag, samtools I have sorted(indexed) bam file and not polished genome. 
I run the command:
sudo python /nanopolish/scripts/nanopolish_makerange.py not-polished-genome.fa | parallel --results dir-nanopolish-res -P 8 \
./nanopolish variants --consensus -o new.{1}.vcf -w {1} --ploidy 1 --reads file.fastq --bam sorted.bam --genome  not-polished-genome.fa -t 3 --min-candidate-frequency 0.1
When using programs that use GNU Parallel to process data for publication please cite:
*information about citation*
Number of variants in span(14) would exceed max-haplotypes. Variants may be missed.  Consider running with a higher value of max-haplotypes!
A lot of such messages
[post-run summamry] total reads: 1289, uparsiable: 0, qc fail: 1, could not calibrate: 0, no alignment: 11, bad fast5: 0
And two or three messages about post-run
It is going for a night and all morning.
Is it normal or am i doing smth wrong?
Before i tried it only for variants with reference genome and it takes from thursday to... in the morning of Monday i had a lot of not empty vcf files.

**Comment by jts** [comment]
Hi,

There are few reasons why nanopolish might be slower than expected:

1) Excessive sequencing coverage (you don't need more than 100-200x to polish)
2) Excessive number of candidate variants

For the first issue, you can try downsampling the data. For the second issue, you can remove the `--min-candidate-frequency 0.1` option and use the default.

Jared

**Comment by jts** [comment]
`samtools view -s` can be used to subsample a BAM file to lower its coverage

**Comment by valery-shap** [comment]
Seems that it helps a bit.
A lot of thanks.

**Comment by valery-shap** [comment]
Hello,
Sorry, should I give a half of --reads too?
I made view -s 0.5 with bam file and didn't change the reads. I don't know what reads to delete.

**Comment by jts** [comment]
No, you don't need to change the `--read`. It will only use reads that have alignments in the downsampled BAM.

Jared

**Comment by valery-shap** [comment]
I began this 07.02 and it is still counting...
I count [post-run summary] total reads and the number is 55 859 reads. Is it normal time for this task? 
Does it show in post run summary reads from bam file?
In --reads I have 111111, in bam file I expected (view -s 0.5), so 55555 reads. I didn't check the number of reads after view -s 0.5.

**Comment by valery-shap** [comment]
Maybe I can pause the process and then restart?

**Comment by jts** [comment]
No, you can't pause and restart sorry. 

I'm not sure I understood your message from 2 days ago, can you clarify what you're asking?

**Comment by valery-shap** [comment]
Sorry if my question confused you.
I'd like to polish my genome(4.6 Mbp, 50.000 reads) and it seems to me that if this polishing goes more then a week, I'm doing smth wrong. Am I right? I try to find the reason of this extra slow working.
I need to use my computer and couldn't wait one more week( and now I'm not sure that one more week or two helps me.

**Comment by jts** [comment]
One week seems a bit slow. The command from your first post says you are running 8 polishing tasks in parallel, each that uses 3 threads. Does your computer have 24 cores? If not it might be slow because your computer is overloaded.

**Comment by valery-shap** [comment]
Thank you for the answer.
I checked settings of my virtual machine and it has 24 threads as max. But I can't do smth more on it now. 
Could you please explain me what reads are displayed in post-run message: reads from --reads (111.111) or reads from bam file (I checked - 59522)? I try to count time for finish.

**Comment by jts** [comment]
If you count the number of VCF files that it has produced, it is a good measure of how far along it is. Each VCF is a 50kb segment of the genome, and your genome is 4.6MBp, so you should have about 90 of them when it is done.

**Comment by valery-shap** [comment]
Finish!
so it takes 12 days to polish. Unfortunately,I didn't find the reason of such slow working.
I'll be very pleased if you comment some tips from the result.
I have some messages like: 
Warning: 4607 variants in span, region not called [4608943 4610878]
Warning: 4310 variants in span, region not called [4610830 4612698]

Why could it be so? what will be there in my polished genome?
After vcf2fasta i have such message:
[vcf2fasta] rewrote contig  with 3925 subs, 31630 ins, 1323 dels (1 skipped)

Does it mean that one deletion is missed? Could i know where it is? Is it because warnings with variants?

A lot of thanks,
Valery

1 skipped

**Comment by jts** [comment]
Those warnings give us a hint about why your run might be slow. It appears the draft assembly had many more errors than expected, so nanopolish had a lot more work to do. What assembler did you use to make the draft assembly?

**Comment by valery-shap** [comment]
Canu with all steps and default settings.
I have another one from miniasm, but suppose that it is worse then canu. And after miniasm I used racon.
Maybe I try to use nanopolish after miniasm.
I have not so much these messages, less then 50.

**Comment by jts** [comment]
Nanopolish will not work with a miniasm assembly, you need to run racon at least once first before polishing.

**Comment by valery-shap** [comment]
Thank you very much for helping me.
