### ISSUE TITLE
Index cannot read summary file

### ISSUE THREAD

**Issue by GeneDesign** [jts/nanopolish#542]
The only file I can find that is named sequencing_summary.txt apparently has extra columns in it. I didn't think I was using a divergent basecaller. 
When I run 
```
nanopolish index -d /path/to/fast5 /path/to/reads.fastq -s /path/to/sequencing_summary.txt
```
I get the error
```
Could not find filename column in the header of /path/to/sequencing_summary.txt
```
When I head the summary file I get
```
filename_fastq	filename_fast5	read_id	run_id	channel	mux	start_time	duration	num_events	passes_filtering	template_start	num_events_template	template_duration	sequence_length_template	mean_qscore_template	strand_score_template	median_template	mad_template
FAK49574_7be2165c8cedec87aa043f70468f13d7e6d5eaa0_0.fastq	FAK49574_7be2165c8cedec87aa043f70468f13d7e6d5eaa0_0.fast5	cd56ef54-c5f7-4b1b-8372-329b3c314600	7be2165c8cedec87aa043f70468f13d7e6d5eaa0	120	1	9.068750	0.639000	0	TRUE	9.233750	0	0.474000	187	10.386013	-0.000010	77.281677	9.903374
FAK49574_7be2165c8cedec87aa043f70468f13d7e6d5eaa0_0.fastq	FAK49574_7be2165c8cedec87aa043f70468f13d7e6d5eaa0_0.fast5	24246891-31f8-4e9f-9fff-8f6f28c805a7	7be2165c8cedec87aa043f70468f13d7e6d5eaa0	433	1	9.194000	0.616000	0	TRUE	9.272750	0	0.537250	246	7.615546	-0.000012	82.763901	10.433907
```

So close, but apparently not the right file?

**Comment by jts** [comment]
What basecaller and version did you use?

**Comment by GeneDesign** [comment]
I apologize, I am trying to figure out how to figure that out. Can you point me to how to determine that? I just ran MinKnow with the default settings

**Comment by jts** [comment]
Ah, you used the basecaller built-in to MinKNOW then. Can you tell me which
version of MinKNOW you used?

**Comment by GeneDesign** [comment]
I believe it is release 18.12.6

**Comment by jts** [comment]
Also, based on that output file it looks like you have the version that makes multi-read fast5 files. If you just drop the `-s` option nanopolish index should work fine.

**Comment by GeneDesign** [comment]
It does it's just very very slow - I guess what you're saying is it as fast as it's going to be already without the summary?

**Comment by jts** [comment]
Hm, I thought multi-fast5 indexing was fast enough without the summary. Right now its your only option though until I figure out what is going on.

**Comment by GeneDesign** [comment]
It is entirely possible my standard for fast is warped. In any event it does work without the summary file, so I am not bottlenecked by anything but time.

I am satisfied with the current answer and appreciate your help. Please don't hesitate to ask me for whatever data you need if you choose to pursue this.

**Comment by marcotoffoli** [comment]
Hello, I am also running nanopolish index on fastq files basecalled with Guppy. I tried running it with the -s option but it doesn't work and without it it's taking ages (7-10 days).
Is there any way to improve this?

**Comment by jts** [comment]
Did you get the same error message as above? I will try to fix it this week.

Jared

**Comment by marcotoffoli** [comment]
Hi Jared, if I use the -s option I get something like
[readdb] num reads: 4339, num reads with path to fast5: 1
repeated for each barcode.
Thank  you for your help, your software is amazing!

**Comment by jts** [comment]
Hm, can you post the start of the summary file? Are you using nanopolish 0.11?

**Comment by marcotoffoli** [comment]
I'm using nanopolish 0.11. 

The start of the summary file looks like this:
`filename	read_id	run_id	channel	start_time	duration	num_events	passes_filtering	template_start	num_events_template	template_duration	sequence_length_template	mean_qscore_template	strand_score_template	median_template	mad_template`

Also, to add some more info, I used barcodes, so after basecalling with Guppy I also demultiplexed with Guppy. I am referring to the summary file that is in the folder created after basecalling. There is another summary file inside the folder created after demultiplexing, but this second file is completely different and doesn't work with the -s option of Nanopolish.

Marco

**Comment by jts** [comment]
Ok, thanks for the info. I haven't looked at guppy debarcoded data so it might be that. If possible could you send me a fast5 file and corresponding fastqs?

**Comment by marcotoffoli** [comment]
Dear Jared,

I don’t have access to my fast5 now. I will send the files to you first think in the morning tomorrow.

All best,
Dr Marco Toffoli | Clinical Research Fellow
Department of Clinical and Movement Neurosciences | UCL Queen Square Institute of Neurology

e: m.toffoli@ucl.ac.uk<mailto:s.rahall@ucl.ac.uk>
t: 02077940500 (ext: 31588)


Da: Jared Simpson <notifications@github.com>
Risposta: jts/nanopolish <reply@reply.github.com>
Data: lunedì 18 febbraio 2019 18:58
A: jts/nanopolish <nanopolish@noreply.github.com>
Cc: "Toffoli, Marco" <m.toffoli@ucl.ac.uk>, Comment <comment@noreply.github.com>
Oggetto: Re: [jts/nanopolish] Index cannot read summary file (#542)


Ok, thanks for the info. I haven't looked at guppy debarcoded data so it might be that. If possible could you send me a fast5 file and corresponding fastqs?

**Comment by marcotoffoli** [comment]
Hi Jared, 
Do you have a preferred way o send my files?
They're just over 10MB so can't post them here.
Marco

**Comment by jts** [comment]
Dropbox or google drive would be great

**Comment by marcotoffoli** [comment]
Here it is. 

https://drive.google.com/open?id=1Hu0ZnTWm4E1WgUiYGsrKiVzDrHibXB67

fast5 folder contains some of the fast5 files obtained with MinKnow.
fastq folder contains fastq files from fast5 above, created with Guppy v2.3.1
fastqdebarcoded contains fastq demultiplexed from fastq above, created with Guppy v.2.3.1.

Let me know if you need more info!

**Comment by jts** [comment]
@marcotoffoli which sequencing summary did you use when trying to index the barcoded data? Can you provide the command that you tried to run, that failed?

**Comment by jts** [comment]
Looked into this a bit - I don't think the `-s` option is working correctly with multi-fast5 files. For now you'll have to run `nanopolish index` without `-s` and just wait. I'll try to fix it soon.

**Comment by marcotoffoli** [comment]
I used the sequencing summary created by Guppy after basecalling (the one inside the folder called fastq in the example I posted previously). 

Indeed, without the -s option nanopolish works, it just takes more than a week to index all the files. I'm basecalling again with Albacore now, and will run nanopolish afterwards.

Looking forward to using nanopolish and guppy in the same pipeline in the future!

**Comment by jts** [comment]
Hi,

I have fixed the multi-fast5 summary file parsing in 8b5e605. Let me know how it looks.

Jared

**Comment by kirstyn** [comment]
I have also been having this problem and tried the new commit but get "Error: no fast5 files found"

**Comment by jts** [comment]
Hi,

Can you post the command you tried?

**Comment by kirstyn** [comment]
nanopolish index -d /var/lib/MinKNOW/data/200219_unitid_run1 unitid_latest_all.fastq

**Comment by jts** [comment]
Can you paste all the messages printed to the terminal when you run that command?

**Comment by jts** [comment]
@kirstyn I'm going to close this issue since it isn't related to the multi-fast5 summary files. Please open a new issue if this is still a problem.

**Comment by gwaldbieser** [comment]
I'm having this problem as well after using qcat to demultiplex the fastq files. 
"Could not find filename column in the header of (sequencing_summary.txt)

The fastq header line is in field 3 instead of field 1 of the sequencing summary file.
