### ISSUE TITLE
New to nanopolish

### ISSUE THREAD

**Issue by Genereneg** [jts/nanopolish#543]
Howdy all,

Checking out nanopolish. Following along with the documentation (0.8.4) and https://nanopolish.readthedocs.io/en/stable/quickstart_consensus.html, and having an issue.

At the checkpoint (chapter 2.5), I'm left with no "reads.sorted.bam" file.

From untaring,

$ ls -lth
total 5.4M
drwxrwxr-x. 2 user user  16K Feb 11 21:24 fast5_files
-rw-rw----. 1 user user 1.5K Nov 17  2017 ecoli_2kb_region.log
-rw-rw----. 1 user user 608K Nov 17  2017 reads.fasta
-rw-rw----. 1 user user 292K Nov 17  2017 reads.bam
-rw-rw----. 1 user user  232 Nov 17  2017 reads.bam.bai
-rw-rw----. 1 user user  101 Sep 15  2017 draft.fa.fai
-rw-rw----. 1 user user 4.5M Sep 15  2017 draft.fa

$ ~/minimap2-2.15_x64-linux/minimap2 -ax map-ont -t 8 draft.fa reads.fasta | samtools sort -o reads.sorted.bam -T reads.tmp
sort: invalid option -- 'T'
open: No such file or directory
[bam_sort_core] fail to open file reads.sorted.bam
[M::mm_idx_gen::0.135*1.01] collected minimizers
[M::mm_idx_gen::0.158*1.75] sorted minimizers
[M::main::0.158*1.75] loaded/built the index for 3 target sequence(s)
[M::mm_mapopt_update::0.169*1.70] mid_occ = 11
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 3
[M::mm_idx_stat::0.179*1.66] distinct minimizers: 833470 (98.00% are singletons); average occurrences: 1.035; average spacing: 5.355
[user@cluster ecoli_2kb_region]$ samtools sort

Usage:   samtools sort [options] <in.bam> <out.prefix>

Options: -n        sort by read name
         -f        use <out.prefix> as full file name instead of prefix
         -o        final output to stdout
         -l INT    compression level, from 0 to 9 [-1]
         -@ INT    number of sorting and compression threads [1]
         -m INT    max memory per thread; suffix K/M/G recognized [768M]

$ samtools

Program: samtools (Tools for alignments in the SAM format)
Version: 0.1.19-44428cd

Not sure where to go from here..

**Comment by jts** [comment]
Hi,

Your version of samtools is quite old, can you try again with a more recent
version?

Thanks,
Jared

**Comment by Genereneg** [comment]
Stuck with the one on the one cluster for now. Trying on another..
