### ISSUE TITLE
Nanopolish citation

### ISSUE THREAD

**Issue by joanmarticarreras** [jts/nanopolish#544]
Dear @jts ,

We would like to cite your tool in our following paper, but we failed to find a previous reference or a recomended citation at the manual or `--help / --version` of nanopolish.

Any guidelines or suggestions of how this tools should be cited?

Thank you very much!

Joan

**Comment by jts** [comment]
Hi Joan,

You can cite this paper: https://www.nature.com/articles/nmeth.3444

Thanks,
Jared

**Comment by joanmarticarreras** [comment]
Thanks Jared
