### ISSUE TITLE
less indels with new nanopolish

### ISSUE THREAD

**Issue by marcotoffoli** [jts/nanopolish#546]
Hi, 
I have just finished processing sequencing data obtained with MinION and noticed something. 
In the past Nanopolish was giving me a lot of indels, that I just ignored. This last time though, no indel i reported in any of the vcf files. 

My question is: is the new version of Nanopolish better at discriminating true and false indels or is it just ignoring ALL indels?
I have a sample from an old run who is a known carrier of a duplication and could re-analyse the fast5 to check if the insertion is picked up, if needed.

The pipeline I'm using is: Minknow --> Albacore --> NGMLR --> Nanopolish
I'm using barcoded samples to sequence the GBA gene in 96 patients per batch

**Comment by jts** [comment]
Hi,

The core algorithm has not changed recently so I'm not sure what this could be. What command line options are you using?

Jared

**Comment by marcotoffoli** [comment]
Hi Jared, 

Here are the commands I'm using:

`for f in /path/to/merged/*.fastq; do nanopolish index -d /path/to/fast5 $f; done`

and

`cd /path/to/mergedfastq/folder && for f in *.fastq; do  nanopolish variants -g /path/to/human_hg19_mod.fa -r $f -b /path/to/sortedbam/sorted.${f}.bam --ploidy 2 -w "1:155,202,239-155,216,653" -o /path/to/whereyouwantpolishedfiles/${f}.vcf --snps --fix-homopolymers; done`

Could be the new MinKNOW software gives better results?

**Comment by jts** [comment]
In older versions of nanopolish the `--snps` option was misleading and it would still output indels. I fixed this in more recent versions. If you remove `--snps` you should get indels in the output.

Jared

**Comment by marcotoffoli** [comment]
I see, thank you for the clarification!
