### ISSUE TITLE
Unable to calculate methylation with new multi-fast5

### ISSUE THREAD

**Issue by ib361** [jts/nanopolish#547]
Hello,
I am having trouble calculating the methylation of my samples using Nanopolish  **v 0.11.0**, which it has worked perfectly fine until I upgraded Nanopolish and I upgraded to guppy base caller when Nanopore outputs changed to **multi-fast5**.

I usually first basecall and demultiplex the new multi-fast5 files using guppy **v 2.3.1+9514fbc**. I then filter the fastq files using NanoFilt v 2.2.0.

 At this point I follow the instructions I found on (https://nanopolish.readthedocs.io/en/latest/quickstart_call_methylation.html): 

```
nanopolish index -d <path_to_multifast5_dir> <path_to_filtered_fastq> -s <path_to_guppy_summary_file>

minimap2 -a -x map-int <reference_genome> <path_to_filtered_fastq> | samtools sort -T tmp -o <path_to_output_bam_file>

samtools index <path_to_output_bam_file>

nanopolish call-methylation -t 8 -r <path_to_filtered_fastq> -b <path_to_output_bam_file> -g <reference_genome> > _methylation_calls.tsv

/nanopolish/nanopolish-0.11.0/scripts/calculate_methylation_frequency.py -i _methylation_calls.tsv > _methylation_frequency.tsv
```

However, this returns an incomplete output. A representative example of my Nanopolish log is the following:

Nanopolish indexing (**here you see that I get indexes only for 7 reads out of 24175**): 

```
[readdb] indexing ./fast5
[readdb] num reads: 24175, num reads with path to fast5: 7
```
Minimap2 alignment:
```
[M::mm_idx_gen::83.829*1.70] collected minimizers
[M::mm_idx_gen::104.091*1.94] sorted minimizers
[M::main::104.092*1.94] loaded/built the index for 194 target sequence(s)
[M::mm_mapopt_update::108.162*1.90] mid_occ = 705
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 194
[M::mm_idx_stat::109.917*1.89] distinct minimizers: 100159079 (38.79% are singletons); average occurrences: 5.540; average spacing: 5.586
[M::worker_pipeline::188.219*2.29] mapped 24175 sequences
[M::main] Version: 2.10-r761
[M::main] CMD: minimap2 -a -x map-ont /data/genomics_f/ib361/nanopore_data/genomes/Homo_sapiens.GRCh38.dna.primary_assembly.fasta ./guppy_test_multifastresults/filtering_results/barcode06_filtered.fastq.gz
[M::main] Real time: 188.718 sec; CPU: 431.319 sec
```
Nanopolish call-methylation (**all fast5 classified as bad**):
```
[post-run summary] total reads: 26033, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 26499
```
This usually outputs incomplete methylation_calls/methylation_frequency files, where only few chromosomes are calculated.

Any idea on how to solve this?

Many thanks
Iacopo

**Comment by jts** [comment]
Hi, 

There was a problem with the -s option for multi-fast5s. See the discussion here: https://github.com/jts/nanopolish/issues/542

The latest commit (one hour ago) fixes this, can you try it? You'll need to re-run index.

Jared

**Comment by ib361** [comment]
Hi Jared,
Thanks for your reply. I now ran again the analysis after updating Nanopolish and everything works fine!

Best
Iacopo

**Comment by suyanan** [comment]
Hi ib361 and Jared, 
now I got the same problem, how did you fix or solve it?
use the Nanopolish version v0.11.0 and remove the -s paras while nanopolish index?
And the consuming time is proper , nearly few hours?

I have process the summary with proper head, and each fast5 has 4000 reads(multi-fast5).
BEST
Sue

**Comment by ib361** [comment]
Hi Sue,
Jared solved this issue after an update of the v0.11.0 of Nanopolish. After that I was able to run the commands I wrote above without problems (including keeping the -s option), using multi-fast5 files.

Best
Iacopo

**Comment by suyanan** [comment]
Hi lacopo,
nanopoish v0.11.0 's release version was on Jan 18.
So, in your experience, I can use the vesrion 0.11.1, which will not casue the above problem?

v0.11.1 released on Mar 27.

Best
Sue

**Comment by ib361** [comment]
I am using v0.11.0, updated after Feb 22. If you check Jared's comment above and the commits it was on that date that the problem with the parsing of the summary file was fixed. 
I am assuming that if you use v0.11.1 will work as well since it was released after that problem was solved.

Best
Iacopo

**Comment by suyanan** [comment]
Fine, thanks a lot.

Best
Sue

**Comment by suyanan** [comment]
Hi,
v0.11.0 and v.0.11.1, there are some changes , would these changes can influence the methylation's results?
OR, the changes are just meant to use the input data, like multi-fast5 or summary?

Best 
Sue

**Comment by jts** [comment]
The changes between those versions should not change methylation calling
results.

Jared
