### ISSUE TITLE
how to decide a kmer model

### ISSUE THREAD

**Issue by olivomao** [jts/nanopolish#548]
Hi,

We're playing with the RNA reads of "cDNA Pass 12 15152101 1030.24 1072" at this page (https://github.com/nanopore-wgs-consortium/NA12878/blob/master/RNA.md).

I wonder if you know what can be a proper kmer model used (from https://github.com/jts/nanopolish/tree/master/etc/r9-models) for this dataset?

Usually how can we decide a proper kmer-model for a nanopore dataset?

Thanks!

**Comment by jts** [comment]
What are you trying to do with the data? In general you don't need to choose the k-mer model, nanopolish will choose based on metadata in the fast5 file.

Jared

**Comment by olivomao** [comment]
Hi Jared,

We try to do some analysis similar as the nanopolish eventalign, and need to convert reads back to current levels (instead of using original current file in fast5).

Just wonder if you know what can be a proper kmer model? Or if you can point us to how we could check this from the metadata in fast5 file? 

Thanks a lot!

**Comment by jts** [comment]
The main things we check are the pore version and molecule type. For the cDNA data from above you'll want r9.4_450bps.nucleotide.6mer.template.model since it is DNA going through the R9.4 pore.

Jared

**Comment by olivomao** [comment]
I see. Thanks!
