### ISSUE TITLE
Pulled most recent version, nanopolish --version returns 10.1

### ISSUE THREAD

**Issue by conchoecia** [jts/nanopolish#551]
Like the title says, I pulled the most recent version of `nanopolish` yesterday and executed `nanopolish --version` and it returned 10.1. Shouldn't it be 11.0?

Also, I tried the 11.0 release on ubuntu 16 with gcc 7.3.0 and it looks like there are some bad `-I` flags or something because the compiler isn't finding the `fast5.h` headers. The line that threw an error was:

```
g++ -o src/main/nanopolish.o -c -g -O3 -std=c++11 -fopenmp -fsigned-char -D_FILE_OFFSET_BITS=64  -I./include -I./htslib -I./fast5/include -I./src -I./src/hmm -I./src/thirdparty -I./src/thirdparty/scrappie -I./src/common -I./src/alignment -I./src/pore_model -I./eigen/ -fPIC src/main/nanopolish.cpp
In file included from src/main/nanopolish.cpp:13:0:
./src/nanopolish_extract.h:12:10: fatal error: fast5.hpp: No such file or directory
 #include <fast5.hpp>
          ^~~~~~~~~~~
compilation terminated.
Makefile:134: recipe for target 'src/main/nanopolish.o' failed
make: *** [src/main/nanopolish.o] Error 1
```

**Comment by jts** [comment]
The version number in the code looks correct so I'm not sure what the problem is: https://github.com/jts/nanopolish/blob/master/src/common/nanopolish_common.h#L21 

For the second problem did you forget the `--recursive` flag to `git clone`?

**Comment by conchoecia** [comment]
My mistake, sorry! My ENV was pointing to another install. Thanks for your time.
