### ISSUE TITLE
Variant not present in bam file

### ISSUE THREAD

**Issue by marctormo** [jts/nanopolish#554]
Hello,

After running "nanopolish variants", it appears a variant in the VCF file that I can't find in the BAM file:
19	28463587	.	T	A	60.8	PASS	TotalReads=6;AlleleCount=1;SupportFraction=0.500219	GT	0/1

When I check both files at the position with IGV, I see:
![igv_snapshot](https://user-images.githubusercontent.com/40198266/53739191-7247d100-3e91-11e9-9e75-54131be6ac4c.png)

Could you please tell me if I'm doing something wrong?

Thank you very much

**Comment by jts** [comment]
Hi,

Nanopolish uses the signal data to make calls, so it does not rely on the basecalled reads. Calling a variant that has no evidence in the basecalled reads is rare, but not unexpected. I think 6x coverage is too low to reliably call variants anyway, so you should probably ignore calls in this region.

Jared

**Comment by marctormo** [comment]
Thank you Jared,

Which would be the lowest coverage to obtain a reliable variant calling, in your opinion?

Marc

**Comment by jts** [comment]
At least 30x, more would be better.

**Comment by marctormo** [comment]
Thanks Jared!
