### ISSUE TITLE
what are the major factors determining polya estimation

### ISSUE THREAD

**Issue by Huanle** [jts/nanopolish#555]
There are some variances among the estimated polya length.
I wonder what are the major factors that could affect the results?
Will these factors affect reads quality and thus reads mapping as well?

Thanks.

**Comment by jts** [comment]
We believe the major factor is the variation in the speed the RNA molecule goes through the pore. I don't know well the basecaller tolerates variation in speed so I can't answer the second part of the question.

I hope this helps!

**Comment by Huanle** [comment]
@jts thanks very much.
