### ISSUE TITLE
Shippable CI for ARM test cases

### ISSUE THREAD

**Issue by junaruga** [jts/nanopolish#556]
Travis ARM 64-bit, 32-bit cases take long time 39 ~ 43 minutes.
https://travis-ci.org/jts/nanopolish

I assumed that the reason might be because the ARM container is run on QEMU on Travis CI x86_64 host OS.

I ran Shippable CI providing an ARM native environment.
https://github.com/junaruga/nanopolish/blob/feature/shippable-ci/shippable.yml

The result is like this.
![shippable-2019 03 16](https://user-images.githubusercontent.com/121989/54482552-a209b800-4845-11e9-8fcb-e4431f588569.png)
https://app.shippable.com/github/junaruga/nanopolish/runs/57/summary/console

* ARM 64-bit with hd5f built from the source: 51 minutes
* ARM 64-bit with pre-built system hdf5: 15 minutes
* ARM 32-bit with hd5f built from the source: 27 minutes
* ARM 32-bit with pre-built system hdf5: 6 minutes

It looks faster than Travis CI.

**Comment by junaruga** [comment]
Total 17 minutes on ARM-64 bit test case!
https://app.shippable.com/github/junaruga/nanopolish/runs/54/1/console

**Comment by jts** [comment]
Perhaps we can switch the ARM CI to this? https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support

**Comment by junaruga** [comment]
Yeah, good idea! Maybe it is much faster than current one with QEMU.
It looks only for ARM 64-bit (aarch64).

I also proposed Drone CI supporting both ARM 64 and 32-bit to Ruby project, as a co-incidence.
https://bugs.ruby-lang.org/issues/16234
https://github.com/ruby/ruby/pull/2520

**Comment by jts** [comment]
@junaruga after much trial and error I have arm64 travis-ci working in this branch:

https://github.com/jts/nanopolish/tree/travis_update

Can you take a look and see if it fits your purpose? I need to use the system libhdf5 and it is installed by apt into an unexpected place (`/usr/lib/aarch64-linux-gnu/hdf5/serial` instead of `/usr/lib/arm-linux-gnuabihf/hdf5/serial`)

cc @hasindu2008

**Comment by junaruga** [comment]
Hi @jts thanks for that!

>  I need to use the system libhdf5

Seeing Current https://github.com/jts/nanopolish/blob/master/.travis.yml and your updated version https://github.com/jts/nanopolish/blob/travis_update/.travis.yml ,
On ARM64 (= aarch64) environment, it is installed into `/usr/lib/aarch64-linux-gnu/hdf5/serial`.
On ARM32 environment, it is installed into `/usr/lib/arm-linux-gnuabihf/hdf5/serial`.

You dropped ARM32 case in `.travis.yml`. How do we run ARM32 case?

**Comment by jts** [comment]
Ah, OK. Thanks for the clarification, I mis-read the architecture string. 

I don't think travis supports arm32. Is this an important platform for your work or is arm64 enough?

**Comment by junaruga** [comment]
Yes, Travis does not support arm32.

For me, arm64 case is good enough. But in my memory, @hasindu2008 runs nanopolish in both arm64 and arm32 environment. He needs both arm64 and arm32 are supported.

To support arm32 case, I have 2 options.

1. Keep current arm32 case (`name: armv7l-system-hdf5`).
https://github.com/jts/nanopolish/blob/master/.travis.yml#L54-L61

2. Use new native arm32 supported CI.
https://github.com/ruby/ruby/blob/master/.drone.yml

How do you think?

**Comment by junaruga** [comment]
I am running arm32 case based on your [.travis.yml](https://github.com/jts/nanopolish/blob/travis_update/.travis.yml).

This is to use a cross compiling gcc package for arm 32-bit on arm64, and `setarch` command.

https://github.com/junaruga/nanopolisha/blob/feature/travis_update_jaruga/.travis.yml
https://travis-ci.org/junaruga/nanopolish/builds/611001707
The arm server is not stared because of a issue for now.

As today it seems I did it for ruby project, I am adapting same way for this project.
https://github.com/ruby/ruby/pull/2673

**Comment by hasindu2008** [comment]
I use 32-bit ARM sometimes but not very frequent. Anyway if it works for ARM64 bit, I think there is a high chance that it will compile on ARM32 bit. So if this 32-bit test gives too much trouble, I don't mind if it is removed.

**Comment by junaruga** [comment]
> I am running arm32 case based on your .travis.yml.

For my progress to run arm32 in Travis arm64, it's hard, because nanopolish `Makefile` is installing dependencies in it. In case to build arm32 binary, need to specify `CC` and etc environment variables for the `Makefile` too.
So, I think this option is hard.

Other options
* Keeping arm32 QEMU case. It takes long time. But it's not hard to keep.
* Starting to use Drone CI arm32 case. It's not hard for me to work to start using it.

So, it's up to you, @jts .

**Comment by jts** [comment]
Thanks for the input guys. I agree with Hasindu that ARM64 testing should be sufficient - proper 32bit testing is outside the scope of travis.ci anyway since it would need appropriately sized real-world datasets.

**Comment by jts** [comment]
Merged in 0b28ff0
