### ISSUE TITLE
how to filter the coverage of methylation_calls.tsv

### ISSUE THREAD

**Issue by DAVID2022** [jts/nanopolish#559]
Hi Jared,

I'm having trouble in finding the script to filtered out any position with <10 reads in  the methylation_calls.tsv created by nanopolish call-methylation

I'd be grateful if you could point me in the right direction.

Cheers,
DAVID

**Comment by jts** [comment]
Hi David,

If you run the `calculate_methylation_frequency.py` script (located in `scripts`) it will output a tsv file with coverage as one column.

Jared

**Comment by DAVID2022** [comment]
> Hi David,
> 
> If you run the `calculate_methylation_frequency.py` script (located in `scripts`) it will output a tsv file with coverage as one column.
> 
> Jared

**Comment by DAVID2022** [comment]
Dear Jared,
    Thank you very much for your help! but I can only find the column named“chromosome  start    end      num_cpgs_in_group  called_sites  called_sites_methylated  methylated_frequency  group_sequence” without one column named "coverage" in the output  tsv file of scripts/calculate_methylation_frequency.py according to the example of your tutorial(https://nanopolish.readthedocs.io/en/latest/quickstart_call_methylation.html). I am trying to run calculate_methylation_frequency.py on the data of DOI:10.1038/nbt.4060, but can not get the wanted result.
    Best wishes,
    David.

**Comment by jts** [comment]
called_sites is effectively sequencing depth when the group contains a single CpG. Sorry for being unclear in my previous response.

Jared

**Comment by jts** [comment]
There's a better explanation of these columns here:

https://github.com/jts/nanopolish/issues/365

**Comment by DAVID2022** [comment]
Thank you very much for your help! Thanks for this great software！

**Comment by jts** [comment]
No problem, glad I could help.
