### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by hygine** [jts/nanopolish#560]
Traceback (most recent call last):
  File "calculate_methylation_frequency_strand.py", line 51, in <module>
    num_sites = int(record['num_motifs']) 
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by jts** [comment]
Hi,

Can you provide more information, like what commands you ran?

Thanks,
Jared

**Comment by jts** [comment]
Can you send me the file `./Scaffold2112.methylation_calls.csv`, or a small subset of it that reproduces the problem?

**Comment by hygine** [comment]
when I check my input file ,i find this:

Scaffold892     +       163256  163256  a4d5d5b6-5677-4b4c-af7c-6d7408985d8f    -0.02   -106.38 -106.36 1       1       ATAAACGCATA
Scaffold892     +       163319  163328  a4d5d5b6-5677-4b4c-af7c-6d7408985d8f    0.28    -142.61 -142.89 1       2       GTGGCCGTAGCCCCCGCCTT
Scaffold892     +       163340  163342  a4d5d5b6-5677-4b4c-af7c-6d7408985d8f    0.41    -93.41  -93.82  1       2       GGATGCGCGAATG
Scaffold892     +       163357  163381  a4d5d5b6-5677-4b4c-af7c-6d7408985d8f    -1.72   -419.61 -417.89 1       5       ATGTTCGAACCCGTCTCGTCCGGAAAGTCCGTACC
Scaffold892     +       163397  163397  a4d5d5b6-5677-4b4c-af7c-6d7408985d8f    -0.49   -142.92 -142.43 1       1       ACTGCCGCCTC
Scaffold892     +       163477  163477  a4d5d5b6-5677-4b4c-af7c-6d7408985d8f    1.23    -167.57 -168.80 1       1       ACCATCGGCTG
Scaffold892     +       163497  163497  a4d5d5b6-5677-4b4c-af7c-6d7408985d8f    1.39    -99.70  -101.09 1       1       TCCACCGGCCA
Scaffold892     +       163517  163517  a4d5d5b6-5677-4b4c-af7c-6d7408985d8f    -0.11   -124.90 -124.79 1       1       CCCATCGGCTG
**Scaffold892     +       163536  163536  a4d5d5b6-5677-4b4c**
Scaffold54      -       556386  556391  363af4fb-3deb-4a42-a1c1-80741963f7be    2.41    -157.23 -159.64 1       2       AATTTCGTCACGACCT
Scaffold54      -       556546  556546  363af4fb-3deb-4a42-a1c1-80741963f7be    -0.70   -104.01 -103.31 1       1       AAAATCGAGGA
Scaffold54      -       556604  556604  363af4fb-3deb-4a42-a1c1-80741963f7be    -2.74   -120.27 -117.54 1       1       TACCACGTCAA
Scaffold54      -       556623  556626  363af4fb-3deb-4a42-a1c1-80741963f7be    3.97    -120.52 -124.48 1       2       CTATACGACGCCAA
Scaffold54      -       556668  556668  363af4fb-3deb-4a42-a1c1-80741963f7be    0.41    -83.18  -83.59  1       1       TACCACGCCAA
Scaffold54      -       556681  556681  363af4fb-3deb-4a42-a1c1-80741963f7be    -1.85   -85.85  -84.01  1       1       GTTATCGTACA
Scaffold54      -       556728  556728  363af4fb-3deb-4a42-a1c1-80741963f7be    -4.02   -154.20 -150.18 1       1       AATAACGGATT
Scaffold54      -       556746  556753  363af4fb-3deb-4a42-a1c1-80741963f7be    -4.70   -186.86 -182.16 1       2       AACAACGTCCTCCGCACA
Scaffold54      -       556914  556914  363af4fb-3deb-4a42-a1c1-80741963f7be    -0.79   -82.38  -81.60  1       1       ATAGTCGTAAT
Scaffold54      -       556935  556935  363af4fb-3deb-4a42-a1c1-80741963f7be    1.99    -111.87 -113.86 1       1       ATGTCCGAACA
Scaffold54      -       556965  556965  363af4fb-3deb-4a42-a1c1-80741963f7be    3.20    -124.34 -127.54 1       1       TCTCCCGAAAT
Scaffold54      -       557082  557082  363af4fb-3deb-4a42-a1c1-80741963f7be    -2.75   -118.34 -115.59 1       1       ACCCTCGCAAT

**Comment by jts** [comment]
Hi,

It looks like the output file of `call-methylation` is truncated. Did it exit with an error?
