### ISSUE TITLE
Error: no fast5 files found

### ISSUE THREAD

**Issue by cmfield** [jts/nanopolish#561]
I'm going mad trying to use nanopolish. I basecalled with guppy, then simply concatenated all the .fastq files together and converted into a single large .fasta file. I try:

nanopolish index -d /definitely/the/path/to/the/fast5/files concatenated_reads.fasta

It spends a long time creating an index for the .fasta and then says there are no fast5 files.. what am I missing?

**Comment by jts** [comment]
What version of nanopolish are you using? If your fast5s are the new multi-fast5 format then you'll need the very latest nanopolish to use them.

**Comment by cmfield** [comment]
I updated to 0.11.0 and now it works, so that was likely the issue. Sorry for the issue!
