### ISSUE TITLE
polya- contig/pos take first line of BAM rather than primary alignment? 

### ISSUE THREAD

**Issue by AngelaLNicholson** [jts/nanopolish#562]
Hello,
I am using your polya algorithm to call polya tail length from Direct RNA Nanopore data. When I compare the polya output tsv file to my aligned BAM file, I noticed that for a readname that mapped to multiple locations, the tsv will list the contig and position of whichever is listed first (so, generally chromosome 1) even though that may not be the primary alignment. It seems like the polya algorithm does not take into account the SAM flags indicating which is the primary alignment and which is not. 

To get to this place, I am using Nanopolish index, followed by minimap2 to do aligning (minimap2 -a -x splice -uf -k14), and then formatting and sorting the BAM file, then Nanopolish polya --threads=8 --reads=all_fastq.fastq --bam=all.sorted.bam --genome hg38.fa > polya_results.tsv

For an example, here is a line from the polya tsv output
d34e4e18-9b35-463d-a114-104caa7cc6b3	chr1	14399	27.0	3424.0	8148.0	13365.0	100.40	168.87	PASS

And here is a screenshot from the BAM file for that particular readname:

<img width="1510" alt="Screen Shot 2019-03-19 at 12 30 23 PM" src="https://user-images.githubusercontent.com/16598458/54636081-d7c7c000-4a42-11e9-8d7d-9354ac9bf551.png">

 So the actual correct contig and position should be on chrom9, 14513 I believe, since that was the primary alignment. Please let me know if I am missing a flag or other identifier that would fix this issue. Thanks!

**Comment by jts** [comment]
Hi Angela,

Good catch, and thanks for the detailed bug report. @paultsw I think we should change the program to only output for the primary alignment, what do you think?

Jared

**Comment by paultsw** [comment]
I think that's a pretty reasonable expectation for the output. I'll make some updates and comment here when the changes are pushed.

**Comment by paultsw** [comment]
Hi @AngelaLNicholson , sorry for the delay. I've made the changes so that the program checks for primary/secondary alignment while looping through the BAM (omitting estimates for secondary). Let me know if you encounter any further issues!
