### ISSUE TITLE
Error of calculate_methylation_frequency.py

### ISSUE THREAD

**Issue by DAVID2022** [jts/nanopolish#563]
Hi Jared,

when I try to run calculate_methylation_frequency.py with Python 2.7.15.  I get the error message like this:

(python27-2) [pgv3193@ln11%cngrid2 code]$ cat slurm-6.out
Traceback (most recent call last):
  File "/public4/home/DAVID/TASK22-3g/code/calculate_methylation_frequency.py", line 85, in <module>
    (c, s, e) = key.split(":")
ValueError: too many values to unpack

I'd be grateful if you could tell me how to solve this problem.

Cheers,
DAVID

**Comment by mike-molnar** [comment]
Hi DAVID,

An error like this can occur if the read name has a ":" in it.  I'm working on a fix for it now, and I will post a message when it has been merged.  Hopefully, this will resolve your issue.

Thanks,
Mike

**Comment by DAVID2022** [comment]
Hi Mike,

    When I run "nanopolish call-methylation " with my nanopore data, I got a 37202167  lines methylation_calls.tsv file, with only 564 lines in that  methylation_calls.tsv file contain a ":" in the column of "chromosome". So, to go on the analysis of my data, may be I should just delete those lines that have  a ":" in the column of "chromosome" in the methylation_calls.tsv file ? As those lines with  a ":" in the column of "chromosome" mean that read can not match to any chromosome, so those reads are meaningless for my subsequent analysis ?

the lines without a ":"  in the methylation_calls.tsv file just like:
chromosome      strand  start   end     read_name       log_lik_ratio   log_lik_methylated      log_lik_unmethylated    num_calling_strands     num_motifs      sequence
chr1    -       10810   10815   befddb77-55dd-4468-ad8e-992452f8ec38    4.90    -89.66  -94.56  1       3       GCTAGCGCGTCGGGGT
chr1    -       10826   10866   befddb77-55dd-4468-ad8e-992452f8ec38    2.28    -403.54 -405.82 1       10      GGAGGCGTGGCGCAGGCGCAGAGAGGCGCGCCGCGCCGGCGCAGGCGCAGA
chr1    -       10884   10886   befddb77-55dd-4468-ad8e-992452f8ec38    -1.00   -125.17 -124.17 1       2       GCTACCGCGTCCA
chr1    -       10902   10942   befddb77-55dd-4468-ad8e-992452f8ec38    6.76    -383.46 -390.22 1       9       GGAGGCGTGGCGCAGGCGCAGAGAGGCGCACCGCGCCGGCGCAGGCGCAGA
chr1    -       10960   10962   befddb77-55dd-4468-ad8e-992452f8ec38    3.77    -191.82 -195.59 1       2       GCTAGCGCGTCCA
chr1    -       10978   11011   befddb77-55dd-4468-ad8e-992452f8ec38    17.60   -473.94 -491.54 1       6       GGAGGCGTGGCGCAGGCGCAGAGACGCAAGCCTACGGGCGGGGG
chr1    -       11026   11026   befddb77-55dd-4468-ad8e-992452f8ec38    0.32    -132.83 -133.15 1       1       GGGGGCGTGTG
chr1    -       11047   11067   befddb77-55dd-4468-ad8e-992452f8ec38    3.18    -264.24 -267.42 1       5       AAAGTCGCACGGCGCCGGGCTGGGGCGGGGG

the lines with a ":"  in the methylation_calls.tsv file just like:
HLA-DQB1*02:02:01 + 4435  4435  fb8b9678-e4d8-4b7f-a926-66db55be9dbb  5.05  -135.21 -140.26 1 1 GAAACCGTGAT
HLA-DQB1*02:02:01 + 4551  4551  fb8b9678-e4d8-4b7f-a926-66db55be9dbb  2.10  -94.79  -96.89  1 1 CAGACCGACCA
HLA-DQB1*02:02:01 + 4882  4889  fb8b9678-e4d8-4b7f-a926-66db55be9dbb  11.19 -111.07 -122.26 1 2 GGAATCGAGTTACGGGCA
HLA-DQB1*02:01:01 + 4444  4444  fb8b9678-e4d8-4b7f-a926-66db55be9dbb  -1.20 -163.91 -162.71 1 1 GAAACCGTGAT
HLA-DQB1*02:01:01 + 4560  4560  fb8b9678-e4d8-4b7f-a926-66db55be9dbb  -0.01 -125.32 -125.31 1 1 CAGACCGACCA
HLA-DQB1*02:01:01 + 4891  4898  fb8b9678-e4d8-4b7f-a926-66db55be9dbb  -1.09 -186.02 -184.93 1 2 GGAATCGAGTTACGGGCA
HLA-DQB1*05:01:01:01  + 1760  1771  68ac8707-347f-4590-90e5-c8d991f5a495  -20.07  -155.94 -135.87 1 3 TCATGCGAGAACGCCCCGATCC
HLA-DQB1*05:01:01:01  + 1809  1809  68ac8707-347f-4590-90e5-c8d991f5a495  2.28  -107.15 -109.43 1 1 CAGCCCGACTG
HLA-DQB1*05:01:01:01  + 1821  1821  68ac8707-347f-4590-90e5-c8d991f5a495  -6.25 -127.91 -121.66 1 1 CTCTTCGCTGG
HLA-DQB1*05:01:01:01  + 1858  1858  68ac8707-347f-4590-90e5-c8d991f5a495  -0.53 -83.97  -83.44  1 1 CTTTCCGCCCT
HLA-DQB1*05:01:01:01  + 1882  1890  68ac8707-347f-4590-90e5-c8d991f5a495  -6.23 -130.40 -124.17 1 2 GAAGGCGGATTCCCGAAGC
HLA-DQB1*05:01:01:01  + 1908  1908  68ac8707-347f-4590-90e5-c8d991f5a495  -8.82 -116.28 -107.46 1 1 GAGGGCGGGCA
HLA-DQB1*05:01:01:01  + 1928  1931  68ac8707-347f-4590-90e5-c8d991f5a495  -3.39 -85.01  -81.61  1 2 AGAGCCGCCGGGAG

Best wishes,
David

**Comment by jts** [comment]
Hi David,

Yes, for now you can just delete those lines. We will fix it properly and post a fix in the next few days.

jared

**Comment by DAVID2022** [comment]
Hi,
I will try to go on the analysis.
Thank you so much for your time!
Best wishes,
David

**Comment by mike-molnar** [comment]
Hi David,

I've made the changes to the script to work no matter what the chromosome is named.  Update your version of Nanopolish and give it a try.  Post another message here if you have any problems with it.

Thanks,
Mike

**Comment by DAVID2022** [comment]
Hi Mike,
Thank you so much for your help!
Best wishes,
David
