### ISSUE TITLE
Nanopolish index not compatible with promethion fast5 files?

### ISSUE THREAD

**Issue by kcastellano13** [jts/nanopolish#564]
Hello!

I was trying to use nanopolish on my promethion data but when I direct nanopolish to my fast5 folder I get an error that says "no fast5 files". There are definitely fast5 files in that folder but it does not recognize them, does anyone know why this is?

Thanks!

**Comment by jts** [comment]
Hi,

It should work with PromethION files. Are you using the latest nanopolish? You can check with the `nanopolish --version` command.

thanks
Jared

**Comment by kcastellano13** [comment]
Oh that is definitely the problem! Looks like we have 0.9.0. Promethion files should work with the newest version? Thanks!

**Comment by jts** [comment]
Yes
