### ISSUE TITLE
vcf2fasta min QUAL

### ISSUE THREAD

**Issue by MaestSi** [jts/nanopolish#565]
Dear Jared,
I would like to know if there are any plans to add a vcf2fasta option for filtering out variants based on quality score (QUAL field) in the vcf file produced by nanopolish.
Thanks in advance,
Simone

**Comment by jts** [comment]
Hi Simone,

vcf2fasta is designed to make a new consensus sequence so nanopolish will use all positive-scoring variants so I don't think we should apply a filter here. Do you find that you get a better consensus if you filter the variants?

In general better variant filtering is on our TODO list but it won't happen for awhile.

Jared

**Comment by MaestSi** [comment]
I am running nanopolish for polishing consensus sequences from amplicons. Based on a few tests I did, I found out that if coverage is about 200X, there is no need for filtering out variants, while if coverage is about 500X, I get sligthly better results when filtering out variants with QUAL < 100. Probably, the increase of coverage above a certain threshold results in a bit of overpolishing.
What do you think about it?
Simone
