### ISSUE TITLE
Does sequencing summary file created by Guppy could work for nanopolish index ?

### ISSUE THREAD

**Issue by DAVID2022** [jts/nanopolish#567]
Hi ,
Can I use the sequencing summary file created by Guppy（v1.8.5） on PromethION to accelate the process of  nanopolish index (v0.11.0)?

the sequencing summary file created by guppy1.8.5 just like:
filename    read_id    run_id    channel    start_time    duration    num_events    passes_filtering    template_start    num_events_template    template_duration    sequence_length_template    mean_qscore_template    strand_score_template    median_template    mad_template
PCT0020_20190203_0004A30B0024921C_1_A11_D11_sequencing_run_20190203_NPL0651_P1_A11_D11_79208_read_2408_ch_2615_strand.fast5    b1d971c3-765a-4211-a654-99eed890050e    40a69fcd7be27de13cbedc2d426dd3be0aecffba    2615    13764.462891    6.223    4978    False    13764.664062    4817    6.02175    2307    6.77315    -0.001893    77.489738    9.868973
PCT0020_20190203_0004A30B0024921C_1_A11_D11_sequencing_run_20190203_NPL0651_P1_A11_D11_79208_read_2472_ch_2394_strand.fast5    2cc114e4-2d03-4df3-b26a-3440da50570e    40a69fcd7be27de13cbedc2d426dd3be0aecffba    2394    13697.359375    34.633751    27707    True    13698.026367    27173    33.966251    16971    8.482862    -0.001558    72.006973    9.503456
PCT0020_20190203_0004A30B0024921C_1_A11_D11_sequencing_run_20190203_NPL0651_P1_A11_D11_79208_read_2490_ch_372_strand.fast5    aaa37cb3-6cd4-41b9-a870-74335ec8c562    40a69fcd7be27de13cbedc2d426dd3be0aecffba    372    13785.490234    5.7815    4625    False    13785.494141    4621    5.7765    53    1.610753    -0.003007    49.7104    6.579319
PCT0020_20190203_0004A30B0024921C_1_A11_D11_sequencing_run_20190203_NPL0651_P1_A11_D11_79208_read_3061_ch_1339_strand2.fast5    00fcb884-3084-4bc6-94bd-2412015280db    40a69fcd7be27de13cbedc2d426dd3be0aecffba    1339    13779.90918    7.659    6127    False    13779.90918    6127    7.659    35    1.0    -0.003279    89.917343    5.848282

I'd be grateful if you could tell me how to solve this problem.
Cheers,
DAVID

**Comment by jts** [comment]
Did you try it? If so what error did you get

**Comment by DAVID2022** [comment]
Hi ,
I have tried.  With the  sequencing summary file created by Guppy（v1.8.5), the speed of nanopolish index (v0.11.0)  was 25 times faster than without the  sequencing summary file (both on a node with CPU:E5-2670 v2   RAM:128GB).  Which means the process that used to cost me more than 100 hours,  just need 4 hours now. The huge improvement make me to  introspect that  is there anything wrong ? As I still in the process to get the final result of the methylation frequency of every genomic position, I can not give the judgement that whether there is any error.  But I have not got any  error message  from nanopolish for now ( I am waiting for the result of nanopolish call-methylation now ).
Cheers,
DAVID

**Comment by DAVID2022** [comment]
No error message from nanopolish during the process of nanopolish index . and all reads got the path to fast5 :
[readdb] num reads: 3973892, num reads with path to fast5: 3973892

**Comment by jts** [comment]
That is all fine, it is intended that using the summary file is much faster than without.

Jared

**Comment by DAVID2022** [comment]
Hi ,
So sequencing summary file created by any base calling software can be used to accelate the process of nanopolish index ? Whatever it is Albacore, Guppy, or Flappie？Is there any requirement for the sequencing summary file that put into nanopolish index?
Best wishes,
David

**Comment by jts** [comment]
I don't think flappie outputs a sequencing summary file. We try to support the latest basecaller output but sometimes we fall behind.

**Comment by DAVID2022** [comment]
Thank you very much for your help! 
    Best wishes,
    David.
