### ISSUE TITLE
nanopolish index just stops doing anything

### ISSUE THREAD

**Issue by cmfield** [jts/nanopolish#568]
I'm using nanopolish 0.11.0.

I run nanopolish index -d fast5/ basecall.fasta and at the point where it should be producing the readdb file it just freezes - no CPU or memory activity.

I ran strace:
```
open("fast5//FAK41338_39265f711ac520b1e56b63e2d889427ed1a6df9a_1.fast5", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0640, st_size=236488936, ...}) = 0
flock(3, LOCK_SH|LOCK_NB
```

Does it have a problem only running on some of the reads from a run, because I have only copied across 1 fast5 file with 4000 reads to test it.

**Comment by jts** [comment]
That is strange, and I'm not sure it is a nanopolish issue. Are you able to read those fast5 files with other tools (eg `h5dump`)?
