### ISSUE TITLE
Does sequencing summary file created by Guppy could work for nanopolish index ?

### ISSUE THREAD

**Issue by DAVID2022** [jts/nanopolish#569]
Hi ,
So sequencing summary file created by any base calling software can be used to accelate the process of nanopolish index ? Whatever it is Albacore, Guppy, or Flappie？Is there any requirement for the sequencing summary file that put into nanopolish index?
Best wishes,
David

**Comment by jts** [comment]
Closing as this is a duplicate of a comment made in a different issue.

Jared

**Comment by DAVID2022** [comment]
Thank you very much for your help! 
Best wishes,
David.
