### ISSUE TITLE
Error during the process of running calculate_methylation_frequency.py

### ISSUE THREAD

**Issue by DAVID2022** [jts/nanopolish#571]
Hi ,
After finish nanopolish call-methylation,I always get  a message like this:

[bam process] iterating over region: chr7:1-29762391
[post-run summary] total reads: 56879, unparseable: 0, qc fail: 165, could not calibrate: 59, no alignment: 7719, bad fast5: 0

the proportion of all "qc fail", "could not calibrate" and  "no alignment" reads of the genome  is 15%. Is this situation ok for subsequent analysis ?

Also,  I cat all  methylation_calls.tsv files into a single methylation_calls.tsv, and try to run calculate_methylation_frequency.py on that files, but I get the error message like :
 
Traceback (most recent call last):
File "/public1/home/DAVID/software/nanopolish/scripts/calculate_methylation_frequency.py", line 51, in <module>
num_sites = int(record['num_motifs'])
ValueError: invalid literal for int() with base 10: 'num_motifs'

my methylation_calls.tsv just like:

chromosome strand start end read_name log_lik_ratio log_lik_methylated log_lik_unmethylated num_calling_strands num_motifs sequence
chr1 - 48 48 552d4e70-3035-44f0-a008-7bfc272dd3f0 0.94 -103.11 -104.05 1 1 CACAACGGCAT
chr1 - 67 67 552d4e70-3035-44f0-a008-7bfc272dd3f0 0.20 -95.26 -95.46 1 1 TGTTGCGCATA
chr1 - 117 117 552d4e70-3035-44f0-a008-7bfc272dd3f0 1.73 -93.76 -95.49 1 1 AAAATCGATTT
chr1 - 304 304 552d4e70-3035-44f0-a008-7bfc272dd3f0 0.94 -104.82 -105.77 1 1 AAAATCGGCTG
chr1 - 322 322 552d4e70-3035-44f0-a008-7bfc272dd3f0 2.89 -109.45 -112.34 1 1 AAATACGTTGG
chr1 - 342 356 552d4e70-3035-44f0-a008-7bfc272dd3f0 6.32 -195.99 -202.31 1 3 GTTTTCGGTTGCGGAACCCCGTATC

I'd be grateful if you could tell me how to solve this problem.
Best wishes,
David

**Comment by jts** [comment]
Each of the individual files have a header ("chromosome strand ..."). When you cat them together you have 60 headers in the file and the script can't parse it. Try catting them together with only a header on the first line.

**Comment by DAVID2022** [comment]
Thank you very much for your help！
