### ISSUE TITLE
nanopolish call-methylation error

### ISSUE THREAD

**Issue by huangjianzuishuai** [jts/nanopolish#572]
I'm using nanopolish 0.11.0.

I run nanopolish call-methylation -t 8 -r fastq.gz -b minimap2.hg19.merged.bam -g hg19.fa -w chr6:1-171115067 > chr6.5mC.nanopolish.tsv

error:
          build FASTA index
         iterating over region: chr6:1-171115067

and now call-methylation will spend more time than before.

**Comment by jts** [comment]
Hi,

Those are normal status messages, not errors.

Jared

**Comment by huangjianzuishuai** [comment]
spend more time than before
