### ISSUE TITLE
Eventalign Summary fields of direct RNAseq

### ISSUE THREAD

**Issue by monahanj** [jts/nanopolish#573]
Hi Jared & Paul,

I was wondering if you could tell me what do the "shift", "scale",  "drift" and  "var" values in the eventalign summary tell me about a read.

Best wishes,

Jack

**Comment by paultsw** [comment]
Hi Jack,

The raw pico-amp signal associated to a given read typically has a linear trend which requires us to apply a linear correction to de-trend the signal before model-based methods are applicable. The four parameters `shift`, `scale`, `drift`, and `var` refer to this trend. Briefly:
* `shift` and `scale` are the parameters of a linear correction applied to each sample of the read;
* `drift` refers to another scaling parameter, which adjusts the drift in the signal over time;
* `var` is the variance in the signal over time.

You can see an example of the usage of `shift`, `scale`, and `drift` in the following section of the nanopolish source code:
https://github.com/jts/nanopolish/blob/master/src/nanopolish_squiggle_read.cpp#L1093-L1110

**Comment by monahanj** [comment]
Thanks Paul,

That's great help, I'll check out the source code

Best wishes,

Jack
