### ISSUE TITLE
Error: no fast5 files found

### ISSUE THREAD

**Issue by dominik-handler** [jts/nanopolish#574]
Hi,

I am using the newest 0.11.1 version of nanopolish but have problems with indexing of multi-read fast5 files. 
It runs the indexing but then tells me that no fast5 files were found. Can the problem be that these multi fast5 files have been created with the ONT tool single_to_multi_fast5 from single read fast5 files?

Thank you and all the best,
Dominik

**Comment by dominik-handler** [comment]
Nevermind, I found the problem. It was a small bug in my basecalling pipeline. 

Thank you nonetheless,
Dominik

**Comment by Velastegui** [comment]
Hi! 
I am using nanopolish 0.10.2, and Guppy basecalling. My outputs are .index, .index.fai, and .index.gzi , but I have got an error in the readdb indexing. The message looks like this: 


nanopolish index -d ~/nanopolish/scripts/R_25/allFast5_R25.fast5 ~/nanopolish/scripts/R_25/R25_all.fastq
ls
allFast5_R25.fast5  R25_all.fastq  R25_all.fastq.index  R25_all.fastq.index.fai  R25_all.fastq.index.gzi  
[readdb] indexing /home/edgar/nanopolish/scripts/R_25/allFast5_R25.fast5
Error: no fast5 files found


Any suggestion will help. 
Thanks!

**Comment by jts** [comment]
Hi,

The parameter to -d should be a directory, not a single file.

Jared

**Comment by Velastegui** [comment]
Thank you so much, Jts! So far I haven't got any errors.

**Comment by behrimg** [comment]
I am also getting the fast5 error. I basecalled and demultiplexed with guppy, i then demultiplexed my fast5 files with the fast5_subset from the Nanopore tools API. 

my script looks like so
`#!/bin/bash

# number of cores
#SBATCH -n 4

# set max wallclock time
#SBATCH -t 2-00:00

# set account
##SBATCH -A mbehrin2

# set name of job
#SBATCH --job-name=nanopolish_index.sh

# set STDOUT file
#SBATCH -o nanopolish_index.%j.out

#set STDERR file
#SBATCH -e nanopolish_index.%j.err

# mail alert at start, end and abortion of execution
#SBATCH --mail-type=ALL

# send mail to this address
#SBATCH --mail-user=myemail@email.com


cd /scratch/GATC_Gwyn

nanopolish index -v -d /scratch/GATC_Gwyn/Nanopolish_Fast5/barcode05/ -s /scratch/GATC_Gwyn/guppy_GPU_fastq/sequencing_summary.txt /scratch/GATC_Gwyn/guppy_GPU_barcode/CombinedFastq/Sample_113_1.guppy.fastq`

i'm giving it the proper path to my barcode files as when i enter 
ls /scratch/GATC_Gwyn/Nanopolish_Fast5/barcode05/
i get:
`[username@agave1:/scratch/]$ ls GATC_Gwyn/Nanopolish_Fast5/barcode05
barcode05_NP0.fast5   barcode05_NP12.fast5  barcode05_NP15.fast5  barcode05_NP18.fast5  barcode05_NP20.fast5  barcode05_NP23.fast5  barcode05_NP4.fast5  barcode05_NP7.fast5  filename_mapping.txt
barcode05_NP10.fast5  barcode05_NP13.fast5  barcode05_NP16.fast5  barcode05_NP19.fast5  barcode05_NP21.fast5  barcode05_NP2.fast5   barcode05_NP5.fast5  barcode05_NP8.fast5
barcode05_NP11.fast5  barcode05_NP14.fast5  barcode05_NP17.fast5  barcode05_NP1.fast5   barcode05_NP22.fast5  barcode05_NP3.fast5   barcode05_NP6.fast5  barcode05_NP9.fast5`

its not obvious to me at this point what the issue might be.

**Comment by jts** [comment]
Just a note to say I’m on vacation but will help you when I’m back at work next week.

Jared

**Comment by behrimg** [comment]
Thanks!

**Comment by jts** [comment]
@behrimg can you paste any output messages from `nanopolish index`?

**Comment by behrimg** [comment]
Yeah so there aren't any.  Heres the .err and .out files

```
[username@agave1:/scratch]$ more nanopolish_index.1597618.err 
[readdb] indexing /scratch/GATC_Gwyn/Nanopolish_Fast5/barcode05/
Error: no fast5 files found
[username@agave1:/scratch/]$ more nanopolish_index.1597618.out 
[username@agave1:/scratch/]$ 
```
The fastqs are indexed...but the fast5s are a problem.

**Comment by jts** [comment]
For some reason, nanopolish can't read your fast5 files. Can you send me `barcode05_NP0.fast5` and the corresponding basecalls?

**Comment by jts** [comment]
Also if you can open a new issue to discuss this problem it would be great
