### ISSUE TITLE
Using Nanopolish with R9 reads

### ISSUE THREAD

**Issue by bistace** [jts/nanopolish#58]
Hi,
I tried using Nanopolish on my R9 dataset. However, I encountered this error : 

HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140381286520704:
  #000: H5D.c line 358 in H5Dopen2(): not found
   major: Dataset
    minor: Object not found
  #001: H5Gloc.c line 430 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #002: H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #003: H5Gtraverse.c line 641 in H5G_traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #004: H5Gloc.c line 385 in H5G_loc_find_cb(): object 'Model' doesn't exist
    major: Symbol table
    minor: Object not found
terminate called after throwing an instance of 'hdf5_tools::Exception'
  what():  /Analyses/Basecall_1D_000/BaseCalled_template/Model: error in H5Dopen

I think that it searches for the field ` /Analyses/Basecall_1D_000/BaseCalled_template/Model` which is not present anymore in R9 fast5 files.

**Comment by jts** [comment]
Hi,

R9 support is not public yet but the development version can be found in the branch `r9-new-model`. You'll also need model files - can you email me at jared.simpson@oicr.on.ca to discuss?

**Comment by bistace** [comment]
Sure, I am going to email you.

**Comment by jts** [comment]
R9 version (0.5.0) is live
