### ISSUE TITLE
nanopolish_makerange.py output

### ISSUE THREAD

**Issue by Phallus1989** [jts/nanopolish#581]
Hi there,

I'm in the process of trying to call variants across the whole human genome. Everything seems to work fine untill I get to nanopolish variants -w. 

I used the nanopolish_makerange.py script to generate a range covering the whole genome, however non of the output files i'm generating seem to be acceptable to nanopolish variants:

error: faidx could not get contig length for contig HR.vcf
error: faidx could not get contig length for contig HR.txt
error: faidx could not get contig length for contig HR.bed

I used the following command:
python nanopolish_makerange.py /WORKSPACE/GCF_000001405.38_GRCh38.p12_genomic.fna > HR.X

It works fine if I use single -w inputs: NC_000001.11:0-50200
But if I link multiple together to run a the same time, it generates an error of too many arguments.

Is it possible to generate a file using python nanopolish_makerange.py that I can use for subsequent variant calling? Should I be using the parallel command as used for variant --consensus?

I am using v0.11.1

Thanks alot!

**Comment by jts** [comment]
Hi,

Can you post the nanopolish variants commands you're trying to run?

Jared

**Comment by jts** [comment]
I missed the last question - yes if you're trying to call variants in
multiple regions then yes you should use a parallel command like with
--consensus.

**Comment by Phallus1989** [comment]
Thanks for the prompt reply!
This is one of the nanopolish variant commands:
./nanopolish variants -t 12 --ploidy 24 --reads /STORAGE/Will/ONT/norm_rt_1/porechopped/BC01.fastq --bam /WORKSPACE/Will/minimap2-2.16_x64-linux/BC01_N.sorted.bam --genome /WORKSPACE/Will/Genomes/GCF_000001405.38_GRCh38.p12_genomic.fna -w HR.txt -o BC01_n.variants.vcf

So I should be using:
python nanopolish_makerange.py draft.fa | parallel --results nanopolish.results -P 8 \
    nanopolish variants --consensus -o polished.{1}.vcf -w {1} -r reads.fa -b reads.sorted.bam -g draft.fa -t 4 --min-candidate-frequency 0.1

I am not trying to polish or build a consensus assembly, just looking for variants in my aligned data.

Thanks again!

**Comment by Phallus1989** [comment]
In attempting to adapt the consensus parallel command my output is looking problematic:

/WORKSPACE/Will/nanopolish$ python nanopolish_makerange.py /WORKS                                                                                                                        PACE/Will/Genomes/GCF_000001405.38_GRCh38.p12_genomic.fna | parallel --results n                                                                                                                        anopolish.results -P 8
./nanopolish variants -o BC01_N.{1}.vcf threads -w {1} -r /STORAGE/Will/ONT/norm                                                                                                                        _rt_1/porechopped/BC01.fastq -b /WORKSPACE/Will/minimap2-2.16_x64-linux/BC01_N.s                                                                                                                        orted.bam -g /WORKSPACE/Will/Genomes/GCF_000001405.38_GRCh38.p12_genomic.fna -t                                                                                                                         4 --min-candidate-frequency 0.1

Academic tradition requires you to cite works you base your article on.
If you use programs that use GNU Parallel to process data for an article in a
scientific publication, please cite:

  O. Tange (2018): GNU Parallel 2018, Mar 2018, ISBN 9781387509881,
  DOI https://doi.org/10.5281/zenodo.1146014

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

More about funding GNU Parallel and the citation notice:
https://www.gnu.org/software/parallel/parallel_design.html#Citation-notice

To silence this citation notice: run 'parallel --citation' once.
/bin/bash: NC_000001.11:0-50200: command not found
/bin/bash: NC_000001.11:50000-100200: command not found
/bin/bash: NC_000001.11:100000-150200: command not found
/bin/bash: NC_000001.11:150000-200200: command not found
/bin/bash: NC_000001.11:200000-250200: command not found
/bin/bash: NC_000001.11:250000-300200: command not found
/bin/bash: NC_000001.11:300000-350200: command not found
.......

It doesn't seem to appreciate the ranges supplied.

**Comment by jts** [comment]
What happens if you remove the quotes around `"{1}"`?

**Comment by Phallus1989** [comment]
I get the same result without the quotes, each range still gives the error:

/bin/bash: NC_000006.12:33250000-33300200: command not found
/bin/bash: NC_000006.12:33300000-33350200: command not found
/bin/bash: NC_000006.12:33350000-33400200: command not found
/bin/bash: NC_000006.12:33400000-33450200: command not found
/bin/bash: NC_000006.12:33450000-33500200: command not found

**Comment by jts** [comment]
I edited your initial comment so the command is clearer. Is there supposed to be a line break or should that all be one command?

**Comment by Phallus1989** [comment]
I believe thats an artifact of my copy and pasting.
Using the edited command I still get the same result:

/bin/bash: NC_000006.12:17300000-17350200: command not found
/bin/bash: NC_000006.12:17350000-17400200: command not found
/bin/bash: NC_000006.12:17400000-17450200: command not found
/bin/bash: NC_000006.12:17450000-17500200: command not found
/bin/bash: NC_000006.12:17500000-17550200: command not found
/bin/bash: NC_000006.12:17550000-17600200: command not found
/bin/bash: NC_000006.12:17600000-17650200: command not found
/bin/bash: NC_000006.12:17650000-17700200: command not found
/bin/bash: NC_000006.12:17700000-17750200: command not found
/bin/bash: NC_000006.12:17750000-17800200: command not found
/bin/bash: NC_000006.12:17800000-17850200: command not found

**Comment by jts** [comment]
Sorry I wasn't clear, it should all be one line like this:

```
python nanopolish_makerange.py /WORKSPACE/Will/Genomes/GCF_000001405.38_GRCh38.p12_genomic.fna | parallel --results nanopolish.results -P 8 ./nanopolish variants -t 12 --ploidy 24 -o BC01_N.{1}.vcf -w "{1}" -r /STORAGE/Will/ONT/norm_rt_1/porechopped/BC01.fastq -b /WORKSPACE/Will/minimap2-2.16_x64-linux/BC01_N.sorted.bam -g /WORKSPACE/Will/Genomes/GCF_000001405.38_GRCh38.p12_genomic.fna --min-candidate-frequency 0.1
```

**Comment by jts** [comment]
Also, I don't think you want --ploidy 24. --ploidy should be 2 for diploid genomes

**Comment by Phallus1989** [comment]
Thanks alot! 
That definitely did something, checking the original command on the help page I must have lost the '\' and the end of the first line (https://github.com/jts/nanopolish#computing-a-new-consensus-sequence-for-a-draft-assembly):

[post-run summary] total reads: 3, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 3
[post-run summary] total reads: 3, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 3
[post-run summary] total reads: 11, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 11
[post-run summary] total reads: 9, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 8
.........

Number of variants in span (18) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (14) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (14) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (12) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
nanopolish: src/nanopolish_variant_db.cpp:32: Combinations::Combinations(size_t, size_t, CombinationOption): Assertion `k <= N' failed.

I am assuming the 'bad fast5' is normal and due to low quality reads?
I was using ploidy like that to get around another error (that was likely also me doing something silly...)

I'll update with the result proper when it finishes running.

**Comment by Phallus1989** [comment]
Apologies for the delay, using porechop in my pipeline seems to annoy nanopolish:

[post-run summary] total reads: 3, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 3
[post-run summary] total reads: 3, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 3
[post-run summary] total reads: 2, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 2

So i re-ran it using non-nanopolished reads from guppy_barcoder, which generates a slough of strange errors as well as blank vcf files:
nanopolish: src/nanopolish_squiggle_read.cpp:321: void SquiggleRead::load_from_raw(fast5_file&, uint32_t): Assertion `rt.n > 0' failed.
[post-run summary] total reads: 1, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 0
[post-run summary] total reads: 3, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 0
[post-run summary] total reads: 5, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 0
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 139744274970368:
  #000: H5L.c line 815 in H5Lexists(): unable to get link info
    major: Links
    minor: Can't get value
  #001: H5L.c line 3095 in H5L__exists(): path doesn't exist
    major: Links
    minor: Object already exists
  #002: H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #003: H5Gtraverse.c line 741 in H5G__traverse_real(): component not found
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 139744274970368:
  #000: H5L.c line 815 in H5Lexists(): unable to get link info
    major: Links
    minor: Can't get value
  #001: H5L.c line 3095 in H5L__exists(): path doesn't exist
    major: Links
    minor: Object already exists
  #002: H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #003: H5Gtraverse.c line 741 in H5G__traverse_real(): component not found
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 139744274970368:
  #000: H5G.c line 470 in H5Gopen2(): unable to open group
    major: Symbol table
    minor: Can't open object
  #001: H5Gint.c line 318 in H5G__open_name(): group not found
    major: Symbol table
    minor: Object not found
  #002: H5Gloc.c line 422 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: H5Gtraverse.c line 741 in H5G__traverse_real(): component not found
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 139744266577664:
  #000: H5L.c line 815 in H5Lexists(): unable to get link info
    major: Links
    minor: Can't get value
  #001: H5L.c line 3095 in H5L__exists(): path doesn't exist
    major: Links
    minor: Object already exists
  #002: H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #003: H5Gtraverse.c line 741 in H5G__traverse_real(): component not found
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 139744266577664:
  #000: H5L.c line 815 in H5Lexists(): unable to get link info
    major: Links
    minor: Can't get value
  #001: H5L.c line 3095 in H5L__exists(): path doesn't exist
    major: Links
    minor: Object already exists
  #002: H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #003: H5Gtraverse.c line 741 in H5G__traverse_real(): component not found
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 139744274970368:
  #000: H5D.c line 292 in H5Dopen2(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #001: H5Dint.c line 1205 in H5D__open_name(): not found
    major: Dataset
    minor: Object not found
  #002: H5Gloc.c line 422 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: H5Gtraverse.c line 741 in H5G__traverse_real(): component not found
    major: Symbol table
    minor: Object not found

It would appear that nanopolish_makerange.py is working fine, its the downstream stuff i am now having an issue with. Feel free to close the issue.

Thanks alot for your help!

**Comment by jts** [comment]
Did you re-run `nanopolish index` on the reads produced by guppy_barcoder? Those errors indicate nanopolish had problems loading the reads from the fast5 files.

**Comment by Phallus1989** [comment]
I did, yes:
william@Janice:/WORKSPACE/Will/nanopolish$ ./nanopolish index -d /STORAGE/Will/ONT/norm_rt_1/normal_1_rt/20190318_0306_GA20000_FAK28210_f7aff70b/ /STORAGE/Will/ONT/norm_rt_1/barcoder/barcode01/BC01_N.fastq -s /STORAGE/Will/ONT/norm_rt_1/normal_1_rt/fastq_guppy/sequencing_summary.txt

[readdb] indexing /STORAGE/Will/ONT/norm_rt_1/normal_1_rt/20190318_0306_GA20000_FAK28210_f7aff70b/
[readdb] indexing /STORAGE/Will/ONT/norm_rt_1/normal_1_rt/20190318_0306_GA20000_FAK28210_f7aff70b//fast5_fail
[readdb] indexing /STORAGE/Will/ONT/norm_rt_1/normal_1_rt/20190318_0306_GA20000_FAK28210_f7aff70b//sequencing_summary
[readdb] indexing /STORAGE/Will/ONT/norm_rt_1/normal_1_rt/20190318_0306_GA20000_FAK28210_f7aff70b//fast5_pass
[readdb] num reads: 252726, num reads with path to fast5: 252726

The link to the fast5 files seems to be fine according to the index output.

**Comment by jts** [comment]
Hi,

Just following up on this - is it still an issue?
