### ISSUE TITLE
A incredible low correlation bwtween nanopolish and bisulfite  methylation output

### ISSUE THREAD

**Issue by DAVID2022** [jts/nanopolish#582]
Hi,
    When I finish the process of  call methyaltion on my own data of a new organism, I compare  the data of WGBS with nanopolish methylation calling result . After the application of a minimum log-likelihood threshold of 2.5 and a minimum coverage of ten reads at any sites to filter the result of nanopolish, I think I should get a correlation about 0.89 like the result in the paper published last year（ doi:10.1038/nbt.4060）:

![image](https://user-images.githubusercontent.com/45761661/55665513-b6086e80-5873-11e9-8279-48d4b5278b39.png)

However I find that there always a error position  problem between the result of Bismark_v0.20.0 and nanopolish 0.11.0, so I have to move the all methylation sites detected by  Bismark_v0.20.0 forward 1 base manually to match the nanopolish result to go on the subsequent analysis.

After all this problem ,I use the compare_methylation.py to do a comparison between nanopolish and bisulfite  methylation output, I find a incredible low correlation between them on any chromosome on my own data. what may cause this  incredible low correlation?  Is my  conduct on the result of Bismark_v0.20.0  correct ?

I'd be grateful if you could tell me how to solve this problem.
Best wishes,
David

**Comment by jts** [comment]
Bismark reports methylation for each strand separately, which is why there are lines with "+" or "-" flags. To make the file similar to nanopolish's output, you should sum the "-" records with the "+" records.

**Comment by jts** [comment]
Also, the CG density seems extremely high for your organism (27 million CGs on chromosome 1 only?). This may cause problems with calling.

**Comment by DAVID2022** [comment]
I change  the part of bisulfite analysis script of compare_methylation.py  into :

def load_bisulfite(filename):
    out = dict()
    fh = open(filename)
    for line in fh:
        fields = line.rstrip().split()
        chromosome = fields[0]
        start = int(fields[1])
        end = int(fields[1])
        strand = fields[2]
        num_reads = float(fields[3])
        methylated_reads = float(fields[4])
        key = ""

        # accumulate on forward strand
        if strand == "+":
            key = make_key(chromosome, str(start- 1), str(start- 1))
        else:
            key = make_key(chromosome, str(start - 2), str(start - 2))

        update_stats(out, key, num_reads, methylated_reads, "bisulfite")

    return out

to  sum the "-" records with the "+" records. Can this change solve  the error methylated position problem? I still do not know why there always one base distance between the  result of bismark and nanopolish.

**Comment by jts** [comment]
Maybe it is a difference between zero-based and 1-based coordinates.

**Comment by DAVID2022** [comment]
As I get a incredible low correlation bwtween nanopolish and bisulfite methylation output, can I improve the accuracy of  nanopolish methylation detection  on my research organism by just changing the log-likelihood threshold ? After I change the log-likelihood threshold, Is the output result of  nanopolish methylation detection  reliable for further research and future publication of my paper ?

**Comment by jts** [comment]
Please see my comment here:

https://github.com/jts/nanopolish/issues/582#issuecomment-480500355

Is the CG content of your organism exceptionally high?

**Comment by DAVID2022** [comment]
I plot a picture to analysis the proportion of the CpG motif in each 500 base pair bin across the whole genome as shown below, and I find that the proportion of the CpG motif across of my research organism of the whole genome is not very different  from the proportion of the CpG motif of GRCh38 reference.



![image](https://user-images.githubusercontent.com/45761661/56277102-45e0cf00-6136-11e9-9bbb-6f834d476101.png)

**Comment by DAVID2022** [comment]
I plot a picture to analysis the proportion of the C+G sites in each 500 base pair bin across the whole genome as shown below, and I find that the proportion of the C+G sites across of my research organism of the whole genome is not very different  from the proportion of the C+G sites of GRCh38 reference.
![image](https://user-images.githubusercontent.com/45761661/56284397-eccd6700-6146-11e9-9b95-b035bc974703.png)

**Comment by jts** [comment]
Thanks, that is helpful. There is quite a large shoulder in your samples around 0.6. If you exclude these regions with very high GC does correlation improve?

Also you might want to run `nanopolish call-methylation` with the option `--min-separation 5` which might help calling in CG dense regions.

**Comment by DAVID2022** [comment]
Can I use the command line parameter --min-separation in nanopolish v0.11.0 ? I can not find this parameter  when I check "nanopolish call-methylation --help".
And can you tell me after I run nanopolish call-methylation with the option --min-separation 5  ，what may happen to the accuracy of the methylation detection?

Best wishes,
David

**Comment by jts** [comment]
Yes you can use that option with 0.11.0 but it is not listed on the help page since it is experimental. We have not fully benchmarked it but it is worth trying in your case.

**Comment by DAVID2022** [comment]
Thank you very much for your help! I will try it now.

**Comment by jts** [comment]
No problem, let me know how it goes.

**Comment by DAVID2022** [comment]
Yes, definitely.

**Comment by DAVID2022** [comment]
Hi,
After the application of a minimum log-likelihood threshold of 2.5 and a minimum coverage of ten reads at any sites to filter the result of nanopolish, I get the result of methylation detection of nanopolish and  Bismark_v0.20.0 on chromosome1 on my research organism like this :


After the application of  option "--min-separation 5", a minimum log-likelihood threshold of 2.5 and a minimum coverage of ten reads at any sites to filter the result of nanopolish, I get the result of methylation detection of nanopolish and  Bismark_v0.20.0 on chromosome1 on my research organism like this :




After the application of  a minimum log-likelihood threshold of 0  and a minimum coverage of ten reads at any sites to filter the result of nanopolish, I get the result of methylation detection of nanopolish and  Bismark_v0.20.0 on chromosome1 on my research organism like this :




After the application of  a minimum log-likelihood threshold of 6  and a minimum coverage of ten reads at any sites to filter the result of nanopolish, I get the result of methylation detection of nanopolish and  Bismark_v0.20.0 on chromosome1 on my research organism like this :





After the application of  a minimum log-likelihood threshold of 10  and a minimum coverage of ten reads at any sites to filter the result of nanopolish, I get the result of methylation detection of nanopolish and  Bismark_v0.20.0 on chromosome1 on my research organism like this :






It seems whatever parameter adjustment contributes little  to my research organism .
However ,when I load the result of both software to IGV to check the methylation situation of each position ,I find a high correlation bwtween the result of the two software  based on an sketchy observation.




So after all, do you think I can use nanopolihs to proceed the analysis of DNA 5mc methyaltion on my research organism ? do you think the result of DNA methyaltion detection  by nanopolish on my research organism is reliable ?(reliable  to present the result in a coming paper?)

Best wishes,
David

**Comment by jts** [comment]
Those results look better than before, but I am not comfortable with the correlation between nanopolish and bisulfite yet so I think we need to look at it further. Can you provide me with the bismark and nanopolish frequency files for one chromosome, so I can take a closer look?

Thanks,
Jared

**Comment by DAVID2022** [comment]
Because of the great firewall of china, It may take me some time to upload the data (about 12 GB) to my google drive. I will send the shareable link of of my data to you email address (jared.simpson@oicr.on.ca) as soon as I finish the process of uploading.   

Best wishes,
David

**Comment by DAVID2022** [comment]
I have already send the google drive link of my data to your email address (jared.simpson@oicr.on.ca)  through my mailbox: canamaster2022@gmail.com.  can you get my data now?

Best wishes,
David

**Comment by jts** [comment]
Thanks, i have the files now.

Jared

**Comment by DAVID2022** [comment]
I  will look forward to your precious instruction.

Best wishes,
David

**Comment by jts** [comment]
Can you describe how you generate the bismark file (what commands you ran)?

**Comment by DAVID2022** [comment]
###TASK19-3gMETH-bismark-S1.sh
#!/bin/bash
bismark_genome_preparation /public1/home/pg3152/DAVID/TASK22-3gMETH/NANO19/DATA/bisulfite/genome

###TASK19-3gMETH-bismark-S2.sh
#!/bin/bash
bismark --bowtie2 -N 0 -q -p 10 /public1/home/pg3152/DAVID/TASK22-3gMETH/NANO19/DATA/bisulfite/genome -1 /public1/home/pg3152/DAVID/TASK22-3gMETH/NANO19/RODATA/bisulfite/RO_L2_I330.R1.clean.fastq.gz,/public1/home/pg3152/DAVID/TASK22-3gMETH/NANO19/RODATA/bisulfite/RO_L4_I330.R1.clean.fastq.gz -2 /public1/home/pg3152/DAVID/TASK22-3gMETH/NANO19/RODATA/bisulfite/RO_L2_I330.R2.clean.fastq.gz,/public1/home/pg3152/DAVID/TASK22-3gMETH/NANO19/RODATA/bisulfite/RO_L4_I330.R2.clean.fastq.gz



###TASK19-merge-bam.sh
#!/bin/bash
samtools cat -o bisulfitetotal.clean_bismark_bt2_pe.bam	RO_L2_I330.R1.clean_bismark_bt2_pe.bam RO_L4_I330.R1.clean_bismark_bt2_pe.bam
		

###TASK22-3g-bisulfite-S3-dedup.sh
#!/bin/bash
deduplicate_bismark -p --bam bisulfitetotal.clean_bismark_bt2_pe.bam


###TASK19-3g-S5-bisulfitetotal.sh
#!/bin/bash
bismark_methylation_extractor -p --no_overlap --comprehensive --multicore 5 bisulfitetotal.clean_bismark_bt2_pe.deduplicated.bam


###TASK19-3g-S6.sh
#!/bin/bash
perl new_combine_output_from_bismark_methylation_extractor.pl CHG_context_bisulfitetotal.clean_bismark_bt2_pe.deduplicated.txt CHH_context_bisulfitetotal.clean_bismark_bt2_pe.deduplicated.txt CpG_context_bisulfitetotal.clean_bismark_bt2_pe.deduplicated.txt bisulfitetotal-D_PE_all.txt

#new_combine_output_from_bismark_methylation_extractor.pl
#! usr/bin/perl -w
open(OUT,">$ARGV[$#ARGV]") or die "$!";           
$i=0;
while ($i<=$#ARGV-1){
	open (F1,$ARGV[$i]) or die "$!";
	$count=0;   #计行数
	while(my $line=<F1>){
		chomp $line;
		$count+=1;
		if ($count==1){
			if ($i==0){
				print OUT $line,"\n";             
			}
		}else{
			print OUT $line,"\n";
		}
	}
	close F1;
	$i+=1;
}



###TASK19-3g-S7.sh
#!/bin/bash
bismark2bedGraph -o bisulfitetotal_PE_all_bedgraph.txt -CX --ample_memory bisulfitetotal-D_PE_all.txt


###TASK19-3g-S8.sh
#!/bin/bash
coverage2cytosine -o bisulfitetotal_all_genome_C_report.txt -genome_folder /public1/home/pg3152/DAVID/TASK22-3gMETH/NANO19/RODATA/bisulfite/genome/ -CX bisulfitetotal_PE_all_bedgraph.txt.gz.bismark.cov.gz


####TASK22-RO-bis-get_cover-methkind-filtered_1943.sh

#!/bin/bash
#$ -cwd
#$ -j y
#$ -S /bin/bash
perl get_cover-methkind-filtered_19122.pl bisulfitetotal_all_genome_C_report.txt  bisulfite_CHH.txt  bisulfite_CHG.txt  bisulfite_CG.txt
       
#get_cover-methkind-filtered_19122.pl


#!/usr/bin/perl
my($input_FILE1,$outputfilename1,$outputfilename2,$outputfilename3)=@ARGV;
open LIST,"<", $input_FILE1 or die "cannot open :$input_FILE1";
open OUT1, ">",  $outputfilename1     or die "cannot open :$outputfilename";  
open OUT2, ">",  $outputfilename2     or die "cannot open :$outputfilename"; 
open OUT3, ">",  $outputfilename3     or die "cannot open :$outputfilename"; 

while (my $line=<LIST>){
	chomp $line;
	my @arr=split/\t/,$line;
	if ( ($arr[3]+$arr[4])>=3 ) {
		if($arr[5]=~/CHH/){
			print OUT1 $line,"\n";
		}elsif($arr[5]=~/CHG/){
			print OUT2 $line,"\n";
		}elsif($arr[5]=~/CG/){
			print OUT3 $line,"\n";
		}else{}
	}else{}
}

####TASK22-RO-CG-bi-convert1946.sh

#!/bin/bash
#$ -cwd
#$ -j y
#$ -S /bin/bash
perl CG-bi-convert-4-6.pl bisulfite_CG.txt bisulfite.JdS-all_CG-nanoform-19422.txt


#CG-bi-convert-4-6.pl

#!/usr/bin/perl -w
open I, "$ARGV[0]" or die;
open O, ">$ARGV[1]" or die;

while(<I>){
    chomp;
    @ss=split;
    my $test=0;
      my $treads=$ss[3]+$ss[4];
      print O $ss[0],"\t",$ss[1],"\t",$ss[2],"\t",$treads,"\t",$ss[3],"\n";

}

**Comment by DAVID2022** [comment]
Basically, I follow the instruction of Bismark User Guide(https://rawgit.com/FelixKrueger/Bismark/master/Docs/Bismark_User_Guide.html) to get the "bisulfite.JdS-all_CG-nanoform-19422.txt" sended to you and applied in the analysis.

**Comment by DAVID2022** [comment]
Also ,I am confused with the .so, in the chacter 1.3.3 ,I can say "For
a group consisting of n CG sites, we only make a call if |LogLikRatio(SM )| > nt otherwise the group is
ignored. When calling a group, we say that n sites are called and of the called sites n are methylated if
LogLikRatio(SM ) > 0. **Also, of the called sites n are unmethylated if LogLikRatio(SM ) < 0**."

**Comment by jts** [comment]
>  Also, of the called sites n are unmethylated if LogLikRatio(SM ) < 0

yes, this is correct

I have looked at your data and have better correlation than the results you showed above. I ran the following commands to generate the plot:

```
# Remove duplicate header lines from the methylation calls file
awk 'NR == 1 || $0 !~ /num_motifs/' chr10-JdS-meth_calls.tsv > chr10-JdS-meth_calls.remove_duplicate_headers.tsv

# Calculate methylation frequency
python ~/nanopolish/scripts/calculate_methylation_frequency.py -s chr10-JdS-meth_calls.remove_duplicate_headers.tsv > nanopolish_methylation_frequency.190422.tsv

# Compare to bismark results
python compare_methylation-BISMARKv20.6.py nanopolish_methylation_frequency.190422.tsv chr10.bisulfite.JdS-all_CG-nanoform-19422.txt > compared_freq.190423.tsv
```


![methylation](https://user-images.githubusercontent.com/389535/56609443-1e2cb380-65db-11e9-961b-20bc4ea94268.png)

Can you run the same commands and see if you get the same correlation?

I noticed that some sites in your bisulfite file are strange, and only have coverage on the '+' or '-' strand. I am going to see if filtering out these sites improves the results.

**Comment by DAVID2022** [comment]
Thank you very much！ I will recheck those process now！

Best wishes,
David

**Comment by DAVID2022** [comment]
After trying the same steps again, I get a good correlation between bisulfite and ONT data. I guess the problem may be in the step of calculate_methylation_frequency—— I used to divide my research organism's genome into 60 parts and call methylation  on each part respectively. After call methylation  I  calculate methylation frequency on each methylation_calls.tsv respectively. The total methylation_frequency.tsv I used to compare with bisulfite data(and got a low correlation about 0.62 ) was merged from 60  methylation_frequency.tsv files.
    When I  merge all methylation_calls.tsv files and use a single merged  methylation_calls.tsv file to calculate methylation frequency, I  get a different total methylation_frequency.tsv. This new total methylation_frequency.tsv was correlated well (a correlation about 0.817) with the bisulfite data of same tissure.
    Can you tell me what may be the real source of different correlation based on same data ? Can I continue my analysis with dividing my research organism's genome into 60 parts and call methylation on each part respectively (in order to accelate the process of analysis)?

![image](https://user-images.githubusercontent.com/45761661/56805326-432f5980-685b-11e9-9144-5d6c3cd69e8f.png)

**Comment by jts** [comment]
Hi,

It is OK to call methylation across many processes, but you should merge the call files before running calculate_methylation_frequency.py. I am not sure what went wrong when you tried to merge the frequency.tsv files, but I don't recommend doing that.

Jared

**Comment by DAVID2022** [comment]
Thank you very much！ I will follow your advice in the followed analysis!

Best wishes,
David
