### ISSUE TITLE
Error when calling wariants

### ISSUE THREAD

**Issue by yangxiaofeill** [jts/nanopolish#583]
Dear,
    I installed nanopolish by conda.
    I try to call variants on our samples (nanopore sequencing data) using:

```
nanopolish variants -r $FQ --genome $REF --bam $BAM --threads $NO_THREAD --outfile $OUTDIR/$SAMPLE\_ONT.nanopolish.vcf
```

However, it occurs error like:

```
TODO: train model
TODO: filter data
Error: could not find path to FAST5 for read 0000031f-9741-437a-9d31-6a95bc1df287
Please make sure that this path is accessible: start_time=2018-05-02T08:46:06Z
```

Do you have any idea to solve this problem?

**Comment by jts** [comment]
The version you installed is very very old. The version on Conda should be much more recent (0.11.1).

**Comment by yangxiaofeill** [comment]
@jts 
Thanks, I updated from conda, but it updated to `nanopolish version 0.10.2`

When I run the variants command like:

```
$NANOPOLISH variants -r $FQ --genome $REF --bam $BAM --threads 2 --ploidy 2 --outfile $OUTDIR/$SAMPLE\_ONT.nanopolish.vcf -w chr1:5000000-10000000
```

it reports errors like:

```
error: could not load the index files for input file $FQ
Please run nanopolish index on your reads (see documentation)
```

I checked the Index command and found it require raw ONT signal files which I have not.  I just have the fastq file after basecalling. 

So, how to solve this issue?

Thanks.

**Comment by jts** [comment]
Nanopolish requires the signal files, sorry. If you can't get them you won't be able to run nanopolish.
