### ISSUE TITLE
Minimalistic commands to call variants and get a output vcf file

### ISSUE THREAD

**Issue by lakhujanivijay** [jts/nanopolish#584]
Hi @jts 

I hope you are doing well. Thanks for the amazing tool first of all, really appreciate the hard work and efforts that are put into projects like nanopolish. I am a beginner with nanopore sequencing and getting my hands dirty with long reads from ONT.

I am reading/following blogs for nanopore data and currently I am interested in variant calling. My primary objective is to just perform variant calling and get the data into a vcf (the old man's way).

While I followed the documentation of nanopolish, I could see that the steps help to polish a draft genome by variant calling (correct me if I am wrong). However, I am interested in getting just the vcf file containing variants; how to proceed for that. So far, I have followed the following steps:

1. basecalling by guppy

2. mapping reads on to the genome using minimap2

3. Ran this command:

```
nanopolish_makerange.py my_genome.fa | parallel --results nanopolish.results -P 8 \
nanopolish variants --consensus -o polished.{1}.vcf -w {1} -r my_nanopore_reads.fa -b out.sorted.bam -g my_genome.fa -t 4 --min-candidate-frequency 0.1
```
Am I on the right track ?

Also, what I get at the end is multiple vcf files and most of them does not contain anything except the headers.

**Comment by jts** [comment]
Hi @lakhujanivijay,

You are on the right track but you don't need the --consensus option if you just want variants. You might benefit from running this tutorial to see how nanopolish works from end-to-end:

https://nanopolish.readthedocs.io/en/latest/quickstart_consensus.html

This tutorial is for calculating a consensus sequence for a genome assembly, but the process for calling variants is very similar (just don't use the `--consensus` option).

Jared

**Comment by lakhujanivijay** [comment]
Ah, there! Thank you @jts . You rock !
