### ISSUE TITLE
Failure to open the draft fasta file

### ISSUE THREAD

**Issue by chytrids** [jts/nanopolish#585]
Hello,

Hello, I am trying to use Nanopolish v.11.0 on the Flux Linux-based operating environment at the University of Michigan to polish assembled contigs from Canu v1.8 of demultiplexed amplicons 
generated in Minibar v0.21 from fungal genomic DNA using a Nanopore MinION.

Below is an example of an attempted workflow (using bwa v.0.7.15, samtools 1.9, and minimap2 v2.16), ultimately resulting in failure to read the draft fasta file (contigs.fasta from Canu, including only tig00000002, with a length of 9173):

```
/home/chytrids/nanopolish/nanopolish index \
-d /scratch/tyjames_flux/chytrids/nanopore/CZEUM03_NoBaseCall/20190325_1730_MN29144_FAK52702_d2a7a2ad/fast5/ \
-s /scratch/tyjames_flux/chytrids/nanopore/CZEUM03_NoBaseCall/20190325_1730_MN29144_FAK52702_d2a7a2ad/fastq/sequencing_summary.txt \
../CZEUM03.fastq

[readdb] indexing /scratch/tyjames_flux/chytrids/nanopore/CZEUM03_NoBaseCall/20190325_1730_MN29144_FAK52702_d2a7a2ad/fast5/
[readdb] num reads: 221187, num reads with path to fast5: 221187

bwa index TYJ_large.contigs.fasta

/home/chytrids/programs/minimap2-2.16_x64-linux/minimap2 -ax map-ont -t 8 TYJ_large.contigs.fasta ../CZEUM03.fastq \
| samtools sort -o TYJ_large.contigs.sorted.bam -T reads.tmp

[M::mm_idx_gen::0.004*1.89] collected minimizers
[M::mm_idx_gen::0.005*2.81] sorted minimizers
[M::main::0.005*2.81] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.005*2.72] mid_occ = 8
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.006*2.67] distinct minimizers: 1391 (77.93% are singletons); average occurrences: 1.224; average spacing: 5.386
[M::worker_pipeline::43.459*1.24] mapped 155055 sequences
[M::worker_pipeline::47.969*1.16] mapped 66132 sequences
[M::main] Version: 2.16-r922
[M::main] CMD: /home/chytrids/programs/minimap2-2.16_x64-linux/minimap2 -ax map-ont -t 8 TYJ_large.contigs.fasta ../CZEUM03.fastq
[M::main] Real time: 48.116 sec; CPU: 55.584 sec; Peak RSS: 1.559 GB
[bam_sort_core] merging from 2 files...

samtools index TYJ_large.contigs.sorted.bam
samtools view TYJ_large.contigs.sorted.bam | head

/home/chytrids/nanopolish/nanopolish variants --consensus \
-o TYJ_large.contigs.polished.vcf -w "tig00000002:1-9173" \
-r ../CZEUM03.fastq -b TYJ_large.contigs.sorted.bam -g TYJ_large.contigs.fasta

[fai_load] build FASTA index.
[fai_build] fail to open the FASTA file TYJ_large.contigs.fasta
```

Would you please let me know what I'm doing wrong, or is there some step that I am missing?

Thank you for your attention and assistance,
Rabern.

**Comment by jts** [comment]
Hi,

That is very strange. Nanopolish is only trying to build an .fai file for your draft genome using an API call to htslib (the same function that `samtools faidx` uses). I can't see why this would fail if the file exists and is readable.

**Comment by jts** [comment]
Maybe try running `strace <nanopolish command>` and `strace samtools faidx TYJ_large.contigs.fasta` and send me the result of each.

**Comment by chytrids** [comment]
Thank you for your assistance. Below are the requested outputs:

[strace_samtools.txt](https://github.com/jts/nanopolish/files/3073564/strace_samtools.txt)
[strace_nanopolish.txt](https://github.com/jts/nanopolish/files/3073565/strace_nanopolish.txt)

**Comment by jts** [comment]
It looks like `samtools faidx` reported the same error (file not found), so this isn't a nanopolish issue. You'll have to figure out why these programs can't see the file (can you open it in a text editor, or run `head` on the file?)

**Comment by chytrids** [comment]
Yes, it opens fine in other applications that I've attempted. It is the Canu output contigs.fasta file. Below is the .txt of it.
[TYJ_large.contigs.fasta.txt](https://github.com/jts/nanopolish/files/3073666/TYJ_large.contigs.fasta.txt)

**Comment by jts** [comment]
Sorry for the lack of response, I just downloaded your file though and `samtools faidx TYJ_large.contigs.fasta` worked without a problem, so I'm really not sure why it doesn't work for you.
