### ISSUE TITLE
Nanopolish consensus won't run to completion or on subsequence

### ISSUE THREAD

**Issue by twaddlac** [jts/nanopolish#59]
Hello,

I am having some difficulties getting nanopolish to run to both completion as well as on a subsequence.

When I try to run nanopolish without specifying a subsequence it will run for some time and then throw the error: 

`[E::hts_open] fail to open file 'reads.pp.sorted.bam'
nanopolish: src/alignment/nanopolish_anchor.cpp:31: HMMRealignmentInput build_input_for_region(const string&, const string&, const Fast5Map&, const string&, int, int, int): Assertion `bam_fh != __null' failed.`

However, there is a partially corrected sequence that can be found in the log file at the very bottom. Though the sequence is partially corrected, I noticed that the length varies if run iteratively - the subsequent sequence is generally shorter than the starting assembly. Is this to be expected?

Second, when I do try to subset the sequence it seems that it runs when the starting coordinate is zero.

Below is an example command
` nanopolish consensus -o out.fasta -w seq:500-1000 -r reads.pp.fa -b reads.pp.
sorted.bam -g assembly.fasta -t 10 &> seq:1785-1985.log`

Please let me know if you need any other information or clarification. Thank you!

**Comment by jts** [comment]
Hi,

It would appear the required `reads.pp.sorted.bam` file and `reads.pp.sorted.bam.bai` files are not present. Can you check these files exist?

**Comment by twaddlac** [comment]
Yep, they're present.

**Comment by jts** [comment]
These two lines suggest they aren't readable by nanopolish for some reason:

```
[E::hts_open] fail to open file 'reads.pp.sorted.bam' 
nanopolish: src/alignment/nanopolish_anchor.cpp:31: HMMRealignmentInput build_input_for_region(const string&, const string&, const Fast5Map&, const string&, int, int, int): Assertionbam_fh != __null' failed.``
```

Do they have read permissions? Can `samtools view` open the files?

**Comment by twaddlac** [comment]
Yep, they all have read permission and can be opened by `samtools view`

**Comment by jts** [comment]
Oh, I see the problem now, when passing in the bam file you have an errant space: `-b reads.pp. sorted.bam`

**Comment by twaddlac** [comment]
Oh, sorry, that must've been introduced when I entered the command into this thread. The interpreter wouldn't recognized ' sorted.bam' if there was a space in it and I don't have that space in the commands that I've ran so I'm not sure that's the problem.

**Comment by jts** [comment]
Ok, can you send the fixed command and log for a subsequence? You have provide a range to nanopolish (`-w` is mandatory) which might explain the other issues (this will be changed to be more intuitive in the next release). 

Generally the sequences should become longer as the error rate is biased towards deletions rather than insertions IIRC.

**Comment by twaddlac** [comment]
Sure, below is the command:
`for i in $(samtools idxstats reads-6-2.pp.sorted.bam | cut -f1,2 | grep -v '*' | perl -pe 's/^(.+)\t(.+)/$1:0-$2/g'); do nanopolish consensus --verbose  -o assembly_6_2_blast_masked.consensus.nanopolish.nanopolish.fasta -w ${i} -r reads-6-2.pp.fa -b reads-6-2.pp.sorted.bam -g assembly_6_2_blast_masked.consensus.nanopolish.fasta -t 30 &>
assembly_6_2_blast_masked.consensus.nanopolish.nanopolish.log ; done`

And attached is the log file. Please let me know if you need anything else, thanks!
[HA_6_2_blast_masked.consensus.nanopolish.nanopolish.txt](https://github.com/jts/nanopolish/files/397451/HA_6_2_blast_masked.consensus.nanopolish.nanopolish.txt)

**Comment by jts** [comment]
Thanks - I see that you have a lot of reads here (>6,000) for this region. Is it possible that you've run out of memory? Does the problem still occur if you downsample to much lower coverage (100-200X)?

**Comment by twaddlac** [comment]
Yep, it still fails even when I downsample down to 250x. It's also highly unlikely that it runs out of memory - I'm running 30 threads on 128G of memory with 300G swap.

**Comment by jts** [comment]
Ok thanks. The log doesn't really make sense to me since it only corrects the first 1500bp (`CONSENSUS[32]`) of the 10kb segment before moving on to a new segment, where it crashes. If you run the first command outside of the loop in gdb do you get a different error?

**Comment by twaddlac** [comment]
Ah, I think I may have identified the problem. I'm trying to correct amplicons which don't get much larger than 1500bp. I notice this being mentioned in the "make_range.py" script but wasn't sure how to change it. Do you think this could be the problem? If so, is there a way to toggle the range size?

**Comment by jts** [comment]
Unfortunately not. This will be fixed in the r9 version of consensus which will be a lot more robust and flexible. You'll have to change the code, the ranges are in here:

https://github.com/jts/nanopolish/blob/master/src/nanopolish_consensus.cpp#L861

**Comment by jts** [comment]
R9 version now released, closing
