### ISSUE TITLE
error: faidx could not get contig length for contig {1}

### ISSUE THREAD

**Issue by emmannaemeka** [jts/nanopolish#590]
Hello,
Please am having problem of error: faidx could not get contig length for contig {1}. I have tried applying all the error reported yet without solution

My syntax

source tutorial-env/bin/activate python3.6 ${nanopolish}/nanopolish_makerange.py ${DRAFT}.fa | /home/emmanuel/bin/parallel --results nanopolish$ ~/nanopolish/nanopolish variants --consensus -o ${HERE}/polished.{1}.vcf -w {1} -r ${FASTQ}/…20190404.fq -b ${BAM}/nanopolish_mucuna_flye.1361.srt.bam -g ${DRAFT}.fa -t 20  --min-candidate-frequency 0.1

**Comment by jts** [comment]
I think there is a problem with your command, maybe it should be:

```
${nanopolish}/nanopolish_makerange.py ${DRAFT}.fa | /home/emmanuel/bin/parallel --results nanopolish ~/nanopolish/nanopolish variants --consensus -o ${HERE}/polished.{1}.vcf -w {1} -r ${FASTQ}/…20190404.fq -b ${BAM}/nanopolish_mucuna_flye.1361.srt.bam -g ${DRAFT}.fa -t 20 --min-candidate-frequency 0.1
```

**Comment by emmannaemeka** [comment]
That left me with this result

File "/home/emmanuel/nanopolish/scripts/nanopolish_makerange.py", line 6,
in <module>

    from Bio.SeqIO.FastaIO import SimpleFastaParser

ImportError: No module named Bio.SeqIO.FastaIO



Nnadi Nnaemeka Emmanuel,Ph.D
Department of Microbiology,
Faculty of Natural and Applied Science,
Plateau State University, Bokkos, Plateau State, Nigeria.
+2348068124819
Publications:
 https://www.researchgate.net/profile/Emmanuel_Nnadi/publications

**Comment by jts** [comment]
Hi, 

You need to install BioPython.

Jared
