### ISSUE TITLE
long time to process data

### ISSUE THREAD

**Issue by arrusus** [jts/nanopolish#591]
nanopolish is running since one week now. is it normal? 
I expected to have a longer processing time because this time I get a lot of reads from my minion run but 1 week seems too much.
do you suggest to split the reads file into smaller files and try to process them separately?
thanks

**Comment by jts** [comment]
Can you please provide more information about what you're trying to do?

Jared

**Comment by arrusus** [comment]
I have done a minion run to sequence a small genome of 8kb. The entire sequence was processed through minion 1d. 
After, using spades and another tool I get a draft reconstruction of the genome. To polish this draft sequence of 8kb I use nanopolish. The entire run was used to sequence this 8kb genome so to give an idea of the magnitude,  I get a fastq file of  4.5 Gb. Now the nanopolish is running to produce a polished genome taking into account the draft genome and the raw reads. The process is running on a cluster since 5 days now.

**Comment by jts** [comment]
Thanks. Your genome has >100,000X coverage, which is excessive. I suggest downsampling to 200-300x coverage and trying again.

Jared

**Comment by arrusus** [comment]
Ok, thanks.

**Comment by arrusus** [comment]
So, now I'm running nanopolish on less than 1/4 of the total reads but I get the error message anyway and the run keeps going since 1 day now. 
here follow the parameters that I've used:
nanopolish variants -x 50000 --consensus -o polished.vcf -r reads.fasta -b reads.sorted.bam -g finalcontig.fasta

I've seen somewhere in the forum that maybe it's normal sometimes to have the error message:
"Number of variants in span (27) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!"
Like, this not means that nanopolish is not working properly.
So I'll leave it running for the whole weekend and then on Monday, I hope that it 'll have finished.
otherwise, I can reduce the number of reads even more but it's strange since last time (for another run with fewer reads in total) it worked perfectly.

thanks 
Rosario

**Comment by jts** [comment]
If you took 25% of the reads you still have excessive coverage. I suggest only using 200x. Also, that warning about the number of variants is only a warning, you don't have to change -x.

Jared

**Comment by arrusus** [comment]
ok, but what if I leave things like that? I mean, is it just a matter of time and it will finish sooner or later, or if I don't decrease the coverage, nanopolish will never be able to finish?

**Comment by arrusus** [comment]
by the way, I have divided by 7 the 25% file.  Now I have a file of 94 Mb. Hope it'll be enough.
thanks for your support.
