### ISSUE TITLE
nanopolish variants too many arguments

### ISSUE THREAD

**Issue by Gon1976** [jts/nanopolish#592]
Hi, I am trying to run nanopolish variants (version nanopolish version 0.9.2).
And I have the error:
./nanopolish/nanopolish variants --consensus  -w "tig00000381:1-34238" -r ../reads.fasta -b reads.sorted.bam -g draft.fasta -o polished.vcf
variants: too many arguments

Usage: nanopolish variants [OPTIONS] --reads reads.fa --bam alignments.bam --genome genome.fa
Find SNPs using a signal-level HMM

It's something wrong in the command line?

**Comment by jts** [comment]
0.9.2 is very old, please try with the latest version.
