### ISSUE TITLE
No BaseCalledReadsWithVariant in VCF file

### ISSUE THREAD

**Issue by nick297** [jts/nanopolish#594]
Hello,
Sorry if this has been asked before, I haven't been able to see an answer.

My VCF files from nanopolish variants --consensus do not contain the BaseCalledReadsWithVariant information. What causes this to be omitted? 

I am calling regions of a reference.

Thanks,
Nick

**Comment by jts** [comment]
With the `--consensus` option, two types of candidate corrections are considered:

1) Mismatches/indels wrt the assembly that are consistently seen in the reads
2) All possible 1bp substitutions, insertions and deletions

The `BaseCalledReadsWithVariant` tag will only be present in corrections from 1).

Jared
