### ISSUE TITLE
Could not open fast5 file (methylation_example)

### ISSUE THREAD

**Issue by zifeng8824** [jts/nanopolish#595]
Hi,
I am trying to build my index with nanopolish index. Here is the command I use:
nanopolish index -d fast5_files/ albacore_output.fastq
However, I get the following errors for a few files:
could not open fast5 file（part result）: fast5_files//MinION2_20161115_FNFAB46664_MN20093_sequencing_run_Chip105_Genomic_R9_4_450bps_tune_41856_ch351_read170_strand.fast5
could not open fast5 file: fast5_files//PLSP61583_20161122_FNFAB45277_MN17048_sequencing_run_Hu_Bir_R94_1Dlig_fc1_1hr_31503_ch181_read1160_strand.fast5
could not open fast5 file: fast5_files//LomanLabz_PC_20161125_FNFAF01132_MN17024_sequencing_run_20161124_Human_Qiagen_1D_R9_4_96293_ch348_read1661_strand.fast5
could not open fast5 file: fast5_files//LomanLabz_PC_20161123_FNFNFAF01441_MN17024_sequencing_run_20161122_Human_Qiagen_1D_R9_4_44266_ch103_read122_strand.fast5
Error: no fast5 files found
However, I have permission to this file and am able to open it. Could there be some other thing, aside from permissions, which might cause this error?
thanks

**Comment by jts** [comment]
These are the files from the methylation tutorial? They have always worked for me and other users so I can't think of what the problem might be. What version of nanopolish are you using?

**Comment by zifeng8824** [comment]
> 
> 
> These are the files from the methylation tutorial? They have always worked for me and other users so I can't think of what the problem might be. What version of nanopolish are you using?
 yes, it is the methylation_example files. nanopolish version 0.11.1, have any problems in this version? thanks!

**Comment by jts** [comment]
0.11.1 should work. What does this command print:

```
md5sum fast5_files//LomanLabz_PC_20161123_FNFNFAF01441_MN17024_sequencing_run_20161122_Human_Qiagen_1D_R9_4_44266_ch103_read122_strand.fast5
```

**Comment by zifeng8824** [comment]
2cbba6fdaaa27c0168781ca3d27b05ae  fast5_files//LomanLabz_PC_20161123_FNFNFAF01441_MN17024_sequencing_run_20161122_Human_Qiagen_1D_R9_4_44266_ch103_read122_strand.fast5




------------------ 原始邮件 ------------------
发件人: "Jared Simpson"<notifications@github.com>;
发送时间: 2019年5月10日(星期五) 晚上9:14
收件人: "jts/nanopolish"<nanopolish@noreply.github.com>;
抄送: "zifeng8824"<zsk8920@gmail.com>;"Author"<author@noreply.github.com>;
主题: Re: [jts/nanopolish] Could not open fast5 file (methylation_example)(#595)




0.11.1 should work. What does this command print:
 md5sum fast5_files//LomanLabz_PC_20161123_FNFNFAF01441_MN17024_sequencing_run_20161122_Human_Qiagen_1D_R9_4_44266_ch103_read122_strand.fast5

**Comment by jts** [comment]
That looks fine, it matches what I have locally. Can you run `strace nanopolish index -d fast5_files/ albacore_output.fastq` and send me the complete output?

Jared

**Comment by zifeng8824** [comment]
the complete output(part)
openat(AT_FDCWD, "fast5_files//LomanLabz_PC_20161125_FNFAF01132_MN17024_sequencing_run_20161124_Human_Qiagen_1D_R9_4_96293_ch348_read1661_strand.fast5", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOTDIR (Not a directory)
open("fast5_files//LomanLabz_PC_20161125_FNFAF01132_MN17024_sequencing_run_20161124_Human_Qiagen_1D_R9_4_96293_ch348_read1661_strand.fast5", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0755, st_size=40161, ...}) = 0
flock(3, LOCK_SH|LOCK_NB)               = -1 ENOSYS (Function not implemented)
close(3)                                = 0
write(2, "could not open fast5 file: fast5"..., 160could not open fast5 file: fast5_files//LomanLabz_PC_20161125_FNFAF01132_MN17024_sequencing_run_20161124_Human_Qiagen_1D_R9_4_96293_ch348_read1661_strand.fast5
) = 160
openat(AT_FDCWD, "fast5_files//LomanLabz_PC_20161123_FNFNFAF01441_MN17024_sequencing_run_20161122_Human_Qiagen_1D_R9_4_44266_ch103_read122_strand.fast5", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOTDIR (Not a directory)
open("fast5_files//LomanLabz_PC_20161123_FNFNFAF01441_MN17024_sequencing_run_20161122_Human_Qiagen_1D_R9_4_44266_ch103_read122_strand.fast5", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0755, st_size=140464, ...}) = 0
flock(3, LOCK_SH|LOCK_NB)               = -1 ENOSYS (Function not implemented)
close(3)                                = 0
write(2, "could not open fast5 file: fast5"..., 161could not open fast5 file: fast5_files//LomanLabz_PC_20161123_FNFNFAF01441_MN17024_sequencing_run_20161122_Human_Qiagen_1D_R9_4_44266_ch103_read122_strand.fast5
) = 161
write(2, "Error: no fast5 files found\n", 28Error: no fast5 files found
) = 28
munmap(0x2ab178dc0000, 876544)          = 0
munmap(0x2ab178e96000, 233472)          = 0
munmap(0x2ab178ecf000, 233472)          = 0
munmap(0x2ab178f08000, 233472)          = 0
munmap(0x2ab178f41000, 876544)          = 0
munmap(0x2ab179017000, 233472)          = 0
munmap(0x2ab179050000, 876544)          = 0
munmap(0x2ab179126000, 876544)          = 0
munmap(0x2ab178909000, 503808)          = 0
munmap(0x2ab17724e000, 503808)          = 0
munmap(0x2ab1771d3000, 503808)          = 0
munmap(0x2ab1771b2000, 135168)          = 0
munmap(0x2ab177191000, 135168)          = 0
munmap(0x2ab177170000, 135168)          = 0
munmap(0x2ab1770f5000, 503808)          = 0
exit_group(1)                           = ?
+++ exited with 1 +++
 
I may not have installed the software, but I don't know what went wrong.
Thanks a lot!

------------------ 原始邮件 ------------------
发件人: "Jared Simpson"<notifications@github.com>;
发送时间: 2019年5月15日(星期三) 晚上10:33
收件人: "jts/nanopolish"<nanopolish@noreply.github.com>;
抄送: "zifeng8824"<zsk8920@gmail.com>;"Author"<author@noreply.github.com>;
主题: Re: [jts/nanopolish] Could not open fast5 file (methylation_example)(#595)




That looks fine, it matches what I have locally. Can you run strace nanopolish index -d fast5_files/ albacore_output.fastq and send me the complete output?
 
Jared

**Comment by zifeng8824** [comment]
I download  example dataset and try  basecalled the reads using this albacore command:
read_fast5_basecaller.py -c r94_450bps_linear.cfg -t 8 -i fast5_files -s basecalled/ -o fastq
 but in the result of basecalled/workspace folder,there nothing in it.
in the example dataset , there is not have the  r94_450bps_linear.cfg , so the command is right?

**Comment by jts** [comment]
I think this line might be important:

```
flock(3, LOCK_SH|LOCK_NB) = -1 ENOSYS (Function not implemented)
```

what operating system and file system are you using? Can you try to run the tutorial on a different computer to see if it works?

**Comment by jts** [comment]
I have pushed a new version that should fix this problem. Can you try it?

**Comment by zifeng8824** [comment]
hi, When I am using the following command to to calculate how often each reference position was methylated,there was have some errors;how do I solve it,thanks a lot.


python2.7 ~/biosoft/nanopore_bin/nanopolish/nanopolish.1.0/scripts/calculate_methylation_frequency.py -i methylation_calls.tsv >2.tsv
Traceback (most recent call last):
File "/lustre/xiazhiqiang/biosoft/nanopore_bin/nanopolish/nanopolish.1.0/scripts/calculate_methylation_frequency.py", line 47, in <module>
num_sites = int(record['num_cpgs']) 
KeyError: 'num_cpgs'

**Comment by jts** [comment]
Hi,

Please update to the most recent version.

Jared

**Comment by zifeng8824** [comment]
Hi,
I have update the recent version:
[zsk@fat01 nanopolish]$ nanopolish --version
nanopolish version 0.11.1
Written by Jared Simpson.
Copyright 2015-2017 Ontario Institute for Cancer Research


but When I am using the following command, there not have -i parameter. Is it right?
[zsk@fat01 scripts]$ python calculate_methylation_frequency.py  -h
usage: calculate_methylation_frequency.py [-h] [-c CALL_THRESHOLD] [-s]
Calculate methylation frequency at genomic CpG sites
optional arguments:
  -h, --help            show this help message and exit
  -c CALL_THRESHOLD, --call-threshold CALL_THRESHOLD
  -s, --split-groups


then I  using the following command to to calculate the frequency, this error persists.
[zsk@fat01 scripts]$ calculate_methylation_frequency.py -i wc_methylation_calls.tsv > 123.tsv
Traceback (most recent call last):
  File "./calculate_methylation_frequency.py", line 37, in <module>
    in_fh = open(f)
FileNotFoundError: [Errno 2] No such file or directory: '-i'


Whether there are other parameters to calculate.Thanks.


------------------ 原始邮件 ------------------
发件人: "Jared Simpson"<notifications@github.com>;
发送时间: 2019年7月19日(星期五) 中午11:14
收件人: "jts/nanopolish"<nanopolish@noreply.github.com>;
抄送: "zifeng8824"<zsk8920@gmail.com>;"Author"<author@noreply.github.com>;
主题: Re: [jts/nanopolish] Could not open fast5 file (methylation_example)(#595)



Hi,
 
 Please update to the most recent version.
 
 Jared
