### ISSUE TITLE
Error with calculate_methylation_frequency.py

### ISSUE THREAD

**Issue by Hannah1746** [jts/nanopolish#597]
When I run this python script on my data I get this error. 

File "calculate_methylation_frequency.py", line 42, in <module>
    num_sites = int(record['num_motifs']) 
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Please help.

**Comment by jts** [comment]
Hi,

In recent versions of nanopolish the name of one of the columns in the methylation output files changed. I think you ran an old version of `call-methylation` but a new version of `calculate_methylation_frequency.py`.

Jared

**Comment by Hannah1746** [comment]
I used this one:
https://github.com/jts/nanopolish/blob/master/scripts/calculate_methylation_frequency.py

**Comment by jts** [comment]
Yes, that is the correct and up-to-date version - what version of `nanopolish` did you use to make calls?

**Comment by Hannah1746** [comment]
Oh sorry I didn't understand what you were saying. Where can I find the old version of calculate_methylation_frequency.py?

**Comment by jts** [comment]
https://github.com/jts/nanopolish/releases

**Comment by Hannah1746** [comment]
I have downloaded the last three updates. It is still not running and give the same error. The line num_sites = int(record['num_motifs']) is the problem.

**Comment by jts** [comment]
Sorry for the terse replies, I was in meetings the last few days. If you use this version it should work for you:

https://github.com/jts/nanopolish/blob/7612a4d28d0d4e3efbce5d849ef47ca8ca201522/scripts/calculate_methylation_frequency.py

I suggest updating nanopolish to the latest version and re-calling on your data though, the version you used to run `nanopolish call-methylaion` appears to be a bit old.
