### ISSUE TITLE
nanopolish variants extremely slow for intervals partially with Ns

### ISSUE THREAD

**Issue by wdecoster** [jts/nanopolish#598]
Not really a bug, merely an inconvenience:

To run nanopolish variants on a human genome I have split the genome into ~3200 parts (per 1Mb). That works great, but for some of these intervals, I notice that it takes lots longer than others. When I check those (e.g. GRCh38: chr16:46,000,000-47,000,000) in the UCSC genome browser it turns out that those intervals consist partially of `NNNN`s, e.g. a centromeric region.

I'm not sure if those NNNNNs are the cause, but it is unlikely to be a coincidence...

Let me know if there is something else you want me to test.

**Comment by jts** [comment]
Thanks, I'll make a note to look into this.

Jared

**Comment by jts** [comment]
Hi @wdecoster,

I've just looked at this region (finally, sorry), and I don't think nanopolish is doing anything unusual in regions of long Ns. The region downstream of the Ns appears to be quite repetitive and has high depth of MapQ=0 reads, which may be causing problems. I'm not sure I can do anything about that though, so I'm going to close this for now. Let me know if this is a major problem (e.g. you are stuck waiting days for this region to finish) and I can take a closer look.

Jared
