### ISSUE TITLE
index multi fast5 files

### ISSUE THREAD

**Issue by aspitaleri** [jts/nanopolish#599]
Hi there,
I converted to single fast5 files in order to use albacore 

_multi_to_single_fast5 --input_path fast5 --save_path fast5_single_
_read_fast5_basecaller.py --flowcell FLO-MIN106 --kit SQK-LSK108 --barcoding --output_format fastq --input fast5_single --save_path fastq --worker_threads 8 --recursive --reads_per_fastq_batch 0_

Then I got my fastq barcoded on which I did my minimap2 stuff as in https://github.com/jts/nanopolish/issues/320

Now in order to analyze my amplicon data to get the variants I need to generate the index files from my fast5 files and I in doubt how do it. Basically I need to run this command for each my barcoded fastq

for i in `seq 1 10`; do nanopolish index -d fast5_single BC$i; done

but, here it is the doubt, I need to use the fast5 single files converted or the fast5 multiple (the original one)?

Thanks
Best
Andrea

**Comment by jts** [comment]
Since you used the single fast5 files for basecalling you should probably index those.  It would probably work with the multi files too though.

Jared

**Comment by aspitaleri** [comment]
Thanks @jts . I will try. One more thing: the index has to be done per each fastq file, which are from the concatenation of the several fastq from the barcoding step, right? I am in new in nanopore technology and I want to be sure that I am doing right.
Best

**Comment by jts** [comment]
Yes, that's right. Feel free to re-open if you have other questions.
