### ISSUE TITLE
nanopolish index error

### ISSUE THREAD

**Issue by huangjianzuishuai** [jts/nanopolish#601]
Hi
I am executing nanopolish and ran into this error. nanopolish version 0.11.0

nanopolish index -d /fast5_pass/ -s summary.txt** reads.fastq

Error

kseq_read returned -2 indicating an error with the input file reads.fastq

For the fastq, I have filtered less than four lines and the third line is not the same length and number of bases.

Can you please help? Thank you.

**Comment by jts** [comment]
You have to fix your fastq file so that it is correctly formatted.

Jared

**Comment by huangjianzuishuai** [comment]
For the fastq，I I have already dealt with it.I have filtered less than four lines and the third line is not the same length and number of bases.but  i do not why？

**Comment by jts** [comment]
I can't help you with this, you need to find out why your fastqs are improperly formatted.
