### ISSUE TITLE
error rate analysis for indels and substitution following variant calling?

### ISSUE THREAD

**Issue by herrroaa** [jts/nanopolish#602]
Hi ,
Probably, this is not the right place to ask this question. However, I hope I can get some ideas.
How can I perform error rate analysis for indels and substitution following variant calling?

Thanks.
T

**Comment by jts** [comment]
Do you have a truth set of known variants?

**Comment by herrroaa** [comment]
yes, I have genotypes for 93 SNPs from illumina genotyping chip.

**Comment by jts** [comment]
Ok, I would calculate how often the genotype from nanopolish matches the genotype from the Illumina array.
