### ISSUE TITLE
Which type of fast5 file to use? 

### ISSUE THREAD

**Issue by jessydit** [jts/nanopolish#603]
Hi, I'm using nanopolish for the first time and I am a bit confused regarding the type of fast5 that is needed for the indexing/polishing procedure. There are the fast5 files originally created by the sequencer and a second set of fast5 files created by the albacore basecaller, together with the fastq files. Are these two sets of fast5 files identical? Which one do I need to use for nanopolish? Thanks for any help/clarification.

**Comment by jts** [comment]
Hi,

You should use the fast5s that are originally generated by the sequencer.

Jared
