### ISSUE TITLE
Update documentation to show support for fastq

### ISSUE THREAD

**Issue by Shians** [jts/nanopolish#604]
Currently in the call-methylation documentation

```
-r, --reads=FILE                     the ONT reads are in fasta FILE
-g, --genome=FILE                    the genome we are computing a consensus for is in FILE
```

but the `--reads` argument supports at least fasta, fastq and fastq.gz files. I think there is similar documentation in the other tools as well but I don't know if they have the same support. Also it would be nice to clarify that `--genome` is a fasta file (unless it also supports other formats).

**Comment by jts** [comment]
Thanks, I agree this should be fixed.

**Comment by jts** [comment]
Thanks, this is now fixed.
