### ISSUE TITLE
Position of CpG methylation calling on negative strand

### ISSUE THREAD

**Issue by Shians** [jts/nanopolish#605]
I am a bit confused about the position of the methylation call on negative strands when using `call-methylation`. I associated positions from the methylation calls with bases from the reference and every base is a `C`, I was under the impression that if read were on the negative strand, then the base at the location would be a `G` since the coordinates and reference are based on the positive strand and a `C` on the negative should correspond to a `G` on the positive.
```
TCGCGA - positive strand
||||||
AGCGCT - negative strand
```
Any idea why nanopolish would report the position as on a `C` regardless of strand?

**Comment by jts** [comment]
The convention we've used is to report the reference location of the CpG on the positive strand. I understand that this may be unintuitive but I'm reluctant to change it at this point unless there is a good argument against this convention.

**Comment by Shians** [comment]
I guess it's fine as long as it's intentional. I think that it's more intuitive to place it on the G as that's the actual physical location as per the diagram in my original post. I'm not experienced enough to know what the more common convention is, but at least Tombo uses the convention of actual location. It matters quite a bit when comparing methods in the Nanopore or bisulphite space.

**Comment by jts** [comment]
I'm going to close this but will consider changing this in the future when I re-visit the `call-methylation` output.
