### ISSUE TITLE
Readdb Error: no fast5 files found

### ISSUE THREAD

**Issue by Velastegui** [jts/nanopolish#606]
Hi!
I am using nanopolish 0.10.2, and Guppy basecalling files. My outputs are: .index, .index.fai, and .index.gzi , but I have got an error in the readdb indexing. The message looks like this:

```
nanopolish index -d ~/nanopolish/scripts/R_25/allFast5_R25.fast5 ~/nanopolish/scripts/R_25/R25_all.fastq
ls
allFast5_R25.fast5 R25_all.fastq R25_all.fastq.index R25_all.fastq.index.fai R25_all.fastq.index.gzi
[readdb] indexing /home/edgar/nanopolish/scripts/R_25/allFast5_R25.fast5
Error: no fast5 files found
```

Any suggestion will help.
Thanks!

**Comment by jts** [comment]
See here: https://github.com/jts/nanopolish/issues/574#issuecomment-497679748 (I saw that comment before this issue)

**Comment by aaronphillips7493** [comment]
Hey,

I am having the same problem. After running the command:

`nanopolish index -d /path/to/fast5/ /path/to/fastq`

I get the error:
`[readdb] indexing /path/to/fast5/
Error: no fast5 files found`

However, the directory is full of fast5 files, and I get the output files (.index, .index.fai, and .index.gzi) in the fastq directory. I'm not sure what's going on. Any ideas? I have a feeling it might have to do with the way my university has set up its HPC, but if you know of any work around for this error that is unrelated to that I would love to hear it.

Thanks,
Aaron :)

**Comment by aaronphillips7493** [comment]
Hey,

This is resolved - it was a quirk with the way the HPC at my university is set up. 

All sorted!

Thanks,
Aaron :)

**Comment by jts** [comment]
Glad to hear it, thanks for following up to let us know.

Jared
