### ISSUE TITLE
error: faidx could not get contig length for contig {1}

### ISSUE THREAD

**Issue by clcastr2** [jts/nanopolish#607]
I am having trouble getting nanopolish to work with amplicon data i have. I am attempting to create a consensus sequence with nanopolish variants. I tried with and with out --consensus option and receive errors such as the one listed above, Error: genome has multiple contigs or please use -w to specify input region. It is my first time using nanopolish and I am attempting to generate a consensus sequence to be further corrected and then used in determining the variants from my experiment. 

Commands i am attempting to use: 

get a .fa file from .bam 
samtools bam2fq BC1.bam | seqtk seq -A - > BC1_output.fa

./nanopolish index -d /home/fast5 -s /home/sequencing_summary.txt /home/file.fastq

python scripts/nanopolish_makerange.py ~/BC1_output.fa | parallel --results nanopolish.results -P 8 \
./nanopolish variants --consensus --reads /home/BC1.fastq --bam BC1.bam --genome output.fa -o snps.vcf

or 

./nanopolish variants -g /home/GCF_000146045.2_R64_genomic.fa -b /home/BC1.bam -r /home/BC1.fastq -w {1} -t 8 --ploidy 2

**Comment by jts** [comment]
For amplicon data you should not need to use `nanopolish_makerange.py` but use the -w parameter to tell nanopolish the amplicon region. Try something like this:

```
./nanopolish variants -g /home/GCF_000146045.2_R64_genomic.fa -b /home/BC1.bam -r /home/BC1.fastq -w "chr1:10,000-11,000" -t 8 --ploidy 2
```

but replace chr1:10,000-11,000 with the coordinates of the amplicon.

Jared

**Comment by clcastr2** [comment]
Jared,

I attempted this command that you suggested 

`./nanopolish variants -g /home/GCF_000146045.2_R64_genomic.fa -b /home/BC1.bam -r /home/BC1.fastq -w "chr1:560000-570000" -t 8 --ploidy 2`

and i received error: faidx could not get contig length for contig chr

How am i able to get the contig information and satisfy this error?

**Comment by jts** [comment]
Can you paste the exact error? It doesn't match the command you entered so it doesn't make sense to me.

**Comment by clcastr2** [comment]
'error: faidx could not get contig length for contig chr'

**Comment by jts** [comment]
Hmm, if you asked to polish `chr1:560000-570000` it shouldn't look for contig `chr`

**Comment by jts** [comment]
That looks like the cerevisae reference genome, where the contigs are named like this:

```
>NC_001133.9 Saccharomyces cerevisiae S288C chromosome I, complete sequence
>NC_001134.8 Saccharomyces cerevisiae S288C chromosome II, complete sequence
>NC_001135.5 Saccharomyces cerevisiae S288C chromosome III, complete sequence
>NC_001136.10 Saccharomyces cerevisiae S288C chromosome IV, complete sequence
>NC_001137.3 Saccharomyces cerevisiae S288C chromosome V, complete sequence
>NC_001138.5 Saccharomyces cerevisiae S288C chromosome VI, complete sequence
>NC_001139.9 Saccharomyces cerevisiae S288C chromosome VII, complete sequence
>NC_001140.6 Saccharomyces cerevisiae S288C chromosome VIII, complete sequence
>NC_001141.2 Saccharomyces cerevisiae S288C chromosome IX, complete sequence
>NC_001142.9 Saccharomyces cerevisiae S288C chromosome X, complete sequence
>NC_001143.9 Saccharomyces cerevisiae S288C chromosome XI, complete sequence
>NC_001144.5 Saccharomyces cerevisiae S288C chromosome XII, complete sequence
>NC_001145.3 Saccharomyces cerevisiae S288C chromosome XIII, complete sequence
>NC_001146.8 Saccharomyces cerevisiae S288C chromosome XIV, complete sequence
>NC_001147.6 Saccharomyces cerevisiae S288C chromosome XV, complete sequence
>NC_001148.4 Saccharomyces cerevisiae S288C chromosome XVI, complete sequence
>NC_001224.1 Saccharomyces cerevisiae S288c mitochondrion, complete genome
```

Maybe you meant `-w NC_001133.9:560,000-570,000`?

**Comment by clcastr2** [comment]
ok yes this did the trick. my results are now in /nanopolish.results/1/ and now there is 346 directories containing seq stderr and stdout. How do i go about obtaining my consensus for another re-alignment?

I am going to use 'nanopolish vcf2fasta -g draft.fa polished.*.vcf > polished_genome.fa' but i dont see any files with .vcf format that were created.

**Comment by jts** [comment]
Since you have a reference genome I don't think you need to obtain a consensus, just use the vcf file as your final output.

**Comment by clcastr2** [comment]
I would like to obtain a consensus sequence for a local re-alignment step, this should provide a higher overall alignment if i am not mistaken.  I do not see a vcf file output in the nanopolish directory.

**Comment by jts** [comment]
If you run the command you pasted above, it should output a vcf to stdout. You can redirect it to a file, or use the `-o output.vcf` option.

**Comment by clcastr2** [comment]
Ok i do not have a stdout but it did work using the -o option. After a quick look at my output.vcf there is no SNPs listed. The file has the header but there is no data generated below the tab separated headers.

**Comment by jts** [comment]
There should be a status line printed to stderr - can you paste it here? Are you running the command with `nanopolish_makerange` and `parallel`, or just on its own? I think you should just run it on its own, over a single amplicon region.

**Comment by clcastr2** [comment]
I am running it on its own with out either of the commands. 

the status line says 'variants: too many arguments'

**Comment by jts** [comment]
It didn't run correctly then. Please paste the full command you tried to run

**Comment by clcastr2** [comment]
`./nanopolish variants -g /home/GCF_000146045.2_R64_genomic.fa -b /home/BC1.bam -r /home/BC1.fastq -w "NC_001147.6:560000-570000" -t 8 --ploidy 2 -o output.vcf
`

**Comment by jts** [comment]
What command did you run when you got the VCF header?

**Comment by clcastr2** [comment]
I used head and more output.vcf and this is what was returned 
##fileformat=VCFv4.2
##nanopolish_window=NC_001147.6:560000-570000
##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">
##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">
##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">
##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">
##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample

**Comment by jts** [comment]
I think there's a bit of miscommunication here. You said above that you got an error ("too many arguments") when running the nanopolish command above. It looks like there is valid output (the VCF header) in output.vcf though, which implies the command-line arguments were OK and it ran correctly. Did you use the same command when it gave you "too many arguments" and when it produced a header in the VCF file?

**Comment by clcastr2** [comment]
Yes there was a miscommunication, i should have been more concise. 

I went to /nanopolish.results/1/ffa74b0f-4176-415a-8dc6-67407a007466:0-379/stderr which is a file containing one line that says too many arguments. I do not have a directory called stderr in /nanopolish.

**Comment by jts** [comment]
Ok, ignore the `nanopolish.results` directory entirely. You can delete it. It was generated by the `parallel` command you tried to run earlier. Now, try to run this command only:

```
./nanopolish variants -g /home/GCF_000146045.2_R64_genomic.fa -b /home/BC1.bam -r /home/BC1.fastq -w "NC_001147.6:560000-570000" -t 8 --ploidy 2 -o output.vcf
```

What happens?

**Comment by clcastr2** [comment]
I receive "[post-run summary] total reads: 341, unparseable: 0, qc fail: 0, could not calibrate: 8, no alignment: 10, bad fast5: 0"

**Comment by jts** [comment]
Ok, great. Everything ran to completion, but nanopolish found no variants in the region.

Jared

**Comment by clcastr2** [comment]
ok thank you for the conformation. 

I am attemtping to now create a polished amplicon using `nanopolish vcf2fasta --skip-checks -g draft.fa polished.vcf > polished_genome.fa`

the -g option is going to use my reference database, shouldnt i use a draft.fa amplicon sequence i generated and not the reference?
