### ISSUE TITLE
H5FD_sec2_open(): unable to open file

### ISSUE THREAD

**Issue by jadud** [jts/nanopolish#608]
Hi there,

first of all, thank you so much for nanopolish and the continuous support!

I have an issue with the final polishing step:

When using the following command:

python ~/projects/nanopolish/scripts/nanopolish_makerange.py ~/projects/canu-assembly/bwa/qtest.fasta | parallel --results ~/projects/nanopolish/nanopolish.results -P 8 \
   ~/projects/nanopolish/nanopolish variants --consensus -o polished.{1}.vcf -w {1} -r ~/projects/raw-reads/combined-reads.fastq -b ~/projects/canu-assembly/bwa/reads.sorted.bam -g ~/projects/canu-assembly/bwa/qtest.fasta -t 4 --min-candidate-frequency 0.1

I get this output:

[warning] fast5 file is unreadable and will be skipped: home/projects/raw-reads/fast5-pass/single_files/FAK51180_27085c0d8c1c2494d29b2c155f447e024cb68fce_66.fast5
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140208868460288:
  #000: H5F.c line 509 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1400 in H5F__open(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #002: H5Fint.c line 1546 in H5F_open(): unable to open file: time = Wed Jun  5 14:32:47 2019
, name = 'home/projects/raw-reads/fast5-pass/single_files/FAK51180_27085c0d8c1c2494d29b2c155f447e024cb68fce_66.fast5', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #003: H5FD.c line 734 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #004: H5FDsec2.c line 346 in H5FD_sec2_open(): unable to open file: name = 'home/projects/raw-reads/fast5-pass/single_files/FAK51180_27085c0d8c1c2494d29b2c155f447e024cb68fce_66.fast5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140208868460288:
  #000: H5L.c line 805 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 246 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140208868460288:
  #000: H5L.c line 805 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 246 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value

But the files are present and accessible. Any idea what the problem could be? Help is much appreciated!

Thank you, JD

**Comment by jts** [comment]
Hi,

Did you run live basecalling? Do you have files in a folder called `fast5_skip`?

Jared

**Comment by jadud** [comment]
Hi Jared, thanks for you response.

Yes we did live basecalling and there is a folder called `fast5_fail` but not `fast5_skip` .

Cheers,
JD

**Comment by jadud** [comment]
Hi again,

I found an old thread with a similar issue where re-compiling nanopolish resolved the issue. I also re-compiled nanopolish and now it works... awkward but it did the trick! Thank you again Jared.
