### ISSUE TITLE
wrong ftp url for ena ebi download

### ISSUE THREAD

**Issue by joachimwolff** [jts/nanopolish#610]
Hi, 

Using your documentation https://nanopolish.readthedocs.io/en/latest/quickstart_polya.html and the ftp download link: `wget ftp://ftp.sra.ebi.ac.uk/vol1/ERA158/ERA1580896/oxfordnanopore_native/30xpolyA.tar.gz -O 30xpolyA.tar.gz && mv 30xpolyA.tar.gz data/
` returns `No such directory ‘vol1/ERA158/ERA1580896/oxfordnanopore_native’.`

I think it should be: `ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR276/ERR2764784/30xpolyA.tar.gz `

Thanks for fixing it.

Best,

Joachim

**Comment by jts** [comment]
Thanks for the note @joachimwolff. @paultsw can you take a look?

**Comment by paultsw** [comment]
Hi @joachimwolff , you're right, that's the correct URL. I must have written the documentation using an older, deprecated URL when it was initially submitted. I've updated the documentation to reflect this.
