### ISSUE TITLE
vcf2fasta: no polishing windows found 

### ISSUE THREAD

**Issue by mmiladi** [jts/nanopolish#611]
Hi Jared,

I am upgrading the galaxy a test recipe from v 0.9 to the latest 0.11.1. Switching from the single step variants and fasta output to: 
`nanopolish variants -r reads.fasta -b reads.bam -g genome.fa -o variants.vcf --consensus  -w "tig00000001:200000-202000"` then  ` nanopolish vcf2fasta --skip-checks -g genome.fa variants.vcf > polished.fa` 
fails with the following stderr:
```
readdb] indexing fast5_files/
[readdb] num reads: 112, num reads with path to fast5: 112
[post-run summary] total reads: 101, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 0
[vcf2fasta] rewrote contig tig00000001 with 0 subs, 0 ins, 0 dels (0 skipped)
error: no polishing windows found for tig00000005
```
Is running with -w option over multi-sequence input an unexpected procedure?

Thanks,
Milad

**Comment by jts** [comment]
The polishing workflow (`variants --consensus` followed by `vcf2fasta`) assumes that you want to polish the whole genome. It checks that the polishing is complete (the entire genome is contained in a window)  in case one of the windows failed. In case the user wants to do something different we provide `--skip-checks` to disable this but it looks like I missed the case where a contig has no windows at all (https://github.com/jts/nanopolish/blob/master/src/nanopolish_vcf2fasta.cpp#L181). This should be a straightforward fix, I'll try to push it a bit later.

**Comment by jts** [comment]
I've just pushed a fix, can you test if it fixes the issue for you?

**Comment by mmiladi** [comment]
The test procedure works only with the conda installation. For the moment I pruned the test by excluding other contigs.

**Comment by mmiladi** [comment]
Also I tried with installing the github version. Though in the first tries I had difficulties with installing correct dependencies. `./src/nanopolish_extract.h:12:21: fatal error: fast5.hpp: No such file or directory`

**Comment by jts** [comment]
I had mistakenly broken the github version for about an hour while trying to update `htslib` for another issue - can you try again? (`fast5.hpp` should be pulled in with `git clone --recursive [...]` anyway though)

**Comment by mmiladi** [comment]
This issue is fixed.
