### ISSUE TITLE
Use <algorithm> rather than <bits/stl_algo.h>

### ISSUE THREAD

**Issue by Shians** [jts/nanopolish#612]
[Here](https://github.com/jts/nanopolish/blob/b9dc627e73816a415e4b96b14e8a8bf53622a6c9/src/pore_model/nanopolish_poremodel.cpp#L13) the library `<bits/stl_algo.h>` is included for, I assume, the standard library algorithms. But as far as I can tell this is meant to be used by GCC internally and not very portable. I've tried changing it to `<algorithm>` and the code still compiles, so I assume it is a portable and equivalent solution.

**Comment by jts** [comment]
Thanks for noting this, the include is not necessary so I have removed it.
