### ISSUE TITLE
RNA kit 002 + guppy

### ISSUE THREAD

**Issue by mmiladi** [jts/nanopolish#615]
Hello again,

As a follow up to this https://github.com/jts/nanopolish/issues/545, I wanted to ask about the current state of nanopolish for supporting data with RNA kit 002 and Guppy. 

- Is `polya` expected to work with this setup?
- Does nanopolish methylation support this setup (or RNA reads at all)?

Thanks much,
Milad

**Comment by jts** [comment]
`polya` should work with RNA002 and Guppy. We don't have methylation models for RNA yet.
