### ISSUE TITLE
Nanapolish indexing with errors

### ISSUE THREAD

**Issue by utritala** [jts/nanopolish#617]
Hi, 

I have been trying to run nanopolish (version 0.11.1) to correct a draft assembly generated from some PromethION data using Flye. When I try to run polishing step like below: 

`Python-2.7.14/bin/python nanopolish/scripts/nanopolish_makerange.py assembly.fasta | parallel --results nanopolish.results -P 16 nanopolish/nanopolish variants --consensus -o polished.{1}.vcf -w {1} -r Lib1.fastq -b minimap2_to_flye_sorted.bam -g assembly.fasta -t 10 --min-candidate-frequency 0.1`

Although it starts generating some output files, it also throws an error saying: 

> Please run nanopolish index on your reads (see documentation)
> error: could not load the index files for input file Lib1.fastq

Hence, I tried to generate the indexed files for these with following commands: 
`nanopolish/nanopolish index -d Lib1/fast5_pass/  Lib1_pass.fastq`

It seems like this step generated the indexing files "Lib1.index.fai and Lib1.index.gzi" but there are some error messages saying: 

> couldn't open fast5 files: 
> Error: no fast5 files found

I can see all the files are there and also I checked the md5sums for the fast5 files on the sequencer and on the storage where they were copied and they match. I saw this error has been reported by many users earlier but none of the solutions works for me. I would be very grateful if someone could shed some light on this. 

Many thanks.

**Comment by jts** [comment]
Hi,

Can you send the exact error messages (what is printed after `couldn't open fast5 files:`)?

Jared

**Comment by utritala** [comment]
Hi Jared,

Thanks for your prompt response. I have 1674 fast5 files in the directory fast5_pass. So, there are same number of lines saying none of these files can be opened and the last line after `Couldn't open fast5 files `says : `Error: no fast5 files found`.  For example:

`could not open fast5 file: Lib1/fast5_pass//PAD59570_3996998bd4376118a891932f7bdb76cc4535f3b3_474.fast5`
`could not open fast5 file: Lib1/fast5_pass//PAD59570_3996998bd4376118a891932f7bdb76cc4535f3b3_592.fast5`
`could not open fast5 file: Lib1/fast5_pass//PAD59570_3996998bd4376118a891932f7bdb76cc4535f3b3_602.fast5`
`could not open fast5 file: Lib1/fast5_pass//PAD59570_3996998bd4376118a891932f7bdb76cc4535f3b3_1084.fast5`
`could not open fast5 file: Lib1/fast5_pass//PAD59570_3996998bd4376118a891932f7bdb76cc4535f3b3_950.fast5`
`could not open fast5 file: Lib1/fast5_pass//PAD59570_3996998bd4376118a891932f7bdb76cc4535f3b3_185.fast5`
`could not open fast5 file: Lib1/fast5_pass//PAD59570_3996998bd4376118a891932f7bdb76cc4535f3b3_408.fast5`
`could not open fast5 file: Lib1/fast5_pass//PAD59570_3996998bd4376118a891932f7bdb76cc4535f3b3_376.fast5`
`could not open fast5 file: Lib1/fast5_pass//PAD59570_3996998bd4376118a891932f7bdb76cc4535f3b3_758.fast5`
`Error: no fast5 files found`

**Comment by jts** [comment]
Can you run `strace nanopolish/nanopolish index -d Lib1/fast5_pass/ Lib1_pass.fastq` and send a bit of the output? I suspect this is the same issue another user reported and want to confirm.

Jared

**Comment by jts** [comment]
I've just pushed a new version to github, can you try it and let me know if it fixed the "could not open" issue?

**Comment by utritala** [comment]
Hi Jared,

Thanks for your help. The output from strace command is given at the link below
https://drive.google.com/file/d/1crMdIu_HopE4IqNu-R9nRRb1dqcmi9pA/view

I have obtained the latest version and its running at the moment. I will update as soon as I have some results.

**Comment by utritala** [comment]
The newer version still gives the same "Couldn't find files errors".

**Comment by jts** [comment]
Couldn't find or couldn't open?

**Comment by utritala** [comment]
Sorry, I mean't could not open fast5 errors.

**Comment by jts** [comment]
Looking at the strace you provided above, this error should have been fixed with the new version. Can you try to delete your entire nanopolish directory and re-clone from github? I think the old version of hdf5 is still hanging around so it didn't properly update.

**Comment by utritala** [comment]
Thanks Jared. I will give that a go and let you know how I get on.

**Comment by utritala** [comment]
Hi Jared,
It worked! No errors anymore. Thanks a lot for your help. 
Cheers,
Urmi
