### ISSUE TITLE
Is resquiggle necessary (or redundant)?

### ISSUE THREAD

**Issue by Blosberg** [jts/nanopolish#618]
Hi Jared. Thanks again for this resource. I have a question about current values for RNA transcripts.

I use nanopolish to index fast5 data with respect to the base-called reads, and then minimap2  to align the (spliced) reads to the reference. Since these base-calls are susceptible to error from the very modifications we are trying to detect (i.e. they assume canonical bases) the “events” that delineate them must be redefined (like tombo's  `re-squiggle`) --otherwise, non-canonical bases might be squeezed in with their neighbours, as they are “made to fit” with presumptive canonical-base sequences. Is nanopolish doing this, or are the base-calling events still “baked in”.

I ask for two reasons: (1) the base-called read is being used explicitly as an input, and (2) Tombo’s “resquiggle” command (which does this) requires a reference transcriptome to avoid the complications of spliced alignment. I can easily run “resquiggle” on my fast5 data with the reference transcriptome directly, but I don’t see any way to tell nanopolish to look for the resulting `.tombo.index` file, so I’m assuming nanopolish does something analogous on its own. 

Should I be doing a resquiggle? ( or aligning to the transcriptome without splicing)?

**Comment by jts** [comment]
Hi Bren,

Event detection is performed independently of the models and basecalls so you shouldn't have to redefine events. When you align events to the reference (`nanopolish eventalign`) it does rely on the canonical models, so is susceptible to misaligning events from modified bases.
 
Nanopolish doesn't support .tombo files, so you won't be able to use those. You can align reads to the transcriptome and use the unspliced alignments though, that is fine.

I hope this helps,
Jared

**Comment by Blosberg** [comment]
Hi Jared.
Yes, that does clarify things. I'll use the transcriptome for alignment. Thanks!
