### ISSUE TITLE
bad fast5 call_methylation

### ISSUE THREAD

**Issue by Genereneg** [jts/nanopolish#619]
Howdy,

Following up on email.

-the type of sequencing performed (e.g. genomic DNA using LSK-109 on the MinION):

**1D SQK-LSK108 on MinION (mammalian genomic DNA)**

-the version of the basecaller used:

**guppy 2.3.1 flipflop (dna_r9.4.1_450bps_flipflop.cfg)**

-the complete list of commands run:

[agener@sphere xmas_nanopolish_trial]$ head *mito.sh
==> meth_xmas_mito.sh <==
#!/bin/sh

#SBATCH -c1 -n24 -p longjob -t 6-00:00:00

srun -c1 -n24

**~/nanopolish/nanopolish call-methylation -t 48 -r ~/xmas_nanopolish_trial/Galaxy877-[Collapse_on_data_870].fasta -b xmas_mito.sorted.bam -g ~/xmas_nanopolish_trial/CM004184.1.fasta > methylation_calls_xmas_mito.tsv**

==> minimap2toref_xmas_mito.sh <==
#!/bin/sh

#SBATCH -c1 -n24 -p longjob -t 6-00:00:00

srun -c1 -n24

**~/minimap2/minimap2 -a -x map-ont ~/xmas_nanopolish_trial/CM004184.1.fasta ~/xmas_nanopolish_trial/Galaxy877-\[Collapse_on_data_870\].fasta | /usr/local/bin/samtools sort -T tmp -o xmas_mito.sorted.bam 
/usr/local/bin/samtools index xmas_mito.sorted.bam**

==> preprocessing_xmas_mito.sh <==
#!/bin/sh

#SBATCH -c1 -n24 -p longjob -t 6-00:00:00

srun -c1 -n24

**~/nanopolish/nanopolish index -d ~/xmas_nanopolish_trial/Users/alejandrogener/Desktop/fast5_all/unsorted_all.fast5/ ~/xmas_nanopolish_trial/Galaxy877-\[Collapse_on_data_870\].fasta**

#did that for mito and for a smaller target, and same errors. 

-the output of each command (as you've already included)

**[agener@sphere xmas_nanopolish_trial]$ head slurm-198346.out slurm-198347.out slurm-198348.out
==> slurm-198346.out <==
srun: fatal: No command given to execute.
[readdb] indexing /home/agener/xmas_nanopolish_trial/Users/alejandrogener/Desktop/fast5_all/unsorted_all.fast5/
could not open fast5 file: /home/agener/xmas_nanopolish_trial/Users/alejandrogener/Desktop/fast5_all/unsorted_all.fast5//slurm-198213.out
could not open fast5 file: /home/agener/xmas_nanopolish_trial/Users/alejandrogener/Desktop/fast5_all/unsorted_all.fast5//slurm-198214.out
[readdb] num reads: 358041, num reads with path to fast5: 159818

==> slurm-198347.out <==
srun: fatal: No command given to execute.
[M::mm_idx_gen::0.0031.51] collected minimizers
[M::mm_idx_gen::0.0072.31] sorted minimizers
[M::main::0.0072.29] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.0082.21] mid_occ = 2
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.0082.09] distinct minimizers: 3012 (100.00% are singletons); average occurrences: 1.000; average spacing: 5.412
[M::worker_pipeline::4.4922.10] mapped 198223 sequences
[M::main] Version: 2.15-r913-dirty
[M::main] CMD: /home/agener/minimap2/minimap2 -a -x map-ont /home/agener/xmas_nanopolish_trial/CM004184.1.fasta /home/agener/xmas_nanopolish_trial/Galaxy877-[Collapse_on_data_870].fasta

==> slurm-198348.out <==
srun: fatal: No command given to execute.
[post-run summary] total reads: 720, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 708
[agener@sphere xmas_nanopolish_trial]$**

Giving an empty methylation.tsv. Was thinking that it was a coverage problem, so shifted to mito (has coverage around 90x), and still most of the reads come back as "bad."

Ignoring the nonsense srun and superfluous files in the fast5 folder.

Suggestions?

Thanks again!

**Comment by jts** [comment]
What does **Galaxy877-[Collapse_on_data_870** mean? The output of the basecaller should be a fastq file. Did you do anything to the reads after basecalling? 

The output of nanopolish index suggests it only found a fast5 file for half of your reads, which suggests there is a mismatch between the fasta and the fast5 files.

**Comment by Genereneg** [comment]
The “Galaxy” bit is a de-duplicated set of fastq. When I tried to run before, it let me know that there was at least one duplicated read, and I couldn’t track down what was duplicated. The Galaxy set should be all reads that were counted at least once. I’ll check input again.

**Comment by jts** [comment]
I suspect that galaxy step is the problem.

**Comment by jts** [comment]
Closing this, please re-open if there is anything else I can help with.
