### ISSUE TITLE
Error: nanopolish_profile_hmm.cpp

### ISSUE THREAD

**Issue by jaesvi** [jts/nanopolish#62]
Hi Jared,
I am running Nanopolish using some R7 2D pass reads. I have 608 partitions, all of which worked correctly except for 1, that fails with error:
`nanopolish: src/hmm/nanopolish_profile_hmm.cpp:151: std::vector<HMMAlignmentState> profile_hmm_align(const HMMInputSequence&, const HMMInputData&, uint32_t): Assertion 'get(vm, row, col) != -(__builtin_inff())' failed.
Aborted`

I have checked the contig that is referred in this partition in both the FASTA and the BAM file and I cannot find what is causing the error. Any hints on where to look?
Thanks a lot,
Jose

**Comment by jts** [comment]
Hi,

This probably indicates that some bad data was passed to the HMM, like a read with an empty range of events. Could you try to catch the error in gdb and provide a stack trace? What git commit are you running?

**Comment by jts** [comment]
I'm closing because I didn't hear back, feel free to reopen if you have more information.
