### ISSUE TITLE
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140621515970304

### ISSUE THREAD

**Issue by sangeet2019** [jts/nanopolish#620]
Hello, 
i have been getting the error below. I saw that similar issues were reported before, and the solution for such issues were to update the nanopolish version. I am using v0.11.01, but not sure why I get such errors. Any suggestion would be greatly appreciated,

HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140621515970304:
  #000: H5L.c line 815 in H5Lexists(): unable to get link info
    major: Links
    minor: Can't get value
  #001: H5L.c line 3095 in H5L__exists(): path doesn't exist
    major: Links
    minor: Object already exists
  #002: H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #003: H5Gtraverse.c line 741 in H5G__traverse_real(): component not found
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140621515970304:
  #000: H5L.c line 815 in H5Lexists(): unable to get link info
    major: Links
    minor: Can't get value
  #001: H5L.c line 3095 in H5L__exists(): path doesn't exist
    major: Links
    minor: Object already exists
  #002: H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #003: H5Gtraverse.c line 741 in H5G__traverse_real(): component not found
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140621515970304:
  #000: H5G.c line 470 in H5Gopen2(): unable to open group
    major: Symbol table
    minor: Can't open object
  #001: H5Gint.c line 318 in H5G__open_name(): group not found
    major: Symbol table
    minor: Object not found
  #002: H5Gloc.c line 422 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: H5Gtraverse.c line 741 in H5G__traverse_real(): component not found
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140621515970304:
  #000: H5D.c line 292 in H5Dopen2(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #001: H5Dint.c line 1205 in H5D__open_name(): not found
    major: Dataset
    minor: Object not found
  #002: H5Gloc.c line 422 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: H5Gtraverse.c line 741 in H5G__traverse_real(): component not found
    major: Symbol table
    minor: Object not found
nanopolish: src/nanopolish_squiggle_read.cpp:321: void SquiggleRead::load_from_raw(fast5_file&, uint32_t): Assertion `rt.n > 0' failed.
Aborted (core dumped)

**Comment by jts** [comment]
Hi,

Can you provide a .fast5 file that demonstrates the problem?

Thanks,
Jared

**Comment by sangeet2019** [comment]
Hi Jared,

Thanks for the super quick response.

I attach one of the .fast5 file  it reports to be problematic

Regards
Sangeet

 FAK64794_7e8f815a965cae4341431b4bcde720cf045987...
<https://drive.google.com/file/d/1u9xqSjmifxsOdmqe7nZUt9wDhm4Nk9YX/view?usp=drive_web>

**Comment by jts** [comment]
Hi,

This fast5 works for my local version when basecalled with guppy. I suspect the problem may be the basecaller. Could you upload also the fastq file you used?

Jared

**Comment by sangeet2019** [comment]
I have used guppy for basecalling as well. The nanopolish indexing and read mappings run smooth. These error arise only at Nanopolish variants step.

**Comment by jts** [comment]
Can you confirm this particular file has the problem? What reference genome should I map to?

I’m traveling the next few days but will keep looking into it when I can.

**Comment by jonaudet** [comment]
Hi @sangeet2019,
I stumbled on this issue after having the same problem. For me the issue was that I followed ONT's recommendation and re-basecalled both failed and passed reads (which are kept in separate folders). When guppy writes to sequencing_summary.txt, it writes the file name, but no path whatsoever. Because the files are in different folders all the names of the failed fast5 files also exist as passed files.
I copied both sets into one folder, renaming the files to failed.{filename} and pass.{filename}, re-basecalled (so sequencing_summary.txt has the new names) and pointed nanopolish to this combined fast5 folder. It worked fine.

**Comment by jts** [comment]
Hi @jonaudet and @sangeet2019,

I have just pushed a workaround for this problem in 5d6fa83. Nanopolish will now detect name clashes in the summary file, and ignore the conflicting information. This is a temporary fix as ONT has told me they are going to change MinKNOW to output unique fast5 names in a future release.

Jared

**Comment by jts** [comment]
Have you installed the VBZ decompression plugin?

**Comment by jackzhong1995** [comment]
> Hi Jared,
> 
> thanks for the quick response. I installed nanopolish and minimap2. I did not need VBZ in previous studies. what ı need to do fi it?

You can install it by this way "conda install -c bioconda ont_vbz_hdf_plugin"

**Comment by Fatihlrcfs** [comment]
hi Jared,
thanks for your response. best

**Comment by Hassannawazish** [comment]
I am trying to read a .h5 file and got this error.

HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 139840384053824:
  #000: ../../../src/H5D.c line 292 in H5Dopen2(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #001: ../../../src/H5Dint.c line 1205 in H5D__open_name(): not found
    major: Dataset
    minor: Object not found
  #002: ../../../src/H5Gloc.c line 422 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: ../../../src/H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: ../../../src/H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #005: ../../../src/H5Gloc.c line 378 in H5G__loc_find_cb(): object 'dataset' doesn't exist
    major: Symbol table
    minor: Object not found
terminate called after throwing an instance of 'H5::FileIException'
./script.sh: line 4: 140496 Aborted                 (core dumped) ./converter

**Comment by AndreaYCT** [comment]
Hi, 

I have the similar error when running eventalign.

Here is the code to run 
`nanopolish eventalign --reads /staging/biology/andreachi77/guppyv6.1.2/STM2457_1uM.fastq \
--bam  /staging/biology/andreachi77/guppyv6.1.2/STM2457_1uM.bam \
--genome /staging/biology/andreachi77/MOP2/anno/Human.v41CRCh38.p13.transcripts.fa \
--scale-events \
--summary STM2457_1uM_summary.txt \
--signal-index \
--threads 56  > STM2457_1uM_eventalign.txt`

Here are errors:
[readdb] indexing /staging/biology/andreachi77/guppyv6.1.2/NoTreat_basecalled_fast5
[readdb] indexing /staging/biology/andreachi77/guppyv6.1.2/NoTreat_basecalled_fast5/workspace_fail
[readdb] indexing /staging/biology/andreachi77/guppyv6.1.2/NoTreat_basecalled_fast5/pass
[readdb] indexing /staging/biology/andreachi77/guppyv6.1.2/NoTreat_basecalled_fast5/workspace
[readdb] indexing /staging/biology/andreachi77/guppyv6.1.2/NoTreat_basecalled_fast5/fail
[readdb] num reads: 787838, num reads with path to fast5: 787838
HDF5-DIAG: Error detected in HDF5 (1.10.6) thread 47813602129664:
  #000: H5Dio.c line 199 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: H5Dio.c line 603 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: H5Dchunk.c line 2293 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: H5Dchunk.c line 3658 in H5D__chunk_lock(): data pipeline read failed
    major: Dataset
    minor: Filter operation failed
  #004: H5Z.c line 1301 in H5Z_pipeline(): required filter 'vbz' is not registered
    major: Data filters
    minor: Read failed
  #005: H5PLint.c line 270 in H5PL_load(): search in path table failed
    major: Plugin for dynamically loaded library
    minor: Can't get value
  #006: H5PLpath.c line 604 in H5PL__find_plugin_in_path_table(): search in path /opt/ohpc/Taiwania3/pkg/biology/Nanopolish/Nanopolish_v0.13.2/lib/hdf5/plugin encountered an error
    major: Plugin for dynamically loaded library
    minor: Can't get value
  #007: H5PLpath.c line 656 in H5PL__find_plugin_in_path(): can't open directory: /opt/ohpc/Taiwania3/pkg/biology/Nanopolish/Nanopolish_v0.13.2/lib/hdf5/plugin
    major: Plugin for dynamically loaded library
    minor: Can't open directory or file

It gives an empty eventalign.txt and summary.txt. It can keep going to m6anet data prep but i guess it will be impossible to finish running. 

Is there anything I should fix? 
many thanks!

**Comment by jts** [comment]
Please see here: https://github.com/jts/nanopolish/issues/1065#issuecomment-1449405646

**Comment by AndreaYCT** [comment]
> Please see here: [#1065 (comment)](https://github.com/jts/nanopolish/issues/1065#issuecomment-1449405646)

Thanks! but I still got some errors:
  #000: H5Dio.c line 199 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: H5Dio.c line 603 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: H5Dchunk.c line 2293 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: H5Dchunk.c line 3658 in H5D__chunk_lock(): data pipeline read failed
    major: Dataset
    minor: Filter operation failed
  #004: H5Z.c line 1301 in H5Z_pipeline(): required filter 'vbz' is not registered
    major: Data filters
    minor: Read failed

**Comment by AndreaYCT** [comment]
@jts 

It worked. Solution was found in https://github.com/jts/nanopolish/issues/932

Thanks for everything!

Best, 

ANdrea

> > Please see here: [#1065 (comment)](https://github.com/jts/nanopolish/issues/1065#issuecomment-1449405646)
> 
> Thanks! but I still got some errors: #000: H5Dio.c line 199 in H5Dread(): can't read data major: Dataset minor: Read failed #1: H5Dio.c line 603 in H5D__read(): can't read data major: Dataset minor: Read failed #2: H5Dchunk.c line 2293 in H5D__chunk_read(): unable to read raw data chunk major: Low-level I/O minor: Read failed #3: H5Dchunk.c line 3658 in H5D__chunk_lock(): data pipeline read failed major: Dataset minor: Filter operation failed #4: H5Z.c line 1301 in H5Z_pipeline(): required filter 'vbz' is not registered major: Data filters minor: Read failed
