### ISSUE TITLE
Nanopolish_makerange: permission denied

### ISSUE THREAD

**Issue by Velastegui** [jts/nanopolish#621]

**Comment by jts** [comment]
I see you edit the issue to be blank, does that mean I can close it?

**Comment by Velastegui** [comment]
Yes, thank you!

________________________________
De: Jared Simpson <notifications@github.com>
Enviado: miércoles, 19 de junio de 2019 14:13
Para: jts/nanopolish
Cc: Velastegui; Author
Asunto: Re: [jts/nanopolish] Nanopolish_makerange: permission denied (#621)


I see you edit the issue to be blank, does that mean I can close it?

**Comment by jts** [comment]
Thanks
