### ISSUE TITLE
methyltrain outputs empty model

### ISSUE THREAD

**Issue by bs2810** [jts/nanopolish#622]
Hello everyone,

I'm trying to run nanopolish methyltrain and it reports no error so it's a little bit hard to figure out what is not working. 

The script takes about 2 min to run and the output I get is empty .tmp.model.roundX.events.tsv files. Similarly the summary file gives me num_matches, num_skips, num_stays, num_events_for_training and was_trained as 0 for each kmer. Any idea what could be wrong?

I prepared reduced fasta files including only reads that I want to train on, sorted bam file including the same reads and .bai file.  I also prepared the files and models. I also ran the nanopolish index and then I run the following command:

`  nanopolish/nanopolish methyltrain -t 1 --train-kmers all -out-fofn tmp.fofn --out-suffix .tmp.model -m ont.unmet_alphabet.fofn -b data.bam -r data.fa -g reference_genome.fa --filter-policy R9.4 "gi|556503834|ref<NC_000913.3|:0-248956422" `

Another error that I get when I try to leave out the training region is: 

`  nanopolish: src/nanopolish_methyltrain.cpp:356: void add_aligned_events(...): Assertion 'training_k==sr.get_model_k(strand_idx)' failed. Aborted (core dumped).`

Many thanks!

**Comment by jts** [comment]
Hi,

How did you prepare the model file?

Jared

**Comment by bs2810** [comment]
I was following the methyltrain makefile and used the template files provided in the methylation-analysis pipe and inserted as header model_name, type, kit and strand. 

Then I made the 5mer model from those files using nanopolish/scripts/dropmodel.py and created a file with the name of all the models to feed the methyl train command.

**Comment by jts** [comment]
Can you try with a 6-mer model instead of 5-mer?

**Comment by bs2810** [comment]
I have tried that, Then I have a model file looking like this:

```
#ont_model_name     r9.4_180mv_450bps_6mer
#kit     r9.4_450bps
#strand     template
#k     6
#original_file     r9.4_180mv_450bps_6mer/template_median68pA.model
kmer      level_mean     level_stdv     sd_mean     sd_std     weight
#alphabet    cpg
AAAAAA     86.486336     1.517846     0.941478     0.609357     4739.559092
AAAAAC     83.948839     1.517846     1.07051     0.745608     3403.762207
AAAAAG     85.475368     1.517846     0.953434     0.621001     3553.658043
AAAAAM     83.948839     2.517846     1.07051     0.745608     3403.762207
AAAAAT     84.423907     1.517846     1.106077     0.775951     3909.663587
...
```

I run methyltrain the same way as before and the output are 5 methyltrain.tmp.model.roundX.events.tsv files which are all empty files looking like this (containing no other lines):
```
model     model_kmer     level_mean     level_stdv     scaled_read_var     read_scale_sd     read_var_sd
```

**Comment by jts** [comment]
Ok, it looks like it didn't find any aligned events for the specified training region. If you run `nanopolish eventalign` with the same input data, does it write aligned events to stdout?

**Comment by bs2810** [comment]
Yes you are correct, the region was the problem and when I changed the region I also noted that there was a problem with my fasta index file. I had to re-index the file and change the region and now I get non-empty models. Thanks!

**Comment by jts** [comment]
Great, thanks for following up. I'm currently working on rewriting the model training subprogram to hopefully make it more intuitive and easier to run.

**Comment by bs2810** [comment]
Great, that would be very helpful!

One question just to clarify, in the Supplementary Note you say that you train using both types of data (methylated and unmethylated) over both the nucleotide and CpG alphabet, generating four combinations of data type/alphabet: met_nucleotide,  met_cpg, unmet_nucleotide and unmet_cpg.

I lift the reference genome to CpG alphabet, should I also do so for the methylated and unmethylated reads when training against the methylated reference genome or keep them in the four base nucleotide alphabet?

**Comment by jts** [comment]
You don't need to modify the reads, nanopolish only uses the reference sequence (with M symbols) for training.

**Comment by bs2810** [comment]
Perfect, then I should be performing the training correctly. 
Many thanks for the fast replies!
