### ISSUE TITLE
Haplotype::substr_by_reference error

### ISSUE THREAD

**Issue by johnomics** [jts/nanopolish#623]
I just had two ranges fail with the same error, running nanopolish v0.11.0 with "-q dcm,dam --fix-homopolymers --consensus --min-candidate-frequency 0.1" on a de novo canu assembly using Guppy 3.1.5 MinION reads from a Circulomics library:
```
[haplotype-debug] ctg: tig00003605, position: 749960
[haplotype-debug] r-sequence: AAAGTGCGCCGAGCTCGA...
[haplotype-debug] h-sequence: AAAGTGCGCCGAGCTCGA...
nanopolish: src/nanopolish_haplotype.cpp:113: Haplotype Haplotype::substr_by_reference(size_t, size_t) const: Assertion `derived_base_end != m_coordinate_map.size()' failed.
```

```
[haplotype-debug] ctg: tig00000209, position: 349960
[haplotype-debug] r-sequence: GCCGCGTTTCCGACGACA...
[haplotype-debug] h-sequence: GCCGCGTTTCCGACGACA...
nanopolish: src/nanopolish_haplotype.cpp:113: Haplotype Haplotype::substr_by_reference(size_t, size_t) const: Assertion `derived_base_end != m_coordinate_map.size()' failed.
```

These are both from the second-to-last ranges for each of these contigs:
tig00003605:700000-750200
tig00003605:750000-773220
tig00000209:300000-350200
tig00000209:350000-384398

Here are the nanopolish logs for these ranges, including the full haplotype sequences:
[slurm-nanopolish-consensus-3076881_205.out.txt](https://github.com/jts/nanopolish/files/3359323/slurm-nanopolish-consensus-3076881_205.out.txt)
[slurm-nanopolish-consensus-3076881_319.out.txt](https://github.com/jts/nanopolish/files/3359324/slurm-nanopolish-consensus-3076881_319.out.txt)

The tig00000209 haplotype is 34440bp long; if it starts at 349960, this would take it to 384400bp, 2bp beyond the end of the contig at 384398.

Similarly, the tig00003605 haplotype is 23262bp long; if it starts at 749960, it ends at 773222bp, 2bp beyond the end of the contig at 773220.

Both of these haplotypes end with telomere sequence so the contig ends are probably chromosome ends.

Please could you look into this?

**Comment by jts** [comment]
Does the error only occur with the --fix-homopolymers option? 

Could you run our debug script [here](https://nanopolish.readthedocs.io/en/latest/debug.html#usage-example) to extract the data I'll need to reproduce this?

Thanks,
Jared

**Comment by johnomics** [comment]
Thanks for the quick response - these samples have the same error:
https://drive.google.com/open?id=17QbNI7OsEoHk1vJgtj4RBw4yjX0NtmuI

I ran them like this:
```
tig00000209_haplotype_error $ nanopolish index -d fast5_files reads.fasta
tig00000209_haplotype_error $ nanopolish variants --consensus --fix-homopolymers -r reads.fasta -b reads.bam -g draft.fa -o tig00000209.vcf -w tig00000209:349000-384398 -t 10 -m 0.1
```

```
tig00003605_haplotype_error $ nanopolish index -d fast5_files reads.fasta
tig00003605_haplotype_error $ nanopolish variants --consensus --fix-homopolymers -r reads.fasta -b reads.bam -g draft.fa -o tig00003605.vcf -w tig00003605:749000-773220 -t 10 -m 0.1
```

I've tried the tig00003605 sample without --fix-homopolymers and get the same error. (Forgot to add methylation options here but it looks like that's not the problem.)

Thanks
John

**Comment by johnomics** [comment]
Sorry, link should be available now.

**Comment by jts** [comment]
Thanks, downloading now.

**Comment by jts** [comment]
I'm able to reproduce the problem here and am looking at it now.

**Comment by jts** [comment]
I think I've fixed this, can you try again?

**Comment by johnomics** [comment]
I've run the two samples using the latest commit and both worked fine. Thank you very much!

**Comment by jts** [comment]
Great, thanks for the report and for providing data to reproduce the error.
