### ISSUE TITLE
High proportion of reads with no alignment

### ISSUE THREAD

**Issue by samstu** [jts/nanopolish#625]
Hi Jared,

I'm running nanopolish on a couple of old-ish (early 2018) data sets generated from amplicons and am getting a lot of reads with no alignment. I'm basecalling with Guppy, demultiplexing with qcat, aligning to a reference with bwa mem, calling a draft, indexing the demultiplexed fastq files (all reads found and indexed, no errors), aligning the indexed reads to the draft, and running variants:

nanopolish variants -p 1 -t 20 --reads /full/path/to/barcode11.fastq --bam /full/path/to/primerclipped.bam --genome /full/path/to/draft.fasta > /full/path/to/polished.vcf
[fai_load] build FASTA index.
Number of variants in span (25) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
[post-run summary] total reads: 25385, unparseable: 0, qc fail: 567, could not calibrate: 10, no alignment: 17740, bad fast5: 0

I'm seeing the same issue on all of the barcodes on both runs (tried it with and without soft-clipping the primers as well but it gave the same output). It hasn't been happening with more recent runs so it may be something related to the older run/fast5s?

I've seen a couple of other people reporting similar issues but they seem to have been user specific, any chance you could take a look?

If so, let me know what you'd need and I will get it over to you.

Cheers,

Sam

**Comment by jts** [comment]
Hi Sam,

I agree that is an unusually high proportion of unaligned reads. Could you send me a subset of fast5s (enough for ~200x coverage of the genome), the `barcode11.fastq`, `primerclipped.bam` and `draft.fasta` files?


Thanks,
Jared

**Comment by samstu** [comment]
Hi Jared,

I've sent you a link to the files, let me know if you don't receive it.

Thanks,

Sam

**Comment by jts** [comment]
Hi @samstu,

I've been trying to email you but have received bounce backs from your mail server. If there's another email address you can use, can you email me? I've been unable to read the files that you uploaded.

Jared

**Comment by jts** [comment]
As discussed over email, the problem was that sequencing speed was slightly lower than expected so failed nanopolish's internal QC checks. Closing this issue for now but will consider how to better handle variation in sequencing speed.
