### ISSUE TITLE
filtered fastq data from filtlong, unicycler fasta data, then run nanopolish failed.

### ISSUE THREAD

**Issue by limin321** [jts/nanopolish#629]
I filtered the original fastq data using following command:
filtlong --min_length 1000 --keep_percent 90 186.fastq > 186.filtered.fastq

Then run unicycler to get fasta data with following command:
unicycler -l 186.filtered.fastq -o 186_unicycler -t 20

Then I ran the following nanopolish:
awk '{if(NR%4==1){print ">"substr($1,2)}}{if(NR%4==2){print}}' 186.filtered.fastq > Sta001_reads.fasta &&\
nanopolish index -d ./../../20190125_pool2/fast5_pass/ Sta001_reads.fasta &&\
minimap2 -ax map-ont -t 8 assembly.fasta Sta001_reads.fasta | samtools sort -o Sta001_reads_sorted.bam -T reads.tmp &&\
samtools index Sta001_reads_sorted.bam &&\
nanopolish_makerange.py assembly.fasta | parallel --results nanopolish.results -P 8 nanopolish variants --consensus -o polished.{1}.vcf -w {1} -r Sta001_reads.fasta -b Sta001_reads_sorted.bam -g assembly.fasta -t 4 --min-candidate-frequency 0.1 &&\
nanopolish vcf2fasta -g assembly.fasta polished.tig000*.vcf > 186_uni_np.fasta

Nanopolish failed with following error:
[post-run summary] total reads: 179, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 179
[post-run summary] total reads: 164, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 164
error: could not detect polishing window from input file polished.tig000*.vcf

Does anyone have any idea what might be the problem?  You are greatly appreciated.  

I am a beginner in doing bacteria genome.

Thanks a lot.

**Comment by jts** [comment]
Hi,

Nanopolish was not able to find the fast5 files for your reads. Did the read names change in one of your pre-processing steps? What was the output of the `nanopolish index` command?

Jared

**Comment by limin321** [comment]
Hi Jared,

Thank you so much for the reminder. You are right, I just noticed that I
put the wrong fast5 files, no wonder the program complains that all fast5
are bad fast5.  Thank you so much. I learned from mistakes.
I am trying again right now. Thanks a lot.

Have a nice weekend.

**Comment by limin321** [comment]
> Hi,
> 
> Nanopolish was not able to find the fast5 files for your reads. Did the read names change in one of your pre-processing steps? What was the output of the `nanopolish index` command?
> 
> Jared

Hi, Jared

Though I put correct fast5 files this time, I still got the same error, as following shows

[post-run summary] total reads: 179, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 33, bad fast5: 0
Number of variants in span (16) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (34) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (14) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (17) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (39) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (11) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (22) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (11) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (13) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (17) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (12) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (25) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (38) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (14) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (11) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
[post-run summary] total reads: 155, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 29, bad fast5: 0
Number of variants in span (55) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (14) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (10) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (18) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (11) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (11) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
[post-run summary] total reads: 164, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 34, bad fast5: 0
error: could not detect polishing window from input file polished.tig000*.vcf
(base) campus-040-014:uni_np dklabuser$ ls

At least, this time no bad fast5. I checked the output of all previous steps, they all look good. Do you have any idea how to solve this problem. 
By the way, I used the same filtered fastq to run both canu and nanopolish, it works. 
The only difference of this one is the fasta file is generated by unicycler. I ran samtools view reads.sorted.bam | head     the output of this command looks okay. so unicycler output shouldn't be a problem.  

Please help me if you have any better explanation.
Thanks a lot.
Limin

**Comment by jts** [comment]
Hi,

Sorry for the delay, I was on vacation. It looks like no vcf files were generated. Is that correct?

Jared

**Comment by limin321** [comment]
Hope you had a nice vacation. No worries.  Thanks you for being so
helpful.  I know what the problem is now.  Different batches fast5 data,
the output name of   . vcf are a little different.  I just need to ensure
my input . vcf is correct.  Then it works.

Thanks again.

**Comment by jts** [comment]
Ok, thanks for the update.
