### ISSUE TITLE
error for calculate_methylation_frequency.py 

### ISSUE THREAD

**Issue by zifeng8824** [jts/nanopolish#631]
Hi,I have update the recent version:
[zsk@fat01 nanopolish]$ nanopolish --version
nanopolish version 0.11.1
Written by Jared Simpson.
Copyright 2015-2017 Ontario Institute for Cancer Research

but When I am using the following command, there not have -i parameter. Is it right?
[zsk@fat01 scripts]$ python calculate_methylation_frequency.py  -h
usage: calculate_methylation_frequency.py [-h] [-c CALL_THRESHOLD] [-s]
Calculate methylation frequency at genomic CpG sites
optional arguments:
  -h, --help            show this help message and exit
  -c CALL_THRESHOLD, --call-threshold CALL_THRESHOLD
  -s, --split-groups

then I  using the following command to to calculate the frequency, this error persists.
[zsk@fat01 scripts]$ calculate_methylation_frequency.py -i head_test.tsv> 123.tsv
Traceback (most recent call last):
  File "./calculate_methylation_frequency.py", line 37, in <module>
    in_fh = open(f)
FileNotFoundError: [Errno 2] No such file or directory: '-i'

]$ head head_test.tsv 
chromosome	start	end	read_name	log_lik_ratio	log_lik_methylated	log_lik_unmethylated	num_calling_strands	num_cpgs	sequence
chrA1	193	193	77766855-6d88-4209-8e57-a1b5c847ddf5	0.41	-124.71	-125.12	1	1	TTTTTCGACAG
chrA1	241	241	77766855-6d88-4209-8e57-a1b5c847ddf5	-0.57	-191.46	-190.89	1	1	TTTTACGGATA
chrA1	265	265	77766855-6d88-4209-8e57-a1b5c847ddf5	0.01	-181.02	-181.03	1	1	TGAATCGTTGA
chrA1	280	303	77766855-6d88-4209-8e57-a1b5c847ddf5	0.15	-387.00	-387.15	1	4	GTCCTCGTCGAGGGACACCGCCAATGGCCGGGAG
chrA1	315	315	77766855-6d88-4209-8e57-a1b5c847ddf5	-0.04	-178.06	-178.02	1	1	GGGGCCGGGTG
chrA1	350	350	77766855-6d88-4209-8e57-a1b5c847ddf5	-1.18	-155.84	-154.65	1	1	CACTGCGGGCA
chrA1	370	370	77766855-6d88-4209-8e57-a1b5c847ddf5	-0.34	-200.69	-200.35	1	1	GGTGGCGGGTC
chrA1	388	395	77766855-6d88-4209-8e57-a1b5c847ddf5	-2.53	-220.30	-217.76	1	3	TTCCACGGCGGGCGCAGG

then I used older version to calculation the methylation frequency：
]$ python calculate_methylation_frequency.py -h
usage: calculate_methylation_frequency.py [-h] [-c CALL_THRESHOLD] [-i INPUT]
                                          [-s]
Calculate methylation frequency at genomic CpG sites
optional arguments:
  -h, --help            show this help message and exit
  -c CALL_THRESHOLD, --call-threshold CALL_THRESHOLD
  -i INPUT, --input INPUT
  -s, --split-groups

[]$ python calculate_methylation_frequency.py -i head_test.tsv 
Traceback (most recent call last):
  File "calculate_methylation_frequency.py", line 47, in <module>
    num_sites = int(record['num_cpgs']) 
KeyError: 'num_cpgs'

how can I do? thanks

**Comment by jts** [comment]
> When I am using the following command, there not have -i parameter. Is it right?

Correct, in the latest version of the script the `-i` option is not needed, it will take all files as input:

```
python calculation_methylation_frequency.py test1.tsv test2.tsv [...] testn.tsv
```

We'll update the documentation.

**Comment by wzhjlau2009** [comment]
I have the same question about this ,  
python calculate_methylation_frequency.py -i head_test.tsv
Traceback (most recent call last):
File "calculate_methylation_frequency.py", line 47, in 
num_sites = int(record['num_cpgs'])
KeyError: 'num_cpgs'

right now , the version of nanopolish is 8.4 setup on my server , how can i solve this problem through this version ? or only the latest version of nanopolish can fix the problem ? Thanks . @jts @zifeng8824

**Comment by jts** [comment]
@wzhjlau2009 your issue is caused by a mismatch between the versions of `nanopolish call-methylation` and `calculate_methylation_frequency.py`. The simplest solution is to update `calculate_methylation_frequency.py` to the latest version.
