### ISSUE TITLE
Compressed package parsing error(methylation_example.tar.gz)

### ISSUE THREAD

**Issue by chenji333** [jts/nanopolish#633]
use tar -xvf methylation_example.tar.gz：

gzip: stdin: invalid compressed data--format violated
methylation_example/fast5_files/FMH_15Le080325s_20161103_FNFAB42798_MN17638_sequencing_run_161103_Human5_LSK108R9_4_13493_ch65_read3445_strand.fast5
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

**Comment by Shians** [comment]
I may be wrong but I think you need to write

`tar -xzvf methylation_example.tar.gz`

where the extra `z` option handles the zipped file. If that works then the quickstart tutorial will need to be updated.

**Comment by chenji333** [comment]
I just tried tar -xzvf methylation_example.tar.gz, But still the same result.

**Comment by chenji333** [comment]
I just tried tar -xzvf methylation_example.tar.gz, but still the same result.

**Comment by Shians** [comment]
You may have an incomplete download, can you check the size and checksum?

```bash
> du -h methylation_example.tar.gz
2.1G	methylation_example.tar.gz
> md5sum methylation_example.tar.gz
8720ce984e01aef429888072b43ca4cd  methylation_example.tar.gz

**Comment by chenji333** [comment]
It is true that the compressed package download is incomplete.
$ du -h methylation_example.tar.gz
2.0G 	methylation_example.tar.gz
$ md5sum methylation_example.tar.gz
209e8994223bb038ca94c1c6d45e5e79  methylation_example.tar.gz

I think there is an error in the compression package?
I downloaded it in the last two days, and downloading twice is the problem.

**Comment by Shians** [comment]
It's most likely an error in the downloading, your connection might have cut off just before the file finished downloading. Since gzip unzips files from front to back, it doesn't error out until it actually hits the incomplete part of the file. That's the meaning of the `Unexpected EOF in archive` message, EOF is end-of-file.

The decompression expected more data to complete its unzipping, but the file unexpectedly ended because the download was incomplete.

**Comment by chenji333** [comment]
Thank you for your answer. I tried it again.
I downloaded half of it before. After the failure, I continued to download.
There was no problem this time.

**Comment by jts** [comment]
Thanks @Shians for resolving this one!
