### ISSUE TITLE
error with nanopolish vcf2fasta

### ISSUE THREAD

**Issue by K-N-S** [jts/nanopolish#635]
I'm encountering an error when running nanopolish vcf2fasta.

The command I'm using is: 
 nanopolish vcf2fasta  -g /Sample/Ref/annotation/NC_000964.3.gbk /VCFF/*_polished.*.vcf > /Sample/nanopolish/MW01/fasta/ref-A/MW01_Q9_polished_genome.fa

The error I receive is:
[E::fai_build_core] Format error, unexpected "L" at line 1
error: could not detect polishing window from input file /VCFF/*_polished.*.vcf

Could you offer a recommendation to fix the issue?

Thanks in advance for your help!

**Comment by jts** [comment]
.gbk files are not supported, you need to use FASTA as input.

**Comment by K-N-S** [comment]
Thank you for the correction!

I switched to using a fasta input with the command below:
nanopolish vcf2fasta  -g /Sample/Ref/annotation/NC_000964.3.fa /VCFF/*_polished.*.vcf > /Sample/nanopolish/MW01/fasta/ref-A/MW01_Q9_polished_genome.fa

Now, I'm getting the following  error:
[E::fai_build_core] Format error, unexpected "#" at line 1
error: could not detect polishing window from input file /VCFF/*_polished.*.vcf

Any more advice you can offer would be much appreciated!

**Comment by jts** [comment]
`/VCFF/_polished..vcf` does not look like a valid name, you should check the names of your VCF files and correct the command.

**Comment by K-N-S** [comment]
Hi Jared,

Though I changed the file name, I'm still getting approximately the same error.

nanopolish vcf2fasta  -g /Sample/Ref/annotation/NC_000964.3.fa /VCF/MW01_Q9_variants_polished.*.vcf > /Sample/nanop
olish/MW01/fasta/ref-A/MW01_Q9_polished_genome.fa

[E::fai_build_core] Format error, unexpected "#" at line 1
error: could not detect polishing window from input file VCF/MW01_Q9_variants_polished.NC_000964.3:0-50200.vcf

Looking at the reference and vcf files, I don't see anything obviously amiss. 

Any recommendations you might have would be much appreciated!

**Comment by jts** [comment]
Can you show the output from the command 

```
head VCF/MW01_Q9_variants_polished.NC_000964.3:0-50200.vcf
```

**Comment by K-N-S** [comment]
The output is:

##fileformat=VCFv4.2
##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">
##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">
##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">
##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">
##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
NC_000964.3	9441	.	GA	G	45.7	PASS	TotalReads=53;AlleleCount=1;SupportFraction=0.549181	GT	1
NC_000964.3	9448	.	GA	G	45.7	PASS	TotalReads=53;AlleleCount=1;SupportFraction=0.536988	GT	1

**Comment by jts** [comment]
Hi,

You need to provide the `--consensus` flag to `nanopolish variants` before using `vcf2fasta`.

**Comment by K-N-S** [comment]
Hi,

Thank you for the feedback. I tried running nanopolish variants using the --consensus flag but received a similar error.

nanopolish variants --verbose --faster --consensus -o /Sample/nanopolish/MW01/fasta/polished.vcf \
>     -w ":0" \
>     -r /Sample/Q9Filter/MW01/MW01_Q9.fq \
>     -b /Sample/samtools/MW01_Q9_polished.NC_000964.3_A.sorted.bam \
>     -g /Sample/Ref/annotation/NC_000964.3.fa
[E::fai_build_core] Format error, unexpected "#" at line 1
Segmentation fault
