### ISSUE TITLE
I am also getting the fast5 error. I basecalled and demultiplexed with guppy, i then demultiplexed my fast5 files with the fast5_subset from the Nanopore tools API.

### ISSUE THREAD

**Issue by behrimg** [jts/nanopolish#636]
I am also getting the fast5 error. I basecalled and demultiplexed with guppy, i then demultiplexed my fast5 files with the fast5_subset from the Nanopore tools API. 

my script looks like so
`#!/bin/bash

#number of cores
#SBATCH -n 4

#set max wallclock time
#SBATCH -t 2-00:00

#set account
##SBATCH -A mbehrin2

#set name of job
#SBATCH --job-name=nanopolish_index.sh

#set STDOUT file
#SBATCH -o nanopolish_index.%j.out

#set STDERR file
#SBATCH -e nanopolish_index.%j.err

#mail alert at start, end and abortion of execution
#SBATCH --mail-type=ALL

#send mail to this address
#SBATCH --mail-user=myemail@email.com

cd /scratch/GATC_Gwyn

nanopolish index -v -d /scratch/GATC_Gwyn/Nanopolish_Fast5/barcode05/ -s /scratch/GATC_Gwyn/guppy_GPU_fastq/sequencing_summary.txt /scratch/GATC_Gwyn/guppy_GPU_barcode/CombinedFastq/Sample_113_1.guppy.fastq`

i'm giving it the proper path to my barcode files as when i enter 
ls /scratch/GATC_Gwyn/Nanopolish_Fast5/barcode05/
i get:
`[username@agave1:/scratch/]$ ls GATC_Gwyn/Nanopolish_Fast5/barcode05
barcode05_NP0.fast5   barcode05_NP12.fast5  barcode05_NP15.fast5  barcode05_NP18.fast5  barcode05_NP20.fast5  barcode05_NP23.fast5  barcode05_NP4.fast5  barcode05_NP7.fast5  filename_mapping.txt
barcode05_NP10.fast5  barcode05_NP13.fast5  barcode05_NP16.fast5  barcode05_NP19.fast5  barcode05_NP21.fast5  barcode05_NP2.fast5   barcode05_NP5.fast5  barcode05_NP8.fast5
barcode05_NP11.fast5  barcode05_NP14.fast5  barcode05_NP17.fast5  barcode05_NP1.fast5   barcode05_NP22.fast5  barcode05_NP3.fast5   barcode05_NP6.fast5  barcode05_NP9.fast5`

its not obvious to me at this point what the issue might be.

_Originally posted by @behrimg in https://github.com/jts/nanopolish/issues/574#issuecomment-517070589_

**Comment by jts** [comment]
Can you try without demultiplexing the fast5s?

**Comment by behrimg** [comment]
I've attached my barcode05_NP0.fast5 and my Sample_113_1.guppy.fastq files.

**Comment by behrimg** [comment]
Ok, I will try that now. I've tried to attach the barcode05_NP0.fast5 but the file is far too large for github. I can try and share on a google drive if the original fast5s dont work.

**Comment by jts** [comment]
Did it work without demultiplexing?

**Comment by behrimg** [comment]
Yes and no. So using the demultiplexed fast5s allowed indexing to complete, however a new issue emerged with nanopolish eventalign where it would only align a handful of reads before quitting. Going through the issues here, that may be due to how MinKnow dumped my fast5 files (a pass, fail, and skip). Thus, when I did basecalling with guppy the sequencing summary file had the fast5 file name but not the path. 

I just copy and renamed the original fast5 files into a single directory, rebasecalled, demultiplexed the fastqs, and re-indexed. All have gone fine so far. I'm now working on remapping the reads with minimap2 and will try nanopolish eventalign again next.

**Comment by jts** [comment]
Thanks for the update, sorry it has given you so much trouble.

Jared
