### ISSUE TITLE
Making my own summary file?

### ISSUE THREAD

**Issue by mvollger** [jts/nanopolish#637]
I recently merged a lot of single fast5s into multi_fast5 and in the process I kept track of the read_ids and the filenames. 

Is it possible to make my own fake "sequencing_summary.txt" formatted as follows and expect it to work with nanopolish index?
```
filename        read_id
/path/to/gridion_181008_CHM13.fast5  1d101641-548d-4c9a-b3a7-4b407f65b757
/path/to/gridion_181008_CHM13.fast5  63f5baa8-320d-4d8d-b27f-e64c44857949
...
```

Thanks in advance!

**Comment by jts** [comment]
that should be fine, indexing only uses those two columns and the order doesn't matter.
