### ISSUE TITLE
Option to use locally installed EIGEN package

### ISSUE THREAD

**Issue by tseemann** [jts/nanopolish#64]
Currently, to compile with my own `libhdf5` I can just use `make HDF5=` and it works.

However  the same functionality is not possible for EIGEN. The `EIGEN` variable doesn't behave the same way in the Makefile. 

Could this be changed to behave like HDF5 does?

This would make the `Linuxbrew` package for nanopolish much simpler.

**Comment by jts** [comment]
I've put a candidate fix in the `eigen-fix` branch. Could you grab it and test? If it works with linuxbrew I'll merge into master.

**Comment by jts** [comment]
Note you may have to set `EIGEN_INCLUDE` if eigen is not on your include path

**Comment by jts** [comment]
@tseemann is it possible to test branch with linuxbrew?

**Comment by tseemann** [comment]
I know I never replied here, but your changes do work and are used by the brew formula to use the system eigen packages. thank you!
