### ISSUE TITLE
Error with nanopolish variants

### ISSUE THREAD

**Issue by K-N-S** [jts/nanopolish#641]
I'm encountering an error when running nanopolish vcf2fasta.

nanopolish vcf2fasta -g /Sample/Ref/annotation/NC_000964.3.fa /VCF/MW01_Q9_variants_polished.*.vcf > /Sample/nanop
olish/MW01/fasta/ref-A/MW01_Q9_polished_genome.fa

[E::fai_build_core] Format error, unexpected "#" at line 1
error: could not detect polishing window from input file VCF/MW01_Q9_variants_polished.NC_000964.3:0-50200.vcf

I tried running nanopolish variants using the --consensus flag but received a similar error.

nanopolish variants --verbose --faster --consensus -o /Sample/nanopolish/MW01/fasta/polished.vcf 
-w ":0" 
-r /Sample/Q9Filter/MW01/MW01_Q9.fq 
-b /Sample/samtools/MW01_Q9_polished.NC_000964.3_A.sorted.bam 
-g /Sample/Ref/annotation/NC_000964.3.fa

[E::fai_build_core] Format error, unexpected "#" at line 1
Segmentation fault

Any advice you can offer would be much appreciated!

**Comment by jts** [comment]
`[E::fai_build_core]` is a message that the FASTA indexing step prints out. This should only be run on the reference genome `-g /Sample/Ref/annotation/NC_000964.3.fa`, so it makes me suspect there is a problem with your reference. Can you run `head /Sample/Ref/annotation/NC_000964.3.fa` and paste the result?

Thanks
Jared

**Comment by K-N-S** [comment]
When I run that command, it returns:

/ # head /Sample/Ref/annotation/NC_000964.3.fa
##gff-version 3
#!gff-spec-version 1.21
#!processor NCBI annotwriter
#!genome-build ASM904v1
#!genome-build-accession NCBI_Assembly:GCF_000009045.1
##sequence-region NC_000964.3 1 4215606
##species https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=224308
NC_000964.3	RefSeq	region	1	4215606	.	+	.	ID=id0;Dbxref=taxon:224308;Is_circular=true;Name=ANONYMOUS;gbkey=Src;genome=chromosome;mol_type=genomic DNA;strain=168;sub-species=subtilis
NC_000964.3	RefSeq	gene	410	1750	.	+	.	ID=gene0;Dbxref=GeneID:939978;Name=dnaA;gbkey=Gene;gene=dnaA;gene_biotype=protein_coding;locus_tag=BSU00010
NC_000964.3	RefSeq	CDS	410	1750	.	+	0	ID=cds0;Parent=gene0;Dbxref=Genbank:NP_387882.1,GeneID:939978;Name=NP_387882.1;Note=binds to the dnaA-box as an ATP-bound complex at the origin of replication during the initiation of chromosomal replication%3B can also affect transcription of multiple genes including itself.;gbkey=CDS;gene=dnaA;inference=ab initio prediction:AMIGene:2.0;product=chromosomal replication initiator protein DnaA;protein_id=NP_387882.1;transl_table=11

Thank you so much for your time and help!

**Comment by jts** [comment]
That is a GTF file, your reference genome should be a FASTA file.

**Comment by K-N-S** [comment]
Thank you! I'm trying it now and will get back to you if I have further issues.

Thanks again for your help!

**Comment by jts** [comment]
No problem
