### ISSUE TITLE
Number of base called reads with variant is greater than the number of total reads 

### ISSUE THREAD

**Issue by thaisegreja** [jts/nanopolish#643]
Hello, 
I am running nanopolish --variants to call SNPs and for some of the SNPs the number of base called reads with variant is greater than the number of total reads. Have you seen this before? Any comments on that? 

Thanks!

**Comment by jts** [comment]
Sorry for the slow response. Yes, that is expected. The `TotalReads` value is the number of usable signal-space reads. Nanopolish performs QC on the signal data, which discards reads, so this number can be lower than the number of BaseCalledReads.

**Comment by thaisegreja** [comment]
Thank you!
