### ISSUE TITLE
What is the training data for traning the HMM model of estimating polya length?

### ISSUE THREAD

**Issue by smallfade** [jts/nanopolish#645]
I wonder what organisms or cell types you used to get the emission distributions. And do you observe any differences among cell types?

**Comment by jts** [comment]
We developed program using a small subset of human and SIRV reads from [this dataset](https://github.com/nanopore-wgs-consortium/NA12878/blob/master/RNA.md). We tested the trained models using data ONT generated [found here](https://www.ebi.ac.uk/ena/data/view/PRJEB28423)

**Comment by smallfade** [comment]
> We developed the program using a small subset of human and SIRV reads from [this dataset](https://github.com/nanopore-wgs-consortium/NA12878/blob/master/RNA.md). We tested the trained models using data ONT generated [found here](https://www.ebi.ac.uk/ena/data/view/PRJEB28423)

Thanks a lot!
