### ISSUE TITLE
The depth of methylation sites from methylation_frequency.tsv.

### ISSUE THREAD

**Issue by tengfeixiaozhu** [jts/nanopolish#646]
hi @jts 

You said "called_sites is effectively sequencing depth when the group contains a single CpG. Sorry for being unclear in my previous response." in issuse #559 .
Could I calculate the depth of the region when group containds multiple CpG sites as called_sites/num_cpgs_in_group? 
 
Thank you for your reply!

chromosome  start    end      num_cpgs_in_group  called_sites  called_sites_methylated  methylated_frequency  group_sequence
chr20       5036763  5036763  1                  21            20                       0.952                 split-group
chr20       5036770  5036770  1                  21            20                       0.952                 split-group
chr20       5036780  5036780  1                  21            20                       0.952                 split-group
chr20       5037173  5037173  1                  13            5                        0.385                 AAGGACGTTAT
I

**Comment by jts** [comment]
depth is approximately `called_sites / num_cpgs_in_group`
