### ISSUE TITLE
Spliced reads error

### ISSUE THREAD

**Issue by vahidAK** [jts/nanopolish#647]
Hi @jts ,  
I have just installed nanopolish. I tried methylation calling but I got the same error as discussed in #364. I upgraded the htslib, but the error is still there. The read that gave this error is ~430kb long.  
My minimap code:  
minimap2 -t 32 -a -x map-ont fastq_file > output.sam
Thanks,  
Vahid.

**Comment by jts** [comment]
Thanks, I need to upgrade htslib to fix this. In the meantime I suggest filtering out these ultralong reads (or upgrade htslib in your version of nanopolish, if you're able to).

**Comment by vahidAK** [comment]
> Thanks, I need to upgrade htslib to fix this. In the meantime I suggest filtering out these ultralong reads (or upgrade htslib in your version of nanopolish, if you're able to).

**Comment by vahidAK** [comment]
Thanks, @jts.  
I deleted the reads more than 400kb and it worked. I had a question regarding the nanopolish algorithm.  
As mapping with minimap2 gives a bam file with many multi mapped and low quality mapped reads, how nanopolish deal with this? I mean does it automatically consider high quality mapped reads? if yes, which column of a bam file will be considered for filtering low quality reads? I would be grateful if you could give me some information in this regard.  
Thanks,  
Vahid

**Comment by vahidAK** [comment]
Thanks, @jts.
I deleted the reads more than 400kb and it worked. I had a question regarding the nanopolish algorithm.
As mapping with minimap2 gives a bam file with many multi mapped and low quality mapped reads, how nanopolish deal with this? I mean does it automatically consider high quality mapped reads? if yes, which column of a bam file will be considered for filtering low quality reads? I would be grateful if you could give me some information in this regard.
Thanks,
Vahid
