### ISSUE TITLE
Could not open index for input fasta

### ISSUE THREAD

**Issue by GomathiNayagam** [jts/nanopolish#648]
I am trying nanopolish for the first time and I am working with example dataset as given in the quick start. when I gave this" nanopolish variants -o polished.vcf --window="tig00000001:200000-202000" --reads reads.fa --bam reads.sorted.bam --genome draft.fa --ploidy=1" it gives the following error " error: could not load the index files for input file reads.fa ".  I am completely new to this, I need help!

**Comment by jts** [comment]
Hi,

Did you run the `nanopolish index` step? https://github.com/jts/nanopolish#data-preprocessing

Jared

**Comment by GomathiNayagam** [comment]
Of course yes!. I have the index file in too.

**Comment by jts** [comment]
If you have an index file you shouldn't get that error. Can you run `ls` on the directory that you're running in?

**Comment by GomathiNayagam** [comment]
I have a readdb file in the working directory. ls gives the following, 

> draft.fa              polished.fa         reads.bam.bai       reads.fasta.index.gzi     ref.fa
> draft.fa.fai          polished.vcf        reads.fa.index.fai  reads.fasta.index.readdb
> ecoli_2kb_region.log  polished_genome.fa  reads.fasta         reads.sorted.bam
> fast5_files           reads.bam           reads.fasta.index   reads.sorted.bam.bai

**Comment by jts** [comment]
It looks like you have run some commands with `reads.fa` and some commands with `reads.fasta`. You should correct the commands to use the right suffix, depending on the file your reads are in.
