### ISSUE TITLE
Index question

### ISSUE THREAD

**Issue by dcastaneda5** [jts/nanopolish#649]
Hi! I am very new to nanopolish and I was wondering if you guys could help me with the indexing section. Prior to calling variants, I am doing the indexing like this:

index -d ../raw_output_files/cpmp_and_msp2/cpmp_and_msp2/20190801_0023_MN32391_FAL13168_f49ad8ea/fast5_pass/ ../trim50_dem_q9/barcode01.fastq 

My question is: -d refers to the whole folder where my fast5 files passed the filter, correct? Also, the .fastq file refers to one of my samples? Or am I supposed to pass the folder where my .fastq files are? Can I use my filtered (used nanofilt and qcat) .fastq samples? In the example above I am passing the folder with my fast5 passed files, along with one out of the 96 filtered .fastq samples.

Thanks!

**Comment by jts** [comment]
Hi,

Yes, -d should be the whole folder and the .fastq should be the sample that you plan to align, analyze and variant call/polish. Its ok to use filtered reads for the .fastq.

Jared

**Comment by jts** [comment]
Yes, indexing can be very slow (but depends on the filesystem to come extent). You should be able to use the summary file from MinKNOW to speed it up.
