### ISSUE TITLE
compile failure on 0.5.0

### ISSUE THREAD

**Issue by rachelglover** [jts/nanopolish#65]
I'm getting a compile failure on v0.5.0 on debian Jessie:

`Makefile:104: recipe for target 'src/nanopolish_squiggle_read.o' failed`

I can't figure out where the problem might be. It's worth noting that I'm installing on a server with no internet access so I had to download the fast5 and htslib dependencies independently (no recursive git for me...) as well as download the wgets in the makefile (eigen and hdf5) and comment those lines out before make. This approach worked fine with v0.4.0 so I'm a bit stuck!

**Comment by jts** [comment]
Hi Rachel,

Could you post more of the error output?

Thanks,
Jared

**Comment by rachelglover** [comment]
No problem, here's a screenshot of the terminal output after using make.
![nanopolish_error](https://cloud.githubusercontent.com/assets/832654/17969874/0e243a10-6acc-11e6-8148-5f04acace8b8.png)

**Comment by jts** [comment]
It looks like you don't have the right version of `fast5` - could you make sure to download/checkout ` 2741874`?

**Comment by rachelglover** [comment]
I definitely downloaded that one but started again from scratch and re-downloaded nanopolish, fast5 and htslib dependencies and was able to compile without errors by compiling in a different location. Definitely something that was unique to our servers rather than an error from nanopolish (thankfully). Thanks for the pointers on what was going wrong - I wasn't sure what I was looking at in the errors.

**Comment by jts** [comment]
Great, glad to hear it is fixed.
