### ISSUE TITLE
Should running on split fastq produce identical methylation results as combined fastq?

### ISSUE THREAD

**Issue by Shians** [jts/nanopolish#650]
I don't have a good enough understanding of nanopolish's methylation calling to understand if it's expected to produce identical results for split and combined fastq. For example if I run nanopolish on a thousand small fastq containing 4000 reads each coming from Guppy, should I expect the results to be identical to if I had run it on the concatenated fastq?

**Comment by jts** [comment]
Yes, it should.

Jared

**Comment by Shians** [comment]
Thanks, that's useful to know for parallelising the workflow,
