### ISSUE TITLE
Indexing: low num reads with path to fast5

### ISSUE THREAD

**Issue by ekhtan** [jts/nanopolish#651]
Hello, I ran into the issue where I'm getting low numbers of reads with a path to the fast5 files during indexing. Reads were basecalled using Guppy 3.2.2.

```
nanopolish index -d /fast5 ahu_reads.fastq -s sequencing_summary.txt
[readdb] indexing /home/ekhtan/nanopore/ahu/sequencing/fast5
[readdb] num reads: 13094, num reads with path to fast5: 7
```

The reads I'm using are filtered reads from FiltLong but run on the same fast5 files. I thought that was the issue, so I used all the reads and this is what I got:

`[readdb] num reads: 396921, num reads with path to fast5: 100`

Thanks for your help!

**Comment by jts** [comment]
What version of nanopolish are you using?

**Comment by ekhtan** [comment]
What we have currently is version 0.11.0

**Comment by ekhtan** [comment]
Hi @jts - any ideas on how we can get a better correlation for reads to fast5 path?

**Comment by jts** [comment]
Its hard to say what the problem is without more information. What is the directory structure of `/home/ekhtan/nanopore/ahu/sequencing/fast5`? If you try without the `-s` option does it find more reads?

**Comment by ekhtan** [comment]
I haven't tried it without -s (wouldn't this take a long time without this file?) but I can try it and report back.

The files within `/home/ekhtan/nanopore/ahu/sequencing/fast5` look like this:

```
-rw-r--r-- 1 ekhtan ceballos 162M Apr 24 16:45 FAK53626_e60c29cb77b5919df1ccddaae30c43ca62418ab1_0.fast5
-rw-r--r-- 1 ekhtan ceballos 251M Apr 24 16:46 FAK53626_e60c29cb77b5919df1ccddaae30c43ca62418ab1_100.fast5
-rw-r--r-- 1 ekhtan ceballos 216M Apr 24 16:46 FAK53626_e60c29cb77b5919df1ccddaae30c43ca62418ab1_101.fast5
```

**Comment by jts** [comment]
You can try on a small subset of the reads to see if it indexes properly without `-s`. Try something like this:

```
mkdir test_subset
ln -s fast5/FAK53626_e60c29cb77b5919df1ccddaae30c43ca62418ab1_0.fast5 test_subset/test.fast5
nanopolish index -d test_subset reads.fastq
```

You should get 4000 reads indexed.

Jared

**Comment by ekhtan** [comment]
When I did that, I got the `no fast5 files found error`

```
razor-l1:ekhtan:~$ ln -s nanopore/ahu/sequencing/fast5/FAK53626_e60c29cb77b5919df1ccddaae30c43ca62418ab1_0.fast5 test/test.fast5
razor-l1:ekhtan:~$ nanopolish index -d test/ ahu_reads.fastq
[readdb] indexing test/
could not open fast5 file: test//test.fast5
Error: no fast5 files found
```

**Comment by ekhtan** [comment]
My symlink didn't work, apologies. I'll try again.

**Comment by ekhtan** [comment]
I just copied one of the fast5 files, and got the same error. Perhaps my fast5 files are the problem here? 

```
razor-l1:ekhtan:~$ nanopolish index -d test/ ahu_reads.fastq
[readdb] indexing test/
could not open fast5 file: test//FAK53626_e60c29cb77b5919df1ccddaae30c43ca62418ab1_0.fast5
Error: no fast5 files found
```

**Comment by jts** [comment]
Could you send me that fast5 so I can try?

Jared

**Comment by ekhtan** [comment]
This issue seem to be specific to the cluster that I ran it on. I switched to a different cluster and it solved the issue. Hope that's useful for others that are having this issue.

```
tres-l1:ekhtan:~$ nanopolish index -d test/ ahu_reads.fastq
[readdb] indexing test/
[readdb] num reads: 17047, num reads with path to fast5: 4000
```

**Comment by ekhtan** [comment]
Let me know if you're interested in the differences between the two clusters that I was using.

**Comment by jts** [comment]
Its quite strange that it would be cluster dependent. Was it a file permissions issue?

**Comment by ekhtan** [comment]
Hmm. I'm confused as well, the permissions appear to be identical to me.
