### ISSUE TITLE
problem polishing multiple contigs

### ISSUE THREAD

**Issue by marianovosolov** [jts/nanopolish#653]
I'm trying to polish multiple contigs into consensus contigs using the nanopolish_makerange.py script and the command line proposed in the manual and the solutions of several previous issues here and it doesn't seem to work correctly. 
This is the line I'm using 
python /share/apps/nanopolish/scripts/nanopolish_makerange.py MinIonAssembly_mito_OD_G_all.contigs.fasta | parallel --results nanopolish.results nanopolish variants --consensus -o polished.{1}.vcf -w "{1}" -r nano_non_nuc_reads_OD.fasta -b reads.sorted.bam -g MinIonAssembly_mito_OD_G_all.contigs.fasta -t 4 --min-candidate-frequency 0.1

This is already after I completed successfully all the previous commands of indexing the fast5 files and using minimap to align the reads. 
The line above does the divission of the contigs but instead of creating multiple vcf files it constantly overwrites the polished.1.vcf file that it creates. How can i overcome this problem? 

A bit about my data: I have contigs from Canu assembly of MinION reads. Many of the contigs are relatively short (half of them are less than 2000bp), and the reads are the same (half are shorter than 1000). There is a lot of variation in the data, which is why I'm trying to polish it into a consensus.

**Comment by jts** [comment]
Hi @marianovosolov,

The `{1}` token in the output filename (`polished.{1}.vcf`) should be replaced with the contig name and region to polish. So it should generate output files like `polished.contig1:0-50200.vcf`. Can you run:

```
python /share/apps/nanopolish/scripts/nanopolish_makerange.py MinIonAssembly_mito_OD_G_all.contigs.fasta 
```

and paste the results?

**Comment by marianovosolov** [comment]
Hey @jts 

I ran the line you said. It creates a folder that is called nanopolish.results, inside there is one folder called 1, and inside there are many folders that each has the following names (subsample):
tig00000001:2700000-2750200
tig00000001:2750000-2800200
tig00000001:2800000-2850200
tig00000001:2850000-2900200
tig00000001:2900000-2950200
tig00000001:2950000-3000200
tig00000001:3000000-3021690
tig00000028:0-50200
tig00000028:50000-59601
tig00000030:0-50200
tig00000030:50000-71679
tig00000038:0-50200

This is also what is printed as the output of the run.

As for the size will nanopolish gives an error when the contigs are shorter then 100kb?

**Comment by jts** [comment]
Hi @marianovosolov,

What version of parallel are you using (`parallel --version`)?

Jared

**Comment by marianovosolov** [comment]
Hey @jts 

This is the output of the version command:

GNU parallel 20190722
Copyright (C) 2007-2019 Ole Tange and Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
GNU parallel comes with no warranty.

Web site: http://www.gnu.org/software/parallel

When using programs that use GNU Parallel to process data for publication
please cite as described in 'parallel --citation'.

**Comment by jts** [comment]
Can you try running this version, and send the output to me? It will print the commands that should be run without actually running them (note the addition of the `--dryrun` flag).

```
python /share/apps/nanopolish/scripts/nanopolish_makerange.py MinIonAssembly_mito_OD_G_all.contigs.fasta | \
parallel --dryrun --results nanopolish.results nanopolish variants --consensus -o polished.{1}.vcf -w "{1}" -r nano_non_nuc_reads_OD.fasta -b reads.sorted.bam -g MinIonAssembly_mito_OD_G_all.contigs.fasta -t 4 --min-candidate-frequency 0.1
```

**Comment by marianovosolov** [comment]
This is the example of what is printed out:
nanopolish variants --consensus -o polished.1.vcf -w tig00000001:0-50200 -r nano_non_nuc_reads_OD.fasta -b reads.sorted.bam -g MinIonAssembly_mito_OD_G_all.contigs.fasta -t 4 --min-candidate-frequency 0.1
nanopolish variants --consensus -o polished.1.vcf -w tig00000001:350000-400200 -r nano_non_nuc_reads_OD.fasta -b reads.sorted.bam -g MinIonAssembly_mito_OD_G_all.contigs.fasta -t 4 --min-candidate-frequency 0.1
nanopolish variants --consensus -o polished.1.vcf -w tig00000001:250000-300200 -r nano_non_nuc_reads_OD.fasta -b reads.sorted.bam -g MinIonAssembly_mito_OD_G_all.contigs.fasta -t 4 --min-candidate-frequency 0.1

**Comment by jts** [comment]
What if you change `polished.{1}.vcf` to `polished."{1}".vcf`?

**Comment by marianovosolov** [comment]
Yeah. that seems to work...can you explain me the logic behind the double quotation marks?
output example
nanopolish variants --consensus -o polished.tig00000001:200000-250200.vcf -w tig00000001:200000-250200 -r nano_non_nuc_reads_OD.fasta -b reads.sorted.bam -g MinIonAssembly_mito_OD_G_all.contigs.fasta -t 4 --min-candidate-frequency 0.1
nanopolish variants --consensus -o polished.tig00000001:1050000-1100200.vcf -w tig00000001:1050000-1100200 -r nano_non_nuc_reads_OD.fasta -b reads.sorted.bam -g MinIonAssembly_mito_OD_G_all.contigs.fasta -t 4 --min-candidate-frequency 0.1
nanopolish variants --consensus -o polished.tig00000001:550000-600200.vcf -w tig00000001:550000-600200 -r nano_non_nuc_reads_OD.fasta -b reads.sorted.bam -g MinIonAssembly_mito_OD_G_all.contigs.fasta -t 4 --min-candidate-frequency 0.1
nanopolish variants --consensus -o polished.tig00000001:600000-650200.vcf -w tig00000001:600000-650200 -r nano_non_nuc_reads_OD.fasta -b reads.sorted.bam -g MinIonAssembly_mito_OD_G_all.contigs.fasta -t 4 --min-candidate-frequency 0.1

**Comment by jts** [comment]
To be honest, I don't know. I tested it without the double quotes and it worked fine for me. What shell are you using?

**Comment by marianovosolov** [comment]
Good question. I'm sending it as a job in sun grid engine.
