### ISSUE TITLE
Nanopolish Methylation Frequency group_sequence

### ISSUE THREAD

**Issue by vahidAK** [jts/nanopolish#654]
Hi @jts ,  
In the methylation frequency results, the last column is group_sequence which may only include one single CpG or multiple CpGs. As I understand the "compare_methylation.py" script only merges the motifs with only one CpG in the last column with the bisulfite results, is it correct?  
Also, in the group_sequences with several CpGs, do all the CpGs are methylated? if no how can we understand which CpGs are methylated?
Many thanks,  
Vahid.

**Comment by jts** [comment]
> As I understand the "compare_methylation.py" script only merges the motifs with only one CpG in the last column with the bisulfite results, is it correct?

Correct, the compare_methylation.py script only compares groups that have a single CpG site.

> Also, in the group_sequences with several CpGs, do all the CpGs are methylated? if no how can we understand which CpGs are methylated?

Right now we only call the group as completely methylated or completely unmethylated. We plan to change this is in the future.

Jared
