### ISSUE TITLE
Nanopolish eventalign standardized_level

### ISSUE THREAD

**Issue by TongChengxuan** [jts/nanopolish#655]
Hi,
I would like to clarify on nanopolish eventalign output. What is standardized_level mean. I noticed that if absolute value of standardized_level is large, there will be a larger difference between event_level_mean and model_mean. Do I have to correct my event_level_mean with this standardized_level to get the actual signal for the k-mer? Or is this a useful parameter to remove outliers beside the "NNNNNN" model_kmer. I ran nanopolish eventalign with --scale-events

Another question I had is the same read output multiple events. Most of the event_level_means are  very close to model_mean, but there are a few outliers. I am curious why nanopolish output can be very different for the same read at the same position? Can these kind of outliers be trusted for analysis?

**Comment by jts** [comment]
Hi,

`standardized_level` is simply `(event_level_mean - model_mean) / model_stdv`. To get the actual measured signal for the event you have to run without `--scale-events`.

> Another question I had is the same read output multiple events. Most of the event_level_means are very close to model_mean, but there are a few outliers. I am curious why nanopolish output can be very different for the same read at the same position?

After sequencing, there is a segmentation algorithm run on the current signal to generate the events. This algorithm may over-segment the data, resulting in multiple events for some positions. Nanopolish does not attempt to fix this, it just finds the best alignment of the event sequence to the reference genome.
