### ISSUE TITLE
calling haplotypes problem

### ISSUE THREAD

**Issue by dcastaneda5** [jts/nanopolish#656]
Hi,

I am currently running nanopolish for calling the variants after I indexed my files. I am running the following command:

`nanopolish variants -v -p 1 --genotype genotype_31 --fix-homopolymers -r barcode31.fastq -b ../minimap2_output_ax_sr/aln_31.sorted.bam --genome ../gene_references/cpmp_pf3d7_0104100.fasta`

and it gives me an empty file (with the headers and all). First I trimmed the adapters from my raw fastq files, then I removed the barcodes, then I filtered low quality reads, and after that I aligned those reads against a reference gene (~800 bp) using `minimap2 -ax -sr`. After that I sorted and indexed my bam file, which I used as input for the nanopolish variants command previously described. Am I doing something wrong? I am working with haploid malaria genes, and I am basically trying to get the number of haplotypes per sample (each sample is a pool of haplotypes).

Thanks a lot for all the help and contribution you've done so far!

Daniel

**Comment by jts** [comment]
Hi,

Can you paste the output printed to `stderr` by nanopolish? I don't think you should use `-x sr` for nanopore data, even for short amplicons.

**Comment by dcastaneda5** [comment]
Sure, here it's the output:

```
##fileformat=VCFv4.2
##nanopolish_window=Plasmodium:0-2375
##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">
##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">
##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">
##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">
##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
[post-run summary] total reads: 109, unparseable: 0, qc fail: 0, could not calibrate: 1, no alignment: 19, bad fast5: 0
```

Yes, I noticed that is more for paired end reads, rather to what I have. I'll run minimap2 again without that and try to see if I get something different with `nanopolish variants`

Thanks

**Comment by dcastaneda5** [comment]
Sorry, I just realized I mapped and aligned using `minimap2 -x map-ont <ref.fasta> <sample.fastq> > output.sam`, I did not use the previous command I mentioned (`minimap2 -ax -sr`)

**Comment by jts** [comment]
The `--genotype genotype_31` option asks nanopolish to genotype variants that are present in the `genotype_31` VCF file. Is this what you want, or do you want the output to go to `genotype_31`?

**Comment by dcastaneda5** [comment]
I was hoping to call genotypes in the VCF file that I was expecting to get after running the nanopolish variants command. Am I using it wrong?

**Comment by jts** [comment]
Yeah the `--genotypes` option is to provide an existing list of sites to call genotypes at. If you remove that option it should work as expected.

**Comment by dcastaneda5** [comment]
It did! It worked! Thanks a lot! So if I want to obtain the number of genotypes across my sample, how would I use the `--genotype` command?

**Comment by jts** [comment]
You'd have to decide on a list of sites that you want to genotype, produce a VCF file with those sites, then pass it in with `--genotypes`. In regular variant calling mode it will produce genotypes too (at all detected variable sites). You can probably ignore the `--genotypes` option.

**Comment by jts** [comment]
No problem.
