### ISSUE TITLE
nanopolish workflow question

### ISSUE THREAD

**Issue by dcastaneda5** [jts/nanopolish#657]
Hi !

I have a question regarding how nanopolish works in general. My question is, will I get a set of corrected DNA reads in my .fastq files (or fasta) at the end of the workflow showed in https://nanopolish.readthedocs.io/en/latest/quickstart_consensus.html ? 

For this I first ran minimap2 to get .sam and .bam files for my nanopolish index step. After indexing, I am looking forward to identify real SNPs from sequencing errors, which I believe should be the nanopolish consensus step, correct? (I skipped the make range step because the genes we sequenced are less than 1kb long). I am basically trying to identify haplotypes from my nanopore data, as each of my files is likely to have multiple haplotypes of a malaria strain. I am trying to get fastq or fasta files of my reads that can be used to estimate the concentration of haplotypes across many samples (to see how many of these haplotypes are shared across samples, its abundance based on my data, etc.).

Thanks a lot!

**Comment by jts** [comment]
Hi @dcastaneda5,

Sorry for the slow reply. To answer your questions in order:

> My question is, will I get a set of corrected DNA reads in my .fastq files (or fasta) at the end of the workflow

No, you get a corrected genome sequence. Nanopolish does not correct individual reads.

> After indexing, I am looking forward to identify real SNPs from sequencing errors, which I believe should be the nanopolish consensus step, correct?

Correct, the output is a VCF file

>  I am basically trying to identify haplotypes from my nanopore data, as each of my files is likely to have multiple haplotypes of a malaria strain.

You can try `whatshap`, which supports phasing of variants with nanopore data.

jared
