### ISSUE TITLE
duplicate read name when indexing

### ISSUE THREAD

**Issue by marcotoffoli** [jts/nanopolish#658]
Good afternoon, 

I recently tried the newest version of Nanopolish with data generated from a R10 flowcell on my MinION. 

I basecaleld with Guppy (HAC).
I used barcoded samples and merged the fastq files for each barcode in a folder.

I used the following string to index:
`for f in /path/to/merged/*.fastq; do =nanopolish index -s /path/to/sequencing_summary.txt -d /path/to/fast5 $f; done`

This gave me multiple errors like the following (wth different names of course):
`Warning: duplicate read name 48a93996-58b7-4584-a045-a06b601c3c5e found in fasta file`

It never happened to me before, any idea why I'm getting loads of reads with the same name?

Thank you!

**Comment by jts** [comment]
Hi @marcotoffoli,

The reads are produced upstream of nanopolish, so I'm not sure what the problem might be. If you grep for `48a93996-58b7-4584-a045-a06b601c3c5e` in the input fastq do you see it multiple times? What about in the files directly output by guppy?

Jared

**Comment by marcotoffoli** [comment]
Hi Jared, 

Yes I checked and it looks like in my merged fastq files there are duplicates. 
I then checked h original fastq (output of Guppy) and also found duplicates, like:

`~/guppy_fastq/fastq_runid_80697603299af90e17ac69931f0d73d1c7b7811e_0_0.fastq:@48a93996-58b7-4584-a045-a06b601c3c5e runid=80697603299af90e17ac69931f0d73d1c7b7811e sampleid=4th_minion_run read=12971 ch=171 start_time=2019-07-25T15:39:17Z
~/guppy_fastq/fastq_runid_80697603299af90e17ac69931f0d73d1c7b7811e_0_4.fastq:@48a93996-58b7-4584-a045-a06b601c3c5e runid=80697603299af90e17ac69931f0d73d1c7b7811e sampleid=4th_minion_run read=12971 ch=171 start_time=2019-07-25T15:39:17Z
`
I will contact the Guppy soppurt team to check why this is the case.

All best, 
Marco

**Comment by jts** [comment]
Ok, let me know if I can help with anything else.
