### ISSUE TITLE
nanopolish indexing: num reads vs. num reads with path to fast5

### ISSUE THREAD

**Issue by jhcaddisfly** [jts/nanopolish#660]
Hi,

I ran nanopolish index as follows:
nanopolish index -d AC1/fast5/ AC1/AC1_nano_filtered.fq

And the output is:
[readdb] num reads: 13384791, num reads with path to fast5: 13383173

However, when I do wc -l AC1_nano_filtered.fq it gives me 53046260  which is equivalent to 13261565 reads (divided by 4).

Do you think I can still proceed with the indexed files? Does it matter much?

All the very best,

J.

**Comment by jts** [comment]
Hi,

It looks like the number of reads in the fast5 files are slightly higher than in the fastq, probably due to the filtering you applied. If this is the case it does not matter, the extra reads will be ignored.

Jared

**Comment by jhcaddisfly** [comment]
Thank you very muchfor your quick response.
