### ISSUE TITLE
Question about the DNA model

### ISSUE THREAD

**Issue by WenxuZhang** [jts/nanopolish#663]
Hi, I am working on some data analysis on the DNA nanopore data. 

I want to double check that whether the kmer pore model data (shown in the etc/r9-models/r9.4_450bps.nucleotide.6mer.template.model) is from 5' to 3' or from 3' to 5'?

Thanks in advanced!

**Comment by jts** [comment]
Hi @WenxuZhang,

It is 5'->3'.

Jared

**Comment by WenxuZhang** [comment]
ok, thanks!
