### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by caonetto** [jts/nanopolish#666]
I keep on getting this error when trying to index reads bascalled with the latest guppy, and the latest nanopolish version. I havent had this issue before, any ideas? If I remove the -s option it start indexing the reads without the Segmentation fault error

nanopolish index -d /20190902_0453_MN18577_FAK10687_aa73f907/fast5/ -s /basecalled/sequencing_summary.txt reads.fastq 

Segmentation fault (core dumped)

If I remove the -s option it start indexing the reads without the Segmentation fault error

**Comment by jts** [comment]
Can you paste the start of the sequencing summary file (or email it to me)? What is the version number of guppy?

Jared

**Comment by jts** [comment]
Closing for now, please re-open if you are able to provide me with a file that can reproduce the issue.

**Comment by caonetto** [comment]
Hi,
Still having the same issue with the latest nanopolish and guppy.
Attached an example file 
[example.txt](https://github.com/jts/nanopolish/files/3948320/example.txt)

Thanks for your help.

**Comment by jts** [comment]
The summary file looks fine. I've updated the indexing code a little since you initial issue, can you update from github and try again?

**Comment by caonetto** [comment]
Hi,
This error was created with the latest nanopolish version.

**Comment by jts** [comment]
Can you provide me with a minimal set of data (like 1 fast5 file, 1 fastq and the sequencing summary) that will allow me to reproduce the problem here?
