### ISSUE TITLE
Explanation of nanopolish variant .vcf output

### ISSUE THREAD

**Issue by smf96** [jts/nanopolish#667]
Hello,

I am calling variants from amplicons that each cover one of several genes in a very homologous locus.   

Please could someone explain simply the output .vcf from the nanopolish variant command. I am new to bioinformatics and the descriptions aren’t that intuitive to me.  

What is the difference and relationship between the BaseCalledFraction and the SupportFraction? I think for this I am really looking for an explanation of base-space vs event-space reads?

Why does the BaseCalledReadsWithVariant divided by TotalReads never equate to either of the fractions that support the variant?

How do you interpret the quality score? In a previous post it was stated the QUAL values are not well calibrated, what information do they really represent?

Also in a previous post it was suggested SupportFraction were best to filter on…but how close to 1 can be trusted to represent a true variant and what is the threshold to call homozygous variants?

Thanks for your help!

**Comment by jts** [comment]
Hi,

> What is the difference and relationship between the BaseCalledFraction and the SupportFraction? I think for this I am really looking for an explanation of base-space vs event-space reads?

`BaseCalledFraction` is the number of reads that support the ALT allele when simply aligned to the reference genome. `SupportFraction` is the number of reads that support the ALT allele using nanopolish's signal-level probabilistic model.

> Why does the BaseCalledReadsWithVariant divided by TotalReads never equate to either of the fractions that support the variant?

`TotalReads` is the number of usable signal-space reads. It is the denominator for `SupportFraction`.

> How do you interpret the quality score? In a previous post it was stated the QUAL values are not well calibrated, what information do they really represent?

It is the log-likelihood ratio that was calculated by nanopolish's probabilistic model

> Also in a previous post it was suggested SupportFraction were best to filter on…but how close to 1 can be trusted to represent a true variant and what is the threshold to call homozygous variants?

If you have validation data from another sequencing platform I suggest you determine your own threshold for SupportFraction. Very coarsely anything above 0.9 SupportFraction is quite good in my experience, but if you filtered out anything below this you'd likely lose some variants.

I hope this helps,
Jared

**Comment by smf96** [comment]
Thank you for the swift reply.

Apologies but it still isn't that clear to me...

If the BaseCalledFraction is the number of reads that support the alt allele, how is that then different to BaseCalledReadsWithVariant? Is the TotalReads presented here not the denominator in this calculation?

I also still don't truly understand the distinction between the fractions. Aren't the base-called reads generated using a probabilistic model of the 5mer within the pore and therefore should be the same? (Obviously they aren't but please could you explain the contrast).

What constitutes a 'usable signal-space' read and how are they different to the base-called reads I have aligned to the reference? What is the numerator of the SupportFraction?

I really appreciate you taking the time to explain these details.

**Comment by smf96** [comment]
Also, what influences the decision of whether a variant is heterozygous or homozygous?

**Comment by jts** [comment]
Sorry, I misread your question before - I was describing `BaseCalledReadsWithVariant`, not `BaseCalledFraction`. `BaseCalledFraction` is `BaseCalledReadsWithVariant` divided by the aligned coverage at that position (which isn't recorded in the VCF INFO fields).

> Aren't the base-called reads generated using a probabilistic model of the 5mer within the pore and therefore should be the same? (Obviously they aren't but please could you explain the contrast).

The basecaller (guppy) and nanopolish use quite different models (guppy is a neural network, nanopolish is an HMM). Also, nanopolish has more information available to it - the reference sequence - so it can constrain the possibilities more than the basecaller can, as the basecaller can generate an arbitrary nucleotide sequence.

> What constitutes a 'usable signal-space' read and how are they different to the base-called reads I have aligned to the reference?

Nanopolish performs various quality control checks to determine whether the reads are worth using. If reads are discarded by this QC then they are not included in `TotalReads`.

>What is the numerator of the SupportFraction?

Nanopolish scores each read as supporting the reference allele or ALT allele better. The numerator of `SupportFraction` is the number of reads that support the ALT allele better.

Jared

**Comment by smf96** [comment]
Thank you so much for your explanations, I understand better!

What I'm still struggling with is how the AlleleCount is calculated. In a diploid organism (I'm working on humans), which information is used to determine whether the alt allele is homozygous or heterozygous? Is there a specific SupportFraction threshold?
