### ISSUE TITLE
Segmentation fault in methylation calling when genome file path is invalid

### ISSUE THREAD

**Issue by snajder-r** [jts/nanopolish#668]
Hi,

This is a minor issue, but I just wanted to point out that in the methylation calling pipeline currently you get a segmentation fault if the path to the genome fasta file is wrong. Maybe an error message saying that the specified genome file doesn't exist would be nice.

I had accidentally typed "-g cpg" instead of "-q cpg" and it took me quite some time to figure out why it was segfaulting :-D

Best,
Rene

**Comment by jts** [comment]
Ah, thanks for pointing that out, I will fix it.

Jared

**Comment by jts** [comment]
Thanks again for this, I've now added a check so will close this issue.
