### ISSUE TITLE
Nanopolish principle

### ISSUE THREAD

**Issue by BioRB** [jts/nanopolish#669]
Dear Author,
I would like to know the generic principle behind Nanopolish. I have used it in combination with minimap2 and SAMtools to perform the polishing of a draft sequence as suggested in the guide. 
my question then is:  Does this kind of pipe ( that involves Nanopolish) and in general Nanopolish itself, takes into account the frequencies of kmers (oligos in general) in the raw data ( since you provide raw data for the polishing).  How does this algorithm decide if the specific base is an error or if it is a variant?
I just want a general explanation of the principle, if you can.
Thanks

**Comment by jts** [comment]
Hi @BioRB,

I suggest having a look at this paper, which describes the idea behind nanopolish: https://www.nature.com/articles/nmeth.3444

This slide deck also describes the main ideas (but some parts are out of date now): https://www.slideshare.net/jaredsimpson/150514-jts-londoncalling

Jared
