### ISSUE TITLE
software aborts when lowercase letters are in the reference sequences

### ISSUE THREAD

**Issue by rachelglover** [jts/nanopolish#67]
Hi (again, sorry!),
I was running eventalign earlier with this command:

`nanopolish eventalign -t 8 --sam -r mydata.fasta -b reads.sorted.bam -g myreference.fasta --models nanopolish_models.fofn`

and got the following error message:
`nanopolish: ./src/common/nanopolish_alphabet.h:173: virtual std::string Alphabet::disambiguate(const string&) const: Assertion 'IUPAC::isValid(out[i]' failed.
Aborted`

After investigating the code, my reference sequences and my 2D read data I managed to figure out that nanopolish doesn't like lowercase bases in the reference sequence(s). Once I amended those bases to uppercase, eventalign worked as expected. 

Figured it was worth mentioning here for future releases?

**Comment by jts** [comment]
Ah, good catch. I'm not sure if I want to require the reference to be upper case (and emit a better error) or change the bases internally. I'll think about this, thanks for reporting.

**Comment by jts** [comment]
Finally fixed in 046e7c6, thanks for the report
