### ISSUE TITLE
Methylation Calling Soft Clip Question

### ISSUE THREAD

**Issue by mattdmem** [jts/nanopolish#670]
Hey,

Thanks for the great tool. Just wondering something.

I have reads which a large repeat sequence with flanking CpGs. This repeat is soft clipped, but along with it so is one of the flanking sequences. I'm interested in methylation either side of the repeat. How does nanopolish handle this? obviously one side of the repeat would be mapped properly so there is no problem there, then the other side is contained in the softclipped region. I get methylation calls for those bases, however, I have a sinking feeling that these are probably not correct (I do have reads in both directions though that agree).

Thanks for you help!

Matt

**Comment by jts** [comment]
Hi @mattdmem,

The softclipped parts of reads should not be called. This sounds like a bug, can you send an example?

Jared

**Comment by mattdmem** [comment]
Thanks Jared. I'll do some in-depth investigation this week and if I find out that I'm getting calls in these areas I'll send over some examples.

**Comment by jts** [comment]
Hi @mattdmem,

Any luck?
