### ISSUE TITLE
Empty VCF file during nanopolish variants

### ISSUE THREAD

**Issue by dcastaneda5** [jts/nanopolish#673]
Hi,

I was trying to run nanopolish variants in a server, and after an hour I obtained the following results:

```
Number of variants in span (15) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
[post-run summary] total reads: 41018, unparseable: 0, qc fail: 19, could not calibrate: 950, no alignment: 4911, bad fast5: 0
```

My workflow is as follows:

`nanopolish index -v -s <sequencing_summary.txt> -d <fast5_pass/> <barcode01.fastq>`

(the barcode01.fastq file is after trimming, demultiplexing and removing low quality reads with qcat; also it was indexed with sam faidx)

Then after indexing with nanopolish, I aligned my barcode to a reference using minimap2:

`minimap2 -ax msp2_reference.fasta barcode01.fastq > output1.sam`

I converted from .sam to .bam, sorted and indexed it. And finally I tried running the command that gave me that message:

`nanopolish variants --verbose --fix-homopolymers --ploidy=1 --threads=24 --min-candidate-frequency=0.20 --min-candidate-depth=20 --outfile=test --reads ../trim50_dem_q9/indexed_nanopolished_fastq/barcode01.fastq --bam /home/dcmogollon/nanopore/minimap2_alignment/mapped1.bam --genome ../gene_references/msp2_pf3d7_02026800.fasta`

My VCF file is empty too. Do you know what could be causing the problem? Thanks!

**Comment by jts** [comment]
Hi @dcastaneda5,

When you say the VCF is empty, do you mean there is nothing at all in `test` or does it print the VCF header but no variant records?

Jared

**Comment by dcastaneda5** [comment]
Hi Jared,

It's completely empty, with no headers.

**Comment by jts** [comment]
It looks like the run was successful so its strange that at least the VCF header didn't print. Can you re-run over a small region of the genome (`-w contig:start-end`) to see if it works? If this is targeted sequencing and you have excessive depth (>500X) you may wish to downsample the data (you can do this by downsampling the BAM file, you don't need to remove reads from the fastq).
