### ISSUE TITLE
Why nanopolish gives significantly higher coverage at CpG rich sites? 

### ISSUE THREAD

**Issue by vahidAK** [jts/nanopolish#674]
Hi @jts 
I realized that after methylation calling, the coverage is very much higher in methylated rich reagions compare to other sites. As you see in these pictures, the top track is coverage and the lower one is methylation frequency, and the coverage at CpG islands is unreasonably higher while the average coverage is 13x. Why the coverage is higher in CpG rich sites?

![Screenshot from 2019-10-18 17-23-41](https://user-images.githubusercontent.com/46334063/67135204-294c4f00-f1cc-11e9-9d01-8e6e2a8fe23b.png)  
  
  

![Screenshot from 2019-10-18 17-24-01](https://user-images.githubusercontent.com/46334063/67135205-2baea900-f1cc-11e9-8ed9-24f5e5c29c29.png)
  
Many thanks,
Vahid.

**Comment by jts** [comment]
Hi Vahid,

The output of nanopolish can be a little confusing when there are closely-spaced cpgs. Can you have a look at the discussion here and see if it helps resolve your issue:

https://github.com/jts/nanopolish/issues/365

Jared

**Comment by vahidAK** [comment]
Thanks @jts , I also had a question. Does "called_sites" column in methylation frequency file represent the coverage for that region?

**Comment by jts** [comment]
See here: https://github.com/jts/nanopolish/issues/646#issuecomment-528349951
