### ISSUE TITLE
cat slurm-32987210.out error: could not detect polishing window from input file polished.ctg

### ISSUE THREAD

**Issue by jhcaddisfly** [jts/nanopolish#675]
Hello,

I run the last step of nanopolish as follows:
nanopolish vcf2fasta --skip-checks -g /L2_Halesus_reads_racon1.fasta  polished.*.vcf > L2_racon1_nanopolished_genome.fa

but get the following error message:
error: could not detect polishing window from input file polished.ctg170:50000-100200.vcf

Do you know how to solve this issue?

Thanks,

J.

**Comment by jts** [comment]
The task that tried to generate that file (`polished.ctg170:50000-100200.vcf`) must have failed and the file is empty. Can you check if this is the case, and re-run it if necessary?

**Comment by jhcaddisfly** [comment]
Thanks for your quick response!

Yes, that is the case. However, re-running the file gave:
error: faidx could not get contig length for contig polished.ctg170

**Comment by jts** [comment]
Does that contig appear in the fasta file of the genome you're trying to polish?

**Comment by jhcaddisfly** [comment]
Yes, it does.

**Comment by jts** [comment]
Can you paste the command that failed?
