### ISSUE TITLE
Noob Question - Nanopore data Methylation call shows nothing

### ISSUE THREAD

**Issue by chansbro** [jts/nanopolish#679]
Hello.

I'm relatively new to this field, so please be aware of my noob question. 

I have bunch of human genome data sequenced using PromethION R9.4 flow cells. Then, Fast5 data were basecalled with Guppy Basecaller version 3.2.6. After basecalling, following steps were done to do methylation call. 

1. Multiple FastQ files were merged into single file using `cat *.fastq > merged.fastq`.

2. Created Fast5 index using nanopolish command.

3. Aligned FastQ data into the reference genome (GRChg38, 3.3 Gb file size) using minimap2. 

4. Aligned BAM file was sorted using samtools.

5. Index was created for BAM file using samtools. 

6. Performed nanopolish methylation call using the same reference genome over certain chromosome (e.g. chr20:5,000,000-10,000,000). Output shows none. 

7. Tried other chromosome sites, still showing none. 

Following these procedure above, I would expect to see at least few methylation sites as a result. But I'm not getting any... 

Does Nanopolish work with Guppy basecalled data instead of Albacore? 
Or am I using the wrong reference genome to be aligned and call methylation?

Thank you for your time in advance.
Seokchan

**Comment by jts** [comment]
Hi,

Can you show the exact command you ran, and the output it printed to the terminal?

Jared

**Comment by chansbro** [comment]
Okay. I will post several commands that I used.

Case 1
```bash
nanopolish call-methylation -t 30 -r merged.fastq -b output.sorted.bam -g reference.fasta

# Output
[E::fai_build3_core] Failed to open the file reference.fasta
chromosome	strand	start	end	read_name	log_lik_ratio	log_lik_methylated	log_lik_unmethylated	num_calling_strands	num_motifs	sequence
Segmentation fault


```

**Comment by jts** [comment]
Hi @chansbro,

The chromosome name (`chr20` or `NC_000020.11`) must match what is in the `reference.fa` file. For the tutorial chromosome 20 is called `chr20`, so we use that. For your reference file it is named differently, so you need to change that part of the command.

Jared

**Comment by chansbro** [comment]
Yeap. You are right. 
I now understand what's going on.
By the way, after getting the list of log_like_ratio from `call-methylation` command, 
what is the equation to convert log number into frequency? 

I was looking at `calculate_methylation_frequency.py` file, but I couldn't find the calculation part. 

Sorry for asking question with different topic... 

Seokchan

**Comment by jts** [comment]
The output of `call-methylation` is per read calls. `calculate_methylation_frequency` groups the per-read calls by reference base, applies a log likelihood threshold (default: 2.5) to make a binary call, then calculates the fraction of sites that are called as methylated.

**Comment by chansbro** [comment]
Hi @jts,

Okay. From what I understood so far,

1. Groups the read calls, meaning that group the same start and end position read. 
2. For each read call groups, compare `log_like_ratio` and threshold (default: 2.5) to make a binary call (yes as 1, no as 0).  --> **Q. By the way, how should we determine the log likelihood threshold??**
3. Calculate the fraction of methylation for each read call groups. 

Another question regarding the output file, if the number of motifs in group is five and methylated frequency is 0.88, then the entire five motifs show 88% of methylation frequency? 

Lastly, would you please refer me related research papers or textbooks to understand how methylation analysis work?

Thank you for your time in advance. 

Cheers,
Seokchan

**Comment by jts** [comment]
> Groups the read calls, meaning that group the same start and end position read.

Correct

> or each read call groups, compare log_like_ratio and threshold (default: 2.5) to make a binary call (yes as 1, no as 0). --> Q. By the way, how should we determine the log likelihood threshold??

Right now, we recommend using the default (2.5) although it is a conservative threshold and I may lower it in the future.

> Another question regarding the output file, if the number of motifs in group is five and methylated frequency is 0.88, then the entire five motifs show 88% of methylation frequency?

If nanopolish put 5 motifs into the same group, it considers them to all have the same methylation status. So 88% of the time, all 5 of the motifs would be methylated.

> Lastly, would you please refer me related research papers or textbooks to understand how methylation analysis work?

I'm not sure I can answer this, I leave the downstream methylation analysis to others.

jared

**Comment by chansbro** [comment]
Thanks, Jared.

All questions I had right now are resolved :)
