### ISSUE TITLE
Previous versions of nanopolish not compiling

### ISSUE THREAD

**Issue by shao4** [jts/nanopolish#68]
We're currently trying to analyze some old R7 runs, and are trying to compile Nanopolish v0.4.0 (tarball downloaded from the releases tab) using the makefile. After it fails and we try to make again, we end up with this issue: 

![image](https://cloud.githubusercontent.com/assets/11275847/18102165/9c6983b0-6ebf-11e6-9d96-47e990826fba.png)

Any insight into this would be appreciated (including which version of htslib is compatible (folder is empty) and any other necessary prereqs we may be missing). We are using ubuntu 16.04, g++ version 5.4.0. Thanks!

**Comment by jts** [comment]
Hi,

Thanks for the report. I also see that the `htslib` and `fast5` folders in the tarball are empty. Could you try cloning the repository instead?

Jared

**Comment by shao4** [comment]
Will the cloned repo work for R7 data?

**Comment by jts** [comment]
You can clone (using `--recursive` as in the README) then do `git checkout v0.4.0` to get the older version. Note that I will soon release a new version that supports both r7 and r9.

**Comment by shao4** [comment]
Hi Jared,

Trying that gave me this error:

![image](https://cloud.githubusercontent.com/assets/11275847/18106087/1628b6a2-6ed0-11e6-90ad-57ed4eec96d0.png)

Also, when do you estimate to release the next version of nanopolish?

Thanks!

**Comment by jts** [comment]
Hi,

It seems the problem is that doing `git checkout` on a tag doesn't update the submodules. Can you go into the `fast5` directory and do `git checkout 0639cc5` to update fast5 to the version compatible with v0.4? 

I'll release the r7/r9 version sometime this week.

Jared

**Comment by mateidavid** [comment]
Try:

    git checkout v0.4.0
    git submodule update

Then compile as usual.

**Comment by jts** [comment]
The dual r7/r9 version is now on github.
