### ISSUE TITLE
nanopolish eventalign skip state

### ISSUE THREAD

**Issue by TongChengxuan** [jts/nanopolish#680]
Dear Jared,

I have some queries on the output of nanopolish eventalign
1. The NNNNNN in the output file indicate the bad state described in the paper?
2. For the same read, a position have multiple event, but one of the event seems to be coming from an adjacent position, how does this happened? Is there a way to fixed this.
3. I observed some position ad significantly lower number of event compared than other position for the whole library, is this due to the skip state? But according to your paper that R9 model have constant skip probability. Or is this a indication of indels?
4. If there is a N in the reference genome, what is the behavior of nanopolish? I do not see N appear in the reference kmer at the position that should contains N. Will the kmer that contains N 
more likely to be skipped?

Best regards,
Tong Chengxuan

**Comment by jts** [comment]
Hi @TongChengxuan,

> The NNNNNN in the output file indicate the bad state described in the paper?

That's right.

> For the same read, a position have multiple event, but one of the event seems to be coming from an adjacent position, how does this happened? Is there a way to fixed this.

Can you show me an example from eventalign for this? I'm not sure I understand

> I observed some position ad significantly lower number of event compared than other position for the whole library, is this due to the skip state? But according to your paper that R9 model have constant skip probability. Or is this a indication of indels?

The skip transition probability is a prior, the observed skip rate will depend on local sequence context and how similar the k-mer levels are for the adjacent states.

> If there is a N in the reference genome, what is the behavior of nanopolish? I do not see N appear in the reference kmer at the position that should contains N. Will the kmer that contains N
more likely to be skipped?

Nanopolish will change the N to a randomly chosen base. These regions should be avoided in subsequent analysis.
