### ISSUE TITLE
what's the algorithm of nanopolish

### ISSUE THREAD

**Issue by LinXialab** [jts/nanopolish#681]
Excuse me, we want to learn the algorithm of the nanopolish, could you please tell us which article is worthy learning and studying.

**Comment by jts** [comment]
Hi,

The main idea is here:

https://www.nature.com/articles/nmeth.3444

Methylation calling:

https://www.nature.com/articles/nmeth.4184

These slides may help too:

https://www.slideshare.net/jaredsimpson/170216-jts-agbtfinal

Jared

**Comment by LinXialab** [comment]
Thank you so much!

Jared Simpson <notifications@github.com> 于2019年10月31日周四 下午9:17写道：
