### ISSUE TITLE
Non CpG methylation calling?

### ISSUE THREAD

**Issue by vahidAK** [jts/nanopolish#682]
Hi @jts 
I was wondering that nanopolish does have a model for non-CpG methylation calling?

Best,
Vahid

**Comment by jts** [comment]
It has a model for Dam and Dcm methylation that is present in some bacteria. We are working on a model for GpC methylation too.

Jared

**Comment by vahidAK** [comment]
So it does not do that for human?

**Comment by jts** [comment]
You can run any of those models on any input samples.

**Comment by vahidAK** [comment]
Yes! But how accurate do you think that can be? Is it reliable?

**Comment by jts** [comment]
Well if you ran the Dam model on human samples I would expect very few calls, and the calls that are made would be false positives since humans don't have this type of methylation.

Maybe I don't understand the question though?

**Comment by vahidAK** [comment]
Thanks @jts , 
You answered my question, Basically, I was asking that can we call non-CpG methylation (Cs that are not in CpG context. e.g CA, CC, AC etc) in humans using nanopolish and its current models. So, the short answer is no?

Sorry, I have another question, in your paper, you built your model based on pore R7.3 and R9. But in your model folder, the names of some models are R9.4. Are these models the new updated ones?

Also, I am curious to know why you used 6-mer alphabet for R9.4 model. Because, as far as I know, the electrical resistance of a pore is determined by the bases present within multiple nucleotides that reside in the pore’s narrowest point (approximately five nucleotides for the R9.4 pore), so it makes more sense to have 5bp alphabet?
Thanks,
Vahid

**Comment by jts** [comment]
Correct.

> Sorry, I have another question, in your paper, you built your model based on pore R7.3 and R9. But in your model folder, the names of some models are R9.4. Are these models the new updated ones?

R9.4 is an updated version of the R9 pore and different enough that we trained a new model for it.

> [...] so it makes more sense to have 5bp alphabet?

As you say, the k-mer length is an approximation to what is going on in the pore. Longer k-mers will always capture more information, but are harder to train. For R9 6-mers seem to give a good balance between how much signal they capture and how large the model is.

Jared

**Comment by vahidAK** [comment]
Thanks a lot, @jts for your time and responses.

**Comment by jts** [comment]
No problem
