### ISSUE TITLE
Nanopolish methylation call segmentation error

### ISSUE THREAD

**Issue by vahidAK** [jts/nanopolish#683]
Hi @jts 

I have been seeing the following error when I am trying to index or calling methylation:

HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140592415237888:
  #000: H5A.c line 642 in H5Aread(): unable to read attribute
    major: Attribute
    minor: Read failed
  #001: H5Aint.c line 661 in H5A_read(): datatype conversion failed
    major: Attribute
    minor: Unable to encode value
  #002: H5T.c line 4816 in H5T_convert(): data type conversion failed
    major: Attribute
    minor: Unable to encode value
  #003: H5Tconv.c line 3274 in H5T__conv_vlen(): can't read VL data
    major: Datatype
    minor: Read failed
  #004: H5Tvlen.c line 891 in H5T_vlen_disk_read(): Unable to read VL information
    major: Datatype
    minor: Read failed
  #005: H5HG.c line 622 in H5HG_read(): unable to protect global heap
    major: Heap
    minor: Unable to protect metadata
  #006: H5HG.c line 262 in H5HG_protect(): unable to protect global heap
    major: Heap
    minor: Unable to protect metadata
  #007: H5AC.c line 1320 in H5AC_protect(): H5C_protect() failed.
    major: Object cache
    minor: Unable to protect metadata
  #008: H5C.c line 3574 in H5C_protect(): can't load entry
    major: Object cache
    minor: Unable to load metadata into cache
  #009: H5C.c line 7954 in H5C_load_entry(): unable to load entry
    major: Object cache
    minor: Unable to load metadata into cache
  #010: H5HGcache.c line 141 in H5HG_load(): bad global heap collection signature
    major: Heap
    minor: Unable to load metadata into cache
error reading attribute experiment_type
./nanopolish_command.sh: line 18: 40216 Segmentation fault      (core dumped)

**Comment by jts** [comment]
Can you try indexing without using the sequencing summary file?

**Comment by vahidAK** [comment]
I indexed without that.
Is it an issue from nanopolish or because of my HDF5 library?
Cause I have already analyzed the same data with nanopolish without getting such error.

**Comment by jts** [comment]
What is different between when it worked and now, when it doesn’t?

**Comment by vahidAK** [comment]
Nothing really, the data and index is exactly same and I use the same nanopolish I installed. 
I am working on server and recently had issue to install some software.
I did export some libraries to my path to overcome those errors like this:
export PATH=/gsc/software/linux-x86_64-centos7/gcc-7.2.0/bin:$PATH
export PATH=/gsc/software/linux-x86_64-centos7/samtools-1.9/bin:$PATH
export PATH=/gsc/software/linux-x86_64-centos7/bwa-0.7.13:$PATH
export LD_LIBRARY_PATH=/gsc/software/linux-x86_64-centos7/gcc-7.2.0/lib64:$LD_LIBRARY_PATH

**Comment by jts** [comment]
Did you install nanopolish from source or with conda?

**Comment by vahidAK** [comment]
I installed from source step by step as you provided in github

**Comment by jts** [comment]
Ok, in that case it installed its own hdf5 and other libraries so that shouldn’t be the problem. 

Since it was previously working I’m not sure how much help I can give. If you have any other information (like details about the fast5, the exact commands you ran) it would be helpful

**Comment by vahidAK** [comment]
Oh! I think I found the problem. **MY BAD**, so sorry.
I completely forgot that I changed the name of the folder including fast5 files and in my readdb the path is for the previous name. I modified the path of files by sed -i 's/wrong/correct_path/' *readdb.
I will let you know if it worked.

**Comment by vahidAK** [comment]
Hi @jts 
I indexed the fastq file again and did methylation calling. After a while and writing methylation call results I got this error:
$nanopolish index -d fast5s/ merged_guppy.fastq
[readdb] indexing /projects/vakbari_prj/scratch/NA12878_fast5s/
[readdb] num reads: 5599945, num reads with path to fast5: 5599945

$nanopolish call-methylation -t 64 -q cpg -r merged_guppy.fastq -b merged_guppy.sorted.bam -g hg38.fa > methylation_calls.tsv
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140612119774976:
 #000: H5A.c line 642 in H5Aread(): unable to read attribute 
major: Attribute
minor: Read failed
#001: H5Aint.c line 661 in H5A_read(): datatype conversion failed
 major: Attribute
minor: Unable to encode value
#002: H5T.c line 4816 in H5T_convert(): data type conversion failed
major: Attribute
minor: Unable to encode value
#003: H5Tconv.c line 3274 in H5T__conv_vlen(): can't read VL data 
major: Datatype
minor: Read failed
#004: H5Tvlen.c line 891 in H5T_vlen_disk_read(): Unable to read VL information
major: Datatype
minor: Read failed
#005: H5HG.c line 622 in H5HG_read(): unable to protect global heap 
major: Heap
minor: Unable to protect metadata
#006: H5HG.c line 262 in H5HG_protect(): unable to protect global heap
major: Heap
minor: Unable to protect metadata
 #007: H5AC.c line 1320 in H5AC_protect(): H5C_protect() failed.
 major: Object cache
minor: Unable to protect metadata 
#008: H5C.c line 3574 in H5C_protect(): can't load entry
major: Object cache
minor: Unable to load metadata into cache
#009: H5C.c line 7954 in H5C_load_entry(): unable to load entry
major: Object cache
 minor: Unable to load metadata into cache
 #010: H5HGcache.c line 141 in H5HG_load(): bad global heap collection signature
major: Heap
minor: Unable to load metadata into cache
error reading attribute experiment_type
nanopolish: src/nanopolish_squiggle_read.cpp:304: void SquiggleRead::load_from_raw(fast5_file&, uint32_t): Assertion `this->base_model[strand_idx] != __null' failed.
 ./nanopolish_command.sh: line 18:  7364 Aborted
(core dumped)

**Comment by jts** [comment]
Can you run ldd on the nanopolish binary? What version of nanopolish are you using?

**Comment by vahidAK** [comment]
(base) [vakbari@gphost14 Nanopolish_NA12878]$ ~/Software/nanopolish/nanopolish --version                                nanopolish version 0.11.1
Written by Jared Simpson.
 Copyright 2015-2017 Ontario Institute for Cancer Research
(base) [vakbari@gphost14 Nanopolish_NA12878]$ ldd ~/Software/nanopolish/nanopolish                                              linux-vdso.so.1 =>  (0x00007ffde5d37000)
libz.so.1 => /lib64/libz.so.1 (0x00007f60b172f000)
librt.so.1 => /lib64/librt.so.1 (0x00007f60b1527000)
 libdl.so.2 => /lib64/libdl.so.2 (0x00007f60b1322000)
libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f60b101b000)
 libm.so.6 => /lib64/libm.so.6 (0x00007f60b0d19000)                                                                      
libgomp.so.1 => /lib64/libgomp.so.1 (0x00007f60b0af2000)
 libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f60b08dc000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f60b06c0000)
 libc.so.6 => /lib64/libc.so.6 (0x00007f60b02f2000)
/lib64/ld-linux-x86-64.so.2 (0x000055c82c997000)

**Comment by jts** [comment]
Can you try to determine which fast5 causes the problem (try running on small regions with fewer threads) and send it to me?

Jared

**Comment by vahidAK** [comment]
Sure! I will try.
The other thing is that the error is now always at the same output size. For example, right now the output methylation call file is 740 Mb that I saw the error. but if I run it again it may give me a 2 Gb output and the crash by error.

**Comment by jts** [comment]
@vahidAK are you using this data? https://github.com/nanopore-wgs-consortium/NA12878

**Comment by vahidAK** [comment]
Yes, @jts

**Comment by jts** [comment]
There is an old dataset (R9 before R9.4) which is probably causing the problem. Can you try without that dataset?

Jared

**Comment by vahidAK** [comment]
hmm, yes probably.
Sure! I'll try
Thanks a lot
