### ISSUE TITLE
index problem

### ISSUE THREAD

**Issue by huandna** [jts/nanopolish#685]
Hi
When I use Nanopolish index the fasta file，The following problems were encountered:
my version of nanopolish is the latest，and I am sure the fast5 file could be index for I had did it successfuly using an older version of  nanopolish，sorry for I forgot the specific version number.Now I need to reproduce with the new version, I don't know what the problem is, is there any change in the new version in index ? 

there is my command：
`nanopolish index -d $fast5_dir -f $summry $readpath/reads.fasta
`
`head  $summry`

/share/home/yaoxinw/data/11.17.fast5/yeast/nas/hanyue/Data/20171214yeast303/GA10000/sequencing_summary_0.txt
/share/home/yaoxinw/data/11.17.fast5/yeast/nas/hanyue/Data/20171214yeast303/GA10000/sequencing_summary_100.txt
/share/home/yaoxinw/data/11.17.fast5/yeast/nas/hanyue/Data/20171214yeast303/GA10000/sequencing_summary_101.txt
/share/home/yaoxinw/data/11.17.fast5/yeast/nas/hanyue/Data/20171214yeast303/GA10000/sequencing_summary_102.txt

`head /share/home/yaoxinw/data/11.17.fast5/yeast/nas/hanyue/Data/20171214yeast303/GA10000/sequencing_summary_0.txt`

filename        read_id run_id  channel start_time      duration        num_events      template_start  num_events_template     template_duration       sequence_length_template        mean_qscore_template    strand_score_template
GXB01043_20171214_FAH30662_GA10000_mux_scan_20171214yeast303_57183_read_11_ch_268_strand.fast5  54ec1292-29e9-44e2-ac97-32c59c205b09    16d7e7597aa51f731e496bd24e190a11b19e2e40        268
     5.95425 1.14375 915     5.95425 915     1.14375 422     11.2722 -0.00148793
GXB01043_20171214_FAH30662_GA10000_mux_scan_20171214yeast303_57183_read_5_ch_470_strand.fast5   597852c2-ad1b-48ee-a8fa-3f05bf14f9e4    16d7e7597aa51f731e496bd24e190a11b19e2e40        470
     6.1915  1.187   949     6.1915  949     1.187   538     6.90996 -0.00144222
GXB01043_20171214_FAH30662_GA10000_mux_scan_20171214yeast303_57183_read_5_ch_492_strand.fast5   d62efe48-8dc8-4b5b-b27f-91c7549efee0    16d7e7597aa51f731e496bd24e190a11b19e2e40        492
     5.9925  1.5     1200    5.9925  1200    1.5     643     10.8143 -0.00236351
GXB01043_20171214_FAH30662_GA10000_mux_scan_20171214yeast303_57183_read_7_ch_319_strand.fast5   69e2d577-be1f-48a7-b658-cb54f2c640e1    16d7e7597aa51f731e496bd24e190a11b19e2e40        319
     5.961   1.33525 1068    5.961   1068    1.33525 588     10.5001 -0.00278391
GXB01043_20171214_FAH30662_GA10000_mux_scan_20171214yeast303_57183_read_5_ch_322_strand.fast5   4d3c9e1f-6e49-4271-8e83-f5b030d2c57e    16d7e7597aa51f731e496bd24e190a11b19e2e40        322
     6.51475 1.05925 847     6.51475 847     1.05925 448     10.5423 -0.00209421

my error：

warning: detected invalid summary file entries for 1925461 of 1925461 fast5 files
These files will be indexed without using the summary file, which is slow.
[readdb] indexing /share/home/yaoxinw/data/11.17.fast5/yeast/nas/hanyue/Data/20171214yeast303/GA10000/reads/
could not open fast5 file: /share/home/yaoxinw/data/11.17.fast5/yeast/nas/hanyue/Data/20171214yeast303/GA10000/reads//267
could not open fast5 file: /share/home/yaoxinw/data/11.17.fast5/yeast/nas/hanyue/Data/20171214yeast303/GA10000/reads//471

**Comment by jts** [comment]
Hi,

I think I know what the problem is and I'll try to provide a fix tomorrow.

Jared

**Comment by huandna** [comment]
Thank you very much for reply

**Comment by jts** [comment]
This should now be fixed, can you update to the lastest version on github and let me know if it solves your problem?

**Comment by huandna** [comment]
yeah ，I used  the lastest version on github to do ：
`nanopolish index -d $fast5_dir -f $summry $readpath/reads.fasta `
and it worked，thank you again

**Comment by jts** [comment]
great, thanks for letting me know.
