### ISSUE TITLE
missing .readdb file after nanopolish index

### ISSUE THREAD

**Issue by KLC409** [jts/nanopolish#686]
Hi

A very basic question i'm sure, but i'm new to this, so apologies, but i cant find the answer anywhere else.  

I am trying to carry out nanopolish index on fast5 files but keep getting the same error.

My code is:
nanopolish index -d fast5_pass/ -s sequencing_summary.txt raw.fastq.gz
where "fast5_pass" is the directory containing fast5 files and "raw.fastq.gz" is my zipped file containing all fastq files.

I get output in the form of:
raw.fastq.gz.index
raw.fastq.gz.index.gzi
raw.fastq.gz.index.fai

But 
raw.fastq.gz.index.readdb is missing.

I also get the following error:
[readdb] indexing fast5_pass/
Error: no fast5 files found

The fast5_pass/ directory contains all of the fast5 files.
I have tried doing the same command with various versions of "fast5_pass/" such as 
"/fast5_pass/*.fast5" and other variations, and have tried using raw.fastq (unzipped), raw.fasta, but always the same error.

I thought maybe i could carry on without having this .readdb file since the other files are present but when i try:
nanopolish call-methylation -t 8 -r raw.fastq.gz -b wgs.sorted.bam -g genome.fa > raw_methylation_calls.tsv

I get this error message:
error: could not load the index files for input file org_692_longread.fastq.gz
Please run nanopolish index on your reads (see documentation)

So, its obviously not happy that i dont have the .readdb file.
 
Any help gratefully received
Thanks
Kate

**Comment by KLC409** [comment]
Also, i see in issue #564 there was a problem with not using the correct version of nanopolish for PromethION fast5 files.  

I am using:
nanopolish version 0.10.1

Could this be the problem? Do i need to upgrade to version 0.11.0 or later?

Thanks very much
Kate

**Comment by jts** [comment]
Hi Kate,

Can you please try with the latest code from github? There have been changes to the summary files lately so 0.10.1 may not work.

Thanks,
jared

**Comment by KateChew** [comment]
Hi, thanks for your help.  Have tried it now with version 0.11.0 but still the same problem.  Any thoughts?

Regards
Kate
(this is my new login, but still the same person as KLC409)

**Comment by jts** [comment]
Hi @KateChew,

0.11.0 is a bit old (Jan 2019), can you try 0.11.2? If it still doesn't work can you paste in your reply the exact command you ran?

Jared

**Comment by KateChew** [comment]
Hi, so problem solved.

The version 0.11.0 turned out to be fine.  The issue was that  my sequencing_summary.txt file, which came direct from the sequencer, contained the column header "filename_fast5" instead of just "filename" and therefore nanopolish couldn't find the column of fast5 files. Column header changed and now runs fine.
Thanks for your help
Kate

**Comment by jts** [comment]
Hi Kate,

Thanks for letting me know. This was fixed in the most recent version so if you update you won't have to change the column names of your summary files for future runs.

Jared
