### ISSUE TITLE
how to read the content of *fastq.index

### ISSUE THREAD

**Issue by Huanle** [jts/nanopolish#687]
Hi There,
How is the results from nanopolish indexed?
```
nanopolish index -d ${f5_dir}/workspace/pass/0/ -s ${f5_dir}/sequencing_summary.txt test.fastq 
```
the above command produces test.fastq.index and test.fastq.index.gzi, which are encoded into binaries. what type of encoding has been performed? how to read the content of them?

Also, the test.fastq.index.fai file has 5 columns. Two of them are obviously read name and read length. What are the rest?

Thanks a lot. I look forward to your help.

**Comment by jts** [comment]
Hi @Huanle,

The index files are:

-`X.index`: a bgzip-compressed fasta file. `zcat X.index` will show you the contents
-`X.index.gzi` and `X.index.fai` allow random access to a read's sequence. they are created by the equivalent of `samtools faidx`.
-`X.index.readdb` is a simple TSV file mapping read names to fast5 files.

I hope this helps,
Jared

**Comment by Huanle** [comment]
thanks @jts . simpler than I thought. :)
