### ISSUE TITLE
vbz compression compatibilty

### ISSUE THREAD

**Issue by nick297** [jts/nanopolish#688]
Hello,

With nanopore releasing the options to compress fast5 files by default (https://community.nanoporetech.com/posts/improved-fast5-compression-5353), will nanopolish be compatible without having to decompress the files first? I understand they have released tools to enable this https://github.com/nanoporetech/vbz_compression/

Thanks,
Nick

**Comment by jts** [comment]
Hi Nick,

Yes, we intend to natively support compressed fast5 files (without decompression). I have not yet figured how to do this as I'll have to integrate the plugins into the version of HDF5 that nanopolish builds but I will definitely work on it.

Jared

**Comment by nick297** [comment]
Great! Thank you Jared
Nick
