### ISSUE TITLE
Assertion `read->read_type != SRT_2D' failed. nanopolish_train_poremodel_from_basecalls

### ISSUE THREAD

**Issue by gkutish** [jts/nanopolish#69]
i got an error with nanopolish  train-poremodel-from-basecalls --verbose pass.fofn &>log.base

Loading ./pass/DESKTOP_TEOOQR9_20160726_FNFAD22371_MN17911_sequencing_run_07_26_16_Edan_DNA_18470_ch429_read2252_strand.fast5
Loaded 40 reads
nanopolish: src/nanopolish_train_poremodel_from_basecalls.cpp:259: int train_poremodel_from_basecalls_main(int, char**): Assertion `read->read_type != SRT_2D' failed.

**Comment by jts** [comment]
Hi @gkutish,

The submodule `train-poremodel-from-basecalls` is not really part of the core functionality and only for internal development. If you let me know what you're trying to do I might be able to suggest an alternative workflow.

Jared

**Comment by gkutish** [comment]
Jared,my data is high a/t and i wanted to try a model different thanthe template_median68pA.model included with your nanopolishprogram. thanksgerald kutish

---------- Original Message ----------

**Comment by jts** [comment]
Interesting. I would guess that it is best to use the built-in model. If you would like to explore training a new model, you should provide 1D reads to this program, not 2D.
