### ISSUE TITLE
nanopolish eventalign with --sample flag leads to core dumped

### ISSUE THREAD

**Issue by pabloacera** [jts/nanopolish#690]
I am running nanopolish eventalign with dRNA :

`nanopolish eventalign --reads ../fastq/sythetic.fastq --genome ../ligated_oligo.fa --bam ../alignment/minimap_filtered.bam --samples  > eventalign.txt
terminate called without an active exception
Aborted (core dumped)
`
But if I run it without the --samples flag it works fine

`nanopolish eventalign --reads ../fastq/sythetic.fastq --genome ../ligated_oligo.fa --bam ../alignment/minimap_filtered.bam > eventalign.txt
[post-run summary] total reads: 270, unparseable: 0, qc fail: 13, could not calibrate: 6, no alignment: 0, bad fast5: 0`

I know there is a close issue about this but do not know what happened here.

**Comment by jts** [comment]
Which version of nanopolish are you using?

Jared

**Comment by pabloacera** [comment]
I see, not the newest,  0.9.0. It is cause I installed like this:

`$sudo apt-get install nanopolish
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nanopolish is already the newest version (0.9.0-1).
The following package was automatically installed and is no longer required:
  libllvm7
Use 'sudo apt autoremove' to remove it.
0 to upgrade, 0 to newly install, 0 to remove and 129 not to upgrade.
`
It is working with the current version, 
Thanks a lot, 
Pablo
