### ISSUE TITLE
Extracting fastq basecalled with Guppy with nanopolish

### ISSUE THREAD

**Issue by touala** [jts/nanopolish#691]
Hello,

It seems that `nanopolish extract` command is broken (v0.11.2) when fast5 are basecalled with Guppy (v3.2.4).
```
nanopolish extract -v -r -q /path/to/read.fast5 -o read.fastq                                                 
= extract.2 nanopolish_extract.cpp:386 parse_extract_options paths: /path/to/read.fast5
= extract.2 nanopolish_extract.cpp:387 parse_extract_options recurse: yes
= extract.2 nanopolish_extract.cpp:388 parse_extract_options read_type: 2d-or-template
= extract.2 nanopolish_extract.cpp:389 parse_extract_options basecaller_name: 
= extract.2 nanopolish_extract.cpp:390 parse_extract_options basecaller_version: 
= extract.2 nanopolish_extract.cpp:245 process_path /path/to/read.fast5
= extract.2 nanopolish_extract.cpp:185 process_file file [/path/to/read.fast5]: no basecalling data suitable for nanoplish
[extract] found 1 files, extracted 0 reads
```
Did I misused the command? If not, do you plan to update the code?

Thanks for your help.

**Comment by jts** [comment]
Extract is only used for very old data (before 2017). For recent data you should just use the guppy basecalls and nanopolish index.

Jared

**Comment by touala** [comment]
Thank you for the quick answer. I was using nanopolish to extract reads after subsetting my datasets as it was more convenient (because already loaded in my pipeline). I will swap it with another solution.

Thanks again Jared.
