### ISSUE TITLE
draft sequence gaps ans mismatches

### ISSUE THREAD

**Issue by BioRB** [jts/nanopolish#692]
if I have a draft sequence with few errors, does nanopolish will produce a better final consensus sequence compared to the one produced by providing a draft sequence with many gaps and mismatches or independently to the quality of the draft sequence provided, nanopolish will be able to fix any gaps ( any size) and mismatches? 
Better input = better output or good input = bad input

**Comment by jts** [comment]
Nanopolish performs best when the draft is high quality and the errors are small and sparse. It is not able to effectively fix large errors (>5bp complex indels, structural variations, etc).
