### ISSUE TITLE
Indexing error in current release (invalid summary file) 

### ISSUE THREAD

**Issue by scogi** [jts/nanopolish#693]
Hi!

I just wanted to start an assembly polishing, but when indexing a fastq file for later polishing I get the error

```
nanopolish index -d fast5/ -s basecalled/sequencing_summary.txt basecalled/20191121_run1.fastq
warning: detected invalid summary file entries for 26 of 26 fast5 files
These files will be indexed without using the summary file, which is slow.
```

I could not figure out what the issue is. The data was collected last week with LSK109. Basecalling was done offline with guppy 3.3.3 and demultiplexing subsequently with qcat 1.1.0.

I get the error on all fastq files that I have from different analysis stages:
-  the original fastq from guppy 3.3.3. (not demultiplexed)
- the demultiplexed fastq file
- on fastq files which have been selected for read length. 

The headers in the fastq files do not seem to have changed in any of the derived files, but the error occurs also with the original fastq. 
Nanopolish has been downloaded freshly from github (0.11.2). 

Thank you for any help!
Stefan

**Comment by jts** [comment]
Hi @scogi,

That is just a warning so you can ignore it. Currently the fast5 filenames in the summary might be ambiguous, so nanopolish has to ignore the summary file entries for those files and index them in a slower way. The subsequent index will be fine though so you can carry on with the rest of your analysis.

Jared

**Comment by scogi** [comment]
I see. Thank you for the clarification!
Stefan
