### ISSUE TITLE
variants --consensus running for 17 days

### ISSUE THREAD

**Issue by SR-Martin** [jts/nanopolish#694]
Hi,

I'm running nanopolish (version 0.11.1) on a cluster (running slurm). One of the variants --consensus jobs has taken 17 days and is still going. I thought this could be a broken node, but when trying again the same tig is stuck. All others have finished. Any idea what the problem is? Here is the command:

nanopolish variants --consensus -o polished_tigs/polished.${tigs[${SLURM_ARRAY_TASK_ID}]}.vcf -w ${tigs[${SLURM_ARRAY_TASK_ID}]} -r ${reads} -b reads.sorted.bam -g ${draft} -t 4 --min-candidate-frequency 0.1

Output is attached.

Thanks!

[nanopolish_script3-24921380_483.txt](https://github.com/jts/nanopolish/files/3911517/nanopolish_script3-24921380_483.txt)

**Comment by jts** [comment]
What does the `-w` argument expand to in this case?

Jared

**Comment by SR-Martin** [comment]
-w contig_323:0-50200

This is from running the script nanopolish_makerange.py on a flye assembly.

**Comment by jts** [comment]
Based on the error log nanopolish has found a lot of candidate variants in this region and is having trouble assembling them into haplotypes.

What do the read mappings look like in IGV for this region?

**Comment by SR-Martin** [comment]
They look messy... coverage is pretty high (~3000x) and there are a lot of mismatched bases. Here's a screenshot: 
![Screenshot 2019-12-11 at 16 18 14](https://user-images.githubusercontent.com/39562021/70639259-2309aa80-1c32-11ea-8fe7-c52221f0c615.png)

On the next section of this contig, for which the job finished, the coverage is much lower. Do you think it could legitimately take a few weeks?

Unfortunately the job that was running was killed due to an HPC disruption, so I've started it again (running for 7 days so far).

**Comment by jts** [comment]
I doubt much useful polishing will happen in this section so I'd ignore the segment and run the next step (`vcf2fasta`) with the `--skip-checks` option. Alternatively you can try turning --max-haplotypes down to something like 32, or try downsampling coverage.

Jared

**Comment by SR-Martin** [comment]
Okay, I'll try that. Thanks!

**Comment by SR-Martin** [comment]
The job finished after being submitted using the option --max-haplotypes=32.
