### ISSUE TITLE
nanopolish variants --consensus is not able to load fasta.index files

### ISSUE THREAD

**Issue by wgallin** [jts/nanopolish#696]
I am unable to get nanopolish consensus to work.
I am running on a HPC cluster, 48 cpus, 187.5 G of RAM.
The running directory contains the following files at the start of the run:
-rw-r--r-- 1 wgallin wgallin   254858525 Dec  2 14:28 191111_gt20kb_Assembly.fasta
-rw-r--r-- 1 wgallin wgallin       96309 Dec  3 08:15 191111_gt20kb_Assembly.fasta.fai
drwxrwxrwx 2 wgallin wgallin      200704 Nov 13 11:31 191113_FAST5_Pooled
-rw-r--r-- 1 wgallin wgallin         633 Dec  2 14:44 191113_minimap2_align.sh
-rw-r--r-- 1 wgallin wgallin         462 Dec  3 19:45 191113_nanopolish_index_job.sh
-rw-r----- 1 wgallin wgallin         619 Dec  4 19:22 191203_nanopolish_new.sh
-rw-r--r-- 1 wgallin wgallin 33904895362 Dec  4 08:16 All_Reads.fasta
-rw-r----- 1 wgallin wgallin  9315296765 Dec  4 23:40 All_Reads.fasta.index
-rw-r----- 1 wgallin wgallin   552344136 Dec  4 23:45 All_Reads.fasta.index.fai
-rw-r----- 1 wgallin wgallin     8310024 Dec  4 23:45 All_Reads.fasta.index.gzi
-rw-r----- 1 wgallin wgallin   740985848 Dec  4 23:46 All_Reads.fasta.index.readdb
-rw-r--r-- 1 wgallin wgallin 18471892328 Dec  4 17:40 reads.sorted.bam
-rw-r--r-- 1 wgallin wgallin    12569360 Dec  4 17:46 reads.sorted.bam.bai
-rw-r--r-- 1 wgallin wgallin  2792280340 Dec  2 14:30 sequencing_summary.txt
-rw-r--r-- 1 wgallin wgallin 18471892328 Dec  4 17:40 reads.sorted.bam
-rw-r--r-- 1 wgallin wgallin    12569360 Dec  4 17:46 reads.sorted.bam.bai
-rw-r--r-- 1 wgallin wgallin  2792280340 Dec  2 14:30 sequencing_summary.txt

The running command in the SLURM submission script is:
python3 $EBROOTNANOPOLISH/scripts/nanopolish_makerange.py ${MYWROKDIR}/191111_gt20kb_Assembly.fasta | parallel --workdir ${MYWROKDIR} --results ${MYWROKDIR}/nanopolish.r
esults -j 48 --joblog ${MYWROKDIR}/191203_Job.log --resume --tmpdir ${MYWROKDIR}/Temp_Parallel nanopolish variants --consensus -o ${MYWROKDIR}/polished.{1}.vcf -w {1} -r
 ${MYWROKDIR}/All_reads.fasta -b ${MYWROKDIR}/reads.sorted.bam -g ${MYWROKDIR}/191111_gt20kb_Assembly.fasta -t 1 --min-candidate-frequency 0.1

The SLURM submission works and the whole job finishes in about 10 minutes or less.
All the expected .vcf files are created, but they only have the headers, no actual results, and the slurm output file is basically repeats of:

error: could not load the index files for input file /home/wgallin/scratch/191202_Genome_Polishing/All_reads.fasta
Please run nanopolish index on your reads (see documentation)
error: could not load the index files for input file /home/wgallin/scratch/191202_Genome_Polishing/All_reads.fasta
Please run nanopolish index on your reads (see documentation)
error: could not load the index files for input file /home/wgallin/scratch/191202_Genome_Polishing/All_reads.fasta
Please run nanopolish index on your reads (see documentation)

However, the index files are all there indexing appears to have worked, in that the files are large and the readdb file shows the expected pairing of fasta id and a pointer to the corresponding FAST5 file. First few lines example:

0000055c-59fc-4a3d-bce6-76f40a992d75	191113_FAST5_Pooled/GonMan3_353.fast5
00000831-1d73-4010-b82b-3fc35b4b3017	191113_FAST5_Pooled/FAK85871_ae79bc6cd9d7d044be4da4bedffb38477e9df319_5.fast5
0000085c-2ec5-4ed1-9691-ada6a30ef2cc	191113_FAST5_Pooled/GonMan3_122.fast5
00000934-bf35-4667-a63c-50a58f66d906	191113_FAST5_Pooled/Ind5_536.fast5
00000957-3f45-4f44-b843-53c3d9fffba7	191113_FAST5_Pooled/FAK68890_e9fe4f6297ea3ee60ac9aef72348a9c86621e695_3.fast5
00000b8b-83f7-4671-87ef-b95117d2b455	191113_FAST5_Pooled/Ind5_1303.fast5

The individual output from the Job log for the first chunk is:

Seq	Host	Starttime	JobRuntime	Send	Receive	Exitval	Signal	Command
1	:	1575532008.677	     4.625	0	0	1	0	nanopolish variants --consensus -o /home/wgallin/scratch/191202_Genome_Polishing/polished
.0_length_1426604:0-50200.vcf -w 0_length_1426604:0-50200 -r /home/wgallin/scratch/191202_Genome_Polishing/All_reads.fasta -b /home/wgallin/scratch/191202_Genome_Polishi
ng/reads.sorted.bam -g /home/wgallin/scratch/191202_Genome_Polishing/191111_gt20kb_Assembly.fasta -t 1 --min-candidate-frequency 0.1

so it looks like the correct files are being pointed to, but for some reason the index files are not being loaded, in spite of the .

The same job with a subset of only reads >10kb runs fine on a different cloud setup, so I am at a loss as to what may be going on.

Any advice or suggestions would be appreciated.

**Comment by wgallin** [comment]
Additionally, when I run just one of the commands I get the following:

nanopolish variants --consensus -o /home/wgallin/scratch/191202_Genome_Polishing/polished.0_length_1426604:0-50200.vcf -w 0_length_1426604:0-50200 -r /home/wgallin/scratch/191202_Genome_Polishing/All_reads.fasta -b /home/wgallin/scratch/191202_Genome_Polishing/reads.sorted.bam -g /home/wgallin/scratch/191202_Genome_Polishing/191111_gt20kb_Assembly.fasta -t 1 --min-candidate-frequency 0.1
error: could not load the index files for input file /home/wgallin/scratch/191202_Genome_Polishing/All_reads.fasta
Please run nanopolish index on your reads (see documentation)

**Comment by jts** [comment]
Hi,

The paths are case sensitive so I think it should be `[...]All_Reads.fasta` instead of `[...]All_reads.fasta`.

Jared

**Comment by wgallin** [comment]
Well I feel stupid - thanks for the careful read.
Is there a way in future versions to make the error message exiplicitly state that the file doesn't exist?  If not too much trouble it might save someone else some time.
Thanks again.
