### ISSUE TITLE
To call variants from multiple amplicons in a sample  

### ISSUE THREAD

**Issue by ckhithesh** [jts/nanopolish#697]
Hi team,
I'm looking to call the variants from multiple amplicons in single sample. 
Clearly a sample contains **10genes** to call variants using nanopolish variants. And I don't want to mention the regions (**-w**).

Thanks in advance 
Regards
Hithesh

**Comment by jts** [comment]
Unfortunately you will have to specify the regions with `-w`.

**Comment by ckhithesh** [comment]
Dear Team,
Any suggestion on parameters for SNP calling (**multiple contigs**).
Regards 
Hithesh

**Comment by jts** [comment]
It is hard to help without information about your sample and sequencing data so I suggest using the defaults.

**Comment by ckhithesh** [comment]
Dear Simpson,
My sample details are 6 samples. where a sample consists of 5 amplicons and I have to call variants of all 5 amplicon in a sample. As if I used -w it will work for specific region. How to retrieve variants for 5amplicons from a sample. 
Regards
Hithesh

**Comment by jts** [comment]
Hi,

You will have to run nanopolish 5 times, once for each region.

Jared

**Comment by ckhithesh** [comment]
Dear Jared, 
Thank you for the reply!
I have one more question regarding the variant call for the complete genome. I have a genome of around 500 scaffolds. So, please let me know how to do for this?
  
Regards
Hithesh

**Comment by jts** [comment]
Hi @ckhithesh,

We provide an example of running over many windows of a genome here:

https://github.com/jts/nanopolish#computing-a-new-consensus-sequence-for-a-draft-assembly

This is for consensus calling but you should be able to adapt it to call variants instead (remove the `--consensus` flag, add any other options you need).

Jared
