### ISSUE TITLE
No calls in methyl.tsv file

### ISSUE THREAD

**Issue by nanopol** [jts/nanopolish#698]
I can't seem to obtain any methylation calls at all in the methylation.tsv file (empty file) in the end but do not know what the problem might be. I will paste my script and the job output. 

#! /bin/bash
# Parameters for slurm (don't remove the # in front of #SBATCH!)
#  Use partition debug:
#SBATCH --partition=debug
#  Use one node:
#SBATCH --nodes=1
#  Request 10 cores (hard constraint):
#SBATCH -c 10
#  Request 10GB of memory (hard constraint):
#SBATCH --mem=10GB
#  Request one hour maximal execution time (hard constraint):
#SBATCH --time=0-2:0:0
#  Request 100 GB of local scratch disk (hard constraint):
#SBATCH --tmp=100G
#  Notify me at job start and end:
#SBATCH --mail-type=ALL
#  Find your job easier with a name:
#SBATCH --job-name=MethylationTry1

#Initialize the module system:
source /etc/profile.d/modules.sh
# Allow aliases (required by some modules):
shopt -s expand_aliases
# Load your necessary modules (example):
module load nanopolish
module load pomoxis
module load minimap2

# Prepare $SCRATCH
mkdir $SCRATCH/inputdata/ 
mkdir $SCRATCH/results/ 
mkdir $SCRATCH/fast5_files
# Copy your input data into your local job directory for much faster execution:
cp -a /home/trinh/inputdata/*.fastq $SCRATCH/inputdata/
cp -a /home/trinh/inputdata/*.fast5 $SCRATCH/fast5_files/
cp -a /home/trinh/inputdata/chrM.fa $SCRATCH/inputdata/
# Do some computing here (can be commands or a second script)
cat $SCRATCH/inputdata/*.fastq > outputmethyl.fastq
nanopolish index -d $SCRATCH/fast5_files/ outputmethyl.fastq
minimap2 -a -x map-ont $SCRATCH/inputdata/chrM.fa outputmethyl.fastq > outputmethyl.sam 
samtools view -S -b outputmethyl.sam > outputmethyl.bam 
samtools sort outputmethyl.bam -o outputmethyl.sorted.bam
samtools index outputmethyl.sorted.bam
nanopolish call-methylation -t 8 -r outputmethyl.fastq -b outputmethyl.sorted.bam -g  $SCRATCH/inputdata/chrM.fa -w "chrM:1-1,600" > methylation_callsmtDNA.tsv

My job output:
[readdb] indexing /scratch/795844/fast5_files/
[readdb] num reads: 138362, num reads with path to fast5: 138362
[M::mm_idx_gen::0.002*19.61] collected minimizers
[M::mm_idx_gen::0.004*11.64] sorted minimizers
[M::main::0.005*10.58] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.005*9.38] mid_occ = 2
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.006*8.39] distinct minimizers: 3099 (100.00% are singletons); average occurrences: 1.000; average spacing: 5.347
[M::worker_pipeline::11.367*1.20] mapped 138362 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -a -x map-ont /scratch/795844/inputdata/chrM.fa outputmethyl.fastq
[M::main] Real time: 11.371 sec; CPU: 13.668 sec; Peak RSS: 0.635 GB
[fai_load] build FASTA index.
[bam process] iterating over region: chrM:1-1,600

**Comment by jts** [comment]
Did anything else print? The output log doesn't indicate any error.

**Comment by Shians** [comment]
Do any reads actually fall into `chrM:1-1,600`?

**Comment by nanopol** [comment]
Yes we have reads 30X coverage
Also the pipeline mapped 138362 sequences to the mitoDNA specifically
Nothing else printed on the output log :(

**Comment by jts** [comment]
With 138,000 reads it will take a few hours to call. I suspect your job hit the time limit and was killed by the scheduler. Try increasing the time limit or as a test use a small number of reads (~1000) to see if it runs.

Jared
