### ISSUE TITLE
Nanopolish variants workflow

### ISSUE THREAD

**Issue by chansbro** [jts/nanopolish#699]
Hello Jared, 

I'm having a little trouble (or confused) with running variants call using nanopolish.

Could you please confirm the workflow demonstrated below? 

1. Fast5 indexing: `nanopolish index -d fast5_pass/ reads.fq`

2. Read alignment: `minimap2 -ax map-ont -t 4 reference.fa reads.fq | samtools sort - o output.sorted.bam`

3. Bam indexing: `samtools index output.sorted.bam`

4. SNP calling: `nanopolish variants --reads reads.fq --bam output.sorted.bam --genome reference.fa -t 4 --progress --snps --ploidy 2 -w "NC_000007.14:1,000-5,000" > output.vcf`

However, when I tried to follow these steps above, I got an error at the final step (SNP calling).
Error message says `Failed to retrieve block` which I'm not sure what the problem is...
I've deleted all of output fi

Thank you for your help in advance!

**Comment by jts** [comment]
Hi,

It looks like you have a typo in your samtools sort command. It should be:

```
[...] | samtools sort -o output.sorted.bam
```

Jared

**Comment by chansbro** [comment]
Oh, that was my mistake on the question...

The output of the following `nanopolish variants...` showed output below...

`[E::fai_retrieve] Failed to retrieve block: unexpected end of file` 

Which I'm not quite sure what is wrong.

Could you please elaborate this error code?

Thanks.

**Comment by jts** [comment]
Nanopolish uses fai from `htslib` to retrieve segments of the reads, or reference genome. The message likely means that `reference.fa`, `reads.fq`, or the indices associated with those files is corrupt.

**Comment by chansbro** [comment]
Okay. 
How should I index the reference.fa file then??
Un addution, does my workflow above look correct??

**Comment by jts** [comment]
Try re-running nanopolish index, and deleting the .fai file corresponding to your reference.fa then running `samtools faidx reference.fa`.
