### ISSUE TITLE
default log level is verbose

### ISSUE THREAD

**Issue by vadimzalunin** [jts/nanopolish#7]
I'm experiencing many megabytes of 'Realigning ...' messages, which I think was added recently. Command line: 
 nanopolish eventalign -t 8 -r <fastq> -b <bam> -g <ref fasta>

**Comment by jts** [comment]
I'll remove these, in the meantime I suggest redirecting stderr to /dev/null

**Comment by jts** [comment]
Fixed in 02bd21878
