### ISSUE TITLE
HDF5 error

### ISSUE THREAD

**Issue by vineeth-s** [jts/nanopolish#70]
Hi Jared,

I seem to be running into HDF5 issues again, similar to the one I saw in an earlier **Issue** 
These are 1D reads, is it still advisable to use nanopolish with only 2D reads as you suggested in the reply to that post ?

The reads are visibile and accessible from where the the script is being run

> HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140623901505280:
>   #000: H5O.c line 246 in H5Oopen(): unable to open object
>     major: Symbol table
>     minor: Can't open object
>   #001: H5O.c line 1357 in H5O_open_name(): object not found
>     major: Symbol table
>     minor: Object not found
>   #002: H5Gloc.c line 430 in H5G_loc_find(): can't find object
>     major: Symbol table
>     minor: Object not found
>   #003: H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
>     major: Symbol table
>     minor: Object not found
>   #004: H5Gtraverse.c line 755 in H5G_traverse_real(): component not found
>     major: Symbol table
>     minor: Object not found

Cheers,
Vineeth

**Comment by jts** [comment]
Hi,

Can you post the complete error message? There should be a line describing what object is not found. Nanopolish v0.5 should work with 1D reads.

jared

**Comment by vineeth-s** [comment]
Hi Jared,

am getting a different error now ...

Here goes (a sort of log ... ) ...

I first run ... 
> /home/vineeth/polypore/tools/nanopolish/nanopolish eventalign -t 8 --sam -r test.fasta -b test.sorted.bam -g /home/vineeth/polypore/reference/dpb1_homebrew.fa --models nanopolish_models.fofn 

This is what I get on stderr ... 

> registering model t.007-base
> registering model t.007-ONT
> nanopolish: src/common/nanopolish_fast5_map.cpp:84: void Fast5Map::load_from_fasta(std::string): Assertion `read_to_path_map.find(seq->name.s) == read_to_path_map.end()' failed.
> Aborted (core dumped)

So I looked at the header for the fasta file generated with poretools 

> vineeth@wsdd02:~/nanopolish/test$ head -1 test.fasta 
> >7ff33256-1d80-48a6-b7c8-666539e9df64_Basecall_2D_2d minion01_20160628_FNFAD16686_MN17659_sequencing_run_TrainingDP_60703_ch23_read1241_strand /home/vineeth/nanopolish/fast5/dpb1/160627_TrainingDP/08_fastq_TrainingDP_2D_ONBC_96SetAdapt/001/minion01_20160628_FNFAD16686_MN17659_sequencing_run_TrainingDP_60703_ch23_read1241_strand.fast5

and the path does hold ... 

> vineeth@wsdd02:~/nanopolish/test$ ls -l /home/vineeth/nanopolish/fast5/dpb1/160627_TrainingDP/08_fastq_TrainingDP_2D_ONBC_96SetAdapt/001/minion01_20160628_FNFAD16686_MN17659_sequencing_run_TrainingDP_60703_ch23_read1241_strand.fast5
> -rwxr-xr-x 1 vineeth vineeth 4739565 Aug 31 18:37 /home/vineeth/nanopolish/fast5/dpb1/160627_TrainingDP/08_fastq_TrainingDP_2D_ONBC_96SetAdapt/001/minion01_20160628_FNFAD16686_MN17659_sequencing_run_TrainingDP_60703_ch23_read1241_strand.fast5
 
Am I missing something ?

Cheers,
Vineeth

**Comment by Blosberg** [comment]
Hello. 
I'm having an issue that seems similar to this one and [another](https://github.com/jts/nanopolish/issues/52) (older) issue. I'm trying to just start with indexing, and my input command and output is as follows:

```
$ ./nanopolish index -d [path_to_fast5_files_folder]  [path_to_fastq_file] 
Indexing [path_to_fast5_files_folder]
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140516061956096:
  #000: H5O.c line 246 in H5Oopen(): unable to open object
    major: Symbol table
    minor: Can't open object
  #001: H5O.c line 1357 in H5O_open_name(): object not found
    major: Symbol table
    minor: Object not found
  #002: H5Gloc.c line 430 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: H5Gtraverse.c line 755 in H5G_traverse_real(): component not found
    major: Symbol table
    minor: Object not found
terminate called after throwing an instance of 'hdf5_tools::Exception'
  what():  /Raw/Reads//Signal_Pack/params/read_id: error in H5Oopen
Aborted
```

What I've tried:
- I've used relative and absolute paths for the fast5 and fastq files (I read somewhere about mount-point access issues here), and copied both into a local subdirectory.
- I've unzipped the fastq to see if that made any difference.
- I've made sure that the version I'm using is up to date (as of time I posted this) by cloning, pulling and then with `make clean && make`

Those were all the possible solutions I was able to find on forums such as this. If you can offer any insight into other possible solutions, I'd much appreciate the help.
