### ISSUE TITLE
Are models compatible with Promethion FLO-PRO002 flow cell?

### ISSUE THREAD

**Issue by snajder-r** [jts/nanopolish#700]
Hi!

I'm sorry if this is a stupid question, but.. I was recently testing out Megalodon for methylation calling, and to my great dismay found an issue on their github page explaining that it simply wasn't compatible with PromethION flow cells.

Now I am thinking of using nanopolish's call-methylation function instead. Do you know if it would work with this particular flow cell?

Thanks a lot!

Best regards,
Rene

**Comment by jts** [comment]
Yes, nanopolish works with PromethION data.

Jared

**Comment by snajder-r** [comment]
Thank you so very much for your quick reply!
