### ISSUE TITLE
Methylation frequency issue

### ISSUE THREAD

**Issue by wzhjlau2009** [jts/nanopolish#701]
Hi，Jared
Thanks for so powerful tools. Recently i used this tools to call methylation, but when i used the python scripts to calculate methylation frequency, i have a TSV file which has 10 column as input for the scripts and i got a traceback. I don't know what's wrong, thank you very much if you can give me some advice.
![image](https://user-images.githubusercontent.com/6326115/70610255-3884d180-1c3e-11ea-9948-d2aa1ee838d0.png)
The TSV fie : 
![image](https://user-images.githubusercontent.com/6326115/70610666-eee8b680-1c3e-11ea-9cc7-cc18028310d4.png)

Best!

**Comment by jts** [comment]
The start of the file looks file, what does the end of the file (last 10 lines) look like?

**Comment by wzhjlau2009** [comment]
Hi，@jts
The last 15 lines of the csv file look like this
![image](https://user-images.githubusercontent.com/6326115/70633437-86fc9500-1c6b-11ea-96ef-fdb135b008c4.png)

**Comment by jts** [comment]
That looks fine. Maybe try bisecting the input file to see if you can isolate which line is problematic?

**Comment by wzhjlau2009** [comment]
Hi，@jts
ok, i will check all the input file to see which line is problematic. But now all the files have 10 column. Thanks.
