### ISSUE TITLE
Enquiries

### ISSUE THREAD

**Issue by mccartneya90** [jts/nanopolish#703]
Hey Jared,

I'm running a benchmarking of a couple of polishers at the minute and I'm working on a lot of subsampled datasets. For example I've taken a dataset and subsetted it into reads over 5kb, 10kb, 22kb etc. I've also subsetted by coverage (30, 50, 70x etc). So I'm trying to polish my initial assemblies using nanopolish.

 I've indexing the reads I've used for each subset and against the original complete datasets fast5. It appears to index fine with no errors, but when I move to the consensus step I seem to be getting core files being generated and when I look in the log I get :

error: faidx could not get contig length for contig contig_100
[E::fai_read] Could not understand FAI 10kb_flye_initial.fasta.fai line 2888
[E::fai_load3] Failed to read FASTA index 10kb_flye_initial.fasta.fai
[E::fai_read] Could not understand FAI 10kb_flye_initial.fasta.fai line 1933
[E::fai_load3] Failed to read FASTA index 10kb_flye_initial.fasta.fai
[E::fai_read] Could not understand FAI 10kb_flye_initial.fasta.fai line 1933
[E::fai_load3] Failed to read FASTA index 10kb_flye_initial.fasta.fai
[E::fai_read] Could not understand FAI 10kb_flye_initial.fasta.fai line 1933
[E::fai_load3] Failed to read FASTA index 10kb_flye_initial.fasta.fai
[E::fai_read] Could not understand FAI 10kb_flye_initial.fasta.fai line 3852
[E::fai_load3] Failed to read FASTA index 10kb_flye_initial.fasta.fai
Number of variants in span (12) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!

....
That carries on for awile but the log completes with:
[post-run summary] total reads: 110, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 0
.....

FRom reading online the max-haplotype thing is not an issue? and it produced .vcf files so I decided to move on to the vcf2fasta step but I keep getting the same error across all of my datasets (even when I tried to polish the complete data set, so it doesn't appear to be specific to the data subsetting issue):

error: could not detect polishing window from input file polished.contig_XXXX.vcf
....

I've double and tripled checked that I'm calling the correct genome assemblies that these were created off of, so I'm clueless as to what is going wrong as I'm getting a polished.fa with nothing in it. Have you any idea? Could it be something to do with the core dumps?Should I retry with increased RAM (consensus) or do you think it's an indexing issue?
I've pasted my slurm scripts underneath if they're useful.

Many thanks,
Ann

::::::::::::::
nano_step1.pbs
::::::::::::::
#!/bin/bash
#SBATCH -J flye_10kb_s1
#SBATCH -A landcare02569
#SBATCH --time=36:00:00
#SBATCH --ntasks=1
#SBATCH --mem=50G
#SBATCH --cpus-per-task=8
#SBATCH --chdir=/nesi/nobackup/landcare02569/HKGP_readlength_analysis/Nanopolish_Test/Rewa_Polishing/Flye/10kb

ml minimap2
ml SAMtools
minimap2 -ax map-ont -t 8 10kb_flye_initial.fasta ./../../rewa_porechop_10000.fasta | samtools sort -o 10kb_flye_sorted.bam -T reads.tmp
samtools index 10kb_flye_sorted.bam

::::::::::::::
nano_step2.pbs
::::::::::::::
#!/bin/bash
#SBATCH -J rewa_10kbF_s2
#SBATCH -A landcare02730
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --mem=50G
#SBATCH --cpus-per-task=8
#SBATCH --chdir=/nesi/nobackup/landcare02569/HKGP_readlength_analysis/Nanopolish_Test/Rewa_Polishing/Flye/10kb

ml Parallel/20190622
ml nanopolish/0.11.1-gimkl-2018b

nanopolish_makerange.py 10kb_flye_initial.fasta | parallel --results nanopolish.results -P 8 \
nanopolish variants --consensus -o polished.{1}.vcf -w {1} -r ./../../rewa_porechop_10000.fasta -b 10kb_flye_sorted.bam -g 10kb_flye_initial.fasta

::::::::::::::
nano_step3.pbs
::::::::::::::
#!/bin/bash
#SBATCH -J rewa_flye10_s3
#SBATCH -A landcare02730
#SBATCH --time=12:00:00
#SBATCH --ntasks=1
#SBATCH --mem=50G
#SBATCH --cpus-per-task=8
#SBATCH --chdir=/nesi/nobackup/landcare02569/HKGP_readlength_analysis/Nanopolish_Test/Rewa_Polishing/Flye/10kb

ml Parallel/20190622
ml nanopolish/0.11.1-gimkl-2018b

nanopolish vcf2fasta -g 10kb_flye_initial.fasta polished.*.vcf > polished_f_rewa.fa

**Comment by jts** [comment]
Hi @mccartneya90,

The messages about the .fai file are problematic and indicate the fasta index is corrupted somehow. Can you try to run these commands then try again?

```
rm 10kb_flye_initial.fasta.fai
samtools faidx 10kb_flye_initial.fasta.fai
```

Jared
