### ISSUE TITLE
In eventalign, does nanopolish compute population standard deviation or sample standard deviation of current samples?

### ISSUE THREAD

**Issue by adnaniazi** [jts/nanopolish#705]
Hi Jared,

Thank you for the great software!

I have a CSV table produced by nanopolish eventalign. From looking at it, it seems like nanopolish computes population standard deviation for all the samples that contribute to a particular 5-mer. But shouldn't it calculate sample standard deviation instead of population standard deviation? My understanding is that the sampling process of an analog-to-digital converter in a MinION produces a finite number of measurements -- i.e. samples -- from a continuous current signal. So the current samples attributed to a particular 5-mer cannot be treated as population but instead should be treated as a sample of the population.

To illustrate my point, we can consider one row from the eventalign tsv file produced from an RNA dataset:

reference_kmer: TACTT   
read_name: 935998e5-3e72-42e8-977f-ab040387ce46              
event_level_mean: 92.00  
event_stdv: 2.506     
event_length: 0.00398     
model_kmer: TACTT      
model_mean: 88.10     
model_stdv: 2.73    
standardized_level: 1.09
samples: 86.9282, 88.1188, 90.2023, 91.2441, 91.2441, 91.9882, 94.5182, 94.8158, 94.667, 95.1135, 93.7741, 91.3929

If I calculate the sample standard deviation from the samples reported by nanopolish myself, it turns out to be: 2.69
If I calculate the population standard deviation of these sample, it turns out to be 2.578021 close to the event_stdv that nanopolish reports, which makes me think that perhaps nanopolish is computing population standard deviation. But as I said earlier, I think it should report sample standard deviation instead of population standard deviation. Can you please correct me if I am wrong?

Thank you. 

Adnan

**Comment by jts** [comment]
Hi @adnaniazi,

Nanopolish uses code from ONT to detect events and calculate their summary statistics:

https://github.com/jts/nanopolish/blob/master/src/thirdparty/scrappie/event_detection.c#L213

Indeed it uses the length of the event as the denominator, rather than (length - 1).

Jared

**Comment by adnaniazi** [comment]
Hi @jts ,

Thank you for clarifying it. 

Best,
Adnan
