### ISSUE TITLE
Issue #515 follow-up

### ISSUE THREAD

**Issue by ranitori** [jts/nanopolish#706]
Hi,
I'm re-trying to install nanopolish again. This time I'm using OSX 10.14.6 Mojave on a MacBook Pro. I installed the latest code from github, but when I try to make it's not working. Please see the attached Terminal log file. Any help is greatly appreciated. Thanks.
[make.log](https://github.com/jts/nanopolish/files/3979869/make.log)

**Comment by jts** [comment]
Hi,

I’m on holidays so I can’t help much but I suggest installing through bioconda. If you want to install from source you’ll need to install gcc.

Jared

**Comment by ranitori** [comment]
Got it to work with bioconda. Thanks!
