### ISSUE TITLE
Installing issues

### ISSUE THREAD

**Issue by rebeelouise** [jts/nanopolish#707]
Hi,

I've tried installing nanopolish through conda and when I try to call it I get this error: 

`nanopolish: error while loading shared libraries: libhdf5.so.10: cannot open shared object file: No such file or directory
`
I uninstalled that and then tried to install through github, however when I used the make command in the directory it went a bit mad. 
`make[1]: Entering directory '/home/hlrpenri/nanopolish/hdf5-1.8.14'
Making all in src
make[2]: Entering directory '/home/hlrpenri/nanopolish/hdf5-1.8.14/src'
make  all-am
make[3]: Entering directory '/home/hlrpenri/nanopolish/hdf5-1.8.14/src'
  CC       H5.lo
In file included from H5.c:27:0:
H5Eprivate.h:35:32: warning: anonymous variadic macros were introduced in C99 [-Wvariadic-macros]
 #define HERROR(maj_id, min_id, ...) H5E_printf_stack(NULL, __FILE__, FUNC, __LINE__, H5E_ERR_CLS_g, maj_id, min_id, __VA_ARGS__)
                                ^~~
In file included from H5.c:27:0:
H5Eprivate.h:41:33: warning: anonymous variadic macros were introduced in C99 [-Wvariadic-macros]
 #define HCOMMON_ERROR(maj, min, ...)                    \
                                 ^~~
H5Eprivate.h:55:40: warning: anonymous variadic macros were introduced in C99 [-Wvariadic-macros]
 #define HDONE_ERROR(maj, min, ret_val, ...) {          \
                                        ^~~
H5Eprivate.h:67:40: warning: anonymous variadic macros were introduced in C99 [-Wvariadic-macros]
 #define HGOTO_ERROR(maj, min, ret_val, ...) {          \
                                        ^~~
In file included from H5.c:24:0:
H5.c: In function 'H5_init_library':
H5private.h:1539:14: warning: ISO C90 does not support '__func__' predefined identifier [-Wpedantic]
 #define FUNC __func__
              ^
H5Eprivate.h:35:70: note: in expansion of macro 'FUNC'
 #define HERROR(maj_id, min_id, ...) H5E_printf_stack(NULL, __FILE__, FUNC, __LINE__, H5E_ERR_CLS_g, maj_id, min_id, __VA_ARGS__)
                                                                      ^~~~
H5Eprivate.h:42:4: note: in expansion of macro 'HERROR'
    HERROR(maj, min, __VA_ARGS__);           \
    ^~~~~~
H5Eprivate.h:68:4: note: in expansion of macro 'HCOMMON_ERROR'
    HCOMMON_ERROR(maj, min, __VA_ARGS__);           \
    ^~~~~~~~~~~~~
H5.c:181:9: note: in expansion of macro 'HGOTO_ERROR'
         HGOTO_ERROR(H5E_FUNC, H5E_CANTINIT, FAIL, "unable to initialize error interface")
         ^~~~~~~~~~~
H5private.h:1539:14: warning: ISO C90 does not support '__func__' predefined identifier [-Wpedantic]
 #define FUNC __func__
              ^
H5Eprivate.h:35:70: note: in expansion of macro 'FUNC'
 #define HERROR(maj_id, min_id, ...) H5E_printf_stack(NULL, __FILE__, FUNC, __LINE__, H5E_ERR_CLS_g, maj_id, min_id, __VA_ARGS__)
                                                                      ^~~~
H5Eprivate.h:42:4: note: in expansion of macro 'HERROR'
    HERROR(maj, min, __VA_ARGS__);           \
    ^~~~~~
H5Eprivate.h:68:4: note: in expansion of macro 'HCOMMON_ERROR'
    HCOMMON_ERROR(maj, min, __VA_ARGS__);           \
    ^~~~~~~~~~~~~
H5.c:183:9: note: in expansion of macro 'HGOTO_ERROR'
         HGOTO_ERROR(H5E_FUNC, H5E_CANTINIT, FAIL, "unable to initialize property list interface")
         ^~~~~~~~~~~
H5private.h:1539:14: warning: ISO C90 does not support '__func__' predefined identifier [-Wpedantic]
 #define FUNC __func__
              ^
H5Eprivate.h:35:70: note: in expansion of macro 'FUNC'
 #define HERROR(maj_id, min_id, ...) H5E_printf_stack(NULL, __FILE__, FUNC, __LINE__, H5E_ERR_CLS_g, maj_id, min_id, __VA_ARGS__)
                                                                      ^~~~
H5Eprivate.h:42:4: note: in expansion of macro 'HERROR'
    HERROR(maj, min, __VA_ARGS__);           \
    ^~~~~~
H5Eprivate.h:68:4: note: in expansion of macro 'HCOMMON_ERROR'
    HCOMMON_ERROR(maj, min, __VA_ARGS__);           \
    ^~~~~~~~~~~~~
H5.c:185:9: note: in expansion of macro 'HGOTO_ERROR'
         HGOTO_ERROR(H5E_FUNC, H5E_CANTINIT, FAIL, "unable to initialize datatype interface")
         ^~~~~~~~~~~
H5private.h:1539:14: warning: ISO C90 does not support '__func__' predefined identifier [-Wpedantic]
 #define FUNC __func__
              ^
H5Eprivate.h:35:70: note: in expansion of macro 'FUNC'
 #define HERROR(maj_id, min_id, ...) H5E_printf_stack(NULL, __FILE__, FUNC, __LINE__, H5E_ERR_CLS_g, maj_id, min_id, __VA_ARGS__)
                                                                      ^~~~
H5Eprivate.h:42:4: note: in expansion of macro 'HERROR'
    HERROR(maj, min, __VA_ARGS__);           \
    ^~~~~~
H5Eprivate.h:68:4: note: in expansion of macro 'HCOMMON_ERROR'
    HCOMMON_ERROR(maj, min, __VA_ARGS__);           \
    ^~~~~~~~~~~~~
H5.c:187:9: note: in expansion of macro 'HGOTO_ERROR'
         HGOTO_ERROR(H5E_FUNC, H5E_CANTINIT, FAIL, "unable to initialize dataset interface")
         ^~~~~~~~~~~
H5private.h:1539:14: warning: ISO C90 does not support '__func__' predefined identifier [-Wpedantic]
 #define FUNC __func__
              ^
H5Eprivate.h:35:70: note: in expansion of macro 'FUNC'
 #define HERROR(maj_id, min_id, ...) H5E_printf_stack(NULL, __FILE__, FUNC, __LINE__, H5E_ERR_CLS_g, maj_id, min_id, __VA_ARGS__)
                                                                      ^~~~
H5Eprivate.h:42:4: note: in expansion of macro 'HERROR'
    HERROR(maj, min, __VA_ARGS__);           \
    ^~~~~~
H5Eprivate.h:68:4: note: in expansion of macro 'HCOMMON_ERROR'
    HCOMMON_ERROR(maj, min, __VA_ARGS__);           \
    ^~~~~~~~~~~~~
H5.c:189:9: note: in expansion of macro 'HGOTO_ERROR'
         HGOTO_ERROR(H5E_FUNC, H5E_CANTINIT, FAIL, "unable to initialize metadata caching interface")
         ^~~~~~~~~~~
H5private.h:1539:14: warning: ISO C90 does not support '__func__' predefined identifier [-Wpedantic]
 #define FUNC __func__
              ^
H5Eprivate.h:35:70: note: in expansion of macro 'FUNC'
 #define HERROR(maj_id, min_id, ...) H5E_printf_stack(NULL, __FILE__, FUNC, __LINE__, H5E_ERR_CLS_g, maj_id, min_id, __VA_ARGS__)
                                                                      ^~~~
H5Eprivate.h:42:4: note: in expansion of macro 'HERROR'
    HERROR(maj, min, __VA_ARGS__);           \
    ^~~~~~
H5Eprivate.h:68:4: note: in expansion of macro 'HCOMMON_ERROR'
    HCOMMON_ERROR(maj, min, __VA_ARGS__);           \
    ^~~~~~~~~~~~~
H5.c:191:9: note: in expansion of macro 'HGOTO_ERROR'
         HGOTO_ERROR(H5E_FUNC, H5E_CANTINIT, FAIL, "unable to initialize link interface")
         ^~~~~~~~~~~
` . etc. 

Thanks in advance for your support!

Rebekah

**Comment by jts** [comment]
Hi @rebeelouise,

Sorry for the slow response, I was on holiday. Is this still an issue? If so can you copy the entire compile log into a text file and attach it to this issue?

Thanks,
Jared

**Comment by swethak1989** [comment]
Hi,

I am also running into this exact issue.
Background: I'm using Ubuntu on my Windows 10 machine. until this morning, my indexing using Nanopolish indexing wouldn't work completely- error being that fast5 files could not be found and so no readdb file was created
I checked the nanopolish version - 0.9.0.
So I tried to update in multiple ways - conda, sudo apt upgrade and GitHub repo.
Ran into the SAME problems mentioned here - even the version check command won't work now
Please let me know how I could fix this? Thanks for your support!

**Comment by nicolo-tellini** [comment]
Hi all, 

I am having the same issue.
Any solution to that ? 

best,

Nic

**Comment by CountBorgula** [comment]
Did this get solved?
