### ISSUE TITLE
Meaning of "num_calling_strands"

### ISSUE THREAD

**Issue by Shians** [jts/nanopolish#710]
What is the meaning of the "num_calling_strands" column in the call-methylation output? Is this a referenced to 1d2 protocol that sequences both strands of a fragment? So are the values 1 and 2 for 1D and 1D2 respectively?

**Comment by jts** [comment]
That's the right idea but it was for the 2D protocol. 1D2 is not supported
by nanopolish methylation calling.

**Comment by Shians** [comment]
Got it, thanks!
