### ISSUE TITLE
fast5 missing in v0.11.3.tar.gz

### ISSUE THREAD

**Issue by Phhere** [jts/nanopolish#711]
Hello,

i have just downloaded the latest release and it is missing fast5, maybe other dependencies.
in v0.11.1.tar.gz the dependencies are included.

**Comment by jts** [comment]
Hi @Phhere,

That is strange, the dependencies should not be in any of the tars (github doesn't add them). In the v0.11.1 tar.gz the fast5/ folder appears to be there, but empty.

In any case you can follow these instructions to get a particular version:

https://github.com/jts/nanopolish#installing-a-particular-release

Jared
