### ISSUE TITLE
Invalid summary file entries for 1 file only

### ISSUE THREAD

**Issue by Ganthark** [jts/nanopolish#712]
Hi,
I wanted to use nanopolish for methylation calling but I am already stuck with the indexing of the fast5 files. I have 237 multi-fast5 files that have been basecalled with guppy (Version 3.2.4+d9ed22f) and my sequencing_summary.txt file looks correct with all the 237 file names present. However, I get this warning message :
`warning: detected invalid summary file entries for 1 of 237 fast5 files
These files will be indexed without using the summary file, which is slow.`
As I got many files (and more to come) I would really like for the indexing to work with the sequencing_summary.txt file to gain some time. I tried the -vvv flag as suggested in another issue but but it didn't give more information. 
I would be pleased if you could help me solve this issue,
Thanks

**Comment by jts** [comment]
Hi,

In this case it will only use the slow indexing method for the 4000 reads contained in the bad summary file, so the effect on run time will not be significant.

Were you able to complete the indexing step?

Jared

**Comment by Ganthark** [comment]
Hi,

That is what I understood but I suspect a more complex situation because the indexing has been running for 7 days now and is not finished yet.
For the time being I am doing an analysis on a subset of the files that I know contain a sequence of interest to be faster but at some point I will need to study everything. When I'm done with this preliminary study I will try the same analysis on another dataset to dig deeper on this problem.

Thanks

**Comment by jts** [comment]
That's unusual, it shouldn't take 7 days, especially with a mostly valid summary file. Is the process actually running or is it stuck? Are any messages being printed to the console?

**Comment by Ganthark** [comment]
There are no error or new messages since the first warning and the cpu is running at 99% for this job (on a cluster).

**Comment by jts** [comment]
Can you try to index a small subset of the data by symlinking a few of the fast5s into a new directory, to see if it completes in a reasonable amount of time?

**Comment by xusijia1211** [comment]
Hi, I have the same situation in my yesterday's try.
I use all fast_pass folder generated during the sequencing, and I re-basecalled data using guppy.3.4.4, fastq folder is a subset with the same barcode, only 305 MB.  
My command is: 
`nanopolish index -d fast5_pass/ -s summary.txt guppy.3.4.4_recalled_fastq/epi2me_barcoded/BC01/
`
Then I got this. I left it over-night. Today nothing changed. No error info, seems still running.
warning: detected invalid summary file entries for 1 of 209 fast5 files
These files will be indexed without using the summary file, which is slow.

**Comment by Ganthark** [comment]
Hi,

I come back with a bit more information about things I tried.

- on a full Nanopore run of about 134Go, indexing not finished after a month (with or without summary file)
- on different subsets of fast5 of size < 500Mo (symlinked) with the corresponding fastq files, indexing not finished after a week (with or without summary file)
In both cases, no error or output is printed and the process is working. The indexing command is always called from a script with prints before and after to be sure the indexing is still running.

In the meantime I wanted to to study certain loci, so with blast and the ont_fast5_api I extracted very little subsets of the fast5 and fastq (a few thousand reads each time) and in this case the indexing is working in matter of seconds and I never had any problems.

I hope this could help solve the issue,
Thanks

**Comment by jts** [comment]
Hi @Ganthark,

Thanks for following up, I will add a check to see if the input is a directory instead of the expected fastq file. @xusijia1211 I think this is your problem too, the last argument in your command should be a single fastq file instead of a directory.

Jared

**Comment by xusijia1211** [comment]
Hi, jts and Ganthark, thanks for more information.
I tried using single fastq file merged from fastq directory. It worked without '-s summary.txt' option.
The fastq files here  were re-basecalled ones from original fast5 by latest guppy basecaller. Since both MinKNOW sequencing  and guppy re-basecalling generate their own summary.txt, I wonder which one should be appropriate.
```
# using original MinKNOW summary.txt
$ nanopolish index -d path/to/fast5_pass/ -s MinKNOW.summary.txt  guppy.re-basecalled.barcode1.merged.fastq 
warning: detected invalid summary file entries for 54 of 209 fast5 files
These files will be indexed without using the summary file, which is slow.
[readdb] indexing ...

# using guppy rebasecalling summary.txt
$ nanopolish index -d fast5_pass/ -s guppy.3.4.4.summary.txt  guppy.re-basecalled.barcode1.merged.fastq 
warning: detected invalid summary file entries for 1 of 209 fast5 files
These files will be indexed without using the summary file, which is slow.
[readdb] indexing ...
[readdb] num reads: 38122, num reads with path to fast5: 38122
```
I checked those column names in both summary.txt.
MinKNOW summary.txt seems to contain more columns like: 
`pore_type` , `experiment_id` and `sample_id` 
at the tail part.

Any further information would be greatly appreciated.

**Comment by jts** [comment]
Hi @xusijia1211,

You should use the summary file that matches the input fastq file. If the FASTQ was generated by Guppy, you should use the guppy summary. You can ignore the warnings.

Jared

**Comment by jts** [comment]
I have added a check so that an error will be given when the input is accidentally a directory instead of a file in 279e23a5.
