### ISSUE TITLE
Does “nanopolish polya” support the data generated by sequencing kit SQK-PCS109?

### ISSUE THREAD

**Issue by xxz19900** [jts/nanopolish#713]
Hi, I wonder whether “nanopolish polya” can analyze the sequencing data generated by the cDNA-PCR sequencing method. Or, it just supports the direct RNA sequencing?

**Comment by jts** [comment]
Hi,

Currently it only supports the direct RNA method.

Jared

**Comment by xxz19900** [comment]
Thanks for your reply.

**Comment by stegiopast** [comment]
Hi,

I am currently running polyA estimation with nanopolish and wanted to know whether there has been any update to use it with cDNA approaches ? 

Best regards,
Stefan

**Comment by stegiopast** [comment]
Thanks for the fast reply :+1:
