### ISSUE TITLE
How eventalign works?

### ISSUE THREAD

**Issue by vahidAK** [jts/nanopolish#714]
Hi @jts ,
I am trying to understand the process of eventalign and I really appreciate it if you could help me.
As far as I know, this module aligns the raw signal data to the reference and returns back some statistics for each kmer. So, basically, this module detects what signals correspond to what kmers in the reference.

From my understanding, this module first extracts the corresponding reference sequence for each read in a fastq file (replace the reads with the corresponding reference sequence)? and then it looks at the reference sequence and the raw signals for each read and assigns signals to kmers?
If is it correct, I am a bit confused about the second step.  How it finds signals for each kmer? because, as I did some measurements, the read length and signal length are not compatible and it varies from read to read.

Thanks,
Vahid.

**Comment by jts** [comment]
Hi @vahidAK,

In this blog post I explain how eventalign works:

http://simpsonlab.github.io/2015/04/08/eventalign/

Jared

**Comment by vahidAK** [comment]
Thamks @jts
