### ISSUE TITLE
Error while installing Nanopolish

### ISSUE THREAD

**Issue by pinkysaid** [jts/nanopolish#715]
Hi,

While using the following commands to install Nanopolish on a Linux server (CentOS):

**git clone --recursive https://github.com/jts/nanopolish.git
cd nanopolish
make**

I got the following error;

**ERROR 403: Forbidden. make: *** [eigen/INSTALL] Error 8**

**Comment by jts** [comment]
Hi,

It looks like this was a problem accessing the website hosting the EIGEN package. It looks OK now, can you try again?

Jared

**Comment by pinkysaid** [comment]
Hello,

Thank you for your response. Tried it and got the same error. I even tried **make EIGEN=noinstall** and received another error message;

**src/nanopolish_methyltrain.cpp:48:23: fatal error: Eigen/Dense: No such file or directory
 #include "Eigen/Dense"
                       ^
compilation terminated.
make: *** [.depend] Error 1**

**Comment by jts** [comment]
Can you send me the complete error log when you run `make` (without `EIGEN=noinstall`)?

**Comment by pinkysaid** [comment]
Hi Jared,

Is there a log file to access this? I have just copied the last verbose output on the terminal window, I hope this will suffice.

**+ cd examples
+ make install-examples
make[2]: Entering directory `/Tools/nanopolish/hdf5-1.8.14/examples'
../bin/mkdirs /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c
+ /usr/bin/install -c ./h5_write.c /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c/.
+ /usr/bin/install -c ./h5_read.c /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c/.
+ /usr/bin/install -c ./h5_extend_write.c /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c/.
+ /usr/bin/install -c ./h5_chunk_read.c /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c/.
+ /usr/bin/install -c ./h5_crtgrpd.c /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c/.
+ /usr/bin/install -c ./h5_subset.c /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c/.
+ /usr/bin/install -c ./h5_cmprss.c /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c/.
+ /usr/bin/install -c ./h5_rdwt.c /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c/.
+ /usr/bin/install -c ./h5_crtgrpar.c /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c/.
+ /usr/bin/install -c ./h5_extend.c /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c/.
+ /usr/bin/install -c ./h5_crtatt.c /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c/.
+ /usr/bin/install -c ./h5_crtgrp.c /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c/.
+ /usr/bin/install -c ./h5_crtdat.c /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c/.
+ /usr/bin/install -c ./h5_compound.c /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c/.
+ /usr/bin/install -c ./h5_group.c /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c/.
+ /usr/bin/install -c ./h5_select.c /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c/.
+ /usr/bin/install -c ./h5_attribute.c /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c/.
+ /usr/bin/install -c ./h5_mount.c /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c/.
+ /usr/bin/install -c ./h5_reference.c /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c/.
+ /usr/bin/install -c ./h5_drivers.c /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c/.
+ /usr/bin/install -c ./h5_extlink.c /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c/.
+ /usr/bin/install -c ./h5_elink_unix2win.c /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c/.
+ /usr/bin/install -c ./h5_ref2reg.c /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c/.
+ /usr/bin/install -c ./h5_shared_mesg.c /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c/.
+ /usr/bin/install -c ./ph5example.c /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c/.
+ /usr/bin/install -c run-c-ex.sh /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/c/.
+ /usr/bin/install -c ./README /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/.
+ /usr/bin/install -c ./run-all-ex.sh /Tools/nanopolish/hdf5-1.8.14/../share/hdf5_examples/.
make[2]: Leaving directory `/Tools/nanopolish/hdf5-1.8.14/examples'
make[1]: Leaving directory `/Tools/nanopolish/hdf5-1.8.14'
if [ ! -e 3.2.5.tar.bz2 ]; then \
	wget http://bitbucket.org/eigen/eigen/get/3.2.5.tar.bz2; \
fi
--2020-01-21 09:53:43--  http://bitbucket.org/eigen/eigen/get/3.2.5.tar.bz2
Resolving bitbucket.org (bitbucket.org)... 18.205.93.1, 18.205.93.0, 18.205.93.2, ...
Connecting to bitbucket.org (bitbucket.org)|18.205.93.1|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-01-21 09:53:43 ERROR 403: Forbidden.

make: *** [eigen/INSTALL] Error 8**

Kind regards,

Pinky

**Comment by jts** [comment]
Are you about to run `wget http://bitbucket.org/eigen/eigen/get/3.2.5.tar.bz2`?

**Comment by pinkysaid** [comment]
Hi Jared,

Do you mean if I'm able to run it independently? If so, unfortunately no. Same error. I decided to use another alternative. So after running,
`git clone --recursive https://github.com/jts/nanopolish.git`, 

I installed Eigen (using a different URL) within the Nanopolish directory while ensuring the version was corrected to 3.3.7 in the Nanopolish Makefile
`wget https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.bz2` 

Then edited the Nanopolish Makefile by changing the URL (in case one doesn't want to install Eigen themselves) prior to running `make`. This unpacks the tar.bz2 file. 

I hope this works with no errors. For now, I am about to run Nanopolish but **can't find the nanopolish variants --consensus subprogram.** 

Your assistance will be highly appreciated.

**Comment by jts** [comment]
Hi,

Sorry for the slow response. Did you solve this? You have to give the full path to the nanopolish binary that you built.

Jared

**Comment by giesselmann** [comment]
Hi,
I'm having the same error today, also a manual 
>wget http://bitbucket.org/eigen/eigen/get/3.2.5.tar.bz2

results in:

> URL transformed to HTTPS due to an HSTS policy
--2020-08-27 14:15:31--  https://bitbucket.org/eigen/eigen/get/3.2.5.tar.bz2
Resolving bitbucket.org... 18.205.93.2, 18.205.93.1, 18.205.93.0, ...
Connecting to bitbucket.org|18.205.93.2|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-08-27 14:15:32 ERROR 403: Forbidden

If I go directly to https://bitbucket.org/eigen/eigen/ it tells me repository doesn't exist, if you click into it from the parent, it's asking for a password.

Pay

**Comment by jts** [comment]
Hi @giesselmann,

Can you make sure you pulled the latest change? As of last week the eigen url should point to gitlab, not bitbucket:

https://github.com/jts/nanopolish/commit/46a029cbf3dc63a96bda6daaf96383b07711546c

Jared

**Comment by giesselmann** [comment]
That works, I'll patch. Thanks for the fast help!
