### ISSUE TITLE
error: faidx could not get contig length for contig 

### ISSUE THREAD

**Issue by sstwins21** [jts/nanopolish#716]
Hi,

I have searched to fix this error message in this forum, but I think none of them referred to my problem...

What I want is to build a better consensus assembly using long reads.
So this is the command line I used: 

nanopolish_makerange.py chrom_polar_racon_6.fasta | parallel --results nano_racon_flye nanopolish variants --consensus -o polished.{1}.vcf -t 8 -w {1} -r rebasecalled_cliatrchus_nanopore.fasta -b polar_flye.sorted.bam -g chrom_polar_racon_6.fasta -t 12 --min-candidate-frequency 0.1 

But it gives me error messages that it couldn't find the contig lengths. When I had a look at the names, names it were finding was different to actual name in the assembly. 
For example, one of the error message was:
error: faidx could not get contig length for contig 1076_nd

And when I tried to find that name in the assembly file, the actual name was:
>1076_nd:0-14523 LN:i:14611 RC:i:54 XC:f:1.000000

Do I need to edit the names of the contig? Or what would be the problem causing this error?

Thank you for your help.

Kind regards,
Shane

**Comment by jts** [comment]
It’s probably because the names match the format nanopolish expects for the -w argument. If you rename the contigs it will probably work. I’ll look into it more tomorrow.

Jared

**Comment by sstwins21** [comment]
Thank you Jared for looking into this.

Shane

**Comment by sstwins21** [comment]
Hi Jared,

Have you had a look at why this might have happened?
For more information, I have used Supernova and flye as a scaffolder and polished with Racon.
So the name of the contig might have adjusted to Racon's output names.


Kind regards,
Shane

**Comment by jts** [comment]
I've confirmed that the contig names in the format `<name>:<start>-<end>` aren't acceptable to nanopolish, and it is not possible to change this, so you'll have to edit them. Sorry for the trouble.

Jared

**Comment by sstwins21** [comment]
Hi Jared,

I have changed the scaffolds' name and it seems to work fine.
Thank you so much for your help!

Kind regards,
Shane
