### ISSUE TITLE
nanopolish variants per read output

### ISSUE THREAD

**Issue by vahidAK** [jts/nanopolish#718]
Hi @jts .
I have nanopore sequencing data for 1 sample. I already called methylation for that sample and now I am trying to phase the reads and find imprinted regions. As far as I understand, it is more efficient to use nanopolish to call variants rather than something like bcftools mpileup, because nanopolish also uses row signal information to call variants? if is it correct, then to phase reads I also need polished reads by raw signals that used in nanopolish variant step in order to phase them. Can I output per-read results by nanopolish variant or I just can use bascalled reads from basecaller?

Many thanks,

Vahid.

**Comment by jts** [comment]
Hi @vahidAK,

You might be interested in this framework that @MeHelmy and @fritzsedlazeck have developed:

https://github.com/MeHelmy/princess

It will perform phasing of nanopolish methylation calls, directly solving your problem.

Jared

**Comment by vahidAK** [comment]
Thanks a lot, @jts .

I will check that out
