### ISSUE TITLE
comparable signals across replicates

### ISSUE THREAD

**Issue by pabloacera** [jts/nanopolish#719]
Hi Jared,
Thanks for the useful software.
I have a 6 (3X3) of biological replicates that I want to compare the signals among them. I have use nanopolish eventalign with each of the individual replicates like:
`nanopolish eventalign -t 10 --reads all_KO1.fastq --bam KO1_sorted.bam --genome reference.fa --samples --print-read-names --scale-events > KO1_eventalign.txt`
If I am not wrong the 'raw' samples from KO1_eventalifgn.txt will be scaled. That this scaling makes the signals comparable between replicates? Do you think it needs further normalization?
Thank you very much for your time!
Pablo.

**Comment by jts** [comment]
Hi @pabloacera,

> If I am not wrong the 'raw' samples from KO1_eventalifgn.txt will be scaled

Correct, with the `--scale-events` option the eventalign output will be scaled to the pore model, so the signals should be comparable across replicates.

**Comment by pabloacera** [comment]
Thank you very much!
im closing! =)
