### ISSUE TITLE
Cutting PCR adapters and demultiplexing before DNA methylation analysis

### ISSUE THREAD

**Issue by andreaswallberg** [jts/nanopolish#720]
Dear developers,

We are running a DNA methylation analysis using Nanopore data and the pipeline appears to work fine. I just wanted to double-check and get a confirmation regarding read trimming.

My understanding is that it is ok to cut PCR adapters and to perform barcode demultiplexing with tools like porechop or qcat prior to analyses with nanopolish, as long as reads are not split on middle adapters/motifs such that more than one fastq accession gets derived from a single original fast5 accession.

Is this true?

Because trimmed reads in the fastq files may then be of different lengths compared to the original signals in the fast5, this also means that nanopolish performs internal alignment of bases against signals, right?

Cheers and many thanks for a great tool!

**Comment by jts** [comment]
Hi @andreaswallberg,

That's right, nanopolish performs an internal signal-to-bases alignment, which tolerates some missing sequence at the beginning/end of the basecalled sequence. Keep an eye on the "post-run summary' message, which prints how many reads are usable by nanopolish. If many reads have failed the alignment or calibration QC then you may have trimmed too much.

Jared
