### ISSUE TITLE
Can I use Nanopolish for RNA?

### ISSUE THREAD

**Issue by vahidAK** [jts/nanopolish#721]
Hi @jts ,

I was wondering if is it possible to train a model for RNA by nanopolish and then use nanopolish to call modification from RNA sample using that model?

Thanks, 
Vahid.

**Comment by jts** [comment]
In principle yes, but it would be a lot of work to change the code to properly support RNA modification calling. Its in our long term plans to support this though. In the meantime, I suggest you use https://github.com/tleonardi/nanocompore, which uses nanopolish's eventalign module.

Jared

**Comment by vahidAK** [comment]
Thanks @jts ,

Yes, I already knew about this tool. The problem is that Nanocompore is not a model base and I need to have normal and knock out conditions.

**Comment by LeilyR** [comment]
Wouldn't it possible to use `nanopolish eventalign` with` transcriptome.fa` for that purpose? I was going to try it out on direct RNA data but I came across this issue. So,  just wanted to be sure that it makes sense. I also don't have different conditions.
