### ISSUE TITLE
Nanopolish eventalign modelling 6-mers with DNA and 5-mers for dRNA

### ISSUE THREAD

**Issue by pabloacera** [jts/nanopolish#724]
Hi Jared,

Sorry for bothering, I didn't find any ticket with this question.
I have used nanopolish eventalign with DNA and direct RNA using fairly similar commands. 

`nanopolish eventalign -t 10 --reads _rep1.fastq --bam rep1_sorted.bam --genome ../genome.fasta --samples --print-read-names --scale-events --signal-index > Non_mod_rep1_eventalign.txt
`

I have realized that the columns 'reference_kmer' and 'model_kmer' contains 5-mers for RNA and 6-mers for DNA, meaning that they are modeling a different number of mers.
Please, do you know why? I would like to model 5-mers for DNA as well, is it something I should specify? and is it convenient to do? 
Thank very much in advance for your help.
Pablo.

**Comment by jts** [comment]
Hi @pabloacera,

Nanopolish's models are either directly, or derived, from the ONT models here: https://github.com/nanoporetech/kmer_models. These models use a 5-mer for RNA and a 6-mer for DNA, so we do as well. 

Jared
