### ISSUE TITLE
compatibility with vbz compression?

### ISSUE THREAD

**Issue by wdecoster** [jts/nanopolish#725]
Hi,

We have some data compressed with the newish vbz compression method, which doesn't seem to be compatible with nanopolish?
The error we received is: 
`error: nanopolish: src/nanopolish_squiggle_read.cpp:321: void SquiggleRead::load_from_raw(fast5_file&, uint32_t): Assertion `rt.n > 0' failed.`

Or should that not be due to the compression and something else is going on?

Cheers,
Wouter

**Comment by jts** [comment]
Nanopolish should be compatible, as long as you load the plugin. See a discussion here:

https://github.com/nanoporetech/vbz_compression/issues/5

This isn't the most user-friendly solution though, so I'll look into handling this internally. I don't have vbz-compressed data yet, so it may take a little while.

Jared

**Comment by wdecoster** [comment]
Thanks!

**Comment by jts** [comment]
I'm going to re-open this as a reminder to fix this. Can you let me know if setting the environment variable works for you?

**Comment by wdecoster** [comment]
I've forwarded it to those who run the pipelines on the cluster... and will report back.

**Comment by wdecoster** [comment]
After managing to compile the plugin things seem to work now!

**Comment by jts** [comment]
Great, thanks!
