### ISSUE TITLE
how to be sure that nanpolish index is running ?

### ISSUE THREAD

**Issue by DelphIONe** [jts/nanopolish#726]
Hi,

My command nanopolish index is running, since 270 hours. I'm wondering if I'm waiting for nothing...
In htop command nanopolish index is running it's ok but I see none new files as .readbb or other in writting. My command :
sudo ~/softs/nanopolish/nanopolish index -d /data2/200113_gI_run048/fast5_pass/ /data2/200113_gI_run048/fastq_pass/

Nanopolish didn't accept the parameter -f for sequencing_summary.txt file.
The fast5 are mutli fast5 files. Must I use the multi_to_single_fast5 script before Nanopolish ?

Can you help me ? 
Thanks for your help.

**Comment by jts** [comment]
Hi,

The second argument should be a fastq file, not a directory. I suspect this has caused the unexpectedly long run time. Can you fix this and try again?

The summary file should be provided with the `-s` option, not `-f`.

Jared

**Comment by DelphIONe** [comment]
yes, sorry I was too speed.

sudo ~/softs/nanopolish/nanopolish index -s /data2/200113_gI_run048/sequencing_summary_FAL11939_1d8f98e1.txt -d /data2/200113_gI_run048/fast5_pass/ /data2/200113_gI_run048/reads_pass.fastq 

Could not find filename column in the header of /data2/200113_gI_run048/sequencing_summary_FAL11939_1d8f98e1.txt

I can launch without option -s ... ?

**Comment by jts** [comment]
Can you run `head -2 /data2/200113_gI_run048/sequencing_summary_FAL11939_1d8f98e1.txt` and show me the result?

**Comment by DelphIONe** [comment]
head -2 /data2/200113_gI_run048/sequencing_summary_FAL11939_1d8f98e1.txt
filename_fastq  filename_fast5  read_id run_id  channel mux     start_time      duration        num_events      passes_filtering        template_start  num_events_template     template_duration       sequence_length_template        mean_qscore_template       strand_score_template   median_template mad_template    pore_type       experiment_id   sample_id       end_reason
FAL11939_pass_1d8f98e1_0.fastq  FAL11939_pass_1d8f98e1_0.fast5  5212ca5d-f712-47a1-ad90-e57a7292ed26    1d8f98e1d5b4d4330c10dedd511982b48ba1370b        407     1       7.127500        0.600250        1200    TRUE    7.129000        1197    0.598750   175     12.858709       0.000000        77.659004       8.591344        not_set DUPONT  DUPO2_1 unblock_mux_change

**Comment by jts** [comment]
This is a newer format of the summary file, which is only supported in the most recent version of nanopolish. Can you update to the latest version from github and try again?

**Comment by DelphIONe** [comment]
~/softs/nanopolish$ git pull
Already up-to-date.

?

**Comment by jts** [comment]
What does `nanopolish --version` say?

**Comment by DelphIONe** [comment]
~/softs/nanopolish/nanopolish --version
nanopolish version 0.10.2
Written by Jared Simpson.

Copyright 2015-2017 Ontario Institute for Cancer Research

**Comment by jts** [comment]
That version is very old (Sept 2018). Try to recompile (`make clean; make`)

**Comment by DelphIONe** [comment]
~/softs/nanopolish$ ~/softs/nanopolish/nanopolish --version
nanopolish version 0.11.3
Written by Jared Simpson.

~/softs/nanopolish/nanopolish index -s /data2/200113_gI_run048/sequencing_summary_FAL11939_1d8f98e1.txt -d /data2/200113_gI_run048/fast5_pass/ /data2/200113_gI_run048/reads_pass.fastq 
warning: detected invalid summary file entries for 2 of 464 fast5 files
These files will be indexed without using the summary file, which is slow.

Index is working, thanks!

**Comment by jts** [comment]
great!
