### ISSUE TITLE
Error: genome has multiple contigs, please use -w to specify input region

### ISSUE THREAD

**Issue by Sudosundu** [jts/nanopolish#727]
I need to run
nanopolish --variants --consensus
I provided the bam, reads and the reference genome. My reference genome has 6 fasta files.

Error: genome has multiple contigs, please use -w to specify input region

How to select the input region?

**Comment by jts** [comment]
Please see the instructions here:

https://github.com/jts/nanopolish#computing-a-new-consensus-sequence-for-a-draft-assembly
