### ISSUE TITLE
Detecting uridylation and guanylation at the downstream of poly(A) tail

### ISSUE THREAD

**Issue by trandoanduyhai** [jts/nanopolish#728]
Dear Jared,
Nanopolish provides important tool to estimate the length of polyA tail. Since the U tails and G tails are often attached to poly(A) tails and play important role in control mRNA stability, is it possible to extract these information using nanopolish? 
Thank you very much!
Hai

**Comment by jts** [comment]
Hi @trandoanduyhai,

Currently the poly-A tail caller does not support polyU and polyG tails, as we haven't trained models for these.

Jared

**Comment by trandoanduyhai** [comment]
Thanks Jared!
