### ISSUE TITLE
Corrupt read, but which one?

### ISSUE THREAD

**Issue by hjjansen** [jts/nanopolish#73]
Hi Jared,

I'm running nanopolish 0.5. When I align the sequences with bwa mem all reads align and no errors are reported. When I then use eventalign to align the events one error is reported:

```
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140689784518592:
  #000: H5Dio.c line 173 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: H5Dio.c line 550 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: H5Dchunk.c line 1872 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: H5Dchunk.c line 2902 in H5D__chunk_lock(): data pipeline read failed
    major: Data filters
    minor: Filter operation failed
  #004: H5Z.c line 1382 in H5Z_pipeline(): filter returned failure during read
    major: Data filters
    minor: Read failed
  #005: H5Zdeflate.c line 125 in H5Z_filter_deflate(): inflate() failed
    major: Data filters
    minor: Unable to initialize object
terminate called after throwing an instance of 'hdf5_tools::Exception'
  what():  /Analyses/Basecall_1D_000/BaseCalled_template/Events: error in H5Dread
Aborted (core dumped)
```

eventalign will finish and produce an alignment file which is used to polish the contigs. Unfortunately four 10 Kbp chunks of one contig are missing and the merge command will fail when it tries to merge the corrected chunks.
From the error message I suspect one of the reads has a problem in the event part of the hdf5 file.
Is there a way to find out which read is corrupt so I can remove it from the dataset?

Thanks,

 Hans Jansen

**Comment by jts** [comment]
Hi Hans,

Did you use the local basecaller in MinKNOW for this run?

Thanks
Jared

**Comment by hjjansen** [comment]
Hello Jared,

Actually I did three runs to get enough data. All of them were basecalled by Metrichor. I'm using the template data from these reads.
As a intermediate solution I'm now using h5check on all readfiles. It's not really fast and still running but it already spotted two files with this error message:
`Invalid file size or file size less than superblock eoa. Validation stopped.`

Thanks,

Hans

**Comment by mateidavid** [comment]
Did you find malformed hdf5 files in the `pass/` download folder? This should be reported to ONT. I've only seen malformed files in `fail/` folder, and they are a pain to deal with if you need to process them.

**Comment by hjjansen** [comment]
h5check found two files in the pass folder of one out of three runs that didn't fit the hdf5 format. I removed those and run the nanopolish pipeline again and got the same error message.
bwa mem doesn't seem to have a problem with this dataset but maybe it can skip bad read files?
I'm not familiar with the inner structure of fast5 files but it could be an error introduced by copying the files from one server to another that corrupted the event part of the file. I'll ask support@ONT if this is possible and also if they have a tool that can check fast5 files because h5check seems to be missing something.
Because it is hdf5 that is throwing an error it is probably best if I ask hdf5group.org if it is possible to somehow extract the filename for the corrupt file.

**Comment by mateidavid** [comment]
BWA works with fasta/q files, it won't see fast5 files. HDF5 have a folder-like internal structure, and it is possible to have some paths that are corrupt but not others. To find out which files caused that particular error, try:

```
ds_path=/Analyses/Basecall_1D_000/BaseCalled_template/Events
for f in /path/to/*.fast5; do
    # skip files that don't have a dataset at that path
    h5dump -n 1 "$f" | grep -q $ds_path || continue
    # print files which produce errors when reading that dataset
    h5dump -N $ds_path "$f" >/dev/null 2>&1 || echo "bad file: $f"
done
```

**Comment by jts** [comment]
If you can isolate the read(s) that cause the problem using the code @mateidavid provides above, we'd be happy to take a closer look.

**Comment by hjjansen** [comment]
I'm running that now the data from all three runs. One has finished and showed no "bad files" The other two are still being processed but h5dump seems to be slower than h5check. Those will likely be finished after the weekend. If there are bad files I'll remove them and run nanopolish again and report back here.

Thanks to both you and Matei for all the help sofar,

Hans

**Comment by jts** [comment]
If this issue still occurs with nanopolish-0.6 please reopen the issue - closing for now.
