### ISSUE TITLE
fail to call polyA tail length with test dataset!

### ISSUE THREAD

**Issue by trandoanduyhai** [jts/nanopolish#730]
Dear Jared,
I installed Nanopolish v0.11.1 by "git checkout v0.11.1". After installation I checked nanopolish --version --> it showed me v0.9.0???
I continued to call polyA tail using test datasets provided by nanopolish:
nanopolish polya --threads=8 --reads=data/30xpolyA.fastq --bam=data/30xpolyA.sorted.bam --genome=data/enolase_reference.fas > polya_results.tsv
When I opened polya_results.tsv, I can only see:
usage: nanopolish [command] [options]
  valid commands: 
    --help
    --version
    call-methylation
    eventalign
    extract
    getmodel
    help
    index
    methyltrain
    phase-reads
    scorereads
    variants
  for help on given command, type nanopolish command --help
Looks like calling polya did not work! Maybe I got the wrong nanopolish version?
Hai

**Comment by jts** [comment]
Yes, it looks like you have the wrong version. Did you run `make` after `git checkout`? Also, make sure you don't have a different version of nanopolish on your `$PATH` (check with `which nanopolish`).

jared

**Comment by trandoanduyhai** [comment]
Thanks Jared! Indeed I did not remove the previous version.
Hai

**Comment by jts** [comment]
Glad this is resolved.
