### ISSUE TITLE
Eventalign duplications

### ISSUE THREAD

**Issue by akk01** [jts/nanopolish#732]
![Screen Shot 2020-02-21 at 11 13 29 AM](https://user-images.githubusercontent.com/25061318/75051058-368b8a00-549b-11ea-99c0-968c62de9a4c.png)

Do you recommend to use `model_mean` instead of `event_level_mean` for current intensity and drop duplications.

**Comment by jts** [comment]
Hi,

Sorry but I'm not sure I understand what you're asking?

Jared

**Comment by akk01** [comment]
For the same position and reference kmer, how can we have multiple `event_level_mean`

**Comment by jts** [comment]
Each row is an event measured by the sequencer in some read. These events are unique and are represented by a (read_idx, event_idx) pair. The rows are observations made by the sequencer and not duplicated.

**Comment by iremtll** [comment]
Hello I have a follow up question: I see the same read multiple times in my output. Which one is the correct one? Thanks a lot!
![image](https://user-images.githubusercontent.com/93679948/171065005-fd7fe29c-2dad-4d21-bc05-2e80e2e7540c.png)
@jts

**Comment by jts** [comment]
Hi,

Each line of output is a single event for a single read. It is expected that each read will have many lines of output. I describe eventalign in this blog post, which might help:

https://simpsonlab.github.io/2015/04/08/eventalign/

Jared

**Comment by iremtll** [comment]
Thanks a lot for your fast reply @jts !

The blog was very helpful but I still didn't get one thing from it: You are saying that it is an error in this part:

> The next 3 events (27471, 27472, 27473) are all aligned to the same reference 5-mer (TTGCG) indicating that the event detector erroneously called 3 events where only one should have been emitted. Note that the current for these 3 events are all plausibly drawn from the expected distribution N(51.68,0.732).

I didn't understand how this error is actually expected?

Thanks a lot ! 
Irem
