### ISSUE TITLE
nanopolish calling methylation only in certain chromosomes

### ISSUE THREAD

**Issue by Coracollar** [jts/nanopolish#733]
Hi,
I have been using nanopolish for a while and it works fine. However it is failing to call methylation in some of the chromosomes of one of my datasets.

First I did this:
#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=8
#SBATCH --time=0-200:00:00

source ~/anaconda3/etc/profile.d/conda.sh

conda activate Nanopore

nanopolish call-methylation -v  -t 8  -r /data/cephfs/punim1048/allbarcoded/CORT/CORT13/CORT13.fastq \
-b /data/cephfs/punim1048/allbarcoded/CORT/CORT13/CORT13.sorted.bam \
-g /data/cephfs/punim1048/GRCm38_genome/genome.fa -q cpg \
> /data/cephfs/punim1048/allbarcoded/CORT/CORT13/CORT13.tsv

And obtain:
[post-run summary] total reads: 9447801, unparseable: 0, qc fail: 14585, could not calibrate: 7545, no alignment: 194882, bad fast5: 213

When I started analysing my data I found that some chromosomes were missing (representation in the picture)
<img width="651" alt="Screen Shot 2020-02-26 at 3 55 10 pm" src="https://user-images.githubusercontent.com/57931696/75313231-60381d00-58b0-11ea-8779-c9dbe9a74fdc.png">

 I have checked the bam file and there are several reads covering that chromosome regions so I don't know what is happening. 

Also I tried to call methylation only in chr1 (which is one of the missing chromosomes in the calling).
#!/bin/bash
#SBATCH --ntasks=8
#SBATCH --cpus-per-task=4
#SBATCH --time=0-200:00:00

source ~/anaconda3/etc/profile.d/conda.sh

conda activate Nanopore

nanopolish call-methylation -v --min-separation 5  -t 8  -r /data/cephfs/punim1048/allbarcoded/CORT/CORT13/CORT13.fastq \
-b /data/cephfs/punim1048/allbarcoded/CORT/CORT13/CORT13.sorted.bam \
-g /data/cephfs/punim1048/GRCm38_genome/genome.fa -q cpg -w "chr1" \
> /data/cephfs/punim1048/allbarcoded/CORT/CORT13/CORT13_chr1.tsv

 I've tried with both the --min-separation 5 part and without. And I obtained:
[bam process] iterating over region: chr1

Can you help me?
Thanks

**Comment by jts** [comment]
Hi @Coracollar,

Is anything written to the output file at all? At the very least a header line should be there (starting with "chromosome"). Do you get a message in the terminal after `[bam process] iterating over region: chr1`?

You should not have to change the min-separation parameter so I suggest leaving this as the default value.

Jared

**Comment by Coracollar** [comment]
Hi!
Yes sorry, the output for the job (which would be the message in the terminal is:[bam process] iterating over region: chr1
The output file :

chromosome      strand  start   end     read_name       log_lik_ratio   log_lik_methylated      log_lik_unmethylated    num_calling_strands     num_motifs      sequence

**Comment by jts** [comment]
How long did the job run for? It may have run out of memory, can you try requesting more memory when submitting it to your HPC system?

**Comment by Coracollar** [comment]
Hi,
I will try a script with bigmem. The job for calling methylation in chr1 ran for less than a day. The whole genome one that had some chromosomes skipped ran for about 7 days.

**Comment by Coracollar** [comment]
Hi,
Same error with more memory.

**Comment by jts** [comment]
Can you try a small window like “chr1:40,000,000-50,000,000”?

**Comment by Coracollar** [comment]
Hi, I obtain the same again.

[bam process] iterating over region: chr1:40,000,000-50,000,000chromosome
    strand  start   end     read_name       log_lik_ratio
log_lik_methylated      log_lik_unmethylated    num_calling_strands
num_motifs      sequence

**Comment by jts** [comment]
Do you get a "[post-run summary]" message?

**Comment by Coracollar** [comment]
The post run summary is the part of:

[bam process] iterating over region.

And the out is the empty table

**Comment by jts** [comment]
What does the post run summary message say? Can you paste all the output you received?

**Comment by Coracollar** [comment]
This is the whole out:

[bam process] iterating over region: chr1:40,000,000-50,000,000chromosome

**Comment by Coracollar** [comment]
shit no the chromosome part was was from the message before. The slurm.out
is only this line. Nothing else. Just as the times before with only
chromosome 1. But now has the coordenates.

[bam process] iterating over region: chr1:40,000,000-50,000,000

**Comment by jts** [comment]
Ok, the post-run message has not been printed so either the process was killed by slurm, or it is still running.

Jared

**Comment by jts** [comment]
Closing, feel free to reopen if this is still an issue.
