### ISSUE TITLE
Query rather than an issue

### ISSUE THREAD

**Issue by pulichandramoulireddy** [jts/nanopolish#734]
Hi,
I have called methylation using nanopolish and I have attempted to visualize the data using 'deeptools'. 

I made a bedgraph file using log_lik_ratio as score and after filtering with log_lik_ratio>0.92 

my query 1) Is the cutoff value is good enough?
                2) I think you have used counts under 'called_sites_methylated' in 'methylation_frequency-tsv' file  to score, does it make difference if I use log_lik_ratio as score.
                 3) In my 'methylation_frequency.tsv' file there are many '0' values under 'methylated_frequency' column, is it filtering data correctly?

Suggestions will be of great help. Thank you!

**Comment by jts** [comment]
Hi,

1. I think that cutoff value is too low. I recommend using a cutoff of 2.0. This will be the default in the next release of nanopolish.
2. No, I use the `log_lik_ratio` column as the score, not `called_sites_methylated`. See here: https://github.com/jts/nanopolish/blob/master/scripts/calculate_methylation_frequency.py#L44
3. It is expected that some CpGs are not methylated. The proportion of unmethylated CpGs depends on the type of sample that you sequenced, so it is difficult for me to answer this question.

Jared

**Comment by pulichandramoulireddy** [comment]
Hi Jared,
Thank you for clarification. 
you have mentioned 'A positive value in the log_lik_ratio column indicates support for methylation.' then why to go for absolute value for filtration. we can use directly 2/2.5 as filter.

Secondly, is there a method to calculate total CG methylation percentage using the outfiles.

Mouli

**Comment by jts** [comment]
Imposing a threshold increases the accuracy of our calls. Calls with small LLR may be incorrect.

Yes, you can run `scripts/calculate_methylation_frequency.py -s -c 2.0 -i calls.tsv > frequency.tsv` to convert the calls to frequencies. It will implement all the logic we have discussed so you don't have to do it yourself.

Jared

**Comment by pulichandramoulireddy** [comment]
Thank you!

**Comment by jts** [comment]
No problem
