### ISSUE TITLE
minimap2 no dependency not documented

### ISSUE THREAD

**Issue by EricDeveaud** [jts/nanopolish#736]
Hello, 

you may want to update the doc to say that system minimap2 or user provided minimpa2 can be used when running make with ```MINIMPA2=noinstall``` exactly as eigen, htslib and hdf5

NB tarball compiles fine with the following provided via module environement and noinstall for all components

gcc/9.2.0
hdf5/1.10.6
htslib/1.10
eigen/3.3.7
fast5/0.6.5   
minimap2/2.17

regards

Eric

**Comment by jts** [comment]
Good catch, sorry for missing this. Fixed now and thanks for testing the noinstall build.
