### ISSUE TITLE
Consensus/variant caller hang up

### ISSUE THREAD

**Issue by zascavage** [jts/nanopolish#74]
Hello,
Thank you so much for this program. I am having a few issues with the commands though. Please forgive me, for I am not a programmer, so when the step by step instructions don't work, I get stuck easily. I cannot get the consensus/variant caller to work. The tells me I need to index FASTA, which I have already done. I think it has something to do with me entering the eventalign command in wrong? I am using the newer version of samtools, and there is no -f for it, so I modified it to be -o reads.eventalign.sorted.bam -

**Comment by jts** [comment]
Hi,

Could you send the complete set of commands you ran and any error messages?

Thanks,
Jared

**Comment by zascavage** [comment]
Hi Jared,
Thank you for getting back to me! I think I worked through that issue, and am now struggling with the same command, but another issue (or 3). Can you help me with a few things:

1.       Can my files be .fasta files or does the extension for the specifically need to be .fa? I know they’re both fasta files, but I wasn’t sure if the extension itself had an impact on anything.

2.       What happens if I do not copy the model files into the working directory? I have been unsuccessful at accomplishing this task. I skipped it for now and it seemed to still work on the next command, although I honestly can’t know that for sure since I can’t see the variants or consensus yet. I think I know the problem, and will address it in a minute as it ties into the next issue too.

3.       I copied the python nanopolish_makerange… word for word (changing only the file names, as seen on the image below), and it tells me it can’t open nanopolish_makerange.py because no such file or directory exists, but that file is in my usr/lib/nanopolish folder.

I think part of my issue is that I am using virtualbox, and I am running the disk image Nick Loman created for us at Porecamp. This means I do not have access to things such as my bash_profile. I cannot move things around in the usr folder, or any folder except the home folder than I have tried. This could be why I can’t find the model files to copy them as well. Every file from the image itself, meaning everything Nick gave us to run poretools and nanopolish , is locked from any modification.

As I mentioned, I am not a bioinformatics person. I am a wet-lab person attempting to learn bioinformatics enough to view my data. I am SO close! I just need a consensus and variant caller and I am golden! So, I do apologize as I assume my questions are elementary and obvious to anyone with any knowledge of how programming works.


Thank you so much for your help,

Roxanne R Zascavage
Post Doctoral Associate | Molecular and Medical Genetics
University of North Texas health Science Center | Office: CBH 356
3500 Camp Bowie Blvd | Fort Worth, TX 76107
817-735-2953
roxanne.zascavage@unthsc.edu<mailto:roxanne.zascavage@unthsc.edu>| www.unthsc.edu<http://www.unthsc.edu/>

**Comment by jts** [comment]
Hi Roxanne,

I'm happy to help, here are some quick replies:

1. It is OK if the file extension is `.fasta`, nanopolish doesn't actually look at these
2. Copying the model files is a requirement unfortunately, so you'll have to find a way to make this work. Maybe you can download them within your virtualbox instance from github?
3. I can't see the image (github doesnt support these) but maybe you need to try the full path? Something like `python /usr/lib/nanopolish/scripts/nanopolish_makerange.py` might work.

Jared

**Comment by zascavage** [comment]
Thank you! I will try these things and see how it turns out. You may be hearing from me again, but hopefully not!


Roxanne R Zascavage
Post Doctoral Associate | Molecular and Medical Genetics
University of North Texas health Science Center | Office: CBH 356
3500 Camp Bowie Blvd | Fort Worth, TX 76107
817-735-2953
roxanne.zascavage@unthsc.edu<mailto:roxanne.zascavage@unthsc.edu>| www.unthsc.edu<http://www.unthsc.edu/>

**Comment by zascavage** [comment]
Hi Jared,
So I was able to get the model files manually installed into my working directory. I am now hung up on the --models options for the nanopolish eventalign command. It says that is an unrecognized option and it doesn’t seem to appear in the help for the program… Any workaround or substitution I should be putting in there? I tried removing it, changing it to r9, etc.

Thank you again for all your help!

Roxanne R Zascavage
Post Doctoral Associate | Molecular and Medical Genetics
University of North Texas health Science Center | Office: CBH 356
3500 Camp Bowie Blvd | Fort Worth, TX 76107
817-735-2953
roxanne.zascavage@unthsc.edu<mailto:roxanne.zascavage@unthsc.edu>| www.unthsc.edu<http://www.unthsc.edu/>

**Comment by jts** [comment]
Hi Roxanne,

It sounds like you are running an old version of nanopolish. Can you update to the latest on GitHub and try again?

Jared

**Comment by zascavage** [comment]
OK… I think I got that worked out. I have to be sure I change the path to the new folder with nanopolish in it because the VDI has an old one that won’t upgrade. Yet I am still stuck…

So, I have somehow come full circle and ended up with the original error I asked about… [fai_load] build FASTA index. I have attached an image (jpeg this time), so hopefully you can see it.

I tried to continue on to see if the makerange.py would work after putting the path to the file in, and it still fails. This time is saids File “usr/lib/nanopolish/nanopolish_makerange.py”, line 2, in <module>
From Bio import SeqIO
ImportError: No module named Bio

I also attached that if you can see it… Please ignore the other mistakes I have made in entering these commands before getting here… It’s been a LONG day trying to get this to work out.

I again apologize! This makes me feel like such an idiot for not being able to figure it out.


Roxanne R Zascavage
Post Doctoral Associate | Molecular and Medical Genetics
University of North Texas health Science Center | Office: CBH 356
3500 Camp Bowie Blvd | Fort Worth, TX 76107
817-735-2953
roxanne.zascavage@unthsc.edu<mailto:roxanne.zascavage@unthsc.edu>| www.unthsc.edu<http://www.unthsc.edu/>

**Comment by jts** [comment]
Hi Roxanne,

No apologies necessary, there is always trouble running very new software. 

In this case the error: 

```
From Bio import SeqIO
ImportError: No module named Bio
```

means that the `BioPython` package is not installed. You might be able to easily install it with the command `pip install biopython`. If that doesn't work there are lengthier instructions online:

http://biopython.org/DIST/docs/install/Installation.html

PS: I still can't see the screenshot - you'll probably have to email to me

**Comment by zascavage** [comment]
Hey Jared!
I just wanted to let you know I have gotten everything working now, and have been able to replicate the set up on additional computers! Thank you for all your help!!!!


Roxanne R Zascavage
Post Doctoral Associate | Molecular and Medical Genetics
University of North Texas health Science Center | Office: CBH 356
3500 Camp Bowie Blvd | Fort Worth, TX 76107
817-735-2953
roxanne.zascavage@unthsc.edu<mailto:roxanne.zascavage@unthsc.edu>| www.unthsc.edu<http://www.unthsc.edu/>

**Comment by jts** [comment]
Great, glad to hear it!
