### ISSUE TITLE
different consensus sequences when I change the reference genome for the same virus

### ISSUE THREAD

**Issue by AhmadAlharbi7** [jts/nanopolish#741]
I aligned my gene sequence reads (gO genotype-2)  against the wild type whole genome of the virus ( which has gO-genotype-1) using minimap2.... and then I generated the consensus sequence using nanopolish ..... Surprisingly I found the the generated consensus sequence was not gO-2 as expected and similar to the reference gO-1 .... How the nanopolish counted the consensus sequence as gO-1 although all of my query reads have gO-2 sequences... When I changed the reference genome to the same genotype gO-2 and the generated consensus sequence was changed to the expected consensus sequence of gO-2... My question is that! Does nanopolish count the most frequently nucleotide at each location or it generates the consensus sequence based on the reference genome I used ! Why I get different consensus sequences when I change the reference genome? inspite of having the same query reads ?!

**Comment by jts** [comment]
Hi @AhmadAlharbi7,

How different are the genotypes? There are many possible explanations, including:

1) the reads may not align well
2) the sequencing depth is not high enough to make a confident call
3) the variants may be in difficult-to-call contexts

If you can provide the VCF files for the two cases (aligned to gt1 and aligned to gt2) I may be able to provide more help.

Jared
