### ISSUE TITLE
Calculate_methylation_frequency: TypeError

### ISSUE THREAD

**Issue by mbasam** [jts/nanopolish#742]
Hi SimpsonLab,

I have downloaded the latest version of Nanopolish (0.12.0), as of March 3rd 2020, and tried to run the calculate_methylation_frequency.py script in Python 3.6.6 but received the following error message:

Traceback (most recent call last):
  File "calculate_methylation_frequency.py", line 41, in <module>
    num_sites = int(record['num_motifs'])
TypeError: int() argument must be a string or a number, not 'NoneType'

From my quick troubleshooting, it seems like the code is trying to convert a list to an integer. I see it is within a for loop trying to go through the TSV, however, it runs into a snag. Any ideas on how to fix this?

**Comment by jts** [comment]
Hi,

It is likely that your input file is truncated in some way. Can you show me the end of the file (using `tail`)?

Thanks,
Jared

**Comment by mbasam** [comment]
Thank you! I should have checked that first. 

I have a few questions about the calculate_methylation_frequency.py script that I hope you can answer. 

1) I have 2 examples that I will include below where methylation_calls reports 4 reads at a CpG site, 1 methylated, 2 unmethylated, and the 4th is ambiguous (according to the new 2.0 threshold). However, methylation frequency reports that position as 2 called sites, 0 of which are methylated, so the methylated_frequency is 0.00. This happens again for another example. Are certain strands thrown out if they do not contain a + and a - read? If not, can you please explain why this is the case?

2) In the calculate_methyation_frequency.py script, I see the following code chunk:
` # Skip ambiguous call
        if abs(llr) < args.call_threshold * num_sites:
            continue
        sequence = record['sequence']

        is_methylated = llr > 0`

If an ambiguous read has a llr of 0, and the threshold is 2 and the num_sites is 1 (assuming there's 1 CpG), then wouldn't the if conditional be true and continue the script? [0<2*1] == TRUE, so continue. Shouldn't the logic be reversed to the following:
`if abs(llr) > args.call_threshold * num_sites:
   continue`
or `if abs(llr) < args.call_threshold * num_sites:
   skip`

Thank you for your help and creating this great tool!

**Comment by jts** [comment]
Hi @mbasam,

1. In this case the sequence has two CpGs, so `LLR > 4` will be called as methylated, and `LLR < -4` will be called as unmethylated. In 3075078 only the call with -4.11 LLR meets that threshold, so only that call is included. Note that in the frequency output file `called_sites` is `num_called_reads * num_motifs` (only one read was used here, not two). 

2. The `continue` statement jumps to the top of the loop, skipping the rest of the code in the loop (and hence skipping the call). I believe it is working as intended.

I hope that clears things up, sorry for the unclear output.

Jared

**Comment by mbasam** [comment]
Thanks for your help! This certainly clears things up for us.

**Comment by jts** [comment]
No problem, let me know if you need help with anything else.
