### ISSUE TITLE
Can't access nanopolish     -bash: .nanopolish: command not found 

### ISSUE THREAD

**Issue by hcheng78** [jts/nanopolish#745]
I'm using a Mac, I've used this: 
git clone --recursive https://github.com/jts/nanopolish.git
cd nanopolish
make

But it keeps on saying -bash: .nanopolish: command not found.
I've tried putting it in the path using echo, ./nanopolish and export NANOPOLISH_PATH=my path to nanopolish. But it continues to say it. 

I also encounter this error and warning when installing:
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang: error: unsupported option '-fopenmp'

Is there anything else I can consider doing.

**Comment by jts** [comment]
Hi,

The error message indicates the compilation failed. The `clang` compiler does not support openmp, which nanopolish uses, so you'll have to install `gcc` to build this.

Jared
