### ISSUE TITLE
Methylation call of insertions

### ISSUE THREAD

**Issue by Yeeok** [jts/nanopolish#746]
Hi,

I want to know the methylation level of the insertions (structural variant).
However, when I call methylation with nanopolish (hg38), I couldn't find any methylation level of insertions. Only CpGs within reference genome can be called their methylation level. 
I wonder that how I can call the methylation level of insertions.

Thank you.

- Yeeok Kang -

**Comment by jts** [comment]
Hi,

Sorry but this is not possible currently with the way we call methylation. We are interested in this too, so want to work on a solution in the future.

Jared
