### ISSUE TITLE
Methylation calling since nanopolish version 0.12.0

### ISSUE THREAD

**Issue by Wojard** [jts/nanopolish#747]
After version 0.12.0, when I try to run call-methylation on test data from the [tutorial](https://nanopolish.readthedocs.io/en/latest/quickstart_call_methylation.html) using command
`nanopolish call-methylation -t 8 -r methylation_example/albacore_output.fastq -b output.sorted.bam -g methylation_example/reference.fasta -w "chr20:5,000,000-10,000,000" > methylation_calls.tsv`
I get warnings like these:
`HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140473320077056:
  #000: H5L.c line 813 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
[warning] fast5 file is unreadable and will be skipped: methylation_example/fast5_files//LomanLabz_PC_20161122_FNFAF01441_MN17024_sequencing_run_20161122_Human_Qiagen_1D_R9_4_81666_ch76_read1556_strand.fast5`
and, as a result,
`[post-run summary] total reads: 20626, unparseable: 0, qc fail: 6, could not calibrate: 3, no alignment: 90, bad fast5: 18573`

If I run the exact same command, using nanopolish version 0.11.3, output will be
`[bam process] iterating over region: chr20:5,000,000-10,000,000
[post-run summary] total reads: 19759, unparseable: 0, qc fail: 74, could not calibrate: 28, no alignment: 1828, bad fast5: 0`

**Comment by jts** [comment]
Hi,

I have tried this locally and it appears to be working as expected. Can you try to re-run the `nanopolish index` step, and if that doesn't work, try to re-build the program from scratch?

Jared

**Comment by jts** [comment]
I think this is now fixed in v0.12.3.

**Comment by Wojard** [comment]
Thanks! Now everything works.
