### ISSUE TITLE
HDF5 issue

### ISSUE THREAD

**Issue by flauro** [jts/nanopolish#75]
I have been trying to run Nanopolish on an assembly done with the new rapid 1d kits and keep getting this error.

registering model t.007-base
registering model t.007-ONT
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 139897868146432:
  #000: H5D.c line 358 in H5Dopen2(): not found
    major: Dataset
    minor: Object not found
  #001: H5Gloc.c line 430 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #002: H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #003: H5Gtraverse.c line 641 in H5G_traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #004: H5Gloc.c line 385 in H5G_loc_find_cb(): object 'Events' doesn't exist
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 139897878636288:
  #000: H5D.c line 358 in H5Dopen2(): not found
    major: Dataset
    minor: Object not found
  #001: H5Gloc.c line 430 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #002: H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #003: H5Gtraverse.c line 641 in H5G_traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #004: H5Gloc.c line 385 in H5G_loc_find_cb(): object 'Events' doesn't exist
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 139897920604096:
  #000: H5D.c line 358 in H5Dopen2(): not found
    major: Dataset
    minor: Object not found
  #001: H5Gloc.c line 430 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #002: H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #003: H5Gtraverse.c line 641 in H5G_traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #004: H5Gloc.c line 385 in H5G_loc_find_cb(): object 'Events' doesn't exist
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 139897910105856:
  #000: H5D.c line 358 in H5Dopen2(): not found
    major: Dataset
    minor: Object not found
  #001: H5Gloc.c line 430 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #002: H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #003: H5Gtraverse.c line 641 in H5G_traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #004: H5Gloc.c line 385 in H5G_loc_find_cb(): object 'Events' doesn't exist
    major: Symbol table
    minor: Object not found
terminate called recursively
terminate called after throwing an instance of 'hdf5_tools::Exception'
terminate called recursively
  what():  /Analyses/Basecall_1D_000/BaseCalled_template/Events: error in H5Dopen[samopen] SAM header is present: 5 sequences.

**Comment by jts** [comment]
Hi,

Did you use the new local basecalling option in MinKNOW?

Jared

**Comment by flauro** [comment]
Hi Jared,


Yes I did.


Federico


________________________________

**Comment by jts** [comment]
Ok - this is a known issue then. The current local MinKNOW basecaller doesn't write out events. I'll try to push a workaround tomorrow but you'll need to use the cloud basecaller first.

**Comment by flauro** [comment]
Ok so I just retried on the cloud basecalled /pass folder and I get the same problem. Although the cloud basecalling was done on the fast5 files from the local basecaller so I am not sure if the issue carries on.

Cheers,

Federico

________________________________

**Comment by jts** [comment]
Yes, as long as the cloud basecaller has been run already the fix I'll make tomorrow will work - sorry I was unclear just now.

**Comment by flauro** [comment]
Ok thanks. I will look for it tomorrow.


Best,


Federico


________________________________

**Comment by flauro** [comment]
Dear Jared,


Have you managed to work out a fix for this issue?


Best,


Federico


________________________________

**Comment by jts** [comment]
Sorry, no. I've been caught up by other things and the fix isn't as simple as I first thought (for 1D reads poretools will take the fasta sequence from the local basecaller group but nanopolish can't use those reads).

**Comment by jts** [comment]
Hi @flauro,

@mateidavid is working on a solution for this problem. Could you email me a single example read so we can test our solution? My email is jared.simpson@oicr.on.ca

Thanks!

**Comment by jts** [comment]
Hi @flauro,

We've now got a solution that will allow your reads to be used with nanopolish. If you use the new `nanopolish extract` module to export your reads to a fasta file (rather than `poretools`) the extracted reads should work with the rest of the pipeline. This new module has been checked into github so if you grab the latest code and compile (remembering to run `git submodule update` as well) you should be all set.

Thanks to @mateidavid for implementing this.

Let us know how it looks!

Jared
