### ISSUE TITLE
polyA estimation tutorial run error

### ISSUE THREAD

**Issue by callumparr** [jts/nanopolish#750]
I was working through the tutorial on and ran through the nanopolish but it outputs a lot of errors although it does finally output length estimation. Are these errors just related to running old single fast5 files through the latest nanopolish release v0.12a?

`
  #000: H5L.c line 813 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
[warning] fast5 file is unreadable and will be skipped: data/30xpolyA/fast5/pass/MINICOL596_20180206_FAH55913_MN19174_sequencing_throughput_LS_RNA_21456_30xpolyA_11237_read_6001_ch_282_strand.fast5
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140009572910848:
  #000: H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 990 in H5F_open(): unable to open file: time = Mon Mar 23 13:53:38 2020
, name = 'data/30xpolyA/fast5/pass/MINICOL596_20180206_FAH55913_MN19174_sequencing_throughput_LS_RNA_21456_30xpolyA_11237_read_1380_ch_184_strand.fast5', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 992 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: H5FDsec2.c line 343 in H5FD_sec2_open(): unable to open file: name = 'data/30xpolyA/fast5/pass/MINICOL596_20180206_FAH55913_MN19174_sequencing_throughput_LS_RNA_21456_30xpolyA_11237_read_1380_ch_184_strand.fast5', errno = 24, error message = 'Too many open files', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140009572910848:
  #000: H5L.c line 813 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140009572910848:
  #000: H5L.c line 813 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
[warning] fast5 file is unreadable and will be skipped: data/30xpolyA/fast5/pass/MINICOL596_20180206_FAH55913_MN19174_sequencing_throughput_LS_RNA_21456_30xpolyA_11237_read_1380_ch_184_strand.fast5
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140009589696256:
  #000: H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 990 in H5F_open(): unable to open file: time = Mon Mar 23 13:53:38 2020
, name = 'data/30xpolyA/fast5/pass/MINICOL596_20180206_FAH55913_MN19174_sequencing_throughput_LS_RNA_21456_30xpolyA_11237_read_1151_ch_430_strand.fast5', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 992 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: H5FDsec2.c line 343 in H5FD_sec2_open(): unable to open file: name = 'data/30xpolyA/fast5/pass/MINICOL596_20180206_FAH55913_MN19174_sequencing_throughput_LS_RNA_21456_30xpolyA_11237_read_1151_ch_430_strand.fast5', errno = 24, error message = 'Too many open files', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140009589696256:
  #000: H5L.c line 813 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140009589696256:
  #000: H5L.c line 813 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
[warning] fast5 file is unreadable and will be skipped: data/30xpolyA/fast5/pass/MINICOL596_20180206_FAH55913_MN19174_sequencing_throughput_LS_RNA_21456_30xpolyA_11237_read_1151_ch_430_strand.fast5
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140009640052480:
  #000: H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 990 in H5F_open(): unable to open file: time = Mon Mar 23 13:53:38 2020
, name = 'data/30xpolyA/fast5/pass/MINICOL596_20180206_FAH55913_MN19174_sequencing_throughput_LS_RNA_21456_30xpolyA_11237_read_1481_ch_445_strand.fast5', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 992 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: H5FDsec2.c line 343 in H5FD_sec2_open(): unable to open file: name = 'data/30xpolyA/fast5/pass/MINICOL596_20180206_FAH55913_MN19174_sequencing_throughput_LS_RNA_21456_30xpolyA_11237_read_1481_ch_445_strand.fast5', errno = 24, error message = 'Too many open files', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140009640052480:
  #000: H5L.c line 813 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140009640052480:
  #000: H5L.c line 813 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
[warning] fast5 file is unreadable and will be skipped: data/30xpolyA/fast5/pass/MINICOL596_20180206_FAH55913_MN19174_sequencing_throughput_LS_RNA_21456_30xpolyA_11237_read_1481_ch_445_strand.fast5
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140009656837888:
  #000: H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 990 in H5F_open(): unable to open file: time = Mon Mar 23 13:53:38 2020
, name = 'data/30xpolyA/fast5/pass/MINICOL596_20180206_FAH55913_MN19174_sequencing_throughput_LS_RNA_21456_30xpolyA_11237_read_2757_ch_123_strand.fast5', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 992 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: H5FDsec2.c line 343 in H5FD_sec2_open(): unable to open file: name = 'data/30xpolyA/fast5/pass/MINICOL596_20180206_FAH55913_MN19174_sequencing_throughput_LS_RNA_21456_30xpolyA_11237_read_2757_ch_123_strand.fast5', errno = 24, error message = 'Too many open files', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140009656837888:
  #000: H5L.c line 813 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140009656837888:
  #000: H5L.c line 813 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
[warning] fast5 file is unreadable and will be skipped: data/30xpolyA/fast5/pass/MINICOL596_20180206_FAH55913_MN19174_sequencing_throughput_LS_RNA_21456_30xpolyA_11237_read_2757_ch_123_strand.fast5
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140009623267072:
  #000: H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 990 in H5F_open(): unable to open file: time = Mon Mar 23 13:53:38 2020
, name = 'data/30xpolyA/fast5/pass/MINICOL596_20180206_FAH55913_MN19174_sequencing_throughput_LS_RNA_21456_30xpolyA_11237_read_331_ch_468_strand.fast5', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 992 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: H5FDsec2.c line 343 in H5FD_sec2_open(): unable to open file: name = 'data/30xpolyA/fast5/pass/MINICOL596_20180206_FAH55913_MN19174_sequencing_throughput_LS_RNA_21456_30xpolyA_11237_read_331_ch_468_strand.fast5', errno = 24, error message = 'Too many open files', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140009623267072:
  #000: H5L.c line 813 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140009623267072:
  #000: H5L.c line 813 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
[warning] fast5 file is unreadable and will be skipped: data/30xpolyA/fast5/pass/MINICOL596_20180206_FAH55913_MN19174_sequencing_throughput_LS_RNA_21456_30xpolyA_11237_read_331_ch_468_strand.fast5
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140009648445184:
  #000: H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 990 in H5F_open(): unable to open file: time = Mon Mar 23 13:53:38 2020
, name = 'data/30xpolyA/fast5/pass/MINICOL596_20180206_FAH55913_MN19174_sequencing_throughput_LS_RNA_21456_30xpolyA_11237_read_1525_ch_63_strand.fast5', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 992 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: H5FDsec2.c line 343 in H5FD_sec2_open(): unable to open file: name = 'data/30xpolyA/fast5/pass/MINICOL596_20180206_FAH55913_MN19174_sequencing_throughput_LS_RNA_21456_30xpolyA_11237_read_1525_ch_63_strand.fast5', errno = 24, error message = 'Too many open files', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140009648445184:
  #000: H5L.c line 813 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140009648445184:
  #000: H5L.c line 813 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
[warning] fast5 file is unreadable and will be skipped: data/30xpolyA/fast5/pass/MINICOL596_20180206_FAH55913_MN19174_sequencing_throughput_LS_RNA_21456_30xpolyA_11237_read_1525_ch_63_strand.fast5
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140009614874368:
  #000: H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 990 in H5F_open(): unable to open file: time = Mon Mar 23 13:53:38 2020
, name = 'data/30xpolyA/fast5/pass/MINICOL596_20180206_FAH55913_MN19174_sequencing_throughput_LS_RNA_21456_30xpolyA_11237_read_1031_ch_134_strand.fast5', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 992 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: H5FDsec2.c line 343 in H5FD_sec2_open(): unable to open file: name = 'data/30xpolyA/fast5/pass/MINICOL596_20180206_FAH55913_MN19174_sequencing_throughput_LS_RNA_21456_30xpolyA_11237_read_1031_ch_134_strand.fast5', errno = 24, error message = 'Too many open files', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140009614874368:
  #000: H5L.c line 813 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140009614874368:
  #000: H5L.c line 813 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
[warning] fast5 file is unreadable and will be skipped: data/30xpolyA/fast5/pass/MINICOL596_20180206_FAH55913_MN19174_sequencing_throughput_LS_RNA_21456_30xpolyA_11237_read_1031_ch_134_strand.fast5
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140009581303552:
  #000: H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 990 in H5F_open(): unable to open file: time = Mon Mar 23 13:53:38 2020
, name = 'data/30xpolyA/fast5/pass/MINICOL596_20180206_FAH55913_MN19174_sequencing_throughput_LS_RNA_21456_30xpolyA_11237_read_934_ch_444_strand.fast5', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 992 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: H5FDsec2.c line 343 in H5FD_sec2_open(): unable to open file: name = 'data/30xpolyA/fast5/pass/MINICOL596_20180206_FAH55913_MN19174_sequencing_throughput_LS_RNA_21456_30xpolyA_11237_read_934_ch_444_strand.fast5', errno = 24, error message = 'Too many open files', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140009581303552:
  #000: H5L.c line 813 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140009581303552:
  #000: H5L.c line 813 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
[warning] fast5 file is unreadable and will be skipped: data/30xpolyA/fast5/pass/MINICOL596_20180206_FAH55913_MN19174_sequencing_throughput_LS_RNA_21456_30xpolyA_11237_read_934_ch_444_strand.fast5
`

`
[post-run summary] total reads: 63797, unparseable: 0, qc fail: 1, could not calibrate: 0, no alignment: 0, bad fast5: 61759`

**Comment by jts** [comment]
Hi, 

This was a bug in <=0.12.2. If you update for 0.12.3 it should work.

Sorry
jared
