### ISSUE TITLE
Problems installing nanopolish

### ISSUE THREAD

**Issue by ThWacker** [jts/nanopolish#751]
Hello, 

when I try to install nanopolish on my macOS Catalina 10.15.3 with Darwin 19.3.0, python 3.7 and Apple clang version 11.0.0 (clang-1100.0.33.16), I get, once I type "make" after git cloning and cd-ing to the nanopolish folder, the following Error:

> c++ -o src/main/nanopolish.o -c -g -O3 -std=c++11 -fopenmp -fsigned-char -D_FILE_OFFSET_BITS=64  -I./include -I./htslib -I./minimap2 -I./fast5/include -I./src -I./src/hmm -I./src/thirdparty -I./src/thirdparty/scrappie -I./src/common -I./src/alignment -I./src/pore_model -I./src/io -I./eigen/ -fPIC src/main/nanopolish.cpp
clang: error: unsupported option '-fopenmp'
make: *** [src/main/nanopolish.o] Error 1

> 

Any help would be greatly appreciated! Many many thanks in advance!

Cheers

**Comment by jts** [comment]
Please try with gcc, clang doesn't support OpenMP which nanopolish relies on.

**Comment by ThWacker** [comment]
Thank you! I will try that!
