### ISSUE TITLE
does nanopolish work on unix? bad fast5, path weirdness

### ISSUE THREAD

**Issue by dunedice** [jts/nanopolish#752]
Hello from yesterday, I am copying my comments into this new issue, because help!

Hello,

I am having a path problem I do not know how to fix with bad fast5, indexing, etc., probably simple fix.

Background: I can get indexing all the way to event calls to work on my local [ a Mac OSx]. Test run looks like:

    nanopolish index -d path.to.fast5 0-1.fastq
    [readdb] indexing path.to.fast5
    [readdb] num reads: 1900357, num reads with path to fast5: 1900357

    graphmap align -r ../../../../../reference_genomes/SAFR032/NC_009848.4.fasta -d 0-1.fastq -o test_whee.sam

    ~/src/samtools/samtools view -bS test_whee.sam | ~/src/samtools/samtools sort -T test_whee.sorted -o test_whee.sorted.bam

    ~/src/samtools/samtools index test_whee.sorted.bam

    nanopolish eventalign -t 1 --scale-events -n -r 0-1.fastq -b test_whee.sorted.bam -g ../../../../../reference_genomes/SAFR032/NC_009848.4.fasta > test_whee.eventalign.tsv

    head -n 5 test_whee.eventalign.tsv
    contig position reference_kmer read_name strand event_index event_level_mean event_stdv event_length model_kmer model_mean model_stdv standardized_level
    NC_009848.4 0 ATGGAA 81636499-3f40-4de0-9d1a-2f6448891da9 t 1788 87.61 2.274 0.00175 ATGGAA 89.70 3.23 -0.60
    NC_009848.4 1 TGGAAA 81636499-3f40-4de0-9d1a-2f6448891da9 t 1789 74.17 2.564 0.00150 TGGAAA 73.55 1.83 0.31
    NC_009848.4 1 TGGAAA 81636499-3f40-4de0-9d1a-2f6448891da9 t 1790 70.97 0.823 0.00075 TGGAAA 73.55 1.83 -1.31
    NC_009848.4 2 GGAAAA 81636499-3f40-4de0-9d1a-2f6448891da9 t 1791 74.57 1.154 0.00175 GGAAAA 76.43 1.68 -1.03

    head -n 5 0-1.fastq.index.readdb
    0000012c-8c3b-4503-96b8-e93aead9b057 /Volumes/theBigBad/RESEARCH/MinION_Sequencing/RUNS/190516-DS1-firstDNArun/DS1_DNA/20190516_2256_MN29361_FAK40688_abf3d95c/fast5/FAK40688_c72d21a84b6f30ff65ff144448b26d8fa2640600_309.fast5
    000006ed-9596-40d6-8e62-77726e9976b2 /Volumes/theBigBad/RESEARCH/MinION_Sequencing/RUNS/190516-DS1-firstDNArun/DS1_DNA/20190516_2256_MN29361_FAK40688_abf3d95c/fast5/FAK40688_c72d21a84b6f30ff65ff144448b26d8fa2640600_179.fast5
    00003489-1e14-4c53-8d7a-2baef11a5aac /Volumes/theBigBad/RESEARCH/MinION_Sequencing/RUNS/190516-DS1-firstDNArun/DS1_DNA/20190516_2256_MN29361_FAK40688_abf3d95c/fast5/FAK40688_c72d21a84b6f30ff65ff144448b26d8fa2640600_17.fast5
    000035eb-7245-40cc-8007-4dbc26a937d7 /Volumes/theBigBad/RESEARCH/MinION_Sequencing/RUNS/190516-DS1-firstDNArun/DS1_DNA/20190516_2256_MN29361_FAK40688_abf3d95c/fast5/FAK40688_c72d21a84b6f30ff65ff144448b26d8fa2640600_340.fast5
    0000528e-b09c-437c-b1f2-9f7d8ac5b922 /Volumes/theBigBad/RESEARCH/MinION_Sequencing/RUNS/190516-DS1-firstDNArun/DS1_DNA/20190516_2256_MN29361_FAK40688_abf3d95c/fast5/FAK40688_c72d21a84b6f30ff65ff144448b26d8fa2640600_249.fast5

Yay, it worked. But I have a lot of data and need to run this on the cluster available to me, so Unix system, and now I have rinsed and repeated with all the variations of paths to the fast5 directory and it still is not finding them, bad fast5 style.

That looks like:

    nanopolish index -d /nobackupp13/smwaters/test_mcaller/small_fast5 0-1.fastq
    [readdb] indexing /nobackupp13/smwaters/test_mcaller/small_fast5
    [readdb] num reads: 16000, num reads with path to fast5: 8000

Right there, it is doubling the number of reads. No, these aren't 2d, they are 1d. And I continue:

    graphmap align -r NC_009848.4.fasta -d 0-1.fastq -o test_small.sam

    samtools view -bS test_small.sam | samtools sort -T test_small.sorted -o test_small.sorted.bam

    samtools index test_small.sorted.bam

    nanopolish eventalign --scale-events -n -r 0-1.fastq -b test_small.sorted.bam -g NC_009848.4.fasta > test_small.eventalign.tsv
    [fai_load] build FASTA index.
    [post-run summary] total reads: 7361, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 7361

woot, there it is.

    head -n 2 0-1.fastq.index.readdb
    000b3a98-1e28-4071-b124-5dc5dcb0899b /nobackupp13/smwaters/test_mcaller/small_fast5/FAK40688_c72d21a84b6f30ff65ff144448b26d8fa2640600_0.fast5
    0014e97f-873e-4089-b96e-0fe06b6cb48d /nobackupp13/smwaters/test_mcaller/small_fast5/FAK40688_c72d21a84b6f30ff65ff144448b26d8fa2640600_1.fast5

I have tried all the flavors of path to fast5, and even tried all of the hundreds of fast5 files, which returns some interesting stuff:

    nanopolish index -d ./fast5 0-1.fastq
    [readdb] indexing ./fast5
    [readdb] num reads: 900000, num reads with path to fast5: 892000

That is the mostly full fast5 directory with all the data, huge. My test run only has 8000 reads, and I am noticing here that the difference between those two numbers is 8000. Why!?

    nanopolish index -d fast5 0-1.fastq
    [readdb] indexing fast5
    [readdb] num reads: 900000, num reads with path to fast5: 892000

Does the same thing.

And then I try with the full path to the mostly full fast5 directory:

    nanopolish index -d /nobackupp13/smwaters/test_mcaller/fast5 0-1.fastq
    [readdb] indexing /nobackupp13/smwaters/test_mcaller/fast5
    [readdb] num reads: 900000, num reads with path to fast5: 892000

The unix .readdb output

head -n 5 0-1.fastq.index.readdb
000006ed-9596-40d6-8e62-77726e9976b2 /nobackupp13/smwaters/test_mcaller/fast5/FAK40688_c72d21a84b6f30ff65ff144448b26d8fa2640600_179.fast5
00003489-1e14-4c53-8d7a-2baef11a5aac /nobackupp13/smwaters/test_mcaller/fast5/FAK40688_c72d21a84b6f30ff65ff144448b26d8fa2640600_17.fast5
0000528e-b09c-437c-b1f2-9f7d8ac5b922 /nobackupp13/smwaters/test_mcaller/fast5/FAK40688_c72d21a84b6f30ff65ff144448b26d8fa2640600_249.fast5
00005ae3-810c-423f-a1d4-cb03256d72d6 /nobackupp13/smwaters/test_mcaller/fast5/FAK40688_c72d21a84b6f30ff65ff144448b26d8fa2640600_286.fast5
00007ce9-817c-4e6b-98f4-7a90722e46d0 /nobackupp13/smwaters/test_mcaller/fast5/FAK40688_c72d21a84b6f30ff65ff144448b26d8fa2640600_245.fast5

The .readdb output matches correctly the reads to the appropriate fast5 files on both the mac and the unix, compare the following:

00003489-1e14-4c53-8d7a-2baef11a5aac /nobackupp13/smwaters/test_mcaller/fast5/FAK40688_c72d21a84b6f30ff65ff144448b26d8fa2640600_17.fast5

from the cluster and then the readdb file on the mac:

00003489-1e14-4c53-8d7a-2baef11a5aac /Volumes/theBigBad/RESEARCH/MinION_Sequencing/RUNS/190516-DS1-firstDNArun/DS1_DNA/20190516_2256_MN29361_FAK40688_abf3d95c/fast5/FAK40688_c72d21a84b6f30ff65ff144448b26d8fa2640600_17.fast5

they are matching the reads with the fast5 files on both systems, there is something else going on in the unix environment and i can't figure it out. 

why would a mismatch only be happening on the unix sytem? And why would the .readdb show the correct matching of the reads with the correct fast5 like when run on the mac?

could this be an environmental issue? in which case, that is above my pay grade, I am a biologist who just runs these things when possible.

any advice or help, even if it comes tomorrow would be greatly appreciated.

thank you.

**Comment by jts** [comment]
Yes, it works on unix. 

Please do the following commands and send me the results.

```
head -4 0-1.fastq
```

This will print the first read in your fastq file. Please take the ID of this read and grep it in the .readdb file on your Mac, then on unix system:

```
grep <ID> mac.index.readdb
grep <ID> unix.index.readdb
```

**Comment by dunedice** [comment]
OK, i think i understand now. All the fast5 finished uploading last night, the first reads in fastq are the last reads in the fast5, because that happens. Hopefully no more issues!

Thank you for helping, very appreciated.
