### ISSUE TITLE
HELP! python3 nanopolish_makerange.py command

### ISSUE THREAD

**Issue by drodriguera** [jts/nanopolish#755]
Greetings!

I am trying to run the following command from Nanopolish, but I always get the error that doesn't find nanopolish_makerange.py

Command in Nanopolish

python3 nanopolish_makerange.py draft.fa | parallel --results nanopolish.results -P 8 \    nanopolish variants --consensus -o polished.{1}.vcf -w {1} -r reads.fa -b reads.sorted.bam -g draft.fa -t 4 --min-candidate-frequency 0.1
My command

cd /project/uma_kristen_deangelis/MinIONData/DataProcessing/GP_174/fast5filesGP174/fast5_pass

python3 nanopolish_makerange.py CanuAssemblyTest1_0.12_GP174_03_06_20.contigs.fasta | parallel --results nanopolish.results -P 8 \

    nanopolish variants --consensus polished.{1}.fa -w {1} -r BBMAPConcatenationGP174.fasta -b out.bam -g CanuAssemblyTest1_0.12_GP174_03_06_20.contigs.fasta -t 4

Another thing I tried was creating the nanopolish_makerange.py so I created with the following (https://github.com/jts/nanopolish/blob/master/scripts/nanopolish_makerange.py )

#! /usr/bin/env python3

import sys

import argparse

from Bio.SeqIO.FastaIO import SimpleFastaParser

parser = argparse.ArgumentParser(description='Partition a genome into a set of overlapping segments')

parser.add_argument('--segment-length', type=int, default=50000)

parser.add_argument('--overlap-length', type=int, default=200)

args, extra = parser.parse_known_args()

if len(extra) != 1:

    sys.stderr.write("Error: a genome file is expected\n")

filename = extra[0]

with open(filename) as handle:

    recs = [(title.split(None, 1)[0], len(seq))

            for title, seq in SimpleFastaParser(handle)]

SEGMENT_LENGTH = args.segment_length

OVERLAP_LENGTH = args.overlap_length

MIN_SEGMENT_LENGTH = 5 * OVERLAP_LENGTH

for name, length in recs:

    n_segments = (length / SEGMENT_LENGTH) + 1

    start = 0

    while start < length:

        end = start + SEGMENT_LENGTH

        # If this segment will end near the end of the contig, extend it to end

        if length - end < MIN_SEGMENT_LENGTH:

            print("%s:%d-%d" % (name, start, length - 1))

            start = length

        else:

            print("%s:%d-%d" % (name, start, end + OVERLAP_LENGTH))

            start = end

But also didn't work it says 

/home/dr66a/.lsbatch/1585691480.3355502.shell: line 17: parallel: command not found

Traceback (most recent call last):

  File "nanopolish_makerange.py", line 6, in <module>

    from Bio.SeqIO.FastaIO import SimpleFastaParser

ImportError: No module named 'Bio'

What am I doing wrong?

**Comment by jts** [comment]
Hi,

When running `nanopolish_makerange.py` you need to provide the full path to where you downloaded nanopolish, like this:

```
python /path/to/nanopolish/scripts/nanopolish_makerange.py [...]
```

I hope this helps,
Jared

**Comment by drodriguera** [comment]
Hello, Thank you so much for your response!

Another question what specific version of phyton should I be using? 
I have been using python3 3.5.0 and python3/3.5.0_packages/biopython/1.74, but doesnt work. 

I have be getting this (please ignore the part of perl warning)

nanopolish v0.12.5 is located under /share/pkg/nanopolish/v0.12.5
python3 3.5.0 is located under /share/pkg/python3/3.5.0
gnu_parallel 20160522 is located under /share/pkg/gnu_parallel/20160522
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
**Traceback (most recent call last):
  File "/share/pkg/nanopolish/v0.12.5/scripts/nanopolish_makerange.py", line 6, in <module>
    from Bio.SeqIO.FastaIO import SimpleFastaParser
ImportError: No module named Bio.SeqIO.FastaIO**

Thank yoy in advance!

**Comment by drodriguera** [comment]
Hello I solved that problem 

Now I am in the step of making the VCF files but I dont know if they are correct. Any suggestion/opinion if everythings is working fine? In the part of CHROM, POS, ID, REF.... I suppose to get something? 

##fileformat=VCFv4.2

##nanopolish_window=tig00000027:0-50000

##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">

##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">

##INFO=<ID=SupportFractionByStrand,Number=2,Type=Float,Description="Fraction of event-space reads that support the variant for each strand">

##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">

##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">

##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">

##INFO=<ID=StrandSupport,Number=4,Type=Integer,Description="Number of reads supporting the REF and ALT allele, by strand">

##INFO=<ID=StrandFisherTest,Number=1,Type=Integer,Description="Strand bias fisher test">

##INFO=<ID=SOR,Number=1,Type=Float,Description="StrandOddsRatio test from GATK">

##INFO=<ID=RefContext,Number=1,Type=String,Description="The reference sequence context surrounding the variant call">

##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample

**Comment by jts** [comment]
Hi @drodriguera,

It can take some time for the variant calls to show up. I hope the run completed successfully, if not please reopen this issue with any new errors you had.

Jared
