### ISSUE TITLE
problem with call-methylation or indexing

### ISSUE THREAD

**Issue by stefanucci-luca** [jts/nanopolish#756]
Hi there!

I am trying to call methylations, but I'm stuck in an error message. 

I first index with:
```nanopolish index -v -d /directory/to/multi_fast5_direcotry directory/to/fastq.gz```
I used minimap2 to align the reads.

The indexing run for ~ 6 hours and I get the data: ``` .index, .index.fai, .index.gzi  .index.readdb```

When I run the call-methylation command:
```nanopolish call-methylation  -r /path/to/file.fastq.gz -b /path/to/file.bam -g /path/to/reference.dna.fasta -v -q cpg --progress```

I get:
```
chromosome	strand	start	end	read_name	log_lik_ratio	log_lik_methylated	log_lik_unmethylated	num_calling_strands	num_motifs	sequence
[post-run summary] total reads: 18901, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 18901
```
So it can't match the reads to the fast5 file to my undersanting.

If I do:
```zcat fastq.gz | head ```
```
@b24b366d-fecb-4040-ab52-5703323eb26c  .........
@489e1a45-7f67-400a-8425-4cb87769d584 ........
@fe8a028c-cccb-4493-93cb-517de84d6ed2 .......
```
 and ```cat readdb | head```
```
0000052f-d09d-47f2-9405-fb1f0d76a383	/rdsc_366.fast5
000007e6-aea4-4137-8c01-1524ac221db5	/rds/pr7fea3c_556.fast5
00000d8d-e991-4199-a2cb-371c54d04e5d	/rdsf17fea3c_941.fast5
```
if I do: ```grep -n fe8a028c-cccb-4493-93cb-517de84d6ed2``` in the readdb the index is present on line 4256668, out of 4281200 total lines

It looks to me that reads are there but not in the correct order. 

I am using 
```
nanopolish version 0.12.5
Written by Jared Simpson.

Copyright 2015-2017 Ontario Institute for Cancer Research
```
And I installed it with conda.

Could you help me out to sort this problem?

Thanks a lot!

**Comment by jts** [comment]
The paths in the `readdb` file look strange and the fast5 filenames don't appear to follow the typical ONT naming convention. Did you use any software to modify the fast5s?

Are you able to access the fast5 directories from the location that you are trying to run in?

```
ls /rds/pr7fea3c_556.fast5
```

**Comment by stefanucci-luca** [comment]
Hi there, 

Thanks for your answer.

The path is my fault. There are some sensible data in the path, so while writing in here I took them out, but I forgot to reshape them in a nicer way. But yes, the path in the original file are correct.

**Comment by jts** [comment]
It is difficult to help without seeing the exact paths because sometime the issue can be subtle. If you prefer you can email me the information instead of sharing it here publicly.

To answer the question from your first post, the order of the reads in readdb is fine. Nanopolish use a map from read it to fast5 path and it is output in sorted order.

Jared

**Comment by stefanucci-luca** [comment]
Hi Jared,

Could I have your email, so I can send you the information you need?

Thanks,
Luca

**Comment by jts** [comment]
jared.simpson@oicr.on.ca

**Comment by stefanucci-luca** [comment]
Hi Jared,

I've just sent you an email. It is a quite general one, describing what I've done and all the commands, but if you need to visualise any file in detail, please just let me know. 

Best,
Luca

**Comment by jts** [comment]
This was resolved offline
