### ISSUE TITLE
PolyA length output 

### ISSUE THREAD

**Issue by jchang97** [jts/nanopolish#757]
Hi there, 
 
Thank you for this amazing tool!

I have generated a tsv file successfully using the polya function, but the lengths seems to be mostly non-discrete. 

Further to this, I can see some lengths which are between 0 and 1. 
![image](https://user-images.githubusercontent.com/41040156/78323827-bf2f3700-75be-11ea-982f-91058ea8d84b.png)

Could you please help with explaining these results? 

Thank you in advance! :)

**Comment by jts** [comment]
@paultsw can you help interpret this?

**Comment by paultsw** [comment]
Hi @jchang97, the lengths are the result of a regression model we built based on underlying segmentations of the read's picoampere current trace, so floating point values are expected.

That said, there shouldn't be many values so close to zero; could you estimate roughly what percentage of passing reads have a `polya_length` at or near zero nucleotides?

**Comment by jchang97** [comment]
Hi @paultsw ,

Thank you for the explanation! The rough percentage of passing reads <1 nts is 0.013 % .

Cheers

**Comment by paultsw** [comment]
Thanks for the update. I was a bit worried that the percentage would be overly high, but based on your count, I don't think there's any issue with 0.013%.

If you don't have any further questions, I'm going to close this issue.

**Comment by jchang97** [comment]
Thank you!
