### ISSUE TITLE
Probelm during installation : [Makefile:39: bseq.o] Error 1

### ISSUE THREAD

**Issue by sigau** [jts/nanopolish#758]
Hi !
First thank for the tool.

I try to install nanopolish with make I got this error :

make -C minimap2  libminimap2.a || exit 255
make[1] : on entre dans le répertoire « /home/gautier16/nanopolish/minimap2 »
/home/gautier16/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  bseq.c -o bseq.o
bseq.c:1:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
          ^~~~~~~~
compilation terminated.
make[1]: *** [Makefile:39: bseq.o] Error 1
make[1] : on quitte le répertoire « /home/gautier16/nanopolish/minimap2 »
make: *** [Makefile:108: minimap2/libminimap2.a] Error 255

Do you have an idea of what I can do ? 
Thanks a lot.

**Comment by jts** [comment]
Hi,

You need to have the `zlib` library installed.

Jared

**Comment by sigau** [comment]
Hi, 
thanks for your quick respond but after verification the zlib library is already install on the computer ...

**Comment by Shians** [comment]
It looks like you're trying to install minimap2 in a conda environment. I don't know why but I've had issues where conda fails to use the zlib on the system. Try to deactivate conda and install.

**Comment by jts** [comment]
Hi @sigau,

Is this still an issue or did @Shians' comment resolve it?

Jared
