### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by suyanan** [jts/nanopolish#759]
hi,
my data is nanopore data with single-fast5 files, so i also use the old version(nanopolish v0.10.1).
at the index step, the command detail is below,
`
nanopolish index -d fast5 -s demo.summary.txt demo.fastq.gz
`
the fast5 directory is the single-fast5 path, there occurs one error:
`terminate called after throwing an instance of 'std::bad_alloc'
what():  std::bad_alloc
Aborted
`
is there methods to solve it ?
thanks a lot.

**Comment by jts** [comment]
Hi,

Sorry for the slow response. I suggest you use ONT's tools to convert your single fast5 to multi and use the most recent version.

Jared
