### ISSUE TITLE
[Question] Can the fast5 files be compressed?

### ISSUE THREAD

**Issue by jolespin** [jts/nanopolish#760]
I'm copying over my `fast5` files and they are absolutely gigantic [>3TB easily].  Does `nanopolish` handle `gzip` or `bz2` compressed `fast5` files?

**Comment by jts** [comment]
Fast5s are already compressed so unfortunately that won’t help (and nanopolish won’t be able to use them)

Jared

**Comment by jolespin** [comment]
Good to know.  I suspected that but when I saw a 111GB fast5 I thought there me an additional layer of compression that could be used. 

Last question, does nanopolish look recursively in a directory for fast5 files? 

For example, if you have a directory with this structure: 

```
fast5
|_____|sample_A
|________________|file1.fast5
|________________|file2.fast5
|_____|sample_B
|________________|file1.fast5
```

Can you give `nanopolish index` the parent `fast5` directory instead of `fast5/sample_A`?

**Comment by jts** [comment]
Yes that will work.
