### ISSUE TITLE
RNA modification_might be redundant with closed #721

### ISSUE THREAD

**Issue by LeilyR** [jts/nanopolish#762]
Hi, 
Would you recommend using `nanopolish eventalign` with a transcriptome reference to call the RNA modification for direct RNA data?

**Comment by jts** [comment]
`nanopolish eventalign` works with direct RNA data but doesn't have a built-in RNA modification caller. You'll have to use something like nanocompore

**Comment by LeilyR** [comment]
thanks a lot for the respond. I was hesitating to use nanocompafre because I didn't have ctrl vs. condition to compare.
