### ISSUE TITLE
kmer model for PromethION?

### ISSUE THREAD

**Issue by joshidhaivat** [jts/nanopolish#764]
Hi Jared,

Is there a different kmer model for the PromethION technology or is it the same kmer model as that for minION.

Thanks,
Dhaivat

**Comment by jts** [comment]
No, we use the same model for both. It may be desirable to make one but I haven’t had the time.

**Comment by joshidhaivat** [comment]
Thanks! Can you also let me know or point me to some reference of how you generate the kmer model?

**Comment by jts** [comment]
It’s not well documented but the new method is called ‘nanopolish train’ in the r10 branch. I’ll try to write a description for it when I find a bit of time.

**Comment by joshidhaivat** [comment]
Thank you!
