### ISSUE TITLE
R9.4 model data

### ISSUE THREAD

**Issue by vahidAK** [jts/nanopolish#765]
Hi @jts ,
Sorry, but I had another question.
I wanted to know that you trained model for R9.4 on new data? Because your paper mentioned you sequenced samples by R9 and R7.3.
I want to know if you sequenced new data on R9.4, is the data available somewhere?

Many thanks,
Vahid.

**Comment by jts** [comment]
I assume you're asking about the methylation models - yes, we trained on R9.4 data that was prepared similarly to the R7.3/R9 data (E.coli gDNA that was PCR amplified then treated with M.SssI)
