### ISSUE TITLE
A vbz compression warning message

### ISSUE THREAD

**Issue by mmiladi** [jts/nanopolish#766]
Hi Jared,

Nanopolish returns empty tsv (header-only) at the eventalign step on a set of fast5 files that are vbz compressed. It would be nice if there be away to check the fast5 status and notify the users once the signals are blank or cannot be decompressed.

Best,
Milad
PS: Problem got resolved after finding out the fast5 files are compressed and following https://github.com/jts/nanopolish/issues/725 & https://github.com/nanoporetech/vbz_compression/issues/5.

**Comment by jts** [comment]
Yes, I need to properly support this, or at least emit a warning. I'm not going to have time right now but I'll leave this issue open as a reminder.

**Comment by jts** [comment]
Fixed by @sabiqali
