### ISSUE TITLE
python3 failed to run the program

### ISSUE THREAD

**Issue by maculatus** [jts/nanopolish#77]
Hello,

I tried python but the Bio module is not available. Python3 failed with a syntax error. Do I need to purge python3 and reinstall python? can I used virtualenv to install python and reinstall bioperl and run from there?

>python3 ~/programs/nanopolish/scripts/nanopolish_makerange.py draft_genome.fasta | parallel --results nanopolish.results -P 4 \ ~/programs/nanopolish variants --consensus polished.{1}.fa -w {1} -r raw.reads.np.fasta -b reads_to_draft.sorted.bam -g draft_genome.fasta -e reads.eventalign.sorted.bam -t 10 -min-candidate-frequency 0.1 --models nanopolish_models.fofn 
  File "~/programs/nanopolish/scripts/nanopolish_makerange.py", line 14
    print "%s:%d-%d" % (name, n, length - 1)
                   ^
SyntaxError: invalid syntax

**Comment by jts** [comment]
Hi,

Yes `nanopolish_makerange.py` is a python2 script so you will need to use `python` to run it. You should not need to purge `python3` as they can co-exist on your system. You should be able to use virtualenv to install it and the biopython dependency.

Jared

**Comment by maculatus** [comment]
Thanks! I installed biopthon in the env environment using pip. I also changed in samtools the function -f - to -o as detailed in previous documents. It is is running now.

Gustavo
