### ISSUE TITLE
bad fast5 with nanopolish v.0.11.3

### ISSUE THREAD

**Issue by IMSS-DMS** [jts/nanopolish#771]
Before indexing, I got the warning: 
warning: detected invalid summary file entries for 985627 of 985627 fast5 files
These files will be indexed without using the summary file, which is slow.

After indexing, I got the following output:
[readdb] num reads: 355204, num reads with path to fast5: 322553

Then when I run the command:
nanopolish_makerange.py CEGA1_63.6x_assembly.fasta | parallel --results nanopolish_CEGA1.results -P 3 nanopolish variants --consensus -o CEGA1.polished.{1}.vcf -w {1} -r CEGA1_nanoporeReads_trimmedFiltered.fasta -b CEGA1_nanoporeAssembly_nanopolishMapping.sorted.bam -g CEGA1_63.6x_assembly.fasta -t 4 --min-candidate-frequency 0.1

I get output that looks like this:
[post-run summary] total reads: 505, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 19, bad fast5: 340
[post-run summary] total reads: 534, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 21, bad fast5: 360
etc.

I'm not sure why I'm getting bad fast5's, presumably due to some reads not having the correct path. Would It be wrong to proceed as is?

**Comment by jts** [comment]
Can you try with the latest version?

**Comment by IMSS-DMS** [comment]
I ran the index command with the latest version (0.13.2). It didn't give me the index warning, but it did output:
[readdb] num reads: 48635, num reads with path to fast5: 15984

**Comment by IMSS-DMS** [comment]
So the num reads is now correct (matches the read number from Nanoplot after filtering).

**Comment by jts** [comment]
Ok - for some reason the paths to the fast5 files aren't right for about half the reads. Do they have entries in the .readdb file (it is a simple map from read name to fast5 path)?

**Comment by IMSS-DMS** [comment]
Upon inspecting the .readdb file, it appears that lots of reads do not have a path. I am using fast5 files that are in a "pass" folder, could it mean that I'm only using a subset of the fast5 files to being with?

**Comment by jts** [comment]
Yes, I think that is a possible explanation.

Jared
