### ISSUE TITLE
How to estimate memory request with `nanopolish call-methylation`? 

### ISSUE THREAD

**Issue by jolespin** [jts/nanopolish#773]
I have 108 Nanopore samples with a range of file sizes plotted below (both gzipped fastq and fast5).  My reference genome is `Rattus_norvegicus.Rnor_6.0` with is made up of `955 scaffolds` totaling `2870184193 bases`.  I've been having some memory issues and I'm wondering how I can allocate the proper amount of resources for accomplishing this.  

Could the memory errors be related to RAM required to load in the genome, fastq, or fast5 into memory?  I do not believe it is a physical space issue.

This is the command I'm running: 

```
nanopolish call-methylation -t 8 -r ont.fastq -g Rattus_norvegicus.Rnor_6.0.dna_rm.toplevel.fa -q cpg --bam sorted.bam > methylation_calls.cpg.tsv
```

Here's my version: 
```
(nanopolish_env) -bash-4.1$ nanopolish --version
nanopolish version 0.13.1
Written by Jared Simpson.

Copyright 2015-2017 Ontario Institute for Cancer Research
```

You mentioned: 

> This command will polish the entire genome in one step, and use a huge amount of memory. Our recommendation is to polish the genome in 50kbp segments, as described here:
> 
> https://github.com/jts/nanopolish#computing-a-new-consensus-sequence-for-a-draft-assembly
https://github.com/jts/nanopolish/issues/500

Would this be a situation where I need to split my genome into 50kbp fragments? 

Here's the file sizes:
![image](https://user-images.githubusercontent.com/9061708/81133021-38df7b00-8f05-11ea-8fb5-02d4ce02af46.png)

**Comment by jts** [comment]
Hi,

Please try 0.13.2, I fixed a memory issue that caused excessive memory use for `call-methylation` (and other programs).

**Comment by jolespin** [comment]
I'll try that tonight.  Do you think it would be overkill to request the fast5 size for the amount of resources on sungrid (i.e. qsub)? For example, if the fast5 directory was 100GB I would run `-l memory=100G` or is this irrelevant?

**Comment by jts** [comment]
Yes, I think that would be excessive. `call-methylation` processes batches of ~1000 reads at once, then frees the memory before processing the next batch. The memory usage is typically determined by the reference genome size and the `.readdb` file. I find ~20-30G is usually sufficient for a mammalian genome.

**Comment by jolespin** [comment]
Wow, it seems like 0.13.2 is much more efficient.  I've also kept all of my fast5 and fastq reads in a separate directory with more space so I think this combination is working wonders.  I currently have an 11GB fastq (uncompressed) running right now so hopefully there's no memory issues but so far so good. 

I had one last question, for call-methylation does number of threads decrease the amount of time linearly?  Basically, I'm wondering if it would be better for me to run 108 samples at 16 threads in batches of 8 or at 2 threads in batches of 64.

**Comment by jts** [comment]
No, there are diminishing returns for more threads. I'd try 32 jobs with 4 threads each.

Jared
