### ISSUE TITLE
fail to open the FASTA file 

### ISSUE THREAD

**Issue by sachingadakh** [jts/nanopolish#775]
sachin@ws-grot:~/nanopolish$ ./nanopolish variants -t 8 -o /media/sachin/Sachin\ Gadakh/covid/SP1_nanopo.vcf -r /media/sachin/Sachin\ Gadakh/covid/SP1-mapped.fasta -b /media/sachin/Sachin\ Gadakh/covid/SP1-mapped.sorted.bam -g /media/sachin/Sachin\ Gadakh/covid/sars-cov2.fasta -p 2

[fai_load] build FASTA index.
[fai_build] fail to open the FASTA file /media/sachin/Sachin
Segmentation fault (core dumped)

I already have indexed using nanopolish index, read fasta file, genome fasta file , bam file even though I don't understand why I am getting this error, in spite of providing correct path to access FASTA file.
Thank you

**Comment by jts** [comment]
try quoting all the paths that have spaces in them

**Comment by sachingadakh** [comment]
Hello,
 The error was consistent, though. 
Anyway, I transferred data to another location. But with the following command,  the command is still processing and the output is not getting printed in a file, given it has been 1 hour. The size of the reads file is just 778 mb. I checked htop, CPU consumption is lesser than 40 %. With 8 threads, this should not have taken this much time. Can you guide me what is going wrong?
Thank you

sachin@ws-grot:/mnt/data1/sachin/covid$ /home/sachin/nanopolish/./nanopolish variants -t 8 -o SP1.vcf -r SP1-mapped.fasta -b SP1-mapped.sorted.bam -g sars-cov2.fasta -p 2

**Comment by jts** [comment]
Hi,

You are analyzing coronavirus sequencing data but provided the `-p 2` (ploidy 2) option, which is inappropriate for viruses. Also I suspect your coverage is extremely high and should be downsampled. Please use the ARTIC bioinformatics SOP to analyze your data:

https://artic.network/ncov-2019/ncov2019-bioinformatics-sop.html

Jared
