### ISSUE TITLE
multithread option but still only using one thread

### ISSUE THREAD

**Issue by callumparr** [jts/nanopolish#778]
Thank you for lovely tools. I am currently using polyA estimation part of nanopolish. I have tried this alone (v0.13.2) and works well, as well as part of pipelines like these:

https://github.com/biocorecrg/master_of_pores (unsure the version as is within a container)

https://github.com/nanoporetech/pipeline-polya-ng conda install with 0.13.2 version

In each case, it seems despite telling it to use more than one thread it is still only using one thread. 
I manually installed nanopolish with git clone and make and I check the makefile has the enable multithread thingy. 

In the case of master of pores nextflow and pipeline-polya-ng they take care of the installation but I assume its similar story. 

This based only seeing one process running in `top` and with the following shell line:

`cat /proc/$(pgrep nanopolish)/status | grep -i Threads`

Sorry if I misunderstood perhaps this not necessary if the inputs are not split into separate processes.

**Comment by jts** [comment]
Hi @callumparr,

There is a known issue with the conda version where multi-threading is disabled. Do you see the same behaviour in the version you manually installed from github?

Jared

**Comment by callumparr** [comment]
When running manually installed nanopolish 

```
❯ ./nanopolish/nanopolish polya --threads=12 --reads=pipeline-polya-ng/Workspaces/pipeline-polya-ng/input/reads.fastq --bam=pipeline-polya-ng/Workspaces/pipeline-polya-ng/alignment/aligned_reads_sorted.bam --genome=transcriptome_tutorial/Analysis/ReferenceData/Mus_musculus.GRCm38.cdna.all.fa > polyA.tsv
```

```
❯ cat /proc/$(pgrep nanopolish)/status | grep -i Threads

Threads:	12
```

Seems in this case it runs as expected using multiple threads. Do all steps use 

To confirm 

```
./pipeline-polya-ng/Workspaces/pipeline-polya-ng/.snakemake/conda/ffe8ea22/bin/nanopolish polya --threads=12 --reads=pipeline-polya-ng/Workspaces/pipeline-polya-ng/input/reads.fastq --bam=pipeline-polya-ng/Workspaces/pipeline-polya-ng/alignment/aligned_reads_sorted.bam --genome=transcriptome_tutorial/Analysis/ReferenceData/Mus_musculus.GRCm38.cdna.all.fa > polyA.tsv
```

gives this output for thread number 

```
❯ cat /proc/$(pgrep nanopolish)/status | grep -i Threads
Threads:	1
```

It takes about 20hr to run through one direct RNA seq library from minION flow cell so its not the end of the world and I could just revert to using nanopolish alone without the pipeline

**Comment by jts** [comment]
I'll try to look into the conda issue soon
