### ISSUE TITLE
Memory Allocation Issues with Nanopolish Variants Consensus

### ISSUE THREAD

**Issue by osteidl** [jts/nanopolish#782]
Hello,

I'm running the nanopolish variants consensus parallel code on a CPU: 8, Mem: 48 GB, Disk: 320 GB root - sized instance. Below is the exact code I'm using.

`python3 /home/osteidl/nanopolish/scripts/nanopolish_makerange.py /scratch/barcode01/outputs/barcode01.contigs.fasta | /home/osteidl/parallel-20200422/src/parallel --results nanopolish.results -P 3 \ /home/osteidl/nanopolish/nanopolish variants --consensus -o barcode01.polished.{1}.vcf -w {1} -r barcode01.fasta -b barcode01.reads.sorted.bam -g /scratch/barcode01/outputs/barcode01.contigs.fasta -t 4 --min-candidate-frequency 0.1`

I continue to get the error "Memory allocation limit reached at adaptive_banded_simple_event_align" and then the polishing appears to continue to the point that I can combine the vcf files with vcf2fasta, but I don't think they are actually polished correctly. I have attempted decreasing the threads allocated to each parallel run, but I continue to get this error.

I have isolated the contig of interest to decrease the size of the draft genome to only one contig that is about 110kb long. The fast5 directory index is roughly 30GB in size, and all previous steps as described in the polishing a genome assembly pipeline provided on the Nanopolish website are successful!

When monitoring the CPU usage, the screen I am running this on reaches 100% within 30 minutes and then the program is terminated. Is there anything I can do, short of trying to run this consensus step on a different-sized instance? And how can I estimate how much memory usage is required, knowing that I have to run this step on 6 more genomes of similar length?

Please let me know if you need other information, and thank you in advance for your help!

**Comment by jts** [comment]
Hi,

A few questions:

1) What version of nanopolish are you using?
2) How big is the genome your a polishing?
3) If you use fewer processes `-P 1` do you get the same error?

Jared

**Comment by osteidl** [comment]
Hi Jared,

Thank you for the speedy response! 

1. I am using the most recent version of Nanopolish, which I believe is 0.13.2. I installed it about a week ago.
2. The genome I am polishing is a novel phage genome. The contig output from Canu is 121,733bp long, and we estimated that it would be between 90-120kb, so this would be a reasonable size for the final assembly.
3. I believe I misunderstood the "-P 1" section of the code to mean how many sections of 50kb you would need to make up the whole assembly. When I ran this previously using a -P 2, it seemed to work more effectively. What exactly does the processes portion of the code mean? Apologies for the misunderstanding!

- Olivia

**Comment by jts** [comment]
Hi Olivia,

`-P` is the number of processes to run at the same time - with more processes it will use more memory. The end result will be the same, no matter what you choose for `-P`.

Since the genome is very small and you have a lot of data, you might want to downsample by reducing coverage to 200-500X. This will use a lot less memory.

I hope that helps,
Jared

**Comment by osteidl** [comment]
Hi again, Jared -

The contig I am using as a reference corresponds to 82.41x coverage. Is the variants command accessing the fast5 files - and if so, is there a way to limit the amount of reads it is looking at?

I am currently rerunning the same command at -P 1 as you suggested, and will update with the result. Thank you!

**Comment by jts** [comment]
Hm, maybe I misunderstood. Above you said the fast5 index is 30GB in size - did you mean the `.readdb` file, or the total size of the fast5s themselves?

Jared

**Comment by osteidl** [comment]
The total size of the fast5s themselves is 35GB. The size of the .readdb file is only 8.4MB!

**Comment by jts** [comment]
Ok thanks. So is your 120kb phage, the entire assembly, or only a portion of it? 82x coverage is lower than I'd expect for such a small genome

**Comment by osteidl** [comment]
I agree. I had so much data from Nanopore that Canu actually defaulted to ~40x coverage, and I adjusted some of the settings to get it to finally be 82x and take into account more of the reads. Do you think that is causing an issue for the memory of polishing?

I just reran it with -P 1 and -t 4, and it hit 99% memory usage at around 30 minutes again, so my instance terminated nanopolish, but it appears to still be running again. Should I try -t 2 or t- 1? I just thought that because I have 8 CPU, I would safely be able to allocate 4 threads to each!

**Comment by jts** [comment]
`-t` controls how many threads each process will use but it doesn't change the memory usage (it only parallelizes the computation, it doesn't load more data).

How many reads are aligned to this contig in `barcode01.reads.sorted.bam`?

**Comment by osteidl** [comment]
Good to know - thank you! 

This is the output from the run of -P 1 and -t 4. I know in a previous post you said to ignore those max-haplotype errors, but I figured the more information I can provide, the better.
```
Memory allocation failed at adaptive_banded_simple_event_align
Memory allocation failed at adaptive_banded_simple_event_align
Number of variants in span (10) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (37) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (19) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (13) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (11) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (18) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (33) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (14) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (10) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (11) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (12) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (11) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (15) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (11) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
[post-run summary] total reads: 8754, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 264, bad fast5: 0
```
According to `samtools view -c -F 260 barcode01.reads.sorted.bam`, there are 86128 reads aligned. I used only that contig to generate a reference, and therefore to generate the sorted bam file.

**Comment by osteidl** [comment]
Follow up: I tried vcf2fasta on the polished contigs, and this was the output.

`[vcf2fasta] rewrote contig tig00000001 with 15 subs, 36 ins, 4 dels (0 skipped)`

Because of the memory allocation error however, should I not trust this polished assembly? Thank you so much for all of your help!

**Comment by jts** [comment]
I'm not sure all these values make sense to me - 86000 reads for a 120,000bp genome should be >1000X coverage. The "variants in span" warnings usually mean the initial assembly quality is low, or there is a mapping error. Maybe try a quick round of racon polishing, then try downsampling to 500X?

**Comment by osteidl** [comment]
I agree. Something seems off! I will try that. Thank you for the suggestion!

**Comment by osteidl** [comment]
Hi Jared - Following up (and thank you again for all of your help), I realized that I did my mapping with minimap2 instead of bwa. Do you think this could also have affected something?

I am going to try Racon polishing today. But do you think I should downsample the fastq files first, and then do Racon polishing? I seem to have way more data than I need, and I think that is what is messing things up downstream in the pipeline.

**Comment by jts** [comment]
Minimap2 is preferred for nanopore data. Yes, I suggest downsampling before racon too.

**Comment by jts** [comment]
I'm going to close this now, feel free to re-open (or open a new issue) if you have any other problems.
