### ISSUE TITLE
How to call nanopolish methyltrain

### ISSUE THREAD

**Issue by snajder-r** [jts/nanopolish#784]
Hi!

Perhaps I wasn't looking hard enough, but I was unable to find documentation on methyltrain, so I tried to understand it from the source code.

One thing I don't understand is: How should the training data be prepared? I am trying to train an ACGMT alphabet, but it looks like it fails to find any of the events that contain an "M" base. How do I tell nanopolish which bases are methylated and which aren't? Does it need the "M" base in the fastq file, or in the bam file, or in the reference, or in all?

Thanks a lot!

Rene

**Comment by jts** [comment]
Sorry, `methyltrain` still isn't very well documented. You might want to look at `nanopolish train` in the r10 branch, which is somewhat simpler to use. Its still in pre-release though.

To answer your question, the `M` bases need to be in the reference genome.

Jared
