### ISSUE TITLE
error: faidx could not get contig length for contig 22

### ISSUE THREAD

**Issue by ashinandjay** [jts/nanopolish#785]
Hello,

I got a following error:
`error: faidx could not get contig length for contig 22`

I am running this command:
`python3 nanopolish_makerange.py paternal_CYP2D6.fa | parallel --results nanopolish.results -P 8 nanopolish variants --consensus -o polished.{1}.vcf -w {1} -r /nanopore/reference_sequence/CYP2D6_refseq.fasta -b aln_paternal_CYP2D6_sorted.bam -g paternal_CYP2D6.fa -t 4 --min-candidate-frequency 0.1 -w "22:42512501-42536812"`

I am not sure why this could not get contig length.

**Comment by jts** [comment]
There are a few possible issues here:

1. You passed paternal_CYP2D6.fa into makerange, but then provided the window option anyway (`-w`). makerange will output a list of windows to run over. You should tell parallel to fill in the window with `-w {1}` (see the README.md) for the full command
2. the `-r` option doesn't match what you passed to makerange (`CYP2D6_refseq.fasta` vs `paternal_CYP2D6.fa`).

Jared

**Comment by ashinandjay** [comment]
Thanks. I figured out the issue by myself. The reference sequence should not be one line sequence. It should break to multiple lines with 100 base width for each line. Then it can read the length.
