### ISSUE TITLE
low number of indexed reads using nanopolish index.

### ISSUE THREAD

**Issue by upasana3** [jts/nanopolish#786]
Hi,

I am trying to index the fastq reads, however only 169 of  722128 fastq reads get linked to corresponding fast5 files. I have not been able to figure out how to fix this issue.

[readdb] indexing /homes/upasanad/project/ONT_assemblies/23473_1/23473/20191203_2231_MN25719_FAL18427_197ca5a1/fast5
[readdb] num reads: 722128, num reads with path to fast5: 169

Any suggestions as to how to fix this problem would be helpful. Thank you!

**Comment by jts** [comment]
Hi,

Can you please paste the full command that you ran?

Jared

**Comment by upasana3** [comment]
This is the command i used:

f5=/homes/upasanad/project/ONT_assemblies/23473_1/23473/20191203_2231_MN25719_FAL18427_197ca5a1/fast5
fq=/homes/upasanad/project/nanopolish/23473/merged23473.fastq
np_dir=/homes/liu3zhen/software/nanopolish/nanopolish_0.11.0
seq_sum=/homes/upasanad/project/ONT_assemblies/23473_1/23473/20191203_2231_MN25719_FAL18427_197ca5a1/fastq/sequencing_summary.txt
$np_dir/nanopolish index -d $f5 -s $seq_sum $fq

I have also worked without using the sequencing summary file. The dose is as follows:
 
f5=/homes/upasanad/project/ONT_assemblies/23473_1/23473/20191203_2231_MN25719_FAL18427_197ca5a1/fast5
fq=/homes/upasanad/project/nanopolish/23473/merged23473.fastq
np_dir=/homes/liu3zhen/software/nanopolish/nanopolish_0.11.0
$np_dir/nanopolish index -d $f5 $fq

I get about 25000 reads indexed without sequencing summary file. I was successfully able to index all the reads without using the sequencing summary file in few other cases. None of the options are working in this case.

Please let me know if you need more information.

**Comment by jts** [comment]
Can you please try with the latest version? 0.11.0 is rather old now

**Comment by upasana3** [comment]
I was able to index all reads for some other genome with version 0.11.0 recently (couple of days back). Is there anything else i could try before switching to another version? Can it be related to the fast5 or fastq files and not to the code and nanopolish version?

**Comment by upasana3** [comment]
I tried with 0.11.3 which we had installed previously and it worked. Thank you for your help.

________________________________

**Comment by jts** [comment]
Glad to hear it, thanks for reporting back.
