### ISSUE TITLE
src/hmm/nanopolish_profile_hmm.cpp:36: Assertion error when running nanopolish_makerange.py 

### ISSUE THREAD

**Issue by jimjimvalkema** [jts/nanopolish#787]
hello,
I get a error when trying to polish on the machine at my university when working on a data set of the deformed wing virus (RNA).

This the error when polishing on the universities machine: 
`nanopolish: src/hmm/nanopolish_profile_hmm.cpp:36: float profile_hmm_score_set(const std::vector<HMMInputSequence>&, const HMMInputData&, uint32_t): Assertion std::string(data.pore_model->pmalphabet->get_name()) == \"nucleotide\"' failed.`
And this is the commandline arguments i used (from the readme):  
`python3 /students/2019-2020/Thema11/minion_aj_jj/programs/nanopolish/scripts/nanopolish_makerange.py \ /students/2019-2020/Thema11/minion_js_jh/msa/consensus_sequence/world3_consensus.fasta \ | parallel --results nanopolish.results -P 80 /students/2019-2020/Thema11/minion_aj_jj/programs/nanopolish/nanopolish variants --consensus -o polished.{1}.vcf -w {1} -r \ temp_all_reads.fastq -b reads.sorted.bam -g \ /students/2019-2020/Thema11/minion_js_jh/msa/consensus_sequence/world3_consensus.fasta -t 80 --min-candidate-frequency 0.1`  

I also tried to build from it on my own machine (from repo with make) but then i get another error before i can try polishing. I also had problems assembling my own draft genome with canu so i used a reference genome instead to see if i can use nanopolish.

I have made very basic documentation of what i have tried in order to use nanopolish for my minor project. And i might be able to provide the data used if needed. but here is the document: [https://bitbucket.org/jjvalkema/thema11_savethebees/src/master/nanopolish_journal.md](url)

I don't have good options to use docker right now but i might look into that.
But any suggestion to help would be appreciated!

**Comment by jts** [comment]
Hi,

Have you tried using the version from conda?

Jared

**Comment by jts** [comment]
I just looked at your log from bitbucket and noticed this comment:

```
(the one without u nucleotide)
```

I suspect the genome you're trying to polish continues `U` nucleotides, which will confuse nanopolish. If you change these to `T` things might go better.

Jared

**Comment by jts** [comment]
Closing for now, feel free to re-open if this is still an issue
