### ISSUE TITLE
Issues during package installation and indexing

### ISSUE THREAD

**Issue by swethak1989** [jts/nanopolish#788]
Hi,
I am currently having trouble with Nanopolish installation, after trying to update it due to errors during indexing. 
Background: I'm using Ubuntu on my Windows 10 machine. Until 06/05, my indexing using Nanopolish indexing wouldn't work completely- error being that fast5 files could not be found and so no readdb file was created
I checked the nanopolish version - 0.9.0.
So I tried to update in multiple ways - conda, sudo apt upgrade and GitHub repo.I've tried installing nanopolish through conda and when I try to call it I get this error:
nanopolish: error while loading shared libraries: libhdf5.so.10: cannot open shared object file: No such file or directory 
I uninstalled that and then tried to install through github, however when I used the make command in the directory it went a bit mad.
make[1]: Entering directory '/Data/nanopolish/hdf5-1.8.14' Making all in src make[2]: Entering directory '/Data/nanopolish/hdf5-1.8.14/src' make all-am make[3]: Entering directory '/Data/nanopolish/hdf5-1.8.14/src' CC H5.lo In file included from H5.c:27:0: H5Eprivate.h:35:32: warning: anonymous variadic macros were introduced in C99 [-Wvariadic-macros] #define HERROR(maj_id, min_id, ...) H5E_printf_stack(NULL, __FILE__, FUNC, __LINE__, H5E_ERR_CLS_g, maj_id, min_id, __VA_ARGS__) ^~~ In file included from H5.c:27:0: H5Eprivate.h:41:33: warning: anonymous variadic macros were introduced in C99 [-Wvariadic-macros] #define HCOMMON_ERROR(maj, min, ...) \ ^~~ H5Eprivate.h:55:40: warning: anonymous variadic macros were introduced in C99 [-Wvariadic-macros] #define HDONE_ERROR(maj, min, ret_val, ...) { \ ^~~ H5Eprivate.h:67:40: warning: anonymous variadic macros were introduced in C99 [-Wvariadic-macros] #define HGOTO_ERROR(maj, min, ret_val, ...) { \ ^~~ In file included from H5.c:24:0: H5.c: In function 'H5_init_library': H5private.h:1539:14: warning: ISO C90 does not support '__func__' predefined identifier [-Wpedantic] #define FUNC __func__ ^ H5Eprivate.h:35:70: note: in expansion of macro 'FUNC' #define HERROR(maj_id, min_id, ...) H5E_printf_stack(NULL, __FILE__, FUNC, __LINE__, H5E_ERR_CLS_g, maj_id, min_id, __VA_ARGS__) ^~~~ H5Eprivate.h:42:4: note: in expansion of macro 'HERROR' HERROR(maj, min, __VA_ARGS__); \ ^~~~~~ H5Eprivate.h:68:4: note: in expansion of macro 'HCOMMON_ERROR' HCOMMON_ERROR(maj, min, __VA_ARGS__); \ ^~~~~~~~~~~~~ H5.c:181:9: note: in expansion of macro 'HGOTO_ERROR' HGOTO_ERROR(H5E_FUNC, H5E_CANTINIT, FAIL, "unable to initialize error interface") ^~~~~~~~~~~ H5private.h:1539:14: warning: ISO C90 does not support '__func__' predefined identifier [-Wpedantic] #define FUNC __func__ ^ H5Eprivate.h:35:70: note: in expansion of macro 'FUNC' #define HERROR(maj_id, min_id, ...) H5E_printf_stack(NULL, __FILE__, FUNC, __LINE__, H5E_ERR_CLS_g, maj_id, min_id, __VA_ARGS__) ^~~~ H5Eprivate.h:42:4: note: in expansion of macro 'HERROR' HERROR(maj, min, __VA_ARGS__); \ ^~~~~~ H5Eprivate.h:68:4: note: in expansion of macro 'HCOMMON_ERROR' HCOMMON_ERROR(maj, min, __VA_ARGS__); \ ^~~~~~~~~~~~~ H5.c:183:9: note: in expansion of macro 'HGOTO_ERROR' HGOTO_ERROR(H5E_FUNC, H5E_CANTINIT, FAIL, "unable to initialize property list interface") ^~~~~~~~~~~ H5private.h:1539:14: warning: ISO C90 does not support '__func__' predefined identifier [-Wpedantic] #define FUNC __func__ ^ H5Eprivate.h:35:70: note: in expansion of macro 'FUNC' #define HERROR(maj_id, min_id, ...) H5E_printf_stack(NULL, __FILE__, FUNC, __LINE__, H5E_ERR_CLS_g, maj_id, min_id, __VA_ARGS__) ^~~~ H5Eprivate.h:42:4: note: in expansion of macro 'HERROR' HERROR(maj, min, __VA_ARGS__); \ ^~~~~~ H5Eprivate.h:68:4: note: in expansion of macro 'HCOMMON_ERROR' HCOMMON_ERROR(maj, min, __VA_ARGS__); \ ^~~~~~~~~~~~~ H5.c:185:9: note: in expansion of macro 'HGOTO_ERROR' HGOTO_ERROR(H5E_FUNC, H5E_CANTINIT, FAIL, "unable to initialize datatype interface") ^~~~~~~~~~~ H5private.h:1539:14: warning: ISO C90 does not support '__func__' predefined identifier [-Wpedantic] #define FUNC __func__ ^ H5Eprivate.h:35:70: note: in expansion of macro 'FUNC' #define HERROR(maj_id, min_id, ...) H5E_printf_stack(NULL, __FILE__, FUNC, __LINE__, H5E_ERR_CLS_g, maj_id, min_id, __VA_ARGS__) ^~~~ H5Eprivate.h:42:4: note: in expansion of macro 'HERROR' HERROR(maj, min, __VA_ARGS__); \ ^~~~~~ H5Eprivate.h:68:4: note: in expansion of macro 'HCOMMON_ERROR' HCOMMON_ERROR(maj, min, __VA_ARGS__); \ ^~~~~~~~~~~~~ H5.c:187:9: note: in expansion of macro 'HGOTO_ERROR' HGOTO_ERROR(H5E_FUNC, H5E_CANTINIT, FAIL, "unable to initialize dataset interface") ^~~~~~~~~~~ H5private.h:1539:14: warning: ISO C90 does not support '__func__' predefined identifier [-Wpedantic] #define FUNC __func__ ^ H5Eprivate.h:35:70: note: in expansion of macro 'FUNC' #define HERROR(maj_id, min_id, ...) H5E_printf_stack(NULL, __FILE__, FUNC, __LINE__, H5E_ERR_CLS_g, maj_id, min_id, __VA_ARGS__) ^~~~ H5Eprivate.h:42:4: note: in expansion of macro 'HERROR' HERROR(maj, min, __VA_ARGS__); \ ^~~~~~ H5Eprivate.h:68:4: note: in expansion of macro 'HCOMMON_ERROR' HCOMMON_ERROR(maj, min, __VA_ARGS__); \ ^~~~~~~~~~~~~ H5.c:189:9: note: in expansion of macro 'HGOTO_ERROR' HGOTO_ERROR(H5E_FUNC, H5E_CANTINIT, FAIL, "unable to initialize metadata caching interface") ^~~~~~~~~~~ H5private.h:1539:14: warning: ISO C90 does not support '__func__' predefined identifier [-Wpedantic] #define FUNC __func__ ^ H5Eprivate.h:35:70: note: in expansion of macro 'FUNC' #define HERROR(maj_id, min_id, ...) H5E_printf_stack(NULL, __FILE__, FUNC, __LINE__, H5E_ERR_CLS_g, maj_id, min_id, __VA_ARGS__) ^~~~ H5Eprivate.h:42:4: note: in expansion of macro 'HERROR' HERROR(maj, min, __VA_ARGS__); \ ^~~~~~ H5Eprivate.h:68:4: note: in expansion of macro 'HCOMMON_ERROR' HCOMMON_ERROR(maj, min, __VA_ARGS__); \ ^~~~~~~~~~~~~ H5.c:191:9: note: in expansion of macro 'HGOTO_ERROR' HGOTO_ERROR(H5E_FUNC, H5E_CANTINIT, FAIL, "unable to initialize link interface") ^~~~~~~~~~~ . etc.

Please let me know how to go about fixing this! Thanks for the help!

**Comment by jts** [comment]
I've never tried to install on the linux subsystem for windows, so I'm not sure where to start. The error log you pasted is incomplete though, if you can upload the entire message as a text file I can take a look.

Jared

**Comment by swethak1989** [comment]
Hello Jared

Thank you for your reply![](url)

I've attached a text file of the entire code that I tried for installation! 
Please let me know what could have been the cause of the error.

Regards,

Swetha

[nanopolish_inst_error.txt](https://github.com/jts/nanopolish/files/4773841/nanopolish_inst_error.txt)

**Comment by swethak1989** [comment]
Hello Jared

Thank you for your reply!

I've attached a text file of the error log.

Please let me know as to what maybe causing the error.

Regards,

Swetha

[nanopolish_inst_error_v2.txt](https://github.com/jts/nanopolish/files/4773899/nanopolish_inst_error_v2.txt)

**Comment by swethak1989** [comment]
Hi

I let the code run, ran into further errors in zlib and fixed it based on your response to other issues on this repo.

The code seemed to have compiled at the end.

But when I tried to check the version (or run indexing later), it did not recognize the word 'nanopolish'. So I'm not sure what got compiled / if the package got installed.

Please find attached the log and help me understand further dependencies needed to be installed.

[nanopolish_inst_error_3.txt](https://github.com/jts/nanopolish/files/4802142/nanopolish_inst_error_3.txt)


Regards,

Swetha

**Comment by swethak1989** [comment]
Hi Jared

I fixed the problem and got my indexing to work!

Just in case it helps, I had to install few dependencies manually.

Thanks,

Swetha

**Comment by jts** [comment]
Great, thanks for letting me know.

**Comment by nicolo-tellini** [comment]
> Hi Jared
> 
> I fixed the problem and got my indexing to work!
> 
> Just in case it helps, I had to install few dependencies manually.
> 
> Thanks,
> 
> Swetha

Hi @swethak1989 ,

can you tell me please what are the dependencies to install?

best,

Nic

**Comment by jts** [comment]
Glad to hear it!
