### ISSUE TITLE
error: unsupported option '-fopenmp'

### ISSUE THREAD

**Issue by OscarChou211** [jts/nanopolish#789]
"error: unsupported option '-fopenmp'" 

When I try to install the package on the MacOS according to the guidance, it showed the following error. 

c++ -g -O3 -std=c++11 -fopenmp -fsigned-char -D_FILE_OFFSET_BITS=64  -I./include -I./htslib -I./minimap2 -I./fast5/include -I./src -I./src/hmm -I./src/thirdparty -I./src/thirdparty/scrappie -I./src/common -I./src/alignment -I./src/pore_model -I./src/io -I./eigen/ -MM  src/nanopolish_call_methylation.cpp src/nanopolish_call_variants.cpp src/nanopolish_extract.cpp src/nanopolish_getmodel.cpp src/nanopolish_haplotype.cpp src/nanopolish_index.cpp src/nanopolish_methyltrain.cpp src/nanopolish_phase_reads.cpp src/nanopolish_polya_estimator.cpp src/nanopolish_raw_loader.cpp src/nanopolish_read_db.cpp src/nanopolish_scorereads.cpp src/nanopolish_squiggle_read.cpp src/nanopolish_train_poremodel_from_basecalls.cpp src/nanopolish_variant_db.cpp src/nanopolish_vcf2fasta.cpp src/training_core.cpp  src/hmm/nanopolish_duration_model.cpp src/hmm/nanopolish_profile_hmm.cpp src/hmm/nanopolish_profile_hmm_r7.cpp src/hmm/nanopolish_profile_hmm_r9.cpp src/hmm/nanopolish_transition_parameters.cpp      src/common/fs_support.cpp src/common/logsum.cpp src/common/nanopolish_alphabet.cpp src/common/nanopolish_bam_processor.cpp src/common/nanopolish_bam_utils.cpp src/common/nanopolish_common.cpp src/common/nanopolish_iupac.cpp src/common/nanopolish_klcs.cpp src/common/nanopolish_variant.cpp  src/alignment/nanopolish_alignment_db.cpp src/alignment/nanopolish_anchor.cpp src/alignment/nanopolish_eventalign.cpp  src/pore_model/nanopolish_model_names.cpp src/pore_model/nanopolish_pore_model_set.cpp src/pore_model/nanopolish_poremodel.cpp  src/io/nanopolish_fast5_io.cpp src/io/nanopolish_fast5_loader.cpp src/io/nanopolish_fast5_processor.cpp      src/thirdparty/fet.c src/thirdparty/stdaln.c  src/thirdparty/scrappie/event_detection.c src/thirdparty/scrappie/scrappie_common.c         > ./.depend;
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
make: *** [.depend] Error 1
 
I wonder what should I do with that? I am sorry since I am new to bioinformatics without any prior knowledge in computing. 

Thank you very much for helping1

**Comment by Shians** [comment]
See #279. This is usually a problem on the Mac, because the compiler that comes with it doesn't have OpenMP enabled. You can use https://brew.sh (Homebrew) to install gcc.

`brew install gcc`

Then you can find all the versions of GCC you've installed

`brew list gcc`

At the time of this comment this should be `gcc-9`. So you need to compile with

`make CXX=g++-9 CC=gcc-9`

**Comment by OscarChou211** [comment]
I see. Thank you very much for helping! The problem is solved!
