### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by REDitter** [jts/nanopolish#790]
Hi I am trying to install nanopolish and had some warnings and errors get thrown, ultimately ending in: compilation terminated.

I was installing using:
git clone --recursive https://github.com/jts/nanopolish.git
cd nanopolish
make

I have attached two files, one with only the fatal errors and the other is the complete install log.

[install_fatal_log.txt](https://github.com/jts/nanopolish/files/4760947/install_fatal_log.txt)

[install_complete_log.txt](https://github.com/jts/nanopolish/files/4760946/install_complete_log.txt)

**Comment by REDitter** [comment]
Hi Jared,

There is a htslib directory, but it is empty.

Robb

> Hi,
> 
> The error message indicates that the `htslib` submodule is missing, but it should be there as you provided the `--recursive` flag. Do you have an `htslib` directory?
> 
> Jared

**Comment by jts** [comment]
That's odd, I suggest deleting the directory and re-cloning. That directory should contained a cloned version of the htslib submodule.

Jared

**Comment by REDitter** [comment]
Hi Jared,

I deleted the directory and re-cloned it from (https://github.com/jts/nanopolish.git).
The htslib is still empty (see attached image).
![Screenshot 2020-06-12 13 36 50](https://user-images.githubusercontent.com/15523142/84531217-3e717300-acb2-11ea-991a-9a99557b3db9.png)
Would it work
![Screenshot 2020-06-12 13 36 50](https://user-images.githubusercontent.com/15523142/84531217-3e717300-acb2-11ea-991a-9a99557b3db9.png)
 for me to clone the htslib directory (https://github.com/samtools/htslib.git) into the folder?

**Comment by jts** [comment]
It would probably not work since nanopolish uses a particular version of htslib - you could clone into that directory but you'd then have to check out the specific version.

Are the other submodule directories (minimap2, fast5) also empty?

**Comment by REDitter** [comment]
Hi Jared,

I just checked and all of the other submodules have something in them.


*Ph.D. Candidate*


*Bracken-Grissom Lab (MSB-330) Florida International UniversityBiscayne Bay
Campus*
*Crustomics: Crustacean Genomics and Systematics Lab*
*brackengrissomlab.com
<https://urldefense.proofpoint.com/v2/url?u=http-3A__heatherbracken.wix.com_brackengrissomlab&d=AwMFaQ&c=1QsCMERiq7JOmEnKpsSyjg&r=rWAH25-c2Us3UVBK4CF-kw&m=s2M-Th-DF1xlXhMmvH18O_6AlDFIEeuJkwljCvhYRN0&s=kvqKaPnXopv0j4Gn_8cNIiHvUz6Q6M80MKkvdXSon9w&e=>*

**Comment by jts** [comment]
Very strange, I just tried on a fresh clone and the htslib directory is populated. Do you get a similar output to `git clone --recursive` as this?

```
Cloning into 'nanopolish'...
remote: Enumerating objects: 8139, done.
remote: Total 8139 (delta 0), reused 0 (delta 0), pack-reused 8139
Receiving objects: 100% (8139/8139), 56.12 MiB | 16.07 MiB/s, done.
Resolving deltas: 100% (5933/5933), done.
Submodule 'fast5' (https://github.com/mateidavid/fast5) registered for path 'fast5'
Submodule 'htslib' (https://github.com/samtools/htslib) registered for path 'htslib'
Submodule 'minimap2' (https://github.com/lh3/minimap2) registered for path 'minimap2'
Cloning into '/home/jsimpson/scratch/nanopolish/fast5'...
remote: Enumerating objects: 1313, done.        
remote: Total 1313 (delta 0), reused 0 (delta 0), pack-reused 1313        
Receiving objects: 100% (1313/1313), 473.08 KiB | 3.56 MiB/s, done.
Resolving deltas: 100% (833/833), done.
Cloning into '/home/jsimpson/scratch/nanopolish/htslib'...
remote: Enumerating objects: 70, done.        
remote: Counting objects: 100% (70/70), done.        
remote: Compressing objects: 100% (48/48), done.        
remote: Total 13324 (delta 35), reused 38 (delta 22), pack-reused 13254        
Receiving objects: 100% (13324/13324), 9.89 MiB | 17.20 MiB/s, done.
Resolving deltas: 100% (9582/9582), done.
Cloning into '/home/jsimpson/scratch/nanopolish/minimap2'...
remote: Enumerating objects: 72, done.        
remote: Counting objects: 100% (72/72), done.        
remote: Compressing objects: 100% (43/43), done.        
remote: Total 4479 (delta 36), reused 50 (delta 28), pack-reused 4407        
Receiving objects: 100% (4479/4479), 1.39 MiB | 7.61 MiB/s, done.
Resolving deltas: 100% (3214/3214), done.
Submodule path 'fast5': checked out '18d6e346cadb9990ff8287e54447f90e76dd79bc'
Submodule path 'htslib': checked out '3dc96c5699a26c5a46e3ccca4092b3801e1874f4'
```
