### ISSUE TITLE
Compilation terminated on Ubuntu 18.04

### ISSUE THREAD

**Issue by liaoyunshi** [jts/nanopolish#791]
Dear All,

I try to install nanopolish.

I download and compile the latest code from github as follows:

```
git clone --recursive https://github.com/jts/nanopolish.git
cd nanopolish
make
```
But Compilation terminated as follow:

> src/nanopolish_call_methylation.cpp:25:10: fatal error: zlib.h: No such file or directory
>  #include <zlib.h>
>           ^~~~~~~~
> compilation terminated.
> Makefile:155: recipe for target 'src/nanopolish_call_methylation.o' failed
> make: *** [src/nanopolish_call_methylation.o] Error 1

May I know how to deal with it?

Thanks!

**Comment by jts** [comment]
Hi,

You need to install the zlib development packages from your operating system package manager.

Jared
