### ISSUE TITLE
Nanopolish runing with long time and lots of memory

### ISSUE THREAD

**Issue by yazuo0204** [jts/nanopolish#792]
Hi, 

I have a sequence which contains 8.5G bases which is about 100X coverage of the sample. While I am running PolyA with Nanopolish it looks would take forever to process and occupied almost all of my memory. I decided to extract 200 or 500 reads for PolyA estimation in order to avoid the core dumped. But it makes no sense for such low amount of reads. 

BTW, my virtual machine contains 48 treads, 380G memory.

Thank you

**Comment by jts** [comment]
Hi,

Which version of nanopolish are you using? There was a bug that caused high memory usage, it is now fixed in 0.13.2.

Jared
