### ISSUE TITLE
[Question] Do you recommend any "differential methylation" methods that use output from nanopolish?

### ISSUE THREAD

**Issue by jolespin** [jts/nanopolish#795]
I currently have quite a bit of frequency tables generated from `nanopolish`.  I have 2 conditions for my experiments and was wondering if there are any differential methylation scripts available in `nanopolish` or if you recommend any methods that can make use of this data? 

In particular, the output from `calculate_methylation_frequency.py`.

My apologies if this is out of scope.  If so, I will close the issue immediately.

**Comment by jts** [comment]
Hi @jolespin,

We don't have an officially recommended differential methylation approach yet. You might look at https://github.com/a-slide/pycoMeth and https://github.com/wdecoster/methplotlib for ideas on how to compare across samples.

Jared

**Comment by jolespin** [comment]
Thanks a lot @jts !  These look really intuitive to use.  Looks like my only hurdle is a good way to merge replicate runs of `calculate_methylation_frequency.py` that I should have merged before running `nanopolish` in the first place so I can properly use `pycoMeth`.  I have some ideas for this though.  Cheers
