### ISSUE TITLE
Error: read file must be provided 

### ISSUE THREAD

**Issue by OscarChou211** [jts/nanopolish#797]
Hi there, 

Thank you very much for helping! Sorry that I am a newbie to bioinformatics. 

I tried to use the nano polish to enhance my alignment, and here's the things that happened. 

nanopolish eventalign \ -r M11_AJ2_GRCH38_unmapped.fasta \ -b M11_AJ2_pHB9-W4_mapped_sorted.bam \ -g pHB9-W4-MR11_for_RNAseq.fasta \ --scale-events > reads-ref.eventalign.txt 
eventalign: too many arguments
eventalign: a --reads file must be provided
eventalign: a --genome file must be provided
eventalign: a --bam file must be provided
 
I have also attempted to provide with the full address. I wonder how to solve the problem? 

Thank you very much for helping! 

Below are the full address command: 

nanopolish eventalign \ --reads /Users/apple/Desktop/Final_Project/1_Mapping_human_genome/M11_AJ2_minimap2_2/M11_AJ2_GRCH38_unmapped.fasta \ --bam /Users/apple/Desktop/Final_Project/1_Mapping_human_genome/M11_AJ2_minimap2_2/M11_AJ2_pHB9-W4_mapped_sorted.bam  \ --genome /Users/apple/Desktop/Final_Project/0_Reference_genomes/HB9_genome_White/pHB9-W4-MR11_for_RNAseq.fasta  --scale-events > reads-ref.eventalign.txt 
eventalign: too many arguments
eventalign: a --reads file must be provided
eventalign: a --genome file must be provided
eventalign: a --bam file must be provided

**Comment by jts** [comment]
Hi @OscarChou211,

Is this still an issue, or did you solve it? If it is still an issue, try without the line continuation (`\`) characters.

Jared

**Comment by OscarChou211** [comment]
The problem has been solved. It works after without the line continuation! Thank you very much for helping!
