### ISSUE TITLE
Error with calculate_methylation_frequency.py

### ISSUE THREAD

**Issue by EllaliT** [jts/nanopolish#798]
Hii,
When I run this python script on my data I get this error:
**Traceback (most recent call last):
  File "/home/Software/nanopolish/scripts/calculate_methylation_frequency.py", line 41, in <module>
    num_sites = int(record['num_motifs'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'**

I have nanopolish version 0.13.2

**Comment by jts** [comment]
Hi @EllaliT ,

Can you provide the input file that causes this problem?
