### ISSUE TITLE
rror running faidx_build on /rds/general/user/oc720/ephemeral/Fast5/WTw/WTw_combined.fastq.index

### ISSUE THREAD

**Issue by OscarChou211** [jts/nanopolish#799]
Hi there, 

I am using nanopolish v0.13.2 

I use the following command on the HPC: 

nanopolish index -d /rds/general/user/oc720/ephemeral/Fast5/WTw /rds/general/user/oc720/ephemeral/Fast5/WTw/WTw_combined.fastq  

and it shows the following error: 

Error running faidx_build on /rds/general/user/oc720/ephemeral/Fast5/WTw/WTw_combined.fastq.index

I wonder what does that means? 

Thank you!

**Comment by jts** [comment]
I think this was fixed in another issue, so closing this one.
