### ISSUE TITLE
level of parallelism in eventalign

### ISSUE THREAD

**Issue by vadimzalunin** [jts/nanopolish#8]
Trying to understand the effects of '-t' options. The only use I can find is:
omp_set_num_threads(opt::num_threads);

but the main loop seems to be single thread if I'm not mistaken.

Should for example '-t 8' be any faster than default?

**Comment by jts** [comment]
Threading is not implemented yet, sorry. I'll keep this open as a reminder to do this. Thanks for testing nanopolish and the bug reports

**Comment by jts** [comment]
Now implemented: 5309c1aee58
