### ISSUE TITLE
kseq_read returned -2 indicating an error with the input file /rds/general/user/oc720/ephemeral/Fast5/HB9/HB9_nanopore_combined.fastq

### ISSUE THREAD

**Issue by OscarChou211** [jts/nanopolish#800]
Hi there, 

As similar to my last post, I have tried to use nanopolish v.0.13.2 

I used the following command: 

nanopolish index -d /rds/general/user/oc720/ephemeral/Fast5/HB9 /rds/general/user/oc720/ephemeral/Fast5/HB9/HB9_nanopore_combined.fastq  

And it shows the following error: 

kseq_read returned -2 indicating an error with the input file /rds/general/user/oc720/ephemeral/Fast5/HB9/HB9_nanopore_combined.fastq 

I wonder how to deal with that? 

Thank you very much for helping!

**Comment by jts** [comment]
It indicates there is a problem with the input FASTQ file (the format is probably not as expected)

**Comment by OscarChou211** [comment]
Thank you very much for helping! I have used _cat_ to combine all the fastq files together previously, I wonder does that matters? Or should I load all the fastq files individually one by one? If so, how can I put that into the command?

**Comment by jts** [comment]
`cat` should be fine, as long as the files weren't compressed. If you open the fastq in a text editor or `less` does it look OK?

**Comment by OscarChou211** [comment]
I see. Thank you very much for that! I guess it is partly because it is truncated due to internet disconnection last night when I uploaded the file. But I am not entirely sure since the remainly reads seems fairly normal.

**Comment by jts** [comment]
Truncated files will cause this error, if you fix the file it should work.

**Comment by OscarChou211** [comment]
I see. I guess that will do and I can close this issue for now! Thank you very much for helping!
