### ISSUE TITLE
[Question] How to get the most verbose progress output for `nanopolish call-methylation`? 

### ISSUE THREAD

**Issue by jolespin** [jts/nanopolish#801]
Currently I'm using the following flags: 

```
nanopolish call-methylation -t 4 -r 4883_3.nanofilt.fastq -g dna_rm.toplevel.fa -q cpg --bam sorted.bam --progress --verbose > methylation_calls.cpg.tsv
```

Are these the most verbose settings for `call-methylation`?  `--progress` or `--verbose` don't take file names correct?

**Comment by jts** [comment]
Hi @jolespin,

Correct, those arguments don't take filenames. Like many linux programs you can turn on additional levels of verbosity by providing `-vv`, `-vvv`, etc. I don't think `call-methylation` prints a lot of status information though.

Jared

**Comment by jolespin** [comment]
Ok, cool that is good to know. I'm currently running some huge PromethION runs through `call-methylation` right now.  The largest of which is has a 38.144 GB fastq file (uncompressed) and a 25.681 GB sorted bam file so it's going to take a bit and was wondering the best way to monitor it (I'm expecting about a week or two at 4 threads). 

Is `-vvv` the max verbosity?
