### ISSUE TITLE
Warning: XX variants in span, region not called [XX XX]

### ISSUE THREAD

**Issue by res33007** [jts/nanopolish#803]
Hello,

I´m an ungraduate student and work with Oxford Nanopore reads to generate whole Chloroplast genomes for my bachelor thesis. 
I´m calling variants with Nanopolish and encountered the warning you can see in the titel (_Warning: XX variants in span, region not called [XX XX]_). The variant calling was done separately for the 12 contigs I have and this warning only appeared for 2 contigs. The warning was accompanied with a lot of warnings like this: 
_Number of variants in span (XX) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!_ 

Furthermore, there were Nanopolish variants runs (not the ones with the other two warnings) where no [post-run summary] was given. Did the variant calling even work here?

./nanopolish variants --consensus -v -o variants_[contig_number_1-x].vcf -w "contig_number_1-x:0-length" --ploidy 1 -t 5 --max-haplotypes 30000 --min-candidate-frequency 0.2 --max-rounds 50 --calculate-all-support --reads [processed_reads].fastq --bam [sorted_indexed_mapping_of_reads_to_contigs].bam --genome [Canu_contigs].fasta

I hope you can help me.

**Comment by jts** [comment]
Hi,

You may ignore that warning, it is for information only

> Furthermore, there were Nanopolish variants runs (not the ones with the other two warnings) where no [post-run summary] was given. Did the variant calling even work here?

That is unexpected. Did it write a VCF file for that run?

Jared

**Comment by res33007** [comment]
Yes, it did.
I compared a VFC file with a post-run summary with one without it and it looks fine, the header is there and everything.

Thank you for your answer.

**Comment by jts** [comment]
Thanks for the reply, sounds like the program completed successfully.
