### ISSUE TITLE
How to get the corresponding original signal according to the event_index of eventalign

### ISSUE THREAD

**Issue by huangnengCSU** [jts/nanopolish#804]
Hi,
    Thank you very much for your excellent tools Nanopolish. Recently, I used `nanopolish eventalign` to align the raw signals to the contig. But I don't know how to get the raw signals of each event. Can I get some information such as start position on raw signal sequence, end position on raw signal sequence of each event?
Thanks for your help.
Neng

**Comment by jts** [comment]
Hi,

Try adding the `--samples` flag to eventalign.

Jared

**Comment by huangnengCSU** [comment]
To Jared,
That is great and it works. Thanks so much.
Neng
