### ISSUE TITLE
Questions about the version of Guppy

### ISSUE THREAD

**Issue by zcWang0591** [jts/nanopolish#806]
Hi,
I meet a problem when I try to use the Calling Methylation module according to the guidance(https://nanopolish.readthedocs.io/en/latest/quickstart_call_methylation.html)
The problem is that I miss file dna_r9.4.1_450bps_flipflop.cfg when I use Guppy. Finally, I find that it may be caused by the different versions of Guppy. So, does nanopolish only support the version of Guppy according to the guidance? Or, I just need to download dna_r9.4.1_450bps_flipflop.cfg, and different versions of Guppy can be used?

**Comment by jts** [comment]
You can use any version of guppy and any config prior to nanopolish. I suggest the latest version of Guppy with the high-accuracy config.

Jared

**Comment by zcWang0591** [comment]
Hi, I was following your guidance(https://nanopolish.readthedocs.io/en/latest/quickstart_call_methylation.html), so I download NA12878 WGS Consortium data provided by you, and use Guppy for base calling, the command line is guppy_basecaller -c dna_r9.4.1_450bps_flipflop.cfg -i fast5_files/ -s basecalled/.  But for -c dna_r9.4.1_450bps_flipflop.cfg, the latest version of Guppy do not have this configuration file, so can you recommend a new parameter setting way for this -c choice?

**Comment by jts** [comment]
I suggest using the "hac" model for the latest version of guppy (`dna_r9.4.1_450bps_hac.cfg`)
