### ISSUE TITLE
Methylation frequency on the + and - strand 

### ISSUE THREAD

**Issue by TheresaLueth** [jts/nanopolish#808]
Hi,

Is there a way to split the output of _naopolish calculate_methylation_frequency_ by + and - strand? There is a column with strand information in the output of _naopolish call-methylation_ but not in the output of _naopolish calculate_methylation_frequency_.

Thank you!

**Comment by jts** [comment]
HI @TheresaLueth,

There currently is not a function to do this in `calculate_methylation_frequency.py`. If you would like stranded frequencies, I suggested splitting the `call-methylation` file in two, one file for `+` and one for `-`.

Jared

**Comment by TheresaLueth** [comment]
Okay, I will try this.
Thank you for your help!

**Comment by jts** [comment]
No problem, happy to help

**Comment by PanZiwei** [comment]
Hi,
How can we split the `call-methylation` file in two? Can you explain more details? Thanks!
