### ISSUE TITLE
Nanopolish Variants error for human genome variants calling 

### ISSUE THREAD

**Issue by shashibioinfo143** [jts/nanopolish#809]
Hi Everyone,

I was doing Targeted Human Genome Variant calling for nanopore data using nanopolish below was the command used

**nanopolish variants --consensus --reads barcode01.fastq --bam barcode01.bam --genome hg19.fa -v -p 2 --genotype barcode01_variants.vcf**

i got error 
**Error: genome has multiple contigs, please use -w to specify input region**

if we use -w option to provide list of below positions in which format shall i provide ?

unlike othe variant callers in this the procedure is complicated.

i request to please resolve this issue for the next release.

Need help

Thank you

List of Positions 

chr1:155203972-155211737
chr2:234668509-234670438
chr2:234675338	234682140	
chr4:979818-984490	
chr4:993326-998994	
chr6:112375170-112382740	
chr6:112384890-112392747	
ch11:5226762-5227234	
chr11:6410628-6416623

**Comment by jts** [comment]
Hi @shashibioinfo143,

The `-w` option does not take a list, so you will have to run the nanopolish command for each region separately.

Jared

**Comment by shashibioinfo143** [comment]
> Hi @shashibioinfo143,
> 
> The `-w` option does not take a list, so you will have to run the nanopolish command for each region separately.
> 
> Jared

In that case
For the next update this issue as to be resolved
It's difficult to provide list of positions manually.

Thanks

**Comment by jts** [comment]
You can use `xargs` to make this a little easier (the `{}` will be replaced with the region):

```
cat regions.txt | xargs -i nanopolish variants --consensus --reads barcode01.fastq --bam barcode01.bam --genome hg19.fa -v -p 2 --genotype barcode01_variants.vcf -o {}.vcf -w {}
```

Btw you should not use the `--consensus` flag for reference variant calling

**Comment by shashibioinfo143** [comment]
> You can use `xargs` to make this a little easier (the `{}` will be replaced with the region):
> 
> ```
> cat regions.txt | xargs -i nanopolish variants --consensus --reads barcode01.fastq --bam barcode01.bam --genome hg19.fa -v -p 2 --genotype barcode01_variants.vcf -o {}.vcf -w {}
> ```
> 
> Btw you should not use the `--consensus` flag for reference variant calling

Thank you so much for resolving
