### ISSUE TITLE
fast5 basecalled with multiple basecaller versions

### ISSUE THREAD

**Issue by touala** [jts/nanopolish#813]
Hello,

When fast5 reads are basecalled with multiple basecallers or basecaller's versions, can I select which one to use? I'm mostly interested in the `eventalign` function but I can see that the `nanopolish extract -b` seems to allow this selection. Does supplying the reads/alignments from one specific basecaller is sufficient or should I also specify which version when using other functions like `eventalign`?

Thanks for your help.

**Comment by jts** [comment]
Hi,

`nanopolish extract` is a legacy program that is only used for compatibility with very old data. You should have guppy output fastq files, then use those basecalled reads with the original fast5s in `nanopolish index`.

Jared

**Comment by touala** [comment]
To be sure I understand correctly. If there are two basecalling versions made on the same set of fast5s, then supplying the reads from one version or the other when running `nanopolish index` will govern `nanopolish eventalign` behaviors?

**Comment by jts** [comment]
Let's say you've run two different basecallers:

```
run_guppy_version_3.5 fast5_directory/ > reads.guppy_3.5.fastq
run_guppy_version_3.6 fast5_directory/ > reads.guppy_3.6.fastq
```

then if you want to use the 3.6 reads:

```
nanopolish index -d fast5_directory reads.guppy_3.6.fastq
nanopolish index -r reads.guppy_3.6.fastq [...]
```

**Comment by touala** [comment]
Great. Thank you for the help and explanation. Have a good day.
