### ISSUE TITLE
What does min-candidate-frequency do?

### ISSUE THREAD

**Issue by chocotwig** [jts/nanopolish#815]
Hello!
I'm unclear on what exactly `--min-candidate-frequency `does for ```nanopolish variants```.
I'm only looking to polish my assembly. This option looks to be the min threshold for just flagging something as a SNP? Does it actually impact the final polished assembly?

Thanks!

**Comment by jts** [comment]
Hi,

Nanopolish uses the aligned reads to gather possible edits that may improve the assembly. That parameter controls how often an edit needs to be seen in the reads to consider it a candidate. You can leave it at the default value.

Jared

**Comment by chocotwig** [comment]
Thanks for your quick response. My assembly is highly error prone, and the read coverage is very low ~5x. 
A larger ```--min-candidate-frequency``` makes more sense here, do you agree?

Thanks!

**Comment by jts** [comment]
It is unlikely that you will get good results from nanopolish with such low coverage with any parameters, sorry.

Jared

**Comment by chocotwig** [comment]
Thanks Jared.
I agree, it is unlikely. Still, I'm keen on trying this out as an experiment, and was wondering what would be a good starting point - do you have any recommendations?

Niraj

**Comment by chocotwig** [comment]
Thanks Jared.
I agree, it is unlikely. Still, I'm keen on trying this out as an experiment, and was wondering what would be a good starting point - do you have any recommendations?

Thanks!

**Comment by jts** [comment]
I'm sorry but I don't have any parameter recommendations for this use case

Jared
