### ISSUE TITLE
Read block operation failed with error 2 after 0 of 4 bytes 

### ISSUE THREAD

**Issue by OscarChou211** [jts/nanopolish#817]
Hi there, 

I am a newbie to bioinformatics and also coding. 

I have been trying to use the eventalign of the nano polish to align the RNA reads to the genome. 

I have used the following command: 

nanopolish index -d /rds/general/user/oc720/ephemeral/Fast5/HB9 /rds/general/user/oc720/ephemeral/Fast5/HB9/HB9_nanopore_combined.fastq  

This index seems to works fine since I used this with the polyA estimation before and it did work well. 

I then move the index file from ephemeral to my home one the HPC. 

I then use the nano polish event align: 

nanopolish eventalign --sam --threads 8 --summary ./summary.txt --reads /rds/general/user/oc720/home/FAST5/HB9/HB9_nanopore_combined.fastq --bam /rds/general/user/oc720/home/nanopolish/HB9/HB9_HB9mutant_sorted.bam --genome /rds/general/user/oc720/home/EBNA_LP/HB9_mutant_mapped/RNAseq-HB9mutant.fa --scale-events > reads-ref.eventalign.txt --progress 

However, it shows the above error: 

Read block operation failed with error 2 after 0 of 4 bytes  

I wonder how to solve that? May I know what is the problem associated with that? 

Thank you very much for helping! 

Best regards

**Comment by jts** [comment]
Hi,

Try to re-run the index on your HPC, there may be a subtle difference in the encoding causing this issue.

Jared
