### ISSUE TITLE
Nanopolish direct RNA sequencing? 

### ISSUE THREAD

**Issue by OscarChou211** [jts/nanopolish#818]
Hi there, 

Thank you very much for helping! I am a newbie to bioinformatics. 

I have some questions about nanopolish. 

I have some direct RNA sequencing data using MINION. I previously ran a guppy and then used the fastq to map to a reference genome. 

However, I wonder if it is possible to use nanopolish to enhance the consensus accuracy of the mapping? I wonder which software should I use? 

Furthermore, I have saw in the manual the eventalign can be able to output a sam file. I wonder if that is the case? 

Thank you very much for helping! 

Best regards,

**Comment by jts** [comment]
Sorry but nanopolish does not support consensus calling for direct RNA data.

Jared

**Comment by OscarChou211** [comment]
I see. 

Sorry it may be the wrong place to ask this subsequent question, but I wonder do you have any idea are there any software for this purpose for direct RNA data? 

Thank you very much Jared!

**Comment by jts** [comment]
Sorry but I don't know of any.

Jared
