### ISSUE TITLE
No extract on reads with no events

### ISSUE THREAD

**Issue by rrwick** [jts/nanopolish#82]
Hello! I just tried to run Nanopolish on some recent sequencing data and found that `nanopolish extract` didn't return any sequence at all from my fast5 files.

The reads have fastq basecalling but no events. Here's a screenshot of one read's structure:
<img width="517" alt="fast5" src="https://cloud.githubusercontent.com/assets/7053555/19808473/c46941c2-9d70-11e6-88e7-5d5dac04e241.png">
[This recent PR[(https://github.com/jts/nanopolish/pull/79) mentions that a read 'must have sequence as well as events', so it seems this is expected behaviour.

This run was basecalled locally (possible with a recent MinKNOW update), not in the cloud with Metrichor. Is it possible that with this new basecalling approach, Oxford Nanopore is no longer saving event in the fast5 files? I hope that doesn't mean any locally basecalled reads are unusable with Nanopolish...

**Comment by jts** [comment]
Hi Ryan,

Yes, right now locally basecalled reads do not have events so they cannot be used with nanopolish. ONT have assured me that will be changed soon but in the meantime you'll have to send them through metrichor/epi2me if you want to use them with nanopolish. If you don't need to run nanopolish `poretools` will extract the sequences for you.

Jared

PS: If you have an ONT account feel free to upvote/comment on the feature request I put in 30 minutes ago: http://features.nanoporetech.com/ideas/ALGS-I-3 :)
