### ISSUE TITLE
No fast5 found

### ISSUE THREAD

**Issue by scogi** [jts/nanopolish#821]
Hi,

I am using Nanopolish to call variants (for phasing later on with whatshap), but I am having an issue with recalled fast5 files. The files were called online during sequencing using FAST algorithm and then worked properly in Nanopolish. i did then recall them with gupy 4.0.14 and HAC algorithm, but Nanopolish now tells that there are no reads in the fast5_folder, despite they are clearly there

`$/opt/nanopolish/nanopolish index -d ../../fast5_pass/barcode20 barcode20.fastq`
`[readdb] indexing ../../fast5_pass/barcode20`
`Error: no fast5 files found`

`$ ls -lh ../../fast5_pass/barcode20`
`total 361036`
`drwxrwxrwx  2 qf0297 qf0297      4096 Aug 13 14:25 ./`
`drwxrwxrwx 23 qf0297 qf0297      4096 Aug 13 14:25 ../`
`-rwxrwxrwx  1 qf0297 qf0297  64890625 Aug 13 13:32 FAO27706_pass_barcode20_4c81d22b_0.fast5*`
`-rwxrwxrwx  1 qf0297 qf0297 128914754 Aug 13 13:32 FAO27706_pass_barcode20_d6764c73_0.fast5*`
`-rwxrwxrwx  1 qf0297 qf0297 131299489 Aug 13 13:32 FAO27706_pass_barcode20_d6764c73_1.fast5*`
`-rwxrwxrwx  1 qf0297 qf0297  44578644 Aug 13 13:32 FAO27706_pass_barcode20_d6764c73_2.fast5*`

 `/opt/nanopolish/nanopolish index -s ../../fastq_hac/sequencing_summary.txt -d ../../fast5_pass/barcode20` `barcode20.4000_5000_q10.fastq`
`[readdb] indexing ../../fast5_pass/barcode20`
`[readdb] num reads: 3556, num reads with path to fast5: 2`
``

Nanopolish is v0.9.2

Any advice what the issue could be?

Thank you!

**Comment by jts** [comment]
Hi, 

0.9 is quite old, can you try with the latest version?

Jared

**Comment by scogi** [comment]
Sorry, my fault!!! I checked out the wrong version. Works like a charm now
