### ISSUE TITLE
Can you eventalign with minimap2 with just the fastq file?

### ISSUE THREAD

**Issue by sydneyguy1981** [jts/nanopolish#822]
Hi.
I've only access to the fastq files at the moment as the fast5 files are quite large and still need time to transfer over to my HPC system. Can you run minimap2 straight from the fastq files?
Thanks.

**Comment by Chris-Kimmel** [comment]
I believe so. Of course, you do need something to map them to (such as a reference genome or a draft assembly).

The commands from the [eventalign tutorial](https://nanopolish.readthedocs.io/en/latest/quickstart_eventalign.html) should work just fine without fast5 files:
```bash
$ minimap2 -ax map-ont -t 8 ref.fa reads.fasta | samtools sort -o reads-ref.sorted.bam -T reads.tmp
$ samtools index reads-ref.sorted.bam
```

The `minimap` step comes after the `nanopolish index` step in the tutorial, but I don't think that is by necessity.

**Comment by jts** [comment]
Eventalign requires the fast5 files as the signal data is contained within the fast5s, so you'll need to transfer these.
