### ISSUE TITLE
"The 2D ONT reads are in fasta FILE"

### ISSUE THREAD

**Issue by Chris-Kimmel** [jts/nanopolish#824]
The help message from running
```bash
nanopolish evantalign --help
```
says
```
  -r, --reads=FILE        the 2D ONT reads are in fasta FILE
```
Doesn't Nanopolish support 1D reads as well?

Similar issue from 2018 regarding `polya` function:
https://github.com/jts/nanopolish/issues/346

**Comment by Chris-Kimmel** [comment]
If it's as simple as deleting a word from this line of code, then let me know and I can make a pull request.
https://github.com/jts/nanopolish/blob/e2745af324c1d59962c54a0e900c72586de32a71/src/alignment/nanopolish_eventalign.cpp#L62

**Comment by jts** [comment]
Thanks for the report - indeed that message was out of date and nanopolish supports 1D reads (and no longer supports 2D). Fixed
