### ISSUE TITLE
Help on using the nanopolish train module in the r10 branch

### ISSUE THREAD

**Issue by hasindu2008** [jts/nanopolish#825]
We have been trying to use  the **train** module in the _r10_ branch of _nanopolish_ (closely related to https://github.com/jts/nanopolish/issues/761). The command used was `nanopolish train --progress --rounds=10 --threads=64 --train-kmers=methylated --input-model-filename etc/r9-models/r9.4_450bps.nucleotide.6mer.template.model --reads positive_pass.test.fastq --bam positive_pass.test.sorted.bam --genome hg38noAlt.fa --verbose -d pos_out/`

However, the _event output_ is totally empty and the in _summary_ many columns are 0 (output attached below).
[r9.4_450bps.nucleotide.6mer.template.round9.events.tsv.txt](https://github.com/jts/nanopolish/files/5121122/r9.4_450bps.nucleotide.6mer.template.round9.events.tsv.txt)
[r9.4_450bps.nucleotide.6mer.template.round9.summmary.tsv.txt](https://github.com/jts/nanopolish/files/5121121/r9.4_450bps.nucleotide.6mer.template.round9.summmary.tsv.txt)

The last part of the log output is as follows:
```
[bam process] processed 1164784 bam records in 4406.00s (264 records/s). Latest: chrUn_GL000218v1:10597
[train] trained 0/0 k-mers in 0.00s
[post-run summary] total reads: 7461941, unparseable: 0, qc fail: 86159, could not calibrate: 19170, no alignment: 991025, bad fast5: 0
```

So I think I am doing something wrong and have the following questions.

1. is _--bedmethyl=FILE_ a mandatory option when training for methylation?
2. Is there any documentation on the correct use of the _train_ module?
3. After running _train_ module, how can the trained module be converted into a _nanopolish_ model to be used with _call-methylation_ module?

**Comment by jts** [comment]
Hi Hasindu,

Has the genome been modified to annotate the methylated positions with an `M` symbol? This is required for training. Also, the input model needs to have a header describing the alphabet. Here is the header I use for the r10 development models:

```
#ont_model_name r10_180mv_450bps_9mer
#kit    r10_450bps
#strand template
#k      9
#alphabet       nucleotide
#original_file  r10_180mv_450bps_9mer/template_r10_9mer.model
kmer    level_mean      level_stdv      sd_mean sd_stdv weight  fstat
#alphabet       cpg
AAAAAAAAA       32.100784       1.234167        0.772451        0.422038        12546.569785
AAAAAAAAC       37.489590       2.482174        1.518776        1.113371        1279.840777
```

(note alphabet key/value).

For your other questions:

1. No, this is an experimental feature and not required
2. Sorry for the poor documentation, this code is not yet ready for public release. The feature is 90% complete but my attention was pulled away
3. The output model should be in the right format and directly usable by call-methylation.

Jared


Jared

**Comment by hasindu2008** [comment]
Thank you, Jared. Now it is giving a non-empty output. 

- Could you please confirm if what we are doing is correct (stated below).

1. For the positive sample (all CpG sites are methylated in this sample), all the CG sites in the reference are made MG, and nanopolish train is run under **--train-kmers=methylated**  with your default **r9.4_450bps.cpg.6mer.template.model** modified to include the _#alphabet       cpg_ line.
2. For the negative sample (no C is methylated), the original reference is used where nanopolish train is run under **--train-kmers=unmethylated**  with your default **r9.4_450bps.nucleotide.6mer.template.model** modified to include the _#alphabet      nucleotide_  line.
3. The k-mers with 'M'  are extracted from the model output from 1 above, and the rest of the k-mers from 2 above, which are concatenated and sorted to create the final model file

- Also, what is the recommended number of training rounds - Is 10 adequate?

**Comment by jts** [comment]
I don't think concatenating models with different alphabets will work. Instead, you could make a hybrid reference genome, one with all CGs changed into MG, and the other with the CGs left unchanged. Then map the positive/negative reads to the corresponding reference, and merge the BAMs together. This produces a training set with a mixture of methylated and unmethylated data. Alternatively just training on the methylated data, leaving CG k-mers untrained, usually gives decent results.

10 rounds should be fine.

**Comment by hasindu2008** [comment]
Thank you, Jared. 

1. For this hybrid approach, is it still  r9.4_450bps.cpg.6mer.template.model to be used as the input model? 
2. Should both _#alphabet cpg_  and _#alphabet nucleotide_ lines be added into the input model or just _#alphabet cpg_?

We are training on a dataset from r9.5.

**Comment by jts** [comment]
1. yes
2. no, you can only have one alphabet per model. it should be `cpg` here.

**Comment by hasindu2008** [comment]
Thanks, Jared. It has successfully run now. The model values have changed and some examples are as follows:

![image](https://user-images.githubusercontent.com/12987163/92427660-677da300-f1d0-11ea-9428-f2086b809ffe.png)
