### ISSUE TITLE
Define "read_index" in eventalign output

### ISSUE THREAD

**Issue by Chris-Kimmel** [jts/nanopolish#828]
Hi!

I'd like to compare Nanopolish eventalign data with Tombo model_sample_compare data on a read-by-read basis. The problem is that Tombo and Nanopolish appear to label reads differently. [Nanopolish eventalign output](https://nanopolish.readthedocs.io/en/latest/quickstart_eventalign.html#assess-the-eventalign-output) refers to a `read_index`, which is a nonnegative integer like `117`, whereas Tombo uses `read_id`s that look like `00676bde-4b93-45bb-a850-c333e08c9927`, (For us, the basename of each fast5 file equals the `read_id` of the read therein. We use single-Fast5s.)

How do I correctly convert between Tombo's `read_id` and Nanopolish's `read_index`?

Thanks,
Chris K

**Comment by jts** [comment]
Hi Chris,

If you provide the `--print-read-names` option you'll get the same names as tombo.

Jared

**Comment by Chris-Kimmel** [comment]
> If you provide the `--print-read-names` option you'll get the same names as tombo.

Thank you for that extremely fast response, @jts .
