### ISSUE TITLE
nanopolish install failed

### ISSUE THREAD

**Issue by malaria123** [jts/nanopolish#829]
can some one please help?
i tried to install nanopore, used
**git clone --recursive https://github.com/jts/nanopolish.git**
got>>> make: *** [src/nanopolish_extract.o] Error 1
then fixed this in bc8ee4f 
then ran
**cd nanopolish**
then ran
**make**
got >>> make: *** [.depend] Error 1
used
**make CC=gcc-6 CXX=g++-6**
got>> make: g++-6: No such file or directory
make: *** [src/main/nanopolish.o] Error 1

**Comment by malaria123** [comment]
please help me out! I dont know what should I do now

**Comment by jts** [comment]
Hi,

It looks like you're using OSX - I recommend that you install nanopolish through conda.

Jared

**Comment by malaria123** [comment]
hi, 
thanks for help.
but
I am using conda, then

(base) flprntst:nanopolish xuzhang$ conda install -c bioconda nanopolish
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                            

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - nanopolish -> python[version='2.7.*|3.5.*|3.6.*']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

**Comment by malaria123** [comment]
does this mean i should use 2.7.|3.5.|3.6. not 3.8?

**Comment by malaria123** [comment]
Then we tried to make an enviroment for it
conda create -n nanopolish-env python=3.6
conda activate nanopolish-env
conda install -c bioconda nanopolish
then I got
(nanopolish-env) Xus-MacBook-Pro:nanopolish xuzhang$ conda install -c bioconda nanopolish
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Thanks!

**Comment by jts** [comment]
Hi,

Unfortunately my time is very limited right now and since the MacOS build is only semi-supported (we try to make it work, but don't spend much time on it) I can't really help resolve this right now. If possible I suggest using nanopolish on a linux computer, or try to find out what packages in your conda environment conflict with it. 

Sorry I can't help more,
Jared

**Comment by malaria123** [comment]
ok, thank you!

**Comment by malaria123** [comment]
I am sorry I am very desperate. you can ignore me if you are busy @jts, and I am just hoping someone can help. I think I am very close to success, maybe i am wrong;( 
anyway,
now I am at this 
MAC184761:nanopolish lak9015a$ make CC=gcc-6 CXX=g++-6
g++-6 -o nanopolish -g -O3 -std=c++11 -fopenmp -fsigned-char -D_FILE_OFFSET_BITS=64  -I./include -I./htslib -I./minimap2 -I./fast5/include -I./src -I./src/hmm -I./src/thirdparty -I./src/thirdparty/scrappie -I./src/common -I./src/alignment -I./src/pore_model -I./src/io -I./eigen/ -fPIC src/main/nanopolish.o src/nanopolish_call_methylation.o src/nanopolish_call_variants.o src/nanopolish_extract.o src/nanopolish_getmodel.o src/nanopolish_haplotype.o src/nanopolish_index.o src/nanopolish_methyltrain.o src/nanopolish_phase_reads.o src/nanopolish_polya_estimator.o src/nanopolish_raw_loader.o src/nanopolish_read_db.o src/nanopolish_scorereads.o src/nanopolish_squiggle_read.o src/nanopolish_train_poremodel_from_basecalls.o src/nanopolish_variant_db.o src/nanopolish_vcf2fasta.o src/training_core.o src/hmm/nanopolish_duration_model.o src/hmm/nanopolish_profile_hmm.o src/hmm/nanopolish_profile_hmm_r7.o src/hmm/nanopolish_profile_hmm_r9.o src/hmm/nanopolish_transition_parameters.o src/common/fs_support.o src/common/logsum.o src/common/nanopolish_alphabet.o src/common/nanopolish_bam_processor.o src/common/nanopolish_bam_utils.o src/common/nanopolish_common.o src/common/nanopolish_iupac.o src/common/nanopolish_klcs.o src/common/nanopolish_variant.o src/alignment/nanopolish_alignment_db.o src/alignment/nanopolish_anchor.o src/alignment/nanopolish_eventalign.o src/pore_model/nanopolish_model_names.o src/pore_model/nanopolish_pore_model_set.o src/pore_model/nanopolish_poremodel.o src/io/nanopolish_fast5_io.o src/io/nanopolish_fast5_loader.o src/io/nanopolish_fast5_processor.o src/thirdparty/fet.o src/thirdparty/stdaln.o src/thirdparty/scrappie/event_detection.o src/thirdparty/scrappie/scrappie_common.o ./htslib/libhts.a ./minimap2/libminimap2.a ./lib/libhdf5.a -lz -ldl 
ld: can't open output file for writing: nanopolish, errno=21 for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [nanopolish] Error 1

any help would be deeply appreciated!

**Comment by malaria123** [comment]
the problem is fixed! Thanks!

**Comment by jts** [comment]
Very glad to hear that!

**Comment by malaria123** [comment]
thank you very much
solution:
install Xcode from apple store and through it download GCC
then run 
brew install gcc
brew cleanup
git clone --recursive https://github.com/jts/nanopolish.git
cd nanopolish
make CC=gcc-6 CXX=g++-6

**Comment by PanZiwei** [comment]
> thank you very much
> solution:
> install Xcode from apple store and through it download GCC
> then run
> brew install gcc
> brew cleanup
> git clone --recursive https://github.com/jts/nanopolish.git
> cd nanopolish
> make CC=gcc-6 CXX=g++-6

Hi sorry to bother you, 
When you use `make CC=gcc-6 CXX=g++-6`, are you suggesting that you assign the gcc version with `gcc-6`? But the readme file shows that nanopolish is developed under `gcc-4.8`?

Thank you so much for your help!
