### ISSUE TITLE
Alphabet error: ./src/common/nanopolish_alphabet.h:173... Assertion `IUPAC::isValid(out[i])' failed

### ISSUE THREAD

**Issue by gringer** [jts/nanopolish#83]
I'm not quite sure what's happening here. The eventalign method fails at line 5316 according to samtools:

```
$ ~/install/nanopolish/nanopolish eventalign -t 8 --sam -r fastq/nanopolish_all_2016-Oct-17.fasta -b nanopolish_all_vs_IFN_All_Actb_DNACS_mmus.bam   -g IFN_All_Actb_DNACS_mmus.fa --models nanopolish_models.fofn | samtools view -Sb - | samtools sort -O BAM -o eventalign_all_vs_IFN_All_Actb_DNACS_mmus.bam
registering model t.007-base
registering model t.007-ONT
[fai_load] build FASTA index.
nanopolish: ./src/common/nanopolish_alphabet.h:173: virtual std::__cxx11::string Alphabet::disambiguate(const string&) const: Assertion `IUPAC::isValid(out[i])' failed.
[W::sam_read1] parse error at line 5316
[main_samview] truncated file.

$ ~/install/nanopolish/nanopolish eventalign -t 8 --sam -r fastq/nanopolish_all_2016-Oct-17.fasta -b nanopolish_all_vs_IFN_All_Actb_DNACS_mmus.bam   -g IFN_All_Actb_DNACS_mmus.fa --models nanopolish_models.fofn > /dev/null
registering model t.007-base
registering model t.007-ONT
nanopolish: ./src/common/nanopolish_alphabet.h:173: virtual std::__cxx11::string Alphabet::disambiguate(const string&) const: Assertion `IUPAC::isValid(out[i])' failed.
Aborted
```
I don't seem to have any non-IUPAC symbols in the fasta file:
```
$ grep -v '^>' fastq/nanopolish_all_2016-Oct-17.fasta | grep '[^ACGT]'
<no output>
```

I am mapping to the mouse reference genome in addition to my target amplicons, so perhaps that's the problem...

**Comment by gringer** [comment]
Ach, nevermind. I was hoping to use this to correct my *reads*, but it looks like it's more for correcting the mapped genome.

**Comment by jts** [comment]
Yes, that's right - it is for calling variants or a new consensus for a given genome.

**Comment by AAMCgenomics** [comment]
Dear jared I am having this error while I trying to eventalign a small amplicon experiment (~1kb), Do you have any suggetion.
I am using the last nanopolish code in github.

Thank you in advance for your suggestions.

"error message:

nanopolish: ./src/common/nanopolish_alphabet.h:173: virtual std::__cxx11::string Alphabet::disambiguate(const string&) const: Assertion `IUPAC::isValid(out[i])' failed. "

code used:

nanopolish eventalign -t 4 --sam -r minoNB0301.fa -b reads.sorted.03.bam -g HIVHXB.fa --models nanopolish_models.fofn | samtools view -Sb - | samtools sort -o reads.eventalign.sorted.03.bam

**Comment by jts** [comment]
Hi,

Your input genome sequence `-r minoNB0301.fa` contains a symbol that is nanopolish doesn't recognise - maybe it contains a lowercase base?

Jared
