### ISSUE TITLE
error: could not load the index files for input file

### ISSUE THREAD

**Issue by navtronius** [jts/nanopolish#830]
Hi!

I used: https://nanopolish.readthedocs.io/en/latest/quickstart_call_methylation.html and everything worked fine. When I use the same commands with my data I get:

error: could not load the index files for input file

when I attempt to run call-methylation in nanopolish.

Here is the pipeline:
~/longread$ ls
fast5  hg19.fa  hu64_test_nanopore.fastq

:~/longread$ nanopolish index -d fast5/ hu64_test_nanopore.fastq
[readdb] indexing fast5/
[readdb] num reads: 147526, num reads with path to fast5: 147526

:~/longread$ minimap2 -a -x map-ont hg19.fa hu64_test_nanopore.fastq | samtools sort -T tmp -o hu64_test_nanopore.sorted.bam
[M::mm_idx_gen::0.719*1.00] collected minimizers
[M::mm_idx_gen::0.840*1.29] sorted minimizers
[M::main::0.840*1.29] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.900*1.27] mid_occ = 47
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.940*1.26] distinct minimizers: 5196958 (91.87% are singletons); average occurrences: 1.165; average spacing: 10.780
[M::worker_pipeline::100.752*2.86] mapped 137010 sequences
[M::worker_pipeline::100.878*2.86] mapped 10516 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -a -x map-ont hg19.fa hu64_test_nanopore.fastq
[M::main] Real time: 100.901 sec; CPU: 288.308 sec; Peak RSS: 2.239 GB
[bam_sort_core] merging from 1 files and 1 in-memory blocks...

:~/longread$ samtools index hu64_test_nanopore.sorted.bam

:~/longread$ nanopolish call-methylation -t 8 -r hu64_nanopore_test.fastq -b hu64_nanopore_test.sorted.bam -g hg19.fa -w "chr20:5,000,000-10,000,000" > longreadmethylationcalls.tsv
error: could not load the index files for input file hu64_nanopore_test.fastq
Please run nanopolish index on your reads (see documentation)

The only difference I see between the example data and my test data is that during the minimap2 alignment step, there is an extra line:
[M::worker_pipeline::100.752*2.86] mapped 137010 sequences
[M::worker_pipeline::100.878*2.86] mapped 10516 sequences

and then there is this extra bam_sort_core that isn't present in the example data either:
[bam_sort_core] merging from 1 files and 1 in-memory blocks...

Other than that, it looks the same. Here is what is currently in the directory:
:~/longread$ ls
fast5                     hu64_test_nanopore.fastq.index      hu64_test_nanopore.fastq.index.readdb  longreadmethylationcalls.tsv
hg19.fa                   hu64_test_nanopore.fastq.index.fai  hu64_test_nanopore.sorted.bam
hu64_test_nanopore.fastq  hu64_test_nanopore.fastq.index.gzi  hu64_test_nanopore.sorted.bam.bai

Any help would be appreciated. Thanks!

**Comment by jts** [comment]
Hmm, it looks like all the index files are there so I'd expect this to work. Are they empty or do they have non-zero size?

Jared

**Comment by navtronius** [comment]
Thanks for responding - they are all non-zero in size.

**Comment by jts** [comment]
Oh I just noticed that the file names are wrong - sometimes you use `hu64_test_nanopore.fastq` and other times `hu64_nanopore_test.fastq` (nanopore and test are swapped)

**Comment by navtronius** [comment]
So when I fix that, I get:

:~/longread$ nanopolish call-methylation -t 8 -r hu64_test_nanopore.fastq -b hu64_nanopore_test.sorted.bam -g hg19.fa > longreadmethylationcalls.tsv
[E::fai_build_core] Different line length in sequence 'PG'
Error: could not open genome file: hg19.fa
Please check the path is correct

ls for directory:
:~/longread$ ls
fast5                               hu64_test_nanopore.fastq.index.gzi
hg19.fa                             hu64_test_nanopore.fastq.index.readdb
hu64_test_nanopore.fastq            hu64_test_nanopore.sorted.bam
hu64_test_nanopore.fastq.index      hu64_test_nanopore.sorted.bam.bai
hu64_test_nanopore.fastq.index.fai  longreadmethylationcalls.tsv

**Comment by navtronius** [comment]
Let me try a couple things out - I'll get back to your shortly

**Comment by navtronius** [comment]
Hi Jared! So, I decided to try a different hg19.fa file: https://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/

Turns out the .fa I was using was incomplete or had some errors. Redid the pipeline with the new hg19.fa and it worked!

**Comment by jts** [comment]
Glad to hear it!
