### ISSUE TITLE
indexed only 39% total reads

### ISSUE THREAD

**Issue by 2017-ambMicrobiome** [jts/nanopolish#832]
Hello, 

I am having an issue were only ~1/3 of the reads in the fastq file have a path to the fast5 files. 
Version 0.13.2
Command:
nanopolish index -d barcode01/ combined_minion.fastq

[readdb] num reads: 1328626, num reads with path to fast5: 512280

Command for Guppy basecalling:
guppy -i ${data} -s ${out} --flowcell FLO-MIN106 --kit SQK-LSK109 \
        --num_callers ${par} --cpu_threads_per_caller ${threads} \
        --qscore_filtering --hp_correct 1 --trim_strategy 'dna' \
        --detect_mid_strand_barcodes --barcode_kits "EXP-NBD104" \
        --trim_barcodes --compress_fastq

Guppy version 3.4.4

Can you see any reason why this might be? Thanks.

**Comment by jts** [comment]
If you provide the directory to all fast5s (instead of `-d barcode01`) do you get a different result?
