### ISSUE TITLE
Number of reads listed in index & eventalign stdout doesn't match 

### ISSUE THREAD

**Issue by a-sneddon** [jts/nanopolish#833]
Hi,

I have been using the output of eventalign to calculate the % of reads discarded by nanopolish and have noticed that the total number of reads listed in the standard output of _nanopolish index_ and _nanopolish eventalign_ for the same dataset do not match.  I have verified the number of reads with alternative tools and found that the number of reads listed by _nanopolish index_ is correct, while _nanopolish eventalign_ overestimates the number of reads.

Here is an example:
**nanopolish index output**
[readdb] indexing data
[readdb] indexing data/sub_dir
[readdb] indexing data/sub_dir/sub_sub_dir
[readdb] num reads: 471731, num reads with path to fast5: 471731

**nanopolish eventalign output**
[post-run summary] total reads: 727710, unparseable: 0, qc fail: 5895, could not calibrate: 7091, no alignment: 2218, bad fast5: 0

Please let me know if I have missed something and this is the intended behaviour.

Thanks,
Alex

**Comment by jts** [comment]
Hi Alex,

The `post-run` message is a little misleading since it counts the number of alignments it processed in the BAM, not unique reads seen. Its probably working as intended.

Jared

**Comment by a-sneddon** [comment]
Hi Jared,

Thanks for getting back to me, that clears things up!

Thanks,
Alex
