### ISSUE TITLE
eventalign could not calibrate

### ISSUE THREAD

**Issue by pabloacera** [jts/nanopolish#834]
Hi,
I am trying to use eventalign with relatively short reads (100bp) and I get that it cannot calibrate the reads. I guess it is because of the small length of the reads?
Thanks. 

```
 ~/lib/nanopolish/nanopolish eventalign -t 10 --reads oligos_all_filtered_16_l80_120_backbone_corrected.fasta  --bam oligos_all_filtered_16_l80_120_backbone_corrected_sorted.bam  --genome oligos_all_filtered_16_l80_120_backbone_corrected_references.fasta --scale-events --signal-index --print-read-names  > oligos_all_filtered_16_l80_120_backbone_corrected_eventalign.txt
[fai_load] build FASTA index.
[post-run summary] total reads: 202, unparseable: 0, qc fail: 0, could not calibrate: 202, no alignment: 0, bad fast5: 0
```

**Comment by jts** [comment]
Yes, it is likely due to the short reads. You may have to change some parts of the code (like [here](https://github.com/jts/nanopolish/blob/master/src/nanopolish_methyltrain.cpp#L241)) but I am not sure how well it will work.

Jared
