### ISSUE TITLE
Calculate Frequency Script and Supplementary Reads

### ISSUE THREAD

**Issue by vahidAK** [jts/nanopolish#835]
Hi @jts ,

I have noticed your frequency calculator script (to calculate methylation frequencies), considers supplementary reads from the same read at a given region as a separate call. For example, for a given CpG site, if there are 4 reads mapped and also 3 supplementary reads (with same read ID), during frequency calculation the script considers 3 supplementary mappings as three different calls. Is it not more reasonable to only keep one of those calls with the most significant llr for such supplementary alignments?

Thanks,
Vahid.

**Comment by jts** [comment]
Hi @vahidAK,

`nanopolish call-methylation` will process any alignments in the bam as long as their mapping quality is at least 20. If there are multiple overlapping alignments for a single read - which seems unusual to me - they will all be processed and called. If you don't want this behaviour the best way to change it is to filter the BAM file before running `call-methylation`.

Jared
