### ISSUE TITLE
Calculating event_length in eventalign

### ISSUE THREAD

**Issue by chrishendra93** [jts/nanopolish#836]
Hi, firstly thanks for developing such an awesome tool. I have been using nanopolish eventalign for most of my work with Nanopore data.

Just curious, how does nanopolish calculate the event length feature in the output for eventalign? Am I right in interpreting this as some estimate on the time it takes for the 5-mer or 6-mer to stay in the pore? 

Thank you!

**Comment by jts** [comment]
Prior to analysis the raw current signal (made up of current samples) is segmented into the "events" nanopolish uses. Each event has a duration (measured in seconds), which corresponds to the number of samples in the segment.

Jared

**Comment by chrishendra93** [comment]
Hi Jared. thanks for the reply. Let me see if I get this right, so we are assuming a constant sampling rate for the pore and this number is multiplied by the number of data points assigned to each event segment detected by nanopolish to get the event length?

Thank you

**Comment by jts** [comment]
Yes that's right, the sampling rate is constant.
