### ISSUE TITLE
New install of checkout v0.13.0 not installing eigen

### ISSUE THREAD

**Issue by navtronius** [jts/nanopolish#837]
So I had to reinstall nanopolish on a new hard drive and the new install is failing at the installing eigen step because wget https://bitbucket.org/eigen/eigen/get/3.3.7.tar.bz2 is returning a 404 error not found...

**Comment by jts** [comment]
Hi,

Eigen was moved from bitbucket to gitlab, this was fixed recently. Please try the latest commit from github rather than version 0.13.0.

Jared

**Comment by navtronius** [comment]
Done! Thanks!
