### ISSUE TITLE
Training a new model

### ISSUE THREAD

**Issue by vahidAK** [jts/nanopolish#838]
Hi @jts ,
Nanopolish uses 6-mers to call CpG methylations. I was wondering can we train a model with nanopolish using 5-mers rather than 6-mers?

Thanks,
Vahid.

**Comment by jts** [comment]
In principle yes but it would be somewhat difficult to set up the initial 5-mer model to base the training on. This is not a supported feature right now so I can't directly help but will keep it in mind next time I work on model training.

Jared

**Comment by vahidAK** [comment]
Thanks @jts
