### ISSUE TITLE
The number of 5mC sites obtained using the new(version 0.13.2) and old(version 0.11.0) versions of nanopolish is very different

### ISSUE THREAD

**Issue by guoxueyu** [jts/nanopolish#839]
Hello, I use different versions of nanopolish to call CpG sites according to the following commands, but the number of sites obtained varies greatly. Is there any filtering process in the new version ?

Thanks,
Xueyu.

Number of sites obtained using version 0.13.2      1575540
Number of sites obtained using version 0.11.0       1618763

```
nanopolish  call-methylation \
   -t 8 \
   -r my.fastq.gz \
   -b my.hg38.bam \
   -g hg38.fa \
   -w "chr1:0-248956422" > methylation_calls.tsv  &&  touch call_methylation_done

python calculate_methylation_frequency.py  -i  methylation_calls.tsv -s > methylation_calls.frequency.tsv
```

**Comment by jts** [comment]
Hi,

In v0.12 we changed some of the criteria for methylation calling. You can read about it in the last paragraph here:

http://simpsonlab.github.io/2020/03/03/nanopolish-v0.12.0/

Jared
