### ISSUE TITLE
SegFault for 'nanopolish variants --consensus' without window parameter

### ISSUE THREAD

**Issue by ChristianBrossette** [jts/nanopolish#84]
Hi,
I followed the analysis workflow on the github page, but did not apply the parallelization step over several windows/regions. Since my draft.fa is short, splitting is not necessary, thus I omitted the window parameter.
```
$ nanopolish variants --consensus r9.polished.fa -r r9.fa -b r9_sorted.bam -g draft.fa -e r9_eventalign_sorted.bam -t 4 --min-candidate-frequency 0.1 --models nanopolish_models.fofn
registering model t.007-base
registering model t.007-ONT
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
TODO: train model
TODO: filter data
[fai_fetch_seq] The sequence "" not found
Segmentation fault
```

I would prefer if the program would use the whole draft.fa file as default instead of the SegFault. Alternatively return an error message hinting to the missing parameter.

BTW: why do I get the lines
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
TODO: train model
TODO: filter data
```
for the consensus step?

**Comment by jts** [comment]
Hi Christian,

Thanks for this report, I have just made a change to support this use case. Now, if `-w` is not used it will polish/call variants on the whole genome. Note this mode is only supported when there is a single contig/chromosome in the input genome file - it is highly recommended to parallelize the polishing step in other cases.

Jared

**Comment by ChristianBrossette** [comment]
Hi Jared,
thank you for the quick reply. I will keep in mind that it only works with one contig.
But I am still curious why a VCF header is returned for the consensus step? (Maybe this will be answered by the time my run finishes)

**Comment by jts** [comment]
nanopolish prints the corrections it makes to stdout in VCF format. You should see some output by the time your run finishes.

**Comment by ChristianBrossette** [comment]
You are right, my run just finished and I wanted to write that. Thank you again! And it is always a good idea to parallelize over windows/ranges, much faster as I just found out :)
Christian
