### ISSUE TITLE
RNA pore model

### ISSUE THREAD

**Issue by pabloacera** [jts/nanopolish#840]
HI, 
Thanks for this useful tool. I was wondering how the table for RNA pore model was built 'r9.4_70bps.u_to_t_rna.5mer.template.model' Is it something provided by nanopore? or it was calculated out of some dateset?
thanks a lot!

**Comment by jts** [comment]
Hi @pabloacera,

Sorry for the slow response. The model is indeed provided by ONT:

https://github.com/nanoporetech/kmer_models/

Jared
