### ISSUE TITLE
methylation frequency script included with example set

### ISSUE THREAD

**Issue by navtronius** [jts/nanopolish#842]
Hi jts,

I have ran the methylation calling pipeline via the documentation using my own data. I was interested to know how methylation frequency is calculated using the methylation frequency script when dealing with different reads that overlap the same CpG location.  For reference, I am looking to parse out methylation frequency across each individual read instead of each individual loci.

**Comment by jts** [comment]
Hi,

Lines 44-49 are the most relevant here:

https://github.com/jts/nanopolish/blob/master/scripts/calculate_methylation_frequency.py#L44

They apply the log-likelihood threshold, then determine the methylation status depending on the direction of the log-likelihood threshold. I suggest you modify this script to have a dictionary indexed by read name and sum the total callable sites (those that pass the check on line 45) and sum the number of callable sites that have a positive llr (line 49).

I hope that helps!

Jared
