### ISSUE TITLE
conda install -c bioconda nanopolish=0.13.2 error 

### ISSUE THREAD

**Issue by q1134269149** [jts/nanopolish#843]
Hi, 
    I used conda to install nanopolish=0.13.0 with the code: _conda install -c bioconda nanopolish=0.13.0_, however, I got failed. And conda only installed the nanopolish=0.4.0. Importantly, I successfully downloaded the installation package of 0.13 version for compilation and installation. I don't know if anyone else has a similar problem.
Thanks

**Comment by druvus** [comment]
Please try `conda install -c  conda-forge -c bioconda nanopolish=0.13.0,` as bioconda depends on conda-forge. 

You may also set up channels globally to make it simplier: https://bioconda.github.io/user/install.html#set-up-channels

I would also recommend you to use seperate enviroments `conda create -n nanopolish nanopolish=0.13.0` (assuming channel are set globally)

**Comment by q1134269149** [comment]
> Please try `conda install -c conda-forge -c bioconda nanopolish=0.13.0,` as bioconda depends on conda-forge.
> 
> You may also set up channels globally to make it simplier: https://bioconda.github.io/user/install.html#set-up-channels
> 
> I would also recommend you to use seperate enviroments `conda create -n nanopolish nanopolish=0.13.0` (assuming channel are set globally)

Thanks!
