### ISSUE TITLE
Nanopolish outputs no variants seen in BAM

### ISSUE THREAD

**Issue by OgnjenMilicevic** [jts/nanopolish#844]
Greetings!
I am using Artic pipeline with a small modification of performing demultiplexing with MinKNOW, so I am not running this step. Essentially both RG vcfs are empty when I use Nanopolish, while Medaka outputs some mutations (simply by adding --medaka to the command).

I have extracted only the nanopolish command from the Artic pipeline and tried varying parameters, and none of the versions gave any variants. I clearly see them in Tablet.

One unusual thing I notice is that your documentation mentions reads in FASTA format, while Artic clearly uses FASTQ files for indexing and subsequent variant calling. Is this ok?

Also, sample name is "sample", even though SN tag in BAM is defined. Is this normal?

Printout is below:
```
Running: nanopolish index -s /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/sequencing_summary.txt -d /var/lib/minknow/data/covid19_01102020_proba/no_sample/20201001_1034_MN34605_FAO44154_820df3e9/fast5_pass/barcode01 /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/filtered_barcode01.fastq
[readdb] indexing /var/lib/minknow/data/covid19_01102020_proba/no_sample/20201001_1034_MN34605_FAO44154_820df3e9/fast5_pass/barcode01
[readdb] num reads: 163952, num reads with path to fast5: 163952
Running: minimap2 -a -x map-ont -t 4 /home/guppyuser/Program_Files/artic-ncov2019/primer_schemes/nCoV-2019/V3/nCoV-2019.reference.fasta /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/filtered_barcode01.fastq | samtools view -bS -F 4 - | samtools sort -o /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.sorted.bam -
[M::mm_idx_gen::0.004*1.45] collected minimizers
[M::mm_idx_gen::0.006*2.19] sorted minimizers
[M::main::0.006*2.18] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.006*2.05] mid_occ = 3
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.007*1.96] distinct minimizers: 5587 (99.93% are singletons); average occurrences: 1.004; average spacing: 5.332
[M::worker_pipeline::7.255*2.73] mapped 163952 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -a -x map-ont -t 4 /home/guppyuser/Program_Files/artic-ncov2019/primer_schemes/nCoV-2019/V3/nCoV-2019.reference.fasta /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/filtered_barcode01.fastq
[M::main] Real time: 7.257 sec; CPU: 19.819 sec; Peak RSS: 0.226 GB
Running: samtools index /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.sorted.bam
Running: align_trim --start --normalise 200 /home/guppyuser/Program_Files/artic-ncov2019/primer_schemes/nCoV-2019/V3/nCoV-2019.scheme.bed --report /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.alignreport.txt < /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.sorted.bam 2> /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.alignreport.er | samtools sort -T /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01 - -o /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.trimmed.rg.sorted.bam
Running: align_trim --normalise 200 /home/guppyuser/Program_Files/artic-ncov2019/primer_schemes/nCoV-2019/V3/nCoV-2019.scheme.bed --remove-incorrect-pairs --report /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.alignreport.txt < /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.sorted.bam 2> /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.alignreport.er | samtools sort -T /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01 - -o /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.primertrimmed.rg.sorted.bam
Running: samtools index /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.trimmed.rg.sorted.bam
Running: samtools index /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.primertrimmed.rg.sorted.bam
Running: nanopolish variants --min-flanking-sequence 10 -x 1000000 --progress -t 4 --reads /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/filtered_barcode01.fastq -o /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.nCoV-2019_1.vcf -b /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.trimmed.rg.sorted.bam -g /home/guppyuser/Program_Files/artic-ncov2019/primer_schemes/nCoV-2019/V3/nCoV-2019.reference.fasta -w "MN908947.3:1-29904" --ploidy 1 -m 0.15 --read-group nCoV-2019_1 
[post-run summary] total reads: 39192, unparseable: 0, qc fail: 0, could not calibrate: 159, no alignment: 19437, bad fast5: 0
Running: nanopolish variants --min-flanking-sequence 10 -x 1000000 --progress -t 4 --reads /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/filtered_barcode01.fastq -o /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.nCoV-2019_2.vcf -b /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.trimmed.rg.sorted.bam -g /home/guppyuser/Program_Files/artic-ncov2019/primer_schemes/nCoV-2019/V3/nCoV-2019.reference.fasta -w "MN908947.3:1-29904" --ploidy 1 -m 0.15 --read-group nCoV-2019_2 
[post-run summary] total reads: 39014, unparseable: 0, qc fail: 0, could not calibrate: 170, no alignment: 19338, bad fast5: 0
Running: artic_vcf_merge /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01 /home/guppyuser/Program_Files/artic-ncov2019/primer_schemes/nCoV-2019/V3/nCoV-2019.scheme.bed nCoV-2019_1:/home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.nCoV-2019_1.vcf nCoV-2019_2:/home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.nCoV-2019_2.vcf
Running: artic_vcf_filter --nanopolish /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.merged.vcf /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.pass.vcf /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.fail.vcf
Running: artic_make_depth_mask --store-rg-depths /home/guppyuser/Program_Files/artic-ncov2019/primer_schemes/nCoV-2019/V3/nCoV-2019.reference.fasta /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.primertrimmed.rg.sorted.bam /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.coverage_mask.txt
Running: artic_plot_amplicon_depth --primerScheme /home/guppyuser/Program_Files/artic-ncov2019/primer_schemes/nCoV-2019/V3/nCoV-2019.scheme.bed --sampleID /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01 --outFilePrefix /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01 /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01*.depths
Running: bgzip -f /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.pass.vcf
Running: tabix -p vcf /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.pass.vcf.gz
Running: artic_mask /home/guppyuser/Program_Files/artic-ncov2019/primer_schemes/nCoV-2019/V3/nCoV-2019.reference.fasta /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.coverage_mask.txt /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.fail.vcf /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.preconsensus.fasta
Running: bcftools consensus -f /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.preconsensus.fasta /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.pass.vcf.gz -m /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.coverage_mask.txt -o /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.consensus.fasta
Note: the --sample option not given, applying all records regardless of the genotype
Warning: Sequence "MN908947.3" not in /home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/barcode01.pass.vcf.gz
Applied 0 variants
```

Any thoughts on this problem?

**Comment by OgnjenMilicevic** [comment]
Missed variant at 241, outputted by minimap2
https://ibb.co/Js8F18t

**Comment by jts** [comment]
Hi,

Thanks for including the full output, the most relevant lines are here:

```
[post-run summary] total reads: 39192, unparseable: 0, qc fail: 0, could not calibrate: 159, no alignment: 19437, bad fast5: 0
[post-run summary] total reads: 39014, unparseable: 0, qc fail: 0, could not calibrate: 170, no alignment: 19338, bad fast5: 0
```

This means nanopolish found ~39,000 reads but discarded ~19000 (nearly 50%) because the basecalled read did not match the expected signal sufficiently well. I have just checked a recent run of ours and only 0.2% of reads fail this check. Do you know if there is a problem with the read quality for this run? What is the average quality score?

Jared

**Comment by OgnjenMilicevic** [comment]
Thanks for a prompt reply. Can you help me check that? Do I use samtools on BAM for that, or is it something that is done on FASTQ like average base score? Is there a quick way to see that? 
Sorry for a silly question!

**Comment by jts** [comment]
Try using [NanoPlot](https://github.com/wdecoster/NanoPlot), which will produce many QC plots for you to look over. If you send some I will be happy to help interpret them. If you provide it with the sequencing summary file (`/home/guppyuser/output/covid19_01102020_proba/no_sample/barcode01/sequencing_summary.txt`) it will produce a plot of the sequencing speed over time, which is very useful for debugging sequencing runs.

Jared

**Comment by OgnjenMilicevic** [comment]
I guess this is pertinent for your question: https://ibb.co/pnrkS4v
Also, for the sequencing run speed over time: https://ibb.co/wNpdQQ8
Please, teach me how to fish :)

**Comment by jts** [comment]
The quality plot looks fine, I wouldn't expect that to cause problems with nanopolish. The other plot is not the one I was looking for, it should be titled something like "Sequencing Speed over time" and the y-axis should be in base pairs per second.

**Comment by OgnjenMilicevic** [comment]
Ah, pardon. Here it is: https://ibb.co/s2qpQJx
If this is all ok, what could cause the rejection of so many reads?
And then, is it expected that the remaining reads cannot give a called variant?

**Comment by jts** [comment]
That looks fine too, I don't think is an issue with the data quality. I'm unsure what the problem is.

I notice the input file name is `filtered_barcode01.fastq` - was the filtering performed by MinKNOW, or a different method?

**Comment by jts** [comment]
Do you get any output in the `fail.vcf` files?

**Comment by OgnjenMilicevic** [comment]
After MinKnow, I used [Artic](https://artic.network/ncov-2019/ncov2019-bioinformatics-sop.html) pipeline command:
artic guppyplex --min-length 400 --max-length 700 --directory output_directory/barcode03 --prefix run_name
Fail VCF is also empty.
If it helps, I am willing to share the data with you.

**Comment by jts** [comment]
Sure, if you can package the fast5 and fastq I can take a look. It is a long weekend here and I have a few other pressing tasks so I can't promise I'll look at it quickly but I'll try

**Comment by OgnjenMilicevic** [comment]
Here are the files:
https://medbgacrs-my.sharepoint.com/:f:/g/personal/ognjen_milicevic_med_bg_ac_rs1/EpcF8O67m5RMn19T01rgqXcBuh3M4frWZvp2y6I6w3B9Jw?e=aBD6AC
It will take some hour more for fast5 upload to finish. Thanks, I am not in a hurry for results, but it would be cool if you set them for download, and at some point just tell me if you managed to extract it properly.

**Comment by rdeborja** [comment]
@OgnjenMilicevic I'm working with Jared on this and wanted to let you know I successfully downloaded both the fastq.zip and fast5.zip files.  Can you let me know the version of nanopolish and guppy you're currently using?

**Comment by OgnjenMilicevic** [comment]
Thank you for your effort.
Nanopolish 0.13.2
Guppy  4.2.2+effbaf8

**Comment by jts** [comment]
@OgnjenMilicevic can you paste the guppy commands you ran?

**Comment by OgnjenMilicevic** [comment]
$GUPPY -i $FOLD/$BC -s $OUTPUT --flowcell FLO-MIN111 --kit SQK-LSK109 --device $GPU

artic guppyplex --min-length 400 --max-length 700 --directory $OUTPUT --prefix $OUTPUT/filtered

**Comment by jts** [comment]
Thanks. `FLO-MIN111` indicates this is an R10 flowcell which nanopolish does not yet support in `master` or the tagged releases. There is an `r10` branch on github that has experimental support for R10 but it is untested on SARS-CoV-2. The fast5s don't have the pore type set (I don't know why) so the right pore type (and hence models) might not be picked up by this branch (you may have to modify the code to ensure it selects the right model):

```
ATTRIBUTE "pore_type" {
         DATATYPE  H5T_STRING {
            STRSIZE 8;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
         DATA {
         (0): "not_set"
         }
      }
```

**Comment by OgnjenMilicevic** [comment]
First of all, thank you for this great insight. I would impose on your knowledge for a bit more.
1. We would gladly test this with the r10 branch, but I am not sure I understand. What you showed us is the attribute from our fast5 showing that pore_type is not set? Or is this a correction we need to perform on your code?

2. Would you help me understand the unset pore type issue and how to further explore it. Is it usually set? How can I find out my pore type? Who could I ask about this problem further, the Nanopore support?

Thanks you so much!

**Comment by rekham1077** [comment]
@OgnjenMilicevic @jts I am having this same problem using FLO-MIN111 where I try to run nanopolish variants and get empty output. 

Looking in my bamfile I definitely have a higher number of mapped reads with high enough quality so I am not sure what the problem is. 

I'm not sure I am understanding what the best solution is. Is there an updated nanopolish version that now allows for FLO-MIN111?

**Comment by jts** [comment]
@rekham1077 can you try the `r10` branch?

**Comment by rekham1077** [comment]
@jts okay I can try that, is it different from the most updated version though?
