### ISSUE TITLE
Use fast5 files with post-basecall event data for methylation calling?

### ISSUE THREAD

**Issue by PanZiwei** [jts/nanopolish#845]
Hi,
I am trying to follow the methylation calling tutorial, but it seems that Nanopolish only accepts base-called fastq files as input. 

So is it possible to apply Nanopolish to handle single read fast5 files with post-basecall event data? If so, how can I do the process?

Thank you so much for your help!

**Comment by jts** [comment]
No sorry, you need to tell the basecaller to generate FASTQ and use the raw, unmodified fast5 files.

Jared

**Comment by PanZiwei** [comment]
> No sorry, you need to tell the basecaller to generate FASTQ and use the raw, unmodified fast5 files.
> 
> Jared

Hi Jared,
Thank you so much for your reply! So if my sample is a mixture with multiple species, is it possible to
