### ISSUE TITLE
Eventalign start and end index values for dRNA

### ISSUE THREAD

**Issue by a-sneddon** [jts/nanopolish#846]
Hi,

I was wondering if you could please help me to understand the eventalign output for dRNA.

As I understand, the signal in the raw fast5 file is 3' --> 5'.  After Eventalign generates events from the raw signal, it reverses the order of events such that they match with the reference kmers (which are ordered 5' --> 3').  However, are each individual event's samples as well as its start and end index still ordered 3' --> 5'?

For example, is the raw signal for the ref_kmer GCATT contained in the fast5 file at index positions 29623 --> 29608 (as opposed to 29608 --> 29623 as is implied by start_index and end_index)?

Example output:
contig           ref_kmer     read     event_index   start_index   end_index   samples
TranscriptA   GCATT      Read1     63            29608         29623       92.8683,88.3946,84.4002,85.0394,
TranscriptA   CATTC      Read1     64            29599         29608       99.0996,94.6259,99.8985,94.3063,
TranscriptA   CATTC      Read1     65            29587         29599       93.827,96.5432,92.2292,91.5901,1
TranscriptA   CATTC      Read1     66            29573         29587       86.4773,87.5958,88.2349,95.7443,
TranscriptA   ATTCC      Read1     67            29566         29573       75.9322,78.4886,80.4059,81.5243,
TranscriptA   TTCCT      Read1     68            29553         29566       70.6596,69.3814,72.4171,70.9791,
TranscriptA   TCCTA      Read1     69            29539         29553       75.9322,72.5769,73.0562,70.9791,
TranscriptA   TCCTA      Read1     70            29521         29539       91.7499,94.6259,99.5789,102.135,
TranscriptA   CTAAT      Read1     71            29511         29521       100.857,101.816,99.5789,101.336,
TranscriptA   TAATG      Read1     72            29501         29511       101.656,109.006,108.526,116.515,
TranscriptA   AATGC      Read1     73            29452         29501       85.0394,91.7499,86.6371,89.6728,
TranscriptA   ATGCT      Read1     74            29440         29452       89.5131,88.7142,91.4304,89.5131,
TranscriptA   ATGCT      Read1     75            29433         29440       85.998,82.8025,87.5958,78.6483,8
TranscriptA   ATGCT      Read1     76            29420         29433       90.7913,95.4248,89.3533,80.7254,
TranscriptA   ATGCT      Read1     77            29402         29420       96.703,95.1052,87.2762,

I am also wondering why the event_index remains in ascending order if the order of events has been reversed?

Thanks for your help and please let me know if you have any questions.

Thanks,
Alex

**Comment by jts** [comment]
Hi Alex,

Sorry for the slow response.

There's quite a lot of coordinate flipping in the direct RNA workflow so I always have to re-familiarize myself with the code...I hope I got it right to answer your questions:

> As I understand, the signal in the raw fast5 file is 3' --> 5'

This is correct

> However, are each individual event's samples as well as its start and end index still ordered 3' --> 5'?

Yes, I believe this is correct. When the event sequence is flipped to be 5' -> 3' the start time/length members within each event are not flipped:

https://github.com/jts/nanopolish/blob/master/src/nanopolish_squiggle_read.cpp#L346

When nanopolish retrieves the sample range it uses the start time/length members:

https://github.com/jts/nanopolish/blob/master/src/alignment/nanopolish_eventalign.cpp#L468
https://github.com/jts/nanopolish/blob/master/src/nanopolish_squiggle_read.cpp#L1109

> I am also wondering why the event_index remains in ascending order if the order of events has been reversed?

event_index in this context is just the index into nanopolish's event vector:

https://github.com/jts/nanopolish/blob/master/src/nanopolish_squiggle_read.h#L277

I could see the argument for making this is in the original 3' -> 5' direction but it's too late to change I think.

Jared

**Comment by a-sneddon** [comment]
Hi Jared,

Thank you for clarifying, that makes sense.  Happy to close this issue now.

Thanks,
Alex
