### ISSUE TITLE
Makefile:95: recipe for target 'eigen/INSTALL' failed make: *** [eigen/INSTALL] Error 8

### ISSUE THREAD

**Issue by dikshyantg** [jts/nanopolish#847]
Hi I was trying to install the latest version of nanopolish but I get this  error .
Makefile:95: recipe for target 'eigen/INSTALL' failed
make: *** [eigen/INSTALL] Error 8

**Comment by jts** [comment]
Do you still have this problem? The EIGEN repository recently moved but I believe is now fixed in the most recent commits on github.

Jared

**Comment by daanverhagen** [comment]
hi,  i just wanted to mention that im encountering the same issue when installing the latest version. 

As far as i can tell it tries to connect to bitbucket.org/eigen/eigen/get/3.2.5.tar.bz2 and then returns an error 301 Moved Permanently. after that it sends an HTTP request which results in 404 not found. 

final lines are similar to @dikshyantg

**Comment by MustafaElshani** [comment]
I can confirm that this problem persists even with the changes to Makefile bitbucked to gitlab for eigen.

For some reason the installation after hdf5 reverts the Makefile back to bitbucked, strange

**Comment by jts** [comment]
@daanverhagen the cpggpc_new_train branch will still point to the old link (bitbucket). I'll try to port that change after the holidays. For now if you compile first from `master`, then switch to `cpggpc_new_train` it should work.  @MustafaElshani is this the same problem for you?

**Comment by MustafaElshani** [comment]
Just tested, it works from `master` the problem persists when using cpggpc_new_train branch

**Comment by jts** [comment]
when on the cpggpc_new_train branch try this:

```
git checkout master -- Makefile
```

**Comment by MustafaElshani** [comment]
the problem persists in `cpggpc_new_train` additionally same problem in` master `when dictating version  `git checkout v`

**Comment by miwolff** [comment]
Hi everyone,

I also wanted to use the cpggpc_new_train branch. Thanks to the infos here I got it to run with the following steps:

1) clone the repo
2) git checkout cpggpc_new_train
3) git checkout master -- Makefile
4) make

First compiling the master branch, switching to cpggpc_new_train and doing make again did not work.

**Comment by jts** [comment]
Hi @miwolff (and others in this thread),

Just a note that we've created a new branch `nanonome` that ports the changes in the cgpgpc_new_train branch to the HEAD of nanopolish so its consistent with the latest version.

Jared

**Comment by wdecoster** [comment]
Hi Jared,

Are there plans to merge the nanonome branch into main soon? Or should we keep on using the branch for nanonome data?

Thanks,
Wouter

**Comment by wdecoster** [comment]
Alright, thanks! Besides using that branch, do you have any other recommendations for the analysis of nanonome-seq data?
(perhaps this fits better in a separate issue, but now we're here...)
