### ISSUE TITLE
Questions for methylation_calls.tsv 

### ISSUE THREAD

**Issue by PanZiwei** [jts/nanopolish#848]
To whom it may concern,
I have a question on the methylation_calls.tsv after Nanopolish methylation calling step. 

1. Can you explain more about the column "num_calling_strands"?

2. Since you have mentioned before that you utilize **log_lik_ratio** to make a binary methylation call at each mapped read, does it mean that for a specific site in a single read, the site will be considered as methylated as long as the |log_like_ratio| >=2.0? 

3. If there are M sites detected in methylation_calls.tsv and N sites' |log_like_ratio| >=2.0, can I say that N/M sites are methylated? Or I should first get the real sites of CG sites since different reads may detect sites of the same location, so the methylated sites should be M'/N'?(M': unique CG sites; N': unique CG sites that whose  |log_like_ratio| >=2.0)? If so, how can I remove the redundant sites?

Thank you so much for your help!

**Comment by jts** [comment]
Hi,

Sorry for the slow response.

1. Older nanopore sequencing kits allowed sequencing both strands of each molecule ("2D sequencing"). For this mode of sequencing, the methylation calls for each strand were merged and `num_calling_strands` was 2. All sequencing is now "1D" so this column will always be 1.

2. Not quite, it means the site will be called as methylated or unmethylated if `|log_lik_ratio| >= 2.0`. If `|log_lik_ratio| < 2.0` it will be ignored as ambiguous (not called). The site will be considered methylated when `log_lik_ratio > 2` and unmethylated when `log_lik_ratio < 2`.

3. We provide a script to process the methylation_calls.tsv file: https://github.com/jts/nanopolish/blob/master/scripts/calculate_methylation_frequency.py. You can parse the output tsv to calculate proportion of methylated sites after accounting for ambiguous sites as described above.

Let me know if any of this is unclear

Jared
