### ISSUE TITLE
read_names alignment/repeat issue

### ISSUE THREAD

**Issue by navtronius** [jts/nanopolish#849]
I was processing the methylation_calls.tsv folder and running my own scripts on the data. It seems as if the read_names are not unique? I am getting the same read_name id for one chromosome and another on a different chromosome, with different sizes between the read_name ids, so I'm assuming they are different strands of DNA completely. Are any of you aware of whether or not read_name ids are unique or are they recycled?

**Comment by jts** [comment]
Hi,

The read names are unique but nanopolish will output methylation calls for all high quality mappings for each read. I suspect if you check the input BAM you’ll find multiple alignments for these reads.

Jared

**Comment by navtronius** [comment]
Thank you for pointing that out! I was following the Quick Start Methylation Calls guide with my own dataset and got multiple alignments for some reads... has anyone tried using minimap2 with more stringent settings such as -x ava-ont to reduce the number of multiple alignments?

**Comment by navtronius** [comment]
Went through the bam file, some redundant alignments will have the same quality, but one will have 1000+ mismatches, but is still high enough quality to pass. Will need to make a decision on what reads to keep....

**Comment by jts** [comment]
Alignments with mapQ >= 20 will be used, others will be ignored.

`minimap2 -x ava-ont` is intended for calculating overlaps between reads and should not be used for aligning reads to a reference genome.

Jared

**Comment by navtronius** [comment]
--secondary=no seems to be the minimap2 option needed, but I'm running into some errors from it. Once that is worked out this should be resolved.
