### ISSUE TITLE
nanopolish: src/alignment/nanopolish_anchor.cpp:141: HMMRealignmentInput build_input_for_region(const string&, const string&, const Fast5Map&, const string&, int, int, int, const string&): Assertion `template_idx != -1 && (!sr.has_events_for_strand(C_IDX) || complement_idx != -1)' failed.

### ISSUE THREAD

**Issue by JohnUrban** [jts/nanopolish#85]
Hi,

We recently MinION sequenced a plasmid, which was massive overkill, but fun.

I assembled it in Canu and want a better consensus. It is 7.2 kb.

I did this:
```
nanopolish extract --type 2d pass/ > pass.nanopolish.fa
G=../plasmid-highcov.contigs.fasta
bwa index $G
I=$G
R=pass.nanopolish.fa
bwa mem -M -x ont2d $I $R -t 8 | samtools sort | samtools view -F 4 -q 60 -bSh - > pass.nanopolish.bam 
samtools index pass.nanopolish.bam 
nanopolish consensus -r pass.nanopolish.fa -b pass.nanopolish.bam -g $G -o plasmid.asm.nanopolish.fasta --models-fofn nanopolish_models.fofn -w tig00000000:0:7120 -t $T
```

I got this:
```
nanopolish: src/alignment/nanopolish_anchor.cpp:141: HMMRealignmentInput build_input_for_region(const string&, const string&, const Fast5Map&, const string&, int, int, int, const string&): Assertion `template_idx != -1 && (!sr.has_events_for_strand(C_IDX) || complement_idx != -1)' failed.
```

Do you have any insight into what I can do to get past this error?

Many thanks,

  John

**Comment by JohnUrban** [comment]
p.s. I am using the latest code on github -- just cloned and installed today.

**Comment by jts** [comment]
Hi John,

`nanopolish consensus` has been rewritten in the `nanopolish variants` module. Could you run the new version using the instructions here:

https://github.com/jts/nanopolish#computing-a-new-consensus-sequence-for-a-draft-assembly

Let me know how it goes.

Jared

**Comment by JohnUrban** [comment]
Thanks Jared.
It has been running for ~1 hour, so I am guessing it is doing its thing.

It is a 7.2 kb sequence with 4000x coverage (I know - total overkill).
Any ideas on how long it might run for?

**Comment by JohnUrban** [comment]
It finished in 4-5 hours. Thanks for the putting me in the right direction.

**Comment by jts** [comment]
Thanks for the update. The long runtime is (partially) caused by the excessive depth. I'm not sure if having 4000x will effect accuracy but I suggest you have a careful look at the results.

**Comment by JohnUrban** [comment]
If I have a chance I will look into the effects of using lower coverage. For now it did improve the consensus and we are reasonably comfortable with it. The experimental homopolymer fix helped a bit too.

Below are BLAST alignments so the identities are the local pct id.
BLAST of various assemblies 

Canu output: Identities = 7078/7189 (98.5%), Gaps = 107/7189 (1.5%)

Nanopolished asm: 
Identities = 7143/7199 (99.2%), Gaps = 48/7199 (0.7%)

Nanopolished asm – fixed homopolymers: 
Identities = 7150/7199 (99.3%), Gaps = 40/7199 (0.6%)

**Comment by jts** [comment]
99.3% is a bit disappointing, is this R9 data?

**Comment by JohnUrban** [comment]
It is R9 yeah. I could share it with you if you'd like, along with the expected plasmid sequence (from Sanger sequencing once upon a time). We just threw it on a flow cell with other stuff to see if the sequence is still the same as was on record. I have separated out the fast5s that seem to be from the plasmid by taking those that had BLAST alignments to the plasmid sequence. Perhaps it could be filtered a little better (e.g. requiring long blast alignments) before trying to assemble and polish. I'd experiment a little more myself, but I was doing this for a friend in the lab who seems to be satisfied with the answer and need to get back to thesis writing. You're welcome to explore it more if you want, though I am sure you have much of your own data for that.

**Comment by jts** [comment]
Sure, having the data would be helpful. No rush though because I'm pretty busy these days so might not get to it for awhile. In the meantime, could you paste a screenshot of the blast alignment so I can see where the errors are?

**Comment by JohnUrban** [comment]
It is long enough where I'd have to take a few screen shots. I tried attaching the txt file instead. Let me know the best way to share the data.


[pFRTmyc6xERE-nanopolish-fix.blast.txt](https://github.com/jts/nanopolish/files/588040/pFRTmyc6xERE-nanopolish-fix.blast.txt)
