### ISSUE TITLE
--window option does not work in nanopolish eventalign

### ISSUE THREAD

**Issue by vahidAK** [jts/nanopolish#851]
Hi @jts ,
I want to align signals for a region of the genome but I have noticed -w option does not work and it starts aligning from chr1:
`~/Software/nanopolish_v13.2/nanopolish/nanopolish eventalign -t 5 -q 20 --reads nanopore.fastq --bam nanopore.bam --genome hg38.fa --print-read-names --samples --signal-index --window chr11:100000-109500 | more `  

Here is the output:

![image](https://user-images.githubusercontent.com/46334063/97114167-1c4e1f80-16ac-11eb-91d8-61139f20f62f.png)  

Thanks,
Vahid.

**Comment by jts** [comment]
Hi,

The coordinates are a positional argument for `eventalign`. If you change your command to this it should behave as expected:

```
~/Software/nanopolish_v13.2/nanopolish/nanopolish eventalign -t 5 -q 20 --reads nanopore.fastq --bam nanopore.bam --genome hg38.fa --print-read-names --samples --signal-index chr11:100000-109500
```

I intend to change it to be consistent with other modules (https://github.com/jts/nanopolish/issues/722)

Jared

**Comment by vahidAK** [comment]
Thanks, @jts 
it works now
