### ISSUE TITLE
Nanopolish taking too long to run 

### ISSUE THREAD

**Issue by vappiah** [jts/nanopolish#855]
I have  5.6MB Draft Asssemby which I am polishing with nanopolish. The script has been running for over 24 hours and  is still running. Is it normal for nanopolish to take that long? or there is something I am doing wrong.  Below is the code which is taking long to run

_python3 nanopolish_makerange.py draft.fa | parallel --results nanopolish.results -P 8 \
    nanopolish variants --consensus -o polished.{1}.vcf -w {1} -r reads.fa -b reads.sorted.bam -g draft.fa -t 4 --min-candidate-frequency 0.1_

**Comment by jts** [comment]
Hi,

Can you provide more details, like:

-The specifications of the computer you are using
-How much coverage you have

Jared

**Comment by jotes35** [comment]
Hi @jts  I use a 36 core Dell Poweredge Server with over 200GB RAM. I am running centos 7.
With regards to the coverage I am a bit confused confused. can you elaborate? (I am new to this of analysis)

**Comment by jts** [comment]
How many bases of sequencing data did you collect for the 5.6Mb genome?

**Comment by jotes35** [comment]
Below is the info

**Contig    No. of bases**
contig_1 | 462689
contig_2 | 30507
contig_3 | 75080
contig_4 | 227207
contig_5 | 520289
contig_6 | 35990
contig_7 | 1423117
contig_8 | 1646993
contig_9 | 958717
contig_10 | 361196
contig_11 | 577

**Comment by jts** [comment]
Sorry, that's not quite what I meant - how many bases are in the input sequencing reads?

Jared

**Comment by jotes35** [comment]
Below is the info

**Contig | No. of bases**
contig_1 | 462689
contig_2 | 30507
contig_3 | 75080
contig_4 | 227207
contig_5 | 520289
contig_6 | 35990
contig_7 | 1423117
contig_8 | 1646993
contig_9 | 958717
contig_10 | 361196
contig_11 | 577
