### ISSUE TITLE
High numbers of 'couldn't calibrate' and 'no alignment' reads.

### ISSUE THREAD

**Issue by janderson94** [jts/nanopolish#856]
Hi,

I'm using nanopolish variants on sequenced small amplicons (~150-250BP). In general the resulting genotype calls match a lot of our expectations, but we've noticed we're losing quite a few reads (on average ~50%), to "couldn't calibrate" and "no alignment". I saw in another issue that "couldn't calibrate" errors may stem from short reads, but not sure if you have any suggestions for a work around as we really are limited to short reads in this application. Second, its strange to see many "no alignment" calls when we are providing an aligned bam file alongside indexed fastq + raw fast5. So in theory the only reads used for variant calling should be ones that mapped to the genome. Any advice on these issues is greatly appreciated!

Best,
Jordan

**Comment by jts** [comment]
Hi Jordan,

The "no alignment" message refers to the internal signal-to-read alignment nanopolish computes to anchor the signal data. If this alignment fails QC, the read will be discarded with the "no alignment" message.

I haven't tried to optimize these thresholds for very short reads but if you're keen to try the relevant thresholds are here:

https://github.com/jts/nanopolish/blob/master/src/nanopolish_raw_loader.cpp#L369
https://github.com/jts/nanopolish/blob/master/src/nanopolish_squiggle_read.cpp#L405

Keep an eye on the genotype accuracy though to make sure loosening these thresholds isn't detrimental to the downstream application.

Jared

**Comment by janderson94** [comment]
Hi Jared, 

Thanks for the quick reply! I'll take a look at those and potentially try tweaking them.

Best,
Jordan
