### ISSUE TITLE
associating eventalign output with raw signal?

### ISSUE THREAD

**Issue by jessicam1** [jts/nanopolish#858]
I would like to associate the output of eventalign (specifically the events) with the corresponding “chunks” of the raw signal in the fast5 files. Any suggestions on how can I do this?

**Comment by jts** [comment]
Hi @jessicam1,

If you pass the `--samples` option it will write out the current observations for the event:

https://github.com/jts/nanopolish/blob/master/src/alignment/nanopolish_eventalign.cpp#L71

Jared

**Comment by jessicam1** [comment]
> Hi @jessicam1,
> 
> If you pass the `--samples` option it will write out the current observations for the event:
> 
> https://github.com/jts/nanopolish/blob/master/src/alignment/nanopolish_eventalign.cpp#L71
> 
> Jared

This worked great, thank you.
