### ISSUE TITLE
Correlation calculation

### ISSUE THREAD

**Issue by XINYAN2** [jts/nanopolish#859]
Hi, 

I noticed that in Nanopolish's output, methylation results of '-' strand C site are summed into '+' strand for each CG site. Is there any reason for not splitting strand? Because when I split strand and calculate correlation, correlation score drops.

**Comment by XINYAN2** [comment]
And also, are you including those positions with reported methylation frequency = 0 into correlation calculation?

**Comment by jts** [comment]
Hi,

If you'd like strand-specific calls you can split the input calls file on the "strand" column then run `calculate_methylation_frequency.py` on the per-strand files. I suspect correlation is a little lower when splitting by strand as you would have half the sequence depth for each strand, so the noise will increase.

I believe methylation frequency = 0 calls should be included in the correlation calculation.

Jared

**Comment by XINYAN2** [comment]
Hi Jared,

Thanks a lot for your help.
