### ISSUE TITLE
modified contig?

### ISSUE THREAD

**Issue by EHC2019** [jts/nanopolish#860]
Hi,
I am trying to run nanopolish on a modified canu output of S. cerevisia. I got from canu more than 1 round of mitochondria so I tried to trim the contig before running nanopolish. It gave a "faidx could not get contig length" for the trimmed contig. How can I overcome that? I saw the amplicon option on a previous ticket but I wish to polish all genome not just the mitochondria. 

Thanks!

**Comment by jts** [comment]
Hi,

If you modified the contig file after the .bam or .fai file were generated, you will need to delete those and re-generate them.

Jared
