### ISSUE TITLE
nanopolish index:  Error: no fast5 files found

### ISSUE THREAD

**Issue by wanjinhu** [jts/nanopolish#861]
Hi there,

when i run 'nanopolish index -d', did i have to get the fasta5 file ?  cause i just have the fastq file, but i want to run 'nanopolish eventalign' command to save a tsv file and the event values scaled towards the model. 

i mean do i have to get the fasta5 file ?

**Comment by jts** [comment]
Hi,

Yes you need the fast5s for nanopolish.

Jared
