### ISSUE TITLE
Theoretical model info

### ISSUE THREAD

**Issue by amitblum** [jts/nanopolish#862]
Hello, 
Do you have the theoretical model info for direct RNA sequencing? 
I.e. the mean and stdv for each 5-mer?

Thanks
Amit

**Comment by jts** [comment]
The RNA model is here:

https://github.com/nanoporetech/kmer_models/tree/master/r9.4_180mv_70bps_5mer_RNA

**Comment by amitblum** [comment]
Is it depends of nanopolish version?
Which model is used in nanopolish>0.13?

Thanks

**Comment by jts** [comment]
All versions of nanopolish use the same RNA model.
