### ISSUE TITLE
Polishing scaffolds

### ISSUE THREAD

**Issue by vappiah** [jts/nanopolish#865]
Hello @jts 

I generated scaffolds from my draft assembly  by reordering the contigs against a reference genome. Is it possible to polish the scaffolds  with nanopolish instead of the draft assembly contigs?

**Comment by jts** [comment]
Hi,

Yes you should be able to just use the reordered contigs as input, rather than the draft assembly.

Jared

**Comment by jotes35** [comment]
Thanks. Just a confirmation . The scaffold has just one sequence in it .
