### ISSUE TITLE
error: adjacent polishing windows do not overlap

### ISSUE THREAD

**Issue by vappiah** [jts/nanopolish#866]
Dear @jts 

I had this error message when running nanopolish. 

[post-run summary] total reads: 10833, unparseable: 0, qc fail: 3, could not calibrate: 74, no alignment: 569, bad fast5: 3
Number of variants in span (11) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (10) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (13) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
Number of variants in span (12) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!
[post-run summary] total reads: 11023, unparseable: 0, qc fail: 7, could not calibrate: 35, no alignment: 540, bad fast5: 3
error: adjacent polishing windows do not overlap (100000-150200 and 200000-250200)
error: one or more polishing windows are missing. Please check that all nanopolish variants --consensus jobs ran to completion

**Comment by jts** [comment]
Hi,

One of the polishing jobs - probably `150000-200200` - failed, which caused this error. The most probable reason is that it ran out of memory. You'll need to check for this and re-run the failed job, then run `nanopolish vcf2fasta`.

Jared
