### ISSUE TITLE
discrepancy between eventalign samples and fast5 datasets

### ISSUE THREAD

**Issue by jessicam1** [jts/nanopolish#867]
Hi,

It is my understanding that when running Nanopolish with the --samples option, I get the "chunks" of signal for each Kmer in the output file. Theoretically, if I throw all of these samples for each Kmer in one read into an array, it should contain all of the signal data for the read. However, when I do this, the size of my eventalign samples array is much larger than the size of the array for the corresponding fast5 dataset and the values are different as well.  I expected the eventalign samples and the signal data in the fast5 files to be the same length and values. Am I understanding this correctly or am I missing something? 

Thanks!

**Comment by jts** [comment]
Hi @jessicam1,

I agree that is unexpected. Could you provide an example?

Jared
