### ISSUE TITLE
no. of reads in index and output after event align mismatch

### ISSUE THREAD

**Issue by callumparr** [jts/nanopolish#868]
I ran eventalign on a direct RNA sample using transcriptome reference and without secondary mappings. I had around 1.8M input reads but the final log output recorded over 3M reads? I was wondering if this difference is something to worry about.

```
[post-run summary] total reads: 3096274, unparseable: 0, qc fail: 27760, could not calibrate: 26334, no alignment: 4741, bad fast5: 0
Mouse_aging/nanopolish/nanopolish_eventalign.sh.e1992206 (END)
```

Also the output is around 250Gbp. Is this expected size? I will use as input for https://github.com/GoekeLab/xpore I guess the dataprep stores this information in a more concise HDF5 format.

**Comment by jts** [comment]
Hi @callumparr,

The output line is a little misleading - it counts the number of alignments in the input BAM, not the number of unique reads. Does that explain the difference?

Jared

**Comment by callumparr** [comment]
Is it the sum of the mappings in the BAM file and then no. of matched fast5 files. If so it would agree somewhat minus plus some filtering. 

From mapping 1,545,383 pass QC FASTQ reads (total sequenced reads was 1,801,807 and matches the fastq.index.readdb)

Primary alignments = 1,488,526 and there were 59,565 supplementary alignments

```
1604948 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
59565 + 0 supplementary
0 + 0 duplicates
1548141 + 0 mapped (96.46% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
Mouse_aging/alignments/Y2.bam.flagstat (END)
```
total no. of alignments and no mappings is equal to line no. in BAM. I still confused why I get over 3M reads in the eventalign file. 

I am not sure if things were complicated by the fact that after live basecalling I put all the fast5 files back into one single folder again and rebasecalled with high accuracy mode but used a FASTQ only containing pass reads for `nanopolish index`.

**Comment by jorgcalis** [comment]
I have a similar question, with 718 mapped reads in the input bam file; and exactly twice (n=1436) that number as total read count in the post-run summary. Maybe somewhere the reads are counted twice?

**Comment by jts** [comment]
Thanks @jorgcalis, you're right there was a double-count in the post-run QC line
