### ISSUE TITLE
faidx could not get contig length 

### ISSUE THREAD

**Issue by qingyyyy** [jts/nanopolish#869]
I am doing the nanopolish variants for the variant calling of the amplicon fastq file. My reference file is the contig fasta, and the error shows that the faidx could not get the contig length of "contig1: 1-xxx". I am confused with this, and my command is as follows: 

nanopolish variants --min-flanking-sequence 10 -x 1000000 --progress -t 4 --reads barcode02.fastq -o barcode02.2.vcf -b barcode02.bam -g LPS_lpg0777.reference.fasta -w "4658:1-1035" --ploidy 1 -m 0.15 --read-group 2 

Btw I did the nanopolish index in the first step, and it worked well

**Comment by jts** [comment]
Hi,

Can you paste the exact error message, directly from nanopolish?

Jared

**Comment by vappiah** [comment]
I got a similar message when doing nanopolish. Below is the exact error message

faidx could not get contig length for contig contig_1

**Comment by jts** [comment]
@vappiah it looks like it is continually trying to build the `.fai` file and failing (from the `[fai_load] build FASTA index`). Do you have write permission to the location where the contigs are stored? I suggest trying to run `samtools faidx assembled_genome.fasta` before nanopolish, where `assembled_genome.fasta` is where you are passing in `-g`.

Jared

**Comment by vappiah** [comment]
@jts I have permission.
The assembled genome and the reads are all in the same folder and I even cd to that folder. I even realized the the .fai is already created there

**Comment by jts** [comment]
@vappiah is this still an issue or can I close this?

**Comment by vappiah** [comment]
@jts I have resolved the issue. Thanks

**Comment by jts** [comment]
Glad to hear it.
