### ISSUE TITLE
Nanopolish eventalign Error: unknown model:

### ISSUE THREAD

**Issue by LCrossman** [jts/nanopolish#87]
Hi,
I'm a bit puzzled about-  Error: unknown model:
after running nanopolish eventalign.  I have the r9-models in the working folder with reads and have specified the directory for the file nanopolish_models.fofn.  The files in that directory look to be fine. I extracted the fasta of the reads with poretools previously and have the correct path to the reads (note there are some spaces in the path name unfortunately).
I previously ran nanopolish 4 fine, this is my first run of nanopolish 5 which was installed by home-brew on mac OS X, it seems to have installed and be running fine.  Any suggestions?
Thanks

**Comment by jts** [comment]
Hi,

Could you post the exact command you tried to run?

Thanks,
Jared

**Comment by LCrossman** [comment]
bwa mem -x ont2d -t 8 All12May_24May-erate-0.025.contigs.fasta All_the_Siobreads.fasta | samtools view -Sb - | samtools sort -f - reads.sorted.bam

this ran fine, although it didn't seem to merge all the bam files throwing up an error about not finding reads.sorted.bam.0000 but the file was called reads.sorted.bam.0000.bam so I ran samtools merge to create a merged bam from the unmerged files.
Also repeated but the same thing happened.  I indexed and looked at the merged bam file in Artemis and it looked fine.  Also a good size.

nanopolish eventalign -t 8 --sam -r All_the_Siobreads.fasta -b reads.sorted.bam -g All12May_24May-erate-0.025.contigs.fasta --models-fofn r9-models/nanopolish_models.fofn
(then changed the fasta files to fa)
or
nanopolish eventalign -t 8 --sam -r All_the_Siobreads.fa -b reads.sorted.bam -g All12May_24May-erate-0.025.contigs.fa --models r9-models/nanopolish_models.fofn
or
nanopolish eventalign -t 8 --sam -r All_the_Siobreads.fa -b reads.sorted.bam -g All12May_24May-erate-0.025.contigs.fa --models-fofn nanopolish_models.fofn

I do have 8 threads.  samtools 0.1.19 in path, also tried samtools 1.3

-rw-r--r--  1 lisacrossman  admin  791328827 22 Nov 10:36 All_the_Siobreads.fa
-rw-r--r--  1 lisacrossman  admin   11792261 22 Nov 10:40 All12May_24May-erate-0.025.contigs.fa
-rw-r--r--  1 lisacrossman  admin  416579933 22 Nov 11:22 reads.sorted.bam
drwxr-xr-x  5 lisacrossman  admin        170 22 Nov 11:36 r9-models
-rw-r--r--  1 lisacrossman  admin     304968 22 Nov 13:46 reads.sorted.bam.bai
-rw-r--r--  1 lisacrossman  admin    2918678 22 Nov 13:47 All12May_24May-erate-0.025.contigs.fa.pac
-rw-r--r--  1 lisacrossman  admin   11674804 22 Nov 13:47 All12May_24May-erate-0.025.contigs.fa.bwt
-rw-r--r--  1 lisacrossman  admin        945 22 Nov 13:47 All12May_24May-erate-0.025.contigs.fa.ann
-rw-r--r--  1 lisacrossman  admin         13 22 Nov 13:47 All12May_24May-erate-0.025.contigs.fa.amb
-rw-r--r--  1 lisacrossman  admin    5837408 22 Nov 13:47 All12May_24May-erate-0.025.contigs.fa.sa
-rw-r--r--  1 lisacrossman  admin        247 22 Nov 14:29 All12May_24May-erate-0.025.contigs.fa.fai
-rw-r--r--  1 lisacrossman  admin      18286 22 Nov 15:01 nanopol.hist

Cheers

**Comment by jts** [comment]
Hi,

You should copy the files from r9-models into the working directory, it isn't enough to copy the full directory:

```
cp /path/to/nanopolish/etc/r9-models/* .
```

**Comment by LCrossman** [comment]
Hi, I think that is it, thanks heaps.

except now I have difficulties with the spaces in the path name as it is asking for a path which is part of the name but I'll fiddle about with the pathnames and change all the names in the read .fa

**Comment by jts** [comment]
nanopolish 0.6 no longer requires the `--models` argument so I'm closing this issue
