### ISSUE TITLE
git clone failed

### ISSUE THREAD

**Issue by super-teng** [jts/nanopolish#871]
When I  git clone --recursive https://github.com/jts/nanopolish.git

Cloning into 'nanopolish'...
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (29/29), done.
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

help me thanks

**Comment by jts** [comment]
This isn't an error I can help with, it looks like a problem with your connection to github, sorry.
