### ISSUE TITLE
Segmentation fault error

### ISSUE THREAD

**Issue by skambha6** [jts/nanopolish#872]
Hi,

I'm trying to use nanopolish (version 0.13.2) to call methylation for some GM12878 data. The indexing has completed successfully, but I'm running into the following error with the call-methylation command.

Running the following command:
../nanopolish/nanopolish call-methylation -t 10 -r /GM12878/fastq/gm12878.fastq -b /GM12878/bam/gm12878_chr22.sorted.bam -g hg38.fa > /GM12878/nanopore/gm12878_methylation_calls.tsv

results in the following error:
/var/spool/slurm//job47029503/slurm_script: line 23:  7624 Segmentation fault      ../nanopolish/nanopolish call-methylation -t 10 -r /GM12878/fastq/gm12878.fastq -b /GM12878/bam/gm12878_chr22.sorted.bam -g hg38.fa > /GM12878/nanopore/gm12878_methylation_calls.tsv

with the following job information:
Nodes: 1
Cores per node: 22
CPU Utilized: 04:52:06
CPU Efficiency: 8.29% of 2-10:45:08 core-walltime
Job Wall-clock time: 02:40:14
Memory Utilized: 1.68 MB
Memory Efficiency: 0.00% of 105.62 GB

With 22 cpu nodes requested, this same error occurs when 10 or 20 threads are specified with the call-methylation command. Some methylation calls are generated in the methylation_calls.tsv file but the calling finishes prematurely. 

Any advice about how to resolve this issue would be greatly appreciated. Thanks!

**Comment by jts** [comment]
Hi,

That's odd, I haven't seen a segmentation fault in the middle of the run. Could you try to see if it runs to completion on the test data [here](https://nanopolish.readthedocs.io/en/latest/quickstart_call_methylation.html)? if it does, I'll need you help isolating the single read that causes the segfault.

Jared

**Comment by skambha6** [comment]
Hi,

It looks like that nanopolish runs to completion on the test data. How would you suggest isolating the single read that causes the segfault? Does nanopolish process reads sequentially? t seems that the output tsv file is sorted by genomic position rather than read. Here are the last few lines of the output methylation calls file for example (run with the command copied in my initial post):
<img width="990" alt="Screen Shot 2021-01-20 at 10 28 45 AM" src="https://user-images.githubusercontent.com/51316814/105218768-6b201f80-5b0a-11eb-973b-3fdc52750f2c.png">

Thank you for your help!
Sandeep

**Comment by jts** [comment]
Sorry for the slow reply. To isolate the problematic read I would suggest to start with a wide window (for example `-w chr22:1-50,000,000`) then bisect the region to narrow it done to a handful of reads that cause the problem.

Jared
