### ISSUE TITLE
Nanopolish variants Aborted (core dumped)

### ISSUE THREAD

**Issue by gezthxbio** [jts/nanopolish#873]
I got this error "Aborted (core dumped)" while running https://artic.network/ncov-2019/ncov2019-bioinformatics-sop.html 
```
artic minion --normalise 200 --threads 4 --scheme-directory ~/artic-ncov2019/primer_schemes --read-file run_name_barcode03.fastq --fast5-directory path_to_fast5 --sequencing-summary path_to_sequencing_summary.txt nCoV-2019/V3 samplename
```
Platform : minION
Protocol: PCR Tiling
Primer: artic primers 
Demultiplexing was performed by minKNOW.

```
nanopolish variants --min-flanking-sequence 10 -x 1000000 --progress --reads COVID_17_12_2020_barcode02.fastq -o barcode02.nCoV-2019_1.vcf -b barcode02.trimmed.rg.sorted.bam -g artic-ncov2019/primer_schemes/nCoV-2019/V3/nCoV-2019.reference.fasta -w "MN908947.3:1-29904" --ploidy 1 -m 0.15 --read-group nCoV-2019_1
```

**Comment by jts** [comment]
Hi,

The usual cause would be running out of memory. Can you provide some details of the computer you’re using (OS, amount of RAM, CPUs, etc)?

Jared

**Comment by gezthxbio** [comment]
OS: Centos 8.2
CPU : 28 x 2 = 56 threads
RAM : 288 GB

**Comment by jts** [comment]
Ok, it is not memory then. Can you paste the complete set of error messages printed to the terminal, and also the messagesif you just run the `nanopolish variants` command on its own?

**Comment by gezthxbio** [comment]
```
/home/gxavier/ST/downldtemp/nanopolish/nanopolish variants --min-flanking-sequence 10 -x 1000000 --progress --reads COVID_17_12_2020_barcode02.fastq -o barcode02.nCoV-2019_1.vcf -b barcode02.trimmed.rg.sorted.bam -g /Compute/CovidSeq/minION/artic-ncov2019/primer_schemes/nCoV-2019/V3/nCoV-2019.reference.fasta -w "MN908947.3:1-29904" --ploidy 1 -m 0.15 --read-group nCoV-2019_1
```

Memory usage summary: heap total: 0, heap peak: 0, stack peak: 0
         total calls   total memory   failed calls
 malloc|          0              0              0
realloc|          0              0              0  (nomove:0, dec:0, free:0)
 calloc|          0              0              0
   free|          0              0
Histogram for block sizes:
Aborted (core dumped)

**Comment by jts** [comment]
No other messages? That's odd. What happens if you run `nanopolish` with no arguments?

**Comment by gezthxbio** [comment]
nanopolish
error: no command provided
usage: nanopolish [command] [options]
  valid commands: 
    --help
    --version
    call-methylation
    eventalign
    extract
    getmodel
    help
    index
    methyltrain
    phase-reads
    polya
    scorereads
    variants
    vcf2fasta
  for help on given command, type nanopolish command --help

**Comment by jts** [comment]
Well, it seems nanopolish is compiled and working so you should not get an immediate abort message when running `nanopolish variants`. Is there anything in `barcode02.nCoV-2019_1.vcf`?

**Comment by gezthxbio** [comment]
No the file is empty, can this be related to hdf5

**Comment by jts** [comment]
It does not seem to get far enough to be related to hdf5

**Comment by jts** [comment]
Did the `nanopolish index` step run correctly? Do you see `*.readdb` files?

**Comment by gezthxbio** [comment]
yes COVID_17_12_2020_barcode02.fastq.index.readdb is present

**Comment by jts** [comment]
What are you using to profile the memory usage (what prints the `Memory usage summary`message)?

**Comment by gezthxbio** [comment]
solved it by following [this link ](https://github.com/nanoporetech/vbz_compression/issues/7), 
downloaded : https://github.com/nanoporetech/vbz_compression/releases/download/v1.0.1/ont-vbz-hdf-plugin-1.0.1-Linux-x86_64.tar.gz
export HDF5_PLUGIN_PATH=ont-vbz-hdf-plugin-1.0.1-Linux/usr/local/hdf5/lib/plugin/

**Comment by jts** [comment]
Ah, thanks. The most recent version on github will print an error message when that plugin is needed. Sorry for the difficulties.
