### ISSUE TITLE
call-methylation parallel questions

### ISSUE THREAD

**Issue by RichardCorbett** [jts/nanopolish#876]
Hi @jts and team,  I hope you are keeping well.

I am running call-methylation on a deeply covered (50X) germline human sample and it took just under 24 hours to process chromosome 1 of my hg38 minimap2 alignments.  

I have an idle machine with 48 CPUs and 400Gb of RAM and my command looks like this:
`${nanopolish_0_13_2} call-methylation -t 48 -b ${bam_file} -g ${reference_file} -r ${fastq_file} > methylation_calls.tsv`

I see that I can provide coordinate ranges to parallelize the process, but I found your `nanopolish_makerange.py` script, which appears to provide coordinate ranges with some overlap between the windows.   Is this recommended for the call-methylation process?    If so, do you have a recommended way to combine the methylation calls from the overlapping windows?

thanks!

**Comment by jts** [comment]
Hi @RichardCorbett,

Great to hear from you! I hope all is well out in BC

The recommended way to do this is to process the genome in 10MB bins with zero overlap by making a file like this:

```
python nanopolish_makerange.py --segment-length 10000000 --overlap-length 0 reference.fasta > segments.txt
```

I hope that helps!
Jared

**Comment by RichardCorbett** [comment]
Wonderful.   Thanks for the speedy reply!
