### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by manburst** [jts/nanopolish#878]
Hello, sir I just want to install nanopolish to use with my dataset. However, its go an error in install process
here is a error message from terminal
`jirachote@ubuntu:~/nanopolish$ make
if [ ! -e hdf5-1.8.14.tar.gz ]; then \
	version_major_minor=`echo "1.8.14" | sed -E 's/\.[0-9]+$//'`; \
	wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-${version_major_minor}/hdf5-1.8.14/src/hdf5-1.8.14.tar.gz; \
fi
--2021-02-01 00:51:39--  https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.14/src/hdf5-1.8.14.tar.gz
Resolving support.hdfgroup.org (support.hdfgroup.org)... 50.28.50.143
Connecting to support.hdfgroup.org (support.hdfgroup.org)|50.28.50.143|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11761702 (11M) [application/x-gzip]
Saving to: ‘hdf5-1.8.14.tar.gz’

hdf5-1.8.14.tar.gz                 100%[================================================================>]  11.22M   216KB/s    in 52s     

2021-02-01 00:52:32 (222 KB/s) - ‘hdf5-1.8.14.tar.gz’ saved [11761702/11761702]

tar -xzf hdf5-1.8.14.tar.gz || exit 255
cd hdf5-1.8.14 && \
	./configure --enable-threadsafe --disable-hl --libdir=`pwd`/../lib --includedir=`pwd`/../include --prefix=`pwd`/.. || exit 255
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking shell variables initial values... done
checking if basename works... yes
checking if xargs works... yes
checking for cached host... none
checking for config x86_64-unknown-linux-gnu... no
checking for config x86_64-unknown-linux-gnu... no
checking for config unknown-linux-gnu... no
checking for config unknown-linux-gnu... no
checking for config x86_64-linux-gnu... no
checking for config x86_64-linux-gnu... no
checking for config x86_64-unknown... no
checking for config linux-gnu... found
checking for config ./config/site-specific/host-ubuntu... no
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/jirachote/nanopolish/hdf5-1.8.14':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** [Makefile:115: lib/libhdf5.a] Error 255
`
How to fix this. Thanks in advance.
Best
Jirachote

**Comment by jts** [comment]
I'm afraid this looks like an issue with your development environment and I'll be unable to help with this. I suggest installing nanopolish through conda instead.
