### ISSUE TITLE
nanopolish eventalign output

### ISSUE THREAD

**Issue by utritala** [jts/nanopolish#880]
Hi,
I kind of understand what each of the output columns mean, I am not sure about read_index, event_index, strand (I see "t" in my output but in the example given in the blog (http://simpsonlab.github.io/2015/04/08/eventalign/) it says "c". I am not sure what does c/t means?) and standardized_level. Sorry if I am missing something obvious but any explanation to the given columns or any pointers to the links explaining this already will be great. 
Many thanks,
Urmi

**Comment by jts** [comment]
Hi @utritala,

`read_index` is simply a counter over the number of reads seen, with the first read in the bam given index 0 and so on. If you use the `--print-read-names` option you'll get the full read names instead.

`event_index` is similar, it is a counter over the segmented events for the read, again starting from 0.

`strand` is for support with the older "2D" chemistry which could sequence both the `template` (t) and `complement` (c) strands of a DNA molecule.

I hope that helps and sorry for the slow reply.

Jared
