### ISSUE TITLE
Train new model using methyltrain

### ISSUE THREAD

**Issue by vahidAK** [jts/nanopolish#881]
Hi @jts ,

I wanted to train a new model using methyltrain module for the PromethION to detect 5-hmC in CpG motif.
Generally I have two PCR samples, one is 100% modified and the other one is not. After looking into previous issues ([400](https://github.com/jts/nanopolish/issues/400) and [157](https://github.com/jts/nanopolish/issues/157)) I still need some instruction and appreciate if you could help me.
1- Regarding the fact that CpG motif is already part of nanopolish, do I need to create a new alphabet for methyltrain? Out of curiosity, what is this alphabet file? Is it only includes all possible k-mers or it also includes other information for the k-mers?

2- From my experience with training using neural networks you need to specify a label for your modified (e.g. 0) and unmodified (e.g. 1)  k-mers. However, as I read previous issues, we will give the read.fa and read.bam file to methyltrain but the read.fa and read.bam file are a mixed of read which are 100% modifies and 100% unmodified. How methyltrain distinguishes those reads? should we train a separate model for each set of reads?

3- You have mentioned to convert modified base to "M" in the reference. Does this mean I need to convert all cytosine's (those in the CpG motive?) in the reference genome to M?

Thanks,
Vahid

**Comment by jts** [comment]
Hi,

> 1- Regarding the fact that CpG motif is already part of nanopolish, do I need to create a new alphabet for methyltrain?

No, you can re-use the CpG alphabet.

>  Is it only includes all possible k-mers or it also includes other information for the k-mers?

It includes all possible k-mers over the alphabet (so for a 5 symbol alphabet 5^6 k-mers) but only the subset of the k-mers that appear in the genome will be trained.

> 2- From my experience with training using neural networks you need to specify a label for your modified (e.g. 0) and unmodified (e.g. 1) k-mers. However, as I read previous issues, we will give the read.fa and read.bam file to methyltrain but the read.fa and read.bam file are a mixed of read which are 100% modifies and 100% unmodified. How methyltrain distinguishes those reads? should we train a separate model for each set of reads?

Typically we start with a model for unmodified data, then train the states using the methylated data.

> 3- You have mentioned to convert modified base to "M" in the reference. Does this mean I need to convert all cytosine's (those in the CpG motive?) in the reference genome to M?

Correct

You should use `nanopolish train` from the r10 branch, rather than `methyltrain`. It is a better training method and easier to use. See the discussion in these issues:

https://github.com/jts/nanopolish/issues/761
https://github.com/jts/nanopolish/issues/825

**Comment by vahidAK** [comment]
Thanks, @jts 

> Typically we start with a model for unmodified data, then train the states using the methylated data.

So I need to first train a model using unmodified samples. Then train a separate model for modified samples? How can I use these two in parallel?

**Comment by jts** [comment]
Usually we start with the basic k-mer model that ONT provides, but you could also train on unmodified samples first if you'd like.

Jared

**Comment by vahidAK** [comment]
Thanks, @jts
