### ISSUE TITLE
PT_R{7,9} can cause build issues on some architectures

### ISSUE THREAD

**Issue by satta** [jts/nanopolish#883]
Hi! When building nanopolish for Debian, we noticed some build failures on PowerPC architectures due to a name clash of 
 the `PT_R7` and `PT_R9` enums with values defined by some architecture-specific header. Please find more information in our original bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=960634

As a fix, it is sufficient to simply rename these to some other value, e.g. `PT_R7` -> `PORETYPE_R7`. I'd be happy to send a PR if that is OK with  you.

**Comment by jts** [comment]
Thanks for this. Yes, changing that enum to be `PORETYPE_R7` would be a good fix. I'd appreciate a PR with that change.

An additional poretype (`PT_R10`) is defined in the unmerged `r10` branch of the code. If you make the change on master we can rebase the `r10` branch and change there as well.

**Comment by satta** [comment]
I have just opened a PR. Thanks for your quick response!
