### ISSUE TITLE
Empty vcf

### ISSUE THREAD

**Issue by madelaam** [jts/nanopolish#885]
Hello,

I am trying to get a polished sequence after canu: 
python3 '/home/grid/nanopolish/scripts/nanopolish_makerange.py' '/data/Varicovorax/Varicovorax/20210204_1720_X2_FAP14911_6902f034/Analysis/Canu/Varicovorax.canu.unitigs.fasta' | parallel --results '/data/Varicovorax/Varicovorax/20210204_1720_X2_FAP14911_6902f034/Analysis/Nanopolish/voricovorazx.results' -P 2 \ '/home/grid/nanopolish/nanopolish' variants --consensus -o '/data/Varicovorax/Varicovorax/20210204_1720_X2_FAP14911_6902f034/Analysis/Nanopolish/voricovorax.polished.{1}.vcf' -w {1} -r '/data/Varicovorax/Varicovorax/20210204_1720_X2_FAP14911_6902f034/Analysis/varicovorax.fasta' -b '/data/Varicovorax/Varicovorax/20210204_1720_X2_FAP14911_6902f034/Analysis/Minimap/voricovorax.sorted.bam' -g '/data/Varicovorax/Varicovorax/20210204_1720_X2_FAP14911_6902f034/Analysis/Canu/Varicovorax.canu.unitigs.fasta' -t 2 --min-candidate-frequency 0.1

And I getting empty vcf files:

##fileformat=VCFv4.2
##nanopolish_window=tig00000001:0-43935
##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">
##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">
##INFO=<ID=SupportFractionByStrand,Number=2,Type=Float,Description="Fraction of event-space reads that support the variant for each strand">
##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">
##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">
##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">
##INFO=<ID=StrandSupport,Number=4,Type=Integer,Description="Number of reads supporting the REF and ALT allele, by strand">
##INFO=<ID=StrandFisherTest,Number=1,Type=Integer,Description="Strand bias fisher test">
##INFO=<ID=SOR,Number=1,Type=Float,Description="StrandOddsRatio test from GATK">
##INFO=<ID=RefContext,Number=1,Type=String,Description="The reference sequence context surrounding the variant call">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample

Thank you.

**Comment by jts** [comment]
In the error logs you should see messages printed that say "post-run summary" or similar. Could you paste some examples of those?

**Comment by madelaam** [comment]
Hello,

I cannot find the posr-run summary, I have just attached the folder where all the output is.

Thank you.



________________________________

**Comment by madelaam** [comment]
Sorry, I though I attached the folder but I did not. Here it is.

[Nanopolish.zip](https://github.com/jts/nanopolish/files/6085207/Nanopolish.zip)

Thank you!

**Comment by madelaam** [comment]
I done it, Thank you!
