### ISSUE TITLE
combining minION and promethION reads

### ISSUE THREAD

**Issue by elbourret** [jts/nanopolish#886]
I have nanopore reads from minION and promethION flowcells (both R9) from the same individual. All reads were basecalled with the same guppy version (but different models for minION and promethION reads, obviously). All reads were aligned to the same genome, resulting in a single .bam file.

Can I call methylation from all these reads in one step using this single .bam file? Or do I need to generate two different .bam files, one for minON and another for promethION, and call methylation separately?

**Comment by jts** [comment]
You can provide all reads in a single .bam file.
