### ISSUE TITLE
Contig/Chr position incorrect for polya module output

### ISSUE THREAD

**Issue by obenno** [jts/nanopolish#888]
Hi,

Thank you for the wonderful tool. I'm using polya module to study PolyA site from our dRNA nanopore data, and found output tsv reporting incorrect contig/chr position for reads mapped to transcripts from positive strand (on 5 prime end instead of 3 prime). Please find a IGV screen capture below:

![image](https://user-images.githubusercontent.com/6121668/110760137-5863d480-8289-11eb-924f-0e0aa6592fcb.png)

The PAS sites were extracted from polya tsv output, and illustrated in the first track. Nanopolish was installed from conda (0.13.2). 

Thanks,
obenno

**Comment by obenno** [comment]
Sorry, forgot to mention:

- minimap2 (2.17-r941) installed from conda
- basecalling were done by guppy (v4+), can't remember the exact version ...

**Comment by jts** [comment]
Hi @obenno,

The contig and position are reported directly from the input BAM file and represent the alignment start position of the entire transcript, not the poly-A site. Does that help clarify the output?

Jared

**Comment by obenno** [comment]
Hi @jts ,

Yes, thank you for the clarification and sorry for the fool mistake, should read the docs more carefully.

obenno

**Comment by jts** [comment]
No problem, I think the column names in the output file can be misleading.

Jared
