### ISSUE TITLE
"fast5 is unreadable and will be skipped"

### ISSUE THREAD

**Issue by kewei2019** [jts/nanopolish#889]
Hi all,
Thank you for the amazing tool. I applied "quickstart_eventaligh" on my nanoporedata, but an error showed up. I can share a raw fast5 file if needed. Thanks for your help! 
![image](https://user-images.githubusercontent.com/52051945/110855621-d9b06c80-8273-11eb-8349-a44bdc8bf56e.png)

Kewei

**Comment by jts** [comment]
Sorry for the slow reply. Are the paths `fast5/[...]_0.fast5` accessible from the directory you are working in?
