### ISSUE TITLE
Raw data

### ISSUE THREAD

**Issue by gegberts** [jts/nanopolish#89]
Hi, 

For my master studies I have to work with raw minION data. However, in the fast5 files I can not find the raw data due to the fact that this data is already basecalled. Since you work with raw data I'd like to ask you how you attained this data. Is there a way you can provide me the data or tell me how to get it from the minION data storage directory? Or does it mean that I need a development license from ONT? 

I hope hearing from you.

**Comment by jts** [comment]
Hi,

For older MinION data the raw samples are not stored in the basecalled fast5 but in newer data they are retained. I suggest you look at the R9 data sets here, which should have raw samples:

http://lab.loman.net/2016/07/30/nanopore-r9-data-release/

(I assume you are looking for raw samples and not events, which are in most basecalled fast5 files).

Jared

**Comment by gegberts** [comment]
Hi,

I've R9 data but still I have no clue how to extract the raw data from the FAST5 files. For now I can only see means and standard deviations.

Could you tell me how to extract raw samples?

Sincerly, Ginger

Op 6 dec. 2016 om 15:18 heeft Jared Simpson <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Hi,

For older MinION data the raw samples are not stored in the basecalled fast5 but in newer data they are retained. I suggest you look at the R9 data sets here, which should have raw samples:

http://lab.loman.net/2016/07/30/nanopore-r9-data-release/

(I assume you are looking for raw samples and not events, which are in most basecalled fast5 files).

Jared

-

**Comment by mateidavid** [comment]
If available in a given fast5 file, raw signal data is stored at paths such as `/Raw/Reads/Read_29/Signal`, encoded as 16bit ints. Our fast5 library here https://github.com/mateidavid/fast5 can read and translate these into more usual picoamp measurements. See, e.g.:
https://github.com/mateidavid/fast5/blob/master/src/f5dump.cpp#L91

**Comment by gegberts** [comment]
I tried to configure the hdf5 library, but it did not work. It's needed for the FAST5 library you've provided. When only putting the hdf5.h kind of header files in the same folder I get the errors "undefined reference ..". Can you help me with that or do I need to search for a programmer in my neighbourhood?

**Comment by mateidavid** [comment]
Are you using Linux? How did you install hdf5? Does `h5dump` work on your fast5 files?

**Comment by gegberts** [comment]
I used Linux but there was a root problem. Now I'm using Windows and I get the following errors using Visual Studio 2015 (it is a long list, I show only two errors):


hdf5_tools.hpp(522): error C2065: 'not': undeclared identifier
hdf5_tools.hpp(522): error C2146: syntax error: missing ')' before identifier 'is_compound'

So I guess I'm missing something important. Do you know what I should do? Searching the web didn't help me much.

**Comment by mateidavid** [comment]
We don't support Windows directly, but you can install Docker on Windows, and then build nanopolish as a Docker container.
