### ISSUE TITLE
Issue with iteration over reference 

### ISSUE THREAD

**Issue by MichaelMont94** [jts/nanopolish#890]
Hello,

I am trying to use the call-methylation command, and while it outputs a methylation_calls.tsv, this file is empty except for the header. The command line input and output is as follows:

$nanopolish call-methylation -t 8 -r output_tar1.fastq -b output.sorted.bam -g ribo45s_in_chrUn_T2T_Hg38_consensus_reference.fa -w "T2T_45S_consensus_reference:0-13,037" > methylation_calls.tsv

[bam process] iterating over region: T2T_45S_consensus_reference:0-13,037

No other errors are appearing and this results in an empty file regardless of the modifications I have tried. I have attached my reference fasta file and my combined fastq file as well. "txt" extension was added to these files to allow for upload to Github.

I have been following this tutorial: https://nanopolish.readthedocs.io/en/latest/quickstart_call_methylation.html
[ribo45s_in_chrUn_T2T_Hg38_consensus_reference.fa.txt](https://github.com/jts/nanopolish/files/6143665/ribo45s_in_chrUn_T2T_Hg38_consensus_reference.fa.txt)
[output_tar1.fastq.txt](https://github.com/jts/nanopolish/files/6143666/output_tar1.fastq.txt)

**Comment by jts** [comment]
Sorry for the slow reply @MichaelMont94. How many reads are mapped to this region with mapping quality >20?
