### ISSUE TITLE
"warning: detected invalid summary file entries for 20 of 20 fast5 files" Is sort order important?

### ISSUE THREAD

**Issue by RichardCorbett** [jts/nanopolish#891]
Hi folks,

I am using nanopolish within a nextflow workflow that uses symlinks to move paths between steps of the workflow.

When I get to the point where I want to use nanopolish I have done the basecalling with guppy on a per-fast5 basis (we find this to be faster than allowing guppy to manage the use of multiple GPUs at once) and then merged the fastq and sequencing_summary.txt files.     I have not taken care to ensure reads are in the same order in both merged files.  Also perhaps of note is that the fast5 files I start with span multiple flowcells.

When I run nanopolish index like this:
```
/gsc/software/linux-x86_64-centos7/nanopolish-0.13.2/bin/nanopolish index -d merged_fast5/ -s F24722_sequencing_summary.txt F24722_merged_fastq.gz
```

I get this warning...
`
warning: detected invalid summary file entries for 20 of 20 fast5 files
These files will be indexed without using the summary file, which is slow.
`

But it seems every read is listed once in my fastq file and once in my sequencing summary file and corresponds to 1 fast5 file.

Is there any requirement that the order of reads in my merged fastq file match the order of the reads listed in the sequencing_summary.txt file?     I'm trying some different sorting options and I haven't figured this out yet.   If I use just the first few thousand reads in my fastq and seuqencing_summary.txt everything works swiftly.  Once I get over 4000 reads in my files I get the warning above, but I can't track down anything out of order in either my merged fastq or sequencing_summary.txt files.

**Comment by RichardCorbett** [comment]
Hmm. Seems more likely now my issue is that my fastq and sequence_summary.txt are in the same order, but don't match the order of the reads in the fast5 files.   I'll see if I can confirm this.

**Comment by jts** [comment]
Hi @RichardCorbett,

The order of the reads in the fastq/summary file shouldn't matter, nanopolish just makes a dictionary from it. Nanopolish does expect there to be at most 4000 reads per fast5 though. Can you clarify by what you mean by:

> Once I get over 4000 reads in my files I get the warning above

Do you have more than 4000 reads per fast5?

**Comment by RichardCorbett** [comment]
Thanks @jts 
Our fast5 files originally had 4000 reads per file but we switched it up to 16000 reads per fast5 file some time ago .  All our minion and promethion runs now generate fast5s with 16000 reads per file.

When I was testing earlier, I noticed that if my fastq and sequencing_summary.txt file had more than 4000 reads I would get the warning i listed above.  Perhaps this makes sense as those 4000 reads would be at the top of the fast5 file.

**Comment by jts** [comment]
Ok, that probably explains part of it. We had to add a check into the indexer to make sure the summary structure was as expected:

https://github.com/jts/nanopolish/blob/master/src/nanopolish_index.cpp#L299

It requires seeing at least 20 fast5 files though, so maybe your test is a bit below this? Can you try with more files?

**Comment by RichardCorbett** [comment]
Aha.    I was testing using 20 fast5 files.   I'll add in a few more and see if it helps.

**Comment by RichardCorbett** [comment]
OK.  I tried with 25 fast5 files, all with 15000 reads and didn't have any trouble or warnings.   Indexing completed in just under 20 minutes.
