### ISSUE TITLE
Nanopolish: fai_build_core different line length in sequence '(null)'

### ISSUE THREAD

**Issue by cmaggior** [jts/nanopolish#892]
Hello,

I'm running Nanopolish v0.13.2 with the follow command:

python3 scripts/nanopolish_makerange.py ../BC02_assemble2.contigs.fasta | parallel --results nanopolish.results ./nanopolish variants --consensus -o BC02polished.{1}.vcf -w {1} -r ../BC02_assemble2.contigs.fasta -b ../BC02.sorted.bam -g ../RawMarsChamber.fastq --min-candidate-frequency 0.1
 
and receiving the following error:

[fai_build_core] different line length in sequence '(null)'.
[fai_load] build FASTA index.

I've tried running samtools faidx on the draft genome file but no luck. Can you advise on what may be causing this issue?

Also, I was previously trying to manually install v0.13.2 due to some technical issues and was running into the following error:

--2021-03-24 14:09:06--  https://bitbucket.org/eigen/eigen/get/3.3.7.tar.bz2
Resolving bitbucket.org (bitbucket.org)... 104.192.141.1, 2406:da00:ff00::22c2:513, 2406:da00:ff00::22cd:e0db, ...
Connecting to bitbucket.org (bitbucket.org)|104.192.141.1|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-03-24 14:09:06 ERROR 404: Not Found.

It seems like eigen is pointing to an incorrect location.

Cheers!

**Comment by jts** [comment]
Hi,

I think you've swapped the `-r` and `-g` options around. `-g` should be the genome, but you've passed in the reads.

The Eigen issue is fixed in the main branch on github, but not yet in a tagged release.

Jared

**Comment by cmaggior** [comment]
Wow that is incredibly embarrassing. I'm really sorry, thank you for clearing that up for me.

Cheers.

**Comment by jts** [comment]
No problem, happy to help
