### ISSUE TITLE
Error in eventalign mode

### ISSUE THREAD

**Issue by kewei2019** [jts/nanopolish#893]
Hi all,
Thank you for the amazing tool. I applied "quickstart_eventaligh" on my nanopore data, but an error showed up. The final output eventalign.txt contains nothing but only the titles. I can share a raw fast5 file if needed. Thanks for your help!
![image](https://user-images.githubusercontent.com/52051945/112702130-1e352e00-8e58-11eb-910e-a2517ac31963.png)
Nanopolish index:
![image](https://user-images.githubusercontent.com/52051945/112702190-3f961a00-8e58-11eb-81e7-72638320b794.png)
Align reads to the ref:
![image](https://user-images.githubusercontent.com/52051945/112702241-6e13f500-8e58-11eb-93ea-4d359b1139b0.png)
samtools:
![image](https://user-images.githubusercontent.com/52051945/112702266-82f08880-8e58-11eb-9f94-61d3c0b21312.png)
Align the events to the ref:
![image](https://user-images.githubusercontent.com/52051945/112702319-b6331780-8e58-11eb-8f84-ae5692643c40.png)

Best,
Kewei Xu

**Comment by jts** [comment]
Addressed over email
