### ISSUE TITLE
nanopolish installation, fatal error: too many errors emited 

### ISSUE THREAD

**Issue by aruizman** [jts/nanopolish#894]
Hi, 
I'm trying to install nanopolish to ultimately learn how to use minimap2 (weird route, I know but i'm having trouble starting minimap2 and no one around me knows anything about data analysis, so i'm on my own following every tutorial that I can find), following this:

>git clone --recursive https://github.com/jts/nanopolish.git
>cd nanopolish
>make

but I keep getting this error:

fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [cache.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [lib/libhdf5.a] Error 2

How can I fix that?
 attached are part of the terminal codes

![Screen Shot 2021-04-02 at 20 54 58](https://user-images.githubusercontent.com/73360287/113464945-1a744f00-93f6-11eb-8293-1b03143d2325.png)
![Screen Shot 2021-04-02 at 20 56 02](https://user-images.githubusercontent.com/73360287/113464946-1b0ce580-93f6-11eb-8525-d3ded08b0ff9.png)
![Screen Shot 2021-04-02 at 20 56 14](https://user-images.githubusercontent.com/73360287/113464947-1b0ce580-93f6-11eb-9163-13d7dfd38d54.png)
![Screen Shot 2021-04-02 at 20 56 26](https://user-images.githubusercontent.com/73360287/113464948-1ba57c00-93f6-11eb-8266-23e9f658a084.png)
![Screen Shot 2021-04-02 at 20 56 38](https://user-images.githubusercontent.com/73360287/113464949-1ba57c00-93f6-11eb-849b-95b372beb007.png)
![Screen Shot 2021-04-02 at 20 56 58](https://user-images.githubusercontent.com/73360287/113464950-1ba57c00-93f6-11eb-8fad-79c1047ab63d.png)

**Comment by jts** [comment]
Hi,

Nanopolish is complicated to install on MacOS so I suggest you use bioconda to install it. In any case, minimap2 is much easier to compile than nanopolish so I think focusing there is your best bet.

Jared

**Comment by aruizman** [comment]
Thanks for the advice! I'll keep working on minimap2.

________________________________
