### ISSUE TITLE
Question about nanopolish event align with rna

### ISSUE THREAD

**Issue by manburst** [jts/nanopolish#895]
Hello
I have a question about how to use nanopolsih event align. My sequence is direct rna seq. I expected to find "UUUUU" motif in model_kmer but somehow it not showing. The "TTTTT" motif is displayed which should not tepresent in rna sequnce. Are there any options to adjust the output as rna?
Thanks in advance.

**Comment by jts** [comment]
Hi,

Another user has reported a similar issue, which is discussed here: https://github.com/jts/nanopolish/issues/479#issuecomment-426762826

Jared

**Comment by manburst** [comment]
Thanks for answering, I have more few questions.
1. Is nanopolish event align work with nanopolish index with fastq input?
2. The result of nanopolish event align didn't show the name of the read ( I mean read id of the sequence) so if I want to get specific eventalign data for each read. I have to perform one by one, am I right?

**Comment by jts** [comment]
1. yes
2. you can use the  `--print-read-names` option to show read names instead of numerical IDs

**Comment by manburst** [comment]
Hello Jared
I have question about event align again 
Why event_index in my result event align file not start with 1?
Here screenshot from my result
![image](https://user-images.githubusercontent.com/68594551/119513490-7926cb00-bd9e-11eb-9787-a1eed8663931.png)

**Comment by jts** [comment]
`eventalign` requires the basecalled sequence to align to the reference genome to anchor the alignment. If parts of the read are clipped off, the corresponding events will not be aligned.

**Comment by manburst** [comment]
Thank you! 
I get it now!
But what about adjusting k-mer in result?

**Comment by jts** [comment]
With DNA sequences 6-mers are used, with RNA 5-mers are used. This comes from the models provided by ONT and cannot be changed.

**Comment by jts** [comment]
Hi @btrspg,

Nanopolish uses the definition of "events" from old versions of the ONT basecallers (specifically, as implemented in scrappie). The "events" from the current version of guppy are defined differently and not used by nanopolish.

Jared
