### ISSUE TITLE
CpG identification and imprinting

### ISSUE THREAD

**Issue by PaulaRomeroLozano** [jts/nanopolish#897]
Hello jst,

I am new at using Nanopolish and I am trying to understand how the methylation detection works.
I have read nanopolish will only look at the 5mC for the CpG islands and I wonder:
How do you define their coordinats on the reference genome?
I am unsure of how do you define the CpG context for the further downstream analysis...

I am also interested in imprinting methylation; would you recommend me to run the script "split_calls_by_phase" for the haplotyping analysis?

Thank you in advance for clarifying,

Kind regards,
Paula

**Comment by jts** [comment]
Hi @PaulaRomeroLozano,

Sorry for the slow reply, I'll answer the questions I'm able to:

> I have read nanopolish will only look at the 5mC for the CpG islands

Nanopolish will call methylation at all CpG sites covered by a read, not just CpG islands

> How do you define their coordinats on the reference genome? I am unsure of how do you define the CpG context for the further downstream analysis...

Sorry but I'm not quite sure what you are asking, nanopolish reports the coordinates of the CpG calls using the usual reference genome coordinate system

Jared
