### ISSUE TITLE
nanopolish installation error

### ISSUE THREAD

**Issue by RippeiHayashi** [jts/nanopolish#898]
Hello,
I would like to install the latest version (as of 2021-Apr-18) of nanopolish on a linux computer (8.3.2011).
But, the installation fails with the following error:

---
In file included from ./src/alignment/nanopolish_eventalign.h(14),
                 from src/nanopolish_call_methylation.cpp(30):
./src/common/nanopolish_alphabet.h(140): warning #823: reference is to variable "j" (declared at line 122) -- u
nder old for-init scoping rules it would have been variable "j" (declared at line 128)
                          out[j--] = get_recognition_site_methylated_complement(recognition_index)[k];
                              ^
---

Could you help fix the issue?
The below version of GNU compiler collection is used (I don't have the admin right to change):
gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC)

Thank you,
Rippei

**Comment by jts** [comment]
Thanks for report, this is now fixed in the commit above.
