### ISSUE TITLE
HDF5-DIAG: Error when calling methylation modification

### ISSUE THREAD

**Issue by zmz1988** [jts/nanopolish#899]
Hi, I recently would like to use Nnaopolish to generate the methylation data from Nanopore sequence. The basecall was done by the sequencing centre for us using guppy, and I started the methylation call from combining fastq files, indexing and all the downstream processes, following this guide (https://nanopolish.readthedocs.io/en/latest/quickstart_call_methylation.html). The indexing step was fine, but in the final call for methylation, I always got errors like following (only parts of the error file):

`HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 139992288380672:
  #000: H5Dio.c line 173 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: H5Dio.c line 554 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: H5Dchunk.c line 1875 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: H5Dchunk.c line 2905 in H5D__chunk_lock(): data pipeline read failed
    major: Data filters
    minor: Filter operation failed
  #004: H5Z.c line 1347 in H5Z_pipeline(): required filter 'vbz' is not registered
    major: Data filters
    minor: Read failed
  #005: H5PL.c line 358 in H5PL_load(): search in paths failed
    major: Plugin for dynamically loaded library
    minor: Can't get value
  #006: H5PL.c line 475 in H5PL__find(): can't open directory: /miniconda3/envs/nanopolish/lib/hdf5/plugin
    major: Plugin for dynamically loaded library
    minor: Can't open directory or file
HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 139992582006528:
  #000: H5Dio.c line 173 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: H5Dio.c line 554 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: H5Dchunk.c line 1875 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: H5Dchunk.c line 2905 in H5D__chunk_lock(): data pipeline read failed
    major: Data filters
    minor: Filter operation failed
  #004: H5Z.c line 1347 in H5Z_pipeline(): required filter 'vbz' is not registered
    major: Data filters
    minor: Read failed
  #005: H5PL.c line 358 in H5PL_load(): search in paths failed
    major: Plugin for dynamically loaded library
    minor: Can't get value
  #006: H5PL.c line 475 in H5PL__find(): can't open directory: /miniconda3/envs/nanopolish/lib/hdf5/plugin
    major: Plugin for dynamically loaded library
    minor: Can't open directory or file
`

I'm not sure where it got wrong. I thought if the indexing step went well, then the nanopolish installation should be fine, right? 

Could you please help me on this issue?

my codes are here :

`nanopolish index -d /fast5_pass/barcode01/ -s sequencing_summary_PAG09908_c2afc1ef.txt /Analysis/0_mergedFastq/fastq/barcode01.fastq

minimap2 -a -x map-ont /Analysis/2_Assemble/TAIR10_chr_all_reference.fasta barcode01.fastq | samtools sort -T tmp -o barcode01.TAIR10.sorted.bam

samtools index barcode01.sorted.bam

#copy all of the files in the same folder, and then

nanopolish call-methylation -t 30 -r barcode01.fastq -b barcode01.sorted.bam -g racon_medaka_pilon_consensus.fasta > barcode01_methylation_calls.tsv`

Thanks!

**Comment by jts** [comment]
Hi @zmz1988,

This message indicates the .fast5 files have been compressed with the vbz encoder. You need to load a plugin to allow nanopolish to read these files. You can find instructions for doing this here:

https://github.com/nanoporetech/vbz_compression/issues/5

Jared

**Comment by zmz1988** [comment]
Thanks @jts! I find that actually I already have the plugin in the package ont_fast5_api, but somehow the nano polish did not recognise it. So I just add the `export HDF5_PLUGIN_PATH=/miniconda3/envs/nanopolish/lib/python3.9/site-packages/ont_fast5_api/vbz_plugin/` in my shell. It works well! Thanks!

**Comment by jts** [comment]
Glad to hear it!
