### ISSUE TITLE
problem opening h5Fopen 

### ISSUE THREAD

**Issue by lfaino** [jts/nanopolish#9]
Dear All, 

I get this error when i try to run nanopolish correct.
Any idea? 
thanks Luigi

Computing consensus for Contig33:0-10200
HDF5-DIAG: Error detected in HDF5 (1.8.15-patch1) thread 0:
  #000: H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 990 in H5F_open(): unable to open file: time = Wed Jun 17 10:04:33 2015
, name = 'D0134423_FlowFAA44478Ac35_3506_1_ch335_file15_strand_twodirections', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 993 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: H5FDsec2.c line 343 in H5FD_sec2_open(): unable to open file: name = 'D0134423_FlowFAA44478Ac35_3506_1_ch335_file15_strand_twodirections', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
terminate called after throwing an instance of 'hdf5_tools::Exception'
  what():  D0134423_FlowFAA44478Ac35_3506_1_ch335_file15_strand_twodirections: error in H5Fopen
local:0/67/100%/0.1s

**Comment by jts** [comment]
Hi Luigi,

nanopolish uses the headers in the input FASTA file to look up the paths to the FAST5 files containing the raw event data. This error seems to indicate that a cetain FAST5 couldn't be found. Can you take a look at your input FASTA and make sure the second field in the header is a valid path to a FAST5 file?

Thanks,
Jared

**Comment by lfaino** [comment]
here the header.

>0.5e568cb1-d4f8-4b21-a9f9-783b989005b2_Basecall_2D_000_2d D0134423_FlowFAA44478Ac35_1_4941_1_ch208_file39_strand_twodirections pass/D0134423_FlowFAA44478Ac35_1_4941_1_ch208_file39_strand.fast5

however, I think that there is an error. in the second field i have : D0134423_FlowFAA44478Ac35_1_4941_1_ch208_file39_strand_twodirections 
 
but after metrichor all the files are like this: D0134423_FlowFAA44478Ac35_1_4941_1_ch208_file39_strand.fast5

if i look in the folder pass or failed there are no files with attached "complement, twodirections, template". therefore i think that the fast5 location is in the 3 field not in the second.

Luigi

**Comment by jts** [comment]
Ok, I wonder if they changed the file format. I'll look into this but am travelling right now. If you want to change the nanopolish code or use awk to rewrite your fasta file it should let you continue on.

Jared

**Comment by jts** [comment]
This is now fixed in 0aeb3b8bbc57d8
