### ISSUE TITLE
nanopolish extract fast5 into fastq

### ISSUE THREAD

**Issue by yuhongning** [jts/nanopolish#90]
Hi
Does "nanopolish extract" will generate "fastq" file from fast5 file? I tried, it only creates "fasta" file. I didn't find suitable options to outut "fastq" file from the help page.

Thanks,

Yuhong Ning

**Comment by jts** [comment]
Hi,

Currently it only outputs fasta, not fastq. @mateidavid do you want to add fastq output as an option?

Jared

**Comment by yuhongning** [comment]
Thanks for your reply, Jared.
Yes, I would prefer fastq output, so it can be used for alignment and
variant detection by applying quality.
Thanks again!
Yuhong

**Comment by jts** [comment]
I think keep the default as fasta.

Jared

**Comment by yuhongning** [comment]
Cool, you are super!
Thanks,
Yuhong

**Comment by jts** [comment]
`nanopolish extract -q` will extract fastq files

**Comment by yuhongning** [comment]
Thanks for upgrading this!
Yuhong
