### ISSUE TITLE
Assertion `data.rt.n > 0' failed

### ISSUE THREAD

**Issue by matthew-valentine** [jts/nanopolish#904]
I have two sets of nanopore data from runs on Mk1C that I am processing, one which was multiplexed and another which wasn't. I was able to run nanopolish eventalign and NanopolishComp successfully after demultiplexing the first set of data, but I am running into some issues with the second set. I am using the exact same code in both cases, so I don't think it is a problem with the version of nanopolish that I'm using, but I am using version 0.12.5

When I try to run nanopolish eventalign I get the following error:

`nanopolish: src/nanopolish_squiggle_read.cpp:114: void SquiggleRead::init(const string&, const Fast5Data&, uint32_t): Assertion 'data.rt.n > 0' failed.`

`An error occured. All processes were killed`

`Traceback (most recent call last):
  File "/opt/local/pyenv/versions/3.7.2/bin/NanopolishComp", line 8, in <module>
    sys.exit(main())
  File "/opt/local/pyenv/versions/3.7.2/lib/python3.7/site-packages/NanopolishComp/__main__.py", line 65, in main
    args.func(args)
  File "/opt/local/pyenv/versions/3.7.2/lib/python3.7/site-packages/NanopolishComp/__main__.py", line 80, in Eventalign_collapse_main
    quiet = args.quiet)
  File "/opt/local/pyenv/versions/3.7.2/lib/python3.7/site-packages/NanopolishComp/Eventalign_collapse.py", line 150, in __init__
    raise E
  File "/opt/local/pyenv/versions/3.7.2/lib/python3.7/site-packages/NanopolishComp/Eventalign_collapse.py", line 140, in __init__
    raise E
NanopolishComp.common.NanopolishCompError: Traceback (most recent call last):
  File "/opt/local/pyenv/versions/3.7.2/lib/python3.7/site-packages/NanopolishComp/Eventalign_collapse.py", line 178, in _split_reads
    cur_read_id = event_l[idx["read_id"]]
IndexError: list index out of range
`

The only real difference between the demultiplexed data set and the one that isn't working (besides going through demultiplexing with poreplex to generate the fastq files), is that in order for the demultiplexing to be successful I had to run guppy myself with the `--fast5_out` option to regenerate the fast5 files, as poreplex wouldn't work on the fast5 files outputted by the machine. So I tried doing this step with the non-multiplexed data to see if the new fast5 files would avoid this error, but unfortunately I was still getting the error. One thing I have noticed is that if I inspect the fast5 files with `h5dump`, although I can get an output file containing sequence information, I do get the intermittent error `h5dump error: unable to print data`. So I'm thinking there must be differences between the two sets of files, and that maybe there was some problem with the second experiment? Is there anything specific I should be looking for in the fast5 files to explain why one set of files works with nanopolish while the other doesn't? 

Best regards,
Matthew

**Comment by jts** [comment]
Hi @matthew-valentine,

This part suggests to me that the fast5 files are corrupt or otherwise non-readable:

>  I do get the intermittent error h5dump error: unable to print data

If the core hdf5 tools (like `h5dump`) are not able to read the files, nanopolish won't be able to as well. I'm afraid I'm unable to help determine why the files are corrupt, I'd suggest getting in touch with ONT support.

Jared
