### ISSUE TITLE
badfast5 in eventalign

### ISSUE THREAD

**Issue by izl2** [jts/nanopolish#908]
Hi!

I’ve been having some trouble with nanopolish eventalign where I receive the following output: [post-run summary] total reads: 1267, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 1267

I saw from previous posts that other people had a similar issue, but after checking my own work I wasn’t able to find a solution. I didn’t receive any error messages for the index step—it outputted the .index, .gzi, .fai, and .readdb files in the same directory as the .fastq file, and finished with the message: [readdb] num reads: 1291130, num reads with path to fast5: 645565. The .readdb file also seems to look as expected. I also made sure that the index files were in the same directory as my working directory when running eventalign. 

As suggested in the manual, I also did samtools quickcheck on the .bam file of the sorted minimap2 alignment, and it seemed to be okay.  

I’m wondering if you had any idea what the problem might be?

Thanks for all your help with this tool!

**Comment by jts** [comment]
Hi,

> num reads: 1291130, num reads with path to fast5: 645565

The number of reads that were found in your files is exactly double the number of reads that have a corresponding fast5 file. I think you've accidentally doubled the read set somewhere, as these two numbers should match.

Jared
