### ISSUE TITLE
`'GLIBCXX_3.4.26' not found` error

### ISSUE THREAD

**Issue by PanZiwei** [jts/nanopolish#909]
Hi,
I follwed the git installation instruction for Nanopolish v0.13.3, but failed to run `nanopolish index` with the error `nanopolish: /cm/local/apps/gcc/8.2.0/lib64/libstdc++.so.6: version 'GLIBCXX_3.4.26' not found (required by nanopolish)`. Any idea on the ossue?

BTW Everything is fine in the last when I installed nanopolish via conda environment. So maybe conda package will be more convenient though git is the recommendation installation way.  Is there any plan to update the bioconda package version for Nanopolish? It is still 0.13.2: https://anaconda.org/bioconda/nanopolish

Thank you so much for your help!

**Comment by jts** [comment]
Hi,

The usual source of this type of error is that you compiled nanopolish on one machine, then tried using it on a different machine with different libraries installed. You'll have to re-compile on the machine you want to run on.

Thanks for the note on the conda version, I'll try to update it.

Jared
