### ISSUE TITLE
parallel: command not found

### ISSUE THREAD

**Issue by jsimba-99** [jts/nanopolish#910]
Dear Nanopolish community,

Im running the nanopolish_makerange.py script as follows:

$ ./scripts/nanopolish_makerange.py Codor_polished.fasta | parallel --results nanopolish.results -P 8
and shows this:
**bash: parallel: command not found...**

Why is the parallel command not working?, also when I run the script without the parallel option, I got an stdout output with three lines but not fasta files with the contig partitioned

I would appreciate any help on this

Cheers,

**Comment by jts** [comment]
Hi,

`parallel` is a stand command line tool, not part of nanopolish. You can install it from your linux distribution's package manager, or with conda.

Jared
