### ISSUE TITLE
make won't compile

### ISSUE THREAD

**Issue by rckeerthivasan** [jts/nanopolish#913]
Hi, I am trying to run 'make' command after creating venv. 

fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [cache.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [lib/libhdf5.a] Error 2

I run these commands: make CXX=/usr/local/bin/g++-11, make CXX=g++-11. 

Any idea? Thank you.

**Comment by jts** [comment]
I've not tested on g++ 11, I suspect it is too recent. Can you paste the full error message?

**Comment by rckeerthivasan** [comment]
tmisc.c:2713:63: warning: incompatible pointer to integer conversion initializing 'const char' with an expression of type 'void *' [-Wint-conversion]
                        {"1234567", "1234567\0", "12345678", {NULL}};
                                                              ^~~~
/Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include/stddef.h:89:16: note: expanded from macro 'NULL'
#  define NULL ((void*)0)
               ^~~~~~~~~~
tmisc.c:2792:63: warning: incompatible pointer to integer conversion initializing 'const char' with an expression of type 'void *' [-Wint-conversion]
                        {"1234567", "1234567\0", "12345678", {NULL}};
                                                              ^~~~
/Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include/stddef.h:89:16: note: expanded from macro 'NULL'
#  define NULL ((void*)0)
               ^~~~~~~~~~
2 warnings generated.
  CCLD     testhdf5
ld: warning: directory not found for option '-L/Users/raviboya/softwares/nanopolish.venv/nanopolish/hdf5-1.8.14/../lib'
  CC       lheap.o
  CCLD     lheap
ld: warning: directory not found for option '-L/Users/raviboya/softwares/nanopolish.venv/nanopolish/hdf5-1.8.14/../lib'
  CC       ohdr.o
  CCLD     ohdr
ld: warning: directory not found for option '-L/Users/raviboya/softwares/nanopolish.venv/nanopolish/hdf5-1.8.14/../lib'
  CCLD     stab
ld: warning: directory not found for option '-L/Users/raviboya/softwares/nanopolish.venv/nanopolish/hdf5-1.8.14/../lib'
  CCLD     gheap
ld: warning: directory not found for option '-L/Users/raviboya/softwares/nanopolish.venv/nanopolish/hdf5-1.8.14/../lib'
  CC       cache.o
cache.c:25754:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:25826:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:25901:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:25977:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:26050:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:26125:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:26197:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:26273:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:26345:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:26417:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:26492:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:26564:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:26640:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:26713:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:26788:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:26860:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:26932:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:27008:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:27083:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [cache.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [lib/libhdf5.a] Error 2

**Comment by rckeerthivasan** [comment]
If I run make CXX=/usr/local/bin/g++-4.9, I get 

configure: error: in `/Users/raviboya/softwares/nanopolish.venv/nanopolish/hdf5-1.8.14':
configure: error: C++ preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details
make: *** [lib/libhdf5.a] Error 255


although both gcc-4.9 and gcc-11 are installed

**Comment by jts** [comment]
I recommend using the conda package as it is difficult to build on MacOS

**Comment by rckeerthivasan** [comment]
using the condo package also gives the same errors.

**Comment by jts** [comment]
When installing nanopolish with conda it should not try to compile, it should use a prebuilt binary. Can you show the commands you ran?
