### ISSUE TITLE
[readdb] indexing Fast5/ Error: no fast5 files found

### ISSUE THREAD

**Issue by Hannah1746** [jts/nanopolish#917]
So I have have all my fast5 files in a directory called Fast5 and all my fastq file cat together in a file called output.fastq.

When I run:
Nanopolish index -d Fast5/ output.fastq

I get this output:
[readdb] indexing Fast5/ 
Error: no fast5files found

I am not sure what to do to fix this problem.

**Comment by Hannah1746** [comment]
I have now also tried to do a test run on just 10 Fast5 and Fastq from a different organism and am getting the same error.

Nanopolish index -d Fast5/ output.fastq

I get this output:
[readdb] indexing Fast5/
Error: no fast5files found

It create the index files:
output.fastq.index         71M
output.fastq.index.fai    2.5M
output.fastq.index.gzi    60K

But when I go to run nanopolish I get the error:
error: can not load the index files for input file output.fastq
Please run nanopolish index on your reads (see documentation)

**Comment by jts** [comment]
Hi,

Can you run `ls Fast5` and paste the output?

Jared

**Comment by Hannah1746** [comment]
Here is the 11 that I am using for my test run.

FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_0.fast5
FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_10.fast5
FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_1.fast5
FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_2.fast5
FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_3.fast5
FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_4.fast5
FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_5.fast5
FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_6.fast5
FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_7.fast5
FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_8.fast5
FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_9.fast5

**Comment by jts** [comment]
Can you run this exact command, and paste everything that is printed to the terminal?

```
find . -name "*.fast5"
```

**Comment by Hannah1746** [comment]
./Fast5/FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_5.fast5
./Fast5/FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_2.fast5
./Fast5/FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_3.fast5
./Fast5/FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_8.fast5
./Fast5/FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_10.fast5
./Fast5/FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_1.fast5
./Fast5/FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_9.fast5
./Fast5/FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_0.fast5
./Fast5/FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_6.fast5
./Fast5/FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_4.fast5
./Fast5/FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_7.fast5

**Comment by jts** [comment]
Can you try to follow the first steps of this tutorial to see if indexing works on our example data?

https://nanopolish.readthedocs.io/en/latest/quickstart_call_methylation.html

**Comment by Hannah1746** [comment]
Yeah I tryed that and it run fine. I just dont understand why it can't read mine.

**Comment by jts** [comment]
Are the files readable by a different program? Can you try 

```
h5dump ./Fast5/FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_0.fast5
```

**Comment by Hannah1746** [comment]
This is what I get:
h5dump error: unable to open file "./Fast5/FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_0.fast5"
But when I go ls -lh:
-rwxrwxrwx 1 krablab krablab 134M Sep 23  2019 FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_0.fast5
-rwxrwxrwx 1 krablab krablab 300M Sep 23  2019 FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_10.fast5
-rwxrwxrwx 1 krablab krablab 230M Sep 23  2019 FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_1.fast5
-rwxrwxrwx 1 krablab krablab 273M Sep 23  2019 FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_2.fast5
-rwxrwxrwx 1 krablab krablab 295M Sep 23  2019 FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_3.fast5
-rwxrwxrwx 1 krablab krablab 287M Sep 23  2019 FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_4.fast5
-rwxrwxrwx 1 krablab krablab 297M Sep 23  2019 FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_5.fast5
-rwxrwxrwx 1 krablab krablab 291M Sep 23  2019 FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_6.fast5
-rwxrwxrwx 1 krablab krablab 310M Sep 23  2019 FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_7.fast5
-rwxrwxrwx 1 krablab krablab 319M Sep 23  2019 FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_8.fast5
-rwxrwxrwx 1 krablab krablab 310M Sep 23  2019 FAL18771_6f89527d9b9722df12e130826ac0682ad600a037_9.fast5

**Comment by Hannah1746** [comment]
Hey Jared,

I don't want to be a bother but do you have any ideas on my problem so I can get nanopolish up and running?

Hannah

**Comment by jts** [comment]
Hi Hannah,

I'm sorry but I think that since `h5dump` is unable to read the files too, then the problem is beyond nanopolish. I'm not sure what the problem could be since the permissions look OK, and the files look to be the right size. Were you able to basecall these reads?

Jared

**Comment by Hannah1746** [comment]
Yes I have one individual that was recalled with guppy V5 and another that was called with sequencing with V3.

**Comment by jts** [comment]
Would you be able to send me one of the fast5 files, and the corresponding fastq?

**Comment by Hannah1746** [comment]
It seems to not support that file type here. Can I get an email for you or you can email me hwaterma@buffalo.edu

**Comment by Hannah1746** [comment]
Moved to our other computer and it runs fine. Must be something weird with our system.

**Comment by jts** [comment]
Glad to hear it, thanks for reporting back!
