### ISSUE TITLE
Error: could not load the index files for input file

### ISSUE THREAD

**Issue by AlfredUg** [jts/nanopolish#919]
Heya @jts 

We have a draft assembly generated using `racon` and trying to generate a polished assembly using `nanopolish`. 

The command is as below;
`nanopolish variants --consensus -o polished.vcf -r sample.fasta -b sample_sorted.bam -g reads_final.fa`.

The error I get is as stated below;
`error: could not load the index files for input file - Please run nanopolish index on your reads (see documentation)`.

Any help is highly appreciated.
Thanks.

**Comment by jts** [comment]
Is it possible you’ve swapped the arguments to -g and -r?

Jared

**Comment by AlfredUg** [comment]
Thanks @jts, True, I had swapped the arguments. 

Upon fixing that, I get another error requiring me to specify the region via `-w`.
`Error: genome has multiple contigs, please use -w to specify input region`.

However, when I try to specify the region for example "utg000001c:0-187", I get the following error.
`error: faidx could not get contig length for contig utg000001c`.

How would go around this? Is there way to get consensus by considering all the contigs without specifying for just one contig?

Thanks.

**Comment by jts** [comment]
Hi @AlfredUg,

Our recommendation is to use `parallel` to polish the genome in regions - we describe how here: https://github.com/jts/nanopolish#computing-a-new-consensus-sequence-for-a-draft-assembly

Jared

**Comment by AlfredUg** [comment]
Thanks @jts, I will try this and see how it goes.

**Comment by AlfredUg** [comment]
Hi @jts

I have followed the example in the tutorial and this seems to work without errors. However I get an empty vcf file.

The command run; `nanopolish_makerange.py ../draft_assembly/barcode2/reads_final.fa | parallel --results nanopolish.results -P 7 nanopolish variants --consensus -o polished.{1}.vcf -w {1} -r ../barcoded/barcode2.fastq -b barcode2_sorted.bam -g ../draft_assembly/barcode2/reads_final.fa -t 2`.

Upon opening the created `.vcf` file, it is only the header section that is displayed as shown in the screen shot below.

<img width="1635" alt="Screen Shot 2021-08-05 at 21 09 58" src="https://user-images.githubusercontent.com/24940585/128400383-7baded81-14fb-489d-865e-0b1f51834087.png">

What could be the issue in this case? 

Thanks,
Alfred.

**Comment by jts** [comment]
Hi Alfred,

In the example you posted, the contig you're trying to polish is only 187bp, which is too short for nanopolish. Are all the VCF files that you generated empty?

Jared
