### ISSUE TITLE
Guppy Basecaller and Nanopolish Methylation

### ISSUE THREAD

**Issue by fidibidi** [jts/nanopolish#920]
Hello!

I have some questions related to the verbiage of getting the methylation calling to work. 

1. I am generating basecalls, mappings, and mod mappings using Megalodon, but wanted to compare the output with that of Nanopolish. Can I use the basecalled files, to do the nanopolish indexing? It is mentioned that the summary file speeds up the process as well, sequencing_summary.txt. I assume so, because basecalling is done with Guppy. 

2. I'm confused because there are a lot of references to albacore and albacore 2.0, is the synonymous with Guppy? Pardon my ignorance!

**Comment by jts** [comment]
Nanopolish will work fine with guppy's basecalls. Albacore is an older version, we will update the documentation to refer to guppy instead. Thanks for pointing that out.

Jared
