### ISSUE TITLE
error on nanopolish_makerange.py

### ISSUE THREAD

**Issue by Janjira19** [jts/nanopolish#921]
I am analyzing Enterovirus genome (about 7 kb). I used nanopolish to polish the canu genome assembly.  I got 1-3 contigs for each assembly ranging 1.5-6kb per contig. I used nanopolish_makerange.py to polish all contigs in parallel as command below. 
However, I got an error like below.

+ for f in /mnt/d/Ana_TrHFM/CanuTriAs_TrHFM001/TrAsB001_B001_barcode*/B001_B001_barcode*.contigs.fasta
++ date +%d%m%y_%H%M
+ NOW=100821_1526
+ DIRA=/mnt/d/Ana_TrHFM/merged_TrHFM001/
+ DIRB=/mnt/d/Ana_TrHFM/NanoPL2
+ PNAME=barcode01.contigs.fasta
+ NAME=barcode01
+ echo barcode01 /mnt/d/Ana_TrHFM/merged_TrHFM001/
barcode01 /mnt/d/Ana_TrHFM/merged_TrHFM001/
+ bwa index /mnt/d/Ana_TrHFM/CanuTriAs_TrHFM001/TrAsB001_B001_barcode01/B001_B001_barcode01.contigs.fasta
[bwa_index] Pack FASTA... 0.00 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.00 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Pack forward-only FASTA... 0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.00 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index /mnt/d/Ana_TrHFM/CanuTriAs_TrHFM001/TrAsB001_B001_barcode01/B001_B001_barcode01.contigs.fasta
[main] Real time: 0.259 sec; CPU: 0.000 sec
+ for i in ${DIRA}${NAME}_merged.fastq
+ echo /mnt/d/Ana_TrHFM/merged_TrHFM001/barcode01_merged.fastq
/mnt/d/Ana_TrHFM/merged_TrHFM001/barcode01_merged.fastq
+ for j in /mnt/d/TrHFM_001/fast5_pass/${NAME}
+ OUT=/mnt/d/Ana_TrHFM/NanoPL2barcode01ContigPoL_sorted2.bam
+ echo /mnt/d/TrHFM_001/fast5_pass/barcode01 /mnt/d/Ana_TrHFM/NanoPL2barcode01ContigPoL_sorted2.bam
/mnt/d/TrHFM_001/fast5_pass/barcode01 /mnt/d/Ana_TrHFM/NanoPL2barcode01ContigPoL_sorted2.bam
+ nanopolish index -d /mnt/d/TrHFM_001/fast5_pass/barcode01 -s /mnt/d/TrHFM_001/sequencing_summary_FAP69708_53b1acc3.txt /mnt/d/Ana_TrHFM/merged_TrHFM001/barcode01_merged.fastq
[readdb] indexing /mnt/d/TrHFM_001/fast5_pass/barcode01
[readdb] num reads: 87169, num reads with path to fast5: 87169
+ bwa mem -t 14 -x ont2d /mnt/d/Ana_TrHFM/CanuTriAs_TrHFM001/TrAsB001_B001_barcode01/B001_B001_barcode01.contigs.fasta /mnt/d/Ana_TrHFM/merged_TrHFM001/barcode01_merged.fastq
+ samtools sort -o /mnt/d/Ana_TrHFM/NanoPL2barcode01ContigPoL_sorted2.bam -T reads.tmp -
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 87169 sequences (50413735 bp)...
[M::mem_process_seqs] Processed 87169 reads in 330.844 CPU sec, 43.268 real sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -t 14 -x ont2d /mnt/d/Ana_TrHFM/CanuTriAs_TrHFM001/TrAsB001_B001_barcode01/B001_B001_barcode01.contigs.fasta /mnt/d/Ana_TrHFM/merged_TrHFM001/barcode01_merged.fastq
[main] Real time: 44.473 sec; CPU: 331.859 sec
+ samtools index /mnt/d/Ana_TrHFM/NanoPL2barcode01ContigPoL_sorted2.bam
+ python3 /home/janjira/anaconda3/envs/myEnv/bin/nanopolish_makerange.py /mnt/d/Ana_TrHFM/CanuTriAs_TrHFM001/TrAsB001_B001_barcode01/B001_B001_barcode01.contigs.fasta
+ parallel --results nanopolish.results -P 4 nanopolish variants --consensus -o '/mnt/d/Ana_TrHFM/NanoPL2barcode01Pol.{1}.vcf' -w '{1}' -r /mnt/d/Ana_TrHFM/merged_TrHFM001/barcode01_merged.fastq -b /mnt/d/Ana_TrHFM/NanoPL2barcode01ContigPoL_sorted2.bam -g /mnt/d/Ana_TrHFM/CanuTriAs_TrHFM001/TrAsB001_B001_barcode01/B001_B001_barcode01.contigs.fasta -t 2 --min-candidate-frequency 0.1
Nanopolish2.sh: line 27: parallel: command not found
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe

**Comment by jts** [comment]
Hi,

You need to install `parallel`, which you can find on conda.

Jared

**Comment by Janjira19** [comment]
Hi Jared
Thank you for your kind response. I did not realize that "parallel" is a command.
Janjira
