### ISSUE TITLE
No Methylation Calls on Zymo Methylation Standards

### ISSUE THREAD

**Issue by cmmonaco** [jts/nanopolish#923]
Hello. I've been attempting to identify methylated bases from nanopore sequencing data of Zymo DNA methylation standards (Zymo catalog #D5405), however, after running call-methylation, the output file only contains headers. The post-run summary is showing up so I know the program is completing without an error. The only deviation from your quickstart guide I took when processing this is data was to not provide the call-methylation function with the -w argument, as the reference I'm aligning to is the sequence is the complete range so there's no sub-region to reference. Could this be the reason that I'm not getting any methylation calls?

**Comment by jts** [comment]
Hi,

It should work fine without the -w argument. Could I see the post run summary message?

Jared

**Comment by cmmonaco** [comment]
Sure thing:

`[post-run summary] total reads: 1670, unparseable: 0, qc fail: 1, could not calibrate: 1, no alignment: 6, bad fast5: 0`

**Comment by jts** [comment]
Hm, looks fine. Do the read mappings look ok (mapq > 20)?
