### ISSUE TITLE
Nanopolish call-methylation HDF5 error

### ISSUE THREAD

**Issue by AnunayS** [jts/nanopolish#930]
I am also facing a similar issue raised by gottaMe 3 days ago. I looked into the comments 206 and 403 and tried those also but still I am getting the same error.

I tried it on ubuntu 20.04 as well as WSL on windows 10.

Both of them are showing the same error.

But I was able to run the same command last month on WSL, so I am not sure whether it is some new release that is causing the issue or the installation is not proper.

It would of great help if you could look into the error paste below and help me out with the issue.

the error is as below:

HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140235507894016:
  #000: ../../../src/H5Dio.c line 199 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: ../../../src/H5Dio.c line 601 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: ../../../src/H5Dchunk.c line 2229 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: ../../../src/H5Dchunk.c line 3609 in H5D__chunk_lock(): data pipeline read failed
    major: Dataset
    minor: Filter operation failed
  #004: ../../../src/H5Z.c line 1301 in H5Z_pipeline(): required filter 'vbz' is not registered
    major: Data filters
    minor: Read failed
  #005: ../../../src/H5PLint.c line 270 in H5PL_load(): search in path table failed
    major: Plugin for dynamically loaded library
    minor: Can't get value
  #006: ../../../src/H5PLpath.c line 604 in H5PL__find_plugin_in_path_table(): search in path /usr/lib/x86_64-linux-gnu/hdf5/plugins encountered an error
    major: Plugin for dynamically loaded library
    minor: Can't get value
  #007: ../../../src/H5PLpath.c line 656 in H5PL__find_plugin_in_path(): can't open directory: /usr/lib/x86_64-linux-gnu/hdf5/plugins
    major: Plugin for dynamically loaded library
    minor: Can't open directory or file
nanopolish: src/nanopolish_squiggle_read.cpp:321: void SquiggleRead::load_from_raw(fast5_file&, uint32_t): Assertion `rt.n > 0' failed.
Aborted (core dumped)

**Comment by jts** [comment]
Hi,

In this case, the VBZ decompression plugin is missing. Please follow the instructions here: https://github.com/nanoporetech/vbz_compression/issues/5
