### ISSUE TITLE
Mapping Quality option

### ISSUE THREAD

**Issue by vahidAK** [jts/nanopolish#931]
Hi @jts,
I hope you are doing well,

In the newer versions of nanopolish, you have implemented a mapping quality of more than 20 during methylation calling. But, as far as I am aware, there is no option in the tool to specify mapping quality in case we were interested in other low-quality mapped reads.
Comparing to older versions it results in detecting about 1-2M less CGs. Does it mean those CGs called by older versions are not reliable at all? 
Do you have any plan to add an option to specify mapping quality for the tool during methylation calling?

Many thanks,
Vahid

**Comment by jts** [comment]
Hi @vahidAK,

> Comparing to older versions it results in detecting about 1-2M less CGs. Does it mean those CGs called by older versions are not reliable at all?

I haven't made this comparison, and I think it would be difficult to do so as if a nanopore read has low mapping quality it is unlikely that the bisulfite data we'd compare to maps well. So it is hard to say whether the calls are reliable or not.

> Do you have any plan to add an option to specify mapping quality for the tool during methylation calling?

Sure, I can make this an option. I'll leave this issue open until I do so.

Jared

**Comment by vahidAK** [comment]
Thanks a lot, @jts 

It would be great if you add the option

**Comment by jts** [comment]
I just added this in the latest commit, give it a try
