### ISSUE TITLE
HDF5 VBZ plugin for methylation calling

### ISSUE THREAD

**Issue by daanverhagen** [jts/nanopolish#932]
Hello @jts,

im at a total loss how to identify the correct HDF_PLUGIN_PATH for the HDF5 plugin that is required for methylation calling using nanopolish. Im aware of the several issues that have been generated and the issue that should resolve it (https://github.com/nanoporetech/vbz_compression/issues/5).

however im running into the issue that no matter what package I download/install, i cannot locate the path with the HDF5 plugin. Im running a virtual environment using conda (python=2.7 if that may matter), and installing any of the HDF5 packages on anaconda.org does not result in any usable folders with the correct plugin. The closest folder structure similar to that in the issue linked above is when i install the ont_vbz_hdf_plugin from nanoporetech, but even that one does not seem to resolve the issue.

my question is: what package do i install to acquire the correct plugin folder. any help would be greatly appreciated.

kind regards,
Daan

**Comment by jts** [comment]
Hi Daan,

Make sure that you are setting the environment variable `HDF5_PLUGIN_PATH`, not `HDF_PLUGIN_PATH`.

Here's the steps I follow:

```
wget https://github.com/nanoporetech/vbz_compression/releases/download/v1.0.1/ont-vbz-hdf-plugin-1.0.1-Linux-x86_64.tar.gz
tar -xzf ont-vbz-hdf-plugin-1.0.1-Linux-x86_64.tar.gz
# this puts the plugin in $PWD/ont-vbz-hdf-plugin-1.0.1-Linux/usr/local/hdf5/lib/plugin/libvbz_hdf_plugin.so
export HDF5_PLUGIN_PATH=/home/jsimpson/ont-vbz-hdf-plugin-1.0.1-Linux/usr/local/hdf5/lib/plugin/libvbz_hdf_plugin.so
```

**Comment by daanverhagen** [comment]
Hi,

thanks for your detailed comment and my mistake for the typo.

I think it should be somewhere clarified (perhaps in this issue for later reference, or in the error code from nanopolish) which plugin should be exactly downloaded. After a fresh installation of Miniconda3 I installed the ont_vbz_hdf_plugin from[( https://anaconda.org/bioconda/ont_vbz_hdf_plugin)]. As a side note, none of the HDF5 plugins available from anaconda.org/hdfgroup.org will work. Only the ont_vbz_hdf_plugin from nanoporetech places a plugin hdf5 folder within the /envs/<your_env> folder. This folder holds the actual hdf5 plugin to be used and can be exported as:

 `export HDF5_PLUGIN_PATH=/<your_folder_structure>/hdf5/lib/plugin/`

To me (as a novice) this was not documented anywhere, and hopefully will clear things up for others who are looking for a similar issue. I have not tested your steps, but i assume it will be identical as you acquire the package from nanoporetech's github directly.

Ill consider this issue closed now. thanks for your help.
