### ISSUE TITLE
Empty output file for nanopolish call-methylation running on dRNA seq data

### ISSUE THREAD

**Issue by AnunayS** [jts/nanopolish#934]
I am running dRNA sequencing for mammalian RNA on GridIon.

The output file for nanopolish call-methylation is empty with just the headers. It takes 3-4 hours to run on a workstation and still generating an empty output file.

However when I did for lamda control DNA seq data, the output file is generated nicely.

Please let me know what can I do to sort the issue.

Thankyou.

**Comment by jts** [comment]
Hi,

I’m sorry but nanopolish can’t call methylation from dRNA data.

Jared

**Comment by AnunayS** [comment]
Will it be okay of I basecall the dRNA raw files using guppy configuration "dna_r9.4.1_450bps_hac.cfg" and then do the methylation calling.

**Comment by jts** [comment]
Unfortunately that won't work, the basecalling models need to match whatever you sequenced.
