### ISSUE TITLE
Empty methylation calling output

### ISSUE THREAD

**Issue by StevenVerbruggen** [jts/nanopolish#935]
Hi Jared,

Thanks for your wonderful tool to call methylation in nanopore data.

For one subset of reads (55 reads in total) however, I seem to not be able to generate meth calling results and I do not see what is causing this. Hopefully you can help.

I do the following steps:
```
#Change fast5 compression from VBZ to gzip
compress_fast5 --input_path ./set1_fast5/ --save_path ./fast5_gzip/ --compression gzip --threads 20

#Nanopolish indexing
nanopolish index -d ./fast5_gzip/ ./tmp.fastq
```
This generates:
```
[readdb] indexing /data2/steven/OHMX/Facio_collab/OHMX20210039_Facio/fshd_analysis/tmp/barcode02//methylation/set1//fast5_gzip/
[readdb] num reads: 55, num reads with path to fast5: 55
```
Then I do:
```
#Map indexed info to reference genome
minimap2 -t 20 -a -x map-ont ./genome.fa ./tmp.fastq | samtools sort -T tmp -o ./output.sorted.bam
samtools index ./output.sorted.bam
```
The used genome here is human GRCh38 from Ensembl. This generates:
```
[M::mm_idx_gen::100.938*1.70] collected minimizers
[M::mm_idx_gen::128.986*2.31] sorted minimizers
[M::main::128.986*2.31] loaded/built the index for 25 target sequence(s)
[M::mm_mapopt_update::131.874*2.28] mid_occ = 702
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 25
[M::mm_idx_stat::133.109*2.27] distinct minimizers: 100128857 (38.82% are singletons); average occurrences: 5.521; average spacing: 5.586; total length: 3088286401
[M::worker_pipeline::133.748*2.31] mapped 55 sequences
[M::main] Version: 2.22-r1101
[M::main] CMD: minimap2 -t 20 -a -x map-ont ./genome.fa ./tmp.fastq
[M::main] Real time: 134.059 sec; CPU: 309.594 sec; Peak RSS: 11.104 GB
```
Then I do:
```
nanopolish call-methylation -t 20 -r ./tmp.fastq -b ./output.sorted.bam -g ./genome.fa -w "4:190,064,999-190,175,984"
```
This generates:
```
[bam process] iterating over region: 4:190,064,999-190,175,984
```
It generates no calls (only headers) and also the post-run summary line is not printed.

I included the input files of this subset with this message here:
[set1_fast5.zip](https://github.com/jts/nanopolish/files/7155558/set1_fast5.zip)
[tmp.fastq.zip](https://github.com/jts/nanopolish/files/7155561/tmp.fastq.zip)
[output.sorted.bam.zip](https://github.com/jts/nanopolish/files/7155563/output.sorted.bam.zip)
[fast5_gzip.zip](https://github.com/jts/nanopolish/files/7155546/fast5_gzip.zip)

Nanopolish version 0.13.2 is installed through bioconda. Process was run on a machine of >300Gb RAM. I do not think RAM is the problem as I did a test in which I added a read from another subset to this problematic subset (a read from which I know it generated calls in another subset). The subset with the extra read (so 56 reads in total) did generate meth calls, but only from the added read. 
This expanded read set gave following post run summary:
```
[post-run summary] total reads: 2, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 0
```
Small site question here maybe, from these 56 reads only 2 reads seem to be included in the total read summary. Why 2? Why are the other reads dropped out? On other subsets that do generate meth calls, I often see that only a small portion is included in the post-run summary. Would also be nice to have some info on this if possible.

Would be nice to know what the problem is with this specific subset though. Read lengths are in between 7K and 31K. Read qualities vary from 17 to 23 (based on a quick FastQC analysis)

Thanks for your help in any case and let me know if I could provide any other information that could be helpful.

Best,

Steven

**Comment by jts** [comment]
Could you attach the genome file as well?

**Comment by jts** [comment]
Actually i don't think I need the genome, the problem is that none of the reads have mapping quality >= q20:

```
samtools view output.sorted.bam 4:190,064,999-190,175,984 | awk '$5 >= 20'
```

**Comment by StevenVerbruggen** [comment]
Aha, that explains a lot. Based on previous issues here, I thought the raw read phred score had to be >= 20.
But ok, so the mapping quality of the reads will definitely cause the problem here, they are indeed below 20 for this specific subset. That is probably also the cause why there is only a small portion of the reads given in the post-run summary for other subsets of reads I analysed earlier?

Mapping qualities are not that high because the region I want to analyse is highly variable due to a differing number of repeats in different samples. Is there a way to circumvent this? A parameter to lower the mapping quality threshold? I could also construct a custom reference per reads subset to boost the mapping quality, because the number of repeats is known before I start the methylation analysis, although this will be a more laborious approach. The reads, which are included in the subset, are in any case already selected for descent mapping towards the ROI priorly, so unless it is necessary for the Nanopolish methylation calling, selection of reads based on mapping quality is not necessarily required for this use case.

**Comment by jts** [comment]
If you install the latest version from github (this version isn't on conda yet) there is a new `--min-mapping-quality` parameter, which you can use to lower this threshold.

**Comment by StevenVerbruggen** [comment]
All right. I will give it try! Thanks in any case for all help and info
