### ISSUE TITLE
eventalign segmentation (core dumped) error

### ISSUE THREAD

**Issue by samir-watson** [jts/nanopolish#937]
Hi,
I have been using eventalign with no problems for a while now, however very recently I am getting a segmentation fault error with the core being dumped on only my most recent sequencing runs. The only thing that I can think of that has changed is the version of minKNOW that I am using but I cant see how this would be related. When I run eventalign on my older data it works perfectly fine. 
I am using guppy 4.0.11 for basecalling and using the nanopolish  0.13.0 from conda
the script im using is
`nanopolish eventalign -t 8 --reads /home/samirwatson/faststorage/GFP_DRS/basecalled/GFP_pool_1_DRS_2.fastq --bam /home/samirwatson/faststorage/GFP_DRS/analysis/genome_aligned/GFP_pool_1_DRS_2.genome.aligned.bam --genome /home/samirwatson/faststorage/GFP_DRS/GFP_genomes/2GFP+GRCh38.p13.genome.fa  --print-read-names --scale-events --samples > /home/samirwatson/faststorage/GFP_DRS/analysis/genome_aligned/GFP_pool_1_DRS_2.genome.aligned.eventalign.tsv
`
and have given it plenty of RAM - 240GB

**Comment by jts** [comment]
Could you try the latest version of nanopolish from github instead of the conda version?

**Comment by samir-watson** [comment]
Yes this worked, I think the problem was vbz compression which is now on by default in minKNOW 4.0+. It may be useful to include a note in the readme to install the nanopore vbz hdf5 plugin as that was not immediately apparent as a requirement. With this installed the older conda version again worked.
