### ISSUE TITLE
Variant calling performance against maximum haplotype threshold

### ISSUE THREAD

**Issue by hiruna72** [jts/nanopolish#941]
Hi Jared,
I ran 3 variant calling tests with different `max-haplotypes` thresholds for some selected regions of the human genome using a NA12878 dataset. I was hoping to observe better ROC curves with the increased threshold values. However, the curves almost overlap each other. Is this the intended behavior? What other parameters can I tweak to get better results if possible?

![image](https://user-images.githubusercontent.com/23216727/135793742-6de8f770-4d9f-4e9b-b366-c94ebb0c8eee.png)

PS - even with a 10000 threshold value, for some regions I still got the following warning .
`Number of variants in span (%lu) would exceed max-haplotypes. Variants may be missed. Consider running with a higher value of max-haplotypes!`

**Comment by jts** [comment]
This parameter controls how hard nanopolish tries in difficult regions of the genome. If there are many possible candidates nanopolish will first try to generate all haplotypes (up to `--max-haplotypes`) but then falls back to trying fewer combinations of variants instead (for example pairs of candidates). As variant calling is naturally very difficult when there are many candidate variants (e.g. low complexity sequence) it is not unexpected that this parameter doesn't do much in practice.

**Comment by hiruna72** [comment]
Hi Jared,

Thank you very much for the information.
