### ISSUE TITLE
methylation of large non-singletons 

### ISSUE THREAD

**Issue by SkabbiVML** [jts/nanopolish#943]
Hi jts

I've been performing cas9 targetted sequencing on a CpG island located in a gene promoter region and using Nanopolish to call methylation of CpGs in the ROI. Some areas within this CpG island are quite dense with CpGs, resulting in numerous non-singleton calls. One of these non-singleton clusters contains 10 CpGs which are called as a single event. In reality, it's more like two very dense clusters of 5 CpGs each, separated by 8 nucleotides. I've been working under the assumption that if CpGs are very close, they tend to have the same methylation status as their closest neighbor. 

A recent publication that performed pysosequencing on the same promoter region in 215 samples showes that CpGs within the two clusters of 5 CpGs mentioned above almost always share methylation status, all or none. However, in about 25% of cases, the two clusters of 5 CpGs have opposite methylation status, one methylated, the other not. This leads me to a couple of questions regarding how Nanopolish works.

1. In the case of a large non-singleton event where some of the CpGs are methylated while others are not, how does Nanopolish call it? Is it a question of detecting methylation anywhere in the non-singleton or is it more complicated then that?
2. Are the 9 nucleotides between CpGs that currently define individual events (singleton or non-singleton) a parameter that can be set? In other words, is it possible to set this to something else, for example 8 nucleotides, therby breaking up some of the large non-singleton events?

I'd really appreciate if you could shed some light on this.

Thanks in advance

S

**Comment by jts** [comment]
Hi @SkabbiVML,

Thanks for the questions, this is something I've been thinking about recently.

> In the case of a large non-singleton event where some of the CpGs are methylated while others are not, how does Nanopolish call it? Is it a question of detecting methylation anywhere in the non-singleton or is it more complicated then that?

It is more complicated - nanopolish calculates a log-likelihood ratio between the entire group being methylated vs the entire group being not methylated (exact details are in [here](https://www.nature.com/articles/nmeth.4184)). It is tempting to interpret the output call as something like "most of the CpGs in the group are methylated" (or vice versa) but I'm not sure if this is entirely valid.

> Are the 9 nucleotides between CpGs that currently define individual events (singleton or non-singleton) a parameter that can be set? In other words, is it possible to set this to something else, for example 8 nucleotides, therby breaking up some of the large non-singleton events?

Yes, you can change the `--min-separation` parameter to control the grouping. The default is 10, which I now feel is too conservative. I have internal tests that show smaller groupings work nearly as well, and may change this default in a future release. If you experiment with this value please let me know how it goes as the feedback might help me decide on how to change the default.

Thanks,
Jared

**Comment by SkabbiVML** [comment]
Thanks so much for the quick reply @jts, I really appreciate it!

I'll re-run some of the analysis I've done so far with a more relaxed grouping parameter. I'll let you know how it goes.

Cheers

S
