### ISSUE TITLE
Nanopolish goes into "uninterruptible sleep" (D) mode 

### ISSUE THREAD

**Issue by kaltinel** [jts/nanopolish#944]
Hi!
I am trying to use `nanopolish eventalign`, however the tool goes into `D` state as if asking for `I/O` interuption, after 38 seconds:
![84](https://user-images.githubusercontent.com/47667755/136180475-4b0e22dd-75cc-4650-b7b6-c0773fe401de.png)

My command is as follows:
`
nanopolish eventalign --reads reads.fa --bam sorted_aligned.bam -t 10 --genome whole_curated.fa --summary=summary_eventalign.txt --scale-events > results.eventalign.txt`

The version is:
```
nanopolish version 0.13.2
Written by Jared Simpson.

Copyright 2015-2017 Ontario Institute for Cancer Research
```

I would be happy to have your help.
Thanks

**Comment by jts** [comment]
Hi,

That likely means it is waiting on I/O. If you leave it for awhile does it make any progress?

Jared
