### ISSUE TITLE
Error: H5Z_pipeline(): required filter 'vbz' is not registered

### ISSUE THREAD

**Issue by rckeerthivasan** [jts/nanopolish#945]
Hi, 

I have a bunch of samples. When I am processing one of the samples, I receive this error. 

`HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 123145433067520:
  #000: H5Dio.c line 173 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: H5Dio.c line 554 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: H5Dchunk.c line 1875 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: H5Dchunk.c line 2905 in H5D__chunk_lock(): data pipeline read failed
    major: Data filters
    minor: Filter operation failed
  #004: H5Z.c line 1347 in H5Z_pipeline(): required filter 'vbz' is not registered
    major: Data filters
    minor: Read failed
  #005: H5PL.c line 358 in H5PL_load(): search in paths failed
    major: Plugin for dynamically loaded library
    minor: Can't get value
  #006: H5PL.c line 475 in H5PL__find(): can't open directory: ont-vbz-hdf-plugin-1.0.1-Linux/usr/local/hdf5/lib/plugin/libvbz_hdf_plugin.so
    major: Plugin for dynamically loaded library
    minor: Can't open directory or file
`

Now, I am aware of the issues regarding some hdf5 missing plugin for VBZ compression/decompression. https://github.com/jts/nanopolish/issues/932 and https://github.com/nanoporetech/vbz_compression/issues/5

I tried to follow the solutions in the above issues, such as h5repack and installing plugin using wget somewhere and exporting the path. they do not work. Could you provide any insights? 

Other details:
OS: MacOS Big Sur
python version being used: 3.7.11
installed nanopolish using condo.

Thank you, 
Ken.

**Comment by rckeerthivasan** [comment]
the updated message would be `H5PL.c line 475 in H5PL__find(): can't open directory: /Users/creminsimacs27/softwares/nanopolish.v2/ont-vbz-hdf-plugin-1.0.1-Linux/usr/local/hdf5/lib/plugin/libvbz_hdf_plugin.so`

**Comment by jts** [comment]
Oh, I think I see the issue. I think you've installed the Linux version of the plugin but should have installed the MacOS version. Can you try this one: https://github.com/nanoporetech/vbz_compression/releases/download/v1.0.1/ont-vbz-hdf-plugin-1.0.1-Darwin.pkg

**Comment by rckeerthivasan** [comment]
The solution is 

1) install 'https://github.com/nanoporetech/vbz_compression/releases/download/v1.0.1/ont-vbz-hdf-plugin-1.0.1-Darwin.pkg' from vbz GitHub release page. 
2) export HDF5_PLUGIN_PATH=/usr/local/hdf5/lib/plugin/
