### ISSUE TITLE
nanopolish variants threads

### ISSUE THREAD

**Issue by igordot** [jts/nanopolish#95]
Based on the README, the suggested command to compute the consensus sequence is to use `nanopolish_makerange.py` to generate windows and then pipe them to `nanopolish variants` using `parallel`. Since `nanopolish variants` has a `--threads` argument, why use `parallel` on top of that?

I tried using just the `nanopolish variants --threads 16` (without `parallel`), but my actual CPU usage is only around 20-30%. Is it not working the way I think it should be? Could that be why you suggest using `parallel`?

**Comment by jts** [comment]
Hi,

Only parts of nanopolish are multi-threaded so you may have seen CPU usage at one of the single-threaded (probably I/O bound) parts. The HMM calculations use multiple threads but only start after the reads are loaded.

Calculating a consensus sequence takes quite awhile and there is a limit to how much multithreading helps, so it is recommended to parallelize across multiple machines. The `parallel` workflow can be easily modified to submit jobs to an HPC system, so I used it as an example in the README.
