### ISSUE TITLE
What is nanopolish best for nowadays?

### ISSUE THREAD

**Issue by harisankarsadasivan** [jts/nanopolish#952]
Given the emergence of ML based methods for variant and methylation calling,
what is nanopolish "the best" for now-a-days? Who uses nanopolish and when?
Please dont get me wrong, I know nanopolish is popular, but I wanted to understand this situation better.
Pls reply to hariss@umich.edu

**Comment by oneillkza** [comment]
Nanopolish methylation calling has pretty consistently out-performed the fancier deep learning methods for a while now. That's been both in our hands and in the hands of other groups who've done their own benchmarking.

But this may be changing with the more recent versions of Megalodon. Also it looks like Nanopolish may not support the new Q20+ chemistry.

**Comment by jts** [comment]
Thanks @oneillkza! We haven't trained a model for Q20 yet (or even tested nanopolish on it) but as it becomes more widely adopted we will. If you have tried it out already I'd be happy to hear your feedback on whether it worked or not.
