### ISSUE TITLE
Nanopolish index could not open fast5 files that could be opened by other tools/scripts

### ISSUE THREAD

**Issue by ravinkazo** [jts/nanopolish#954]
Hello everyone,

While running nanopolish index (as part of the Artic pipeline) I got a lot of error messages, which seem to be caused by nanopolish not being able to open my fast5 files (error messages attached below).
Strangely, when I tried opening the same fast5 files with other tools (for example, using ls), they could be opened with no issues.

The version of nanopolish that I have is 0.13.2. This was installed via conda installation of Artic pipeline (https://github.com/artic-network/artic-ncov2019).

I would truly appreciate your help.
Many thanks!

Error messages:
----------------
[readdb] indexing /home/ubuntu/environment/NANOPORE/2021_Nanopore
could not open fast5 file: /home/ubuntu/environment/NANOPORE/2021_Nanopore/recovered_66bb81cc-de10-49bc-bd57-c2be922aa6d8_1021.fast5
could not open fast5 file: /home/ubuntu/environment/NANOPORE/2021_Nanopore/recovered_66bb81cc-de10-49bc-bd57-c2be922aa6d8_1020.fast5
[readdb] num reads: 17522640, num reads with path to fast5: 17522640
[M::mm_idx_gen::0.002*1.56] collected minimizers
[M::mm_idx_gen::0.003*4.22] sorted minimizers
[M::main::0.003*4.20] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.003*3.94] mid_occ = 3
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.003*3.74] distinct minimizers: 5587 (99.93% are singletons); average occurrences: 1.004; average spacing: 5.332
[M::worker_pipeline::4.622*5.36] mapped 137191 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -a -x map-ont -t 12 /home/ubuntu/environment/artic-ncov2019/primer_schemes/nCoV-2019/V3/nCoV-2019.reference.fasta 2021_Nanopore_barcode04.fastq
[M::main] Real time: 4.635 sec; CPU: 24.780 sec; Peak RSS: 0.194 GB
HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 139628948449024:
  #000: H5Dio.c line 173 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: H5Dio.c line 554 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: H5Dchunk.c line 1875 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: H5Dchunk.c line 2905 in H5D__chunk_lock(): data pipeline read failed
    major: Data filters
    minor: Filter operation failed
  #004: H5Z.c line 1347 in H5Z_pipeline(): required filter 'vbz' is not registered
    major: Data filters
    minor: Read failed
  #005: H5PL.c line 358 in H5PL_load(): search in paths failed
    major: Plugin for dynamically loaded library
    minor: Can't get value
  #006: H5PL.c line 475 in H5PL__find(): can't open directory: /home/ubuntu/miniconda3/envs/artic-ncov2019/lib/hdf5/plugin
    major: Plugin for dynamically loaded library
    minor: Can't open directory or file
HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 139628982019840:
  #000: H5Dio.c line 173 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: H5Dio.c line 554 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: H5Dchunk.c line 1875 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: H5Dchunk.c line 2905 in H5D__chunk_lock(): data pipeline read failed
    major: Data filters
    minor: Filter operation failed
  #004: H5Z.c line 1347 in H5Z_pipeline(): required filter 'vbz' is not registered
    major: Data filters
    minor: Read failed
  #005: H5PL.c line 358 in H5PL_load(): search in paths failed
    major: Plugin for dynamically loaded library
    minor: Can't get value
  #006: H5PL.c line 475 in H5PL__find(): can't open directory: /home/ubuntu/miniconda3/envs/artic-ncov2019/lib/hdf5/plugin
    major: Plugin for dynamically loaded library
    minor: Can't open directory or file
HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 139628931663616:
  #000: H5Dio.c line 173 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: H5Dio.c line 554 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: H5Dchunk.c line 1875 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: H5Dchunk.c line 2905 in H5D__chunk_lock(): data pipeline read failed
    major: Data filters
    minor: Filter operation failed
  #004: H5Z.c line 1347 in H5Z_pipeline(): required filter 'vbz' is not registered
    major: Data filters
    minor: Read failed
  #005: H5PL.c line 358 in H5PL_load(): search in paths failed
    major: Plugin for dynamically loaded library
    minor: Can't get value
  #006: H5PL.c line 475 in H5PL__find(): can't open directory: /home/ubuntu/miniconda3/envs/artic-ncov2019/lib/hdf5/plugin
    major: Plugin for dynamically loaded library
    minor: Can't open directory or file
HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 139628990412544:
  #000: H5Dio.c line 173 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: H5Dio.c line 554 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: H5Dchunk.c line 1875 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: H5Dchunk.c line 2905 in H5D__chunk_lock(): data pipeline read failed
    major: Data filters
    minor: Filter operation failed
  #004: H5Z.c line 1347 in H5Z_pipeline(): required filter 'vbz' is not registered
    major: Data filters
    minor: Read failed
  #005: H5PL.c line 358 in H5PL_load(): search in paths failed
    major: Plugin for dynamically loaded library
    minor: Can't get value
  #006: H5PL.c line 475 in H5PL__find(): can't open directory: /home/ubuntu/miniconda3/envs/artic-ncov2019/lib/hdf5/plugin
    major: Plugin for dynamically loaded library
    minor: Can't open directory or file

**Comment by ravinkazo** [comment]
Hi @jts,

Yes, so I ran the Artic pipeline for many different samples, and it always gave exactly the same error messages for the these two files only, no matter which sample it was processing.

**Comment by jts** [comment]
I'm going to guess these files are corrupted or incomplete in some way. Nanopolish will skip them if so, since you have so much data (>1200 fast5s) I doubt it will change the result so I suggest just carrying on without these two.

Jared

**Comment by ravinkazo** [comment]
I see... ok, I have carried on without those two as you suggested.
Thank you so much for your help, much appreciated! :)
