### ISSUE TITLE
Nanopolish called some consensus bases as Ns, while .bam file showed the opposite

### ISSUE THREAD

**Issue by ravinkazo** [jts/nanopolish#955]
Hi @jts,

This is a follow-up on [my other issue](https://github.com/jts/nanopolish/issues/954) (which has been resolved now, thanks to you, thank you so much!).

So I continued running Nanopolish (as part of Artic pipeline) as you suggested, and have now received the output files. But I noticed something strange here. When I compared the .fasta consensus that I got from Artic/Nanopolish to a .fasta consensus that I got from UGENE (I got this by manually exporting the consensus from .bam file on UGENE), there were some differences: 

![check](https://user-images.githubusercontent.com/1311603/139668860-ed450470-c380-4761-bbaf-8e6f7c548ac6.png)

So I checked the original .bam file, and this is what I got:

![bam file](https://user-images.githubusercontent.com/1311603/139668919-1c5d136b-0270-464a-9e7a-5402c086bb04.png)

It seems that Nanopolish called some consensus bases as Ns, while according to .bam they were not Ns and supported by > 100x coverage (starting from 129x).

Another example:
You can see for base position #2569 here, Artic/Nanopolish also called this and its following bases as Ns:
![Screen Shot 2021-11-01 at 7 26 28 PM](https://user-images.githubusercontent.com/1311603/139672172-8d0da12e-85a3-4786-8674-0f777d929598.png)

However, the .bam file shows that base position #2569 has a coverage of 98x:
![bam file 2](https://user-images.githubusercontent.com/1311603/139672226-95f15ac0-3f5e-42c8-81ef-f4025dcd1f2d.png)

I don't understand why they are different.... Am I missing something? Are there some parameters that I have to modify? (I used all the default settings from Artic)

Thank you very much in advance for your time.

**Comment by jts** [comment]
Can you check the primer trimmed bams? The ARTIC pipeline/nanopolish will not include the primer sequences in the coverage calculation so my guess is that these regions fall below the 20x threshold after trimming.

**Comment by ravinkazo** [comment]
Hi @jts, yes indeed! I've now checked the primer trimmed bams and everything is as you explained. 
Thank you so much for this very valuable info! 

But I have another follow-up question, I hope you don't mind.
You mentioned above that 20x was the threshold after trimming.
How exactly does this work in case of deletion?
For instance:

- If I have 300x coverage for the region, but at a particular base the 290 bases are missing (potentially deleted), so I'm left with 10x coverage that consists of different nucleotide bases (let's say 3 As, 3 Cs, 2 Ts and 2 Gs), how would Nanopolish call this in the consensus?

- If I have 300x coverage for the region, but at a particular base the 280 bases are missing (potentially deleted), so I'm left with 20x coverage that consists of different nucleotide bases (let's say 5 As, 5 Cs, 5 Ts and 5 Gs), how would Nanopolish call this in the consensus?

Thank you very much once again for your valuable time and help.

**Comment by jts** [comment]
Internally nanopolish generates alternative haplotypes containing the variants of interest (here, a deletion) and then re-aligns the reads to these haplotypes. The coverage is assessed on the haplotype bearing the deletion so nanopolish doesn't "see" the drop in coverage at the deletion. So, it should handle the two cases you posted above without any problem.

**Comment by ravinkazo** [comment]
Ah I see... so in those two examples that I mentioned, Nanopolish would call them both as . (deletion). What about the following case?

If I have 300x coverage for the region, but at a particular base the 276 bases are missing (potentially deleted), so I'm left with 24x coverage that consists of different nucleotide bases (let's say 6 As, 6 Cs, 6 Ts and 6 Gs), how would Nanopolish call this in the consensus?

Thank you again, much appreciated.

**Comment by jts** [comment]
Nanopolish uses a probabilistic model to determine the consensus sequence. Since the reads with the deletion are by far the most common it is likely that the probability model would score the deletion as the most likely sequence and it would be called.
