### ISSUE TITLE
.fastq or .fast.qz

### ISSUE THREAD

**Issue by Flower9618** [jts/nanopolish#957]
Hi,

Thank you very much for this useful tool. I just wonder if some commands in nanopolish, like 'nanopolish index' and 'nanopolish call-methylation' can work for .fastq.gz file format.

Thanks again.
Rong

**Comment by ravinkazo** [comment]
Hi @Flower9618,
I've never tried using fastq.gz, but you can convert .fastq.gz to fastq easily in batch. 
I usually do:
for f in *.gz; do gunzip $f; done

Hope this helps! :) (I'm only a fellow user, not part of the development team)

**Comment by jts** [comment]
Hi,

Sorry for the slow reply, and thanks @ravinkazo for helping. Nanopolish is able to read gzipped fastq files.

Jared
