### ISSUE TITLE
methylation call-threshold on non-singleton events

### ISSUE THREAD

**Issue by SkabbiVML** [jts/nanopolish#960]
Hi @jts 

I'm running nanopolish on fast5 files to detect promoter methylation on a pretty dense CpG island. After nanopolish, I summarize the results with calculate_methylation_frequency.py

As far as I understand, the default call-threshold in calculate_methylation_frequency set to log_lik_ratio > 2.0 for a singleton event. This threshold is multiplied by the number of CpGs in a non-singleton event. A non-singleton event with 10 CpGs will have a threshold for being called or not called of 20.

Does it make sense to relax the threshold for non-singleton events? 

Cheers

S

**Comment by jts** [comment]
This is an open question still but I think it is fair to try to relax the threshold. You may also try to reduce the minimum distance between CpGs (—min-separation) to break up the groups as the default value of 10 is fairly conservative.

Jared

**Comment by SkabbiVML** [comment]
Thanks so much for your reply @jts, I appreciate it. I actually asked you about setting the distance parameter between CpGs previously, it was a big help as well.

**Comment by jts** [comment]
Ah my apologies, I didn't link the username between those two issues.
