### ISSUE TITLE
potential false negative in SC2 sequencing

### ISSUE THREAD

**Issue by BCArg** [jts/nanopolish#961]
I am using the  [artic pipeline](https://artic.network/ncov-2019) to call variants on corona virus sequencing. I am afraid nanopolish missed something that should have been called, as shown below:

# case 1 

![image](https://user-images.githubusercontent.com/20555037/143844237-1959c441-73f8-4400-b51d-8129c299d243.png)

The two tracks represent sequencing of the same sample. Even more puzzling is the fact that the SNP was called on the top track i.e. that of lower depth in that region.

This does not sound too intuitive to me. If this is the expected behaviour, though, what would be the explanation?

Below is the vcf entry, where the SNP was called

```
MN908947.3      21638   .       C       T       663.8   PASS    TotalReads=197;SupportFraction=0.8005;SupportFractionByStrand=0.990136,0.744358;BaseCalledReadsWithVariant=187;BaseCalledFraction=0.903382;AlleleCo
unt=1;StrandSupport=0,39,45,113;StrandFisherTest=47;SOR=0.00820477;RefContext=TACCCCCTGCA;Pool=nCoV-2019_2   GT      1
```

# case 2
Another sample was sequenced twice. The SNP was called on the sequencing with higher depth only:

![image](https://user-images.githubusercontent.com/20555037/143854271-ff39d891-38f8-4dbb-8e6c-3383e8ff7e72.png)

Although it sounds intuitive to me that the SNP should also have been called in the bottom track (depth is 156x, supported by 94% of the reads in that position).

Below is the vcf entry of the sample in which the SNP was called

```
MN908947.3      15096   .       T       C       2234.3  PASS    TotalReads=508;SupportFraction=0.843625;SupportFractionByStrand=0.925903,0.747281;BaseCalledReadsWithVariant=460;BaseCalledFraction=0.894942;Allele
Count=1;StrandSupport=20,59,254,175;StrandFisherTest=75;SOR=0.798838;RefContext=AAGAATAGAGC;Pool=nCoV-2019_1 GT      1
```

Please let me know if I should upload any other file for a better assessment.

**Comment by jts** [comment]
Hi,

Is this mutation in the *.fail.vcf file for the bottom sample?

Jared

**Comment by jts** [comment]
Thanks. Nanopolish has called variants here but they have narrowly failed an ARTIC pipeline QC check (`QUAL / TotalReads > 3` - these variants have values of 2.95 and 2.75, respectively). These positions will be masked with `N` in the consensus sequence to avoid false negatives/false positives causing issues in downstream analysis. Here's the relevant code from the artic pipeline:

https://github.com/artic-network/fieldbioinformatics/blob/master/artic/vcf_filter.py#L30

**Comment by BCArg** [comment]
Hi Jared, thanks for the reply, that clarifies. 

Not sure whether or not you were involved in this, but do you know to which sequencing depth this QC check was adapted to? We have a median sequencing depth of 428x and I was wondering if I should lower the threshold (3) a bit to (2.75 max) to accept this kind of SNPs.

**Comment by jts** [comment]
I was involved in developing these thresholds. The reason we divide by TotalReads is to make a metric that is not influenced by depth (I interpret this metric as how strongly the model supports the variant over the reference base, with higher numbers being better). Its up to you whether you change the threshold, dropping it to 2.75 is probably fairly safe.
