### ISSUE TITLE
Error with fast5 files when using nanopolish v0.13.2

### ISSUE THREAD

**Issue by arturomarin** [jts/nanopolish#966]
I am using Nanopilsh v0.13.2 on MacOS 11.6.1 inside a conda enviroment. When I try to use the nanopolish variants command I get the following error:

`HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 123145481318400:`

I add all the error to an attached file . Is there a way to solve this with this version of the program?
[Nanopolish.log](https://github.com/jts/nanopolish/files/7662838/Nanopolish.log)

**Comment by jts** [comment]
Hi,

Please see here: https://github.com/jts/nanopolish/issues/945#issuecomment-939092891

**Comment by arturomarin** [comment]
thank you very much, now it's working.
