### ISSUE TITLE
evenalign for dRNA sequencing

### ISSUE THREAD

**Issue by xieyy46** [jts/nanopolish#969]
Hi developer! To use nanopolish evenalign for dRNA,  which type of reference should I choose when using minimap2 for alignment, genome or transcriptome? Thank you, best wishes!

**Comment by jts** [comment]
Hi,

It depends on what you want to do with the data. Neither solution is perfect as the transcriptome is redundant (the same genomic k-mer may be present in multiple transcripts) and the alignment quality may be poor around splice sites when aligning to the genome.

Jared
