### ISSUE TITLE
mising function declaration for C99

### ISSUE THREAD

**Issue by YuliyaLab** [jts/nanopolish#970]
Error when running: make

cache.c:25754:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \

Seem that function declaration prototype is missing.

**Comment by jts** [comment]
Hi,

cache.c is not a nanopolish source file so I’m not sure where this error came from. Can you post the entire build log and the OS/compiler you’re using?

Jared

**Comment by YuliyaLab** [comment]
Hi, thanks for your reply. 
Using Mac with M1 chip running Big Sur. 
Below is the output from make.
Thank you!!

[make_output.txt](https://github.com/jts/nanopolish/files/7741897/make_output.txt)

**Comment by jts** [comment]
Thanks for the quick reply. It looks like the error is in `libhdf5`. I am off on holidays now but will look into this in January (hopefully).
