### ISSUE TITLE
Segment base assignment

### ISSUE THREAD

**Issue by JannesSP** [jts/nanopolish#973]
Hello,

I am wondering how I have to handle the segmentation start_idx and end_idx.
I know that multiple bases are within the pore and are measured together and now I want to look at the signal on single base resolution.
So I want to assign signal segments to single bases, is this possible?
The contig position defines the position of the first base in the event reference_kmer, as far as I understand.
Does the start_idx and end_idx describe the signal segment for the first base in the kmer as well, or does it belong to the middle base in the 5-mer in RNA mode?
And how can I interpret it in DNA mode with 6-mers?

Kind Regards, Jannes

**Comment by jts** [comment]
Hi,

I'm afraid that it is not possible to assign signals to individual bases, at least not with the way nanopolish is currently designed. Sorry I couldn't help more.

Jared
