### ISSUE TITLE
Nanopolish event align output has infinity values in standardized level

### ISSUE THREAD

**Issue by kaltinel** [jts/nanopolish#974]
Hi,

I would like to ask about the output of `nanopolish eventalign`.

Can you please explain what does `'standardized_level'` mean?
In my data, I have a lot of reads having `inf` values in that column.

Does it mean that these reads with `inf` values in their `standardized_level` column are not to be 'trusted' in their resquiggle ?

I wait to hear back from you. Thank you!

**Comment by jts** [comment]
Hi,

This is unexpected, could you paste a few examples?

Jared

**Comment by kaltinel** [comment]
Hi, 
Thanks for your reply.
Sure:
```
    position  read_index  event_level_mean  event_stdv  event_length  standardized_level
 
       kmer1    read_341         67.75                    1.882          0.00300           -1.95
       kmer1    read_341         65.06                    2.008          0.00733          -2.90
       kmer1    read_341         72.85                    2.613          0.00300          -0.15
       kmer1    read_341         95.72                    2.367          0.00733             inf
       kmer1    read_341       117.04                    3.422          0.00500             inf
       kmer1    read_341       126.08                    2.702          0.00233             inf
       kmer1    read_341       120.50                    4.172          0.00400             inf
```
This is not a rare situation unfortunately: I have ~3000 inf values in 30.000 reads.
Looking forward to your insight, Thanks!

**Comment by jts** [comment]
Are the k-mers `NNNNNN` by chance?
