### ISSUE TITLE
Somehow Nanopolish doesn't find my fast5 files. Error: no fast5 files found

### ISSUE THREAD

**Issue by ArjenB85** [jts/nanopolish#975]
Hi,

I sequenced a part of a prairie vole gene and now I want to call methylation on the reads. I sequenced and let Minknow do the fast basecalling. This resulted in fast5_pass and fast5_fail files.

I basecalled those files with Guppy (HAC mode) again:

`guppy_basecaller --input_path f5files --save_path fastq_merge --config dna_r9.4.1_450bps_hac.cfg -q 0 --num_callers 48 --chunks_per_caller 60 --gpu_runners_per_device 48
`

I combined the resulting fastq files (as suggested in the quickstart methylation guide).

`cat *.fastq > 270F.fastq`

But then, when I do:

`nanopolish index -d fast5_pass/ -d fast_5_fail/ fastq_merge/270F.fastq ` 

It says:

```
[readdb] indexing fast5_fail/
[readdb] indexing fast5_pass/
Error: no fast5 files found
```
 It creates some index files, but not all of them. If I put the raw fast5 files (both path and fail) in the same folder, the problem persists.

I hope somebody can help me figuring this out!

Thanks,
Arjen

**Comment by jts** [comment]
Hi,

You should provide the same path you've given guppy, `f5files`.

Jared

**Comment by ArjenB85** [comment]
Gotcha, I'll try. Thanks!

**Comment by ArjenB85** [comment]
Hi Jared,

I am afraid that doesn't work. It still says that it can't find the fast5 files. I had Guppy looking in a f5old folder and told nanopolish to do the same (see below), but it still says that it can't find the fast5 files. When I tried with the fastq's that came from Minknow (fast basecalling), the problem persists, so it is suspect it isn't a problem of basecalling.  

Then I was like, what happens if I add -s: 

`[readdb] num reads: 2303, num reads with path to fast5: 2`

I checked the fast5 files (HDF5-tools) and indeed they contain 2303 reads when combined. The path to the fast5 files is the same, so what am I doing wrong here? This is my nanopolish command now:

nanopolish index -d f5old/ f5new/276M.fastq -s f5new/sequencing_summary.txt 

Somehow nanopolish can't seem to find the fast5 files, but I fail to understand why...

Hope you can help me!

Arjen

**Comment by jts** [comment]
Hi,

Sorry I didn't reply to this. Did you manage to get it working?

**Comment by ArjenB85** [comment]
Hi Jared,
No problem! I got it working, so there's no pain left!
Thanks,
Arjen

**Comment by jts** [comment]
Glad to hear it, thanks.
