### ISSUE TITLE
Running methylation_frequency.py within a swarm job

### ISSUE THREAD

**Issue by coeyct** [jts/nanopolish#976]
Hi,

I currently have a swarm of jobs set up to output calls for each chromosome for a human sample to its own .tsv file.  I'd like to run the methylation_frequency.py script after this output is generated, but the tutorial page on here and the Biowulf Cluster at NIH seem to suggest running that script separately.  I'm trying to avoid installing Nanopolish directly on my computer, as I've had issues with getting updated versions of Python to work (I don't have administrator privileges anyway).  

The lines per swarm I'm running now look like the following:
`nanopolish call-methylation -r 02384_Merge.fastq -b 02384_sort.bam -g GCF_000001405.39_GRCh38.p13_genomic.fna -w "NC_000001.11" > NPchr01calls.tsv`

I'm guessing all I have to do is pipe after that command, then paste in the line for running the script with the relevant file names, but I wanted to check first if that was how the script was designed to work.  Thanks.

**Comment by jts** [comment]
Hi,

This is fine, as long as each input .tsv file is from a distinct genomic region. Once you have the frequency files for each chromosome/region, then you can merge them together if you'd like.

Jared
