### ISSUE TITLE
The fast5 file is compressed with VBZ but the required plugin is not loaded.

### ISSUE THREAD

**Issue by William-chen777** [jts/nanopolish#977]
Dear professors:
     **I try to use the polya  to calculate the length of polyA by Nanopolish software. The error occurs likes below:**
    
`HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 139904348309248:
  #000: H5Dio.c line 173 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: H5Dio.c line 550 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: H5Dchunk.c line 1872 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: H5Dchunk.c line 2902 in H5D__chunk_lock(): data pipeline read failed
    major: Data filters
    minor: Filter operation failed
  #004: H5Z.c line 1357 in H5Z_pipeline(): required filter 'vbz' is not registered
    major: Data filters
    minor: Read failed
  #005: H5PL.c line 298 in H5PL_load(): search in paths failed
    major: Plugin for dynamically loaded library
    minor: Can't get value
  #006: H5PL.c line 402 in H5PL__find(): can't open directory
    major: Plugin for dynamically loaded library
    minor: Can't open directory or file
The fast5 file is compressed with VBZ but the required plugin is not loaded. Please read the instructions here: https://github.com/nanoporetech/vbz_compression/issues/5
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 139904356701952:
  #000: H5A.c line 634 in H5Aread(): not an attribute
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 139904356701952:
  #000: H5A.c line 1582 in H5Aclose(): not an attribute
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 139904257074944:
  #000: H5A.c line 401 in H5Aopen(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 195 in H5G_loc(): invalid group ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 139904257074944:
  #000: H5A.c line 401 in H5Aopen(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 195 in H5G_loc(): invalid group ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 139904257074944:
  #000: H5G.c line 812 in H5Gclose(): not a group
    major: Invalid arguments to routine`

================================================================
And I have tried nanoporetech/vbz_compression#5
`export HDF5_PLUGIN_PATH=/home/kchen/soft/ont-vbz-hdf-plugin-1.0.1-Linux/usr/local/hdf5/lib/plugin/`

The problem is still unresolved. Can you help me?

Best~
William Chen

**Comment by jts** [comment]
Hi,

Please see here: https://github.com/jts/nanopolish/issues/932

**Comment by jts** [comment]
Hi,

For some reason the plugin is still not found. Can you confirm it is present in this directory?

```
/home/kchen/soft/ont-vbz-hdf-plugin-1.0.1-Linux/usr/local/hdf5/lib/plugin/
```

**Comment by William-chen777** [comment]
> Hi,
> 
> For some reason the plugin is still not found. Can you confirm it is present in this directory?
> 
> ```
> /home/kchen/soft/ont-vbz-hdf-plugin-1.0.1-Linux/usr/local/hdf5/lib/plugin/
> ```

I'm glad to get your reply, professor!
Yes, I‘m sure the plugin is in the directory.
And, I changed another server so I can calculate the polyA. But when I want to used "eventalign" I have another problem:

`$ nanopolish eventalign  --reads /media/shoudong/Data0/polysome-analysis/nanocount/DET-fq/totalRNA/col-0-mock-24-11-2021.nanocount.fq --bam col-0-mock-24-11-2021.nanocount.sorted.bam --genome /media/shoudong/Data0/polysome-analysis/ref/Athaliana_447_Araport11.transcript.fa --scale-events > col-0-mock-24-11-2021.eventalign.txt

[post-run summary] total reads: 258624, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 129312`

**Comment by William-chen777** [comment]
> Hi,
> 
> For some reason the plugin is still not found. Can you confirm it is present in this directory?
> 


> ```
> /home/kchen/soft/ont-vbz-hdf-plugin-1.0.1-Linux/usr/local/hdf5/lib/plugin/
> ```



> Hi,
> 
> For some reason the plugin is still not found. Can you confirm it is present in this directory?
> 
> ```
> /home/kchen/soft/ont-vbz-hdf-plugin-1.0.1-Linux/usr/local/hdf5/lib/plugin/
> ```

I extract a part of reads,  maybe the number of reads must be correspond to the fast5 file?

**Comment by hasindu2008** [comment]
Just saw this thread and thought if I could offer some help given these vbz fast5 have been troubling us every now and then

Could you do an  `ls -lh /home/kchen/soft/ont-vbz-hdf-plugin-1.0.1-Linux/usr/local/hdf5/lib/plugin/` as well as an md5sum `/home/kchen/soft/ont-vbz-hdf-plugin-1.0.1-Linux/usr/local/hdf5/lib/plugin/*`?

Also try running Nanopolish as:
`HDF5_PLUGIN_PATH=/home/kchen/soft/ont-vbz-hdf-plugin-1.0.1-Linux/usr/local/hdf5/lib/plugin/ nanopolish ......`?
