### ISSUE TITLE
Extract polished reads

### ISSUE THREAD

**Issue by AAMCgenomics** [jts/nanopolish#98]
Dear Jared, Thank you so much for your code and the time you spend writing and improving it.
I have a question, Do you have in mind to add a code to extract polished reads after they are called in the eventalign program?. They could be useful to use with further analysis, for example in my case I would like to pass them for other annotation programs to evaluate change at a.a. level.

Waiting for your comments and thank you so much or all your help with the code.

Best Regards.

**Comment by jts** [comment]
Hi,

I think there is a bit of a misunderstanding, nanopolish does not polish reads, it polishes genomes.

Jared
