### ISSUE TITLE
RNA alignment

### ISSUE THREAD

**Issue by biodlab** [jts/nanopolish#980]
I am trying to align nanopolish events for training data but I have some questions regarding the reference transcriptome positions.

It seems the reference position listed in column 2 refers to the first nucleotide in the kmer, so reference position 489 is "T", however the kmer refers to the signal for the middle nucleotide "G" which is reference position 491.

So is the nucleotide referenced  in the fast5 raw signal positions (from the last two columns) 42274-42286 actually G which is reference position 491?

```
AT1G01020.1     489     TGGGA   4       t       139     119.07  3.105   0.00398 TGGGA   113.62  4.05    1.23    42274   42286
AT1G01020.1     490     GGGAT   4       t       140     124.04  5.223   0.00863 GGGAT   124.02  3.17    0.01    42248   42274
AT1G01020.1     491     GGATG   4       t       141     131.92  1.831   0.00365 GGATG   126.02  5.10    1.06    42237   42248
```

So what to do with the beginning of the signal? It starts at reference position 446, but is this actually "A" in position 448 for the fast5 raw signal position 44640-44653?

```
AT1G01020.1     446     AGAGA   4       t       19      134.55  7.290   0.00432 AGAGA   127.71  5.69    1.10    44640   44653
```

Thanks

**Comment by jts** [comment]
Sorry for the slow reply, I've been very busy.

> reference position listed in column 2 refers to the first nucleotide in the kmer

This is correct

> however the kmer refers to the signal for the middle nucleotide "G" which is reference position 491.

I think you need to be careful with this interpretation as we don't assign the signal to individual bases, but the entire k-mer.
