### ISSUE TITLE
Long reads are not detected in nanopolish eventlalign

### ISSUE THREAD

**Issue by kaltinel** [jts/nanopolish#984]
Hi,
I am trying to use` event-align scale-events ` with `RNAs` of `100,150,1500 and 5000 bps`. (contigs corresponding to `5S,5.8S,18S and 28S`).

I use `minimap2` for alignment and the `bam` file has quite big amount of all these contigs. 
However, the `event-align` output only have `18S`... None of the other contigs are there..

Can you elaborate on how to overcome this issue please?
Thank you very much.

**Comment by jts** [comment]
Could you paste the "post-run summary" message?

Jared

**Comment by kaltinel** [comment]
Sure:
[post-run summary] total reads: 8383375, unparseable: 0, qc fail: 34730, could not calibrate: 1461914, no alignment: 179382, bad fast5: 0

**Comment by jts** [comment]
That is an incredible amount of data in `IVT_repeat`, perhaps you ran out of disk space in the first run? In any case, I'm glad you have a result now, can I close this issue?
