### ISSUE TITLE
Definitions of SUFFCLIP, NOREGION, etc in Nanopolish polyA

### ISSUE THREAD

**Issue by DepledgeLab** [jts/nanopolish#986]
Hello,

I've been trying to find specific definitions of poly(A) tail states supplied by nanopolish without any success. Could you please elaborate on the differences between ADAPTER, NOREGION, and SUFFCLIP.

I am also curious as to why some reads are flagged with READ_FAILED_LOAD. Does this imply a corruption within the fast5 file?

**Comment by jts** [comment]
These are all QC checks that we perform to make sure the alignment of the read to the reference, and the segmentation produced by the HMM, is sufficient for calling the poly-A tail length. Description of each:

- SUFFCLIP: the alignment of the read to the reference genome excludes a large amount of sequence at the 3' end of the read.
- ADAPTER: the adapter sequence detected by the HMM segmentation is excessively long
- NOREGION: the length of the ADAPTER or poly-A segments are too short

READ_FAILED_LOAD is a catch-all for any of nanopolish's fast5 I/O failure modes. This can be a bad path to fast5 files, a corrupted file (unlikely) or failure to align the signal to the basecalled read.

Jared

**Comment by DepledgeLab** [comment]
Thank you for the detailed response - this is super helpful!

Regarding SUFFCLIP, are the poly(A) length estimates associated with this likely to be accurate? The reason I ask is that one of my sequencing projects has yielded a small subset of reads in which the 5' region aligns to my target but the 3' does not. I'm concerned about possible vector contamination but this could be ruled out if I can assume there is a robust poly(A) tail present.

Tangential to this is that in a separate sequencing project I have observed a small number of reads derived from a highly abundant non-adenylated RNA. These should of course not be captured by the poly(A) Direct RNA Seq approach but I am wondering if they are sufficiently abundant that a small number might transiently traverse the nanopores. Interestingly almost all the reads assigned to this isoform are flagged with READ_FAILED_LOAD when running nanopolish. I have seen this now in multiple distinct runs (in multiple labs in multiple locations) and so I am wondering whether I can infer anything specific from the READ_FAILED_LOAD tag?

**Comment by jts** [comment]
I can't confidently say whether reads with SUFCLIP will have reliable poly-A calls. If you're interested in looking at the data more deeply, you can use the visualization scripts that @paultsw wrote to see if the segmentation looks reasonable for these reads:

https://github.com/jts/nanopolish/blob/master/scripts/polya_training/workflow.md

(the visualization commands are in the section that starts "my suggested model iteration workflow consists of the following:")

> I have seen this now in multiple distinct runs (in multiple labs in multiple locations) and so I am wondering whether I can infer anything specific from the READ_FAILED_LOAD tag?

You can debug the signal-to-read alignment by uncommenting this line then recompiling:

https://github.com/jts/nanopolish/blob/master/src/nanopolish_raw_loader.cpp#L377

It will output the read ID, and some metrics about how well the signal aligned. If you can send some examples of reads that fail to me, I can try to see why they are failing.

**Comment by jts** [comment]
I'm closing this for now, please feel free to re-open if you have any other questions
