### ISSUE TITLE
Eventalign fails with [E::sam_itr_next] Null iterator

### ISSUE THREAD

**Issue by lkwhite** [jts/nanopolish#987]
I'm trying to use event align on some direct RNA sequencing data where I've aligned to a reference for a single transcript.  Indexing appears to go fine:
`nanopolish index -d fast5_pass_singles -s out/sequencing_summary.txt out/all.fastq
[readdb] indexing fast5_pass_singles`
...
`[readdb] indexing fast5_pass_singles/2
[readdb] num reads: 282863, num reads with path to fast5: 246965`

And I get a .readdb where most reads have paths, and the paths correspond to where the fast5s live. E.g.:
`fffd5d4f-fd82-4637-8dc3-c7dc29107d50	fast5_pass_singles/7/fffd5d4f-fd82-4637-8dc3-c7dc29107d50.fast5`

When I then try to run eventalign:
`nanopolish eventalign \
    --reads all.fastq \ 
    --bam mt.mm2.ref.bam \
    --genome ref.fa \
    --scale-events > eventalign_output.txt`

I get the error 
`++ nanopolish eventalign --reads all.fastq --bam mt.mm2.ref.bam --genome ref.fa --scale-events
[E::sam_itr_next] Null iterator`
And an eventalign_output.txt file with only a header in it.

Eventalign runs fine for me on the test data _E coli_ data set. I can't seem to figure out what this error running my own data might indicate. Thoughts?

**Comment by jts** [comment]
Is it possible the bam file is empty?

**Comment by lkwhite** [comment]
Yes. This is a classic case of me seeing the problem seconds after I finished documenting the entire issue. Thanks.

**Comment by jts** [comment]
No problem, I’ll make a note to write a better error message.

Jared
