### ISSUE TITLE
Empty eventalign output & bad fast5s

### ISSUE THREAD

**Issue by lkwhite** [jts/nanopolish#988]
Hi again,

I'm revisiting running Nanopolish on [this data subset after fixing my alignment error](https://github.com/jts/nanopolish/issues/987). As before, I have no errors during indexing, and in my .readdb, the majority of reads have paths, and the paths correspond to where the fast5s live. However, I'm still getting an empty (except for header) eventalign_output file. The error message is:
`++ nanopolish eventalign --reads all.fastq --bam wt.mm2.ref.bam --genome ref.fa --scale-events
[post-run summary] total reads: 1379, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 735`
Unlike in issue [#807](https://github.com/jts/nanopolish/issues/807), this isn't exactly half of the reads, so I had no reason to suspect duplication, but grepped 5 read IDs from the .readdb file out of all.fastq just to be sure, and all of them were only present as single copies in my FASTQ file.

What should I check next?

**Comment by jts** [comment]
Could you run it with the `-vvv` (verbose) flag to see whether it prints anything useful to understanding what went wrong?

**Comment by lkwhite** [comment]
error file head
`++ nanopolish eventalign -vvv --reads all.fastq --bam wt.mm2.ref.bam --genome ref.fa --scale-events [post-run summary] 
Realigning 071885df-b14c-4154-8b54-59978324cec8 [0 0]
Realigning 7c013ff7-6e8b-4b78-9e1e-f42c9bde51a1 [0 0]
Realigning d397dce0-1a18-4ef2-b226-edb2de29ca5f [0 0]
Realigning bb867ee1-8805-4ae9-85b6-301f3cee9d83 [0 0]
Realigning beea025d-197f-42c2-b65e-db6042ae55bc [0 0]
Realigning 0ea71369-9165-4d0b-bbc7-c5f7958472d2 [0 0]
Realigning 45c0e6ae-ec21-4fae-99c5-642f2855a820 [0 0]
Realigning 33312736-920a-4a28-b845-b4ee2522468e [0 0]
Realigning ea0fa954-6284-4f52-8c83-8739651c4de5 [0 0]`

tail
`Realigning c595fc55-230d-449f-be86-eeedffea192a [0 0]
Realigning 56ec623b-34a5-45f5-8a8a-2564f837dd71 [0 0]
Realigning a3f51ab3-1d62-47e5-b748-cfa0717fe47f [0 0]
Realigning 4dbe1b02-2a8c-4eb8-af48-307f7aef5759 [0 0]
Realigning fee06b8f-600b-4dd9-b91d-66647b93f63f [0 0]
Realigning 0f510043-f276-416d-98d4-67f301e1933b [0 0]
Realigning e5ebf45b-bfb4-47fb-8957-682398110792 [0 0]
Realigning e8ff515a-142b-46c8-a96d-75dc198f86a0 [0 0]
Realigning dc2139b3-24b4-434b-b367-e7ec4168e878 [0 0]
total reads: 1379, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 735`

**Comment by jts** [comment]
The `[0 0]` part of the message means there was no signal data loaded for that read, which is odd since it indicates either there's a problem with the fast5s (which you've checked) or the initial signal-to-read alignment. If the latter case was the problem the reads should have been flagged as "qc fail". Hmm

**Comment by lkwhite** [comment]
I suspect this was an upstream processing issue. I had previously run [multi_to_single_fast5.py](https://github.com/nanoporetech/ont_fast5_api/blob/master/ont_fast5_api/conversion_tools/multi_to_single_fast5.py) and was pointing nanopolish to the fast5s output from that, rather than the original fast5 files. I went back to the original data and, with the help of [this issue & comment](https://github.com/jts/nanopolish/issues/932#issuecomment-914985515), was able to work through the remaining error messages to get eventalign working.

Thanks again for the quick responses.

**Comment by jts** [comment]
No problem, glad its resolved.
