### ISSUE TITLE
make test fails in new Docker container

### ISSUE THREAD

**Issue by nickloman** [jts/nanopolish#99]
root@ee746927d738:/zibra/nanopolish# make test
./nanopolish_test
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 139972006442944:
  #000: H5Dio.c line 173 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: H5Dio.c line 550 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: H5Dchunk.c line 1872 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: H5Dchunk.c line 2902 in H5D__chunk_lock(): data pipeline read failed
    major: Data filters
    minor: Filter operation failed
  #004: H5Z.c line 1357 in H5Z_pipeline(): required filter 'deflate' is not registered
    major: Data filters
    minor: Read failed
  #005: H5PL.c line 298 in H5PL_load(): search in paths failed
    major: Plugin for dynamically loaded library
    minor: Can't get value
  #006: H5PL.c line 402 in H5PL__find(): can't open directory
    major: Plugin for dynamically loaded library
    minor: Can't open directory or file

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
nanopolish_test is a Catch v1.1 b3 host application.
Run with -? for options

-------------------------------------------------------------------------------
hmm
-------------------------------------------------------------------------------
src/test/nanopolish_test.cpp:284
...............................................................................

src/test/nanopolish_test.cpp:284: FAILED:
due to unexpected exception with message:
  /Analyses/Basecall_2D_000/BaseCalled_template/Model: error in H5Dread

===============================================================================
test cases:   5 |   4 passed | 1 failed
assertions: 422 | 421 passed | 1 failed

Makefile:118: recipe for target 'test' failed
make: *** [test] Error 1
root@ee746927d738:/zibra/nanopolish#

**Comment by jts** [comment]
Do you need to mount the test data directory in the docker?
