### ISSUE TITLE
nanopolish consensus: ValueError: not enough values to unpack

### ISSUE THREAD

**Issue by yamkela-mg** [jts/nanopolish#991]
Hi there, 

I am trying to run the consensus module of nanopolish with the following script:

#!/bin/bash
#PBS -l select=1:ncpus=56:mpiprocs=56:mem=900GB
#PBS -l walltime=48:00:00
#PBS -q bigmem
#PBS -W group_list=bigmemq
#PBS -P CBBI1133
#PBS -o /home/ymgwatyu/lustre/000_GenomeData/01_MinION/05_polishing/medaka_long/nanopolish_consesus.out
#PBS -e /home/ymgwatyu/lustre/000_GenomeData/01_MinION/05_polishing/medaka_long/nanopolish_consesus.err
#PBS -N nanopol_cons_flye
#PBS -m abe
#PBS -M 3696167@myuwc.ac.za

module load chpc/BIOMODULES
module load nanopolish

cd /home/ymgwatyu/lustre/000_GenomeData/01_MinION/05_polishing/medaka_long

python3 /apps/chpc/bio/nanopolish/scripts/nanopolish_merge.py flye_raclong_medpolished.fasta | parallel --results nanopolish.results -P 10 \
    nanopolish variants --consensus -o polished.{1}.vcf -w {1} -r /home/ymgwatyu/lustre/000_GenomeData/01_MinION/00_runs/zcat_AllRuns-gunzip.fq -b reads.sorted.bam -g flye_raclong_medpolished.fasta -t 56 --min-candidate-frequency 0.1
------------------------------------------------------------------------------------------------------------------
I get this error:

Traceback (most recent call last):
  File "/apps/chpc/bio/nanopolish/scripts/nanopolish_merge.py", line 75, in <module>
    (contig, segment_range) = title.split(None, 1)[0].split(":")
ValueError: not enough values to unpack (expected 2, got 1)
-----------------------------------------------------------------------------------------------------------------------
Must the input draft.fa file have the range on the title? I am polishing a medaka-polished genome and the headers look something like  >contig_62794

Kindly advise what to do.

**Comment by jts** [comment]
I think you meant to run `nanopolish_makerange.py`, not `nanopolish_merge.py` in this step:

```
python3 /apps/chpc/bio/nanopolish/scripts/nanopolish_merge.py flye_raclong_medpolished.fasta
```

(FWIW I don't recommend using nanopolish on a medaka-polished genome)
