### ISSUE TITLE
why are raw signals much bigger than that from nanopolish eventalign results?

### ISSUE THREAD

**Issue by xieyy46** [jts/nanopolish#993]
Hi developer! I have noticed that the raw signals extracted from fast5 file are much bigger than the output of nanopolish eventalign(like 500 vs 95), so I' d like to know how nanopolish eventalign perform the calculation? Thank you!

**Comment by jts** [comment]
Nanopolish operates on "events" which is a segmentation of the raw signal. Therefore, there are fewer events than raw samples by roughly a factor of 5-10.
