### ISSUE TITLE
Is dna_r9.4.1_450bps_flipflop.cfg necessary for nanopolish?

### ISSUE THREAD

**Issue by BaylorLyu** [jts/nanopolish#994]
For guppy version = 5.0.16, no config file named dna_r9.4.1_450bps_flipflop.cfg. So i use rerio model res_dna_r941_min_flipflop_v001.cfg replace. Is it right config for nanopolish?

**Comment by jts** [comment]
Nanopolish has its own set of models that are different than guppy/rerio models. Generally you do not need to specify the model, it will be automatically determined from the fast5 files.
