### ISSUE TITLE
How to call methylation on secondary alignments ? (e.g. translocated elements)

### ISSUE THREAD

**Issue by fredchaux** [jts/nanopolish#996]
Hi,
Many thanks for this nice tool !

I am using nanopolish call-methylation (versions 0.13.2 and 0.13.3), which work fine for samples perfectly matching the reference genome, but I cannot find methylations in the case of structural variations (for instance, if a small portion of chromosome A has been translocated to the end of chromosome B, I can find methylations of chromosome B but not of the small part of chromosome A).

After the minimap2 and samtools sort commands, the secondary alignments can be found in the output file (I looked at the sam file, I guess it is similar in the bam), but when running the final command (nanopolish call-methylation) I don't get methylations for them.
Is there a specific command to enable calling methylations on the secondary alignment parts of the reads ?

Thank you for your attention !

Attached are a sam file, output of :
minimap2 -a -x map-ont CC-1690_17chr.fa Spacer_16_R_tel-m2-1.fastq | samtools sort -T tmp -o Spacer_16_R_tel-m2-1.sorted.sam
and the methylation file, output of :
nanopolish call-methylation -t 8 -r Spacer_16_R_tel-m2-1.fastq -b Spacer_16_R_tel-m2-1.sorted.bam -g CC-1690_17chr.fa > Spacer_16_R_tel-m2-1_methylation_calls.tsv
[2022-03-17_methylations.zip](https://github.com/jts/nanopolish/files/8327314/2022-03-17_methylations.zip)

**Comment by jts** [comment]
Try setting `--min-mapping-quality 0` in `call-methylation`.

**Comment by fredchaux** [comment]
Thank you very much, it seems to work nicely.
Have a good day,
Best regards
Fred Chaux,
Post-Doc
Sorbonne Universite/CNRS, Paris, France

Le mar. 22 mars 2022 à 20:29, Jared Simpson ***@***.***> a
écrit :
