### ISSUE TITLE
Why one coordinate has multiple methylation estimations?

### ISSUE THREAD

**Issue by ccjjhhxx** [jts/nanopolish#998]
Dear developers,

I used nanopolish to estimate methylation signals. I am confused with the results. For example, the following single coordinate has mutiple different values of methylation log_lik_ratio

**chromosome	strand	start	end	read_name	log_lik_ratio	log_lik_methylated	log_lik_unmethylated	num_calling_strands	num_motifs	sequence
1 - 24881474 24881474 d5ddadd4-9a9d-4dda-9951-02353f231ac9 -2.06 -100.69 -98.62 1 1 GACTGCGGGGC
1 + 24881474 24881474 8e11133a-ce11-4076-947a-a47ba71d138e -1.01 -124.39 -123.38 1 1 GACTGCGGGGC
1 + 24881474 24881474 0ab1d388-df68-4095-82b6-da093c314e61 -4.32 -134.73 -130.41 1 1 GACTGCGGGGC
1 + 24881474 24881474 23b2366e-2528-4d1d-ad49-08043ae50788 -4.29 -103.34 -99.05 1 1 GACTGCGGGGC
1 + 24881474 24881474 a0a0825a-9627-4e05-ac55-89c0619eef42 -18.60 -204.68 -186.08 1 1 GACTGCGGGGC
1 - 24881474 24881474 b4d59999-3402-43bb-8319-447b6e4ce27b -3.78 -150.84 -147.07 1 1 GACTGCGGGGC
1 - 24881474 24881474 b4bc8385-b647-41f6-b514-4196a9c9300e -1.05 -101.45 -100.40 1 1 GACTGCGGGGC
1 + 24881474 24881474 aba96d46-f3ac-431e-aa44-bd139970d861 -6.01 -210.20 -204.19 1 1 GACTGCGGGGC
1 + 24881474 24881474 b4bc8385-b647-41f6-b514-4196a9c9300e 0.87 -132.89 -133.76 1 1 GACTGCGGGGC
1 + 24881474 24881474 bce58f4a-b059-4c40-a1fc-e813367e7fe6 -3.30 -139.91 -136.62 1 1 GACTGCGGGGC
1 + 24881474 24881474 e1724bea-a327-4f88-850c-d01592e7e4b2 -3.56 -86.71 -83.15 1 1 GACTGCGGGGC
1 - 24881474 24881474 5958d8f0-66a2-4001-8463-8c5362fa71c1 -2.09 -160.32 -158.23 1 1 GACTGCGGGGC
1 + 24881474 24881474 b68379b6-f8a1-4066-93fe-a0f4bdd338e6 3.82 -111.85 -115.67 1 1 GACTGCGGGGC
1 - 24881474 24881474 72083bab-e931-486f-b75d-caa942b9cdff -1.53 -106.07 -104.55 1 1 GACTGCGGGGC
1 - 24881474 24881474 bbb5fee5-8ec8-4c4b-a05b-4e4b66925fb4 -1.46 -103.79 -102.33 1 1 GACTGCGGGGC
1 - 24881474 24881474 3406ff40-2767-499d-a8ab-17989c4c1c91 -3.90 -115.51 -111.61 1 1 GACTGCGGGGC
1 - 24881474 24881474 f162d4e6-3651-41d1-81fe-33c6a145bab6 -1.19 -147.55 -146.36 1 1 GACTGCGGGGC
1 - 24881474 24881474 40fab30c-41b2-44e0-869c-e5b33b6d971e -5.52 -134.29 -128.77 1 1 GACTGCGGGGC
1 + 24881474 24881474 c1217460-3443-4d61-afd4-5c8110437374 -2.77 -182.46 -179.68 1 1 GACTGCGGGGC
1 + 24881474 24881474 83839930-7e76-44c0-80a7-f967984d8811 -5.69 -82.73 -77.04 1 1 GACTGCGGGGC
1 - 24881474 24881474 c7c2b3b7-0c73-499c-8698-fd35f51b9dc1 -4.19 -152.78 -148.59 1 1 GACTGCGGGGC
1 - 24881474 24881474 26c7babe-7ed0-4bc3-bd30-73cb50b0f7ce -4.50 -91.17 -86.67 1 1 GACTGCGGGGC
1 + 24881474 24881474 1921b96f-9524-4158-988a-03ad247cd33b -3.38 -167.62 -164.24 1 1 GACTGCGGGGC
1 - 24881474 24881474 8d40e3c5-355f-4ec0-9da9-7b14a5f567f2 0.82 -216.48 -217.30 1 1 GACTGCGGGGC**

My question is that is this result normal ? If yes, which value should I choose? mean, sum, or median ?

All the best,

Jh c

**Comment by jts** [comment]
`nanopolish call-methylation` makes per-read methylation calls. You can use the script `scripts/calculate_methylation_frequency.py` to summarize the calls per reference position.
